AudiusProject/audius-client

- packages/web/src/components/upload/UploadChip.module.css
Margin was unnecessary
Tested w/ artist pick too
> Fix margin issue

- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/web/package-lock.json
- packages/web/package.json
> Update @audius/sdk to 0.0.38

- packages/web/src/common/services/audius-api-client/AudiusAPIClient.ts
Removes logs added by mistake in the eager-load-util refactor
> Remove eager discprov logs

- packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.module.css
> [PAY-438] Fix Twitter icon fill color in matrix mode

- packages/mobile/src/services/audius-backend-instance.ts
- packages/web/package-lock.json
- packages/web/package.json
pairs with https://github.com/AudiusProject/audius-protocol/pull/3734/files
> Add entity manager address to configInternalWeb3

- packages/mobile/package-lock.json
- packages/web/package-lock.json
- packages/web/package.json
- Updates @solana/web3.js to 1.53.0 to be compatible with Jupiter's deps peer deps
- Updates Coinbase Pay sdk to latest
> Update @coinbase/cbpay-js to v1.2.0 and @solana/web3.js to 1.53.0

- packages/stems/src/components/RadioPillButton/RadioPillButton.module.css
- packages/web/src/components/coinbase-pay-button/CoinbasePayButtonCustom.module.css
- packages/web/src/components/coinbase-pay-button/CoinbasePayButtonCustom.tsx
- packages/web/src/components/toggle-collapse-button/ToggleCollapseButton.module.css
- packages/web/src/components/toggle-collapse-button/ToggleCollapseButton.tsx
- packages/web/src/components/toggle-collapse-button/index.ts
- packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css
- packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
See commit messages.
https://user-images.githubusercontent.com/3690498/186288430-5c45f6a7-e8a1-4916-a2f2-b8e2f9d5a623.mov
> [PAY-575] [PAY-574] [PAY-573] [PAY-572] [PAY-581] Coinbase Pay Button and Rewards Page Fixes

- packages/common/src/store/queue/index.ts
- packages/common/src/store/queue/selectors.ts
- packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
- packages/web/src/components/lineup/hooks.ts
- packages/web/src/components/nav/desktop/NavColumn.tsx
- packages/web/src/components/now-playing/NowPlaying.tsx
- packages/web/src/components/play-bar/desktop/PlayBar.js
- packages/web/src/components/play-bar/mobile/PlayBar.tsx
- packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
- packages/web/src/pages/collection-page/CollectionPageProvider.tsx
- packages/web/src/pages/collection-page/store/lineups/tracks/sagas.js
- packages/web/src/pages/deleted-page/DeletedPageProvider.tsx
- packages/web/src/pages/feed-page/FeedPageProvider.js
- packages/web/src/pages/history-page/HistoryPageProvider.tsx
- packages/web/src/pages/profile-page/ProfilePageProvider.tsx
- packages/web/src/pages/remixes-page/RemixesPageProvider.tsx
- packages/web/src/pages/saved-page/SavedPageProvider.tsx
- packages/web/src/pages/search-page/SearchPageProvider.js
- packages/web/src/pages/track-page/TrackPageProvider.tsx
- packages/web/src/pages/trending-page/TrendingPageProvider.js
- packages/web/src/pages/visualizer/VisualizerProvider.tsx
- packages/web/src/store/lineup/sagas.js
- packages/web/src/store/queue/mobileSagas.ts
- packages/web/src/store/queue/sagas.ts
Migrates queue selectors now that player is in common
> Migrate queue selectors to common

- packages/stems/src/components/Modal/ModalContentPages.module.css
- packages/stems/src/components/Modal/ModalContentPages.stories.tsx
- packages/stems/src/components/Modal/ModalContentPages.tsx
- packages/stems/src/index.tsx
Allows for non-fixed page sizes in ModalContentPages:
https://user-images.githubusercontent.com/3690498/186515731-dc444380-7187-400b-b279-baaa36656f05.mov
Tested on storybook. Notably this component is not used anywhere (yet)
> Dynamically resize ModalContentPages

- packages/web/src/components/buy-audio-modal/components/InProgressPage.tsx
- packages/web/src/components/collapsible-content/index.ts
#1783 Accidentally renamed the css and didn't change the import or symbol name
> Fix bug with renamed component

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/web/src/services/audius-backend/BuyAudio.ts
- packages/web/src/services/audius-backend/waudio.ts
- packages/web/src/store/application/ui/buy-audio/sagas.ts
Renamed to getTokenAccountInfo and deriveUserBank.
Tested by sending WAudio to external wallet and confirming user balance was correct.
> [PAY-44] Rename getAssociatedTokenAccountInfo and getUserBank

- packages/mobile/src/components/navigation-container/NavigationContainer.tsx
Fix deep link to settings screen
https://user-images.githubusercontent.com/2731362/186780576-c445580a-756c-46c3-a44e-6e577db5445a.mp4
> [C-817] Deep link /settings on mobile

- packages/common/package.json
Start watch script for common (merged into native-reloaded branch)
> Add packages/common start cmd

- packages/web/src/components/buy-audio-modal/BuyAudioModal.tsx
Brings all the pages together of the BuyAudioModal!
Tested by manually dispatching actions to switch pages.
> Add all the pages to the BuyAudioModal

- packages/stems/src/components/Button/Button.stories.tsx
Adds a story for the `ButtonType.TEXT`
> Add ButtonType.TEXT story

- packages/common/src/store/ui/buy-audio/selectors.ts
- packages/common/src/store/ui/buy-audio/slice.ts
- packages/web/src/components/buy-audio-modal/components/InProgressPage.module.css
- packages/web/src/components/buy-audio-modal/components/InProgressPage.tsx
- packages/web/src/store/application/ui/buy-audio/sagas.ts
Tested by manually using the actions in redux
> [PAY-589] Add error UI to InProgress page of BuyAudio modal

- packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
- packages/web/src/common/store/lineup/sagas.d.ts
- packages/web/src/common/store/player/sagas.ts
Case where our stricter mobile types were complaining about web code recently introduced
> Fix lineup types in mobile build

- packages/mobile/src/screens/trending-screen/TrendingFilterButton.tsx
- packages/mobile/src/screens/trending-screen/TrendingFilterDrawer.tsx
- packages/mobile/src/screens/trending-screen/TrendingLineup.tsx
- packages/mobile/src/screens/trending-screen/TrendingScreen.tsx
- packages/mobile/src/store/sagas.ts
Add trending page sagas to mobile
Replace all usages of useSelectorWeb and dispatchWeb
> [C-917] Add native trending screen

- packages/common/src/store/reducers.ts
- packages/common/src/store/ui/index.ts
- packages/common/src/store/ui/modals/slice.ts
- packages/common/src/store/ui/modals/types.ts
- packages/common/src/store/ui/transaction-details/selectors.ts
- packages/common/src/store/ui/transaction-details/slice.ts
- packages/common/src/store/ui/transaction-details/types.ts
[Notion notes](https://www.notion.so/audiusproject/On-ramp-notes-92eaf6b5f6534489b235d6ed735d1486#202e32d21a144f5b97a577adfcaa831c)
See also: https://github.com/AudiusProject/audius-protocol/pull/3773
- Adds slice to the redux store to manage the `TransactionDetails` needed to populate the `TransactionDetailsModal`
- Also add `TransactionDetails` as a modal type
N/A
Using the console/redux dev tools
N/A
*Are all new features properly feature flagged? Describe added feature …
> [PAY-590] Add Transaction Details to Store

- packages/mobile/src/components/drawer/AppDrawer.tsx
- packages/mobile/src/screens/app-screen/FavoritesTabScreen.tsx
- packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
- packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
- packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
- packages/mobile/src/screens/favorites-screen/TracksTab.tsx
- packages/mobile/src/screens/favorites-screen/index.ts
- packages/mobile/src/store/sagas.ts
Adds fully native favorites screen
> [C-931] Fully native favorites screen

- packages/mobile/src/components/audio-rewards/RewardsBanner.tsx
- packages/mobile/src/components/feed-filter-drawer/FeedFilterDrawer.tsx
- packages/mobile/src/components/lineup-tile/CollectionTile.tsx
- packages/mobile/src/components/lineup-tile/TrackTile.tsx
- packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
- packages/mobile/src/components/overflow-menu-drawer/CollectionOverflowMenuDrawer.tsx
- packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
- packages/mobile/src/components/overflow-menu-drawer/ProfileOverflowMenuDrawer.tsx
- packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
- packages/mobile/src/components/share-drawer/ShareDrawer.tsx
- packages/mobile/src/components/track-list/TrackListItem.tsx
- packages/mobile/src/components/trending-rewards-drawer/TrendingRewardsDrawer.tsx
- packages/mobile/src/screens/feed-screen/FeedFilterButton.tsx
- packages/mobile/src/screens/feed-screen/FeedScreen.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
- packages/mobile/src/screens/trending-screen/TrendingFilterButton.tsx
- packages/mobile/src/store/sagas.ts
Updates opening/closing of all drawers through native store
Updates feed drawer, trending drawer, share drawer, overflow menu open requests
(Drawer opening is so fast now!!!)
> [C-929] Add fully native drawers

- packages/mobile/src/components/lineup-tile/TrackTile.tsx
- packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
- packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
- packages/mobile/src/components/overflow-menu-drawer/ProfileOverflowMenuDrawer.tsx
- packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
- packages/mobile/src/components/user/FollowButton.tsx
- packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
- packages/mobile/src/store/sagas.ts
Ensures all social actions are dispatched in native store context
These actions appear to be failing, need to check that these issues are resolved by https://github.com/AudiusProject/audius-protocol/pull/3788
> [C-933] Add fully native social actions

- packages/mobile/src/screens/user-list-screen/FavoritedScreen.tsx
- packages/mobile/src/screens/user-list-screen/FollowersScreen.tsx
- packages/mobile/src/screens/user-list-screen/FollowingScreen.tsx
- packages/mobile/src/screens/user-list-screen/MutualsScreen.tsx
- packages/mobile/src/screens/user-list-screen/NotificationUsersScreen.tsx
- packages/mobile/src/screens/user-list-screen/RepostsScreen.tsx
- packages/mobile/src/screens/user-list-screen/SupportingUsersScreen.tsx
- packages/mobile/src/screens/user-list-screen/TopSupportersScreen.tsx
- packages/mobile/src/screens/user-list-screen/UserList.tsx
- packages/mobile/src/screens/user-list-screen/UserListItem.tsx
- packages/mobile/src/screens/user-list-screen/UserListScreen.tsx
- packages/mobile/src/screens/user-list-screen/UserListTitle.tsx
- packages/mobile/src/store/sagas.ts
- packages/web/src/store/sagas.ts
Adds fully native user lists
Fixes NotificationUsersLists header
> [C-934] Add fully native user lists

- packages/stems/src/components/SegmentedControl/SegmentedControl.module.css
Fixes segmented-control font color to be neutral
> [C-703] Fix segmented control font color

- packages/web/src/components/search/SearchBar.js
Fixes case where pressing enter in search bar does not send user to search page
> [C-836] Fix enter on search

- packages/mobile/src/components/deactivate-account-confirmation-drawer/DeactivateAccountConfirmationDrawer.tsx
- packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
- packages/web/src/pages/deactivate-account-page/DeactivateAccountPage.tsx
> Update deactivate copy

- packages/web/src/components/search-bar/store/sagas.ts
* Allows autocomplete to work when the user is not signed in
> [C-957] Fix autocomplete when signed out

- packages/web/src/components/test-table/TestTable.module.css
- packages/web/src/components/test-table/TestTable.tsx
- packages/web/src/components/test-table/components/OverflowMenuButton.tsx
- packages/web/src/components/test-tracks-table/TestTracksTable.tsx
- packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Adding reordering to the new tables
Has the current animation for dragging with moving rows, but need to speak with design about the line between rows
manually tested
N/A
N/A
> Add reordering to new tables for playlists

- packages/mobile/src/store/sagas.ts
- packages/web/src/common/store/wallet/sagas.ts
- packages/web/src/store/sagas.ts
* Migrate wallet sagas to web/common
Considered moving `BuyAudio` service because there was a small (recent) dependency on it, but bc that feature is currently in flight and not being rolled out to mobile initially I decided to just copy a small amount of code into the wallet saga directly
> [C-963] Migrate wallet sagas

- packages/web/src/common/store/wallet/sagas.ts
Send $AUDIO flow was broken after wallet saga migration.
Tested on local web.
> Fix send $AUDIO flow after saga migration

- .circleci/src/jobs/@web-jobs.yml
See https://github.com/electron-userland/electron-builder/issues/4741
> [C-914] Fix windows build

- packages/web/src/components/notification/Notification/components/ProfilePicture.tsx
- packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css
Implement Julian's QA feedback
- Border around profile picture
- Remove wrapping for now
Tested on local web
https://user-images.githubusercontent.com/3893871/188964215-052bc56e-ca48-4e3a-8280-5b0610fd2215.mov
> Update feed tip tile per QA feedback

- packages/common/package.json
- packages/eslint-config-audius/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/stems/package.json
- packages/web/package-lock.json
- packages/web/package.json
This enables tipping on native mobile
Merging into `native-reloaded` because we are about to merge back into main anyway
> Consume @audius/sdk@1.0.4

- packages/mobile/src/screens/root-screen/RootScreen.tsx
- packages/web/src/services/WebWorker.js
- Hotfixes breaking issue on testflight due to missing Worker which is injected with chrome debugger, classic....
- Adds splash-screen to initial load. there is still a long blank white section, but its better than rendering the sign-up screen
> [C-1006] Improve initial load, hotfix missing web worker

- packages/common/src/store/pages/audio-rewards/slice.ts
- packages/web/src/common/store/cache/collections/sagas.js
Implements optimistic claiming for first-playlist challenge.
Tested on local mobile + web against staging.
Playlist challenge is already behind a feature flag.
> [PAY-625] Playlist challenge optimistic claiming

- packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
* Reset profile screen state on cleanup
> [C-1001] Fix lineup state persisting across profile screens

- packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
> [C-1014] Fix edit profile screen

- packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
> [C-1009] Fix misaligned social icons

- packages/common/src/hooks/useSelectTierInfo.ts
- packages/mobile/src/components/enable-push-notifications-drawer/EnablePushNotificationsDrawer.tsx
* Fixes a couple issues I caused due to yolomerging
* Very strange type issue with `BadgeTier` resolving to `any` in web & mobile, was able to fix by using relative path for models in common
> Fix failing CI init

- packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
Improves bottom-bar performance by removing delay that we needed when we had  to deal with web-app syncing
> [C-1026] Improve bottom-bar perf

- packages/mobile/src/components/core/PullToRefresh.tsx
- packages/mobile/src/components/lineup/Lineup.tsx
- packages/mobile/src/components/lineup/types.ts
- packages/mobile/src/screens/feed-screen/FeedScreen.tsx
- packages/mobile/src/screens/trending-screen/TrendingLineup.tsx
Fixes pull-to-refresh infinite loader
Also (potentially) improves api by building pull-to-refresh into the lineup, so consumers don't need to re-implement everything.
> [C-1029, C-1036] Fix pull-to-refresh

- packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
Fixes blank edit-profile screen. Weirdly updates are not happening consistently on staging, which im thinking may just be related to stage env, since it's also failing on web.
> [C-1057] Fix blank edit-profile screen

- packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
- packages/mobile/src/screens/profile-screen/selectors.ts
Fixes crash when navigating to a profile from search screen. Also improves account fetch by referencing params.handle if available
> [C-1050] Fix profile search crash

- packages/mobile/src/store/theme/sagas.ts
Ensures ios status icons have correct contrast for light/dark mode
> [C-1053] Fix ios status color in dark/light modes

- packages/mobile/src/screens/profile-screen/ProfileHeader/ExpandHeaderToggleButton.tsx
Improves profile header expand button's touch target
> [C-1031] Improve profile expand section touch target

- packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
Fade in socials links on user screen.
iOS simulator against staging
https://user-images.githubusercontent.com/3893871/189959377-7313fa16-f84c-4be6-8092-fbcb828bd509.mp4
> [PAY-578] Fade in socials on mobile user screen

- packages/web/src/pages/check-page/CheckPage.tsx
Same issue as 
https://github.com/AudiusProject/audius-client/commit/00810b2cebd37ee3f60d1d9dff471eb060d79165
Locally vs. prod. Need to verify on staging b/c of CORS issues w/ cognito API, but should be good
> [C-1060] Fix /check page

- packages/common/src/store/pages/track/reducer.ts
- packages/mobile/src/screens/track-screen/TrackScreen.tsx
- packages/web/src/common/store/pages/track/sagas.js
Fix the more by artist lineup not loading. The issue was that the request needed the track permalink and artist handle which mobile wasn't passing in.
Also fixes a subsequent issue where the lineup wasn't resetting.
> [Reloaded] [C-1017] Fix more by artist lineup

- packages/mobile/src/App.tsx
- packages/mobile/src/components/enable-push-notifications-drawer/EnablePushNotificationsDrawer.tsx
- packages/mobile/src/components/notification-reminder/NotificationReminder.tsx
- packages/mobile/src/store/settings/sagas.ts
We were no longer requesting permissions
Locally on simulator to the best of my ability, but will need a pass on the testflight app because push notifications don't get delivered to the simulator
> [C-907] Fix react native push notifications

- packages/mobile/README.md
Removes web build/copy instructions in mobile readme.
> Update mobile readme install instructions

- packages/common/package-lock.json
- packages/common/package.json
- packages/eslint-config-audius/package-lock.json
- packages/eslint-config-audius/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/stems/package-lock.json
- packages/stems/package.json
- packages/web/package-lock.json
- packages/web/package.json
> Upgrade SDK to 1.0.5

- packages/web/src/common/store/pages/signon/sagas.js
Make sure action callbacks exist before calling them.
None
> Fix broken signup on web

- packages/mobile/ios/Podfile.lock
- packages/mobile/src/screens/app-screen/AppScreen.tsx
Trying out this new feature now that we don't need to have to deal with web navigation! Main thing to watch out for is perf going across bottom-tab bars
> [C-296] Persist stack history across bottom tabs

- packages/mobile/src/ErrorBoundary.tsx
- packages/mobile/src/types/analytics.ts
> Send Amplitude event when app crashes

- packages/common/src/services/remote-config/feature-flags.ts
Add feature flag for offline mode
N/A
N/A
N/A
Yep.
> [C-1067] Add feature flag for offline mode

- .circleci/src/jobs/@web-jobs.yml
Not sure why these never made it, I updated the images for these jobs to `cimg/python:3.7.12-node` to allow this to work but never actually called the command 🤦 
> Upload sourcemaps for prod and release-candidate

- packages/web/src/components/notification/Notification/components/EntityLink.module.css
- packages/web/src/components/notification/Notification/components/UserNameLink.module.css
> [PAY-428] Wrap link text in notifications

- packages/web/src/components/test-tracks-table/TestTracksTable.module.css
Quick update to fix the hover state of artist names on the new tables.
N/A
N/A
N/A
> [C-867] Fix hover state for the new tables

- packages/mobile/src/screens/profile-screen/selectors.ts
Fixes useProfileSelectorRoot return
> Fix native profile render

- packages/web/src/common/store/pages/saved/sagas.js
- packages/web/src/components/test-table/TestTable.module.css
- packages/web/src/components/test-table/TestTable.tsx
- packages/web/src/pages/saved-page/components/desktop/SavedPage.module.css
Fix font-size, row height, and table width for QA issues
N/A
Manual testing
N/A
N/A
> [C-1103, C-1105, C-1106] Fix new table styling

- packages/web/src/components/buy-audio-modal/BuyAudioModal.tsx
- packages/web/src/components/buy-audio-modal/components/AudioAmountPicker.module.css
- packages/web/src/components/buy-audio-modal/components/AudioAmountPicker.tsx
- packages/web/src/components/buy-audio-modal/components/CoinbaseBuyAudioButton.tsx
- packages/web/src/components/transaction-details-modal/components/TransactionPurchaseMetadata.module.css
- packages/web/src/components/transaction-details-modal/components/TransactionPurchaseMetadata.tsx
- packages/web/src/store/application/ui/buy-audio/sagas.ts
See commits. Likely review by commit
- [PAY-641](https://linear.app/audius/issue/PAY-641/dont-show-the-disabled-button-state-when-you-start-the-coinbase-flow)
- [PAY-633](https://linear.app/audius/issue/PAY-633/modal-should-be-dismissable-when-an-error-occurs)
- [PAY-639](https://linear.app/audius/issue/PAY-639/lets-make-sure-we-format-our-token-name-as-dollaraudio)
- [PAY-642](https://linear.app/audius/issue/PAY-642/missing-the-ui-that-shows-the-units-of-the-quick-select-value-buttons)
- [PAY-643](https://linear.app/audius/issue/PAY-643/missing-the-ui-that-shows-the-currency-in-the-transaction-details)
*Please describe the tests that you ran to verify your changes. …
> [PAY-634] On Ramp Design Fixes (Part 1)

- packages/mobile/src/screens/app-screen/AppTabScreen.tsx
- packages/mobile/src/screens/search-screen/content/SearchItem.tsx
- packages/mobile/src/screens/track-screen/TrackScreen.tsx
Fix bug where track screen would not load if it was navigated to from the search result screen.
> Fix search result -> track screen bug [C-1124]

- packages/web/src/components/test-tracks-table/TestTracksTable.module.css
- packages/web/src/components/test-tracks-table/TestTracksTable.tsx
Quick one to have the table action buttons appear in the same spot when buttons are missing
N/A
N/A
N/A
> [C-863] Update new table styles for table action buttons

- packages/common/src/store/ui/artist-recommendations/selectors.ts
- packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
- packages/mobile/src/store/sagas.ts
- packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
- packages/web/src/pages/profile-page/ProfilePageProvider.tsx
- Fixes missing native artist-recommendations
- Improves perf by using proxy-selector here
> [C-976] Fix native artist-recommendations

- packages/web/src/components/test-table/TestTable.tsx
- packages/web/src/components/test-tracks-table/TestTracksTable.tsx
* Fix table action button tooltip glitch
* Fix header tooltip alignment
* Remove length sorter for virtualized track tables
* Adjust column widths
N/A
N/A
N/A
> [C-1141, C-1142, C-1143, C-1144] Update new table styles for qa issues

- packages/common/src/store/pages/audio-rewards/slice.ts
- packages/web/src/common/store/cache/collections/sagas.js
Ensure specifier is always passed for optimistic challenges
> Fix playlist challenge optimistic update

- packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
- packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
- packages/mobile/src/screens/favorites-screen/TracksTab.tsx
- packages/mobile/src/screens/favorites-screen/selectors.ts
- packages/mobile/src/screens/favorites-screen/types.ts
Improves favorites tab performance with custom collection selectors and use of useProxySelector
Cuts down re-renders by 3x
> [C-1152] Improve favorites tab performance

- packages/mobile/src/components/overflow-menu-drawer/CollectionOverflowMenuDrawer.tsx
> [c-1104] Fix playlist link in tile overflow menu

- packages/web/src/pages/search-page/components/desktop/SearchPageContent.js
More results wasn't working. Not sure why we added this here:
https://github.com/AudiusProject/audius-client/pull/1883/files#diff-b1ae8d6e6e22d43c39e967461d7c9fe84e8feab81a6649645ac7df5e48da0653
> [C-1162] Remove trimtoalphanumeric on search web

- packages/mobile/src/screens/search-results-screen/tabs/TracksTab.tsx
- packages/web/src/common/store/pages/search-page/lineups/tracks/sagas.js
🤦 
Double checked search in web and mobile
> Fix tag search more results

- packages/mobile/src/screens/favorites-screen/selectors.ts
> Fix mobile favorites c-831

- packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
FIxes issue where opening search on trending and then feed results in "search" getting stacked double in trending. This was due to a stale navigator.
> [C-1160,C-1161] Fix search navigation

- packages/common/src/services/remote-config/feature-flags.ts
- packages/web/src/common/store/social/users/sagas.ts
Add feature flag for auto sub.
Locally by manually enabling on both web & mobile.
> [PLAT-98] Add feature flag for auto sub

- packages/mobile/src/screens/profile-screen/ProfileHeader/TopSupporters.tsx
- packages/mobile/src/screens/track-screen/TrackScreen.tsx
Fix TopSupporters runtime error when more than 6 supporters
Fix TrackScreen lineup cache issues (track screen lineups dont reset)
> Fix TopSupporters, TrackScreen caching

- packages/mobile/index.js
- packages/mobile/ios/Podfile.lock
- packages/mobile/package-lock.json
- packages/mobile/package.json
Trying out experimental `react-native-screens` feature that prevents rerenders occuring on screens that are not focused. This should help with nested navigators, and bottom-bar navigation history!
Let's see if this causes any weird caching bugs
> [C-1172] Add screen freeze

- packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
- packages/mobile/src/screens/app-screen/AppTabBar.tsx
Fixes issue where navigator in now-playing was not referring to bottom-bar navigator, leading to similar issues that search had.
> Fix now-playing navigation

- packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
- packages/mobile/src/screens/profile-screen/SubscribeButton.tsx
Fixes issues with profile screen follow-button, subscribe-button, and edit-profile button not rending quick enough, leading to weird toggling and disappearance.
> [C-1156, C-1055, C-1159] Fix profile follow button

- packages/mobile/src/components/feed-tip-tile/SendTipButton.tsx
- packages/mobile/src/screens/profile-screen/TipAudioButton.tsx
Fixes tipping header and tipping flow due to missing user data. relying on `useProfile` was incorrect because that removes all elements that are not specifically requested in the dependencies
> [C-1167,C-1171] Fix missing tip data, fix tipping

- packages/mobile/src/components/lineup-tile/CollectionTile.tsx
- packages/mobile/src/components/lineup-tile/TrackTile.tsx
- packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
- packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
- packages/mobile/src/components/overflow-menu-drawer/CollectionOverflowMenuDrawer.tsx
- packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
- packages/mobile/src/components/track-list/TrackListItem.tsx
- packages/mobile/src/hooks/usePopToTopOnDrawerOpen.ts
- packages/mobile/src/screens/app-screen/AppTabNavigationProvider.tsx
- packages/mobile/src/screens/app-screen/index.ts
- packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
- packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
- packages/mobile/src/screens/root-screen/RootScreen.tsx
- Fixes issues with navigation in context outside the bottom-bar tabs
- Removes redundant overflow menu options
> [C-1150, C-1165] Fix app-tab navigation

- packages/web/package.json
Fix bad rebase merged in https://github.com/AudiusProject/audius-client/pull/1577
```
npm run start:dev
```
> Fix start:dev command

- packages/common/package-lock.json
- packages/common/package.json
- packages/eslint-config-audius/package-lock.json
- packages/eslint-config-audius/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/stems/package-lock.json
- packages/stems/package.json
- packages/web/package-lock.json
- packages/web/package.json
Upgrade SDK. 
Needed for feeling lucky change.
https://github.com/AudiusProject/audius-client/pull/1954
> Upgrade sdk 1.0.6

- packages/mobile/src/components/web-app-account-sync/WebAppAccountSync.tsx
> Cast port to number

- packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
- packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
Fixes collection screen track list loading issues. Essentially we weren't reseting collection state when entering a new collection screen.
> [C-1164] Fix collections screen loading issues

- packages/mobile/src/components/co-sign/CoSign.tsx
- packages/mobile/src/components/details-tile/DetailsTile.tsx
- packages/mobile/src/screens/track-screen/TrackScreen.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
> [C-1157] Fix remix cosign icon position

- packages/common/src/store/lineup/actions.ts
- packages/common/src/store/lineup/reducer.ts
- packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
- packages/mobile/src/screens/profile-screen/RepostsTab.tsx
- packages/web/src/common/store/pages/profile/lineups/feed/sagas.js
Fixes issue where reposting/unreposting tracks/collections does not update the user's reposts lineup
> [C-1170] Optimistically add/remove reposted tracks/collections

- packages/common/src/services/explore/Explore.ts
I merged too fast and it failed the typecheck in CI. userId can be null since user does not need to be logged in for feeling lucky.
> Fix feeling lucky param type

- packages/mobile/src/components/web-app-account-sync/WebAppAccountSync.tsx
> Fix static server crash

- packages/common/src/store/lineup/actions.ts
- packages/common/src/store/pages/profile/actions.ts
- packages/common/src/store/pages/profile/reducer.ts
- packages/web/package-lock.json
- packages/web/src/common/store/lineup/sagas.js
- packages/web/src/common/store/pages/profile/lineups/feed/sagas.js
- packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
- packages/web/src/common/store/profile/sagas.js
- packages/web/src/hooks/useTabs/useTabs.tsx
- packages/web/src/pages/profile-page/ProfilePageProvider.tsx
Fixes desktop profile state by ensuring the ProfilePageProvider dispatches actions with the current user's handle
> [C-1194] Fix desktop profile state

- packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
Copied what we do in web
Before - 
Add track to playlist -> choose new playlist -> go to that new playlist -> playlist modified date says "invalid date"
After - 
Fixed
> Fix "invalid date" on new (temp) playlists made via "Add track to playlist" c-1126

- packages/mobile/src/components/feed-tip-tile/FeedTipTile.tsx
- packages/mobile/src/components/feed-tip-tile/FeedTipTileSkeleton.tsx
- packages/mobile/src/components/feed-tip-tile/ReceiverDetails.tsx
- packages/mobile/src/components/feed-tip-tile/SenderDetails.tsx
https://user-images.githubusercontent.com/2731362/192989386-37de4e9d-2e09-4b71-b514-98b4a41e8c92.mp4
> [C-1197] Custom skeleton for feed tip tile

- packages/common/package-lock.json
- packages/common/package.json
- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/common/src/services/remote-config/feature-flags.ts
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/stems/package-lock.json
- packages/stems/package.json
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
Adds user entity manager option to libs via env var
NOTE: waiting on libs version bump
e2e manually and locally
> User entity manager

- .gitignore
- packages/common/src/store/account/types.ts
- packages/common/src/utils/fileUtils.ts
- packages/mobile/src/components/core/FormImageInput.tsx
- packages/mobile/src/screens/edit-playlist-screen/CreatePlaylistScreen.tsx
- packages/mobile/src/screens/edit-playlist-screen/RandomImageButton.tsx
- packages/mobile/src/screens/signon/ProfileAuto.tsx
- packages/mobile/src/screens/signon/ProfileManual.tsx
- packages/mobile/src/utils/launchSelectImageActionSheet.ts
- packages/web/src/common/store/cache/collections/sagas.js
- packages/web/src/common/store/pages/signon/actions.ts
This was v terrible. I think the issues were 1) `atob` not working out of browser env and 2) blobs and files behaving differently in native.
Getting a weird error now after unlinking libs and detaching the debugger when trying to do the  random image upload.  
`NSURLErrorDomain error code -1000`
Sigh, going to try testing on device
> Fix image uploads in new native

- packages/common/package-lock.json
- packages/common/package.json
- packages/eslint-config-audius/package-lock.json
- packages/eslint-config-audius/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/stems/package-lock.json
- packages/stems/package.json
- packages/web/package-lock.json
- packages/web/package.json
Needed for client to have libs change from
https://github.com/AudiusProject/audius-protocol/pull/3965
> Upgrade sdk 1.0.8

- .circleci/src/jobs/@web-jobs.yml
- packages/web/src/pages/sign-on/components/mobile/ProfilePage.tsx
> Add cypress prober videos to artifacts C-1011

- packages/mobile/.env.dev
- packages/mobile/ios/AudiusReactNative/Info.plist
- packages/mobile/src/components/oauth/OAuth.tsx
- packages/mobile/src/screens/signon/ProfileAuto.tsx
- packages/mobile/src/store/oauth/actions.ts
- packages/mobile/src/store/oauth/reducer.ts
- packages/mobile/src/store/oauth/sagas.ts
- packages/mobile/src/store/oauth/selectors.ts
Ouch.
Painfully. Also debugger mode does not work.
> [C-1193] Fix oauth

- packages/mobile/src/components/track-list/TrackArtwork.tsx
- packages/mobile/src/components/track-list/TrackListItem.tsx
- packages/mobile/src/screens/settings-screen/ListeningHistoryScreen.tsx
- packages/mobile/src/screens/smart-collection-screen/SmartCollectionScreen.tsx
Fixes TrackList album artwork and smart collection screens sharp corners
> [C-1213, C-1216] Fix album artwork corners

- packages/mobile/src/hooks/useNavigation.ts
Prevents user from triggering multiple navigation requests by spamming the same link
> [C-1224] Prevent duplicate navigation pushes

- packages/mobile/src/components/core/PullToRefresh.tsx
This is a fairly complicated pr, but suffice to say this ensures the user has more control over their interactions when pull-t-refresh is activated, following the twitter pull-to-refresh logic.
Main things that are improved:
- User can scroll through their content while pull-to-refresh is running. Before the user was forced back up to the top of the scroll-view when pull-to-refresh finished.
- The pull-to-refresh icon is removed from view when user scrolls in the section view.
- Pull-to-refresh will not continue to trigger if the user has scrolled past pull distance, in line with twitter
These improvements only apply to not-collapsible-scroll-view pull-to-refreshes, ie not profile ones. This will be addressed in a separate pr
> [C-1027] Improve pull to refresh interaction

- packages/mobile/index.js
- packages/mobile/src/components/core/PullToRefresh.tsx
- packages/mobile/src/components/core/SectionList.tsx
- packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Fixes issue on profile screen where refresh get's stuck in a loop. This was due to not getting the right `refreshStatus` and some tricky issues with when we should trigger refresh in `PullToRefresh`
> [C-1226] Fix refresh stuck in loop

- packages/web/src/common/store/pages/signon/sagas.js
I believe this was lost in migrating into single sign on slice.
Will test thoroughly on bounce -- Push notifs are challenging to fully test even on the physical device in dev mode.
> [C-1209] Prompt user for notifications

- packages/mobile/src/screens/root-screen/RootScreen.tsx
Forgot to push this fix on branch that was merged. we have no app!
> Fix initial render condition

- packages/mobile/src/screens/edit-playlist-screen/CreatePlaylistScreen.tsx
> Allow hiding keyboard when creating playlist C-1215

- packages/mobile/src/components/user/FollowButton.tsx
- packages/mobile/src/components/user/ProfilePicture.tsx
- packages/mobile/src/screens/notifications-screen/Notification/ProfilePicture.tsx
- packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
- packages/mobile/src/screens/profile-screen/ProfilePicture.tsx
- packages/mobile/src/screens/profile-screen/SubscribeButton.tsx
- packages/mobile/src/screens/profile-screen/selectors.ts
> Fix verified badge C-1178

- packages/mobile/src/components/offline-placeholder/HideIfOffline.tsx
- packages/mobile/src/components/offline-placeholder/OnlineOnly.tsx
- packages/mobile/src/screens/profile-screen/EditProfileButton.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
Hide the edit profile button because changing the profile requires connectivity
> [C-1233] hide edit profile when offline

- packages/common/src/services/RandomImage.ts
Before: Random images cycled between same set of ~7 pics
After: Random images are actually random
https://github.com/unsplash/unsplash-source-js/issues/9
Having issues fully testing our gateway since I hit the rate limit, need to wait an hour and try again
Verified on web and mobile
> Fix random image C-1212

- packages/web/src/common/store/profile/sagas.js
Not sure if this was impacted by other things, but saw this one. UI will show unsubscribed even if you are.
> Fix notif subscription UI

- packages/mobile/src/screens/signon/ProfileManual.tsx
- packages/web/src/common/store/pages/signon/sagas.js
* Remove `.trim()` from onChange handler
* Add `.trim()` in sign up submit saga
Are there any other places the display name from the sign up state is being used? I couldn't find any
> [C-1270] Allow spaces in display name

- package-lock.json
- packages/mobile/package-lock.json
- packages/web/package-lock.json
> fix ci type error?

- packages/mobile/src/screens/root-screen/RootScreen.tsx
This might actually affect perf sitting at the top there 🗡️
> Remove extraneous navState log

- packages/common/src/utils/aaoErrorCodes.ts
Adds new emoji error code, also refactors to use a map instead of array since array is hard to maintain.
> [PAY-670] New emoji error code

- packages/web/src/components/buy-audio-modal/components/AmountInputPage.tsx
- packages/web/src/components/buy-audio-modal/components/InProgressPage.tsx
> Remove references to Coinbase in Stripe BuyAudioFlow

- packages/common/src/services/remote-config/feature-flags.ts
- packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Adds two new feature flags to give us more control on which providers are available for the BuyAudio modal.
Tested locally against stage
> [PAY-612] Add separate feature flags for enabling Coinbase/Stripe

- packages/common/src/utils/wallet.ts
- packages/web/src/services/audius-backend/BuyAudio.ts
- packages/web/src/store/application/ui/buy-audio/sagas.ts
#2043 Fast follows from PR comments
> BuyAudio Recovery Flow Fast Follows

- packages/web/public/index.html
Updates the library we use from Stripe to match the updated documentation.
Hasn't yet.
> Update Stripe JS dependency to match updated docs

- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/services/audius-backend/BuyAudio.ts
- packages/web/src/store/application/ui/buy-audio/sagas.ts
Updates SDK to get fix for saving user bank metadata, and then calls the method with the new signature.
(I guess technically this would be a breaking change in libs but it was barely out before being fixed)
> Update SDK/Libs and call saveUserBankTransactionMetadata correctly

- packages/mobile/src/App.tsx
ONE CHARACTER
got dropped between https://github.com/AudiusProject/audius-client/commit/9c63ab7a5a950f00bc13a686fff4d888a2301342 and https://github.com/AudiusProject/audius-client/commit/f637dedfdc648fada38a5bb5901c24a067bed08a
Don't think it was intentional but lmk if otherwise
> Fix entropy sync part 2

- packages/web/src/common/store/pages/saved/lineups/sagas.js
Similar to reposts, we should prepend favorited tracks to saved-track lineup
> Prepend saved tracks to saved lineup

- packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
> [HOTFIX] Remove unused import

- packages/mobile/ios/Podfile.lock
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/mobile/src/screens/tip-artist-screen/ConfirmSendTipScreen.tsx
The wormhole conversion request takes a few min usually (or even up to 20 sometimes). Keep the screen on to avoid failures in the middle of that.
> Keep screen awake when confirming tip

- package-lock.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
> Bump libs 1.0.12

- packages/common/src/services/audius-backend/AudiusBackend.ts
Accidentally removed the unhealthySlotDiffPlays optimizely flag
> Bring back unhealthySlotDiffPlays

- packages/mobile/ios/Podfile.lock
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/mobile/src/screens/search-screen/SearchBar.tsx
* Delay focusing text input to allow for smooth transition
* Update masked view library to fix visual glitch when navigating on android
> [C-1272] Fix Search UI jank

- packages/mobile/src/screens/track-screen/TrackScreen.tsx
* Slug was not being decoded
* Handle does not need to be decoded because only alphanumeric + underscores is valid
* CollectionScreen is unaffected bc it pulls the id from the collection name
> [C-1327] Fix deep linking for tracks with diacritics

- packages/mobile/src/utils/share.ts
* Audius url was missing from the link when using "Share via"
> [C-1328] Fix "Share via" url on mobile

- packages/mobile/ios/AudiusReactNative/Info.plist
Our ci fails to increment when we've recently released another version on the app store
> Bump ios to 1.1.33

- packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
- packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/BottomTabBarButton.tsx
- packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/NotificationsButton.tsx
- packages/mobile/src/screens/account-screen/AccountDrawer.tsx
- packages/mobile/src/screens/app-drawer-screen/useAppDrawerNavigation.ts
- packages/mobile/src/screens/app-screen/ProfileTabScreen.tsx
- packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
- packages/mobile/src/screens/notifications-screen/Notification/EntityLink.tsx
- packages/mobile/src/screens/notifications-screen/Notification/ProfilePicture.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/AddTrackToPlaylistNotification.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/RemixCosignNotification.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/RemixCreateNotification.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/TrendingTrackNotification.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/UserSubscriptionNotification.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/useSocialActionHandler.ts
- packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx
Implements notifications bottom-tab-bar
Implements notifications screen
Updates account-drawer touch targets
> [C-1341] Add notifications bottom tab screen

- packages/mobile/src/components/navigation-container/NavigationContainer.tsx
- packages/web/public/.well-known/apple-app-site-association
> dont deep link oauth

- packages/web/src/store/token-dashboard/sagas.ts
Eth wallets were not working because `yield *` was being called on a fn without a saga effect
yield works because it awaits the result whereas yield* does not
Locally connected wallet
> Fix connected eth wallets

- packages/web/src/store/application/ui/buy-audio/sagas.ts
Put the recovery flow saga behind a feature flag.
> [PAY-697]: Put recovery flow behind feature flag

- packages/mobile/src/components/core/DynamicImage.tsx
- packages/mobile/src/components/image/ImageLoader.tsx
- packages/mobile/src/components/user/ProfilePicture.tsx
- packages/mobile/src/screens/app-drawer-screen/AppDrawerScreen.tsx
- packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
- packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
Addresses mobile-nav qa
- Updates drawerStyle to "front", which makes transitions to nav-bar items smoother, and prevents double profile image.
- Prevents account-picture-header clipping due to negative margins
- Improves account-picture-header rerender perf by preventing opacity animation
> [C-1368, C-1354, C-1364] Address mobile-nav qa

- packages/common/package-lock.json
- packages/common/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/web/package-lock.json
- packages/web/package.json
This fixes the "Forbidden" error we were seeing on mobile
> Update @audius/sdk to 1.0.16

- package-lock.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/web/package.json
> Update libs to 1.0.18

- .circleci/config.yml
- .circleci/src/commands/@commands.yml
- .circleci/src/jobs/@mobile-jobs.yml
- .circleci/src/jobs/@stems-jobs.yml
- .circleci/src/jobs/@web-jobs.yml
- packages/mobile/patches/@react-navigation+drawer+6.3.1.patch
- packages/mobile/src/screens/account-screen/AccountDrawer.tsx
- packages/mobile/src/screens/app-drawer-screen/useAppDrawerNavigation.ts
- packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
- packages/mobile/src/screens/app-screen/AppTabScreen.tsx
- packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/useSocialActionHandler.ts
- packages/mobile/src/screens/user-list-screen/FollowersScreen.tsx
- packages/mobile/src/screens/user-list-screen/FollowingScreen.tsx
Fixes various aspects of mobile navbar feature.
Biggest changes relate to navigation-stack and swipe-to-close behavior
> [C-1371, C-1372] Address mobile-navbar QA issues #2

- packages/web/src/common/store/social/users/sagas.ts
This action wasn't working as expected without action.update = true
https://github.com/AudiusProject/audius-client/blob/dc58e2b1386042bdc2ff8255c4367928748cde8b/packages/web/src/common/store/profile/sagas.js#L568
Yuck!
> [C-1340] Fix notification subscriptions

- packages/common/package-lock.json
- packages/common/package.json
- packages/eslint-config-audius/package-lock.json
- packages/eslint-config-audius/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/stems/package-lock.json
- packages/stems/package.json
- packages/web/package-lock.json
- packages/web/package.json
> Bump sdk to 1.0.19

- packages/web/src/common/store/pages/signon/sagas.js
> Avoid `handleInUse` libs function bc it hits poa

- packages/web/src/components/cover-photo/CoverPhoto.module.css
> [C-1377] Move cover photo button to top

- packages/common/src/models/Analytics.ts
- packages/common/src/services/remote-config/defaults.ts
- packages/common/src/services/remote-config/types.ts
- packages/common/src/store/ui/buy-audio/selectors.ts
- packages/common/src/store/ui/buy-audio/slice.ts
- packages/common/src/store/ui/transaction-details/slice.ts
- packages/common/src/store/ui/transaction-details/types.ts
- packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.module.css
- packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
- packages/web/src/components/buy-audio-modal/components/SuccessPage.tsx
- packages/web/src/components/stripe-on-ramp-modal/StripeOnRampModal.tsx
- packages/web/src/components/transaction-details-modal/TransactionDetailsModal.tsx
- packages/web/src/components/transaction-details-modal/components/TransactionPurchaseMetadata.tsx
- packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
- packages/web/src/store/application/ui/buy-audio/sagas.ts
**Again, recommended to look commit by commit**
See commit names/linear items for details.
> [PAY-709][PAY-704][PAY-702][PAY-700][PAY-696][PAY-692][PAY-691] Various Stripe OnRamp Fixes pt 2

- packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
> Fix mobile lint

- packages/common/src/services/audio-player.ts
- packages/common/src/services/remote-config/defaults.ts
- packages/common/src/services/remote-config/feature-flags.ts
- packages/common/src/services/remote-config/types.ts
- packages/mobile/src/components/audio/Audio.tsx
- packages/web/src/common/store/player/sagas.ts
- packages/web/src/services/audio-player/AudioPlayer.ts
cherry-pick f1c28bdffe9a6ea2a8cc0fb41bf707e3c6f257bb onto release
> Cherry pick f1c28bdf - add feature flag to mp3 streaming change

- packages/common/src/models/Analytics.ts
- packages/web/src/components/on-ramp-button/OnRampButton.module.css
- packages/web/src/components/on-ramp-button/OnRampButton.tsx
- packages/web/src/components/tipping/tip-audio/SendTip.tsx
- packages/web/src/components/tipping/tip-audio/TipAudio.module.css
- packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css
[Figma](https://www.figma.com/file/kDAWdnLlorKQtAF4pdc0cB/Buy-%24AUDIO-CTA-in-the-Tipping-Flow?node-id=2%3A2171)
> PAY-687 Add new UI to tipping linking to the BuyAudio flow

- packages/web/src/components/cover-photo/CoverPhoto.module.css
Julian wanted this to align with search bar on review!
> Fix cover photo button alignment

- packages/common/src/models/User.ts
- packages/common/src/store/account/selectors.ts
- packages/common/src/store/account/slice.ts
- packages/common/src/store/challenges/selectors/profile-progress.ts
- packages/web/src/common/store/account/sagas.js
- packages/web/src/common/store/social/collections/sagas.ts
- packages/web/src/common/store/social/tracks/sagas.ts
- packages/web/src/components/profile-progress/ConnectedProfileCompletionPane.js
Concretely doesn't do much, but I couldn't repro after this.
Cleaned up a lot of stuff to try to expose race condition.
Biggest change is moving the confetti to the same pattern we use elsewhere driven by an action versus rendered sepately.
Hard to test with staging writes kinda broken :(
> [C-882] Try to fix too often confetti bug

- package-lock.json
- packages/common/package-lock.json
- packages/common/package.json
- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/eslint-config-audius/package-lock.json
- packages/eslint-config-audius/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/stems/package-lock.json
- packages/stems/package.json
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/common/store/pages/signon/sagas.js
Uses new libs method to include handle in Web3Manager, to be sent to relay.
**Needs libs bump before merging**
None
Stage, a lot
> Send handle to relay

- packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
- packages/web/src/services/Location.ts
See Linear items/commits.
Noticed these issues while testing in Portugal. I think these could both be pretty critical
> [PAY-720] [PAY-721] Stripe OnRamp hotfixes

- packages/web/src/components/source-files-modal/SourceFilesModal.tsx
Bump stems limit from 5 to 10.
Locally vs. staging. Upload track with 7 stems.
staging.audius.co/ray65/fame-inc-7
> Bump stems limit from 5 to 10

- packages/mobile/src/store/notifications/sagas.ts
- packages/web/src/store/notifications/sagas.ts
Can go in after released
https://github.com/AudiusProject/audius-protocol/pull/4354
> [Flare-120] Avoid hitting notification settings on each session

- packages/mobile/src/components/audio/Audio.tsx
My last pr broke mobile seeking 😔
This fixes the issue, but it doesn't fix the scrubber positioning issues we are seeing. Have a follow up PR for that :)
> Fix mobile seek

- packages/mobile/android/app/src/main/AndroidManifest.xml
- packages/mobile/android/build.gradle
* Bump android target api to 31
* Add activity:exported to fix build errors
* This should fix our CI builds
> [C-1495] Bump target api to 31

- packages/web/src/store/application/ui/buy-audio/sagas.ts
Make sure to wait for backend account for the buy audio feature flag (recovery flow)
> Wait for backend account for BuyAudio feature flag

- packages/mobile/src/screens/root-screen/RootScreen.tsx
- packages/mobile/src/screens/splash-screen/SplashScreen.tsx
This makes things slightly faster!
> Hide bootsplash earlier

- .circleci/src/jobs/@mobile-jobs.yml
* Android keeps failing, think it's running out of memory
https://app.circleci.com/pipelines/github/AudiusProject/audius-client?branch=release-mobile
> Bump android ci image size

- packages/mobile/src/components/core/FormImageInput.tsx
- packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
- packages/mobile/src/screens/edit-track-screen/EditExistingTrackScreen.tsx
- packages/mobile/src/screens/edit-track-screen/fields/PickArtworkField.tsx
Prevent images from flashing on EditProfile, EditTrack
> Fix edit images

- packages/mobile/src/components/audio/Audio.tsx
- packages/mobile/src/screens/edit-playlist-screen/EditPlaylistScreen.tsx
* Fix MusicControl image
* Fix edit playlist image
> iOS fast follows

- packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
This check for `track` was added as part of the animation performance changes, but it's not really needed and caused the weird double play bug on android
> Fix android double play

- packages/mobile/src/components/suggested-follows/SuggestedFollows.tsx
> [C-1357] Fix followers formatting on sign up

- packages/web/src/components/notification/Notification/components/EntityLink.tsx
See title
N/A
Tested manually against stage
N/A
N/A
> [QA-223] Close notification panel when clicking entity link

- package-lock.json
- package.json
- packages/mobile/android/app/src/main/AndroidManifest.xml
- packages/mobile/ios/Podfile.lock
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/mobile/src/App.tsx
- packages/mobile/src/Drawers.tsx
- packages/mobile/src/assets/images/iconPhantom.svg
- packages/mobile/src/components/drawer/Drawer.tsx
- packages/mobile/src/components/transfer-audio-mobile-drawer/TransferAudioMobileDrawer.tsx
- packages/mobile/src/screens/app-screen/AppTabScreen.tsx
- packages/mobile/src/screens/audio-screen/AudioScreen.tsx
- packages/mobile/src/screens/wallet-connect/WalletConnectScreen.tsx
- packages/mobile/src/screens/wallet-connect/WalletConnectStack.tsx
- packages/mobile/src/screens/wallet-connect/components/LinkedWallets.tsx
- packages/mobile/src/screens/wallet-connect/components/WalletsDrawer.tsx
- packages/mobile/src/screens/wallet-connect/components/index.ts
- packages/mobile/src/store/drawers/slice.ts
Vendors in wallet connect
TODO:
1. Move token dashboard sagas to common and wire up
Basically this code, but inside that saga
```
const connector = useWalletConnect()
connector.signMessage(...), etc.
```
2. Wire up phantom stuff (probably differently than is currently done b/c we never want to touch the privkey) into the same modal experience
3. Wire up solana phone as another option (but quite similar to phantom)
Many tests necessary
*Are all new features properly feature …
> [C-1548] Integrate native WalletConnect

- packages/mobile/src/components/core/DynamicImage.tsx
- packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavDrawer.tsx
- packages/mobile/src/screens/edit-track-screen/fields/PickArtworkField.tsx
- packages/mobile/src/screens/profile-screen/UploadTrackButton.tsx
- packages/mobile/src/screens/upload-screen/screens/SelectTrackScreen.tsx
Improve "Upload Track" copy to "Upload a Track"
Fix upload-track button on profile screen
Fix placeholder dynamic image color
> [C-1565 C-1566 C-1567] Improve upload copy, colors

- packages/common/src/services/remote-config/feature-flags.ts
- packages/mobile/src/screens/edit-track-screen/fields/PickArtworkField.tsx
Updates feature flag value to prepare for mobile upload release
> Finalize mobile-upload feature flag

- packages/mobile/src/screens/upload-screen/components/UploadingTrackTile.tsx
Fixes flashing uploading track cover art by memoizing the track artwork source
> [QA-225] Fix flashing uploading track cover art

- packages/mobile/ios/Podfile.lock
- packages/mobile/package-lock.json
- packages/mobile/package.json
https://github.com/tanguyantoine/react-native-music-control/pull/397/commits/b14e006b9be841be81824c25f96eff397c826f40
> Update react native music control

- packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
- packages/web/src/services/Location.ts
Fixes BuyAudio geolocation API
Made sure to get rate limited, then saw the error "RateLimited" and the button still worked.
> [hotfix]: Location detection fix

- packages/mobile/src/Drawers.tsx
- packages/mobile/src/components/confirm-remove-wallet-drawer/ConfirmRemoveWalletDrawer.tsx
- packages/mobile/src/components/confirm-remove-wallet-drawer/index.ts
- packages/mobile/src/screens/wallet-connect/WalletConnectScreen.tsx
- packages/mobile/src/screens/wallet-connect/WalletConnectStack.tsx
- packages/mobile/src/screens/wallet-connect/components/LinkedWallets.tsx
- packages/mobile/src/screens/wallet-connect/components/WalletsDrawer.tsx
- packages/mobile/src/store/drawers/slice.ts
Brings UI up to spec mostly with the design for connect wallets flow. Some things missing that we'll probably want to QA more deeply as we get it all integrated.
> [C-1574] Update UI in mobile wallet connect flow

- packages/mobile/src/screens/wallet-connect/components/WalletsDrawer.tsx
Fix images. They had no size so were empty.
Also fix flex alignment & spacing
Simulator
> [C-1597] Fix wallet images

- packages/web/src/services/audius-backend/BuyAudio.ts
- packages/web/src/store/application/ui/buy-audio/sagas.ts
> hotfix: Extra padding for BuyAudio flow

- packages/mobile/react-native.config.js
Potential fix for android build failing on rn-threads
> Fix react-native-threads on android

- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
> [C-1573] Fix hidden track centering

- packages/mobile/src/components/core/TextInput.tsx
Hide input accessory on android
https://github.com/expo/expo/issues/2979#issuecomment-457140230
> Disable input accessory on android

- package-lock.json
- packages/mobile/ios/Podfile.lock
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/mobile/src/components/core/Text.tsx
- packages/mobile/src/components/share-drawer/ShareDrawer.tsx
- packages/mobile/src/components/share-drawer/ShareToStorySticker.tsx
- packages/mobile/src/components/share-drawer/messages.ts
- packages/mobile/src/components/share-drawer/useShareToStory.tsx
- packages/mobile/src/styles/typography.ts
- packages/mobile/src/utils/convertRGBtoHex.ts
- packages/web/package-lock.json
https://user-images.githubusercontent.com/36916764/205125922-e4dc4e93-9a98-4b52-be68-725679b5be8e.MP4
Finish up the share to instagram design. 
What's left:
Loading state
Metrics
> Share to Instagram - Use dominant colors; generate sticker

- README.md
- packages/mobile/android/app/src/main/java/com/audiusreactnative/MainActivity.java
- packages/mobile/android/app/src/main/res/values-v27/styles.xml
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/mobile/src/components/drawer/Drawer.tsx
- packages/mobile/src/components/forgot-password-drawer/ForgotPasswordDrawer.tsx
- packages/mobile/src/screens/root-screen/RootScreen.tsx
- packages/mobile/src/screens/root-screen/StatusBar.tsx
- packages/mobile/src/screens/signon/SignOn.tsx
- packages/mobile/src/screens/splash-screen/SplashScreen.tsx
- packages/web/src/common/store/backend/sagas.ts
* Fixes splash screen on android (device consistency) and status bar colors.
Unfortunately, android compatibility seems to be difficult with our splash screen animation & the bootsplash library. It works well on pixel phones, but poorly on galaxy s10 (and I would guess other devices as well).
https://github.com/zoontek/react-native-bootsplash/issues/410
Few apps on android even have good animations because of this I think.
* Fixes white screen between splash screen and app screen on iOS.
* Fixes sign up layout significantly (replacing weird layout stuff with flex + better image sizing)
*Please describe the tests that you ran to verify your changes. Provide repro instructions & any …
> [C-1601][C-1602] Fix splash screen and status bars on android

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/common/src/store/premium-content/actions.ts
- packages/web/src/common/store/notifications/sagas.ts
- packages/web/src/common/store/profile/sagas.js
> Fix social feature lint

- packages/mobile/src/screens/wallet-connect/components/EthWalletConnectOption.tsx
- packages/mobile/src/screens/wallet-connect/components/PhantomWalletConnectOption.tsx
- packages/mobile/src/screens/wallet-connect/components/SolanaPhoneOption.tsx
- packages/mobile/src/screens/wallet-connect/components/WalletConnectDrawer.tsx
- packages/mobile/src/screens/wallet-connect/components/WalletConnectOption.tsx
> [C-1651] Update mobile connect-wallet ui

- packages/web/src/services/audius-sdk/audiusSdk.ts
- packages/web/src/services/audius-sdk/index.ts
FIrst step towards using the SDK in the client. Very rudimental, open to suggestions. But it works!
Tested locally by using it for audio transactions history endpoints.
> Expose SDK in client

- packages/web/src/common/store/notifications/sagas.ts
- packages/web/src/common/store/player/sagas.ts
- packages/web/src/common/store/profile/sagas.js
The `waitForWrite` change broke offline playback. Added a special case for offline and deferred the `waitForWrite` check if we're offline and offline mode is on.
> Fix offline playback

- packages/mobile/src/components/share-drawer/useShareToStory.tsx
- packages/mobile/threads/dominantColors.thread.js
Demos/discussion:
https://audius-internal.slack.com/archives/C04885C9WNA/p1670778634084659
-Pick the two most colorful colors for the video
-Mirror the showfreqs wavform and make it transparent
> [Share to IG] QA - Pick most colorful colors and adjust the wavform

- packages/common/package-lock.json
- packages/common/package.json
- packages/eslint-config-audius/package-lock.json
- packages/eslint-config-audius/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/stems/package-lock.json
- packages/stems/package.json
- packages/web/package-lock.json
- packages/web/package.json
> Upgrade @audius/sdk to 1.0.25

- packages/mobile/src/components/lineup-tile/TrackTile.tsx
Runtime error due to ts-expect-ignore
> Fix track tile currentScreen check

- packages/common/package.json
- packages/web/package.json
> Bump @audius/sdk version to 1.0.26

- packages/common/src/services/remote-config/feature-flags.ts
https://audius-internal.slack.com/archives/C04885C9WNA/p1670955202674829
> Change IG Feature Flag name

- packages/mobile/src/services/remote-config/remote-config-instance.ts
- packages/web/src/services/remote-config/remote-config-instance.ts
Use custom endpoint for optimizely
Simulator on staging
> [C-1666] Use custom optimizely datafile

- packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css
- packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Updates the "Advanced Options" section of the `/audio` page to be "More Options"
> [PAY-767] Change advanced options to more options

- packages/web/src/services/Location.ts
> No expiry on getLocation cache

- packages/mobile/android/app/src/main/AndroidManifest.xml
- packages/web/public/.well-known/assetlinks.json
Fixes android deeplinks by updating android intents, and adding known-site config
> [C-1676] Fix android deeplinks

- packages/mobile/src/components/share-drawer/useShareToStory.tsx
Context: https://audius-internal.slack.com/archives/C03C2V84A1L/p1671053546648829
> Fix share to IG with solid color cover art

- package-lock.json
> Revert package.lock

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/common/src/services/remote-config/defaults.ts
- packages/common/src/services/remote-config/feature-flags.ts
- packages/common/src/services/remote-config/types.ts
- packages/common/src/store/pages/audio-transactions/selectors.ts
- packages/common/src/store/pages/audio-transactions/slice.ts
- packages/common/src/store/pages/index.ts
- packages/common/src/store/reducers.ts
- packages/common/src/store/ui/transaction-details/types.ts
- packages/common/src/utils/formatUtil.ts
- packages/web/src/common/store/pages/audio-transactions/sagas.ts
- packages/web/src/common/store/pages/token-dashboard/sagas.ts
- packages/web/src/components/audio-transaction-icon/AudioTransactionIcon.tsx
- packages/web/src/components/audio-transactions-table/AudioTransactionsTable.module.css
- packages/web/src/components/audio-transactions-table/AudioTransactionsTable.tsx
- packages/web/src/components/transaction-details-modal/components/Block.module.css
- packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.module.css
- packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx
- packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
- packages/web/src/pages/audio-transactions-page/AudioTransactionsPage.module.css
- packages/web/src/pages/audio-transactions-page/AudioTransactionsPage.tsx
- packages/web/src/store/sagas.ts
Audio Transactions History Table
> [PAY-728] Audio Transactions History Table

- packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.module.css
- packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx
Minor UI fixes for TransactionDetailsModal:
* min-height for purchase transaction.
* hover state for user in tip transaction.
Tested on local
> [PAY-771][PAY-773] UI fixes for TransactionDetailsModal

- packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.module.css
- packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx
Removes globally scoped `!important` on `<i>` tag styles to fix broken headers across the product, instead scoping them to the specific use case within the `TransactionDetailsModal`
> hotfix: Broken modal headers

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/common/src/services/remote-config/feature-flags.ts
- packages/mobile/src/services/audius-backend-instance.ts
- packages/mobile/src/store/oauth/sagas.ts
- packages/web/src/common/store/pages/signon/sagas.js
- packages/web/src/common/store/pages/signon/verifiedChecker.ts
- packages/web/src/components/instagram-auth/InstagramAuth.tsx
- packages/web/src/components/instagram-button/InstagramButton.tsx
- packages/web/src/components/social-proof/SocialProof.tsx
- packages/web/src/pages/settings-page/components/InstagramAccountVerified.tsx
- packages/web/src/pages/sign-on/components/ProfileForm.tsx
- packages/web/src/services/audius-backend/audius-backend-instance.ts
Simplify the checks for insta:
* One request after getting the oauth code
* Uses newly defined check in audiusbackend for reserved handle
Add tiktok verification check:
* Somewhat worried about the cost of calling the tiktok checks in particular until we have an even nicer solution, so I increased the debounce to 1s from 300ms.
Want to test on staging. Given that insta is all kinda of whack already, I think safe to merge as is
*Are all new features properly feature flagged? …
> [C-1689] Simplify insta oauth and add tiktok handle check

- packages/mobile/src/hooks/useLoadOfflineTracks.ts
- packages/mobile/src/services/offline-downloader/offline-storage.ts
- packages/mobile/src/store/offline-downloads/sagas.ts
- packages/mobile/src/store/offline-downloads/slice.ts
- packages/mobile/src/store/sign-out/sagas.ts
Clears downloads when signing out. Adds a saga for this, are we trying to avoid using sagas though?
> [C-1478] Clear offline downloads when switching accounts

- packages/common/src/services/oauth/formatSocialProfile.ts
For some reason we are only getting IG id and handle back from the auth response (so no profile pic, no full name, etc). Not sure if this is a change to the IG API that we have to account for in Identity, or maybe a regression in the Identity code or something else. But this fixes the silent failure on the UI side for now. The UX experience is still not great though because basically no info gets filled out from this.
*Are all new features properly feature flagged? Describe …
> C-1725 Fix sign-up with Instagram

- packages/mobile/src/components/audio/Audio.tsx
Fix the issue where calling reset on the Trackplayer when the app is in the background breaks the app on android 12+
Touches audio playback so we should handle with care.
This also infinitely adds to the queue for the track player which could cause memory issues after long sessions of listening. This should be fixed in the future when we update our TrackPlayer implementation
N/A
N/A
> Fix background reset issues for track player on android 12+

- packages/mobile/src/components/image/CollectionImage.tsx
- packages/mobile/src/components/image/TrackImage.tsx
Fix track player artwork and speed up useImage
- Temporarily disables useLocalImage
> Fix track player artwork, speed up useImage

- packages/common/src/services/audius-backend/eagerLoadUtils.ts
- packages/common/src/services/local-storage/LocalStorage.ts
- packages/web/src/services/Location.ts
- packages/web/src/store/application/ui/buy-audio/sagas.ts
- packages/web/src/utils/gdpr.ts
- Use new Identity endpoint for getting location (that PR to go out first)
- Cache isEU in local storage for 1 wk
None
Against stage
> [PAY-740] Use Identity endpoint for location

- .circleci/src/commands/@web-commands.yml
- packages/web/public/.well-known/apple-app-site-association-stage
Add stage apple-app-site-association
> Staging deeplinks on iOS

- packages/mobile/index.js
- packages/mobile/package.json
Attempt to fix crash on profiles with collectibles
Cannot repro locally at all, but can consistently repro on Stage and RC so going to merge and see if it fixes
Error being thrown: https://sentry.io/organizations/audius/issues/3834954449/?query=sdk.name%3Asentry.javascript.react-native+user%3A%22id%3A54432%22&referrer=issue-stream&sort=date&statsPeriod=14d
> Polyfill BigInt

- packages/mobile/index.js
- packages/mobile/patches/big-integer+1.6.51.patch
Forcing the polyfill of bigint on ios so that the package patches will work
> Force polyfill of BigInt on ios as well

- packages/common/src/services/location.ts
Remove async generator that was causing crash/fail during signup
Will cherry pick onto release-v1.5.4
> [C-1751] Fix staging signup

- packages/mobile/ios/Podfile.lock
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/mobile/src/screens/signon/SignOn.tsx
https://github.com/surajitsarkar19/react-native-radial-gradient/issues/38
> Remove radial gradient

- packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
- packages/mobile/ios/Podfile
- packages/mobile/ios/Podfile.lock
```
cd packages/mobile/ios && pod deintegrate && pod cache clean --all && cd -
npm i && npm run ios:prod
```
> Fix local iOS dev/install

- packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
- packages/mobile/ios/Podfile
- packages/mobile/ios/Podfile.lock
- packages/mobile/package-lock.json
- packages/mobile/package.json
- Fixes staging flipper by adding staging.debug scheme to flipper config
- Also updates flipper version, ideally this provides general improvements
> Fix staging flipper

- packages/mobile/package-lock.json
- packages/mobile/package.json
Adds a command to clean the react-native builds
> Add react-native-clean-project

- packages/mobile/src/components/rate-cta-drawer/RateCtaDrawer.tsx
Update button variant to commonAlt to avoid the text color animation issue for the time being.
Good call @dylanjeffers 
N/A
N/A
N/A
> Update button variants for rate cta drawer

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/web/package-lock.json
- packages/web/package.json
> Pass blacklist into sanity check and bump libs/sdk to v1.0.32

- packages/web/package-lock.json
- packages/web/package.json
Bumps SDK to 1.0.33 to get patch-package correctly installed
> Bump sdk to 1.0.33

- packages/web/package-lock.json
- packages/web/package.json
> Update sdk to v1.0.34

- packages/web/package-lock.json
- packages/web/package.json
> Update SDK in Web to v1.0.35

- packages/mobile/ios/AudiusReactNative/Info.plist
> Bump ios to 1.1.51

- packages/mobile/src/screens/user-list-screen/UserList.tsx
User list is infinitely rerendering until user ids come in. Depending on network conditions this can cause `Warning: Maximum update depth exceeded.`
> [C-1814] Prevent infinite rerender of UserList

- packages/common/src/store/pages/chat/sagas.ts
- packages/common/src/store/pages/chat/selectors.ts
- packages/common/src/store/pages/chat/slice.ts
- packages/web/src/assets/styles/index.css
- packages/web/src/assets/styles/shadows.css
- packages/web/src/components/notification/Notification/components/Reaction/Reaction.tsx
- packages/web/src/pages/chat-page/ChatPage.module.css
- packages/web/src/pages/chat-page/ChatPage.tsx
- packages/web/src/pages/chat-page/components/ChatList.module.css
- packages/web/src/pages/chat-page/components/ChatList.tsx
- packages/web/src/pages/chat-page/components/ChatListItem.module.css
- packages/web/src/pages/chat-page/components/ChatListItem.tsx
- packages/web/src/pages/chat-page/components/ChatMessageList.module.css
- packages/web/src/pages/chat-page/components/ChatMessageList.tsx
- packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
- packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
- packages/web/src/pages/chat-page/components/ReactionPopupMenu.module.css
- packages/web/src/pages/chat-page/components/ReactionPopupMenu.tsx
- packages/web/src/utils/route.ts
- Move `/chat` to `/messages/:id` and use chat ID to route
- Add reactions button, reactions, and reaction setting saga
-  Stylize chat list items appropriately
-  Adds partial empty state for no chats
- Styles messages with date and groups if sent near same time, and added new message separator
Outstanding TODOs to be completed in future PRs
> DMs UI Part 1

- packages/mobile/src/screens/chats-screen/ChatsScreen.tsx
Fixes build break introduced in #2563 as i hastily updated and merged without waiting for CI 😅 
> Hotfix: Fix mobile build after selector was changed

- packages/mobile/src/hooks/useNotificationNavigation.ts
Small change to add a null check for the navigate function of the useNotificationNavigation hook
N/A
N/A
N/A
N/A
> Add null check for notification navigation hook

- packages/common/src/store/pages/chat/sagas.ts
- packages/common/src/store/pages/chat/slice.ts
- packages/web/src/pages/chat-page/ChatPage.tsx
- packages/web/src/pages/chat-page/components/ChatListItem.tsx
Marks the current chat as read if the user reaches the most recent message.
Tested against stage
> [DMs] Mark chats as read if the user hits the bottom of the scrollbar

- packages/mobile/src/hooks/useLocalImage.ts
Immediately return empty array if reachable, this avoids the overhead of awaiting the async function
> Improve useLocalImage perf

- packages/common/package-lock.json
- packages/common/package.json
- packages/eslint-config-audius/package-lock.json
- packages/eslint-config-audius/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/stems/package-lock.json
- packages/stems/package.json
- packages/web/package-lock.json
- packages/web/package.json
Upgrade audius sdk version to 1.0.41 to include temp fix for audio transactions history page.
> Bump SDK version to 1.0.41

- packages/common/src/schemas/index.ts
proper fix. tested and it still works
> Add proper fix for track cid bug

- packages/web/src/components/page/Page.js
Fixes bug introduced in #2576 which hid the search bar from most pages
> Fix search being missing from most pages

- packages/web/src/store/application/ui/buy-audio/sagas.ts
Fixes bug introduced in https://github.com/AudiusProject/audius-client/pull/2387/files that caused saving local storage state to fail.
TL;DR: Don't name your local storage variable `localStorage`!
> Fix BuyAudio flow failure due to local storage type error

- packages/web/src/components/track/GiantTrackTile.module.css
- packages/web/src/components/track/desktop/Artwork.module.css
- packages/web/src/components/track/desktop/Artwork.tsx
- packages/web/src/components/track/desktop/BottomRow.tsx
- packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
- packages/web/src/components/track/desktop/PremiumContentLabel.tsx
- packages/web/src/components/track/desktop/TrackTile.module.css
- packages/web/src/components/track/desktop/TrackTile.tsx
- packages/web/src/components/track/helpers.ts
- packages/web/src/components/track/types.ts
- packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Add track tile for premium tracks
N/A
Local dapp vs stage for:
- collectible gated track
- tip gated track
- follow gated track
N/A
existing feature flags
> [PAY-780] Premium content track tile - Web

- packages/web/src/common/store/upload/sagas.js
Fix playlist upload flag in metadata.
It was being overwritten by the default bc of the ordering of playlist upload 
> Fix playlist upload flag in metadata

- packages/web/src/components/track/desktop/Artwork.tsx
- packages/web/src/components/track/desktop/BottomRow.tsx
- packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
- packages/web/src/components/track/desktop/PremiumContentLabel.tsx
- packages/web/src/components/track/desktop/TrackTile.tsx
> Fix typecheck

- packages/common/src/models/Analytics.ts
- packages/web/src/store/configureStore.ts
- packages/web/src/store/errors/sagas.ts
> Add route to ERROR_PAGE event

- packages/mobile/package.json
Fix android crash by upgrading reanimated: https://github.com/software-mansion/react-native-reanimated/issues/3952
> Upgrade reanimated to 2.14.4

- packages/mobile/ios/Podfile.lock
- packages/mobile/package-lock.json
- packages/web/package-lock.json
> Check in package changes for reanimated upgrade

- packages/mobile/src/store/store.ts
Add sentry b/c we do not get console logs/errors from mobile on prod
> Add sentry on saga error

- packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
> Fix playlist tile lint + bug

- packages/mobile/src/store/offline-downloads/sagas.ts
Automatically download tracks if they're added to a playlist that's already marked for download.
> [C-1879] Download track when added to downloaded playlists

- packages/common/src/services/audius-api-client/AudiusAPIClient.ts
- packages/common/src/services/remote-config/feature-flags.ts
- packages/mobile/src/components/track-list/TrackListItem.tsx
- packages/mobile/src/screens/settings-screen/AboutScreen.tsx
- packages/mobile/src/services/offline-downloader/offline-downloader.ts
- packages/mobile/src/store/offline-downloads/sagas.ts
Cherry-picks for offline mode release
> Cherry-picks for offline release

- packages/common/src/utils/challenges.ts
- packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx
- packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
Memoize the sorted challenges, and use not-optimistic user challenges on web to avoid tiles teleporting abruptly.
Local web and ios sim.
> Memoize sorted challenges

- packages/web/src/components/track/PremiumTrackSection.tsx
- packages/web/src/components/track/desktop/TrackTile.tsx
Playlist tile is unclickable due to a bug introduced in a recent commit. This fixes it.
n/a
local dapp v. stage
n/a
none
> Fix playlist tile click

- packages/web/src/common/store/cache/sagas.js
Going to profile broke the dapp. This fixes it.
> Fix profile

- packages/web/src/common/store/premiumContent/sagas.ts
Listening to the ADD_SUCCEEDED action will allow our premium content sagas to get the track update and prevent infinite polling.
local dapp v. stage
> Listen to add succeeded

- package-lock.json
- packages/common/package-lock.json
- packages/common/package.json
- packages/common/src/store/pages/chat/sagas.ts
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/web/package-lock.json
- packages/web/package.json
Note: One breaking change (technically)
> Update SDK to 1.0.42

- packages/mobile/src/components/card/Card.tsx
- packages/mobile/src/components/collection-list/CollectionCard.tsx
- packages/mobile/src/components/now-playing-drawer/Artwork.tsx
- packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
Fixes image rendering for some track artworks due to improperly styled images
> Fix artwork for now-playing and playbar

- packages/web/src/assets/img/ChatTail.svg
- packages/web/src/assets/styles/shadows.css
- packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
- packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Adds tails to chat bubbles, if applicable, using an SVG
> [DMs] Add tails to chat bubbles

- packages/web/src/pages/chat-page/components/ChatHeader.module.css
- packages/web/src/pages/chat-page/components/ChatHeader.tsx
Adds a compose button to the chats layout to allow the compose modal to pop up if already viewing a chat.
> DMs: Add compose button

- packages/mobile/src/components/offline-downloads/DownloadStatusIndicator.tsx
https://audius-internal.slack.com/archives/C042EHZS5NV/p1674589365626939
> C-1908 Show error indicator on playlists if all track downloads failed

- packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
- packages/web/src/pages/audio-rewards-page/RewardsTile.module.css
Fix alignment in rewards panels so the buttons are aligned at the bottom.
Local web
> Fix content alignment in rewards tiles

- .circleci/src/workflows/mobile.yml
This reverts commit 6e9c2d1ee3b9df2ef2fabafb1e5471de4d60320f.
> Revert "Make rc-staging fast-app variant (#2585)"

- packages/common/src/utils/selectorHelpers.ts
- packages/mobile/src/components/audio/Audio.tsx
- packages/mobile/src/components/offline-downloads/DownloadStatusIndicator.tsx
- packages/mobile/src/components/offline-downloads/DownloadToggle.tsx
- packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
- packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
- packages/mobile/src/store/offline-downloads/selectors.ts
Improves selectors used in `DownloadStatusIndicator` and `Audio` to minimize rerenders while offline mode is on.
0 rerenders on feed screen while offline mode is on!
Will follow up with a pr to address excess image fetching and rn queue performance
> Improve offline mode react performance

- packages/web/src/components/notification/Notification/components/UserProfilePictureList.tsx
Undefined user gets passed into picture component
Locally vs. prod with repro
> Fix profile picture crash

- packages/stems/src/components/Modal/Modal.tsx
Fixes the issue where the popups wouldn't dismiss when clicking the modal contents, without reintroducing the $AUDIO transfer modal bug.
Will rebase later...
> [C-1754] Fix modal popups not closing

- packages/web/src/components/data-entry/InputV2.module.css
- packages/web/src/components/data-entry/InputV2.tsx
#2701 auto closed on me when I merged this into my wip branch - see that pr for details
> Port Input Component to Typescript - InputV2

- packages/common/src/services/location.ts
- packages/web/src/utils/gdpr.ts
Change the field we check for gdpr to `is_eu` to match ipdata API that we switched over to.
> Change location.in_eu to is_eu

- packages/web/src/components/track/GiantTrackTile.module.css
- packages/web/src/components/track/PremiumTrackSection.tsx
Fix:
- inline collection link on premium track page unlock section
- weird collapsing text on smaller screen sizes on premium track page 
see https://linear.app/audius/issue/PAY-869/premium-content-qa-items
N/A
local dap v. stage
n/a
exisiting
> Fix some web premium content bugs

- packages/mobile/.env.dev
- packages/mobile/.env.prod
- packages/mobile/.env.stage
- packages/web/.env/.env.prod
- packages/web/.env/.env.stage
s.audius.co configured for this on cloudflare
vs. staging on web & mobile
> [C-1782] Use proxy for sentry dsn

- packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
Avoid showing favorite/repost button status as active if owner
> [C-1960] Do not show favorite/repost on own

- packages/mobile/src/components/offline-downloads/DownloadStatusIndicator.tsx
Wrap rive in view so it aligns properly
> [C-1991] Fix downloading rive animation location

- packages/mobile/src/components/offline-downloads/DownloadToggle.tsx
Disable downloading from toggle when offline
Simulator by dispatching UNREACHABLE action
> [C-1938] Disable downloading from toggle when offline

- packages/common/src/models/Track.ts
- packages/common/src/store/collectibles/selectors.ts
- packages/mobile/src/screens/edit-track-screen/EditTrackNavigator.tsx
- packages/mobile/src/screens/edit-track-screen/components/CollectibleGatedAvailability.tsx
- packages/mobile/src/screens/edit-track-screen/components/HiddenAvailability.tsx
- packages/mobile/src/screens/edit-track-screen/components/PublicAvailability.tsx
- packages/mobile/src/screens/edit-track-screen/components/SpecialAccessAvailability.tsx
- packages/mobile/src/screens/edit-track-screen/fields/TrackVisibilityField.tsx
- packages/mobile/src/screens/edit-track-screen/screens/ListSelectionScreen.tsx
- packages/mobile/src/screens/edit-track-screen/screens/NFTCollectionsScreen.tsx
- packages/mobile/src/screens/edit-track-screen/screens/TrackAvailabilityScreen.tsx
- packages/web/src/components/track-availability-modal/CollectibleGatedAvailability.tsx
- packages/web/src/components/track-availability-modal/SpecialAccessAvailability.tsx
- packages/web/src/components/track-availability-modal/types.ts
First part in a series of PRs that will end up with premium track upload being a feature on mobile.
Merges into https://github.com/AudiusProject/audius-client/pull/2722
Has to do with track upload which is a critical part of the app.
Local mobile app against stage and against prod.
N/A
Existing premium content feature flags, including the ios and android feature flags.
> [PAY-777] Add premium content track upload on mobile - Part 1

- packages/mobile/src/screens/favorites-screen/DownloadProgress.tsx
Only listen to success to show completed downloads in progress bar
> Fix download counter in error state

- packages/mobile/src/services/offline-downloader/offline-sync.ts
> C-1989 Fix "Download is not re-starting even though there are still many tracks that need to be downloaded"

- packages/mobile/src/services/offline-downloader/offline-downloader.ts
Fixes case where after removing favorite downloads, favorited collection tracks still appear to be downloaded
> [C-1985] Remove collection tracks when removing favorites

- packages/web/src/components/data-entry/FormTile.js
- packages/web/src/components/data-entry/FormTile.module.css
- packages/web/src/components/modal-radio/ModalRadio.module.css
- packages/web/src/components/modal-radio/ModalRadioGroup.tsx
- packages/web/src/components/modal-radio/ModalRadioItem.tsx
- packages/web/src/components/remix-settings-modal/ConnectedRemixSettingsModal.tsx
- packages/web/src/components/remix-settings-modal/RemixSettingsModal.module.css
- packages/web/src/components/remix-settings-modal/RemixSettingsModal.tsx
- packages/web/src/components/remix-settings-modal/RemixSettingsModalTrigger.module.css
- packages/web/src/components/remix-settings-modal/RemixSettingsModalTrigger.tsx
- packages/web/src/components/switch/Switch.tsx
- packages/web/src/components/track-availability-modal/CollectibleGatedAvailability.tsx
- packages/web/src/components/track-availability-modal/HiddenAvailability.tsx
- packages/web/src/components/track-availability-modal/PublicAvailability.tsx
- packages/web/src/components/track-availability-modal/SpecialAccessAvailability.tsx
- packages/web/src/components/track-availability-modal/TrackAvailabilityModal.module.css
- packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
- packages/web/src/components/track-availability-modal/types.ts
- packages/web/src/components/track/PremiumTrackSection.tsx
Add new remix settings and handle relationship with premium track availability settings.
Will merge to main after https://github.com/AudiusProject/audius-client/pull/2752 is merged into this one.
track upload flow
local dapp v stage
test remix settings work as currently expected
set track as premium, check remix settings state
set track as remixabled, check track availability state
n/a
exisiting premium content feature flags
> [PAY-866] Add new remix settings - Part 1

- packages/mobile/src/screens/collection-screen/CollectionHeader.tsx
- packages/mobile/src/screens/favorites-screen/DownloadFavoritesSwitch.tsx
- packages/mobile/src/screens/favorites-screen/DownloadProgress.tsx
Download toggle should show up when offline & you have downloaded the thing.
> [C-2006] Fix download toggle when offline

- packages/mobile/src/store/offline-downloads/sagas.ts
Make sure we download local saves (saves this session) in addition to newly added playlist tracks
Download toggle on:
- Favorite trending track
- See it immediately gain download icon & show up in favorites
Download toggle off:
- Favorite trending track
- Doesn't get downloaded
> [C-1921] Make sure to download local saves

- packages/stems/src/components/Modal/Modal.tsx
Fixes bug introduced in #2691 🤦 
> [C-2036] Fix modals not closing on click outside

- packages/common/package-lock.json
- packages/common/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/web/package-lock.json
- packages/web/package.json
> Update sdk to v1.0.45

- packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
Testing component leaked into main
> Remove clear offline downloads button

- packages/common/src/services/remote-config/feature-flags.ts
Prepare flag for release
default: true is necessary for offline cases
> Set offline mode flag default true

- packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/watchReachability.ts
Good to be safe.
Companion PR to https://github.com/AudiusProject/audius-client/pull/2854
> Ensure queue always starts back up

- packages/common/src/services/oauth/formatSocialProfile.ts
- packages/web/src/common/store/pages/signon/sagas.js
- packages/web/src/pages/sign-on/components/ProfileForm.tsx
Superset of twitter/insta/tiktok
twitter: 15 chars, A-Z0-9
insta: 30 chars, A-Z0-9._
tiktok: 24 chars, A-Z0-9._
Entity mgr supports this now. Made account on stage.
> Update handle spec

- packages/mobile/src/screens/settings-screen/AboutScreen.tsx
> Show package version on AboutScreen

- packages/mobile/src/services/audius-sdk.ts
Mobile local/staging builds were using prod nodes in SDK. Use proper config to remedy.
> Fix SDK bootstrap for mobile

- packages/web/src/store/application/ui/buy-audio/sagas.ts
Fix for failing typecheck (locally anyway) with the u64/BN mismatch. (u64 extends BN)
> Use u64 on buy-audio/sagas to fix typecheck

- packages/mobile/src/services/audio-player/NativeMobileAudio.ts
- packages/web/src/common/store/player/sagas.ts
Small update to fix the audio class in mobile to match the type
N/A
N/A
N/A
N/A
> Update audio player class in mobile to match the type and make small update to playback rate saga

- packages/web/src/common/store/cache/collections/utils/processAndCacheCollections.ts
Explore collections aren't loading from 
https://github.com/AudiusProject/audius-client/issues/2679
Probs some other impacted stuff, but seems straight forward of a fix. Going to go thru that PR more deeply so I understand
Local vs prod
> Fix user collections check

- packages/common/src/services/remote-config/feature-flags.ts
New flag: https://app.optimizely.com/v2/projects/18140642080/features/23305470307/rules
> Rename TikTok video feature flag

- packages/mobile/ios/AudiusReactNative/Info.plist
- packages/mobile/ios/Podfile
- packages/mobile/ios/Podfile.lock
- packages/mobile/src/components/share-drawer/messages.ts
- packages/mobile/src/components/share-drawer/useShareToStory.tsx
> Fix TikTok share permission for iOS

- packages/mobile/ios/AudiusReactNative/Info.plist
> Permission copy change

- packages/mobile/src/store/account/sagas.ts
Fixes issue where Image.prefetch wouldn't technically do anything now that we use fast-image
> [C-2197] Fix image prefetch to work with fast-image

- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDownloadButtons.tsx
- packages/web/src/components/data-entry/FormTile.js
- packages/web/src/components/download-buttons/DownloadButtons.tsx
- packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
- packages/web/src/components/track/GiantTrackTile.js
- packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
- packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
Hide download buttons on track page and upload for gated tracks.
no
n/a
existing
> [PAY-943] - Filter out download options for gated track

- packages/mobile/src/utils/routes.tsx
Issue where we had audius.corac instead of audius.co/rac
> Fix collectibles route

- packages/web/src/services/audio-player/AudioPlayer.ts
STREAM_MP3 broken because even though it is safari, instagram changes user agent.
> [C-2193] Fix webview audio players on ios

- packages/mobile/src/components/details-tile/DetailsTile.tsx
> Fix track play button

- packages/common/src/services/remote-config/defaults.ts
- packages/common/src/services/remote-config/types.ts
- packages/web/src/components/tipping/tip-audio/SendTip.tsx
- packages/web/src/components/tipping/tip-audio/TipAudio.module.css
- packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
- packages/web/src/pages/audio-rewards-page/AudioRewardsPage.module.css
- packages/web/src/pages/audio-rewards-page/AudioRewardsPage.tsx
Adds ability to make a notice for app features using Solana that service is degraded via optimizely
> hotfix: Add notice when Solana/$AUDIO features are degraded

- packages/mobile/src/screens/audio-screen/AudioScreen.tsx
- packages/mobile/src/screens/tip-artist-screen/DegradationNotice.tsx
- packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx
Add notice to mobile when Solana services ($AUDIO services) are degraded
see also #2928 
> hotfix: Add Solana/ degradation notice to mobile

- packages/common/src/utils/chatUtils.ts
- packages/mobile/src/assets/images/ChatTail.svg
- packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
- packages/web/src/pages/chat-page/components/ChatMessageList.tsx
- Chat tails
- Unread messages indicator
- Fetch more messages when user scrolls to top.
Need some guidance on this before merging - see comments.
- There is a white line in the chat tail where the svg path and rect are separated.
Android emulator
> [PAY-920] Chat tails, unread indicator

- packages/web/src/components/tipping/tip-audio/TipAudio.module.css
> [QA-369] Fix tip modal without Solana notice

- packages/common/src/models/Analytics.ts
- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/common/src/store/collectibles/selectors.ts
- packages/common/src/store/pages/track/actions.ts
- packages/common/src/store/premium-content/sagas.ts
- packages/common/src/store/premium-content/slice.ts
- packages/mobile/src/components/audio/Audio.tsx
- packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
- packages/web/src/common/store/pages/track/sagas.js
- packages/web/src/components/track/GiantTrackTile.module.css
- packages/web/src/components/track/PremiumTrackSection.tsx
- packages/web/src/components/track/desktop/BottomRow.tsx
- packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
- packages/web/src/components/track/desktop/TrackTile.module.css
- packages/web/src/components/track/desktop/TrackTile.tsx
- packages/web/src/components/track/mobile/TrackTile.tsx
- Dismiss locked content modal on signup redirect
- Dismiss locked content modal on send tip click
- Add ellipsis menu to gated track tiles and fix click behavior
- Update follow and send tip analytics
- and more fixes...
existing
> [PAY-949][PAY-950][PAY-958][PAY-957] Gated content QA fixes

- packages/common/src/services/explore/Explore.ts
- packages/web/src/common/store/pages/explore/exploreCollections/sagas.ts
Updates the client's request to /v1/full/playlists/top to include the encoded user id
NOTE: Pending libs update and version update
Ran against staging and verified that the encoded user_id was a part of the request to the endpoint
> Fix playlist top endpoint with user id

- packages/common/src/services/opensea-client/OpenSeaClient.ts
- packages/web/src/common/store/profile/sagas.js
- packages/web/src/components/collectibles/components/CollectiblesPage.tsx
- fix duplicate nfts
- fix nft show/hide and drag n drop
- exclude nfts that user does not own anymore
local dapp vs prod. tested `leontis` and `secretPANDA007` accounts.
> [PAY-967][PAY-974] Fix nft issues

- packages/common/src/store/storeContext.ts
- packages/web/package-lock.json
- packages/web/src/common/store/notifications/sagas.ts
- packages/web/src/common/store/player/sagas.ts
- packages/web/src/common/store/social/users/sagas.ts
- packages/web/src/store/storeContext.ts
Unifies getFeatureEnabled types so our sagas have a more sane time getting a simple flag :)
> Fix get feature enabled types

- packages/web/src/common/store/lineup/sagas.js
Removes premium content from lineups / store entirely if the feature flag is disabled
Tested on web stage by looking at feed/profile pages. Need to double check mobile.
> [PAY-980] Treat premium content as deleted in lineups if feature flags disabled

- packages/web/src/common/store/lineup/sagas.js
> Fix useContext

- packages/web/src/components/track/PremiumTrackSection.tsx
Fixes issue where the links were not opening correctly
> [PAY-981] Add protocol to external collection links

- packages/web/src/common/store/lineup/sagas.js
> Fix wait for remote config

- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDownloadButtons.tsx
- packages/web/src/components/data-entry/FormTile.js
- packages/web/src/components/download-buttons/DownloadButtons.tsx
- packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
- packages/web/src/components/track/GiantTrackTile.js
- packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Enable downloading of track if user has access
Local dapp + mobile app vs stage
> [PAY-1008] - Gated track download by access

- packages/web/src/components/track-availability-modal/CollectibleGatedAvailability.tsx
- packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
- packages/web/src/components/track-availability-modal/types.ts
The artist should not be able to modify nft collection on which a track is gated after the track is uploaded i.e. on track edit
local web dapp vs stage
> [PAY-1009] - Fix editing of nft gate after upload

- packages/web/src/components/track-availability-modal/CollectibleGatedAvailability.module.css
Fixes the dropdown input getting blurred after clicking on it when you've already selected an option.
> [PAY-996] Fix dropdowns closing immediately in availability UI

- packages/web/src/pages/upload-page/components/EditPage.js
Validation errors weren't showing up on first submit because we were doing two `setStates` in sequence where the second one depended on the result of the first
> [C-2261] Fix upload form validation

- packages/web/src/components/image-selection/ImageSelectionPopup.js
- packages/web/src/components/image-selection/ImageSelectionPopup.module.css
Fix NFT images loading by using `complete` property in conjunction with `onLoad`
> [PAY-976] Fix NFT picker for artwork

- packages/common/src/models/Analytics.ts
- packages/common/src/store/premium-content/sagas.ts
- packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
- packages/mobile/src/store/wallet-connect/sagas/connectNewWalletSaga.ts
- packages/mobile/src/store/wallet-connect/sagas/signMessageSaga.ts
- packages/web/src/common/store/pages/token-dashboard/associateNewWallet.ts
- packages/web/src/common/store/pages/token-dashboard/checkIsNewWallet.ts
- packages/web/src/common/store/social/tracks/recordListen.ts
- packages/web/src/common/store/upload/sagas.js
- packages/web/src/components/track/PremiumTrackSection.tsx
- packages/web/src/store/token-dashboard/connectNewWalletSaga.ts
- gated track upload
- unlock actions
- unlocked gated tracks
- gated track listens
- connect wallet events
- errors
local dapp v stage, and checked amplitude for metrics
> [PAY-826] Add gated track and connect wallet metrics

- packages/web/src/components/track/GiantTrackTile.js
- packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
> [PAY-905] Hide embed option for premium tracks

- packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Fixes spacing issue on track screen when track is special access.
Android emulator against stage. Confirmed unlocked + normal tracks look fine.
> [PAY-1014] Fix spacing on special access track screen

- packages/web/src/common/store/lineup/sagas.js
> Wait for remote config

- packages/mobile/src/screens/edit-track-screen/components/CollectibleGatedAvailability.tsx
Fix lint error on a recent commit.
Passes lint locally.
> Fix lint on CollectibleGatedAvailability.tsx

- packages/common/src/hooks/usePremiumContent.ts
We're not TBD on user access when a user isn't signed in, so `isUserAccessTBD` should be false.
~~Might flicker premium tracks as "locked" until the account is set in the store for tracks that the user _does_ have access to? Will test~~
This seems to be a non issue- lineups are generally loaded after accounts are. Also would only happen on very initial load.
Tested using local prod build against some of the accounts we were seeing infinite load on LP
*Are all new features …
> Fix lineups with premium content infinite loading for signed out users

- packages/web/src/components/modal-radio/ModalRadioItem.module.css
- packages/web/src/components/track-availability-modal/CollectibleGatedAvailability.module.css
> [PAY-988] [PAY-995] Fix premium content modal issues

- packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
> Remove DMs button temporarily

- packages/mobile/src/hooks/useIsGatedContentEnabled.ts
> Fix general gated content flag on mobile

- packages/mobile/android/app/build.gradle
- packages/mobile/ios/AudiusReactNative/Info.plist
- packages/mobile/src/screens/edit-track-screen/components/CollectibleGatedAvailability.tsx
- packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Hide chats UI in profile screen + bump app versions for release
Local ios against stage: 
> Hide chat UI + bump app versions

- packages/mobile/src/components/audio/Audio.tsx
Fixes issue where playing a queue with a hidden track triggers a runtime error in Audio.tsx. This fixes that error and patches the TrackPlayer flow by stubbing out the hidden track with placeholder data. This stops the error but has a sideeffect of stopping the queue and displaying an empty track. This is what happens in desktop, and can only be fixed once discovery-provider filters unlisted tracks from feed and collection endpoints.
> [C-2280] Fix error when playing queue with private track

- packages/mobile/src/screens/settings-screen/AccountVerificationScreen.tsx
> [C-2288] Fix auth error state check

- packages/mobile/android/app/build.gradle
- packages/mobile/ios/AudiusReactNative/Info.plist
I thought this commit was pushed up with the notifications changes, my b
> Upgrade mobile app versions for release

- .circleci/src/commands/@mobile-commands.yml
Previous command was getting all differences between the PR branch and latest main, so it was giving false positives sometimes when the PR branch was not up to date with main.
New command uses the diffs between the common ancestor of PR branch and main.
> Fix native code changes CI comment C-2305

- packages/mobile/src/components/core/FlatList.tsx
- packages/mobile/src/components/core/SectionList.tsx
- packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
Fixes issue where a @ts-ignored line had a typo... :(
also fixes introduced type issue with overflow menus.
> Fix collapsible list typo

- packages/web/src/components/inbox-settings-modal/InboxSettingsModal.module.css
- packages/web/src/components/inbox-settings-modal/InboxSettingsModal.tsx
I'm not sure we really need sagas for this? May change mind after seeing how we read the current permission status (needs to be spec'd still, gap in our planning)
> [PAY-940] Save permissions in chat permission dialog

- .circleci/src/commands/@web-commands.yml
Fixes win/linux CI builds
Tested via ssh'd job. This works even if nvm is installed and will ensure consistent nvm version on mac too.
> Add nvm install step

- packages/mobile/src/services/audius-backend-instance.ts
Original: https://github.com/AudiusProject/audius-client/pull/3036/files
> Hard code entity manager prod address for now

- packages/mobile/src/services/audius-backend-instance.ts
Reverts AudiusProject/audius-client#3039
> Revert "Hard code entity manager prod address for now"

- packages/common/src/store/pages/chat/middleware.ts
Fix bug in chat middleware that caused it to never disconnect.
Local ios simulator against stage.
> Fix chat middleware

- packages/web/src/common/store/confirmer/sagas.ts
Temporary fix, confirm if block has passed in cases where a blockhash has reverted. 
> Confirm if block passed

- packages/web/src/common/store/tipping/sagas.ts
`erc_wallet` doesn't always exist. prefer to use `wallet` instead
> Use wallet instead of ERC wallet

- packages/common/src/store/premium-content/sagas.ts
- packages/common/src/store/social/users/actions.ts
- packages/common/src/store/tipping/slice.ts
- packages/common/src/store/tipping/types.ts
- packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
- packages/web/src/common/store/tipping/sagas.ts
- packages/web/src/components/track/PremiumTrackSection.tsx
Only show confetting when unlocking from how to unlock section on track page or modal
Tested on local dapp v stage
> [PAY-1061] - Only show confetting when unlocking from how to unlock section

- packages/web/src/common/store/tipping/sagas.ts
Not sure why it was added, but it broke tipping. Removing fixes it.
local web app vs stage.
> Remove random line

- packages/mobile/src/screens/edit-track-screen/EditTrackNavigator.tsx
- packages/mobile/src/screens/edit-track-screen/components/CollectibleGatedAvailability.tsx
- packages/mobile/src/screens/edit-track-screen/components/SpecialAccessAvailability.tsx
- packages/mobile/src/screens/edit-track-screen/components/types.ts
- packages/mobile/src/screens/edit-track-screen/screens/TrackAvailabilityScreen.tsx
- packages/mobile/src/screens/edit-track-screen/types.ts
- packages/mobile/src/screens/upload-screen/screens/CompleteTrackScreen.tsx
- packages/web/src/components/track-availability-modal/SpecialAccessAvailability.module.css
- packages/web/src/components/track-availability-modal/SpecialAccessAvailability.tsx
- packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
- Fix issues w.r.t. gated mobile track upload and edit states
- Update disabled special access states
- Update availability modal scroll behavior with fixed "Done" button
local web and mobile apps vs stage
> [PAY-1056] - More gated content updates and fixes

- packages/mobile/ios/Podfile.lock
- packages/web/package-lock.json
- packages/web/package.json
I won't cherry-pick this anywhere, but rather run the same thing on release branch to ensure I don't accidentally update any other deps etc.
> Update @jup-ag/core to 2.0.0-beta.9

- packages/web/src/pages/chat-page/components/ChatMessageList.tsx
- packages/web/src/pages/chat-page/components/SendMessagePrompt.module.css
- packages/web/src/pages/chat-page/components/SendMessagePrompt.tsx
> [PAY-927] DMs: Empty messages state

- packages/mobile/ios/Podfile.lock
- packages/web/package-lock.json
I probably busted this in #3072 
> Clean up NPM package lock

- packages/common/package-lock.json
- packages/common/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/web/package-lock.json
- packages/web/package.json
See: https://github.com/AudiusProject/audius-protocol/pull/4983
> Update SDK to 2.0.3-beta.0

- packages/common/src/store/pages/chat/selectors.ts
- packages/web/package-lock.json
- packages/web/src/components/now-playing/NowPlaying.tsx
Mimics logic seen in https://github.com/AudiusProject/audius-client/commit/59862ad901bf95122a7dab215dfe3c5583910464 to get the playback rate for the scrubber
Also includes some package lock changes that seemed to have happened on `npm i` despite not occurring on the branch I just merged #3066 after merging latest main and cleaning node modules 😕 😵‍💫 
It hasn't, honestly. But the CI build is broken!
> Fix broken Main build due to typeerror

- packages/mobile/src/components/lineup-tile/LineupTile.tsx
- packages/mobile/src/components/lineup-tile/LineupTileTopRight.tsx
- packages/mobile/src/screens/edit-track-screen/components/SpecialAccessAvailability.tsx
- packages/mobile/src/screens/edit-track-screen/screens/TrackAvailabilityScreen.tsx
- packages/web/src/components/track-availability-modal/TrackAvailabilityModal.tsx
- packages/web/src/components/track/EditTrackModal.js
- packages/web/src/components/track/PremiumTrackSection.tsx
- Allow hidden -> gated track edits
- Prioritize artist pick dog ear on mobile track tile
- Remove gated content label on mobile track tile, only keep icon
- Fix copy
local web and mobile apps vs stage
existing
> [PAY-1000][PAY-1084][PAY-1096][PAY-1097][PAY-1098] - More gated content fixes

- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
#3066 removed `getChatMessagesStatus` and `getChatMessagesSummary`
> DMs: Fix broken typecheck on main

- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
More updates after removing chat status selector.
ios simulator on staging.
> Use chat.messagesStatus instead of selector

- packages/mobile/src/components/gated-content-upload-prompt-drawer/GatedContentUploadPromptDrawer.tsx
- packages/web/src/components/gated-content-upload-prompt-modal/GatedContentUploadPromptModal.tsx
- packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
- Remove mobile web track page gated content feature flag
- Also fix blog post link for upload gated track prompt modal
local web app vs prod
> Fix upload prompt modal learn more url

- packages/web/src/components/image-selection/ImageSelectionPopup.js
Was missing a filter to make sure all visible collectibles are not null/undefined.
Tested on prod build in subdomain
> Fix visible collectibles for upload popup

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/common/src/services/remote-config/feature-flags.ts
> [C-2378] Add upload v2 feature flag

- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Now that we're using `createEntityAdapter` we need to check if `chat.messagesStatus` is undefined as well as idle.
Local ios sim + stage
> Check if messagesStatus undefined in ChatScreen

- packages/web/src/components/nav/desktop/NavColumn.tsx
Fixes issue where clicking the notification button when the notification panel is open does not close it.
you were right @raymondjacobson
> [C-2386] Fix notification button not toggling panel

- packages/mobile/src/components/audio/Audio.tsx
- packages/web/src/common/store/player/sagas.ts
> Always include user signature for stream

- packages/web/src/common/store/tipping/sagas.ts
most foolproof for API changes
> Tip using both erc_wallet and wallet

- packages/common/src/store/playback-position/sagas.ts
> Switch to 1s

- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
ChatScreen contents move upwards to avoid the on-screen keyboard.
Both ios and android emulators against stage.
> [PAY-906] Mobile chats KeyboardAvoidingView

- packages/mobile/src/app/Drawers.tsx
- packages/mobile/src/components/supporters-info-drawer/SupportersInfoDrawer.tsx
- packages/mobile/src/components/supporters-info-drawer/index.ts
- packages/mobile/src/screens/edit-track-screen/EditTrackNavigator.tsx
- packages/mobile/src/screens/edit-track-screen/components/SpecialAccessAvailability.tsx
- packages/mobile/src/store/drawers/slice.ts
Add supporters info drawer.
mobile app vs stage
> [PAY-1102] - Add supporters info drawer

- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Removes the "Done" row from the ios textinput keyboard. 
Local ios against stage.
> [PAY-1111] Remove "Done" row on ios keyboard for mobile chats

- packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Make the flat list content containers use full height. Now chat messages appear at the bottom of the screen first.
Local ios against stage.
> [PAY-1031] Mobile chat list views use full height

- packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
- packages/mobile/src/store/store.ts
Now new messages will appear on mobile chats!
Local ios stage.
> [PAY-1027] Mobile chat websockets

- packages/mobile/src/screens/profile-screen/MessageButton.tsx
- packages/mobile/src/screens/profile-screen/SubscribeButton.tsx
Change message and notif subscribe buttons on profile screen to dark grey.
ios stage
https://user-images.githubusercontent.com/3893871/228719409-3f1c048c-955e-4b25-a1dc-b6c034f81ff5.mp4
> [PAY-1038] Fix mobile profile page button borders

- .circleci/src/workflows/mobile.yml
- packages/mobile/ios/fastlane/Fastfile
> Fix app store version fetched from Apple in Fastlane being out of date first 24h after new release C-2397

- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Scrolling was broken on mobile chats
> [PAY-1123] Fix mobile chat scroll being stuck

- packages/common/src/services/remote-config/remote-config.ts
- packages/mobile/src/services/remote-config/remote-config-instance.ts
- packages/web/src/services/remote-config/remote-config-instance.ts
https://docs.developers.optimizely.com/experimentation/v3.1.0-full-stack/docs/pass-in-audience-attributes-swift
Looks like undefined isn't a valid value for an attribute, but null is fine
Issue: https://audius-internal.slack.com/archives/C0322K9M048/p1680195739448289
> Optimizely attributes - use null if empty instead of undefined

- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Pressing on user badge in header in chat screen navigates to profile.
> [PAY-1039] Mobile chat header navs to profile

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/common/src/services/remote-config/feature-flags.ts
- packages/common/src/store/cache/users/reducer.ts
- packages/common/src/store/pages/chat/middleware.ts
- packages/common/src/store/playlist-updates/playlistUpdatesSagas.ts
- packages/common/src/store/playlist-updates/playlistUpdatesSelectors.ts
- packages/common/src/store/premium-content/sagas.ts
Cleans up playlist-update feature flags now that this is live in prod
Do we still need to save to identity?
> [C-2398] Clean up playlist-update feature flags

- packages/common/src/store/cache/collections/reducer.ts
- packages/common/src/store/cache/tracks/reducer.ts
- packages/common/src/store/cache/users/reducer.ts
Broken since https://github.com/AudiusProject/audius-client/pull/3117
toLower the keys so cache hits properly
> [QA-443] Fix cache case matching for handles and permalinks

- packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
[PAY-1041][PAY-1040][PAY-1126]
- Make loading spinner smaller
- Correct loading state, spinner doesn't appear on first load
- Fix black underlay color on row selection
> [PAY-1041][PAY-1040][PAY-1126] Mobile search users screen improvements

- packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
Fixes bug where scrolling would get stuck on ChatListScreen.
> Fix scrolling on ChatListScreen

- README.md
- packages/mobile/README.md
Updates to readme discussed on the call.
- Moved dependencies paragraph to before `npm i` paragraph.
- Added list of dependencies.
- Removed `sudo` in mobile readme for gem installation.
> Update readme with deps, remove sudo

- packages/common/src/services/audius-backend/AudiusBackend.ts
> allow create notification to handle playlist id as array or int

- packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
> [C-2223] Flex on Finnuh

- packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx
- packages/mobile/src/screens/track-screen/TrackScreenRemixes.tsx
Fixes issue where track remix images were misaligned.
> [C-2434] Fix remix image styles

- packages/web/src/common/store/queue/sagas.ts
- packages/web/src/common/store/social/tracks/sagas.ts
- packages/web/src/services/audio-player/AudioPlayer.ts
I believe this fixes it. Need to test the 💩 out of it.
> [C-2452] Remove audio before setting new one

- packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx
- packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
- packages/mobile/src/screens/edit-track-screen/components/CollectibleGatedAvailability.tsx
- packages/mobile/src/screens/edit-track-screen/components/HiddenAvailability.tsx
- packages/mobile/src/screens/edit-track-screen/components/SpecialAccessAvailability.tsx
- packages/web/src/components/track/GiantTrackTile.module.css
- packages/web/src/components/track/PremiumTrackSection.tsx
- Fix how to unlock section description spacing
- Use artist popover for premium track owner
- Fix width of selection content in mobile track availability screen
https://user-images.githubusercontent.com/9600175/232115976-ffce5ce9-18df-4e6f-92e5-da0ce4df5482.mov
local dapp and mobile app v stage
> [PAY-986][PAY-1087][PAY-1091] Fix a bunch of UI issues

- packages/mobile/src/store/oauth/sagas.ts
- packages/web/src/components/instagram-auth/InstagramAuth.tsx
- packages/web/src/components/twitter-auth/TwitterAuth.tsx
Quick PR to get a bit more visibility into errors from insta/twitter
> Improve oauth errors/logging

- packages/common/src/utils/streaming.ts
> Fix lint in common

- packages/web/src/pages/App.js
- packages/web/src/pages/modals/Modals.tsx
Fixes issue where dev-mode hot-key modals didn't register their hotkey hook since they were not rendered. Fixed by reserving a space for them in the Modals component
> Fix dev-mode hot-key modals

- packages/web/src/common/store/player/sagas.ts
Causing fatal saga error on startup
> Fix call to player.getPosition

- packages/web/src/store/configureStore.ts
extends the redux history to 1000 actions before they start to fall off
None, dev tool
My redux dev tools has tons of actions now!
N/A
N/A
> C-2502: extend store history

- packages/web/craco.config.ts
Fixes issue where multiple instances of react-router were present, this also improves perf!
> Fix react-router issues

- packages/stems/src/components/Scrollbar/Scrollbar.tsx
> put back the ref

- packages/common/src/store/notifications/notificationsSlice.ts
Resets notification state when sign-out action is dispatched
> [C-1998] Reset notification state on sign-out

- packages/common/package-lock.json
- packages/common/package.json
- packages/common/src/store/pages/chat/sagas.ts
- packages/common/src/store/pages/chat/selectors.ts
- packages/common/src/store/pages/chat/slice.ts
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/components/inbox-settings-modal/InboxSettingsModal.tsx
- packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
- packages/web/src/pages/profile-page/ProfilePageProvider.tsx
Consume https://github.com/AudiusProject/audius-protocol/pull/5153
fixes linking libs
manually - local web against stage
> [PAY-1187][PAY-1190][PAY-1176] Update SDK: User Chat Permissions to match backend

- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Haptic feedback when user opens chats reactions popup.
local ios stage device
> [PAY-1158] Haptic feedback when opening chat reactions popup

- packages/web/src/pages/modals/Modals.tsx
Stripe on ramp modal must not be conditionally rendered
Haven't been able to test locally
> hotfix: Stripe onramp modal

- packages/mobile/src/screens/wallet-connect/components/useSolanaPhoneAuthorization.ts
Dev-net was hard-coded. Our staging/test env uses mainnet-beta anyway, so this should be safe.
> Fix devnet in wallet authorize for saga phone

- packages/common/src/schemas/index.ts
> Fix ai attrib upload

- packages/web/src/pages/ai-attributed-tracks-page/AiPageProvider.tsx
> Redirect if not allowed ai

- packages/mobile/src/screens/notifications-screen/Notifications/TastemakerNotification.tsx
- packages/web/src/components/notification/Notification/TastemakerNotification.tsx
> Fix taste maker copy

- packages/common/src/services/audius-api-client/helper.ts
- packages/web/src/common/store/pages/search-page/sagas.js
- packages/web/src/common/store/search-ai-bar/sagas.ts
- packages/web/src/common/store/search-bar/sagas.ts
Add override multimap for dispatching multiple search queries in spicey scenarios
> Add search multimap

- packages/web/src/components/notification/Notification/components/Reaction/Reaction.tsx
Increase debounce on notifs reaction
> Debounce reaction for longer on web

- packages/common/src/utils/wallet.ts
- packages/web/src/components/buy-audio-modal/components/SuccessPage.tsx
- packages/web/src/store/application/ui/buy-audio/sagas.ts
> [PAY-901] hotfix: Use SPL amounts for BuyAudio flow

- packages/web/src/store/application/ui/buy-audio/sagas.ts
> I broke main and I'm sorry

- packages/web/src/common/store/notifications/checkForNewNotificationsSaga.ts
Improves `checkForNewNotifications` flow by making better checks for if notifications have changed. right now its really flaky because it compares notification order, which is incorrect since the api is not always accurate with this compared to the slice. By checking for "new" notifs or checking existing ones, instead of caring about index, this makes this much less flaky.
> [C-2560] Improve checking for new notifs

- packages/web/src/common/store/profile/sagas.js
Small update to fetchProfile that gates `fetchPermission` around `CHAT_ENABLED` flag. this error is showing up in sentry, even if it's minor :))
> Update fetchPermission condition

- packages/common/src/store/pages/chat/slice.ts
> DMs: Fix store bug sending messages

- packages/web/src/pages/chat-page/components/CreateChatModal.tsx
Was poking around here and decided to update this while I was in the code
> [PAY-1207] Use Followers instead of Mutuals on compose chat modal

- packages/web/src/services/track-download.ts
For release branch only. Main already has this fix as part of a larger commit that should go through QA.
> [HOTFIX] Fix saga download error

- packages/common/src/store/pages/chat/sagas.ts
- packages/common/src/store/pages/chat/selectors.ts
- packages/common/src/store/pages/chat/slice.ts
- packages/web/src/pages/chat-page/components/ChatMessageList.tsx
Still some more bugs here to iron out I think, but this should help?
> DMs: Fix unread indicator not going away

- packages/mobile/src/components/core/KeyboardAvoidingView.tsx
- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Forgot to pass in height offset of 0 when play bar is not showing.
Also fixes errors complaining about subscription fns being undefined.
> Fix keyboard occluding textinput in mobile chat screen

- packages/web/src/common/store/account/sagas.js
small update to not fetch blockees/blockers when chat feature disabled
> Prevent fetchBlockees/blockers when chat disabled

- packages/web/src/services/audio-player/AudioPlayer.ts
* Clear the buffering timeout when a new audio source loads
If the source changed before the `canplay` event fired, only the second buffering timeout would be cleared. Now the timeout is always cleared when the source changes
* Pull things out of the `_initContext` function to make the control flow more linear
> [C-2451] Fix infinite buffering in audio player

- package.json
- packages/common/package-lock.json
- packages/common/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/mobile/src/services/audius-sdk.ts
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/services/audius-sdk/audiusSdk.ts
Updates sdk latest, bringing in node_selector changes
Improves install script to make sure node_modules for it are removed, forcing lock changes to occur.
> Upgrade sdk to beta.16, update install script

- packages/common/package-lock.json
- packages/common/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/web/package-lock.json
- packages/web/package.json
> Update sdk to 2.0.3-beta.18

- packages/mobile/src/components/overflow-menu-drawer/ProfileOverflowMenuDrawer.tsx
- packages/web/src/components/menu/UserMenu.tsx
- packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
Fixes issue where clicking "share" option in overflow menu wouldnt open up the share drawer
> [QA-488] Fix share overflow menu drawer

- packages/mobile/src/screens/chat-screen/ChatListItem.tsx
Adds unread count tag to chat list items. Also removes leading whitespace from messages for better message previews.
> [PAY-1208][PAY-1216] Mobile chats unread message count

- packages/mobile/src/assets/images/ChatTail.svg
- packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
Fixes mobile chat tails and updates with new tail svg.
> [PAY-1217] Mobile DMs new chat tails, fix shadow

- packages/web/src/pages/chat-page/components/ChatMessageList.tsx
> [PAY-941] Fix "1 new messages" unread tag (web)

- packages/web/src/components/inbox-settings-modal/InboxSettingsModal.tsx
Fix copy on Inbox Settings modal, make button anchored to bottom
> DMs: Update copy, scroll inbox-settings modal

- packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
previously was a bug allowing you to click on a user you're not allowed to chat
> DMs: Fix click handler in search user list for users you can't chat

- packages/web/src/components/notification/Notification/components/Reaction/Reaction.tsx
My prior change does nothing https://github.com/AudiusProject/audius-client/pull/3305/files because I don't believe the debounce is actually used.
Local vs. stage
> Fix debounce on notif reaction

- packages/common/src/store/pages/chat/selectors.ts
- packages/mobile/src/components/block-messages/BlockMessages.tsx
- packages/mobile/src/components/chat-actions-drawer/ChatActionsDrawer.tsx
Switch between block/unblock state on ProfileActionsDrawer and BlockMessagesDrawer.
> [PAY-1218] Mobile block dms drawer switches block/unblock

- packages/mobile/src/screens/chat-screen/CopyMessagesButton.tsx
Just increase the space between these components a tad so they're not overlapping.
> Increase space between chat reaction and copy message button

- packages/mobile/src/assets/images/ChatTail.svg
- packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
New chat tails without that gnarly 0.4px offset!
> [PAY-1260] New chat tails on mobile

- packages/web/src/pages/chat-page/components/ChatHeader.tsx
Fixes bug where when clicking through multiple chats, a ChatUser with no avatar / transparent background would overlay the prior avatar. Just key the component based on user_id. 
Old:
https://github.com/AudiusProject/audius-client/assets/6780028/2704da11-ee8d-424c-a604-dc4e0003deb8
New:
https://github.com/AudiusProject/audius-client/assets/6780028/e15fd92a-0b82-4fd1-962f-502827413966
None
> [PAY-935] Fix ChatHeader issue

- packages/common/src/store/pages/chat/selectors.ts
- packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
> [PAY-1272] Make desktop DM text copyable

- packages/web/src/pages/chat-page/components/ChatMessageList.tsx
- packages/web/src/pages/chat-page/components/StickyScrollList.tsx
Scrolling to bottom didn't work because we weren't passing in a threshold. 
> [PAY-1273] Fix scrolling issues

- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
- packages/mobile/src/screens/chat-screen/ChatUnavailable.tsx
Make inbox unavailable message unsticky at bottom of chat screen.
> Make mobile chat inbox unavailable message unsticky

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/web/src/common/store/profile/sagas.js
Makes editing profiles work for v2 users and/or with v2 uploads for profile pic and cover art.
None
Tested updating a v1 and v2 user locally with https://github.com/AudiusProject/audius-protocol/pull/5291. Set the storage v2 upload feature flag to true/false to test both code paths.
Make sure staging profile edits work.
No new flags
> [CON-678] v2 user profile edit

- packages/web/src/pages/chat-page/ChatPage.module.css
- packages/web/src/pages/chat-page/ChatPage.tsx
- packages/web/src/pages/chat-page/components/ChatMessageList.tsx
- packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
- packages/web/src/pages/chat-page/components/InboxUnavailableMessage.module.css
- packages/web/src/pages/chat-page/components/InboxUnavailableMessage.tsx
Also fixes regression on date styles
> [PAY-1274] DMs: Unsticky inbox unavailable message

- packages/web/src/assets/img/ChatTail.svg
- packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
> [PAY-1142] DMs: Update chat tail

- packages/web/src/pages/profile-page/ProfilePageProvider.tsx
- packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Use confirmation modal on profile page block/unblock actions
Mobile web?
> DMs: Use unblock/block confirmation modals on profile

- packages/common/package-lock.json
- packages/common/package.json
- packages/common/src/services/remote-config/feature-flags.ts
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/mobile/src/services/audius-sdk.ts
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/services/audius-sdk/audiusSdk.ts
> Bump SDK version and change walletapi to auth

- .circleci/src/jobs/@mobile-jobs.yml
- packages/mobile/package.json
This was the error: https://app.circleci.com/pipelines/github/AudiusProject/audius-client/14110/workflows/32746122-eead-45e1-9ff6-09875603407a/jobs/129343
Fixed by using cimg/* docker image instead of circleci/*
> Fix mobile native change comment C-2657

- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
TouchableOpacity on the chat screen header
https://github.com/AudiusProject/audius-client/assets/3893871/886dc1c9-1696-4139-8950-11dbadc63cb0
> [PAY-1243] Mobile chat header touchable feedback

- packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
Feature flag purple notification bubble that appears when use has unread messages behind chat feature flag
> Feature flag unread messages notif bubble

- packages/web/src/pages/chat-page/components/ChatComposer.tsx
Show the max length of the composer field if getting close
> [PAY-1288] DMs: Show max length in composer

- packages/mobile/src/app/Drawers.tsx
- packages/mobile/src/components/block-messages-drawer/BlockMessagesDrawer.tsx
- packages/mobile/src/components/block-messages-drawer/index.ts
- packages/mobile/src/components/block-messages/index.ts
- packages/mobile/src/components/chat-actions-drawer/ChatActionsDrawer.tsx
- packages/mobile/src/components/delete-chat-drawer/DeleteChatDrawer.tsx
- packages/mobile/src/components/delete-chat-drawer/index.ts
- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
- packages/mobile/src/store/chat/sagas.ts
- packages/mobile/src/store/drawers/slice.ts
Delete thread option in chat actions drawer + confirmation drawer.
Also renames block messages drawer + add useCallback.
> [PAY-1246] Mobile delete chat thread UI

- packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
Hide current user from search results
> [PAY-1297] DMs: Don't show current user in search results

- packages/web/src/components/banner/Banner.module.css
- packages/web/src/components/header/desktop/Header.js
- packages/web/src/components/header/desktop/Header.module.css
- packages/web/src/components/header/desktop/HeaderGutter.module.css
- packages/web/src/components/header/desktop/HeaderGutter.tsx
- packages/web/src/components/header/mobile/Header.module.css
- packages/web/src/hooks/usePortal.ts
- packages/web/src/pages/App.js
- packages/web/src/pages/App.module.css
- packages/web/src/pages/chat-page/ChatPage.module.css
- packages/web/src/pages/chat-page/components/ChatHeader.module.css
- packages/web/src/pages/chat-page/components/ChatHeader.tsx
- packages/web/src/pages/chat-page/components/ChatMessageList.module.css
Solved the header gutter problem by making the gutter logic from `Header.js` reusable and including it in the `ChatHeader`. 
- Also refactored this from a bunch of sloppy hooks manually manipulating the DOM to a regular React component that Portals to body.
- Handle the shadow differences on ChatsPage by allowing style overrides to the header, which are also passed to the header gutter
- Fix an old bug, shown below, where the gutter would fail to account for the height of the banner when switching pages, resulting in a "notch". Fixed by having the gutter be responsible for offsetting itself via shared context, instead of app.js doing it.
Old broken bug:
https://github.com/AudiusProject/audius-client/assets/6780028/c799798c-a68d-4d6c-841e-b426ffef03a1
New fixedness: …
> [PAY-1138] Fix headers on Chats and fix old header prod bug

- packages/web/src/components/data-entry/Input.js
Fixes issue where ...other spreading was clobbering some inputs. a proper design system input + ts will help here. for now just explicitly adding a react input prop `autoFocus`. Love how are tests are catching this
> Fix input with explicit input props

- packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
Cap text input to 10k characters.
https://fansided.com/2016/01/05/what-does-10000-characters-look-like/
> [PAY-1294] Max length for chat text input on mobile

- packages/web/src/services/audius-sdk/audiusSdk.ts
- packages/web/src/services/entity-manager.ts
Companion PR: https://github.com/AudiusProject/audius-protocol/pull/5270
> Add EM instance to SDK C-2629

- packages/mobile/src/components/delete-chat-drawer/DeleteChatDrawer.tsx
Change copy to "conversation" instead of "thread"
> Change delete thread copy to conversation on mobile

- packages/web/src/pages/chat-page/components/DeleteChatConfirmationModal.tsx
> DMs: Rename "Thread" to "Conversation"

- packages/common/src/store/pages/chat/sagas.ts
Adds a toast when chat creation fails
> [PAY-1295] DMs: Add a toast when chats fail to create

- package.json
- packages/common/package-lock.json
- packages/common/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/web/package-lock.json
- packages/web/package.json
Updates `sdk:update` script to look for latest beta
Updates SDK to latest beta
> SDK v2.0.3 beta.32

- packages/web/src/components/nav/desktop/NavPopupMenu.tsx
- packages/web/src/pages/chat-page/components/ChatHeader.module.css
- packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
- Adjusts nav menu order
- Fixes margins of chat header
- Improves reaction buttons:
1) Changes CSS hover color
2) Adds grow animation to button *and* to reaction animation if previously reacted to
3) Adds active state to reactions
https://github.com/AudiusProject/audius-client/assets/6780028/7218bb4d-f71b-429e-954e-2b44d4cfaf69
> [PAY-1330][PAY-1317][PAY-1321] Polish DMs #1

- packages/mobile/src/screens/edit-playlist-screen/CreatePlaylistScreen.tsx
- packages/web/src/common/store/playlist-library/watchReorderLibrarySaga.ts
- packages/web/src/components/edit-folder-modal/EditFolderModal.tsx
- packages/web/src/components/edit-playlist/desktop/EditPlaylistModal.tsx
- packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
- packages/web/src/components/nav/desktop/PlaylistLibrary/DeleteCollectionConfirmationModal.tsx
- packages/web/src/components/nav/desktop/PlaylistLibrary/DeleteFolderConfirmationModal.tsx
- packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.tsx
- Fixes left-nav delete-confirmation for playlists and folders.
- HOTFIX navigation issue with edit-playlist
> HOTFIX: left-nav delete-confirmation

- packages/web/src/common/store/pages/signon/sagas.js
* Using `yield*` in js without `typed-redux-saga` doesn't work. This is a pretty big gotcha
> [C-2658] Fix favorite Hot & New in sign up

- packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
- packages/mobile/src/screens/chat-screen/CopyMessagesButton.tsx
- packages/web/src/assets/styles/shadows.css
- packages/web/src/components/artist/ArtistChipFollowers.tsx
- packages/web/src/components/page/Page.module.css
- packages/web/src/components/user-badges/FollowsYouBadge.module.css
- packages/web/src/components/user-badges/FollowsYouBadge.tsx
- packages/web/src/pages/chat-page/ChatPage.module.css
- packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
Various small fixes, can review commit per commit. 
- Touches all headers
> [PAY-1324][PAY-1326][PAY-1323][PAY-1327][PAY-1331][PAY-1328][PAY-1320] DMs UI fixes 2

- packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
Update chat message shadows to match values from figma.
Would be annoying to have to add 2 views every time we wanted a component to have a shadow!
> [PAY-1337] Fix mobile chat message shadows

- .circleci/src/workflows/mobile.yml
- packages/mobile/android/fastlane/Fastfile
- packages/mobile/ios/fastlane/Fastfile
- packages/mobile/src/screens/root-screen/RootScreen.tsx
* Check for force codepush updates before checking for min client version. This is so users on older versions don't get bricked when the min version gets set
* Add the client version to the description field on codepushes
> [C-2708] Improvements around codepush & force pushing

- packages/web/src/components/data-entry/InputV2.tsx
- packages/web/src/components/search-users-modal/SearchUsersModal.module.css
- packages/web/src/components/search-users-modal/SearchUsersModal.tsx
> [PAY-1175] DMs: Autofocus, clear search, elevate placeholder

- packages/mobile/src/screens/chat-screen/ChatUnavailable.tsx
> [PAY-1355] Add space before learn more link in inbox unavailable message

- packages/common/package-lock.json
- packages/common/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/web/package-lock.json
- packages/web/package.json
Doing this change directly on release branch for minimal conflicts, but want other eyes to double check lock files are ok
> Update SDK to revert comms health changes

- packages/web/src/common/store/account/sagas.js
- packages/web/src/common/store/cache/collections/commonSagas.js
- packages/web/src/common/store/lineup/sagas.js
Remove yield* in js files, these are only needed for typed-redux-saga
> Remove yield* in js files

- packages/common/package-lock.json
- packages/common/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/web/package-lock.json
- packages/web/package.json
> Upgrade sdk to 2.0.3-beta.36

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/common/src/services/remote-config/feature-flags.ts
Flags are fully turned on but optimizely seems a little flaky. Going to codepush this in prod before the real fix completely removing flags is released on Wednesday
> Default true cid metadata flags

- packages/common/src/hooks/chats/useCanSendMessage.ts
- packages/common/src/store/pages/chat/sagas.ts
- packages/common/src/store/pages/chat/selectors.ts
- packages/common/src/store/pages/chat/slice.ts
- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
- Defaults users to chatable before they're loaded in
- Navigate optimistically to chats from compose modal
> [PAY-1342][PAY-1360] DMs: Show users as chat unlocked by default, optimistic chat navigation

- packages/common/src/store/account/slice.ts
- packages/web/src/common/store/account/sagas.js
- packages/web/src/store/configureStore.ts
* Add reason to slice for sentry reports
* Handle fetch account failure specifically with a report to sentry to get more breadcrumbs
Locally vs. staging. Verified 
In sentry:
```
Fetch account failed
```
> Add reason to account slice, handle fetch account failure with sentry

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/common/src/services/explore/Explore.ts
- packages/common/src/services/wallet-client/WalletClient.ts
- packages/web/src/common/store/cache/tracks/sagas.js
- packages/web/src/common/store/cache/users/sagas.js
- packages/web/src/common/store/pages/token-dashboard/getAccountMetadataCID.ts
- packages/web/src/common/store/smart-collection/sagas.ts
- packages/web/src/components/notification/Notification/utils.ts
- packages/web/src/pages/upload-page/components/ShareBanner.tsx
- packages/web/src/store/errors/reportToSentry.ts
* Clean up unused/easily replaceable non-v1 API calls
* Document with `//TODO(C-2719)` the rest of them
* Under the radar
* Profile pages
* Signup/upload (for sanity)
* Bunch of clicking around
> [C-2719] Clean up and document non v1 usage

- packages/common/src/utils/chatUtils.ts
> [PAY-1347] DMs: Don't show unread indicator for first messages

- packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
Update disabled check for nav items to check for hidden tracks and public playlists
N/A
N/A
N/A
> [C-2461, C-2476] Prevent user from dragging hidden tracks to public playlists

- packages/web/src/components/inbox-unavailable-modal/InboxUnavailableModal.tsx
- packages/web/src/components/search-users-modal/SearchUsersModal.tsx
- packages/web/src/pages/chat-page/components/CreateChatModal.tsx
- packages/web/src/pages/chat-page/components/CreateChatUserResult.module.css
- packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
- packages/web/src/pages/modals/Modals.tsx
Adds a call to action to users that require some action to unlock tipping, eg if they're tip gated or if you've blocked them. Clicking a "disabled" user brings up the "InboxUnavailable" modal. Closing the "InboxUnavailable" modal should take you back to the search without losing its state.
https://github.com/AudiusProject/audius-client/assets/3690498/b3863312-dc57-4adb-b5b7-f07a71493e98
Opening the tip modal loses context and you can't get back to search, nor can you start the chat with the user …
> [PAY-1363] DMs: Add CTA to Create Chat user rows

- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Scroll to the bottom of the chat screen when the user navigates away while staying in the same navigation stack (eg. clicking on the screen header to nav to profile screen) then comes back.
Bit of a hack to get the unread indicator to go away in this case
Uploading Simulator Screen Recording - iPhone 14 Pro - 2023-06-07 at 16.26.01.mp4…
> [PAY-1356] Mobile chats scroll to bottom when re-entering chat screen

- packages/mobile/src/components/lineup-tile/types.ts
- packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
- packages/mobile/src/screens/chat-screen/ChatMessagePlaylist.tsx
- packages/mobile/src/screens/chat-screen/ChatMessageTrack.tsx
- packages/web/src/common/store/cache/collections/commonSagas.js
- packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx
- packages/web/src/pages/chat-page/components/ChatMessageTrack.tsx
Fix web track and playlist tiles to always load the artwork.
Fix mobile link preview bottom border bug
local web and mobile dapps vs stage
> [PAY-1366] Fix web chat tile artwork and mobile link preview bugs

- packages/web/src/common/store/tipping/sagas.ts
Waits for tip confirmation and refetches permissions for the sender/recipient after
Tested using tip gated DMs on profile page, takes roughly 20s
> DMs: Wait for tip confirmation then refetch permissions

- packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
- packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
- packages/web/src/pages/chat-page/components/ChatComposer.module.css
Can be reviewed per commit. 
@dharit-tan I got rid of your `onTouchStart={Keyboard.dismiss}` but works on simulator with software keyboard, and tested that prior to your fix, this required two presses on simulator.
> [PAY-1406][PAY-1374][PAY-1353][PAY-1411] Fix DMs UI Issues

- packages/common/src/store/notifications/types.ts
- packages/mobile/src/hooks/useNotificationNavigation.ts
Related: https://github.com/AudiusProject/audius-protocol/pull/5392
> [PAY-1409] DMs: Deep link into chat from notification

- packages/mobile/src/app/App.tsx
Error was `Couldn't find a navigation object. Is your component inside a screen in a navigator?`
Needed to move portal inside `NavigationContainer`.
https://github.com/AudiusProject/audius-client/assets/3893871/37f66812-3392-4aa0-bd60-686b5728881e
> [PAY-1403] Fix chat track unfurl reactions

- packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
Fix scrolling with keyboard open on ChatUserListScreen.
https://github.com/AudiusProject/audius-client/assets/3893871/d2d1c077-105f-4961-ad4f-680352882c02
> [PAY-1398] Fix ChatUserListScreen scrolling with keyboard

- packages/mobile/android/app/build.gradle
- packages/mobile/ios/AudiusReactNative/Info.plist
Staging is stuck at 1.6.65 because this commit didn't make it back to main
> Update plist to 1.1.66

- packages/mobile/android/fastlane/Fastfile
- packages/mobile/ios/fastlane/Fastfile
Same as https://github.com/AudiusProject/audius-client/pull/3558 but for Android which I forgot to do 🌚
> Force mobile staging build - Android

- packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
- packages/web/src/pages/chat-page/components/LinkPreview.tsx
Fixes regression in #3551 , adds noopener, removes bottom border on track/playlist tiles
> DMs: Fix broken messages

- packages/mobile/android/fastlane/Fastfile
- packages/mobile/ios/fastlane/Fastfile
> Revert force mobile full staging build

- packages/mobile/src/app/Drawers.tsx
- packages/mobile/src/components/create-chat-actions-drawer/CreateChatActionsDrawer.tsx
- packages/mobile/src/components/create-chat-actions-drawer/index.ts
- packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
- packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
- packages/mobile/src/store/drawers/slice.ts
Add CTA in create chat flow that tells user what action to take in order to message the unpermitted user. Opens InboxUnavailable drawer.
> [PAY-1389] CTA on create chat when not permitted

- packages/mobile/src/screens/chat-screen/ChatUnavailable.tsx
Remove user badges due to dancing badges bug. See https://linear.app/audius/issue/PAY-1325/dancing-badge.
> [PAY-1325] Remove userbadges from chat unavailable message in chat screen

- packages/common/src/models/Collection.ts
- packages/common/src/store/cache/collections/actions.ts
- packages/common/src/store/storeContext.ts
- packages/mobile/src/store/storeContext.ts
- packages/mobile/src/utils/createPlaylistArtwork.ts
- packages/web/package-lock.json
- packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
- packages/web/src/common/store/cache/collections/commonSagas.js
- packages/web/src/common/store/cache/collections/confirmOrderPlaylist.js
- packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
- packages/web/src/common/store/cache/collections/fixInvalidTracksInPlaylist.js
- packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
- packages/web/src/common/store/confirmer/actions.ts
- packages/web/src/common/store/confirmer/types.ts
- packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.tsx
- packages/web/src/components/add-to-playlist/mobile/AddToPlaylist.tsx
- packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
- packages/web/src/store/storeContext.ts
- packages/web/src/utils/imageProcessingUtil.ts
- packages/web/src/workers/createPlaylistArtwork.worker.js
Adds feature where playlist artwork is generated from track artwork. Specifically, when a user adds a fourth track to their playlist, all four track artworks are combined into a single mosaic. Implemented image manipulation logic on web and mobile.
- Refactors addTrackToPlaylist saga to own file and convert to typescript.
- Uses web-worker for image generation in web
- Uses main-thread in mobile
Performance is decently slow on mobile, so the image doesnt change right away.
> [C-2474] Generate playlist artwork from track artwork

- packages/mobile/src/screens/profile-screen/MessageLockedButton.tsx
> [PAY-1446] Set MessageLocked icon in profile screen to 0.4 opacity

- packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
- packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
So that the drawers are not occluded by keyboard. Also sneaking in changing the prop of `ChatUserListItem` to the userId and letting the item select the user from that.
> [PAY-1434] Dismiss keyboard on create chat screen row press

- packages/mobile/src/screens/settings-screen/InboxSettingsScreen.tsx
Remove bottom border on last element
Maintain white background onpress
https://github.com/AudiusProject/audius-client/assets/3893871/7bccec32-c8ec-4a77-8abe-e3092a31df14
> [PAY-1440][PAY-1441] Mobile inbox settings UI fixes

- packages/mobile/dapp-store/.asset-manifest.json
- packages/mobile/dapp-store/config.yaml
- packages/mobile/dapp-store/package.json
- packages/mobile/dapp-store/pnpm-lock.yaml
Updates dapp-store version, and updates dapp-store cli version
> Upgrade dapp store version to v1.5.26

- packages/web/src/components/nav/desktop/NowPlayingArtworkTile.tsx
- packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
Fixes broken drag and drop for NowPlaying track and ConnectedPlaylistTile
None
Locally.
> Allow drag and dropping tracks into chat

- packages/mobile/src/components/chat-actions-drawer/ChatActionsDrawer.tsx
- packages/mobile/src/components/create-chat-actions-drawer/CreateChatActionsDrawer.tsx
For some reason rngh touchables were broken on android.
Android stage
> [PAY-1442] Fix drawer touchables on android

- packages/mobile/src/components/track-list/TrackListItem.tsx
- packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
- packages/web/src/components/table/Table.module.css
Small update to add and update the styles for the overflow menu for playlists
N/A
N/A
N/A
> [C-2472] Update mobile track list items for playlists to have the overflow menu

- packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
- packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
Add padding to bottom of list so user can scroll all the way to the bottom.
Also sneaking in some cleanup from a previous commit.
https://github.com/AudiusProject/audius-client/assets/3893871/4d60345e-99c3-4b52-8450-bc14cedddbaf
> [PAY-1405] Add padding to bottom of chat user search screen

- packages/mobile/src/screens/profile-screen/CoverPhoto.tsx
- packages/mobile/src/screens/profile-screen/MessageButton.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeader/Bio.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeader/ExpandHeaderToggleButton.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
- packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
- packages/mobile/src/screens/profile-screen/SubscribeButton.tsx
Lots of small changes to bring this to spec, found here: 
https://www.figma.com/file/AUCQosYyHmbyYLWIC6GZLi/%F0%9F%92%AC-Direct-Messaging-(DMs)?type=design&node-id=486-49325&t=eVrcG6GwkX5X2IZC-0
New:
Old:
Touches a lot of non-DMs code. Touched some reachability conditional rendering logic.
Simulator
> [PAY-1454] Redline mobile header to latest figma design

- packages/common/src/audius-query/README.md
Feel free to change the copy and merge!
> audius-query debug flag usage in README

- packages/web/src/components/data-entry/InputV2.module.css
- packages/web/src/components/data-entry/InputV2.tsx
- packages/web/src/components/data-entry/TextAreaV2.module.css
- packages/web/src/components/data-entry/TextAreaV2.tsx
- packages/web/src/components/form-fields/TextAreaField.tsx
- packages/web/src/components/form-fields/TextField.tsx
- packages/web/src/components/search-users-modal/SearchUsersModal.tsx
Updates Inputv2 placeholder and label prop
Adds TextField and TextAreaField using InputV2 and TextAreaV2
> [C-2768] Update InputV2, add TextField/TextAreaField

- packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
> [PAY-1461] Format follower count in chat search screen

- packages/mobile/src/screens/profile-screen/MessageLockedButton.tsx
> Reduce MessageLockedButton size on profile screen

- .circleci/config.yml
- .circleci/src/commands/@commands.yml
> Add option to cache bust node_modules

- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
> [PAY-1484] Allow reactions while keyboard is open on mobile

- packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
- packages/mobile/src/screens/chat-screen/ChatUnavailable.tsx
- packages/web/src/components/inbox-unavailable-modal/InboxUnavailableModal.tsx
- packages/web/src/pages/chat-page/components/InboxUnavailableMessage.tsx
> [PAY-1476] Inbox unavailable copy update

- packages/common/src/api/developer-apps.ts
- packages/web/src/pages/settings-page/components/desktop/DeveloperApps/AppDetailsPage.tsx
- packages/web/src/pages/settings-page/components/desktop/DeveloperApps/YourAppsPage.module.css
- packages/web/src/pages/settings-page/components/desktop/DeveloperApps/YourAppsPage.tsx
-Implement copy button func
-Fix key (since apps can have the same name)
-Make spinner normal size
-Exclude 0x from api key (will fix the endpoint later on)
> Developer app modal - small fixes

- packages/web/src/pages/chat-page/components/ChatMessageList.tsx
Per convo in figma. we didn't have a ticket for it afaik
> Change text to 'Beginning of Conversation'

- packages/web/src/utils/restrictedHandles.js
should be lower because we lower handle when comparing
> Lowercase library restricted handle

- packages/common/src/store/ui/reactions/types.ts
- packages/mobile/src/screens/notifications-screen/Reaction/ReactionList.tsx
- packages/mobile/src/screens/notifications-screen/Reaction/reactions.tsx
- packages/web/src/components/notification/Notification/components/Reaction/index.tsx
- packages/web/src/pages/chat-page/components/ReactionPopupMenu.tsx
Instead of sending 'heart' as a reaction, send '😍'!
Breaks existing DMs reactions
> Use emojis instead of 'heart' etc as reactions

- packages/web/src/pages/chat-page/components/ChatComposer.tsx
> [PAY-1473] Clear input on chat change

- packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
- packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
> [PAY-1489] Add more space to reacted to messages

- packages/common/src/store/pages/chat/sagas.ts
- packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
Cleans up saga and uses `closeParentModal` callback to clear the contents of the `SearchUsersModal` on creating a chat
Tested on web and ios sim
> [PAY-1469] Clear the search after creating a chat

- packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
>  [PAY-1470] Remove border radius from track/playlist tiles

- packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
> [PAY-1487] Increase hit slop of mobile dms send button

- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
> [PAY-1494] Change chats copy to beginning of message history

- packages/mobile/src/components/core/KeyboardAvoidingView.tsx
- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Also fixes tap issue.
https://github.com/AudiusProject/audius-client/assets/6780028/ed541706-410d-42de-b4b1-3c497e6cf158
On device
> [PAY-1191] Finesse keyboard enter/exit animations

- packages/common/src/models/Analytics.ts
- packages/common/src/store/pages/chat/sagas.ts
- packages/common/src/store/pages/chat/slice.ts
- packages/mobile/src/components/block-messages-drawer/BlockMessagesDrawer.tsx
- packages/web/src/pages/chat-page/components/BlockUserConfirmationModal.tsx
Remove slice/saga for report abuse, just log an amplitude event instead.
Local ios stage + local web stage
> Amplitude tracking for chat report abuse

- packages/common/package-lock.json
- packages/common/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/web/package-lock.json
- packages/web/package.json
- https://github.com/AudiusProject/audius-protocol/pull/5473
- https://github.com/AudiusProject/audius-protocol/pull/5472
- https://github.com/AudiusProject/audius-protocol/pull/5471
- https://github.com/AudiusProject/audius-protocol/pull/5455
- https://github.com/AudiusProject/audius-protocol/pull/5456
> Update SDK to v3.0.3-beta.56

- packages/mobile/android/app/build.gradle
- packages/mobile/ios/AudiusReactNative/Info.plist
Need to bump version to get the patch for textinput in: https://linear.app/audius/issue/PAY-1483/message-send-button-not-enabled-when-sending-multiple-messages-in
> Bump app versions for full release

- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Chat messages were getting cut off at the top when the keyboard was open + has currently playing track.
before:
after:
> Fix android chat message cut off at top

- packages/common/src/audius-query/AudiusQueryContext.ts
- packages/common/src/audius-query/createApi.ts
- packages/mobile/src/app/App.tsx
- packages/web/src/app.tsx
Log caught API errors to Sentry
Not 100% sure this belongs here vs in the components using the queries/APIs, but I think this would be the most convenient.
> Add Sentry error logging to Audius query C-2800

- packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
> [PAY-1518] DMs: Align the overflow menu bottom center

- packages/mobile/src/components/core/TextInput.tsx
- packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
Make DMs chat input autocorrect properly
> [PAY-1538] Fix autocorrect behavior

- packages/mobile/src/screens/chat-screen/ChatListItem.tsx
- packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
- packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
- packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
- Increase hit area of top right overflow + compose icons
- Change message text color to staticWhite
- Fix font of create chat screen
his Been Tested?
> [PAY-1542][PAY-1539][PAY-1537] Mobile chats QA improvements

- packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
> [PAY-1541] Autofocus textinput on mobile search users screen

- packages/mobile/src/hooks/useContentNodeImage.ts
Fixes issue where mobile image urls were malformed.
@theoilie im noticing some images seem to not show up on staging, but lmk what you see and we can review together
> Fix mobile image uri

- packages/common/src/context/appContext.ts
- packages/mobile/src/app/App.tsx
- packages/mobile/src/app/AppContextProvider.tsx
- packages/mobile/src/components/audio/Audio.tsx
- packages/mobile/src/hooks/useContentNodeImage.ts
- packages/mobile/src/services/sdk/bootstrapStorageNodes.ts
- packages/mobile/src/services/sdk/storageNodeSelector.ts
- packages/mobile/src/store/account/sagas.ts
- packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadCollectionWorker.ts
- packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
- Ensures `getStorageNodeSelector` always returns a singleton
- Adds bootstrap nodes to ensure instant availability to select nodes
- Adds storageNodeSelector to app context to ensure image hooks are re-ran when it becomes active
- Ensures all image functions provide endpoints.
How do we feel about the bootstrap nodes i selected? i essentially just pulled them down from current services
> [C-2808] Improve storageNodeSelector usage and perf

- package-lock.json
- packages/common/package-lock.json
- packages/common/package.json
- packages/embed/package-lock.json
- packages/embed/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/web/package-lock.json
- packages/web/package.json
- 2023-06-30 [https://github.com/AudiusProject/audius-protocol/commit/dda46275f116afdd9badf76cb81ccd4de933529f] Handle chat secret decryption failure cases more gracefully (https://github.com/AudiusProject/audius-protocol/pull/5524) [Michael Piazza]
- 2023-06-30 [https://github.com/AudiusProject/audius-protocol/commit/f071fe0d104e8e179ce19b98a065738b7eb9f94d] @audius/sdk: v3.0.3-beta.62 [audius-infra]
*Are all new features properly feature flagged? Describe added feature …
> Update SDK to v3.0.3-beta.63

- packages/common/src/store/pages/profile/selectors.ts
- packages/mobile/src/components/core/EmptyTile.tsx
- packages/mobile/src/screens/profile-screen/AlbumsTab.tsx
- packages/mobile/src/screens/profile-screen/EmptyProfileTile.tsx
- packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
Fixes issue where hidden playlists down show on profile screen
> [C-2416] Fix missing hidden playlists on own profile

- packages/common/src/store/pages/chat/sagas.ts
Makes debugging DMs easier, as with this package on the window it's now possible to write scripts that programmatically create chats, send messages, etc
> Attach ulid package to window

- packages/web/src/components/collection/desktop/OwnerActionButtons.tsx
Fixed heavy load error on clicking Hot and New on audius.co landing page.
Caused by reading properties from a collection that's not fetched yet.
local dapp vs stage and also vs prod.
> [QA-560][PAY-1564] Fix hot and new bug

- packages/mobile/src/components/card/Card.tsx
- packages/mobile/src/components/card/CollectionDogEar.tsx
Add hidden dog tag to collection cards
> [C-2821] Add hidden dog tag to mobile card

- packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
- Change color of track header to always be neutralLight4 (per Julian's comment in figma)
- Fix color of lock icon for usdc purchase track tiles
> Minor fixes for premium_content + usdc purchases

- packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/
> DMs: Make links noreferrer noopener

- packages/web/src/pages/chat-page/components/InboxUnavailableMessage.tsx
> DMs: Add space to learn more text

- packages/common/src/utils/chatUtils.ts
- packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
- packages/mobile/src/screens/chat-screen/ChatUnavailable.tsx
- packages/web/src/components/inbox-unavailable-modal/InboxUnavailableModal.tsx
- packages/web/src/pages/audio-rewards-page/components/modals/TopAPI.tsx
- packages/web/src/pages/chat-page/components/InboxUnavailableMessage.tsx
> [PAY-1569] Update blog post link

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/mobile/.env.dev
- packages/mobile/.env.prod
- packages/mobile/src/components/audio/GoogleCast.tsx
- packages/mobile/src/components/image/utils.ts
- packages/mobile/src/services/audius-backend-instance.ts
- packages/web/.env/.env.dev
- packages/web/.env/.env.prod
- packages/web/.env/.env.stage
- packages/web/src/common/store/account/sagas.js
- packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
- packages/web/src/common/store/cache/collections/commonSagas.js
- packages/web/src/common/store/cache/tracks/sagas.js
- packages/web/src/common/store/cache/users/sagas.js
- packages/web/src/common/store/profile/sagas.js
- packages/web/src/components/ai-attribution-modal/AiAttributionDropdown.tsx
- packages/web/src/components/ai-attribution-modal/SearchBarResult.js
- packages/web/src/components/search/SearchBar.js
- packages/web/src/components/search/SearchBarResult.js
- packages/web/src/pages/AppContextProvider.tsx
- packages/web/src/pages/AppProviders.tsx
- packages/web/src/pages/PublicSite.tsx
- packages/web/src/pages/landing-page/components/FeaturedContent.tsx
- packages/web/src/pages/oauth-login-page/utils.ts
- packages/web/src/services/audius-backend/audius-backend-instance.ts
Removes replica set references in web, completing the transition to storage v2
> [C-2834] Remove replica set usage in web

- packages/common/src/store/pages/collection/actions.ts
- packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
- packages/web/src/common/store/pages/collection/sagas.js
Small add to update the collection screen to fetch the lineup metadata whenever the screen is focused
N/A
N/A
N/A
> [C-2785] Update collection screen focus effect to fetch lineup

- packages/common/src/services/sdk/bootstrapNodes.ts
- packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
There was a race condition during storageNodeSelector initialization when running against local stack. Setting the bootstrap nodes fixes it
> Add dev storage bootstrap nodes

- packages/web/src/components/notification/Notification/components/NotificationTile.module.css
- packages/web/src/components/notification/Notification/components/NotificationTile.tsx
Change cursor type to pointer only when the notification is clickable
https://github.com/AudiusProject/audius-client/assets/3893871/52682a19-6acd-4bfd-8384-c5f1b103489f
> Notification cursor reflects clickability

- packages/mobile/android/app/build.gradle
- packages/mobile/ios/AudiusReactNative/Info.plist
> Bump app versions

- packages/mobile/src/screens/chat-screen/EmptyChatMessages.tsx
> [PAY-1597] Fix mobile chat screen empty state font

- packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
> [PAY-1599] Fix font in Start Conversation prompt

- packages/mobile/src/screens/notifications-screen/Notifications/AnnouncementNotification.tsx
> Fix android announcement notifs

- packages/common/src/services/audius-api-client/AudiusAPIClient.ts
> Manually set the libs state to prevent retry storm

- packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
- packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
- packages/mobile/src/components/lineup-tile/styles.ts
Dup of https://github.com/AudiusProject/audius-client/pull/3755 - re-doing PR bc we just merged a giant feature branch into `main` that caused lots of conflicts, the rebase was going to be insane for this tiny change.
- Lock icon in correct position on right
- Changed offline status indicator size to match design
- Update spacing of stats items to match design
> [PAY-1607] Fix mobile prem content track tile layout

- packages/embed/src/util/BedtimeClient.js
- packages/embed/src/util/gatewayUtil.js
- packages/embed/src/util/getArtworkUrl.js
Fixes embed by adding a fallback
> Add fallback url to embed

- packages/common/src/services/audius-backend/AudiusBackend.ts
Updates fetchCID logic to retry storage nodes on failure.
> [C-2872] Fix image retries

- packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css
- packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Oops! Missed a negation on checking `doesUserHaveAccess`.
Also fixed a minor display issue with the premium content section not being full width.
N/A
N/A
N/A
N/A
> [PAY-1620] Fix disabled play button for unlocked gated tracks on Mobile Web

- packages/mobile/src/components/core/LockedStatusBadge.tsx
Also updates size from 16 to 14.
> Fix mobile premcontent locked badge colors

- packages/web/src/components/collection/desktop/utils.ts
- packages/web/src/pages/collection-page/components/desktop/CollectionPage.module.css
- packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Fixes issue where favorited, saved, and playing collection buttons overflow.
> [C-2887] Fix collection button widths

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
- packages/web/src/components/collection/desktop/Artwork.tsx
Simple cleanup to remove getBlocknumber code which required an eth call
> [C-2857] Remove get blocknumber

- packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
UI fix - there used to be margins around the "unlocking" section.
> Fix mobile prem-content drawer unlocking margin

- packages/web/src/pages/oauth-login-page/utils.ts
Fixes jwt passed through to discovery nodes after completing auth, e.g. 
https://discoveryprovider.staging.audius.co//v1/users/verify_token?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJrZWNjYWsyNTYifQ.eyJ1c2VySWQiOiJ4azlabFY5IiwiZW1haWwiOiJyYXkrNzI2MjNAYXVkaXVzLmNvIiwibmFtZSI6InJheSIsImhhbmRsZSI6ImlhbXJheSIsInZlcmlmaWVkIjpmYWxzZSwicHJvZmlsZVBpY3R1cmUiOnsiMTUweDE1MCI6Imh0dHBzOi8vY3JlYXRvcm5vZGU1LnN0YWdpbmcuYXVkaXVzLmNvMDFINkFGQTlSSlhFNzdQNVNHVlcwNUtWN04vMTUweDE1MC5qcGciLCI0ODB4NDgwIjoiaHR0cHM6Ly9jcmVhdG9ybm9kZTUuc3RhZ2luZy5hdWRpdXMuY28wMUg2QUZBOVJKWEU3N1A1U0dWVzA1S1Y3Ti80ODB4NDgwLmpwZyIsIjEwMDB4MTAwMCI6Imh0dHBzOi8vY3JlYXRvcm5vZGU1LnN0YWdpbmcuYXVkaXVzLmNvMDFINkFGQTlSSlhFNzdQNVNHVlcwNUtWN04vMTAwMHgxMDAwLmpwZyJ9LCJzdWIiOiJ4azlabFY5IiwiaWF0IjoxNjkwNDIxNzEzfQ.MHgwNmZmZDE5NzhlODQ2ZmM2MTM5NjQzYmZjMjk1MTZmNzI4 …
> [C-801] Fix oauth nodes

- packages/web/src/pages/upload-page/fields/SourceFilesView.module.css
- packages/web/src/pages/upload-page/fields/SourceFilesView.tsx
- packages/web/src/pages/upload-page/fields/SwitchRowField.module.css
- packages/web/src/pages/upload-page/fields/SwitchRowField.tsx
- packages/web/src/pages/upload-page/forms/AttributionModalForm.tsx
- packages/web/src/pages/upload-page/forms/ReleaseDateModalForm.module.css
- packages/web/src/pages/upload-page/forms/ReleaseDateModalForm.tsx
- packages/web/src/pages/upload-page/forms/RemixModalForm.module.css
- packages/web/src/pages/upload-page/forms/RemixModalForm.tsx
- packages/web/src/pages/upload-page/forms/SourceFilesModalForm.module.css
- packages/web/src/pages/upload-page/forms/SourceFilesModalForm.tsx
- packages/web/src/pages/upload-page/forms/TrackAvailabilityModalForm.module.css
- packages/web/src/pages/upload-page/forms/TrackAvailabilityModalForm.tsx
Update the text in the upload forms to use the typography component
N/A
Manaully tested
N/A
N/A
> [C-2902] Update the upload forms to use the typography component

- packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
- packages/web/src/components/premium-content-purchase-modal/components/PayToUnlockInfo.tsx
- packages/web/src/components/premium-content-purchase-modal/components/PurchaseSummaryTable.tsx
- packages/web/src/components/typography/Text.tsx
- packages/web/src/components/typography/constants.ts
- packages/web/src/components/typography/types.ts
- packages/web/src/pages/upload-page/fields/SourceFilesView.tsx
- packages/web/src/pages/upload-page/fields/SwitchRowField.tsx
- packages/web/src/pages/upload-page/forms/AttributionModalForm.tsx
- packages/web/src/pages/upload-page/forms/ReleaseDateModalForm.tsx
- packages/web/src/pages/upload-page/forms/RemixModalForm.tsx
- packages/web/src/pages/upload-page/forms/SourceFilesModalForm.tsx
- packages/web/src/pages/upload-page/forms/TrackAvailabilityModalForm.tsx
Updating the types and props to be camelCase for consistency and dev ergonomics
N/A
N/A
N/A
> [C-2905] Update Text types and props to camelCase

- .circleci/src/@continue_config.yml
- .circleci/src/jobs/@web-jobs.yml
- packages/probers/cypress.config.ts
- packages/probers/cypress/e2e/favoriteTrack.cy.ts
- packages/probers/cypress/e2e/repostTrack.cy.ts
- packages/probers/cypress/e2e/uilts.ts
- packages/probers/cypress/e2e/uploadTrack.cy.ts
- packages/probers/cypress/fixtures/remixes.json
- packages/probers/package-lock.json
- packages/probers/package.json
- packages/web/src/components/track/GiantTrackTile.tsx
Add favorite test and fix aria-label
Co-authored by AJ
`npm run cypress:open`
> Add favorite test and fix aria-label

- packages/mobile/android/app/build.gradle
- packages/mobile/ios/AudiusReactNative/Info.plist
> Bump mobile versions for client v1.5.35 full app release

- packages/common/package-lock.json
- packages/common/package.json
- packages/common/src/services/audius-backend/waudio.ts
- packages/embed/package-lock.json
- packages/embed/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/mobile/src/services/buyCrypto.ts
- packages/web/package-lock.json
- packages/web/package.json
Based on https://github.com/AudiusProject/audius-protocol/pull/5713
Updates our usage of those functions to pass a config object.
N/A
Locally verified
N/A
N/A
> Update userbank function usage to pass config object

- packages/common/src/utils/genres.ts
- packages/mobile/src/screens/edit-track-screen/screens/SelectGenreScreen.tsx
- packages/web/src/components/data-entry/DropdownInput.d.ts
- packages/web/src/components/data-entry/FormTile.js
- packages/web/src/pages/upload-page/fields/TrackMetadataFields.tsx
Context: https://audius-internal.slack.com/archives/C02JBA52NKZ/p1690917700449949
> Fix broken track upload for electronic subgenres on mobile

- packages/common/package-lock.json
- packages/common/package.json
- packages/embed/package-lock.json
- packages/embed/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/mobile/src/components/premium-track-purchase-drawer/StripePurchaseConfirmationButton.tsx
- packages/mobile/src/services/buyCrypto.ts
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/services/audius-backend/BuyAudio.ts
Utilizes the new identity endpoint to create a Stripe session to purchase USDC instead of sol.
Stripe UI is not a drawer yet, but will wait for design before doing that.
https://github.com/AudiusProject/audius-client/assets/3893871/ed0f5b8f-eca7-4937-9923-e4dca8a97fda
> [PAY-1685] Wire up stripe UI for USDC purchase in mobile

- .circleci/src/commands/@mobile-commands.yml
- .circleci/src/jobs/@mobile-jobs.yml
Had to merge previous PR to cherry pick onto release branch and try it out. Was able to submit another version with the version code incremented.
On CI, release-v1.5.34
> Add prepare step to dapp-store ci flow

- packages/common/package-lock.json
- packages/common/package.json
- packages/embed/package-lock.json
- packages/embed/package.json
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/web/package-lock.json
- packages/web/package.json
> Update SDK to latest 3.0.3-beta.109

- packages/web/wrangler.toml
Instead of specifying vars in the CF page.
npx wrangler preview --watch --env staging
> Add nodes to env for SEO support

- packages/web/scripts/workers-site/index.js
Just small copy stuff to more closely match previous helmet rules in
https://github.com/AudiusProject/audius-client/blob/5fa73e027309c5fe4d06fe7377e9d24de5f383ce/packages/web/src/utils/seo.ts#L58
```
npx wrangler preview --watch --env production
```
> Minor improvements to SEO flow merged in #3859

- packages/common/src/models/Analytics.ts
- packages/mobile/src/components/share-drawer/ShareDrawer.tsx
- packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavDrawer.tsx
- packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavLink.tsx
- packages/mobile/src/screens/profile-screen/MessageButton.tsx
- packages/web/src/components/banner/DirectMessagesBanner.tsx
- packages/web/src/components/nav/desktop/NavPopupMenu.tsx
- packages/web/src/components/share-modal/ShareModal.tsx
- packages/web/src/pages/profile-page/ProfilePageProvider.tsx
Adds tracking to entrypoints to DMs
> [PAY-1695] DMs: Entrypoint Analytics

- packages/probers/cypress/e2e/uploadTrack.cy.ts
> Remove .only on upload cypress test

- packages/web/src/pages/profile-page/components/SocialLink.tsx
Fixes issue where donation link does not open a new tab
> [C-2759] Make donation link external

- package.json
Add hotfix command to make hotfix deploys easier to manage
> Add sdk:update-hotfix

- packages/web/scripts/workers-site/index.js
Add h1 tag.
In future, good js can document.getElementById('audius-h1') and replace it with other content. For now, we shall see if this can move the needle.
Touches main index.html
```
npx wrangler preview --watch --env staging
```
Verified body looks like
```
<body ontouchstart=""><h1 id="audius-h1" style="visibility:hidden;display:none;">rayjacobson</h1><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><div id="recaptcha-hidden" style="display:none"></div></body>
```
> [C-2957] Add h1 tag for SEO

- packages/web/scripts/workers-site/index.js
Updates seo h1 to be visually hidden but still accessible. web crawlers should be able to interpret this h1 while not showing an ugly h1 to the user while react is getting set up
> Update seo h1 to be accessibly hidden vs visually hidden

- packages/mobile/src/components/help-callout/HelpCallout.tsx
- packages/mobile/src/components/leaving-audius-drawer/LeavingAudiusDrawer.tsx
Limits the number of lines for the link
> Limit lines in Leaving Audius Modal

- packages/probers/cypress/e2e/uploadTrack.cy.ts
- packages/stems/src/components/Button/Button.module.css
- packages/stems/src/components/Button/Button.tsx
- packages/stems/src/components/Button/types.ts
- packages/stems/src/components/Popup/Popup.tsx
- packages/stems/src/components/Popup/types.ts
- packages/stems/src/types.ts
- packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
- packages/web/src/components/artist-recommendations/ArtistRecommendationsDropdown.tsx
- packages/web/src/components/avatar/Avatar.tsx
- packages/web/src/components/link/Link.tsx
- packages/web/src/components/nav/desktop/AccountDetails.tsx
- packages/web/src/components/nav/desktop/LeftNav.module.css
- packages/web/src/components/nav/desktop/LeftNav.tsx
- packages/web/src/components/nav/desktop/NavButton.module.css
- packages/web/src/components/nav/desktop/NavButton.tsx
- packages/web/src/components/nav/desktop/NavHeader.module.css
- packages/web/src/components/nav/desktop/NavHeader.tsx
- packages/web/src/components/typography/typography.module.css
- packages/web/src/types.ts
Major improvements to left nav seo.
1. Adds link for home-page
2. Adds link
> [C-2961] Fix LeftNav SEO

- packages/web/src/components/link/Link.module.css
- packages/web/src/components/link/Link.tsx
- packages/web/src/components/track/GiantTrackTile.module.css
- packages/web/src/components/track/GiantTrackTile.tsx
- packages/web/src/components/track/desktop/ConnectedPlaylistTile.module.css
- packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
- packages/web/src/components/track/desktop/ConnectedTrackTile.module.css
- packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
- packages/web/src/components/track/desktop/PlaylistTile.tsx
- packages/web/src/components/track/desktop/TrackTile.module.css
- packages/web/src/components/track/desktop/TrackTile.tsx
- packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx
- packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
- packages/web/src/components/track/mobile/PlaylistTile.module.css
- packages/web/src/components/track/mobile/PlaylistTile.tsx
- packages/web/src/components/track/mobile/TrackTile.module.css
- packages/web/src/components/track/mobile/TrackTile.tsx
- packages/web/src/components/track/types.ts
- packages/web/src/components/typography/constants.ts
- packages/web/src/components/typography/types.ts
- packages/web/src/components/typography/typography.module.css
- packages/web/src/pages/track-page/TrackPageProvider.tsx
- packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
- packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css
- packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
- packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
Fixes seo for feed, trending, track-page, and any page with track tiles on desktop and mobile
We should probably not hide the anchor tags for desktop track tiles, mobile correctly renders them behind a skeleton
> [C-2972] Fix feed, trending track-page seo

- packages/mobile/src/components/core/DogEar.tsx
- packages/mobile/src/components/core/LockedStatusBadge.tsx
- packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
- packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx
- packages/mobile/src/components/lineup-tile/LineupTilePremiumContentTypeTag.tsx
- packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSuccess.tsx
- packages/mobile/src/components/premium-track-purchase-drawer/StripePurchaseConfirmationButton.tsx
- packages/mobile/src/components/track-details-tile/TrackDetailsTile.tsx
- packages/mobile/src/utils/theme.ts
Add `specialGreen` color and update name for `specialLightGreen`.
> PAY-1724 Add color specialGreen on mobile

- packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
> Fix stripe modal opening behavior

- packages/web/src/components/nav/desktop/AccountDetails.module.css
- packages/web/src/components/nav/desktop/AccountDetails.tsx
- packages/web/src/components/nav/desktop/LeftNav.module.css
Fix layout of token badge & cut new module.css file 
localhost staging
> Fix account details css

- packages/web/src/components/animated-button/AnimatedButtonProvider.tsx
- packages/web/src/components/link/ExternalLink.tsx
- packages/web/src/components/link/SeoLink.module.css
- packages/web/src/components/link/SeoLink.tsx
- packages/web/src/components/link/index.ts
- packages/web/src/components/nav/mobile/ConnectedNavBar.tsx
- packages/web/src/components/nav/mobile/NavBar.tsx
- packages/web/src/hooks/useTabs/useTabs.tsx
- packages/web/src/pages/profile-page/ProfilePage.tsx
- packages/web/src/pages/profile-page/components/SocialLink.module.css
- packages/web/src/pages/profile-page/components/SocialLink.tsx
- packages/web/src/pages/profile-page/components/desktop/ProfilePage.module.css
- packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
- packages/web/src/pages/profile-page/components/mobile/ProfileHeader.module.css
- packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
- packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
- packages/web/src/pages/profile-page/components/mobile/SocialLink.tsx
Fixes various issues with profile-page seo.
- Fixes tab navigation
- Fixes social links
Adds the following link types:
SEOLink: a component that adds anchor tag but ultimately allows the associated onClick handler to do the navigation. This is a good stop-gap for complex components like tabs 
Externallink: a component that adds all the necessary props to open external links. Useful for social links.
Various other fixes:
- Fixes issue with animatedbutton links
- Fixes mobile navbar links
> [C-2976] Fix profile-page seo

- packages/web/public/index.html
- packages/web/scripts/workers-site/index.js
* Remove unused preconnect
* Add browser cache rules to static assets
> Improve lighthouse score

- packages/web/public/index.html
Per lighthouse's suggestion. It's not even in here: https://github.com/facebook/create-react-app/blob/main/packages/cra-template/template/public/index.html#L29
> Remove ontouchstart from index.html

- packages/web/scripts/workers-site/index.js
- packages/web/src/components/page/Page.js
- packages/web/src/pages/audio-rewards-page/Tiers.tsx
- packages/web/src/utils/seo.ts
> [C-2982] Fix seo based on ahref recommendations

- packages/web/scripts/workers-site/index.js
- packages/web/src/components/mobile-page-container/MobilePageContainer.tsx
Fixes issue where canonical url is inconsistent on page-load leading to seo regressions. These were applied as hotfixes to release-1.5.37, and now in pr to integrate with main
The canonical url does not keep up during a user session, is this an issue @raymondjacobson?
> Fix canonical url consistency

- packages/mobile/src/components/core/Hyperlink.tsx
- packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
- packages/web/src/components/link/ExternalLink.tsx
- packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
- packages/web/src/pages/chat-page/components/LinkPreview.module.css
- Fix overflows in link previews
- Use `UserGeneratedText` in DMs
- Add `LeavingAudius` modal for all external links not just DMs (sans social links)
Tested bio links, social links, and DM links
Non-english, non-hyphenated:
English, hyphenated:
> [PAY-1748][PAY-1731][PAY-1729][PAY-1730] DMs link fixes

- packages/web/src/components/data-entry/ContextualMenu.module.css
- packages/web/src/components/data-entry/ContextualMenu.tsx
- packages/web/src/pages/upload-page/fields/SourceFilesField.tsx
Just used the map that we already had for user friendly strings
N/A
> [C-3002] Fix casing of selected values in upload flow

- packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
- packages/web/src/pages/upload-page/fields/AttributionField.tsx
- packages/web/src/pages/upload-page/fields/MultiTrackSidebar.module.css
- packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx
- packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
- packages/web/src/pages/upload-page/validation.ts
Updating errors to have a period at the end and update the icon to be red
> [C-3001, C-3003] Fix new upload flow error formatting

- packages/web/src/pages/upload-page/UploadPageNew.tsx
Add back button to new upload flow edit page
> [C-3015] Add back button to new upload flow edit page

- packages/web/src/pages/upload-page/components/FinishPageNew.tsx
- packages/web/src/pages/upload-page/fields/DatePickerField.module.css
Add 'Finalizing Upload' text and verify calendar input styles
> [C-2999] Verify calendar input styles and update text when finalizing upload

- packages/stems/src/styles/colors.ts
- packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
- packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Fixes bug where non-links weren't correctly colored.
> Fix text color for DMs

- packages/common/src/store/upload/selectors.ts
- packages/web/src/pages/upload-page/fields/SelectGenreField.tsx
Update the subgenre value that is passed to remove the 'Electronic - ' in the beginning
> [C-2921] Update subgenre value passed in the genre field

- packages/web/src/services/solana/WithdrawUSDC.ts
- packages/web/src/services/solana/solana.ts
- packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Signs the swap transaction with the root solana account and passes the signature to relay.
Local web stage against staging identity - confirmed we hit the "transaction too large" error.
> [PAY-1755] Withdraw USDC flow: send signature to relay

- packages/web/src/services/solana/WithdrawUSDC.ts
- packages/web/src/services/solana/solana.ts
- packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Creates destination token account (if it doesn't exist)
Local web stage - circumvented the entire "swap" flow and just used existing sol to fund. Example of successful creation: https://solscan.io/tx/52Rcr1xYVcSLPi4V4NUfSht5x9JuHJnPszwVFhm44Ck1b4kKdPRuQGHgrrNd7b4Uao5Vt6XWGVNcM3dcuz3jwUMY
> [PAY-1786] Withdraw USDC - create dest token account

- packages/mobile/.gitignore
- packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
* Add .watchman* to gitignore -- the watchman files showed up after `npm i` 
* pbproject changed when doing `pod install`
```
npm run web:stage
```
> Update files to account for changes on node 18

- packages/web/src/hooks/useUserCoverPhoto.ts
- packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.module.css
- packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
- packages/web/src/pages/artist-dashboard-page/components/ArtistCard.module.css
- packages/web/src/pages/artist-dashboard-page/components/ArtistCard.tsx
- packages/web/src/pages/artist-dashboard-page/components/ArtistProfile.js
- packages/web/src/pages/artist-dashboard-page/components/USDCCard.module.css
- packages/web/src/pages/artist-dashboard-page/components/USDCCard.tsx
* Implement ArtistCard
* Refactor and rename USDCCard a little
* Update bg style of stats
* make useCoverPhoto hook match new useProfilePicture pattern
```
npm run web:stage
localhost:3001/dashboard
```
> [PAY-1736] Implement new ArtistCard on dashboard

- packages/mobile/src/screens/ai-generated-tracks-screen/ShareAiTracksTile.tsx
- packages/web/src/utils/route.ts
Noticed this link was broken, somehow it has changed to: [https://help.audius.co/help/What-should-I-know-about-AI-generated-music-on-Audius-0a5a8](https://help.audius.co/help/What-should-I-know-about-AI-generated-music-on-Audius-0a5a8)
local web stage
> Fix AI learn more link

- packages/common/src/utils/formatUtil.ts
Fixes issue where som withdraws had double negative signs.
> [C-3031] Fix transaction history numbers

- packages/web/src/pages/App.js
- packages/web/src/pages/upload-page/UploadPageNew.tsx
- packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx
- packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
- Prev/next buttons scroll to top
- Clicking track or deleting track in MultiTrackSidebar scrolls to top
Using react provider to pass the scroll call down.
local web
> [C-3004] Scroll to top when switching tracks in upload

- packages/mobile/android/app/build.gradle
- packages/mobile/ios/AudiusReactNative/Info.plist
Updating versionName and versionString to prepare for 1.5.40 full app release
> Prepare 1.5.40 full app release

- packages/web/src/components/ai-attribution-modal/DropdownInput.js
- packages/web/src/components/data-entry/DropdownInput.d.ts
- packages/web/src/components/data-entry/DropdownInput.js
- packages/web/src/components/data-entry/DropdownInput.module.css
- packages/web/src/components/link/ExternalLink.tsx
- packages/web/src/components/modal-radio/ModalRadioItem.tsx
- packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
- packages/web/src/pages/upload-page/fields/availability/collectible-gated/CollectibleGatedDescription.tsx
- packages/web/src/pages/upload-page/fields/availability/collectible-gated/CollectibleGatedFields.module.css
- packages/web/src/pages/upload-page/fields/availability/collectible-gated/CollectibleGatedFields.tsx
- packages/web/src/pages/upload-page/fields/availability/collectible-gated/CollectibleGatedRadioField.tsx
Fixes issue where user is unable to select an nft from the collectible gated dropdown menu.
Also cleans up render heirarchy
> [C-3032] Fix collectible gated upload

- .circleci/config.yml
- .circleci/src/commands/@mobile-commands.yml
- package-lock.json
- package.json
- packages/web/package.json
Fixes a few issues with release CI. `release-v1.5.40` is successfully cut and building
> Fix release CI

- packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawer.tsx
> Fix support email

- .circleci/src/commands/@mobile-commands.yml
Fix android release CI. This broke bc we are using a new circle ci image
> Install pip for android release

- packages/web/src/components/Icon/Icon.module.css
- packages/web/src/components/track/desktop/stats/Stats.module.css
- packages/web/src/components/track/desktop/stats/Stats.tsx
- packages/web/src/components/track/desktop/stats/StatsText.tsx
Fixes issue where "Be the first one to repost" text does not overflow on smaller screens
Also does a bit of cleanup, in particular improves the layout of repost text when no artist images are peresnt.
> [C-2862] Fix clipped repost message text

- .circleci/src/commands/@mobile-commands.yml
> Symlink react-native for android release

- packages/mobile/src/components/details-tile/DetailsTile.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Add tombstone view for deleted tracks on mobile
Local mobile dapp vs stage
> Fix mobile deleted track tile

- packages/web/src/pages/artist-dashboard-page/components/USDCCard.tsx
> Fix balance formatting on USDC card

- packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
> [PAY-1794] Math.min(withdrawalAmount, latestBalance) after using USDC to pay tx fee

- packages/mobile/src/components/help-callout/HelpCallout.tsx
- packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx
Fixes text-overflow issue in remix callout on android
> [C-3056] Fix remix callout text overflow

- package-lock.json
- package.json
- packages/common/package.json
- packages/embed/package.json
- packages/mobile/package.json
- packages/web/package.json
- packages/web/src/pages/purchases-and-sales/SalesPage.tsx
- packages/web/src/pages/purchases-and-sales/SalesTable.tsx
I had originally removed the ability to filter by buyer because the API didn't support it. SDK now has the appropriate methods so this adds sorting back in.
> [PAY-1773] Add sorting by buyer name to sales table

- packages/web/src/pages/saved-page/components/mobile/NewPlaylistButton.tsx
> Fix bad merge breaking main

- packages/web/src/components/collection/desktop/PublishConfirmationModal.module.css
- packages/web/src/components/collection/desktop/PublishConfirmationModal.tsx
- packages/web/src/components/suggested-tracks/SuggestedTracks.module.css
- packages/web/src/components/table/Table.module.css
Fixes issues with theme colors not changing for some elements of the playlist page
> [C-3052] Fix playlist page theme

- packages/common/src/store/ui/modals/withdraw-usdc-modal/index.ts
- packages/common/src/store/ui/withdraw-usdc/selectors.ts
- packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.module.css
- packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx
- packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx
- packages/web/src/components/withdraw-usdc-modal/components/Error.module.css
- packages/web/src/components/withdraw-usdc-modal/components/Error.tsx
- packages/web/src/components/withdraw-usdc-modal/components/TransferInProgress.module.css
- packages/web/src/components/withdraw-usdc-modal/components/TransferInProgress.tsx
- packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.module.css
- packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx
* Match designs
* Add error state to confirmation and error page of modal
* Add min balance
npm run web:stage
> [PAY-1822][PAY-1824][PAY-1825] Address withdrawal QA

- .circleci/config.yml
- package-lock.json
- package.json
- packages/common/package.json
- packages/embed/package.json
- packages/eslint-config-audius/package.json
- packages/mobile/package.json
- packages/probers/package.json
- packages/stems/package.json
- packages/web/package.json
Version bump was still broken on the release branch generation, so having to bump manually. Also including a fix for the auto bump
This will need to get cherry picked into `audius-protocol`
> Bump version to v1.5.41 and fix auto version bump
