.circleci/src/commands/@web-commands.yml, .circleci/src/jobs/@web-jobs.yml, .circleci/src/workflows/web.yml, package-lock.json, packages/common/package-lock.json, packages/mobile/package-lock.json, packages/web/craco.config.ts, packages/web/package-lock.json, packages/web/package.json
* Add ci to upload sourcemaps to `sourcemaps.audius.co` s3 bucket
* Remove sourcemaps from build deployed to cloudflare
* Update craco config to point at s3 bucket for sourcemaps
* Remove `@types/webpack` (included with webpack v5)
* Uses `cimg/python:3.7.12-node` image for cloudflare deploy steps because it has both node 14 and python
Was initially going to do the sourcemap move as a separate job but that required attaching and persisting the workspace which added unnecessary run time.
Right now all source maps are `sync`ed into the same directory in the bucket, this is never getting pruned so could get big/expensive. Can do another pass to create separate directories for the different builds, and overwrite existing files. But wanna merge this to unblock builds for now
Tested by …
=> [C-887] Host sourcemaps on s3, fixes cloudflare deploy

packages/web/src/common/store/cache/collections/sagas.js, packages/web/src/pages/collection-page/store/lineups/tracks/sagas.js
2 small fixes for ordering playlist tracks.
* Outdated playlist was used in ordering playlist so ordering changes would not go through entity manager flow.
* Use metadata_time in dateAdded timestamp so tracks can be ordered immediately after being added.
Tested on client pointed to staging.
Confirm track ordering works.
=> Fix order playlist to use updated playlist

packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.module.css
Removes unnecessary !important and fill property from fix for PAY-438 (#1760).
=> Cleans up code for Challenge Twitter icon fill color

packages/web/src/store/wallet/sagas.ts
Adds a generic error message when sending to an external wallet fails.
=> [PAY-476] Display error when send to wallet fails

packages/mobile/src/utils/challenges.tsx, packages/web/src/pages/audio-rewards-page/config.tsx
Change text of first playlist challenge button to "Create a Playlist" so it doesn't read "Create Your First Playlist" even after the user has completed the challenge.
Ran on local browser + ios simulator
=> [PAY-552] Change playllenge challenge button text

packages/stems/src/components/Button/Button.module.css, packages/stems/src/components/Button/Button.tsx, packages/stems/src/components/Button/types.ts
Adds a text button type to the `Button` in stems. A simple text button that can have icons and turns `--secondary` color on hover.
Sizes affect the text size and icon size. The icon size is the same as the font size less 2px
https://user-images.githubusercontent.com/3690498/186540418-b982a2f9-ccff-40f1-8ded-d273bcb00cd9.mov
Tested against usage in the BuyAudio modal and the $AUDIO rewards page 
=> Add Text Button type to Stems

packages/web/src/components/buy-audio-modal/components/SuccessPage.module.css, packages/web/src/components/buy-audio-modal/components/SuccessPage.tsx
- Adds the success page of the buy $AUDIO modal
Note:
- Does not have TransactionDetails wired up
- Not wired up to Modal (yet)
Tested by manually swapping the page for the BuyAudioModal to the SuccessPage and triggering the saga manually
Already behind BUY_AUDIO_ENABLED feature flag
=> [PAY-580] Add Success Page to BuyAudio Modal

packages/web/src/components/buy-audio-modal/components/InProgressPage.module.css, packages/web/src/components/collapsible-content/CollapsibleContent.module.css, packages/web/src/components/collapsible-content/CollapsibleContent.tsx, packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css, packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Depends on #1789 
- Consumes Text button in collapsible content
- Adjusts button on $AUDIO rewards page to not be full width
- Changes text of send/receive buttons in advanced section to match Figma
Tested locally against stage
=> Consume new Text button in CollapsibleContent

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/services/audius-backend/eagerLoadUtils.ts, packages/common/src/services/wallet-client/WalletClient.ts, packages/common/src/store/pages/token-dashboard/selectors.ts, packages/common/src/store/pages/token-dashboard/slice.ts, packages/common/src/store/pages/token-dashboard/types.ts, packages/web/src/pages/audio-rewards-page/components/SendInputConfirmation.module.css, packages/web/src/pages/audio-rewards-page/components/SendInputConfirmation.tsx, packages/web/src/store/wallet/sagas.ts
When transferring WAudio to an external wallet, throw an error if the recipient wouldn't be able to receive it, ie. if the recipient doesn't have an associated WAudio token account AND doesn't have a SOL balance to fund the creation of one.
I'm throwing an error in the selector for canRecipientReceiveWAudio on the assumption that if something is trying to access it from the incorrect state, then the caller probably depends on it in some incorrect way and so things should break. But open to suggestions!
Also in the selector and action, I am nesting the happy path but I think this is a case where it's necessary.
Tested on local browser.
https://user-images.githubusercontent.com/3893871/186984425-43bd5c4e-5d5f-4bac-ac90-d6788e4f5703.mov …
=> [PAY-479] Check recipient wallet SOL before send

packages/web/src/common/store/cache/collections/sagas.js
Entity manager enabled track removals were broken. The metadata_timestamp would not match the playlist indexing timestamp so no track would be removed. This logic will check if the playlist is enabled / has a metadata_timestamp then match based on that. If entity manager is disabled, it will use indexing timestamp instead.
Tested against staging.
Test track addition/removal with without cached state.
Tested legacy flow as well.
This change is behind the …
=> Fix track removal from playlist with entity manager

packages/web/src/common/store/cache/collections/sagas.js
If entity manager is enabled, we can return false early if they do not match. Don't check for index time `t.time`.
Follow up https://github.com/AudiusProject/audius-client/pull/1815.
cached remove track on legacy is broken on prod. entity manager will fix this.
=> Follow up fix track removal from playlist with entity manager

packages/stems/scripts/workers-site/index.js
- stems.audius.co was borked because the requests to the bundle/css were being redirected to the root
- Storybook uses query params anyway to route so just turn off the rewrite altogether
=> [Stems] Don't rewrite to /index.html on stems.audius.co

packages/mobile/src/components/collectible-details-drawer/CollectibleDetailsDrawer.tsx
* Migrate collectible details
The json error I was seeing was due to the react native debugger
=> [C-952] Migrate collectible details

packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css, packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx
Fixes feed tip tile "send tip" button resizing issue. Now also wraps the recipient info and "was tipped by" section.
Some jumpiness if the user resizes the window quickly, see the end of the video.
Now 
Tested on local web
https://user-images.githubusercontent.com/3893871/187829466-d366ffe3-5a9c-46c7-899f-3e8325e55848.mov
=> [PAY-507] Fix feed tip tile tip button resizing

packages/mobile/src/screens/notifications-screen/Notification/ProfilePictureList.tsx
Adds text shadow to follower count, and adds a black view with 10% opacity on top of the last profile picture in supporters.
Before:
After:
Tested on ios simulator
=> [PAY-591] Improve supporter count visibility

packages/web/src/components/co-sign/CoSign.tsx, packages/web/src/components/profile-progress/components/ProfileCompletionTooltip.js, packages/web/src/components/tooltip/Tooltip.module.css, packages/web/src/components/tooltip/Tooltip.tsx, packages/web/src/components/tooltip/types.ts, packages/web/src/utils/theme/theme.ts
* Fix issue where tooltips would have initial theme's colors after a new theme was applied
* Remove styles referencing `--tooltip-background-color` - this css variable didn't exist
`Tooltip` now does a `localstorage.getItem` on every render. I considered using `useLocalStorage` but that effectively does the same thing
Tested locally and compared tooltip colors & behavior against prod
=> [C-877] Make tooltips use updated colors when theme is applied

packages/common/package-lock.json, packages/common/package.json, packages/mobile/package-lock.json, packages/mobile/package.json, packages/stems/package-lock.json, packages/stems/package.json, packages/web/package-lock.json, packages/web/package.json
Upgrade SDK to v1.0.1
Nothing of note in client. Full Changelog for sdk is here https://github.com/AudiusProject/audius-protocol/commit/ff85889a8b534b90af5fdd0a777f6ac35083b49f
Pointed local client to stage and ran create user, track upload, play track
Sentry and amplitude error rates
No feature flags
=> Bump SDK to v1.0.1

packages/common/src/store/recovery-email/index.ts, packages/common/src/store/recovery-email/selectors.ts, packages/common/src/store/recovery-email/slice.ts, packages/common/src/store/reducers.ts, packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx, packages/mobile/src/store/sagas.ts, packages/web/src/common/store/recovery-email/sagas.ts
Adds native recovery email
Update recovery sagas to be web/native compatible
Adds status key to ensure success/failure toast is only shown when request finishes
=> [C-962, C-904] Native recovery email

packages/common/src/store/ui/buy-audio/slice.ts, packages/web/src/components/buy-audio-modal/components/AmountInputPage.tsx, packages/web/src/components/buy-audio-modal/components/CoinbaseBuyAudioButton.module.css, packages/web/src/components/buy-audio-modal/components/CoinbaseBuyAudioButton.tsx, packages/web/src/components/buy-audio-modal/components/InProgressPage.tsx, packages/web/src/components/buy-audio-modal/components/PurchaseQuote.module.css, packages/web/src/components/buy-audio-modal/components/PurchaseQuote.tsx, packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx, packages/web/src/store/application/ui/buy-audio/sagas.ts
- Consolidate the two spinners into one on the input page, replace the USD estimate
- Disable the buy button if the estimated SOL < 0.05 for coinbase
- Add a step 3 and add the total number of steps "Step 3/3"
- Fix bug where a stray coinbase close event can make the system think it errored when it didn't
- Preload the transaction fees/account creation rent on wallet management tile load to speed up estimates
- Fix the quote being negative causing weird estimates
https://user-images.githubusercontent.com/3690498/188028960-4e07fed7-7540-40e6-9360-9cbfa664509a.mov
*For features that …
=> [PAY-605][PAY-601][PAY-548] Buy Audio modal design changes

packages/web/src/components/artist/ArtistChip.module.css, packages/web/src/components/artist/ArtistChipFollowers.tsx
Fix: https://linear.app/audius/issue/C-822/[qa]-dark-mode-desktop-follows-you-tag-is-not-displayed-properly-in
This is only a problem in the "Followers/Following" modal which is why I made the change in ArtistChip instead of the Follows You badge component itself
=> C-822 Fix dark mode "Follows you" chip

packages/web/src/hooks/useRequiresAccount.ts
Fixes issue where signed in users navigating to /audio page are redirected to /trending page
Essentially our `useRequiresAccount` is not waiting for user object before redirecting.
=> [C-879] Fix rewards page navigation

packages/common/src/services/remote-config/index.ts, packages/common/src/services/remote-config/remote-config.ts, packages/common/src/store/remote-config/sagas.ts, packages/web/src/common/store/account/sagas.js
* Makes `waitForUserRemoteConfig` platform agnostic by using EventEmitter instead of window events
* Updates `init` to be consistent with `setUserId` in using the EventEmitter
Removes the `USER_ID_AVAILABLE_EVENT` event, removed all references in the codebase though
Tested on web, ensured that both callbacks were being hit at the correct time and the Feature Flag override modal still works properly
=> Clean up remote-config init handlers

packages/web/src/components/upload/UploadChip.module.css, packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx, packages/web/src/pages/profile-page/components/desktop/ProfileTags.module.css
Fixed lack of spacing below:
to:
Also fixed order of profile mutuals and profile tags based on this design:
Fixed the profile tags spacing too.
locally v stage
=> Fix profile left nav tile spacing and order

packages/common/src/services/remote-config/defaults.ts, packages/common/src/services/remote-config/types.ts, packages/web/src/components/buy-audio-modal/BuyAudioModal.tsx, packages/web/src/components/buy-audio-modal/components/AmountInputPage.tsx, packages/web/src/components/transaction-details-modal/components/Block.module.css, packages/web/src/components/transaction-details-modal/components/TransactionPurchaseMetadata.module.css, packages/web/src/components/transaction-details-modal/components/TransactionPurchaseMetadata.tsx, packages/web/src/services/audius-backend/BuyAudio.ts, packages/web/src/store/application/ui/buy-audio/sagas.ts
See commit messages:
- [PAY-600 Add optimizely config for button presets](https://linear.app/audius/issue/PAY-600/add-optimizely-config-for-button-presets)
- [PAY-599 Make balance polling timeout configurable](https://linear.app/audius/issue/PAY-599/make-balance-polling-timeout-configurable)
- [PAY-607 Fix icon buttons ("View on Solana Explorer") in Transaction Details](https://linear.app/audius/issue/PAY-607/fix-icon-buttons-view-on-solana-explorer-in-transaction-details)
- [PAY-617 Buy Audio Modal should not be dismissable when in progress](https://linear.app/audius/issue/PAY-617/buy-audio-modal-should-not-be-dismissable-when-in-progress)
*Please describe the tests that you ran to verify your …
=> [PAY-600][PAY-599][PAY-607][PAY-617] RemoteConfig for Buy Audio and better transactiondetails link

packages/web/src/components/notification/Notification/components/ProfilePicture.tsx, packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css, packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx
Last hotfix for feed tip tile had broken profile pictures in top supporters list. This commit fixes that while also keeping the border in the feed tip tile.
Would have preferred to name things differently - `wrapperClassName` for the wrapper and just `classname` for the profile picture class but that would mean I'd have to change the names everywhere else that this is referenced.
Tested on local web.
=> Fixes profile pictures in top supporters tile

packages/web/src/components/edit-track/EditTrackModal.tsx, packages/web/src/components/image-selection/ImageSelectionPopup.js, packages/web/src/components/source-files-modal/SourceFilesModal.tsx, packages/web/src/components/upload/Dropzone.tsx, packages/web/src/pages/upload-page/UploadPage.js, packages/web/src/pages/upload-page/components/SelectPage.js, packages/web/src/pages/upload-page/store/utils/processFiles.ts
Show invalid file on drop again.
We lost this functionality in this change: https://github.com/AudiusProject/audius-client/commit/657cce5bfbe86ab728c6e912745b32811ee43b94 which was generally a good one because it fixed images and also prevents bad audio files from getting dropzoned
This PR:
* moves dropzone to ts
* adds onDropRejected and onDropAccepted so the caller has some more control
* Adds back the functionality in onDropRejected to check mime, size, etc.
* track upload
* stems upload
* image upload on track
* profile pic change
*For features that are critical or could fail …
=> [C-878] Show invalid file errors on upload

packages/common/package.json, packages/mobile/metro.config.js
Fixes issue where metro-config's `nodeModulesPaths` broke expected node_module resolution, resulting `eth-sig-util` resolving to v7 unconditionally, even though some libraries needed v5.
Removing `nodeModulesPaths` fixes this issue, but introduces others. The following "extraNodeModules" resolves those issues. (each case is fairly complex, but can explain further if needed, but suffice to say these complained until added.)
=> [C-988] Fix social actions by fixing metro imports

packages/common/src/services/audius-api-client/AudiusAPIClient.ts, packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
Moves retrieveTracks to the v1 API which is better.
Manually against prod. Went through all usages of retrieveTracks (we never care about bulk hidden ones) because of how the artist dashboard and your own feed work by signing requests.
=> Use bulk tracks from API client

packages/mobile/src/screens/search-results-screen/tabs/TracksTab.tsx, packages/web/src/common/store/lineup/sagas.js, packages/web/src/common/store/pages/search-page/lineups/tracks/sagas.js, packages/web/src/common/store/pages/search-page/sagas.js, packages/web/src/pages/search-page/components/desktop/SearchPageContent.js, packages/web/src/pages/search-page/components/mobile/SearchPageContent.tsx, packages/web/src/store/sagas.ts
=> Native-fy search results tracks lineup

packages/web/src/components/card/desktop/Card.tsx, packages/web/src/components/test-collectibles-playlist-table/TestCollectiblesPlaylistTable.tsx, packages/web/src/components/test-table/TestTable.tsx, packages/web/src/components/test-tracks-table/TestTracksTable.tsx, packages/web/src/components/tracks-table/TracksTable.js, packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
Extension of https://github.com/AudiusProject/audius-client/pull/1698
Fixes several other occurrences of the same bug. 
Also addresses the same issue in `NEW_TABLES` feature flag's new tables.
From @sddioulde 
> The issue was that there was an event.stopPropagation as the click event from the the kebab menu in the track/playlist was bubbling up. This was there so that the underlying track does not play/pause on kebab menu click. However, because the click event stopped bubbling up, the logic for the click outside of already open menus would not trigger, leaving those menus open.
This PR does not stop the click event from bubbling up to the document, and it prevents the play/pause track if the click target is from the kebab menu.
Note that we should continue to stop propagation for clicks …
=> [C-892] Fix multiple menus open at once

packages/common/src/store/pages/profile/lineups/tracks/actions.ts, packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
- Interesting case where the lineup actions are classes, so individual methods cannot be destructured without loosing `this`context
- I did a quick search across rest of mobile app and didn't see other cases where we are destructuring lineup actions
=> Fix profile clearing

packages/common/src/services/audius-backend/AudiusBackend.ts
Artist pages are broken on release candidate: https://release-candidate.audius.co/rac
Only happens when directly visiting the page (not via navigating in the app). Fix is to wait for libs before using it to sign data
This needs to be cherry picked onto release
=> Wait for libs before signing data

packages/common/src/services/audius-api-client/AudiusAPIClient.ts, packages/mobile/src/services/audius-api-client/apiClient.ts, packages/web/src/services/audius-api-client/apiClient.ts
* AudiusAPIClient was referencing `window.audiusLibs`, so when a 404 happened the recursion never ended because`audiusLibs` was always undefined
I was able to repro this by going to `hotelgaruda`'s profile on mobile
This does not enable eager load inside of AudiusBackend, but we are already doing eager load when AudiusAPIClient is used. Might be valuable to rethink this logic in general because if a request 404s, we keep retrying until AudiusLibs is initialized
Can enable eager load in AudiusBackend in the future
Can also dig into why we are requesting a deleted track in the first place
Tested both mobile and web, confirmed that 404 requests only fail until libs is initialized
*Are …
=> [C-1041] Fix infinite 404

packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
#1916 made  it so the handle coming from params is used to fetch the profile, but on the user's own account the param value is `accountUser`. Need to check for this to allow the screen to load
We don't have anyone who actually has the handle `accountUser`, but I wonder if it would break?
=> Fix account profile screen loading

packages/mobile/src/components/lineup/Lineup.tsx
* Because we were using the lineup status to set `refreshing`, scrolling to the bottom and loading more lineup items would scroll to the top and show the refresh indicator
https://user-images.githubusercontent.com/19916043/190211757-a04d3ef0-269d-4a3a-99be-33d81f62fc91.mov
Fixed by setting a local refreshing state that gets cleared when the lineup status is not loading
=> Fix pull to refresh

packages/web/src/electron.js, packages/web/src/pages/App.js
Redid this PR from scratch. @sliptype / @Kyle-Shanks could use extra scrutiny here.
I think there are still two issues with the desktop update flow that prevent "web app" updates from working:
1. we trigger an electron banner update and a web banner update at the same time
2. we are using some state variable `showWebUpdate` to determine whether to show the web update banner, and i'm pretty sure that never gets set to true (it's `showWebUpdateBanner`), so `#1` isn't actually an issue we observe
These changes are set up in a way such though that when we download the electron changes in the background, on restarting, the user will still get the full electron update.
*Please describe the tests that …
=> [C-838] Fix desktop update banner flow

packages/mobile/package-lock.json, packages/mobile/package.json, packages/mobile/src/components/lineup-tile/CollectionTile.tsx, packages/mobile/src/hooks/useProxySelector.ts
Improves selector performance with a new library, [proxy-memoize](https://github.com/dai-shi/proxy-memoize). What this library does to improve our perf is to look at every distinct element in the state that we need for a specific selector, and strictly compare those for any changes. This is much better than what we currently have with reselect, which will trigger a re-render every time our cache changes for selectors that need to grab multiple items from it.
This is just a demo showing it's usage, and we should decide an approach. For collection-list-item, we went from ~80 rerenders to 5, so a 90% reduction! 
Moving forward some things to decide:
- Use this new `useProxySelector` hook for the selectors that require many things from the store
- Update some of our complex selectors directly …
=> [C-1091] Improve selector performance

packages/common/src/services/audius-backend/AudiusBackend.ts
The error was that AudiusLibs.RewardsAttester `is not a constructor`. This seems to fix it? Testing on web now, but I'm confused about how this ever worked before.
=> Fix rewards claiming on mobile C-1043

packages/mobile/src/components/feed-tip-tile/SendTipButton.tsx, packages/mobile/src/components/feed-tip-tile/SenderDetails.tsx, packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/SupporterDethronedNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TipReactionNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TipSentNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TopSupporterNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TopSupportingNotification.tsx, packages/mobile/src/screens/profile-screen/TipAudioButton.tsx, packages/mobile/src/screens/tip-artist-screen/AvailableAudio.tsx, packages/mobile/src/screens/tip-artist-screen/BecomeFirstSupporter.tsx, packages/mobile/src/screens/tip-artist-screen/BecomeTopSupporter.tsx, packages/mobile/src/screens/tip-artist-screen/ConfirmSendTipScreen.tsx, packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx, packages/mobile/src/screens/tip-artist-screen/SendTipStatusText.tsx, packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx, packages/mobile/src/utils/challenges.tsx
Context: https://audius-internal.slack.com/archives/C03C2V84A1L/p1663274118032509
Rename tipping feature to "Send $AUDIO" on iOS only.
Some copy I wasn't sure whether we needed to change or not - left comments in code to highlight in PR review but will delete before merging.
Testing now on release branch v1.3.3 ran locally
=> [C-1118] Send tip -> send audio

packages/mobile/src/components/lineup/Lineup.tsx
* Sets `isPastLoadThreshold` to false when loading in more items so another scroll has to happen before loading in more items
=> [C-940] Fix infinite lineup fetch

packages/mobile/src/components/add-to-playlist-drawer/AddToPlaylistDrawer.tsx
* Disable gesture support (swiping to close) on AddToPlaylist drawer. This enables scrolling the list of playlists which was previously not working
=> [C-894] Allow scroll on AddToPlaylist drawer

packages/mobile/src/components/audio/Audio.tsx
* Use image url from `track._cover_art_sizes`, fallback to default image
* Using 1000x1000 for both platforms now because iOS 16 has larger lock screen artwork
I don't entirely understand the reasoning behind pulling the image from the user metadata endpoint before, but this new method seems to work
=> [C-561] MusicControl artwork

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/services/remote-config/feature-flags.ts
NOTE: Relies on libs changes and version update from https://github.com/AudiusProject/audius-protocol/pull/3706
Adds feature flag to use new entity manager contract for track upload, update, and delete
Could break track changes
locally e2e
=> Add feature flag and entity track manager to client

packages/mobile/src/screens/search-results-screen/tabs/TracksTab.tsx
Ignore the known console errors in the gif lol. 
Before:
-Search something, go to more results then tracks tab
-Scroll to bottom -> crash
After:
-Loads more tracks matching query
=> c-1127 Fix more search results track lineup

packages/web/src/pages/search-page/components/desktop/SearchPageContent.js
Because we are no longer doing `stopPropagation` on click in the `Card` component (https://github.com/AudiusProject/audius-client/commit/f3c02b659d40b15ed6628654fa0dc3bcc0d0186e) any card wrapped in a `Toast` component had toasts appearing when the card/menu was clicked. The only cases of this were on the SearchResults page
Fix is simply preventing the toasts from being trigger via the `firesOnClick` prop
Also uncovered a larger bug that already exists in prod: The toasts don't show up at all from the actions in the overflow menu on SearchResults. For example, clicking "share" copies the link to clipboard but there is no toast or visual feedback. https://linear.app/audius/issue/C-1138/no-tooltips-on-overflow-menu-options-on-search-results Can address this in a future cycle
This `Toast` …
=> [C-1133] Prevent toasts from appearing when overflow menu is clicked

packages/common/src/store/queue/slice.ts, packages/web/src/common/store/queue/store.test.js
We were failing to repeat a single track when shuffle was toggled on. This is because the logic to advance the shuffle index was happening before the repeat single track check in the reducer.
N/A
Manually. Unit test added to cover this behavior in the future, but the test itself couldn't be tested due to broken jest setup on main.
N/A
N/A
=> [C-978] Check for track repeat before advancing shuffle

packages/mobile/src/screens/signon/SignOn.tsx
Fixes bug where typing in email in sign-up, and redirecting to sign-in and inputting password results in "invalid email" which is very confusing. It can be resolved if you click email, delete a value and add it, which resets the email state.
This fix ensures that email doesn't get flushed when moving over
=> [C-1004] Fix sign-up -> sign-in email bug

packages/mobile/src/utils/connectivity.ts
Prevent offline placeholder from flashing on and off when network status is changing rapidly.
We will wait 2 sec before making a call to `updateConnectivity` and only process the last call within the 5 second window.
iOS simulator
=> [C-1137] Add debounce to change in NetworkInfo status

packages/mobile/src/App.tsx
Disabling account sync to check if bounce app breaks on load. This will help us debug whether the issue is ios16 related, or static-server related
=> Disable account-sync to test app failure

packages/common/src/services/audius-api-client/AudiusAPIClient.ts
This is a fun one! Was occasionally getting a ton of "track not found" errors:
Turns out that there is a default limit of 100 on the `getTracks` endpoint https://github.com/AudiusProject/audius-protocol/blob/master/discovery-provider/src/queries/query_helpers.py#L40
We are using that endpoint to fetch all the tracks in collections in a lineup. We pass a big long list of ids and sometimes that list is longer than 100 👀. So we get into a state where collection tracks are only partially loaded on the lineup. 
Fixed by specifying the limit as the number of ids we are requesting. Would probably be more elegant to remove the limit on the `getTracks` endpoint, because why limit the response if we are passing a list of ids? But there is some extra complexity in that endpoint because it handles …
=> [C-951] Fix "track not found" error in collection tiles

packages/common/src/store/pages/search-results/reducer.ts, packages/common/src/store/pages/search-results/selectors.ts, packages/common/src/store/pages/search-results/types.ts, packages/mobile/src/screens/search-results-screen/tabs/SearchResultsTab.tsx, packages/mobile/src/screens/search-results-screen/tabs/TracksTab.tsx, packages/mobile/src/screens/search-results-screen/tabs/useFetchTabResultsEffect.tsx, packages/web/src/common/store/pages/search-page/sagas.js
-Improve search results screen performance
Before: When you switched tabs, it would refetch the results even if it was already fetched before
After: We keep and reuse old results for same query
Regular search:
Tag search:
Tested in mobile and tested for regressions on web.
=> [Reloaded] Keep relevant search results in store c-1117

packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
Fixes bug where scrubber doesn't reset when a song is on repeat. This is because the mediaKey was only changing when track_id changed. In reality though, we should actually just look at playCount.
=> [C-1048] Reset scrubber on song repeat

packages/mobile/src/components/lineup/Lineup.tsx, packages/web/src/common/store/lineup/sagas.js, packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
Fixes case where empty lineups don't show the `ListEmptyComponent`
Also fixes minor bug related to sourceSelector
=> [C-1151] Fix empty profile tab

packages/mobile/src/App.tsx, packages/mobile/src/components/audio/Audio.tsx
This ended up being straightforward but I'm still not sure why the user reference equality breaks
* Refactor `Audio` to redux hooks
* Add equality function to `trackOwner` useSelector
=> [C-1114] Prevent track restart

packages/mobile/package-lock.json, packages/mobile/package.json, packages/mobile/src/styles/makeStyles.ts
Drastically reduces calls (up to 10x less) to `Stylesheet.create` by using style cache. This majorly improves renders for small items, like track-tiles that would otherwise each create their own stylesheet.
=> [C-536] Cache makeStyles StyleSheets

packages/common/src/store/pages/explore/selectors.ts, packages/mobile/src/screens/explore-screen/tabs/ArtistsTab.tsx, packages/mobile/src/screens/explore-screen/tabs/PlaylistsTab.tsx, packages/mobile/src/screens/mood-collection-screen/MoodCollectionScreen.tsx
Some QoL updates for explore screen. Reduces re-renders by 5x. There is a lot more work here we can do though, by delaying fetching playlists/artist tab data until you actually go to that tab. Story added for this after reloaded.
=> [C-1176] Improve ExploreScreen performance

packages/mobile/src/components/empty-tile-cta/EmptyTileCTA.tsx, packages/mobile/src/components/empty-tile-cta/index.ts, packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx, packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx, packages/mobile/src/screens/favorites-screen/TracksTab.tsx, packages/mobile/src/screens/settings-screen/ListeningHistoryScreen.tsx, packages/mobile/src/screens/settings-screen/SettingRowLabel.tsx
- Fixes blank listening history by adding the "empty tile cta" that we have on web.
- Also fixes console warning related to invalid style
=> [C-1174] Fix blank listening history screen

packages/web/package.json
Bad rebase 2 from https://github.com/AudiusProject/audius-client/pull/1577
Env should use .env.dev now instead of the generated .dev.local
npm run start:dev
=> Use .env.dev instead of .env.dev.local

packages/mobile/src/components/audio/Audio.tsx, packages/web/src/common/store/profile/sagas.js
* This fixes the track restart bug when going to the artists profile on mobile
* `creator_node_endpoint` from content node should not be used anyway so we can safely omit it when updating metadata
=> Omit creator_node_endpoint when updating metadata via collectible fetch

packages/mobile/README.md
=> Remove more webview instructions from readme

packages/mobile/src/components/web-app-account-sync/WebAppAccountSync.tsx
Hardcodes stage static-server port to see if bounce crash goes away
=> Hardcode web-sync static-server port

packages/mobile/src/App.tsx, packages/mobile/src/hooks/useAppState.ts, packages/mobile/src/utils/connectivity.ts
Skip updates to connectivity state when in background.
Manually trigger connectivity state update when app returns to foreground.
If we have background processes that rely on the connectivity state, we may need to rethink this. Offline mode comes to mind.
Tested on iPhone 11
=> [C-1181] skip connection check if not in foreground

packages/web/src/components/test-table/TestTable.module.css, packages/web/src/components/test-table/TestTable.tsx, packages/web/src/components/test-tracks-table/TestTracksTable.tsx, packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.module.css, packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx, packages/web/src/pages/artist-dashboard-page/store/actions.js, packages/web/src/pages/artist-dashboard-page/store/reducer.js, packages/web/src/pages/artist-dashboard-page/store/sagas.js, packages/web/src/pages/artist-dashboard-page/store/selectors.ts, packages/web/src/pages/artist-dashboard-page/store/types.ts
Adding show more functionality to the new table and update artist dashboard to display the new table with pagination for users with a lot of tracks
Backend updates are needed to resolve the listed vs unlisted track problem, but there is a linear issue to fix that.
N/A
N/A
N/A
=> [C-849] Add new table for Artist Dashboard

packages/mobile/src/components/navigation-container/NavigationContainer.tsx, packages/mobile/src/hooks/usePopToTopOnDrawerOpen.ts, packages/mobile/src/screens/root-screen/RootScreen.tsx
A few mistakes with the new app-tab-navigation-context: 
- It was too low in the stack so modals didn't have access to it
- It wasn't updating correctly since useEffect was only running the first time a tab is rendered, but we want to update whenever it's active
=> Fix navigation context scope and setting

packages/common/src/hooks/useImageSize.ts, packages/web/src/components/artist/ArtistPopover.tsx, packages/web/src/components/notification/Notification/components/ProfilePicture.tsx, packages/web/src/components/remix-card/RemixCard.tsx, packages/web/src/hooks/useCollectionCoverArt.ts, packages/web/src/hooks/useImageSize.test.tsx, packages/web/src/hooks/useTrackCoverArt.ts, packages/web/src/hooks/useUserCoverPhoto.ts, packages/web/src/hooks/useUserProfilePicture.ts
- Fixes pretty interesting/bad bug where we are dispatching fetch image actions in the render cycle by moving dispatch to useEffect/useCallback depending on onDemand value)
- Updates types to properly type useImage based on onDemand value
- Updates usages, particularly onDemand cases (in ArtistPopover) to use special hook rather than overloading useProfileImage and useCoverPhotoImage to match the useImage types in common
=> [C-1195] Fix image loading in image hooks

packages/mobile/src/components/now-playing-drawer/Artwork.tsx, packages/web/src/common/store/cache/tracks/sagas.js
This prevents crash on android. We can revisit dominant color when we tackle glass morphism on the NowPlaying drawer
=> Disable dominant color on mobile

packages/web/src/pages/profile-page/ProfilePageProvider.tsx, packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Fixes issue where non artist profile's reposts tab was not rendering. This regression occured because the initialState of lineups has changed from Status.LOADING to Status.IDLE
=> Fix profile reposts loading issue

packages/mobile/src/components/feed-tip-tile/FeedTipTileSkeleton.tsx, packages/mobile/src/components/skeleton/Skeleton.tsx, packages/mobile/src/screens/profile-screen/ProfileScreen.tsx, packages/mobile/src/screens/profile-screen/ProfileScreenSkeleton.tsx
- Adds profile skeleton, which drastically improves UX for profiles loaded from search screen or deep-link, and other cases where the profile hasn't been fetched yet.
- Adds `noShimmer` option to `Skeleton` which is good for some skeletons that are small, like we have here for the bio element.
> Note: there is some lineup jank present when the profile data is first fetched present in this video. This will be addressed in a separate pr
https://user-images.githubusercontent.com/8230000/193168912-d12caf17-7979-4b25-b2ea-10f94ff9562a.mp4
=> [C-1128] Add profile screen skeleton

packages/mobile/src/components/top-tab-bar/CollapsibleTopTabNavigator.tsx, packages/mobile/src/screens/profile-screen/ProfileTabNavigator.tsx
Fixes issue where profile lineups load underneath the profile header, and all the way at the top, then suddenly transition down. This is due to collapsible-tabs not knowing the height of the header on the first load. Adding a default value that is around the height of an average header.
=> [C-481] Fix profile header loading jank

packages/mobile/src/screens/profile-screen/RepostsTab.tsx, packages/mobile/src/screens/profile-screen/TracksTab.tsx, packages/mobile/src/screens/profile-screen/selectors.ts
Fixes mobile tracks/reposts by ensuring handle is lowerCased, which we need since the profile state references lowercase handles. Ultimately i think we should move all the `.toLowerCase` code to the actions/reducers/selectors so the consumer doesn't have to think about this. This pr unblocks tho.
=> Fix tracks/reposts lineups for artist with handles with capitials

packages/web/src/pages/upload-page/UploadPage.js
Add is_premium and premium_conditions default values
Track upload flow should work.
Local client against stage. Uploaded track. Played it.
n/a
none
=> Add premium content default fields to track upload

packages/common/src/store/pages/profile/selectors.ts, packages/web/src/common/store/cache/collections/sagas.js, packages/web/src/common/store/pages/saved/sagas.js
Problems were:
1. Not awaiting the `getFeatureFlag` call in sagas
2. Not filtering out _moved playlists
=> Fix duplicate playlists once playlist is confirmed  / Await feature flag response in sagas C-1199

packages/mobile/src/services/track-download.ts
Fixes runtime error due to calling `new URL` in native. It was tricky since `URL` works when the Chrome debugger is active, which is why we missed this.
=> [C-1207] Fix stem downloads

packages/common/src/store/pages/profile/reducer.ts, packages/common/src/store/pages/profile/selectors.ts, packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx, packages/mobile/src/screens/profile-screen/ProfileScreen.tsx, packages/web/src/common/store/profile/sagas.js
Fixes edit-profile flow by adding a few improvements to profile state.
- Condenses three state variables, `updating`, `updateSuccess`, and `updateError` into an `updateStatus` variable that can be selected.
- Potentially improves the values of the various variables with the `updateProfile` `updateProfileSuccess` and updateProfileError` actions
- Moves `updateProfileSucceeded` to the onSuccess confirmer callback
- Updates profile screen to only fetch profile when we are not in "edit mode, ie waiting for edit confirmation, cause otherwise the values are overwritten
=> [C-1179] Fix edit-profile

packages/web/src/components/audio-transactions-table/AudioTransactionsTable.module.css, packages/web/src/components/audio-transactions-table/AudioTransactionsTable.tsx, packages/web/src/components/audio-transactions-table/index.ts, packages/web/src/components/test-table/TestTable.module.css, packages/web/src/components/tracks-table/TracksTable.js, packages/web/src/pages/App.js, packages/web/src/pages/audio-transactions-page/AudioTransactionsPage.module.css, packages/web/src/pages/audio-transactions-page/AudioTransactionsPage.tsx, packages/web/src/pages/audio-transactions-page/index.ts, packages/web/src/utils/route.ts
* Add route for audio transactions page
* Add AudioTransactionsPageProvider and desktop page to add the scaffolding for later and display the test data
* Add the AudioTransactionsTable component to display the transaction detail rows
Needs to be updated when the backend is setup to return audio transaction information and pipe that into the table.
Table may need to be updated based on the actual data and based on sorting and filtering and things
N/A
N/A
=> [C-850, C-950] Add AudioTransactionsPage and display test data in AudioTransactionsTable

packages/common/tsconfig.json, packages/stems/tsconfig.json
Fixes go-to-definition for built packages, leveraging a declarationMap ts feature, which proxies the d.ts file to the source code.
=> [C-972] Fix go-to-definition for common/stems

packages/common/src/store/pages/search-results/reducer.ts, packages/mobile/src/components/collection-list/CollectionList.tsx, packages/mobile/src/screens/search-results-screen/tabs/AlbumsTab.tsx, packages/mobile/src/screens/search-results-screen/tabs/PlaylistsTab.tsx, packages/mobile/src/screens/search-results-screen/tabs/ProfilesTab.tsx, packages/mobile/src/screens/search-results-screen/tabs/SearchResultsTab.tsx
- Fixes rendering issues in search results page, where "no results" pops up for a moment, and then loading indicator appears.
- Improves rerender perf by using useProxySelector and simplified selectors.
- Improves reducer logic to be a bit more straightforward, and prevent uneccesary state changes
=> [C-1201,C-1202] Improve search results rendering and perf

packages/mobile/src/screens/root-screen/RootScreen.tsx
Improves TTI for first render by preventing rendering of sign-in screen until we know user account has been attempted to be fetched
=> Prevent rendering root until account fetched

packages/mobile/src/components/lineup/Lineup.tsx, packages/mobile/src/hooks/usePopToTopOnDrawerOpen.ts, packages/mobile/src/screens/app-screen/AppTabNavigationProvider.tsx
- Improves all lineup perf by ensuring we don't trigger a full rerender on it when we are out of view. This significantly improves navigating to profile from feed.
- Improves bottom-tab-navigation by splitting up the reading of bottom-bar-navigation object, and setting of it. Having them together meant that each bottom bar would trigger a full rerender on the one that was being left, slowing that initial navigation.
=> [C-1200] Improve lineup and bottom-tab perf

packages/mobile/src/components/core/FlatList.tsx, packages/mobile/src/components/core/PullToRefresh.tsx, packages/mobile/src/screens/root-screen/RootScreen.tsx
There was a 6 pixel overlap where spinner was sometimes visible over its content.
=> [C-1236] Ensures refresh spinner does not float over content

packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
Without pointer-events specified, that entire area couldn't be scrolled
=> [C-1221] Improve profile socials scroll target

packages/mobile/src/hooks/useNavigation.ts, packages/mobile/src/screens/app-screen/AppTabNavigationProvider.tsx
Refactors debounced navigation solution with a custom push function.
Inspiration here: https://github.com/react-navigation/react-navigation/issues/3839#issuecomment-377159605
dispatch docs: https://reactnavigation.org/docs/navigation-prop/#dispatch
Instead of using the nearest navigator, we are defaulting to the AppStack Navigator, which should result in consistent behavior. Without this, when we were in a collapsible tab bar, we didn't have access to the previous route, so it wouldn't work.
=> [C-1254] Fix debounced navigation

packages/common/src/services/fingerprint/FingerprintClient.ts, packages/common/src/store/storeContext.ts, packages/mobile/android/build.gradle, packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj, packages/mobile/ios/Podfile, packages/mobile/ios/Podfile.lock, packages/mobile/package-lock.json, packages/mobile/package.json, packages/mobile/src/services/fingerprint.ts, packages/web/package-lock.json, packages/web/src/services/fingerprint.ts
~This doesn't 100% work because the `2.0.0` release of https://github.com/fingerprintjs/fingerprintjs-pro-react-native doesn't support our version of react-native. The previous version `1.0.4` doesn't support passing the `linkedId` that we use to match fingerprints with user handles
It's not really feasible to upgrade react native before releasing the reloaded work. Wanted to get some input on whether this react-native fingerprint without `linkedId` would be fine for now. I assume we are using that to prevent extra fingerprints on the same user?~
Works after removing `__apply_Xcode_12_5_M1_post_install_workaround` script from our podfile. I don't believe this script is necessary anymore.
* Add react-native Fingerprint client
*Is there anything the reviewer should be on the lookout for? …
=> [C-1267] Fingerprint in react-native

packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx, packages/mobile/src/components/now-playing-drawer/Artwork.tsx, packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx, packages/mobile/src/components/now-playing-drawer/PlayBar.tsx, packages/mobile/src/components/now-playing-drawer/TrackInfo.tsx, packages/mobile/src/components/scrubber/Slider.tsx
A lot to unpack here.
At it's simplest, the app-background -> app-foreground scrubber position recalculation was happening too often, which was incorrectly setting it for tracks that are short. Explicitly checking previous app-state before calculating prevents that recalc.
However as I was digging around I noticed a pretty major performance regression, which is that we were literally un-rendering, and then quickly re-rendering the entire the now-playing drawer at the end of every song.... this was due to logic in now-playing drawer to require user and track before rendering. This was further complicating the scrubber calc logic cause the component would always run its effects cause it was a remount. I was able to get it to always stick around and handle the null user/track case, which is …
=> [C-1269] Fix now-playing drawer and scrubber

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/mobile/src/services/audius-backend-instance.ts
The logic that handles fetching images from secondaries & legacy image formats is unfortunately split into two places:
Magic image component in native: https://github.com/AudiusProject/audius-client/blob/ee0b668b1165d7f980cf12b8fe59b8dfe5e77ece/packages/mobile/src/components/image/UserImage.tsx#L56
Libs: https://github.com/AudiusProject/audius-protocol/blob/6fdd8a88cb3d72da43743def17255c0fcc40edc7/libs/src/api/File.ts#L94
I think probably we want to move everything to magic image component in native, but this in the near-term makes all "Dynamic Images" work since the magic image thing in native isn't built to handle multiple sizes yet.
Curious for thoughts on this PR...!
At least this doesn't incur double fetch and we are doing some preloading!
*Is there anything the reviewer should be on …
=> [C-1166] Avoid only primary image

packages/mobile/src/components/co-sign/CoSign.tsx, packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx
* Fix styling of remixes tile on track screen by overriding `flex: 1` (which was added to position the cosign check icon on the track screen artwork)
=> [C-1268] Fix height of remixes tile

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/mobile/src/screens/audio-screen/AudioScreen.tsx, packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx, packages/web/src/common/store/pages/audio-rewards/sagas.ts, packages/web/src/utils/sagaPollingDaemons.ts
Polling daemon stuff is implemented using document event listeners.
Another solution here would be to supply the saga context with some sort of lifecycle hook, but that's somewhat of an involved change and think this is easier to at least make sure we have the same functionality!
1. Tested passive polling on interval behavior
2. Tested bringing app into foreground
=> [C-1185] Get user challenge polling daemon working in native

packages/mobile/src/hooks/useNavigation.ts, packages/mobile/src/screens/root-screen/HomeScreen.tsx, packages/mobile/src/screens/root-screen/RootScreen.tsx, packages/mobile/src/screens/splash-screen/SplashScreen.tsx
After lots of testing, I believe the source of the white screen is due to the final frames of the splash being fully white, and lag associated with removing the Lottie animation from the view when animation is finished. When there is lag (due to so many things competing for main thread), the animation is paused in it's final frames, hence the white screen issue. To avoid this, I added an opacity animation that is delayed and quick on the back half of the animation, resulting in 0 opacity for the final frames of the lottie animation as it's being removed. It looks much better I think!
While experimenting with reducing the main thread churn as sign-in/feed is loading in (which could potentially improve speed at which the splash screen is removed from dom), I realized we could drastically …
=> [C-1205,C-1273] Improve splash screen animation, root screen management

packages/common/src/store/pages/collection/actions.ts, packages/mobile/src/screens/collection-screen/CollectionScreen.tsx, packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx, packages/mobile/src/screens/smart-collection-screen/SmartCollectionScreen.tsx
Basically the `resetCollection` action was incorrectly typed, requiring CID and userCID, but smart collections don't have CID. Updating type and updating useFocusEffect in collections-screen to call reset even if CID/userCID not there.
- Also updated the smart collection code to conform a bit more to our standards
- Removed the console.warn about missing user/collection for collection screen, since this is possible with normal behavior, we should add a skeleton eventually tho
=> [C-1246] Fix smart collections

packages/web/src/components/test-table/components/OverflowMenuButton.tsx, packages/web/src/components/test-tracks-table/TestTracksTable.tsx, packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
Remove edit option so that things dont seem at broken
N/A
N/A
N/A
=> Remove track edit option from new dashboard table overflow menus

packages/mobile/src/components/core/Screen.tsx, packages/mobile/src/components/navigation-container/NavigationContainer.tsx, packages/mobile/src/components/scrubber/Slider.tsx, packages/mobile/src/screens/audio-screen/AudioScreen.tsx, packages/mobile/src/screens/collection-screen/CollectionScreen.tsx, packages/mobile/src/screens/profile-screen/ProfileScreen.tsx, packages/mobile/src/screens/root-screen/RootScreen.tsx, packages/mobile/src/screens/settings-screen/SettingsScreen.tsx, packages/mobile/src/screens/signon/SignOn.tsx, packages/mobile/src/screens/track-screen/TrackScreen.tsx, packages/mobile/src/utils/navigation.ts
* Add analytics on screen change on mobile
* Primary routes are recorded via the NavigationContainer `onStateChange`
* Secondary routes are recorded via effects in the corresponding components
This is necessary because in some cases the data needed to build the url is not available in the navigation state. Track screen for example records a url like this: `/KSHMRmusic/anywheres-home` but we only have track id available in the navigation state …
=> [C-977] Add Screen change analytics

packages/common/src/store/ui/buy-audio/slice.ts, packages/web/src/store/application/ui/buy-audio/sagas.ts
- Remove unused setProvider action
- Add action to trigger recovery flow, use `takeLeading` to process the first action
It hasn't yet
=> [PAY-677] Prevent multiple recovery flow triggers

packages/mobile/src/components/web-app-account-sync/WebAppAccountSync.tsx
* The account status was being set to ERROR because the account wasn't found in local storage and currentUserExists was also not in local storage https://github.com/AudiusProject/audius-client/blob/main/packages/web/src/common/store/account/sagas.js#L210
* Setting `CURRENT_USER_EXISTS_LOCAL_STORAGE_KEY` to true when the entropy is synced fixes this issue
| Release branch | Apple Store Version | |
|-----------------|--------------------|---|
| 1.3.3                   | 1.1.30                         | doesn't have native sagas, the entropy sync failed |
| 1.3.2                   | 1.1.29                         | has native sagas, the entropy sync worked |
Tested by confirming the bug when …
=> [C-1284] Fix entropy sync for versions other than 1.1.29

packages/mobile/src/screens/favorites-screen/TracksTab.tsx, packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Improves bottom bar and profile perf by only fetching data once. Users can still see updated data for profile with pull-to-refresh.
=> Only fetch favorites/profiles once

packages/web/src/store/application/ui/buy-audio/sagas.ts
Stop the BuyAudio flow when the user cancels the third-party onramp
=> [PAY-679] Stop BuyAudio flow when user cancels the onramp

packages/web/src/services/audius-backend/BuyAudio.ts
If the wallet initially has no transactions, this code would set the initial transaction to the first transaction after the polling starts, which is already the purchase transaction in stripe's case, so the polling would timeout.
=> BuyAudio: Fix for if wallet has no transactions

packages/mobile/src/screens/signon/CreatePassword.tsx, packages/mobile/src/screens/signon/SignOn.tsx
The bold Avenir LT Pro font isn't compatible with the text input for whatever reason (confirmed this by simply getting rid of the font family and everything worked as expected). In this gif you can see that the second character and on are still lower than the first character. But I at least could get rid of the clipping by getting rid of the vertical padding.
=> Fix password input clipping on mobile sign in/up C-1234

packages/web/src/common/store/profile/sagas.js
* Collectibles failing to load on profiles without either solana nfts or ethereum nfts
* Undo a perf change to prevent cache update when no collectibles exists. The result of this cache update is used to determine loading state on collectibles tab
=> [C-1311] Fix Collectibles

packages/web/src/components/tipping/tip-audio/SendTip.tsx
Removes the insufficient funds error, adds a button that links to $AUDIO page.
https://user-images.githubusercontent.com/3690498/194964813-feff4dc2-cfc0-4c2b-93d6-683847510f7b.mov
=> [Stripe Demo] Always show a "Buy More $AUDIO" button in tipping dialog

packages/mobile/src/components/lineup-tile/TrackTile.tsx
`navigation.getState` is not defined for a brief period when reopening the app on android. Opted to use `useNavigationState` instead for safety
=> [C-1316] Fix getState undefined crash when opening reopening app on android

packages/common/src/store/pages/profile/selectors.ts
Fixes issue where users with captials in their handle mess up with some of our selectors. By updating our profile selectors to always `toLowerCase`, this fixes any other issues.
I may remove some cases where we are manually `toLowerCase`ing things in the client, but this ultimately should fix things
Looking at clayton's account, his collectibles only have one entry. is this expected?
=> [C-1309] Fix playlists/collectibles not loading

packages/common/src/store/pages/profile/reducer.ts
Removes follow user social reducers in profile reducer. This doesn't really make sense, since the profile that is selected is not guaranteed, and on top of that we don't actually use the users for followers/followees in dekstop or native anymore. I think it would make sense for use to remove profile.followees, and profile.followers in the state.
=> [C-1282] Remove followUser social action in profile reducer

packages/common/src/services/opensea-client/OpenSeaClient.ts, packages/common/src/services/opensea-client/index.ts, packages/common/src/store/storeContext.ts, packages/mobile/ios/Podfile.lock, packages/mobile/src/screens/profile-screen/CollectiblesCard.tsx, packages/mobile/src/store/storeContext.ts, packages/web/src/common/store/profile/sagas.js, packages/web/src/store/storeContext.ts
Fixes issue where native profile collectibles were not displaying ethereum collectibles. This had to do with OpenSeaClient referencing `process.env`, which isn't avail on mobile. This was fixed by moving openSeaClient to storeContext and providing the correct url.
- Also fixes issue where the wrong chain icon was rendering.
- Also updates Podfile since we downgraded fingerprint
=> [C-1319] Fix native profile collectibles

packages/mobile/ios/Podfile.lock, packages/mobile/package-lock.json, packages/mobile/package.json, packages/mobile/src/screens/profile-screen/CoverPhoto.tsx
=> Bump react-screens to 3.17.0 to avoid crash on android

packages/mobile/src/components/bottom-tab-bar/BottomTabBarButton.tsx, packages/mobile/src/components/core/AnimatedButton.tsx, packages/mobile/src/components/now-playing-drawer/PlayBar.tsx, packages/mobile/src/utils/zIndex.ts
-Improve now playing bar touch target by removing unnecessary hitslop from bottom buttons
-Fix favorite and play button touch targets on the now playing bar at the bottom by increasing the z-index of the play bar container
=> Fix play bar buttons target (Android) C-1264

packages/web/src/components/mobile-page-container/MobilePageContainer.tsx, packages/web/src/components/page/Page.js, packages/web/src/pages/collection-page/CollectionPageProvider.tsx, packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx, packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx, packages/web/src/pages/deleted-page/DeletedPage.tsx, packages/web/src/pages/deleted-page/DeletedPageProvider.tsx, packages/web/src/pages/deleted-page/components/desktop/DeletedPage.tsx, packages/web/src/pages/deleted-page/components/mobile/DeletedPage.tsx, packages/web/src/pages/explore-page/ExplorePageProvider.tsx, packages/web/src/pages/explore-page/components/desktop/ExplorePage.tsx, packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx, packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx, packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx, packages/web/src/pages/track-page/TrackPageProvider.tsx, packages/web/src/pages/track-page/components/desktop/TrackPage.tsx, packages/web/src/pages/track-page/components/mobile/TrackPage.tsx, packages/web/src/pages/trending-page/TrendingPageProvider.js, packages/web/src/pages/trending-page/components/desktop/TrendingPageContent.tsx, packages/web/src/pages/trending-page/components/mobile/TrendingPageContent.tsx, packages/web/src/pages/trending-page/types.ts, packages/web/src/pages/trending-playlists/TrendingPlaylistPage.tsx, packages/web/src/pages/trending-underground/TrendingUndergroundPage.tsx, packages/web/src/utils/seo.ts
Pass at improving SEO on the client
* Adds Schema Structured Data
* Updates title and description on several pages: user/track/collection, trending, explore
* Fixed canonical url on album pages - there was a bug where we were using the /playlist instead of /album path
Fixes PLAT-325
Fixes PLAT-347
Fixes PLAT-346
Fixes PLAT-341
Ran the client locally against stage and inspected the page head
=> Add structured data and update head

packages/mobile/devUtils/useRenderingTrace.ts, packages/web/devUtils/useRenderingTrace.ts
Add utility fn for determining why components rerendered.
This is a useful companion to the react profiler, since sometimes the profiler doesn't tell you exactly what caused the rerender.
Decided against putting this in common because mobile (react native) doesn't tree shake. That being said though, I don't think this is big enough to make a difference, so I'm down for either way!
=> Add rendering trace util

packages/common/src/store/ui/buy-audio/slice.ts, packages/mobile/package-lock.json, packages/web/package-lock.json, packages/web/src/components/buy-audio-modal/BuyAudioModal.tsx, packages/web/src/components/buy-audio-modal/components/InProgressPage.tsx, packages/web/src/store/application/ui/buy-audio/sagas.ts
The recovery modal would try to open the success screen of the BuyAudio modal, but there would be no provider set.
Works with this PR. Example transaction details on success:
Tested using Phantom to send my root account some SOL and triggering the recovery flow.
=> [PAY-680] Fix BuyAudio recovery success modal

packages/web/src/hooks/useLocalStorage.ts
The only place this hook is used is on the `ReceiveBody.tsx` component, where it's used to acknowledge that the user has dismissed the warning around receiving $AUDIO. This bug manifests such that the user has to repeatedly acknowledge and click "I understand"
=> [PAY-705] Fix useLocalStorage hook to use getItem rather than getValue

packages/web/src/components/profile-picture/ProfilePicture.js
Fixes issue where blank profile picture was using the default placeholder image, which did not provide enough contrast. 
Before: 
After: 
Do we want to apply `usePlaceholder={false}` for all `ProfilePicture` components?
=> [C-1302] Fix blank profile picture background color

package-lock.json, package.json, packages/common/src/models/User.ts, packages/common/src/schemas/index.ts, packages/common/src/services/audius-api-client/types.ts, packages/common/src/services/audius-backend/AudiusBackend.ts, packages/web/src/common/store/cache/tracks/sagas.js, packages/web/src/common/store/cache/users/sagas.js, packages/web/src/common/store/social/tracks/sagas.ts
Currently artist pick lives in the identity service. With this change, we'll also write `artist_pick_track_id` to the users table in discovery when a user pins a track in the client. This is the first part in the migration to completely to reading and writing the artist pick from discovery.
Web:
- Run client with changes locally. Test against staging data, which has API updates to show the artist_pick_track_id on a user in discovery.
- Set artist pick in UI. Verify artist pick was set via API.
- Remove artist pick. Verify change with API.
- Set new artist pick in UI. Verify change with API.
- Delete track. Verify change with API
Mobile:
- Make sure tracks list correctly reflects each change above ^
`updateCreator` is gated by the `USER_ENTITY_MANAGER_ENABLED` feature flag.
=> Dual writes when setting artist pick

packages/mobile/android/app/src/main/AndroidManifest.xml, packages/mobile/src/screens/signon/SignOn.tsx
* Improve layout of sign on screen so there is no overflow on android devices
* Update `windowSoftInputMode` so that the android keyboard overlays on top of the app, similar to ios
Before
After
> Side note: does the space between the email input and the sign up button seem too large to anyone else?
THIS TOUCHES SIGN ON
Also changing the keyboard mode could be dangerous, but I thoroughly tested cases where it could be problematic (outlined below)
Tested on pixel 3 which was exhibiting the problem, as well as OnePlus 7T and ios devices
Tested scroll behavior on android with new keyboard mode on
* Search
* Edit Profile
* Create / edit playlist
*Are all new features properly feature …
=> [C-1261] Android sign on overflow

packages/common/src/models/Analytics.ts, packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx, packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx, packages/web/src/store/application/ui/buy-audio/sagas.ts
** Reviewer note: Go commit by commit **
See commit messages and linear items.
cc: @dylanjeffers / @sliptype : I'm using sentry more directly instead of putting an action or console.erroring, Is this ok?
=> [PAY-703][PAY-698][PAY-699][PAY-686] Various Stripe Fixes pt 1

packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx, packages/mobile/src/hooks/useNavigation.ts, packages/mobile/src/store/mobileUi/sagas.ts
* Fix double navigation on android by listening to the `transitionEnd` event on the current navigator
* Fix now playing bar offset by accounting for the translucent status bar
* Don't hide status bar when now playing drawer is open on android. Showing/hiding the status bar on android causes a lot of UI shift
=> [C-1359] Prevent double navigation on android, plus StatusBar fixes

packages/common/src/services/audius-api-client/AudiusAPIClient.ts, packages/web/src/common/store/cache/users/sagas.js, packages/web/src/common/store/pages/signon/sagas.js
Iteration on #2183
Because `404` response codes trigger a discovery node reelection, the check for user not existing will trigger this logic and results in longer method response times. 
This change is to pass along a flag for `retry` so that checking for an existing handle will not trigger reslection and be instant!
Not sure if there's a mobile component to this that I'm missing @sliptype 
Fixes PLAT-432
Ran locally against stage and validated that no re-selection were happening for non-existent handles. 
=> Pass retry through for client handle validation

packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx, packages/mobile/src/hooks/useNotificationNavigation.ts, packages/mobile/src/notifications.ts, packages/mobile/src/screens/app-screen/AppTabNavigationProvider.tsx, packages/mobile/src/screens/app-screen/AppTabScreen.tsx, packages/mobile/src/screens/notifications-screen/Notifications/AddTrackToPlaylistNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/FavoriteNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/FollowNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/RemixCosignNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/RemixCreateNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/RepostNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/SupporterDethronedNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TierChangeNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TipReactionNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TipSentNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TopSupporterNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TopSupportingNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TrendingTrackNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/UserSubscriptionNotification.tsx, packages/mobile/src/screens/notifications-screen/NotificationsDrawer.tsx, packages/mobile/src/screens/profile-screen/ProfileScreen.tsx, packages/mobile/src/screens/profile-screen/selectors.ts
Add notification navigation hook to be used by notification components and push notifications
This can be updated to have separate handlers for each notification type, but wanted to get the basics down
The structure of notifications coming back from identity is not the same as client side, so need to do a lot of verification to make sure that this will work for push notifications
Manually tested with a lot of notif types, but need to do testing on device to work out the kinks with push notifications
N/A
N/A
=> Add notification navigation hook and update profile screen to accept id param

packages/common/src/services/audio-player.ts, packages/common/src/services/remote-config/defaults.ts, packages/common/src/services/remote-config/feature-flags.ts, packages/common/src/services/remote-config/types.ts, packages/mobile/src/components/audio/Audio.tsx, packages/web/src/common/store/player/sagas.ts, packages/web/src/services/audio-player/AudioPlayer.ts
This reverts https://github.com/AudiusProject/audius-client/pull/2147 and uses a feature flag to switch playback from hls to mp3.
Once this has been verified in prod, we can go back and rip out the unused hls code as originally done in https://github.com/AudiusProject/audius-client/pull/2147
See the non-revert commit [9313d83](https://github.com/AudiusProject/audius-client/pull/2202/commits/9313d83f0de8352f102584ca26327c430125c00d) for effective changes.
Affects all of track streaming.
Local web and sim
Tested with feature flag on and off. The correct endpoint was used in both cases
Metrics for track play/listen will drop if malfunctioning
`STREAM_MP3`
- `true`: use mp3
- `false`: use hls
=> Use feature flag for mp3 stream toggle

packages/common/src/utils/sagaHelpers.ts, packages/web/src/pages/upload-page/store/sagas.js
Not sure how this was ever working before, but calling close on the progress channel puts an undefined action, so we would typically use the channelCanceller to close the channel because it would take the last undefined action and then call cancel
ref: https://github.com/AudiusProject/audius-client/blob/8cc3a29a7582323dbd19c1fa9a6ce0f45daf3c1b/packages/common/src/utils/sagaHelpers.ts#L47-L53
But since the current logic called close, the action channel dispatcher is called with an action of undefined which is put and then throws an error on the webpage
ref: https://github.com/AudiusProject/audius-client/blob/8cc3a29a7582323dbd19c1fa9a6ce0f45daf3c1b/packages/common/src/utils/sagaHelpers.ts#L40-L45
*Is there anything the reviewer should be on the lookout for? Are there any dangerous …
=> Fix upload

packages/common/src/models/Analytics.ts, packages/web/src/pages/upload-page/store/sagas.js, packages/web/src/pages/upload-page/store/utils/sagaHelpers.ts
Upload flow is extremely difficult to reason with, but I did what I could here for now to hopefully get somewhat more useful metrics:
1. New metric for rejected in addition to success / failure. That will make this graph more useful: https://analytics.amplitude.com/audius/chart/b9jlu2b?linkingDashboardId=p8cbu9n. It should be 100% or something is broken and we don't understand why
2. In the single-track upload case COMPLETE_UPLOAD will get recorded if that single track was rejected (per what this ticket calls for). However, this is really tough to do in the case of playlists/albums where one of multiple tracks could get rejected and then it's really hard to determine how we should count those metrics. With this change, we will at least infer how many of the batch were rejected (which …
=> [C-1323] Somewhat improve upload metrics

packages/mobile/src/components/core/Screen/Screen.tsx
Then new mobile-nav-overhaul includes a change to the secondary screen background color, which was missed.
=> Update secondary screen background color

packages/common/src/store/ui/buy-audio/selectors.ts, packages/common/src/store/ui/buy-audio/slice.ts, packages/web/src/components/buy-audio-modal/components/SuccessPage.tsx, packages/web/src/components/tipping/tip-audio/SendTip.tsx, packages/web/src/components/tipping/tip-audio/TipAudio.module.css, packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Takes the user to the trending page to find an artist to support if they open the BuyAudio modal from the $AUDIO page. Also makes the topbanner in tips static white.
Locally against prod
=> [PAY-716] Go to Trending after BuyAudio flow if not opened from Tip

packages/mobile/src/screens/splash-screen/SplashScreen.tsx
* The lottie animation occasionally plays some erroneous extra frames when running on hermes. By using the opacity animation end as the trigger to remove the splashscreen, the glitch is fixed
* Still looking into why we are occasionally seeing a blank white screen after the splash screen, will make separate pr 
=> Fix splashscreen animation glitch when running on hermes

packages/web/src/common/store/cache/tracks/sagas.js
This has likely not been necessary for a long time (since streaming from IPFS directly). It was used to keep the IPFS caches warm, but optimize for UX. Given the only small concerns about initial playback delay with MP3s, stoked to remove this from the client which should re-render less and remove many many network reqs.
Local client
=> Remove prefetch first segment functionality

packages/mobile/src/screens/account-screen/AccountDrawer.tsx, packages/mobile/src/screens/app-drawer-screen/AppDrawerScreen.tsx, packages/mobile/src/screens/notifications-screen/NotificationsDrawer.tsx, packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx
Fixes tip reactions in notification tab bar.
Issues due to `disabledGestures` not being propagated down correctly, so the drawer opens when interacting with reactions. additionally interaction can only occur when the reactions are visible and the tab bar / notif drawer is focused on screen
=> [C-1428] Fix tip reactions in notifications tab

packages/mobile/src/hooks/useUpdateRequired.ts
* Updated optimizely `MIN_APP_VERSION` to 1.3.11 earlier and it bricked mobile because the `useUpdateRequired` hook is checking the mobile app version which is different on android/ios from web/desktop. Using the version in the package.json is more useful
=> [C-1451] Use package.json version number in mobile updateRequired check

packages/web/src/store/errors/sagas.ts
There has been a large drop off in error page analytics since february https://analytics.amplitude.com/audius/chart/hghn2r9/edit/hzfdg28?source=copy+url
`redirectRoute` is defaulted to `ERROR_PAGE`. But error page analytics were not being recorded when `redirectRoute` exists
* Update error saga logic so analytics are recorded when redirectRoute is `ERROR_PAGE`
Perhaps it would be better to have an effect in the error page component itself? Because currently these analytics are triggered on every error, so potentially multiple times even though the user is only seeing the error page once
Tested by throwing errors in react hierarchy and dispatching error actions in sagas. Also realized that actual errors getting thrown in sagas do not redirect to the error page (just get a blank screen) …
=> [C-1443] Fix error page analytics

packages/mobile/src/components/audio/Audio.tsx, packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
* Match behavior from web, pressing `previous` within 3 seconds of the beginning of a track will restart the track
=> [C-1467] Make previous button restart track within 3 seconds

packages/web/src/common/store/pages/saved/sagas.js
The SavedPageProvider fires the fetch saves action before the saga is registered, since `takeLatest` is called only after waiting for the backend/client
tested locally against stage
=> [ARCH-1996] hotfix: takeLatest was registering after action already fired

packages/web/src/pages/visualizer/VisualizerProvider.tsx, packages/web/src/services/audio-player/AudioPlayer.ts
Also fixes some behavior around fadeIn/fadeOut that has been bugging me for a while.
I'm not entirely sure how this fixes it, but my guess is due to the `302` and us not handling the CORS properly.
Locally vs. staging.
I suggest that we cherry pick this onto the release branch after it goes in and re-enable mp3 stream when this is out.
Please verify my changes!
=> [C-1482] Fix visualizer on mp3 stream

packages/common/src/store/player/slice.ts, packages/web/src/common/store/player/sagas.ts
* Plays are being recorded for every play, but Listens are only being recorded for the first play in a session. The counter we are using to trigger the Listen is never being incremented. Not sure how this ever worked? Or is this how it's supposed to work?
https://user-images.githubusercontent.com/19916043/202252557-5b9908ef-995c-4bd9-9ea9-c179ea0ce277.mov
https://github.com/AudiusProject/audius-client/blob/main/packages/web/src/common/store/player/sagas.ts#L351
Fixed by incrementing the counter on playSuccessful. This also has the added benefit of triggering a scrubber reset on mobile when things are played, resolving the scrubber issues we've been seeing
Not sure what else this could break, did testing around all player actions on web and mobile but we will want to do a thorough pass if …
=> [C-1494] Listens not being recorded properly?

packages/web/src/services/audio-player/AudioPlayer.ts
The extra things happening in `_initContext` due to these changes https://github.com/AudiusProject/audius-client/pull/2259 have made it so simply doing `this.source!.disconnect()` doesn't properly pause the audio context. This resulted in the next track playing even when playback is paused.
The fix is to always do `this.audio.pause()`, even in a chrome-like browser. I tested to make sure the playback speed was correct after backgrounding/foregrounding the tab
*Are all new …
=> [C-1514] Prevent next track playing when playback is paused

packages/mobile/src/hooks/useNavigation.ts, packages/mobile/src/utils/navigation.ts
Pushing via `useNavigation` inside a nested navigator (such as a tab navigator inside a stack navigator) was deduping any subsequent pushes to that same screen because the `transitionEnd` handler was being attached on the inner navigator instead of the stack navigator
* Add `getNearestStackNavigator` utility
* Use utility to push and attach the `transitionEnd` handler to the nearest stack instead of the nearest navigator
Slight perf implications. I considered computing the nearest stack navigator outside of the `performCustomPush` function but that would mean every instance of useNavigation is doing that work. I think computing it inside `performCustomPush` is better and in most cases it will only need to traverse one level up the navigation hierarchy anyway
*Please describe the tests …
=> [C-1515] Allow repeat pushes via useNavigation inside nested navigator

packages/mobile/src/components/audio/Audio.tsx, packages/mobile/src/components/audio/GoogleCast.tsx
Chromecast was impressively broken, I'm not sure how it ever worked tbh
* Parts of the object being passed to `loadMedia` were undefined
* `track.uri` - this might be because of the streaming change? Fixed this by using the same logic as in `Audio` to create the streaming endpoint
* `track.largeArtwork` - straight up doesn't exist in the codebase, where did this go from? where did it go? something something cotton-eyed joe
* `track.artist` also didn't exist on the track object. Fixed this by following the pattern in `Audio` and using the `getUser` selector to get the owner
* Scrubber position was being updated by both the GoogleCast client and the Audio player, resulting in flickering time values
* Time also wasn't resetting when the next queued track started playing. Fixed this by …
=> [C-1399] Fix chromecast

packages/web/src/common/store/tipping/sagas.ts
* When no userTips exist (maybe due to network conditions, cloudflare rate limitting, WAF, whatever) hide the tip tile. Previously this just sat in an infinite skeleton state
=> [C-1527] Hide tip tile when no tips

packages/common/src/schemas/index.ts, packages/mobile/src/components/navigation-container/NavigationContainer.tsx, packages/mobile/src/screens/edit-track-screen/EditExistingTrackScreen.tsx, packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx, packages/mobile/src/screens/edit-track-screen/fields/RemixSettingsField.tsx, packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx, packages/mobile/src/screens/edit-track-screen/types.ts, packages/mobile/src/screens/upload-screen/screens/CompleteTrackScreen.tsx, packages/mobile/src/screens/upload-screen/screens/SelectTrackScreen.tsx, packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx, packages/mobile/src/screens/upload-screen/screens/UploadingTracksScreen.tsx
Adds upload analytics to mimic existing desktop analytics.
Adds page-views for upload flow, to get another way to collect metrics about user's flow through upload
=> [C-1535] Add mobile-upload analytics, fix remix field

packages/mobile/src/components/core/TextInput.tsx, packages/mobile/src/screens/search-screen/SearchBar.tsx
=> Fix android search input style

packages/mobile/src/screens/root-screen/RootScreen.tsx
My understanding of how/why this happened is because the nav stack used to be not rendered until account came back as SUCCESS or ERROR. Since we always render it to have a faster startup time, we need to be careful around whether the sign on stack shows.
I think this feels right -- I wasn't able to repro, but I also think the build version on the app store is different even than "Release mode" build from xcode.
https://user-images.githubusercontent.com/2731362/204440960-73fb98e0-dd77-4e35-a928-6c516ffa0100.MP4 …
=> Fix logged out offline startup

packages/mobile/src/hooks/useContentNodeImage.ts
See comment and related PR  https://github.com/AudiusProject/audius-client/pull/2318
=> Always fetch content node images from cache

.circleci/src/jobs/@web-jobs.yml, .circleci/src/workflows/web.yml, package-lock.json, packages/common/package.json, packages/web/package.json
- Persist root node modules to workspace so that npx lerna can work in subsequent steps.
- Use react-redux 7.2.5 everywhere (primarily for this change https://github.com/reduxjs/react-redux/releases/tag/v7.2.2)
It works on CI & went thru previous 7.2.0-7.2.5 changelogs in react-redux. Only meaningful changes (albeit somewhat substantial) are improvements to useSelector edge-cases/rerenders that can happen. Good thing to look out for in future QA/releases, but should be ok
https://app.circleci.com/pipelines/github/AudiusProject/audius-client/9448/workflows/1bbf358c-417f-4391-9a05-68e6b …
=> Fix mac build

packages/web/src/services/audius-backend/BuyAudio.ts, packages/web/src/store/application/ui/buy-audio/sagas.ts
=> hotfix-ff: Unify magic numbers

packages/common/src/services/remote-config/defaults.ts, packages/common/src/services/remote-config/types.ts, packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Add button in Audio page that navigates to audio transactions page.
Tested locally using early access audience.
AUDIO_TRANSACTIONS_ENABLED - boolean that enables/disables this button. Does not block `audio/transactions` route however.
=> [PAY-739] Add view transactions button in Audio page

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/utils/sagaHelpers.ts, packages/mobile/src/components/sign-out-confirmation-drawer/SignOutConfirmationDrawer.tsx, packages/mobile/src/components/web-app-account-sync/WebAppAccountClear.tsx, packages/mobile/src/components/web-app-account-sync/index.ts, packages/mobile/src/screens/root-screen/RootScreen.tsx, packages/mobile/src/screens/root-screen/StatusBar.tsx, packages/mobile/src/screens/signon/SignOn.tsx, packages/mobile/src/store/notifications/sagas.ts, packages/mobile/src/store/sagas.ts, packages/mobile/src/store/settings/sagas.ts, packages/mobile/src/store/sign-out/sagas.ts, packages/web/src/common/store/account/sagas.js, packages/web/src/common/store/cache/tracks/sagas.js, packages/web/src/common/store/change-password/sagas.ts, packages/web/src/common/store/notifications/sagas.ts, packages/web/src/common/store/pages/explore/sagas.ts, packages/web/src/common/store/pages/feed/sagas.ts, packages/web/src/common/store/pages/remixes-page/sagas.ts, packages/web/src/common/store/pages/search-page/sagas.js, packages/web/src/common/store/pages/settings/sagas.ts, packages/web/src/common/store/pages/signon/sagas.js, packages/web/src/common/store/pages/track/sagas.js, packages/web/src/common/store/profile/sagas.js, packages/web/src/common/store/search-bar/sagas.ts, packages/web/src/common/store/social/collections/sagas.ts, packages/web/src/common/store/social/tracks/sagas.ts, packages/web/src/pages/artist-dashboard-page/store/sagas.js, packages/web/src/store/notifications/sagas.ts, packages/web/src/store/sign-out/sagas.ts
Fix sign out / sign in behavior. I felt like a small sensible refactor was due here -- I made SignOnScreen and HomeScreen both rendered at the same time so we can control via navigation what screen you're on as a user -- I think this is better? But open to feedback.
Some other issues:
- sign out sagas connected twice :oops:
- wait for account wasn't taking into consideration IDLE state
- sign out wasn't doing a page navigation but implicily relying on account state to change, which makes it hard to track
- sign in sometimes clears state before animations finish so you can see some error messages at the tail end of signing in sometimes in dev mode
*Please describe the tests that you ran to …
=> [C-1595] Fix sign out

packages/web/src/components/table/Table.tsx
We need to use a different `isEmptyRow` fn in `AudioTransactionsTable`. Parametrize it and use the current one as a default.
Tested on local.
=> Make default Table isEmptyRow

packages/common/src/services/audius-api-client/AudiusAPIClient.ts, packages/mobile/src/App.tsx, packages/mobile/src/services/libs.ts
There is some preserved state between separate runs of the app (especially on android). Sometimes top level code like configuring the store or declaring the `audiusLibs` variable is not run. This causes an issue where consumers of libs think it is already initted but it is in a broken state
Working case:
Broken case:
Manually clearing libs in an effect in App fixes the problem because this effect is run before the store configuration or any sagas. It also runs every time the app is opened
Will make another PR to address similar issue with store
Could be dangerous if this effect were to run after the libs initialization. But that seems to be impossible
*For features that are …
=> [C-1649] Reset libs on app start

packages/common/src/store/cache/reducer.ts, packages/web/src/store/token-dashboard/sagas.ts
Fixes interesting edge-case where accountUser's associated_wallets were not updating correctly when deleting a wallet. This resulted in bad user experience where deleting an eth-wallet, then deleting a sol-wallet resulted in the eth-wallet being re-added to associated-wallets.
The crux of the issue had to do with two things:
1. Our deleteWallet success call did not tell redux to update accountUser's associatedWallets
2. Our update-cache merger did not respect deletions from associated-wallet object, meaning that the removed value would remain.
=> [C-1665] Fix deleteWallet bug

packages/mobile/src/components/card/Card.tsx, packages/mobile/src/components/collection-card/CollectionCard.tsx, packages/mobile/src/components/lineup-tile/LineupTile.tsx, packages/mobile/src/components/lineup-tile/LineupTileStats.tsx, packages/mobile/src/components/offline-downloads/DownloadStatusIndicator.tsx
* Update DownloadStatusIndicator to handle collections
*  Add download indicator to lineup tiles and collection cards
* Moved the call to fetch download track status to OfflineDownloader.tsx from the saved page so that download status could show up on the feed and trending screens, etc.
Didn't update the styles of the Card component bc that seemed like a large change across all cards that should be in its own PR
This relies on the collection being in state when the indicator tries to fetch the track for the collection and determine if it is in the process of being downloaded. Chatted with @amendelsohn and this is planned to be added as part of this project
N/A
N/A
=> [C-1663] Update DownloadStatusIndicator to handle collectionIds

packages/mobile/src/components/share-drawer/useShareToStory.tsx
Share drawers other than share track were erroring out due to:
` TypeError: undefined is not an object (evaluating 'trackImage.source[2].uri')
`
Turns out the `trackImage` not null check before didn't work because `useTrackImage` doesn't actually return null if its input is null...
=> Fix other share drawers

packages/common/src/models/Track.ts, packages/common/src/schemas/index.ts, packages/common/src/services/audius-api-client/ResponseAdapter.ts, packages/web/src/common/store/upload/sagas.js
Client change to add extra field in metadata for is playlist upload
NOTE: libs changes it depends on https://github.com/AudiusProject/audius-protocol/pull/4469/files
Fixes PLAT-526
=> Add is playlist upload to meta on upload

packages/common/package-lock.json, packages/common/package.json, packages/common/src/models/Collectible.ts, packages/common/src/models/Track.ts, packages/common/src/services/opensea-client/ethCollectibleHelpers.ts, packages/common/src/services/solana-client/SolanaClient.ts, packages/common/src/services/solana-client/solCollectibleHelpers.ts, packages/common/src/services/solana-client/types.ts, packages/web/src/common/store/premiumContent/sagas.ts
- Add logic to pass in track ids for solana-nft-gated tracks to get their premium content signatures.
- Add function `isCollectionNFT` to `SolanaClient` to check whether a mint address represents an NFT that denotes a collection. This will later be used by the premium content UI to ensure solana nfts which gate track access are valid.
- Update Collectible and sol nft collection types.
- Simplify logic to get sol nft chain metadata.
none
Tested by hardcoding solana collectibles from another profile and premium tracks gated on some solana nft collection and seeing that the client would build and make the correct request to DN to fetch the nft-gated track signatures.
n/a
existing `premium_content_enabled` feature flag
=> [PAY-747] Handle solana-nft-gated premium content

packages/web/src/common/store/remix-settings/sagas.ts
Sets premium track as invalid when trying to upload track as a remix of a premium track.
related to https://github.com/AudiusProject/audius-protocol/pull/4499
Also, when building premium content UI, we need to ensure that the "This is a remix switch" is non-existing when uploading a premium track, so premium track will not be a remix child.
part of track upload flow, but should be fine
Sets the track as invalid so user cannot proceed to use premium track as remix parent.
n/a
=> [PAY-757] Prevent use of premium tracks as remix parents

packages/web/src/components/table/Table.module.css
Small styling update. Should remove the space between the text and sorters so there is no gap in the clickable area
N/A
N/A
N/A
=> [PAY-772] Update table styles to remove the space between the header text and sorters

packages/common/src/services/audius-api-client/AudiusAPIClient.ts, packages/mobile/src/utils/reachability.ts, packages/web/src/common/store/notifications/sagas.ts
* Check reachability in AudiusApiClient so retries stop once we enter an unreachable state. This means there are still some requests that fail before we get into the unreachable state, but they stop fairly quickly. Would be ideal to have the unreachable state happen faster, but bc we do a ping check it takes a bit
* Check reachability in `getNotifications`. This function gets run on an interval, so we can prevent failed requests by returning early
The reachability handlers not being in sagas made this kind of interesting. I'm definitely still in favor of moving away from sagas but the border between saga <> non-saga can be annoying
I noticed that coming back online doesn't seem to be working. Once my wifi is reconnected and I press reload in the app, nothing happens. Not sure if you are …
=> [C-1692] Prevent infinite failed requests while offline

packages/web/src/common/store/cache/collections/sagas.js, packages/web/src/components/table/components/OverflowMenuButton.tsx
Fix bug with deleting last track of a playlist.
Fix bug with migrating to EntityManager only (no optimizely gating). EM only uses playlist obj doesn't need the other stuff.
https://github.com/AudiusProject/audius-client/commit/843d689fd7e9191a0d2ef481f1f75f9724fb6cf3
Tested locally successful track removals.
=> Fix playlist track removal

packages/common/src/models/Track.ts, packages/common/src/services/audius-api-client/types.ts, packages/mobile/src/components/offline-downloads/DownloadToggle.tsx, packages/mobile/src/hooks/useFetchAllFavoritedTrackIds.ts, packages/mobile/src/hooks/useFetchAllFavoritedTracks.ts, packages/mobile/src/hooks/useLoadOfflineTracks.ts, packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx, packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx, packages/mobile/src/screens/favorites-screen/TracksTab.tsx, packages/mobile/src/services/offline-downloader/offline-downloader.ts, packages/mobile/src/services/offline-downloader/offline-storage.ts, packages/mobile/src/services/offline-downloader/offline-sync.ts
Resolves two issues (mostly):
[C-1646]: Add favorite created_at data to the `offlineDownloads` slice and forces the lineups to sort by either favorite or playlist added timestamp accordingly
[C-1647]: Make sure lineups (collection page & favorites page) allow you to deal with switching back & forth between reachability states. This involved a few things:
* Fix a couple bugs around promises where things were not being awaited properly (missing data in the `offlineDownloads` slice)
* Restructure the `useOfflineCollectionLineup` hook to accept a bit more lineup functionality so that the component itself can forget about conditionally rendering certain things. I think this is ok, but maybe not ideal. Hard to get better without significant code restructuring, but the mental modal here is that …
=> [C-1646][C-1647] Handle more offline lineup states

packages/web/src/common/store/pages/audio-transactions/sagas.ts, packages/web/src/services/audius-sdk/audiusSdk.ts
Fixes the discovery node selection for SDK on stage to not use prod - worth considering though how to not have both libs and SDK do selection, possibly by reusing components or something.
Tested to make sure transactions history still works
=> Fix AudiusSDK to not select prod discovery nodes on state environment

packages/web/src/pages/upload-page/components/FinishPage.js
Clicking on title when upload completes throws an error. This change just makes it in line with the view media button.
Link only routes when upload is complete.
Tested locally against stage for track, playlist, album.
=> Fix finish page upload title link

packages/mobile/src/components/audio/Audio.tsx, packages/mobile/src/components/offline-downloads/DownloadToggle.tsx, packages/mobile/src/components/offline-downloads/OfflineDownloader.tsx, packages/mobile/src/services/offline-downloader/offline-download-queue.ts, packages/mobile/src/services/offline-downloader/offline-sync.ts, packages/mobile/src/services/offline-downloader/workers/playCounterWorker.ts, packages/mobile/src/services/offline-downloader/workers/trackDownloadWorker.ts
Adds offline play count recording using react-native-queue
Additional changes: 
- Divides out worker types into separate files
- Adds helper for reseting workers
- starts/stops the queue based on reachability status
=> [C-1083, C-1080] Add offline play count recording

packages/common/src/services/audius-api-client/AudiusAPIClient.ts, packages/common/src/services/audius-api-client/ResponseAdapter.ts, packages/common/src/services/local-storage/LocalStorage.ts, packages/common/src/utils/hashIds.ts, packages/web/src/common/store/premiumContent/sagas.ts, packages/web/src/common/store/search-bar/sagas.ts
Fixes issue where ApiClient consumers were not getting the correct input/return types, meaning things silently became type "any", yikes. When going to definition however, the types are correct, ie @audius/common is internally consistent, but its build is not. nice catch @piazzatron 
Issue ultimately due to absolute imports in @audius/common. This for whatever reason silently breaks the build with no warning, propagating "any" types to consumers.
- Fixed absolute imports
- Fixed emergent type bugs in @audius/web-client now that AudiusApi actually typed
=> Fix api-client types by fixing @audius/common absolute imports

packages/common/package-lock.json, packages/common/package.json, packages/common/patches/@noble+ed25519+1.7.1.patch, packages/common/patches/@noble+secp256k1+1.7.0.patch, packages/mobile/index.js
The addition of `@metaplex-foundation/mpl-token-metadata` in https://github.com/AudiusProject/audius-client/pull/2398 caused a crash on mobile when loading a profile with solana collectibles (It was not possible to repro locally on ios and only able to repro locally on android without the debugger attached)
This was the error being thrown: https://sentry.io/organizations/audius/issues/3832938092/?query=bigint&referrer=issue-stream&statsPeriod=14d
This PR:
* Polyfills BigInt with `big-integer` 
* Patches @noble packages for compatibility `big-integer`. `big-integer` does not support `0x` prefixes, instead uses a radix argument
Solana docs specify a min version of react-native of 0.70 which would fix this problem also. We should prioritize upgrading so that we don't need this hacky fix for …
=> [C-1738] Fix mobile crash

packages/mobile/src/components/audio/Audio.tsx
Update logic for the counter effect to only reset the playback position when the track index has not changed. This will reset it when we restart the track, but not when playing a new track.
There was some wonkiness with the effect being called too many times due to the function updating when the queue index updated so there is some hacky counterRef logic to help with that.
N/A
Manually tested on iOS
N/A
N/A
=> [QA-269] Update counter effect logic to only reset track position when the track index is the same

packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx, packages/mobile/src/screens/settings-screen/AboutScreen.tsx
Move the dev backdoor to a place where it doesn't conflict with the offline download toggle.
This unblocks Android where the download toggle's touch target was being occluded by the backdoor's onclick.
=> Move offline mode feature backdoor to about page

packages/web/src/common/store/premiumContent/sagas.ts
Fix the base58 error on solana nft collection key.
As written in the comment above the fix, the types returned are sometimes strings, other types PublicKey even though the library type says that it should be PublicKey.
`toBase58` function does not exist on strings, and this is what caused the bug.
See screenshot below for types returned by the library.
None
No longer fails with account that currently fails on staging.
N/A
None
=> Fix the base58 error on solana nft collection key

packages/common/src/store/pages/profile/reducer.ts, packages/web/src/common/store/cache/collections/sagas.js, packages/web/src/common/store/playlist-library/sagas.ts, packages/web/src/common/store/upload/sagas.js, packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
- New playlists start on top of playlist library in navbar
- Changed default sort order to recency in profile page
- Fixed issues with playlist creation:
Prior to this PR, creating a playlist would write out a playlist to your account's collections, which would get flushed to local storage. The playlist library wouldn't get updated until *next session* as part of the sign on sagas, which check for playlist library state differing from account collection state. This PR writes out the playlist library as part of the confirmation flow.
Playlist creation flow is a bit scary. But this seems to work
Web. Testing mobile
*For features that are critical or could fail silently please …
=> [PAY-808] [PAY-810] Float new playlists to top of library

packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj, packages/mobile/ios/Podfile.lock
Adds back the ARM64 exclusions to the pbxproj file to ensure we build for x86_64 simulator
=> Add back arm64 exclusion

packages/mobile/src/store/sagas.ts, packages/mobile/src/store/sign-out/sagas.ts, packages/web/src/common/store/backend/reducer.ts, packages/web/src/common/store/backend/sagas.ts, packages/web/src/common/store/backend/selectors.ts, packages/web/src/common/store/backend/types.ts, packages/web/src/common/store/lineup/sagas.js, packages/web/src/components/reachability-bar/components/ReachabilityBarContainer.tsx, packages/web/src/store/sagas.ts
Changes:
* Move setupBackend first call to action so that every call follows the same flow and sets isSettingUp = true. This informs us to not double-fire setupBackend in the ifNotAlreadySetup check
* Remove extraneous setupBackend call in ifNotAlreadySetup
* Fix corresponding sign out method to use isSettingUp state
ONLY tested on web:
- Lineup load
- Sign in/sign out
=> Fix setup states

packages/mobile/src/components/audio/Audio.tsx, packages/mobile/src/components/image/CollectionImage.tsx, packages/mobile/src/components/image/TrackImage.tsx, packages/mobile/src/hooks/useLocalImage.ts
* Re-enables useLocalImage. `Audio` is now using `getImageSourceOptimistic` so the initial problem with image hooks returning null is resolved
* Adds `getLocalImageSource`. This is used In `Audio` to get the local source
Wanted to get your thoughts on the performance of `useLocalImage` in general. We are now doing 3 filesystem reads for every image load before starting to fetch the image remotely. Maybe we do only want to enable local images when reachability is false? Also this is another good argument for making image sizing explicit, because we would only need a single filesystem read
Touches all images
Tested that images, lock screen images, work online/offline. Felt like the perf is maybe slightly worse …
=> [C-1726] useLocalImage

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/services/remote-config/feature-flags.ts, packages/web/src/components/nav/desktop/NavColumn.tsx, packages/web/src/components/nav/desktop/PlaylistLibrary.tsx, packages/web/src/components/nav/desktop/PlaylistNavItem.tsx
Adds two feature flags (also created in optimizely)
`ENTITY_MANAGER_VIEW_PLAYLIST_ENABLED`: For enabling client to send playlist view entity manager actions
`ENTITY_MANAGER_VIEW_NOTIFICATIONS_ENABLED`: For enabling client to send view notifications action to entity manager
Note: this also fixes a method for sending the action from the web navbar
e2e locally 
=> Entity manager notification writes

packages/mobile/src/components/core/Screen/SafeAreaScreen.tsx, packages/mobile/src/screens/signon/ProfileAuto.tsx
Fixes issue with "I'd rather fill out my profile manually" on android when the nav bar buttons are enabled. We probably shouldn't be using `SafeAreaView` from `react-native` anywhere, there was also slightly broken layout on the Suggested followers screen
=> [C-1821] Fix android manual sign up overflow

packages/common/src/store/notifications/types.ts, packages/mobile/src/notifications.ts
Updates onNotification function to only navigate when the user explicitly presses on a notification in the notification panel, ie `userInteraction = true`
Also handles case where notification data is sometimes (always?) `notification.data`, not `notification.data.data`
=> Fix notification userInteraction

packages/web/src/utils/route.ts
This adds an optional permalink argument to the PLAYLIST_PAGE route generation and branches off of whether a permalink is available or the playlist id and playlist name are available for legacy routing. 
I know we discussed passing in a playlist object, but that approach didn't work because not all calls to this had a playlist object to pass in. I tried another approach where it accepted an object of PlaylistPageArgs, but that required a lot of changes to all calls to this function and looked bulkier. This approach seemed the least invasive and easy to build off of but let me know what you think! 
Tested locally pointed to stage data. Loading playlists worked fine. Creating one didn't work but I think that's because stage is messed up right now?
=> update playlist_page route to accept permalink optionally

packages/common/src/schemas/index.ts, packages/common/src/services/audius-api-client/ResponseAdapter.ts
Track updates/edits currently do not send over the track cid as part of the metadata, therefore causing DNs to set the track_cid value to null for the updated track. This fixes it.
None
Local dapp vs prod. Updated track and cid remained intact.
N/A
None
=> [PAY-819] Fix track update cid bug

packages/common/src/utils/challenges.ts, packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx, packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
Completed rewards that are ready to claim float to the top of the rewards tiles. Rewards that are already disbursed sink to the bottom. Respects optimistic claiming. Both mobile and web.
Tested locally on web and ios sim. Also tested that aggregate rewards eg. invites function correctly.
=> [PAY-845] Sort rewards tiles by completed/disbursed

packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx, packages/web/src/utils/route.ts
Playlist tiles were trying to compute an href to a playlist that doesn't yet exist during the skeleton loading state, causing a crash in the `playlistPage` route util.
=> Fix broken loading state for playlist tiles

packages/mobile/src/components/track-list/TrackListItem.tsx
I spent some time trying to filter out deleted tracks from the download queue, but because we are only pulling the `favorites` endpoint we don't have the data to know if the track is deleted. Fetching that data would require extra calls for each batch of tracks in `fetchAllFavoritedTracks` etc and seemed like it would add quite a bit of complexity
This is the simple solution, the download fails silently in the background and the deleted track doesn't show up when offline
*Are …
=> [C-1876] Hide download indicator on deleted tracks

packages/common/src/services/audius-api-client/AudiusAPIClient.ts
Same `[]` vs `null` return bug from https://github.com/AudiusProject/audius-client/pull/2625/files#diff-2f1a5ad307b83e3d504719fb91b411a8619a6f7ecaf23a2cf3e17d79f3b811efR1409
This bug could occur elsewhere. Might be worth fixing all the lineup fetches? But impact of that is not known, so taking it one at a time for now.
=> [C-1875] Fix empty favorited tracks lineup on reconnect

packages/common/src/store/pages/track/actions.ts, packages/common/src/store/premium-content/slice.ts, packages/web/src/common/store/cache/sagas.js, packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts, packages/web/src/common/store/pages/track/sagas.js, packages/web/src/common/store/premiumContent/sagas.ts, packages/web/src/components/artist/ArtistCard.tsx, packages/web/src/components/artist/ArtistPopover.tsx, packages/web/src/components/track-availability-modal/CollectibleGatedAvailability.tsx, packages/web/src/components/track-availability-modal/TrackAvailabilityModal.module.css, packages/web/src/components/track/GiantTrackTile.js, packages/web/src/components/track/GiantTrackTile.module.css, packages/web/src/components/track/PremiumTrackSection.tsx, packages/web/src/components/track/desktop/Artwork.tsx, packages/web/src/components/track/desktop/BottomRow.tsx, packages/web/src/components/track/desktop/ConnectedTrackTile.tsx, packages/web/src/components/track/desktop/TrackTile.tsx, packages/web/src/components/track/types.ts, packages/web/src/pages/track-page/TrackPageProvider.tsx, packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Fix some bugs introduced in premium PRs and add more functionality:
- poll for premium track access on unlock
- handle follow/unfollow, unlock/lock of follow-gated  tracks
- update unlocking state as per design
- sort nft collections in track upload
- disable clicking/playing locked premium track
- fix playlist tile hover icon bug
- update copy
- some refactor (more to come)
Touches tracks, but should be okay. also gated behind feature flags.
Local dapp vs stage and vs prod
N/A
Existing premium content feature flags
=> [PAY-853] Premium content fixes on web

packages/common/src/utils/challenges.ts, packages/mobile/src/screens/audio-screen/AudioScreen.tsx, packages/mobile/src/screens/audio-screen/Panel.tsx, packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx, packages/web/src/pages/audio-rewards-page/components/ButtonWithArrow.tsx, packages/web/src/pages/audio-rewards-page/config.tsx
Followups from design after QA-ing the rewards UI improvements.
On local web + ios sim.
=> [PAY-862] Rewards UI Improvements Followups

packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx, packages/web/src/pages/audio-rewards-page/components/ButtonWithArrow.tsx
Fixes bug where rewards claim button was COMMON instead of PRIMARY_ALT for aggregate challenges.
Local web
=> Fix rewards claim button for aggregate challenges

packages/web/src/pages/audio-rewards-page/RewardsTile.module.css
Extends buttons in reward tiles to full width.
Local web
=> [PAY-871] Extend reward buttons to full tile width

packages/common/src/services/remote-config/defaults.ts, packages/common/src/services/remote-config/types.ts, packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Added 2-letter country code allow lists for coinbase and stripe in optimizely, and this commit updates the client to use those to verify that the user is allowed to buy audio using stripe or coinbase instead of the 3-letter country codes. This is to prepare for the switch to ipdata instead of ipapi.
Local web + vpn
=> Use 2-letter country codes in buy-audio location

packages/web/src/components/data-entry/InputV2.module.css, packages/web/src/components/data-entry/InputV2.tsx
Changes/differences from existing Input component:
- Typescript!
- Allows for including an icon, button, or anything really as a child inside the boundary of the input
- Uses CSS selectors rather than JS state for managing focus state etc
- Doesn't include the "shaded" variant since I didn't see any usages
- Less absolute positioning magic for elevated placeholders
- No need to manually limit length
- Uses and forwards existing props for an `input` element (but overrides `size`)
- Elevated placeholders look slightly different spacing-wise (will want a design review if in use anywhere, but thought this was sufficient for now...)
- Uses enums instead of strings for variants and sizes (makes it easier to track usages of each variant/size)
Various usages:
*Is there anything the reviewer …
=> Port Input component to Typescript

packages/stems/src/components/PopupMenu/PopupMenu.module.css
Removes the background circle and increases size of icons in `PopupMenu` components per [Figma](https://www.figma.com/file/hcVGqf35jfxueO7klqXlma/Components-%5BSTEM%5D?node-id=244%3A749&t=LWmQFOJq1JSlZkt8-1)
Note: Doesn't implement design fully, just the icons bit. (Still need a menu header, I think)
Will need Design check-off, and will need to verify that this looks good on all themes, _and_ will double check other PopupMenus, but it looked good for the one use case I was using it for!
*For features that are critical or could fail silently please describe the monitoring/alerting …
=> Update PopupMenu to not have circular icons

packages/mobile/src/services/offline-downloader/offline-download-queue.ts
The job queue checking for new jobs every 10ms adds overhead to the cpu usage anytime the queue is running (which is always when offline mode is enabled)
Bumping the interval to 500ms reduces this overhead considerably
=> Change react-native-job-queue updateInterval to 500 ms

packages/common/src/services/location.ts, packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Remove use of `country_code_iso3`. Fixes bug where disabled stripe buy-audio popup was not showing the specific blocked region, just a generic `stripe is disabled in your region` message.
Local web
=> Remove use of iso3 country code

packages/mobile/src/components/offline-downloads/DownloadProgress.tsx, packages/mobile/src/components/progress-bar/ProgressBar.tsx, packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
Add progress bar for downloads. Only shows when actively downloading, SUCCESS & ERROR count as "complete" as far as the progress bar cares, so the user doesn't see it forever if something has failed.
Locally on simulator vs. staging env
=> [C-1963] Add download progress bar

packages/mobile/src/screens/track-screen/TrackScreen.tsx, packages/web/src/common/store/pages/track/sagas.js
Hide more by this artist section on track page when offline.
This is a bit cumbersome to use the count artificially here to prevent loading skeletons, but the count itself is already a kind of hacky way that we make track pages work currently.
On simulator in unreachable state -- lineup doesn't show other than "hero" track
=> [C-1977] Hide more by this artist when offline

packages/mobile/src/services/offline-downloader/offline-downloader.ts
When toggling off favorites download, we don't clear all the tracks that could have been downloaded within collections.
This makes that possible, but it's still very slow. Needs something like https://linear.app/audius/issue/C-1974/batch-cancel-downloads-instead-of-1-by-1 to make that better.
Before change:
Downloaded all faves => turned off downloads => some tracks remain downloaded inside collections
After change:
Downloaded all faves => turned off downloads => empty
*Are …
=> [C-1938] Remove tracks within collections when toggling off favorites

packages/mobile/src/screens/favorites-screen/DownloadProgress.tsx, packages/mobile/src/services/offline-downloader/offline-downloader.ts
Update the placement of the purgecollection call for the favorites to mark it as false for downloaded collection so that the progress indicator goes away earlier when undownloading favorites
N/A
N/A
N/A
=> Update undownload favorites to hide progress earlier

packages/mobile/src/services/offline-downloader/offline-downloader.ts
Fixes case where race condition to re-create collection directory prevents collections from downloading when we trigger favorites download.
=> [C-2000] Fix collections not downloading on favorites download

packages/mobile/src/hooks/useLoadOfflineTracks.ts, packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx, packages/mobile/src/screens/favorites-screen/TracksTab.tsx, packages/web/src/common/store/pages/collection/lineups/sagas.js
Fixes playback when switching from offline<>online and vise-versa.
The crux of this PR is to steal (if available) the UIDs from the existing lineup before refreshing the lineup itself.
Don't love all of this code all-in-all, but I think this works fairly well!
@Kyle-Shanks and I also separated the big ole hook into two separate hooks that we should move into the components, but wanted this diff to be smaller. Can be a follow up. Left a TODO
Favorites lineup & collection lineup:
1. play track
2. dispatch REACHABILITY/SET_UNREACHABLE
3. playback works, prev & next work
4. dispatch …
=> [C-1950] Smooth offline<>online playback

packages/mobile/src/components/offline-downloads/DownloadStatusIndicatorBase.tsx
Show download success icon when offline in status indicators. This makes sense if we're certain we aren't showing non-offline stuff when visiting the app offline.
=> [C-1952] Show download successful when offline in status indicator

packages/mobile/src/screens/profile-screen/ProfileInfo.tsx, packages/mobile/src/services/offline-downloader/offline-downloader.ts
Two small changes:
* Hide follow/sub buttons on profiles when offline
* Remove 1s delay between jobs. Seems to have no noticeable perf impact now, I randomly took a few measurements while downloading with the 1s delay and without the 1s delay and it all basically looked like this. The 7x one is with the 1s delay removed
=> Hide buttons on profiles when offline and remove timeout

packages/mobile/src/services/offline-downloader/offline-download-queue.ts, packages/mobile/src/services/offline-downloader/offline-downloader.ts, packages/mobile/src/services/offline-downloader/workers/collectionDownloadWorker.ts, packages/mobile/src/services/offline-downloader/workers/trackDownloadWorker.ts
Removes queued downloads if the track/collection is deleted/unlisted. Currently deleted tracks in your favorites/collection cause a bottleneck as they wait to be retried 3 times only to find the same result.
Improves looping code in the existing cancelXDownloads methods
Local simulator vs. staging with a bunch of deleted tracks
=> [C-2001] Remove queued downloads if deleted/unlisted/etc

packages/common/src/models/Track.ts, packages/common/src/store/premium-content/selectors.ts, packages/common/src/store/premium-content/slice.ts, packages/common/src/store/tipping/slice.ts, packages/web/src/common/store/premiumContent/sagas.ts, packages/web/src/common/store/tipping/sagas.ts, packages/web/src/components/artist/ArtistCard.tsx, packages/web/src/components/artist/ArtistPopover.tsx, packages/web/src/components/track/GiantTrackTile.js, packages/web/src/components/track/PremiumTrackSection.tsx, packages/web/src/components/track/desktop/BottomRow.tsx, packages/web/src/components/track/desktop/ConnectedTrackTile.tsx, packages/web/src/components/track/desktop/TrackTile.module.css, packages/web/src/components/track/desktop/TrackTile.tsx, packages/web/src/components/track/types.ts, packages/web/src/pages/track-page/TrackPageProvider.tsx, packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Make sure follow / unfollow across app updates premium track access accordingly.
Same for tipping.
This is to show correct locked/unlocking/unlocked states for premium tracks across entire app as user may follow/unfollow or send tip from multiple places in app.
n/a
local dapp v stage
n/a
existing feature flags
=> [PAY-868] Handle follow and tip send states across

packages/common/src/store/queue/selectors.ts, packages/common/src/utils/uid.ts, packages/mobile/src/components/audio/Audio.tsx, packages/web/src/common/store/lineup/sagas.js
This was kinda tricky!
Architecturally, it's simple, refresh the queue stuff when the toggle is flipped to fix the bug -- this is because we use UIDs to check whether the queue should change. We need to keep the UIDs the same to allow playback to work when reachability state changes.
There was no exposure to the collection that is playing from the queue, so I had to add that, and then do some changes within Audio.tsx to respect toggles to the switch contextually based on what you're listening to.
Could be more elegant, but I think not terrible given the way this comes together. …
=> [C-1941] Refresh queue when download toggle is flipped

packages/mobile/src/components/offline-downloads/DownloadStatusIndicator.tsx, packages/mobile/src/screens/favorites-screen/DownloadFavoritesSwitch.tsx, packages/mobile/src/screens/favorites-screen/DownloadProgress.tsx, packages/mobile/src/services/offline-downloader/offline-downloader.ts, packages/mobile/src/store/offline-downloads/sagas.ts, packages/mobile/src/store/offline-downloads/slice.ts
Commits can be reviewed in isolation:
- [C-2026] Make it so we download all tracks from favorites + from collections within favorites in one fell swoop so download progress shows X/Y and Y is the complete number of tracks. Otherwise, you get Y in two parts
- [C-2028 & C-2027] Same fix: Add another state to consider downloads abandoned. Problem is that tracks that enter ERROR state get swept from the downloadTracks so your downloadprogress Y number goes down and the download spinner thinks you've never finished
- [C-2029] Quick little optimize to download art + track at same time. …
=> Improve download toggle, download progress and fetch

packages/mobile/src/screens/signon/SignOnScreen.tsx, packages/mobile/src/store/sagas.ts, packages/mobile/src/store/sign-up/sagas.ts, packages/mobile/src/store/sign-up/sagas/watchSignUpSucceededSaga.ts
The way we were firing sign up complete analytics in a useEffect in the SignOnScreen did not always trigger because the screen was removed as soon as an account existed (in RootScreen) 
This pr moves the analytics and notification reminder into a mobile specific saga that watches SIGN_UP_SUCCEEDED. We've followed this pattern for other mobile specific sagas but open to thoughts/comments. Also @dylanjeffers I followed the pattern you did for offline mode sagas
Edit: I think sign up needs an audit / some love in general
Specifically did not make any changes that affect web. This should be fairly safe …
=> [C-2079] Fix mobile sign up analytics

packages/common/src/models/User.ts, packages/common/src/services/audius-api-client/ResponseAdapter.ts, packages/common/src/services/audius-api-client/types.ts
Noticed I didn't encode artist pick track IDs in the user API response... added in discovery in https://github.com/AudiusProject/audius-protocol/pull/4725; these are the accompanying client changes. Will remove the conditional and 'number' type when all discovery nodes have updated.
Also noticed reading artist pick from discovery wasn't working when viewing other people's profiles. This was because we had added a line manually pruning the artist pick field when fetching and caching the user's metadata sometime between now and when I initially added the flag in. Does not affect viewing one's own profile because that info is fetched and cached in getAccount in AudiusBackend.ts.
Going to hotfix this change onto the 1.5.9 release so that we can turn on reads then delete the legacy identity …
=> Decode artist pick IDs and fix artist pick reads from discovery

packages/web/src/pages/visualizer/VisualizerProvider.tsx, packages/web/src/services/audio-player/AudioPlayer.ts
* Skip AudioContext set up on safari
* Fix visualizer check -- AudioContext is now defined in safari. We can probably make the visualizer work, but I tried for a little and couldn't figure it out for now.
Should be able to re-enable feature flag if we cherry this into this week's release.
* MacOS Safari
* MacOS Chrome
* MacOS Firefox
* MacOS Edge
* iOS Safari
* iOS Chrome
* Android Chrome
=> [C-1975] Fix safari stream mp3

packages/mobile/src/store/search/slice.ts
Fixes issue where our search query was being saved between sessions, which i don't think is necessarily bad, but our ui doesn't handle it properly, so excluding it from persist config for now.
=> [C-2039] Fix search query persist

packages/common/src/store/ui/transaction-details/types.ts, packages/web/src/common/store/pages/audio-transactions/sagas.ts, packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx, packages/web/src/components/transaction-details-modal/components/TransactionPurchaseMetadata.tsx
In some rare cases, the tx metadata doesn't exist on identity (usually due to bugs). This fixes client so that it doesn't crash when this occurs.
Fallout from this fix: the modal will start at 580px then suddenly shrink when this case occurs. I think this is ok to ignore though as this is a rare case.
Local web client.
=> Fix audio tx modal where metadata is null

packages/mobile/src/components/scrubber/Slider.tsx
Fixes issue where pressing the slider rail throws error, this is due to us changing the animation type for `useNativeDriver: false`
=> Fix onPressRail animation error

packages/mobile/src/store/offline-downloads/sagas/watchSaveTrackSaga.ts
We were downloading tracks on save even if the favorites download toggle was not on.
=> Don't download on save if all favorites toggle off

packages/mobile/src/components/audio/Audio.tsx, packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/playCounterWorker.ts, packages/mobile/src/store/offline-downloads/sagas/downloadQueueSagas/requestDownloadQueuedItemSaga.ts, packages/mobile/src/store/offline-downloads/slice.ts
Add play-count type to offline queue.
This was removed in the queue refactor.
1. Do we need error handling? Is best-effort good enough?
2. Is the same queue state logic sufficient for this? Process while online, stop while offline.
=> [C-2067] Add 'play-count' queue

packages/mobile/src/screens/collection-screen/useCollectionLineup.ts, packages/mobile/src/screens/favorites-screen/useFavoritesLineup.ts
In lineup sagas, we match tracks in the playback queue and reuse the ids for the new lineup. This keeps playback consistent when re-fetching a lineup. We need the same logic for collection lineups which switch states between online and offline lineups.
The UIDs look good in the store, but lineup loading issues are preventing me from testing fully.
=> [C-2125] match uids from queue to preserve smooth playback

packages/web/src/common/store/profile/sagas.js
Realized that we can probably remove the call to local-storage here, since it gets picked up whenever there is a cache/add/update to a user, it will merge that data with existing stuff, preserving the full account data.
=> [C-2126] Fix empty collections on first session

packages/mobile/src/components/drawer/Drawer.tsx
Fixes issue where now-playing disappears when tapping. Reverts change that was made to attempt to improve the confirmation flashes, but actually didn't fix it anyway
=> [C-2139] Fix now playing

packages/mobile/src/components/core/Screen/Screen.tsx, packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Took me a while to find out that I could pass a component into the Screen via `headerTitle` prop instead of `title`.
Android emulator
=> [PAY-893] UserBadge in chat screen header

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/web/src/components/search-users-modal/SearchUsersModal.tsx
Noticed that fetching mutuals was failing because we weren't waiting for libs init, and then also not refreshing the selector on the modal becoming visible.
=> [DMs][PAY-832] Fix compose modal mutuals default

packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/watchReachability.ts
Fixes issue where coming back online may trigger another queue download, leading to multiple running job processes.
=> Fix saga reachability

packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
Fixes small bug where invites reward wouldn't show "Ready to Claim" pill because it was relying on `hasCompleted` instead of `needsDisbursement`.
Local web.
=> Show Ready to Claim Pill on needsDisbursement

packages/web/craco.config.ts, packages/web/src/common/store/pages/explore/exploreCollections/sagas.ts
& fix some types
```
npm run web:prod
```
=> [C-2167] Deduplicate explore playlists

packages/mobile/src/app/Drawers.tsx
Fixes issue where drawer data is removed when visibility is false, which broke because we still kept drawer around for 100ms longer. realizing none of this is needed now, it appears the background fixes for the drawer were enough here, and this was overkill.
=> [C-2198] Fix runtime error due to missing drawer data

packages/common/src/store/pages/collection/lineup/reducer.ts, packages/common/src/store/pages/collection/reducer.ts, packages/common/src/store/pages/feed/lineup/reducer.ts, packages/common/src/store/pages/feed/reducer.ts, packages/common/src/store/pages/history-page/lineups/tracks/reducer.ts, packages/common/src/store/pages/history-page/reducer.ts, packages/common/src/store/pages/profile/reducer.ts, packages/common/src/store/pages/remixes/slice.ts, packages/common/src/store/pages/saved-page/lineups/tracks/reducer.ts, packages/common/src/store/pages/saved-page/reducer.ts, packages/common/src/store/pages/search-results/lineup/tracks/reducer.ts, packages/common/src/store/pages/search-results/reducer.ts, packages/common/src/store/pages/track/lineup/reducer.ts, packages/common/src/store/pages/track/reducer.ts, packages/common/src/store/pages/trending-playlists/slice.ts, packages/common/src/store/pages/trending-underground/lineup/reducer.ts, packages/common/src/store/pages/trending-underground/slice.ts, packages/common/src/store/pages/trending/lineup/reducer.ts, packages/common/src/store/pages/trending/reducer.ts, packages/web/src/pages/deleted-page/store/slice.ts
Rough bug. Turns out the way we initialize lineup reducers is bad.
Cannot read order of undefined comes from the fact that an action gets dispatched against feed when you repost *any* track https://github.com/AudiusProject/audius-client/blob/61d832b5e78ecfffd5f26c9bdcd96758ac5b61b1/packages/web/src/common/store/pages/profile/lineups/feed/sagas.js#L119 and that hits an `undefined` value for the feed lineup slice.
This removes the lazy init and normalizes a few things.
This is a deep cut. Major lineup change (but should be for the better)
Locally vs staging. Bug no longer reproable …
=> [C-2130] Fix race cond in lineup init

packages/mobile/src/components/share-drawer/ShareDrawer.tsx, packages/mobile/src/components/share-drawer/ShareToStorySticker.tsx, packages/mobile/src/components/share-drawer/useShareToStory.tsx
For some reason, about half the tracks fail to "Share to X" on the first time because the "sticker" image (which is loaded and captured off screen) fails to load in time.
Not sure why or how this regression occurred. But the changes in this PR fix this ~90-95% of the time.
-Use TrackImage component directly in the sticker, which uses FastImage under the hood
-Load the sticker as soon as you open the drawer (instead of when you click "Share to X") …
=> Fix image loading issues w Share to X

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/services/remote-config/feature-flags.ts, packages/common/src/store/notifications/selectors.ts, packages/common/src/store/notifications/types.ts, packages/web/src/common/store/notifications/sagas.ts, packages/web/src/components/notification/NotificationPanel.tsx
Client Reads for notifications from discovery
Behind a feature flag, but changes how notifications are read.
Ran against a local discovery box pointed at a prod discovery database and validated that each of the notification types were rendered
notifications panel on web 
Yes, new discovery notifications read feature flag
=> Add client notifications from discovery

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/store/social/collections/actions.ts, packages/common/src/store/social/tracks/actions.ts, packages/web/src/common/store/social/collections/sagas.ts, packages/web/src/common/store/social/tracks/sagas.ts, packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx, packages/web/src/components/track/desktop/ConnectedTrackTile.tsx, packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx, packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
two things:
1. rename is_repost_repost metadata to is_repost_of_repost in the client
2. move repost metadata logic from the web/mobile playlist/track tile components into track and playlist social sagas. this DRYs up the code to generate the logic
Tested locally pointing client against stage. Reposting from feed vs trending and confirming the metadata sent to audius backend is expected.
=> Rename is_repost_of_repost and move repost metadata logic

packages/web/src/store/token-dashboard/connectNewWalletSaga.ts
Previously, if you try to connect with Phantom and then close the phantom popup, the app would crash! 
This fixes it by catching the errors and resetting the modal state. 
=> [PAY-956] Catch wallet connect errors and reset modal state

packages/web/src/pages/audio-rewards-page/components/ConnectWalletsBody.module.css, packages/web/src/pages/audio-rewards-page/components/ConnectWalletsBody.tsx, packages/web/src/pages/audio-rewards-page/components/WalletsTable.module.css, packages/web/src/pages/audio-rewards-page/components/WalletsTable.tsx
We would only show the error if you'd previously connected a wallet, on the `WalletsTable`
Only shown here previously:
Now also showing here:
[] Need to make sure this works on mobile
[] Doublechecking that this text goes away when a wallet *is* successfully connected
=> [PAY-972] Handle duplicate wallet connections properly

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/store/social/collections/actions.ts, packages/common/src/store/social/tracks/actions.ts, packages/web/src/common/store/social/collections/sagas.ts, packages/web/src/common/store/social/tracks/sagas.ts, packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx, packages/web/src/components/track/desktop/ConnectedTrackTile.tsx, packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx, packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
This sends save of repost metadata to get processed by entity manager any time a track or collection gets reposted. Pretty much mimics what we've done for repost of a repost
Ran client locally against staging and printed metadata in audius backend endpoints to confirm the correct metadata is passed.
=> Send save_of_repost metadata on item save

packages/common/src/store/notifications/types.ts, packages/mobile/src/hooks/useNotificationNavigation.ts, packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx, packages/mobile/src/screens/notifications-screen/Notifications/RepostOfRepostNotification.tsx, packages/web/src/components/notification/Notification/Notification.tsx, packages/web/src/components/notification/Notification/RepostOfRepostNotification.tsx
adds repost-of-repost notification ui for web/mobile
There is still a bit to figure out regarding `onClick` for the notif tiles. I think it's possible for us to render a user-list like we do with reposts etc... it would probably be more consistent. But for now, we simply just go to the content.
=> [PLAT-702] Add repost-of-repost notification

packages/mobile/src/utils/routes.tsx
Fixes track permalink share route once again, not realizing encodeUriName strips out the / needed for artist/track. This general uri encoding issues still exists, but reverting for the mobile release.
=> Fix track permalink share route

packages/web/src/common/store/lineup/sagas.js
Fixes a bug where `getFeatureEnabled` was imported instead of grabbed from the saga context.
=> Fix getFeatureEnabled bug: get from context

packages/common/src/services/remote-config/defaults.ts, packages/common/src/services/remote-config/types.ts, packages/common/src/services/solana-client/SolanaClient.ts, packages/common/src/store/premium-content/sagas.ts, packages/mobile/src/components/lineup-tile/TrackTile.tsx, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx, packages/web/src/components/track/GiantTrackTile.js, packages/web/src/components/track/desktop/ConnectedTrackTile.tsx, packages/web/src/components/track/mobile/ConnectedTrackTile.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
- Show repost/favorite button on unlocked mobile gated track screen
- Hide add to playlist overflow buttons for web, mobile web, and native mobile
- Show better warning message when failing to get nft metadata
- Remove forgotten comment
- Use remote config for gated track polling frequency
none
local dapp vs stage. tested on web, mobile web, and ios
existing
=> Fix button visibilities and other small misc gated related items

packages/web/src/components/track/TrackBannerIcon.module.css
Fix spacing issue for mobile web special access track screens.
Local mobile web against stage. Confirmed normal (non-special access) track tiles look the same, as well as non-mobile wb.
What it looked like before:
=> Fix mobile web track screen special access spacing

packages/mobile/src/components/audio/Audio.tsx
Removing the queue removal check bc it was firing too often and causing issues with end of queue playback when selecting songs in the same lineup.
N/A
N/A
N/A
=> Remove queue removal check to fix end of queue playback

packages/web/src/common/store/pages/token-dashboard/removeWalletSaga.ts, packages/web/src/store/token-dashboard/connectNewWalletSaga.ts
Refresh collectibles state when the user adds or removes a wallet, so that they can gate on the newly added wallet's collectibles or access tracks gated by the newly added wallet's collectibles, as well as so they can't gate on collectibles no longer linked.
=> [PAY-1020] Refresh collectibles when adding/removing wallets

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/store/upload/actions.ts, packages/web/src/common/store/cache/users/sagas.d.ts, packages/web/src/common/store/cache/users/sagas.js, packages/web/src/common/store/pages/token-dashboard/associateNewWallet.ts, packages/web/src/common/store/upload/errorSagas.ts
`upgradeToCreator()` has not existed in libs for a long time, so this PR removes the wallet connection logic that tries to call `upgradeToCreator()`
Most users should already have `metadata_multihash` and `creator_node_endpoint` (including new users - I tested that), and Entity Manager is handling them now (tagged Isaac for visibility), so this path was likely almost never called. [Sentry logs](https://audius.sentry.io/issues/3966211875/?project=1457231&query=is%3Aunresolved+upgradeToCreator&referrer=issue-stream&statsPeriod=14d) show one error in the past 14 days for this function (and the error was because the function doesn't exist in libs anyway so there's no point in trying to call it in client)
Created a new user, verified it has `metadata_multihash` and `creator_node_endpoint` at …
=> Remove upgradeToCreator

packages/common/src/store/ui/modals/slice.ts, packages/common/src/store/ui/modals/types.ts, packages/mobile/src/app/Drawers.tsx, packages/mobile/src/components/profile-actions-drawer/ProfileActionsDrawer.tsx, packages/mobile/src/screens/profile-screen/ProfileInfo.tsx, packages/mobile/src/screens/profile-screen/ProfileScreen.tsx, packages/mobile/src/store/drawers/slice.ts
Re-add message button and change profile top right icon to include path to block messages drawer. But feature flagged this time.
And also using ActionDrawer for ProfileActionsDrawer. Still need to convert ChatActionsDrawer as well.
Local ios against both staging and prod.
Staging:
Prod:
=> Re-add chat features to profile screen

packages/common/src/services/audius-api-client/AudiusAPIClient.ts, packages/web/src/common/store/smart-collection/sagas.ts
This updates the heavy rotation playlist to hit a discovery endpoint for getting user track listen histories. Previously it was hitting an identity endpoint which was outdated when we migrated listening info from identity to discovery, so the rotation playlist page was either blank entirely for new users or contained really old listening data.
This gets a playlist of the top 20 listened to tracks, but can easily change the value to whatever seems best
Note: we've recently updated the GetUserTrackHistory endpoint on the discovery side to start collecting play counts of tracks for a user from now moving forward, and we did not backfill for previous play counts of tracks. So the playlist may reflect most recently played songs for a bit until we've been indexing play counts in listening …
=> Fix heavy rotation playlist on client

packages/web/src/common/store/notifications/checkForNewNotificationsSaga.ts
When user signs out on mobile, there is a period where libs is reset, yet our "hasLibsInitted" watcher doesn't reset, causing any fetch that requires libs while it's reinitting to break with a root level saga error. Since notification polling wasn't checking if signed-in before fetching, this triggered this case :(
=> [C-2369] Fix issue where notification poll can break app on signout

packages/common/src/hooks/usePremiumContent.ts, packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx, packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx, packages/mobile/src/components/track-list/TrackListItem.tsx, packages/web/src/components/edit-playlist/mobile/EditPlaylistPage.tsx, packages/web/src/components/table/components/OverflowMenuButton.tsx, packages/web/src/components/track-availability-modal/SpecialAccessAvailability.tsx, packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx, packages/web/src/components/track/mobile/TrackList.tsx, packages/web/src/components/track/mobile/TrackListItem.module.css, packages/web/src/components/track/mobile/TrackListItem.tsx, packages/web/src/components/tracks-table/TracksTable.module.css, packages/web/src/components/tracks-table/TracksTable.tsx, packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx, packages/web/src/pages/history-page/components/mobile/HistoryPage.tsx, packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
Update UI for inaccessible gated tracks from favorites page for both web and mobile.
local web and mobile apps vs stage
=> [PAY-1063][PAY-1085][PAY-1086] Update UI for inaccessible gated tracks from favorites and history pages

packages/web/src/components/data-entry/FormTile.js, packages/web/src/pages/upload-page/components/EditPage.js
Only allow prompt modal when single track is being uploaded.
Also automatically expand the advanced form section if user clicks on Got It.
=> [PAY-1083] - Only allow prompt modal when single track is being uploaded

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/services/remote-config/feature-flags.ts, packages/web/src/common/store/notifications/fetchNotifications.ts
- Adds trending-playlist and trending-underground notification types to discovery-notifications "valid_types" parameter
- Refactors `fetchNotification` function to more accurately switch between new and old notification format.
=> [PLAT-695] Add trending notifications to valid_types

packages/common/src/store/pages/chat/sagas.ts, packages/common/src/store/pages/chat/slice.ts, packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
Use createEntityAdapter api to update a message's reactions.
Also include a import re-ordering (lint) + an extra null check for reactions on mobile.
Local ios + stage
=> Fix chat reactions with createEntityAdapter

packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Centers the text in the textinput. This was a bit tricky because using `multiline` in the textinput disallows centering. This feels a bit janky but unfortunately it's the only way I got it to work!
@sliptype including you because you helped me find the first fix, which was to use `lineHeight`, but we actually need to use lineHeight for its intended purpose (line spacing) unfortunately.
on iOS the cursor is larger than the text.. punting for now.
Local ios/android on stage
=> [PAY-1107][PAY-1112] Center mobile chat text input, enlarge icon

packages/common/src/hooks/usePremiumContent.ts, packages/common/src/store/premium-content/sagas.ts, packages/common/src/store/premium-content/selectors.ts, packages/common/src/store/premium-content/slice.ts
There is an edge case where an artist can be followed or tipped before their tracks are loaded, and if their tracks happen to be loaded in the small window between the follow/tip and its confirmation, the UI will show a locked state instead of an unlocking/unlocked state for those tracks.
To handle this scenario, this PR stores followee and tipped user ids so that those the UI knows to be in an unlocking state as those users' special access tracks load.
local web app vs stage
=> [PAY-1090] - Subscribe to special access gates to unlock new tracks

packages/mobile/src/screens/chat-screen/ChatScreen.tsx, packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
Separates TextInput in ChatScreen to its own component to avoid re-rendering the entire screen every time the user enters a char.
=> Separate chat text input to own component

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/web/src/components/nav/desktop/NavColumn.tsx
Fixes the isViewed attribute on a notification to be whether a notification has a `seen_at` value. If a notification has seen_at timestamp, isViewed is true because it's been viewed.
Also marks notifications as viewed once we close the notifs menu as opposed to once we open the notif menu, to allow users to see the tag when they first open a new notif
=> [PLAT-834]: Fix notifications last seen new tag

packages/mobile/src/screens/chat-screen/ChatScreen.tsx
- Scroll to earliest unread message only on first page load. (Was scrolling randomly while on chat screen).
- Maintain scroll position even when new messages come in, if you've scrolled past a certain threshold away from the bottom (currently set to 1/4 of the screen height).
- Some code cleanup.
Noticed something is wrong with scrolling on android but don't think it's related to these changes.
=> Mobile chats scrolling improvements

packages/mobile/src/screens/app-screen/AppTabScreen.tsx, packages/mobile/src/screens/chat-screen/ChatListItem.tsx, packages/mobile/src/store/chat/sagas.ts
Use `navigation.push` instead of `navigate` to navigate to chat screens. Also pass in a `getId` function so that the chats are unique. Otherwise, if a user
- navs to a chat
- clicks on the username header to nav to the profile
- then navs somewhere else and lands on a different user
- then hits the chat entry from that new user's profile page
the navigator will go back (left) instead of forwards.
Had to ts-ignore the type warning in `getId`. I think it's a known issue that typing is pretty wonky with react navigation, have run into this before and confirmed with client team. cc @sliptype in case i'm wrong.
*Are all new features properly feature flagged? Describe …
=> Mobile chats use push instead of navigate

packages/mobile/src/screens/notifications-screen/Notifications/FavoriteNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/FavoriteOfRepostNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/RepostNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/RepostOfRepostNotification.tsx, packages/web/src/components/notification/Notification/FavoriteNotification.tsx, packages/web/src/components/notification/Notification/FavoriteOfRepostNotification.tsx, packages/web/src/components/notification/Notification/RepostNotification.tsx, packages/web/src/components/notification/Notification/RepostOfRepostNotification.tsx
This updates the copy for repost and save notifications. It was printing `X reposted your playlist my_album` for albums which is wrong. this is because in the backend reposts are saved as either playlist or track so factoring in is_album when we generate the copy
Tested locally by re enacting a repost notif for an album 
=> [PLAT-819]: Fix copy for repost and save of albums notifications

packages/common/src/store/pages/chat/sagas.ts, packages/common/src/store/pages/chat/selectors.ts, packages/common/src/store/pages/chat/slice.ts, packages/web/src/common/store/account/sagas.js, packages/web/src/common/store/profile/sagas.js, packages/web/src/components/artist/ArtistChip.tsx, packages/web/src/components/inbox-settings-modal/InboxSettingsModal.tsx, packages/web/src/components/stat-banner/StatBanner.tsx, packages/web/src/pages/chat-page/components/CreateChatModal.tsx, packages/web/src/pages/chat-page/components/CreateChatUserResult.module.css, packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx, packages/web/src/pages/profile-page/ProfilePageProvider.tsx, packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
- Gray out profiles you can't message on the search user modal
- Hides message icon from people you can message on their profile (TEMPORARY until we get CTA)
- Binds chat inbox settings to existing data
=> [PAY-829][PAY-1044] Desktop: Chats search users modal permissions/blocks and profile page permissions/blocks

packages/mobile/src/screens/chat-screen/ChatListScreen.tsx, packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
RN touchables were sometimes not registering presses, using react-native-gesture-handler ones seem to perform better. Might not be the final solution but want to merge to test on real devices on android and ios.
Local ios simulator.
=> Use RNGH touchables for mobile chats

packages/web/scripts/workers-site/index.js, packages/web/src/app.tsx, packages/web/src/components/app-redirect-popover/components/AppRedirectPopover.tsx, packages/web/src/pages/App.d.ts, packages/web/src/pages/App.js, packages/web/src/pages/App.test.tsx, packages/web/src/root.tsx
* Fix /204 loop from localhost on CORS error
* Remove isready logic -- this was only used for the app banner (used to be used for more). No need to have it b/c we want this banner to show all the time, except the landing page (which i've confirmed it does not).
* Deep link to /trending => shows banner
* Deep link to /signup => shows banner
* Landing page => no banner
* Landing page (no banner) => sign up (shows banner)
* Landing page (no banner) => trending (shows banner)
*Are …
=> [C-2418] Fix mobile web open in app banner

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/store/notifications/types.ts
Was testing uploads and the create album notification for subscribed users was rending a weird copy. Fixed the id parsing in audius backend discovery notifications
before:
after:
tested locally against stage
=> [PLAT-847]: Fix user subscription create album notification copy

packages/mobile/package-lock.json, packages/mobile/package.json, packages/mobile/src/components/core/Hyperlink.tsx, packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx, packages/mobile/src/screens/chat-screen/LinkPreview.tsx, packages/mobile/src/screens/chat-screen/constants.ts
Link unfurling on mobile chats.
Known issues:
- Flicker on long press for reactions popup bc we are fetching the unfurl metadata again.. def could do something smart here but punting for now.
cc @sliptype bc I'm making `source` prop in `Hyperlink` optional, hope this is ok.
Local ios stage.
=> [PAY-918] Mobile chat link unfurling

packages/common/src/store/pages/chat/selectors.ts, packages/common/src/store/pages/chat/slice.ts, packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx, packages/mobile/src/screens/chat-screen/ChatScreen.tsx
There was one more dependency on index in `ChatMessageListItem` that was used to determine whether to show/hide the reactions. This was because without this, we would render 2 reactions on top of each other which looked jank. Moved all the logic to a selector so we can still memoize `ChatMessageListItem`.
Local ios
=> [PAY-1152] Chats selector to check if is equal to popupMessageId

packages/web/src/components/nav/desktop/NavColumn.tsx, packages/web/src/components/notification/NotificationPanel.tsx
Fixes issue where dismissing notif panel does not mark notifs as read.
Slightly updates how we mark as read by moving the dispatch from the button to the panel itself
=> [C-2444] Fix notification panel notification count

packages/web/src/components/unload-dialog/UnloadDialog.js
Fixes safari beforeunload events not being captured properly.
Note: cmd+r hotkey remapping still doesn't work, we get the generic safari alert instead of our nice "hang tight" one. But with this fix at least we prevent a user losing their changes unknowingly.
Local web on safari, brave, chrome. Confirmed behavior on brave/chrome stayed the same.
=> Fix safari refresh event not being captured

packages/common/src/services/audius-backend/AudiusBackend.ts
The notification was fetching the wrong username to display, so it was saying the receiver became their own top supporter
testing locally against stage
=> Fix the entity id in supporter rank up notification

packages/common/src/services/audius-backend/AudiusBackend.ts
Gates storage v2 replica-set-free signups on the existing `storage_v2` feature flag OR a user whose email starts with `storage_v2_test_` (kinda hacky but makes dev and demo easier since you can't press "f" and enable a feature flag before signing up).
As long as no poor soul has an email staring with "storage_v2_test_" we should be good.
Tested whole signup and subsequent upload flow with and without the prefixed email.
Signups should continue working as usual.
Existing `storage_v2` flag
=> Gate v2 signups

packages/common/src/store/wallet/selectors.ts, packages/common/src/store/wallet/slice.ts, packages/web/src/components/nav/desktop/NavAudio.module.css, packages/web/src/components/nav/desktop/NavAudio.tsx
This updates the logic in `NavAudio` to wait on values used for conditional rendering to finish loading. The logic here uses information from 3 different calls. So depending on order, you could see the pill in multiple states in rapid succesion.
Also did some cleanup of the logic and styling:
* Updated balance calculations to prefer wallet balance if loaded, falling back to account balance and then a constant of `0`.
* Updated logic for displaying bubble to wait on loading of challenges and wallet for the two cases where we show "claim" and "earn" variants
* Removed the `useState` and `useEffect` pair for updating the bubble type. This should be unnecessary, since the hooks we use to select data will cause a re-render when the results change.
* Make the token counter and earn/claim pills …
=> [PAY-1128] Update logic for showing "earn/claim $AUDIO" pill

packages/web/src/components/notification/NotificationPanel.tsx
Fixes bug where notifications are set to viewed on first load, not when the panel is actually open
=> Only mark notifications as viewed when notif panel is open

packages/common/src/models/Status.ts, packages/common/src/store/pages/audio-transactions/selectors.ts, packages/common/src/store/pages/audio-transactions/slice.ts, packages/web/src/common/store/pages/audio-transactions/sagas.ts, packages/web/src/components/audio-transactions-table/AudioTransactionsTable.tsx, packages/web/src/pages/audio-transactions-page/AudioTransactionsPage.tsx
The `isLoading` logic for the AudioTransactionsTable was previous relying on an `every` check against the loaded data, instead of tracking success of the fetch. Due to the way `Array.prototype.every()` works, an empty array will always cause the loading condition to be true.
To fix this, I added loading state tracking to the slice for both transactions and count, and then wait on them explicitly to determine table loading state.
Additionally, I moved the reset logic mostly into the slice to simplify the component. The slice will now reset the items array when a fetch begins and the offset is zero (fetching the first page). This means the component doesn't have to manually clear items when paginating, and gets us closer to a pagination functionality that is separate from the display logic. …
=> [PAY-937] Fix empty state for transactions table

packages/common/src/services/discovery-node-selector/DiscoveryNodeSelectorInstance.ts, packages/common/src/services/local-storage/LocalStorage.ts, packages/mobile/src/services/discovery-node-selector.ts, packages/web/src/services/discovery-node-selector.ts
Client-side changes to pass down the DN override to SDK.
Related to: https://github.com/AudiusProject/audius-protocol/pull/5124
Tested on local web + linked libs. Confirmed setting/unsetting DN override works by inspecting comms requests.
=> [PAY-1166] Make SDK respect DN override (client-side)

packages/common/src/services/discovery-node-selector/DiscoveryNodeSelectorInstance.ts, packages/mobile/src/services/discovery-node-selector.ts, packages/web/src/services/discovery-node-selector.ts
Related to https://github.com/AudiusProject/audius-protocol/pull/5146.
There was already a way to specify an `initialSelectedNode` in the sdk so using that instead of the `overrideEndpoint` field I added.
Local web stage with linked libs.
=> SDK respects DN override using initialSelectedNode

packages/mobile/src/components/block-messages/BlockMessages.tsx, packages/mobile/src/components/profile-actions-drawer/ProfileActionsDrawer.tsx
Wire up block/unblock actions to the block messages drawer.
It seems like `getProfileUserId` could potentially return `undefined`, but I don't understand how that could be possible if we've successfully navigated to a user's profile screen, so I assume it exists in the `BlockMessages` drawer.
Local web vs stage.
=> Mobile chats block/unblock users

packages/common/src/store/notifications/notificationsSelectors.ts, packages/mobile/src/screens/notifications-screen/Notification/EntityLink.tsx, packages/mobile/src/screens/notifications-screen/Notifications/RemixCreateNotification.tsx, packages/web/src/components/notification/Notification/RemixCreateNotification.tsx
Fixes issue where remix notifications relied on legacy selectors for old notification data shape. Now it's simply selecting tracks based on parent/child id, rather that picking tracks out of a list.
=> [PLAT-903] Fix missing remix notifications

packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx, packages/web/src/components/notification/NotificationPanel.tsx
Fixes issue where new notifications were not tagged with `new` in ui. This was due to notification-panel and notification-screen dispatching `markAllAsViewed` on initial render, which removed `new` ui. Now we wait until the component unmounts to dispatch action.
=> [PLAT-908] Fix new notifications not tagged in ui

packages/common/src/schemas/index.ts, packages/common/src/services/audio-player.ts, packages/common/src/services/audius-backend/AudiusBackend.ts, packages/web/src/common/store/player/sagas.ts, packages/web/src/services/audio-player/AudioPlayer.test.js, packages/web/src/services/audio-player/AudioPlayer.ts
- Displays and passes around `duration` from track metadata when it's truthy in all places that used `track_segments` to calculate duration. Keeps the calculation as a fallback if `duration` is not truthy
- See https://github.com/AudiusProject/audius-protocol/pull/5165
Everything still falls back to track_segments, so it should be safe
Uploaded (v1 and v2 flow) multiple times locally, checked the duration on the track page, and played around with moving the scrubber
Manual testing of track playback on staging
None
=> [CON-660] Prefer duration from track metadata over track_segments calculation

packages/mobile/src/screens/chat-screen/ReactionPopup.tsx, packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx, packages/mobile/src/screens/notifications-screen/Reaction/ReactionList.tsx
Changes to the mobile `ReactionList` for chats broke the other usage of `ReactionList` in notifications (tip sent). The fix:
- Originally measurements were happening inside a `useEffect` that fired whenever `isVisible` changed. Re-add this back so notifications reactions work.
- Using `isVisible` properly on the chats `ReactionPopup` side, but this did not fix so also need to...
- Still perform measurements during `onLayout`.
Local web stage.
Test by confirming both chats `ReactionPopup` and notifications reactions work. Also check that notifications still works when navigating away/back to the notifications screen. …
=> [C-2524] Fix mobile notification reactions

packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx, packages/mobile/src/screens/notifications-screen/Reaction/ReactionList.tsx
Better fix for https://github.com/AudiusProject/audius-client/pull/3279/files that uses values from `LayoutEvent` in the parent `Animated.View` `onLayout` handler.
Local ios stage - tested both chat reactions and notification reactions.
=> Better fix for reactions using LayoutEvent

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/services/remote-config/feature-flags.ts, packages/web/src/components/data-entry/FormTile.js
Splits `storage_v2` feature flag into `storage_v2_track_upload` and `storage_v2_signup` so we can rollout uploads separately first.
@endline I removed the ability to prefix an email with "storage_v2_test_". We'll want to use real emails in prod/staging anyway so just run `localStorage.setItem('FeatureFlagOverride:storage_v2_signup', 'enabled')` in Console and then use a real email with the "+" like theo+42623@audius.co
Will be testing on staging today. Flags are set in optimizely as well
removed: `storage_v2`
added: `storage_v2_track_upload` and `storage_v2_signup`
=> [CON-664] Split storage v2 feature flag into signup+upload

packages/common/src/services/audius-backend/AudiusBackend.ts
Create notifications for tracks weren't showing up in discovery UI 🤦 not sure how we missed this. a while ago joe changed the specifier of track create notifications which audiusbackend was expecting for tracks, so had to update audiusbackend to parse for the information elsewhere in the notif
=> Fix parsing create notification track owner id

packages/common/src/store/pages/chat/slice.ts
Sending a message in a new or unloaded chat for the other user would fail if they have the chats page open, as `addMessage` was getting called for a chat that didn't exist and the `hasTail` check expects there to be one.
=> [PAY-1178] Fix new messages on new/unloaded chats

packages/common/src/services/audius-backend/eagerLoadUtils.ts, packages/common/src/utils/stringUtils.ts
Weird formatting of URL.
Bug: AudiusBackend eager requests (not even AudiusAPIClient... why we have so many API interaces 🤮 ) will send array args like ?id[]=1 instead of ?id=1. This causes initial load to do weird things if you have no discovery selected and are trying to fetch something via a numeric ID.
=> Fix eager fetch

packages/web/src/store/application/ui/buy-audio/sagas.ts
The TransactionDetailsModal on success was showing incorrect values for balance and change, due to a difference in the values being sent from the final part of the buy audio process and the transaction history page
=> [PAY-901] hotfix: TransactionDetailsModal now expects wei amounts

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/web/src/common/store/upload/sagas.js
Frontend changes for https://github.com/AudiusProject/audius-protocol/pull/5171. Want to pass metadata blob directly to `addTracksToChainAndCnode` so it can pass that directly through chain so discovery doesn't have to query content nodes when indexing the event. Use the metadata uploaded to content in libs `uploadTrackContentToCreatorNode`.
This is only triggered by collection uploads (albums and playlists).
Test against staging 
- with backend changes: verify discovery doesn't query content for metadata and albums/playlists upload successfully and are streamable
- without backend changes: albums/playlists upload successfully and are streamable
- with backend and without frontend changes: …
=> Pass metadata to libs for addTracksToChainAndCnode

packages/web/src/common/store/notifications/fetchNotifications.ts
Fixes issue where duplicate notifications sometimes showed up in users notification panel. this was due to not waiting for feature flags + remote config to be ready before making the initial notifications fetch.
=> [PLAT-904] Fix duplicate notifications

packages/common/src/services/audius-api-client/AudiusAPIClient.ts
Fixes issue where we are not indexing the param, just creating an array `[1]` 😢
=> Fix index issue with constructUrl

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/services/discovery-node-selector/DiscoveryNodeSelectorInstance.ts
Fixes issue where we get a retry storm on `/reactions` endpoint when sdk service selector is active. This is due to a change in service-selector where we pass in a cached endpoint, as `initialSelectedNode`, and as a result the service "change" event never gets fired, meaning the callbacks waiting for change never get called. one of those callbacks is from audius-api, which sets libs state from 'eager' to 'libs'. since that never happenend, we continually stayed in the 'eager' state, which looped over forever.
=> [PLAT-863] Fix reaction endpoint when sdk-v2

packages/common/src/hooks/useDownloadTrackButtons.ts, packages/common/src/services/track-download/TrackDownload.ts, packages/common/src/store/cache/tracks/actions.ts, packages/web/src/common/store/cache/tracks/sagas.js, packages/web/src/common/store/pages/track/sagas.js, packages/web/src/common/store/upload/sagas.js, packages/web/src/services/track-download.ts
- In some places we were still showing the download button conditionally upon whether the track's `download` field has the CID in place. We no longer need to do this because we now rely on the stream endpoint to download files. Also, sometimes on stage `cid` is null even though it's downloadable.
- This means we can get rid of the 'processing' state of the download button and a lot of adjacent code
- Removes a lot of code. Testing thoroughly
Tested against stage.
*Are all new …
=> Remove dependency on `download.cid` for determining download eligibility

packages/common/src/utils/urlUtils.ts
Fixes issue where remix.audius.co was marked as an "internal" audius url, causing a redirect issue. The fix was to remove the capture group between https:// and audius.co
There may have been an important reason for this capture group. @Kyle-Shanks would love your insight here
=> Fix internal/external audius urls

packages/web/src/common/store/pages/search-page/sagas.js
Fixes issue in search-results saga where we use yield* instead of yield since it's a .js file
=> Fix search-results saga error due to yield*

packages/web/src/services/audio-player/AudioPlayer.ts
Prevents play error on skip.
Not sure if simply calling `.remove()` is enough, or if setting `src = ''` is also required. @raymondjacobson for thoughts 😄
=> [C-2566] Prevent player error on skip

packages/common/src/store/pages/chat/middleware.ts
Now that we're sending a user's own chats to themselves in websocket land, we need to filter to not inc the unread count if the message comes from themselves
=> DMs: Don't increment unread if it's your own message

packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Dismiss the keyboard when pressing top right kebab on chat screen so that the drawer isn't occluded by keyboard.
=> Dismiss keyboard on mobile chat screen top right press

packages/mobile/src/hooks/useNotificationNavigation.ts, packages/mobile/src/screens/track-screen/TrackScreen.tsx
Fixes issue where navigating to track screen with just an id fails because `canBeUnlisted = true` causes issues. There is a follow up pr to remove `canBeUnlisted` but this is a simpler fix that we can take out to prod early.
=> HOTFIX track notification navigation

packages/web/public/.well-known/apple-app-site-association, packages/web/public/.well-known/apple-app-site-association-stage
Updates apple-site-association file to ignore /legal/terms-of-use url. Unfortunately we cannot do the same thing for android. Their intent-filter's dont allow exclusions, and since we have audius.co/user/... scheme there is no way to exclude this specific url.
This SO answer is super clear regarding android limitations: https://stackoverflow.com/a/45247815
=> [C-2519] Ignore TOS deeplink

packages/common/src/store/pages/chat/selectors.ts, packages/common/src/store/ui/search-users-modal/sagas.ts, packages/common/src/store/ui/search-users-modal/slice.ts, packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx, packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
On search users screen, disable row when not permitted to message user.
Per @sliptype's suggestion, selecting relevant data in flatlist item component rather than passing it in from parent.
Also fixed a bug where `searchUsers` would dispatch infinitely when result count was low.
Local ios simulator stage tested with blocker, blockee, account with followers only inbox settings. Tested that `searchUsers` changes didn't break web.
=> [PAY-1148] Mobile chat user search row disabled when not permitted

packages/common/src/store/pages/chat/slice.ts
Now that the backend is resending recent messages, hasTail calculations were getting re-triggered for old messages and they would randomly show tails when websocket reconnects happened. Unfortunately that means we do need to check if the incoming message already exists and don't add if it does.
Extracted hasTail recalculation to a helper function to be used in both `addMessages` and `fetchMoreMessagesSucceeded`.
=> [PAY-1221] Fix message hasTail recalculations when server resends messages

packages/common/src/store/pages/chat/selectors.ts
On a new chat, `getChatMessageById` would fail (used for the reactions popup on mobile) bc the `chatMessagesState` would be undefined (line 141) and we'd try to access `entities` of it.
Local ios stage + web stage - tested with user Saliou_2 as well as others.
=> [PAY-1215] Fix create new message crash

packages/common/src/store/pages/chat/slice.ts
If we are in the middle of an optimistic chat read and get a new message, we want the new unread count to reflect our optimism.
=> DMs: Use the optimistic unread count if applicable

packages/web/src/pages/chat-page/components/ChatUser.tsx
Clicking the underlined text will now route to the user's profile. 
=> [PAY-1183] Make clicking ChatUser handle/displayname lead to profile

packages/common/src/utils/chatUtils.ts, packages/mobile/src/screens/chat-screen/ChatScreen.tsx, packages/web/src/pages/chat-page/components/ChatMessageList.tsx
- On web, throttle calls to fetchMessages once per 500ms.
- Fixes a bug the existing web scroll handlers where we failed to check if `prev_count > 0` when fetching at the top of the list, leading to spamming comms:
```
// old version:
if (
chatId &&
isScrolledToTop(e.currentTarget) &&
chat?.messagesStatus !== Status.LOADING
) {
// Fetch more messages when user reaches the top
dispatch(fetchMoreMessages({ chatId }))
}
```
Mobile was performing this check correctly, so I took this as opportunity to consolidate this code.
On Throttle vs Debounce:
- I picked throttle because debounce will only call the final invocation of a function; we want to call this periodically as a user scrolls if they're scrolling through a long list of messages.
*Is there anything the reviewer should be on the …
=> [PAY-1139] Throttle calls to fetchMessages on web scroll

packages/web/src/components/animated-button/AnimatedButtonProvider.tsx
Breaking because of remounting of lottie component and it not being able to clean up past event listeners
```
"Cannot read properties of null (reading 'removeEventListener')" 
```
https://audius.sentry.io/discover/homepage/?field=title&field=event.type&field=project&field=user.display&field=timestamp&id=17670&name=&query=%22Cannot+read+properties+of+null+%28reading+%27removeEventListener%27%29%22&sort=-timestamp&statsPeriod=24h&yAxis=count%28%29 …
=> [C-2614] Fix download stems mobile web

packages/common/src/services/audius-api-client/ResponseAdapter.ts, packages/common/src/services/audius-api-client/types.ts
Follow-up to https://github.com/AudiusProject/audius-client/pull/2795 -- all DNs are encoding artist pick track ids now, remove logic handling non-encoded ids.
Change artist pick and query via API
=> Clean up artist_pick_track_id in APIUser

packages/web/patches/react-lottie+1.2.3.patch, packages/web/src/pages/track-page/TrackPageProvider.tsx
- Never go to the 404 page from `TrackProvider` if we're actually trying to go to `/signup`, which happens on mobile web
- Patch Lottie to prevent accessing `this.anim` when `this.anim` is null
=> Hotfix: Fix stems downloads on mobile web

packages/common/src/hooks/useSavedCollections.ts, packages/common/src/store/saved-collections/selectors.ts, packages/common/src/store/saved-collections/types.ts, packages/web/src/components/lineup/CardLineup.tsx, packages/web/src/components/lineup/InfiniteCardLineup.module.css, packages/web/src/components/lineup/InfiniteCardLineup.tsx, packages/web/src/pages/saved-page/SavedPageProvider.tsx, packages/web/src/pages/saved-page/components/desktop/SavedPage.module.css, packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx, packages/web/src/pages/saved-page/components/mobile/SavedPage.module.css, packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
* Now generic to all collections
* Accepts a list of IDs to fetch, which enables filtering of the list _before_ fetching and preserves proper `hasMore` / `fetchMore` behavior based on the filtered list
* Simplified logic which only returns the list of ids which have been fetched, allowing `Card` components to fetch the full metadata themselves
For Desktop and Mobile web, the `AlbumCard` component now accepts an ID and fetches the collection and user info directly. This follows our normalized data patterns and will also help prevent excessive re-renders for already loaded cards just because we've added more items to the albums list.
* Created a version of `CardLineup` which does infinite scrolling. I didn't modify the existing `CardLineup` to do this because we use it in other places where …
=> [PAY-1136][PAY-1129] Add infinite loading to albums on desktop / mobile web

packages/common/src/store/pages/chat/sagas.ts, packages/common/src/store/pages/chat/slice.ts
**Bug:** receiving a new chat in an active session causes a crash because we try to use the ChatID of a chat that doesn't yet exist to index into the `messages` object.
**Fix**:
- First, in the `addMessage` flow exit early if we don't know about the chat yet.
- Fix additional bug in the `fetchChatIfNeeded` flow to fetch chat users so that the `ChatListItem` renders
Also adds a misc type cleanup
None
Web/stage
*Are all new features properly feature flagged? Describe added …
=> [PAY-1220] Fix chat receive bug

packages/common/src/store/pages/chat/sagas.ts, packages/common/src/store/pages/chat/selectors.ts, packages/common/src/store/pages/chat/slice.ts, packages/mobile/src/screens/chat-screen/ChatScreen.tsx, packages/mobile/src/screens/chat-screen/ChatUnavailable.tsx
Adds a message at the bottom of the chat screen when current user is not allowed to send messages to another user. Replaces the textinput. Also disables reactions.
Also added a saga to re-fetch a chat and update it if the recheck permissions flag was changed. This is helpful for if the user loses permissions mid-session. Not sure if strictly necessary, maybe it's ok to just let the user continue to message and only show the `ChatUnavailable` state on next app load.
Either way we should probably handle error states for sent messages.
*Are all new features properly feature …
=> [PAY-1195] Mobile chat screen unavailable states

packages/common/src/store/pages/chat/middleware.ts, packages/common/src/store/pages/chat/sagas.ts, packages/common/src/store/pages/chat/slice.ts, packages/web/src/pages/chat-page/components/ChatMessageList.tsx
Fixes multiple bugs here. 
**Bugs:**
- Retransmitted messages would get double counted. Fix this by losing the `incrementUnreadCount` action entirely and performing the increment in the `addMessage` reducer.
- If scrolled up in a chat, own messages would be counted because the chat would be considered inactive. Now explicitly check for own messages.
- Fixed issues with scroll handler: need to throttle on leading and trailing edge (otherwise it might not fire on scrolling down to bottom of the screen), which necessitated a change to event.target instead of event.currentTarget, bc the latter may no longer existed when the throttled scrollhandler runs
- Fixed issue where chats wouldn't be immediately marked as read when going to a new chat page because we relied on the scroll handler to fire …
=> [PAY-1222] Fix unread messages count

packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Mark chat as read immediately when entering the ChatScreen. This prevents the unread indicator in the ChatListScreen (previous screen) flickering when navigating back to it.
=> Mark chat as read on ChatScreen entry

packages/web/src/components/notification/Notification/components/Reaction/Reaction.tsx, packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Old:
https://github.com/AudiusProject/audius-client/assets/6780028/1d035414-ee9e-45ab-94b0-530700ded035
New:
https://github.com/AudiusProject/audius-client/assets/6780028/75dff7a0-2c19-48f7-a81a-8505e8841756
The issue that the normal reaction click animation was playing, which looks bad when the reaction is shrunk down. This solution is a bit of compromise (removing the active click animation entirely), but matches messenger + iMessage behavior. …
=> [PAY-1177]  Fix double reaction click animation

packages/common/src/store/playlist-library/helpers.ts, packages/web/src/common/store/cache/collections/commonSagas.js, packages/web/src/common/store/playlist-library/sagas.ts, packages/web/src/common/store/playlist-library/watchAddToFolderSaga.ts, packages/web/src/common/store/playlist-library/watchReorderLibrarySaga.ts, packages/web/src/common/store/social/collections/sagas.ts, packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.module.css, packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistUpdateDot.module.css
Fixes issue where drag-dropping new (unfavorited) playlists into the left nav wouldnt appear. Also fixes case of drag-dropping to specific sections in the left nav, including inside folders
- Refactors playlist-library saga to use `typed-redux-saga` which caught a few type bugs.
- Small styling fix with overflowing text. Now that we wrap everything in a span, we also need to text wrap it.
=> [C-2644] Fix issue where new playlist drag-drop not persisting

packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
Adds some logic to show a toast when a user copies a chat message. Also cleaned up a couple of callbacks which were redefined every render unnecessarily
N/A
Manual testing on physical ios device and simulator
N/A
N/A
=> [PAY-1258] Add toast when chat messages are copied

packages/stems/src/assets/styles/colors.css, packages/stems/src/components/Button/Button.module.css, packages/stems/src/components/Button/Button.stories.tsx, packages/stems/src/components/Button/Button.tsx, packages/stems/src/components/Button/types.ts, packages/stems/src/components/Modal/types.ts, packages/web/src/assets/styles/colors.css, packages/web/src/components/help-callout/HelpCallout.module.css, packages/web/src/components/help-callout/HelpCallout.tsx, packages/web/src/pages/chat-page/components/BlockUserConfirmationModal.module.css, packages/web/src/pages/chat-page/components/BlockUserConfirmationModal.tsx, packages/web/src/pages/chat-page/components/ChatHeader.tsx, packages/web/src/pages/chat-page/components/DeleteChatConfirmationModal.module.css, packages/web/src/pages/chat-page/components/DeleteChatConfirmationModal.tsx, packages/web/src/pages/chat-page/components/UnblockUserConfirmationModal.module.css, packages/web/src/pages/chat-page/components/UnblockUserConfirmationModal.tsx, packages/web/src/utils/theme/dark.ts, packages/web/src/utils/theme/default.ts
Adds confirmation modals to blocking, unblocking, and delete chats.
Opted not to make a general "ConfirmationModal" after realizing how much of the modal was being redefined via props, and considering how much of it changes from modal to modal (like button types etc).
- Doesn't have any error handling
- Doesn't wait for success
- Delete Chat copy to be finalized still
- Destructive button type didn't exist yet, adding now
- Updates all `--accent-red-dark-1` to new values per Julian's request
Locally, vs Stage, blocking and unblocking stage users
*For features that are critical or …
=> [PAY-1255] [PAY-1245] DMs: Add confirmation modals

packages/mobile/src/screens/app-screen/AppTabScreen.tsx, packages/mobile/src/screens/edit-playlist-screen/CreatePlaylistScreen.tsx, packages/mobile/src/screens/edit-playlist-screen/LegacyEditPlaylistScreen.tsx, packages/mobile/src/screens/edit-playlist-screen/LegacyPlaylistImageInput.tsx
* Update legacy screens to display legacy inputs
* Update app tab screen to render legacy edit playlist screen
N/A
N/A
N/A
=> Update legacy playlist screens to use legacy inputs

packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Partially solves a bug where while pressing and holding on a chat message, after the reactions popup appears, the user can still scroll vertically on the underlying flatlist, as well as swipe left to navigate back on the navigator. This commit disables scrolling when the popup is active. Unfortunately the user can still swipe left, and if time a scroll gesture right at the end of the longpress there will still be an offset between the popup and original chat message.
=> [PAY-1150] Disable scrolling when chat reaction popup is active

packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
Set a max height for the chat text input. Maintains a consistent height regardless of whether now playing drawer is visible or not.
=> [PAY-1247] Cap height of chat textinput on mobile

packages/mobile/src/app/useSyncCodepush.ts
Attempt to reinstall CodePush updates that failed to install the first time (for unknown reasons)
Will try up to 5 times
Android has a 20-30% CodePush rollback rate consistently, will see if this helps
From CodePush docs:
```
rollbackRetryOptions (RollbackRetryOptions) - The rollback retry mechanism allows the application to attempt to reinstall an update that was previously rolled back (with the restrictions specified in the options). It is an "options" object used to determine whether a rollback retry should occur, and if so, what settings to use for the rollback retry. This defaults to null, which has the effect of disabling the retry mechanism. Setting this to any truthy value will enable the retry mechanism with the default settings, and passing an object to this parameter allows …
```
=> Retry CodePush installs if they failed the first time C-2659

packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx, packages/mobile/src/screens/chat-screen/LinkPreview.tsx
Mobile chats change color on press
When the reaction popup appears, the chat message in the popup will not have the press colors. I don't think it's possible to pass the touch event to the newly created chat message component. And it won't register a `handlePressOut` for that reason.
Uploading Simulator Screen Recording - iPhone 14 Pro - 2023-05-26 at 17.32.55.mp4…
=> [PAY-1276] Mobile chats change color on press

packages/common/src/store/pages/chat/sagas.ts
Sometimes `last_read_at` is `""` so we need to explicitly check for that and fire the `markChatAsRead` request in that case.
=> [PAY-1329] Fix marking chats as unread

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/services/discovery-node-selector/DiscoveryNodeSelectorService.ts, packages/common/src/services/discovery-node-selector/index.ts, packages/mobile/src/services/audius-backend-instance.ts, packages/mobile/src/services/audius-sdk.ts, packages/mobile/src/services/discovery-node-selector.ts, packages/web/src/services/audius-backend/audius-backend-instance.ts, packages/web/src/services/audius-sdk/audiusSdk.ts, packages/web/src/services/discovery-node-selector.ts
Removes the initialSelectedNode from discovery-node-selector to prevent issues where users get stuck on a node that may be unhealthy.
=> [C-2702] Remove initialSelectedNode from disc-node selector

packages/stems/src/components/Button/Button.module.css, packages/web/src/components/collection/desktop/CollectionActionButton.tsx, packages/web/src/components/collection/desktop/CollectionHeader.module.css, packages/web/src/components/collection/desktop/EditButton.tsx, packages/web/src/components/collection/desktop/FavoriteButton.tsx, packages/web/src/components/collection/desktop/OverflowMenuButton.tsx, packages/web/src/components/collection/desktop/PlayButton.tsx, packages/web/src/components/collection/desktop/PublishButton.tsx, packages/web/src/components/collection/desktop/RepostButton.tsx, packages/web/src/components/collection/desktop/ShareButton.tsx
Fixes issue where favorites button had a different size than the rest of the collection action buttons. The issue actually had to do with the way "medium" sized button styles worked, where secondary font-size was larger than other button variant sizes. This fix adds consistency to button sizes across the board, reducing the need for hard-coded styles
=> [C-2699] Fix collection action button sizes

packages/common/src/store/pages/chat/slice.ts
Since our chat state reducers and sagas are all based on the current signed-in user and don't support multiple user chat states, we should reset it on sign out. This isn't an issue for web, as the page is refreshed after sign out and we lose all redux state.
N/A
Tested on physical device against staging
N/A
N/A
=> [pay-1311] Reset chat state on sign out

packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
Make sure that the user is the profile owner when rendering the add playlist tile
N/A
N/A
N/A
=> [C-2717] Fix playlist create tile bug

packages/mobile/src/screens/notifications-screen/Reaction/ReactionList.tsx
For some reason (maybe after RN upgrade) the gesture position values were being measured in reference to the leftmost edge of the screen, but the x and width measurements in the reaction list were measured in reference to the parent view. Needed to incorporate the x offset from the parent to the screen into the gestures.
Local ios stage - tested on both notification screen and reactions popup.
=> [PAY-1370] Fix reaction touch targets

packages/mobile/src/components/collection-list/CollectionCard.tsx
I made a mistake in merging main into my last PR for infinite loading and swapped the track count condition. This caused us to show the offline track count when online and vice versa.
N/A
Locally on physical device
N/A
N/A
=> [PAY-1390] fix inverted condition for computing track count

packages/common/src/store/saved-collections/selectors.ts, packages/mobile/src/store/offline-downloads/sagas/requestDownloadAllFavoritesSaga.ts, packages/web/src/common/store/saved-collections/sagas.ts
The original logic in `requestDownloadAllFavorites` assumed that all collections were fetched before running. This was true because we would load everything when `FavoritesScreen` mounted. However, now that we are fetching full collection details in pages, the selector used for the "download all" flow will only include items that have already been fetched as part of viewing the Albums or Playlists tabs.
To fix this, I added a helper saga that will fetch all account collections and we will wait on that before starting the download process.
Note: I chose to implement it as parallel fetches of albums/playlists so that we reuse the same sagas/actions that power the favorites screen. The result is that if you open the favorites screen and toggle download all, the albums and playlists tabs will …
=> [PAY-1391] ensure all collections are fetched before attempting to download

packages/mobile/src/screens/app-screen/AppTabScreen.tsx
After much investigation with @dylanjeffers and @schottra we were unable to come up with the perfect solution. Current thinking is that if we were able to get the stack navigator gesture handler to cede handling the pan gesture via `onResponderTerminateRequest` then this might work. Would have to patch rngh to do this.
For now the best we could come up with is disabling full screen swipe left gestures on the ChatScreen entirely. User will still be able to swipe left from the leftmost edge of the screen.
*Are all new features properly feature flagged? Describe added …
=> [PAY-1365] Disable fullscreen gestures on mobile chat screen

packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css, packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Fixes issue where the edges of the reactions button wouldn't be clickable. This was caused by my `:active` scaling animation scaling the button instead of the content inside the button, causing the `onClick` to fail to fire. The fix is to animate/scale content inside the button instead of the button itself. 
Would attach video but airplane wifi; play around on demo to see!
CSS diff looks scary but it works
*Are all new features properly feature flagged? Describe added feature …
=> [PAY-1361] Fix reactions button hit area

packages/common/src/store/pages/chat/selectors.ts
Small change to show the global unread indicator if any of the loaded chats have unread messages (since the global unread message count doesn't increase when sent a new message)
Doesn't fix the plethora of other unread optimistic problems, but a small win
=> [PAY-1394] DMs: Show global unread indicator if there's unread messages in a loaded chat

packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.module.css, packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.tsx, packages/web/src/components/collection/desktop/PublishButton.tsx, packages/web/src/components/collection/desktop/ShareButton.tsx, packages/web/src/components/menu/TrackMenu.tsx, packages/web/src/components/share-modal/components/ShareDialog.module.css, packages/web/src/components/share-modal/components/ShareDialog.tsx, packages/web/src/components/share-modal/messages.ts, packages/web/src/components/track/desktop/ConnectedTrackTile.tsx, packages/web/src/components/tracks-table/TracksTable.module.css, packages/web/src/components/tracks-table/TracksTable.tsx
* Update share modal for playlists to warn the user of sharing private playlists
* Update add to playlist modal for hidden tracks to disable public playlists
* Add hidden icon for hidden tracks in playlist tracks table
* Update disable logic for action buttons for playlists based on emptiness and if they contain hidden tracks
N/A
N/A
N/A
=> [C-1873, C-2551, C-2552, C-2553] Add hidden track logic for playlists on web

packages/common/src/store/pages/chat/sagas.ts, packages/common/src/store/pages/chat/slice.ts
- Refactors the "bustCache" param an instead separates out a new fn
- Fetch chat on message failure to get `recheck_permissions` flag in case chat was deleted
=> DMs: Fix deletions not causing perms rechecks

packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
* Reuses the logic from the web user list screen
* Made two local hooks for the two data sources (default user list and search user list)
* Cleans up `ChatUserListScreen` to be a little less complicated and to use the same logic, just switching the data source based on presence of query text
N/A
N/A
N/A
N/A
=> [PAY-1348] clean up ChatUserListScreen and use followers as default list

packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx, packages/mobile/src/screens/chat-screen/LinkPreview.tsx
- Simplifies the DM bubble on mobile (mirroring #3554 ) by adding `overflow: hidden` to the main bubble and leaving it in charge of all border radiuses. Notably, this does not result in the same halo effect that occurs on web, so I didn't opt to do the same wrapper/background color strategy
Before:
After:
=> [PAY-1426] DMs: Simplify unfurl styles for mobile, fix border radius shadow

packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx, packages/mobile/src/screens/chat-screen/ChatScreen.tsx, packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
Was doing this as part of investigation for PAY-1422. Ultimately couldn't repro the bug but this is probably a better pattern to follow anyway.
Bonus: prevent user from setting reaction when not permitted.
=> Mobile ChatMessageListItem uses message id + selector

packages/mobile/src/screens/chat-screen/ChatScreen.tsx, packages/mobile/src/screens/chat-screen/EmptyChatMessages.tsx
Change the empty chat message box to be an actual `ListEmptyComponent` of the flatlist which necessitated mirror-flipping it, and also add extra padding when currently playing track drawer is visible.
Keep in mind everything is flipped because the parent flatlist is inverted.
Feel like there's a clever css way to do this but couldn't figure it out.
=> [PAY-1423] Fix empty chat message box with currently playing track

packages/mobile/ios/fastlane/Fastfile
Forcing mobile staging build since prod 1.1.66 was inadvertently released before staging 1.1.66, so staging is stuck on 1.1.65
Revert once staging 1.1.66 is up on Testflight
=> Force mobile staging build

packages/mobile/ios/fastlane/Fastfile
Accidentally released 1.1.67 intstead of 1.1.66 due to some old code in the fastlane file that doesn't even have to be there any more :')
Expired 1.1.67 and going to force release 1.1.66 using this, then revert. Double checked the android file to make sure the same issue won't happen there as well.
=> Force mobile build again

packages/common/src/store/pages/chat/selectors.ts, packages/common/src/store/pages/chat/slice.ts
Small change to allow us to know a chat is read by seeing our own message through a web socket
=> [PAY-1386] DMs: Mark chat as read on client when new message from self comes through websocket

packages/mobile/src/screens/chat-screen/ChatTextInput.tsx, packages/mobile/src/utils/convertHexToRGBA.ts
Workaround to keep Android send icon always white.
Changed logic in `convertHexToRGBA` but I believe it was a bug.
Before:
After:
=> [PAY-1399] Fix Android chat send button color

packages/mobile/src/components/block-messages-drawer/BlockMessagesDrawer.tsx, packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx, packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx, packages/mobile/src/screens/profile-screen/MessageLockedButton.tsx, packages/mobile/src/store/drawers/slice.ts
Adds a boolean flag to allow certain drawers to navigate to a chat after the user unblocks the selected user they want to chat with.
local ios  stage
=> [PAY-1435] Navigate to chat after unblocking user on mobile

packages/web/package.json
Noticed that sourcemaps were working fine when running web:dev. Turns out we have sourcemap generation via the `build:prod-source-maps` command. All we needed was the same env var when running `start:prod`
We expose source maps in prod anyway so this should be safe. It may slow down `start:prod` slightly
=> [INF-417] Generate sourcemaps when running web:prod

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/web/src/common/store/cache/tracks/sagas.js
Makes it safe to flip v2 tracks back to disabled after flipping to enabled. Otherwise updating v2 tracks would fail because it would try the old flow (which is what I saw for my prod v2 track on mobile where I didn't have the feature flag enabled - the app crashed and sentry confirmed it was trying to use the v1 edit-track flow).
This is also important for users who signup as v2 but don't get the feature flag for v2 uploads (due to feature flag flakiness we've run into before).
- Uploaded a v2 track to staging and confirmed that editing it works even with setting the feature flag to false (previously broken - caused heavy load screen)
- Tested the inverse (upload a v1 track with the track upload feature flag set to true and then to false)
Same upload flag: `storage_v2_track_upload`
=> [CON-742] Make users and track actions v2 for v2 users/tracks even when feature flags are disabled

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/store/pages/chat/middleware.ts, packages/web/src/services/audius-sdk/audiusSdk.ts
tl;dr - let's just wait for libs to init before doing anything with SDK, even if SDK is fully functional on its own
Occasionally, the user would get into a state where they'd be infinitely requesting the same "bad" request to the same DN. Oftentimes, this would be on page load as we'd try to fetch reactions for a notification that hasn't been reacted to yet. Other times, I was able to trigger it by opening the tip modal for someone I hadn't tipped yet. These are expected "failed" requests (404s in this case) as we expect those to not exist sometimes. So why was there an infinite request happening?
What's more, we had seen this bug before and _thought_ we had fixed it!
In `AudiusAPIClient` we had this branch of code that makes a request using the eager discovery provider, and on failure, …
=> [PAY-1448] End the race between SDK and Libs, once and for all

packages/mobile/src/components/core/TextInput.tsx
Bug was that `map` passes index as 2nd arg, so the first color in the list was getting opacity 0. We didn't hit this before because `opacity` in `convertHexToRGBA` was actually not being used, we always set it to `1` regardless of the `opacity` arg.
Local ios stage:
Confirmed send button opacity still works on android:
a41b2df0-1dce-4028-9def-5aa73af550fc)
=> Fix mobile textinput borders + labels

packages/common/src/store/cache/reducer.ts
Fixes issue where user's playlist library can disappear from left-nav. This has to do with the api not always returning a user's playlist_library, which actually makes sense for all users other that the active user. The fix for now is to just always keep a user's playlist_library on their user object if we ever get it back.
=> [C-2770] Fix issue where playlist library can disappear

packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Changes two props on our flatlist:
- `removeClippedSubviews` - this detaches out of screen views from the main UI thread
- Set `windowSize = 5`. `windowSize` determines how many viewports (half above, half below) are still rendered invisibly before the views are culled. The default is 21, which is very high!
https://reactnative.dev/docs/optimizing-flatlist-configuration#windowsize
Anecdotally this seems to help chats with many reactions on iOS simulator, but need to test this on device more thoroughly to see if it actually does anything (or introduces any scary bugs).
I went down another rabbit hole earlier trying to have the reactions only render when the parent view itself is onscreen; this is actually quite easy with `onViewableItemsChanged` …
=> [PAY-1455] Optimize reactions perf (maybe)

packages/web/src/services/audius-sdk/audiusSdk.ts
SDK internally calls DN.select() here now : https://github.com/AudiusProject/audius-protocol/blob/f1a02996172e91f8880abbbe3c3588b08f5fa7dd/libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts#LL40C4-L40C4
so we have to wait for handlers
=> Wait for libs to init before initting SDK

packages/mobile/src/screens/chat-screen/ChatScreen.tsx, packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
The real fix here was to switch to using `measure` and `pageY` everywhere. God knows why this is different on iOS vs Android. 
Made few cosmetic changes as well; removed the `measureView` abstraction, and the promise wrapping the message ref measurement.
Video of me not knowing how to use the Android emulator 😆:
https://github.com/AudiusProject/audius-client/assets/6780028/3186d262-4521-42b3-81f8-4232a9d1307e
*Are all new features properly feature flagged? Describe added …
=> [PAY-1421] Fix android reaction offsets

packages/mobile/patches/README.md, packages/mobile/patches/react-native+0.71.8.patch
Discovered an RN bug with TextInput where `multiline` was set to true - `onChange` would not fire for the first character entered into the textinput.
See https://github.com/facebook/react-native/issues/37784.
The patch reverts a commit that is to fix a different issue: https://github.com/facebook/react-native/issues/36494
Tested the repro steps in that issue and didn't notice anything broken.
https://github.com/AudiusProject/audius-client/assets/3893871/163a15f5-beb0-4213-bd11-430a31b8223e
=> [PAY-1483] Patch RN to fix textinput multiline onchange not firing

packages/mobile/src/screens/chat-screen/CopyMessagesButton.tsx, packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
The fix was to add zIndex to the correct parent View.
Bonus - use `staticWhite` so copy message button is always white in other themes.
https://github.com/AudiusProject/audius-client/assets/3893871/9bf099d7-2816-43a6-ac15-070e178c36d6
=> [PAY-1468] Fix mobile chats copy message button

packages/mobile/src/components/core/CardList.tsx, packages/mobile/src/screens/explore-screen/components/TabInfo.tsx, packages/mobile/src/screens/explore-screen/tabs/ArtistsTab.tsx, packages/mobile/src/screens/explore-screen/tabs/ForYouTab/ForYouTab.tsx, packages/mobile/src/screens/explore-screen/tabs/ForYouTab/LetThemDJScreen.tsx, packages/mobile/src/screens/explore-screen/tabs/ForYouTab/TopAlbumsScreen.tsx, packages/mobile/src/screens/explore-screen/tabs/ForYouTab/TrendingUndergroundScreen.tsx, packages/mobile/src/screens/explore-screen/tabs/MoodsTab.tsx, packages/mobile/src/screens/mood-collection-screen/MoodCollectionScreen.tsx, packages/mobile/src/screens/profile-screen/AlbumsTab.tsx, packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx, packages/mobile/src/screens/search-results-screen/tabs/AlbumsTab.tsx, packages/mobile/src/screens/search-results-screen/tabs/PlaylistsTab.tsx, packages/mobile/src/screens/search-results-screen/tabs/ProfilesTab.tsx
Updated the component structure slightly to fix the headers
N/A
N/A
N/A
=> [C-2760, C-2779] Fix header for playlist and artists tabs in explore screen

packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
- Fixes onPress colors for `InboxUnavailableDrawer` by default button text colors
- Fixes crash on slowly dragging to dismiss said drawer
Not sure if there was a reason we were specifically styling the text color versus just falling back on the variant.
=> [PAY-1498][PAY-1477] Misc mobile DMs UI Fixes

packages/mobile/src/screens/root-screen/RootScreen.tsx
Hard to repro this bug but I think this should fix it. The theory is that after a crash, the player state from before the crash was persisted, which caused `getHasTrack` player selector to erroneously report `true`.
Would like to get this in for the QA and see if we get any repros of the bug.
Adding stuff to root screen!
Hard to prove this makes the bug go away, but I did confirm this action only runs once on startup and that normal app behavior is unaffected.
=> [PAY-1412] Reset player state on app load

packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
=> [PAY-1526] Mobile chat reaction picker shadow

packages/mobile/src/screens/chat-screen/ChatScreen.tsx
The bug: with keyboard open, if the user longpresses a message and opens the reaction popup, the message will display over the textinput below it.
=> Mobile chats recalculate container bottom on keyboard shown

packages/mobile/src/screens/profile-screen/ProfileTabNavigator.tsx, packages/mobile/src/screens/profile-screen/useIsArtist.ts
Fixes issue where every profile screen shows "artist" tabs if the current user happens to be an artist.
Moved relevant code into isolated hook for easier reading.
Ensures fetch only happens once per session.
=> Fix user profile always showing artist tabs

packages/web/src/components/collection/desktop/utils.ts, packages/web/src/components/track/GiantTrackTile.module.css
Fixes issue where track-page action buttons get cut off when a user has favorited and/or reposted it.
Also improves distances where the buttons collapse
=> Fix entity button widths

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/mobile/src/components/image/FastImage.tsx, packages/mobile/src/store/settings/sagas.ts
At app startup, reregister device token if notification permissions are enabled. This will prevent cases where a device id changes causing users to not receive notifications.
- Also improves some typing
- Also fixes issue with fast-image, there are some obscure cases where uri is undefined leading to app-ending bug
=> [C-2787] Reregister device-token on app startup

packages/mobile/src/components/now-playing-drawer/PlayBar.tsx, packages/web/src/components/play-bar/desktop/PlayBar.js, packages/web/src/components/play-bar/mobile/PlayBar.tsx
Disable favorite and repost buttons in the play bar for hidden tracks. they should not be able to be liked/favorited, and there is no ui button for it on the page, but there is a way to do so via the play bar currently. this diff disables the buttons in the play bar
This change is only for tracks since you can't even view private playlists via links as of right now.
tested via ui, will attach video
https://github.com/AudiusProject/audius-client/assets/109105561/5556dfd4-8f29-4344-b4a5-3483c8eb8610
=> [plat-1085] disable fav and repost on hidden tracks in play bar

packages/common/src/store/pages/chat/sagas.ts, packages/common/src/store/pages/chat/slice.ts, packages/mobile/src/screens/chat-screen/ChatListScreen.tsx, packages/mobile/src/screens/chat-screen/ChatScreen.tsx
Would appreciate more eyes and testing on this, it's rather large.
- On rendering a chat screen:
- If it's the first load:
- Get batches of messages until we have all the unread messages
- Otherwise
- Get all messages newer than what we have
- Adds pull to refresh on the chat list screen
- Updates reducer logic to take the earliest prev_cursor and latest next_cursor in both fetchMessages and fetchChats
- Updates messages batch size to 50 from 10
Known issue: Going into a chat that has new messages before a chat has been refreshed to acknowledge an unread count won't show the inline indicator of the unread count. This is because we cache the unread state on loading the chat screen prior to …
=> [PAY-1535] Refresh chat messages on render and pull to refresh on chats list

packages/web/src/common/store/pages/signon/sagas.js
Fixes sign-up issues stemming from improper use of environment variables that only work on web
- Fixes sign up issue where mobile app wasn't following audius-account
- Fixes sign up issue where mobile app didnt check twitter/insta/tiktok for handles
- Fixes sign up issue where mobile app didnt follow hot-and-new playlist
=> [C-2718] Fix mobile sign-up environment issues

packages/mobile/src/screens/chat-screen/ChatScreen.tsx
There was a bug where our nice new `fetchLatestMessages` action/saga wouldn't fire if we backgrounded the app on a chat page and then foregrounded it onto the same chat page, because we wouldn't remount the component + trigger the useEffect that dispatches the action.
This change also listens to app state to trigger fetching new messages.
On device, turned off websockets, looked at logs. 
=> Fetch chats on app foreground

packages/mobile/src/components/details-tile/DetailsTile.tsx
Noticed the artist name was looking a little thin. Not sure when this changed but simple fix.
before:
after:
=> Fix track screen artist name font weight

packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx, packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx, packages/mobile/src/components/locked-content-drawer/LockedContentDrawer.tsx
I'd missed some subtle margin changes to the gated content track screen.
Local ios stage - also tested locked content drawer
=> Mobile gated content updates pt. 2

packages/common/src/store/pages/chat/selectors.ts
Somewhat of a provisional change since I can't get push notifs to work on local builds... let's land this on stage and then see if it fixes the issue. 
Slightly scary if there's any other situation where userId is none besides loading in from a push notif, but I can't think of any
It has not been
=> [PAY-1563] Fix loading into a chat from a push notification

packages/common/src/services/local-storage/LocalStorage.ts, packages/common/src/services/sdk/discovery-node-selector/DiscoveryNodeSelectorService.ts, packages/web/src/services/audius-sdk/discoveryNodeSelector.ts
Fix the "d" dialog that changes discovery node by adding back the code that reads and sets the local storage cache for discovery node.
Web only.
=> [PAY-1463] Fix d to set discovery node

packages/stems/src/components/Popup/Popup.tsx, packages/stems/src/components/Popup/types.ts, packages/stems/src/components/PopupMenu/PopupMenu.tsx, packages/stems/src/components/PopupMenu/types.tsx, packages/stems/src/utils/scrollParent.ts, packages/web/src/components/audio-transactions-table/AudioTransactionsTable.tsx, packages/web/src/components/table/Table.tsx, packages/web/src/components/tracks-table/TracksTable.tsx, packages/web/src/pages/App.d.ts, packages/web/src/pages/App.test.tsx, packages/web/src/pages/MainContentContext.tsx, packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
This reverts commit 12fe88d07660922df8a985557bf6af84af745b52.
Stumbled upon some issues with this.. looking into it but reverting for now.
=> Revert "[PAY-1534] Allow Popup to be mounted inside a container (#3669)"

packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
Ensures that all chat permission actions render something.
=> DMs: Ensure every permission action has a CTA

packages/common/src/services/audius-backend/AudiusBackend.ts
Our endless retry logic happened again. I so want to rework this AudiusAPIClient and AudiusBackend nonsense but in the meantime, just added this minor hack to allow cached DNs to work.
It calls the AudiusBackend DN change listener if the config for DN selector has an initialSelectedNode.
Relies on using a private member of DN selector, `config`, and as such requires a `@ts-ignore`.
=> Call the DN selection callback in AudiusBackend if using a cached DN

packages/mobile/src/components/audio/Audio.tsx, packages/mobile/src/components/image/CollectionImage.tsx, packages/mobile/src/components/image/TrackImage.tsx, packages/mobile/src/components/image/UserCoverImage.tsx, packages/mobile/src/components/image/UserImage.tsx, packages/mobile/src/hooks/useContentNodeImage.ts, packages/mobile/src/screens/search-screen/SearchResults/SearchItem.tsx, packages/mobile/src/store/account/sagas.ts, packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadCollectionWorker.ts, packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
Now that we dont need user.creator_node_endpoint, a lot of the mobile image hooks dont need to pull in the user. this is great cause it simplifies the api and also reduces rerender count since we dont listen to user updates.
=> [C-2809] Remove user from image hooks

packages/common/src/models/Lineup.ts, packages/common/src/store/lineup/reducer.ts, packages/common/src/store/pages/ai/lineup/reducer.ts, packages/common/src/store/pages/feed/lineup/reducer.ts, packages/common/src/store/pages/profile/lineups/feed/reducer.ts, packages/common/src/store/pages/profile/lineups/tracks/reducer.ts, packages/common/src/store/pages/remixes/lineup/reducer.ts, packages/common/src/store/pages/search-results/lineup/tracks/reducer.ts
- Removes `containsDeleted` which was causing the bug in remix lineup [C-2547](https://linear.app/audius/issue/C-2547/[qa]-remix-lists-failing-to-load-completely)
- Fixes `hasMore` offset logic
Changing feed is scary
- `containsDeleted` was from https://github.com/AudiusProject/audius-client-old/pull/1043 which we believe is no longer relevant
- hasMore logic was definitely wrong, but maybe was for a case where an absolute limit was passed instead of a pageSize limit. Need to keep an eye on this in stage.
=> [C-2547] Lineup pagination fixes

packages/stems/src/components/MarkdownViewer/MarkdownViewer.module.css, packages/web/src/components/ai-attribution-settings-modal/AiAttributionSettingsModal.module.css
Removed `overflow` css prop from stems, allow consumer to pass it in when necessary.
One more user of `MarkdownViewer` is `AnnouncementPage` but don't think it's accessible via UI anymore? The route is `/notification/:notificationId`.
Local web stage:
=> [QA-565] Fix notification overflow bug

packages/web/src/components/notification/Notification/AnnouncementNotification.module.css, packages/web/src/components/notification/Notification/AnnouncementNotification.tsx, packages/web/src/components/notification/Notification/components/NotificationTile.module.css, packages/web/src/components/notification/Notification/components/NotificationTile.tsx, packages/web/src/components/notification/NotificationPage.tsx, packages/web/src/components/notification/NotificationPanel.tsx
Bonus: removed a few unused messages that were annoying during ctrl+f
Now if `NotificationTile` `disabled` prop is true, hover animation is also disabled. Originally it was only `active` styles that were disabled. Only other place that uses this is `TipReceivedNotification`, don't entirely understand the purpose of this but I tested against current stage and behavior seemed the same. cc @dylanjeffers .
https://github.com/AudiusProject/audius-client/assets/3893871/94973579-ac76-446f-a50b-d5e46cb77f2e
*Are all new features properly feature flagged? Describe added feature …
=> Update announcement notification style and hover behavior

packages/web/src/components/notification/Notification/AnnouncementNotification.module.css, packages/web/src/components/notification/Notification/AnnouncementNotification.tsx, packages/web/src/components/notification/Notification/components/NotificationTile.module.css, packages/web/src/components/notification/Notification/components/NotificationTile.tsx, packages/web/src/components/notification/NotificationPage.tsx, packages/web/src/components/notification/NotificationPanel.tsx
Last one resulted in an empty commit somehow??
=> Update announcement notification style and hover behavior retry

packages/stems/src/assets/styles/colors.css, packages/stems/src/components/Button/Button.module.css, packages/stems/src/components/Button/Button.stories.tsx, packages/stems/src/components/Button/Button.tsx, packages/stems/src/components/Button/types.ts, packages/web/src/components/locked-content-modal/LockedContentModal.tsx, packages/web/src/components/track/CardTitle.tsx, packages/web/src/components/track/GiantTrackTile.module.css, packages/web/src/components/track/GiantTrackTile.tsx, packages/web/src/components/track/PlayPauseButton.tsx, packages/web/src/components/track/PremiumTrackSection.tsx, packages/web/src/pages/track-page/components/HiddenTrackHeader.module.css, packages/web/src/pages/track-page/components/mobile/ActionButtonRow.module.css, packages/web/src/pages/track-page/components/mobile/StatsButtonRow.module.css, packages/web/src/pages/track-page/components/mobile/StatsButtonRow.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Updates all of the code paths for web and mobile web track details and locked content modal to render the USDC variants for locked, unlocking, unlocked, and owner states.
* Added `Large` variant to Button
* Updated Secondary Button style to match new Harmony versions
* It's only used in two places at the moment, so should be safe
* Updated Button stories to render all sizes to make things easier to compare
* Cleaned up GiantTrackTile and TrackHeader
* Both now correctly show the Gated/Premium track section based on type/unlocked/owner status
* TrackHeader got an overall to make the layout simpler and correctly order the sections (we had two copies of <PremiumTrackSection /> for no apparent reason)
* Added Preview button to both versions of the page. Will show if the user is owner or …
=> [PAY-1561][PAY-1558] Implement USDC variants on track details page

packages/web/src/pages/oauth-login-page/utils.ts
Causing bug where the url was too large as we're serializing the entire storage node list into the request
=> Get the first storage node for o-auth not all of them

packages/mobile/src/screens/chat-screen/ChatScreen.tsx, packages/web/src/pages/chat-page/ChatPage.tsx, packages/web/src/pages/chat-page/components/ChatMessageList.module.css
If a user tries to message someone whose inbox is tip-gated, they can optimistically navigate to an empty chat page even though the chat hasn't been created yet (has to wait for tip to be indexed). This can take a while and in this state if the user sends a message, the app crashes (on both mobile and web). Solution is to hide the textinput until the chat is actually created.
Also center the loading spinner.
Local web + mobile stage
Including other screenshots to show that behavior of chat messages + say hello prompt has not changed with the css layout changes in this PR.
*Are all new …
=> [PAY-1595] Hide chat textinput until chat exists

packages/web/src/common/store/lineup/sagas.js, packages/web/src/pages/upload-page/fields/availability/collectible-gated/CollectibleGatedFields.tsx, packages/web/src/pages/upload-page/forms/TrackAvailabilityModalForm.tsx
Using a similar strategy to #2956 , inserts a step into the lineup processing that treats USDC-gated tracks as "deleted" in all cases. This should take care of all environments since it's done at the generic lineup saga level.
You could still navigate directly to a USDC-gated track. But I think our goal for now is to not surface these tracks into feeds/trending/artist pages.
Tested locally on web/mobile web/ simulator
N/A
Uses the USDC_PURCHASES feature flag. On by default in development.
=> [PAY-1578] Hide USDC-gated tracks if the feature flag is disabled

packages/mobile/src/screens/chat-screen/ChatMessageSeparator.tsx, packages/mobile/src/screens/chat-screen/ChatUnavailable.tsx, packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx, packages/mobile/src/screens/chat-screen/CopyMessagesButton.tsx, packages/mobile/src/screens/chat-screen/ResendMessageButton.tsx
Figured I'd go ahead and change all the `Text` usages in mobile chats to our `Text` component, after all the incorrect fonts we caught.
Also caught an erroneous `marginTop` that was causing incorrect layout in `ChatUserListItem`.
=> Use Text component in mobile DMs

packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Dup of https://github.com/AudiusProject/audius-client/pull/3755 - re-doing PR bc we just merged a giant feature branch into main that caused lots of conflicts, the rebase was going to be insane for this tiny change.
Change hidden track track screen header to `neutralLight4` to match other track header types.
=> [PAY-1612] Change mobile hidden track header color

packages/mobile/src/components/lineup-tile/LineupTileStats.tsx, packages/web/src/components/track/mobile/TrackTile.module.css, packages/web/src/components/track/mobile/TrackTile.tsx
Icon should be first, followed by stat number.
Fixed on both mobile and mobile web.
=> [PAY-1621] Reverse order of mobile lineup tile stat icon and number

packages/web/src/store/token-dashboard/signMessage.ts
When trying to connect a phantom wallet, we see this error message
```
"Caught error during handleConnectNewWallet:  TypeError: Cannot read private member from an object whose class did not declare it, resetting to initial state"
```
Presumably this is because of some change in a typescript dependency, not directly because of a phantom change.
I am unsure exactly how this change fixes it, but it seems to, probably because `this` context is necessary?
N/a
1. Ran client against stage
2. Connected phantom wallet …
=> [C-2858] Fix phantom signing

packages/mobile/src/components/details-tile/DetailsTile.tsx, packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx, packages/mobile/src/components/details-tile/types.ts, packages/mobile/src/components/lineup-tile/LineupTile.tsx, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Adds dog ear for hidden tracks.
Also gets rid of green background in track screen details section.
Decided to plumb down `isUnlisted` prop to `DetailsTile` etc bc that's the pre-existing pattern (instead of just using `track?.is_unlisted` directly.
I know the hidden track lineup tile is still weird, will follow up in another PR.
=> [PAY-1639] Fix mobile hidden track dog ear

.circleci/src/commands/@mobile-commands.yml, .circleci/src/jobs/@mobile-jobs.yml, .circleci/src/workflows/mobile.yml, .gitignore, packages/mobile/dapp-store/README.md, packages/mobile/dapp-store/pnpm-lock.yaml
Add CI for solana saga dapp store release
All release branches will have a mobile hold step for solana phone push
Could accidentally publish solana build? 🤷 
Didn't want to run and full test and deploy until we were actually ready, but it got quite far on the last run
https://app.circleci.com/pipelines/github/AudiusProject/audius-client/15288/workflows/8d320d67-55c2-4072-b63b-26e059076bf3/jobs/143269
and the only change at that point was just to make sure we used node 18 via nvm use in the dapp store CI commands. have confirmed that the solana key gets loaded correctly
*For features …
=> Add Dapp store publishing in CI

packages/stems/src/components/Button/Button.module.css
I made changes to secondary buttons as part of our gated content updates. This broke some more subtle behavior of buttons which use Secondary as an "active" variant. For now, going to undo them to fix the regression. Will follow up later with a more backwards-compatible change.
Technically breaks the new "preview" button style slightly. But that's feature-flagged anyway. Will fix before release.
Manually tested locally
N/A
N/A
=> [C-2866] Undo secondary button style changes

packages/mobile/src/assets/images/dogEarRectangle.svg, packages/mobile/src/components/card/Card.tsx, packages/mobile/src/components/card/CollectionDogEar.tsx, packages/mobile/src/components/core/DogEar.tsx, packages/mobile/src/components/details-tile/DetailsTile.tsx, packages/mobile/src/components/lineup-tile/LineupTile.tsx, packages/web/src/assets/img/dogEarRectangle.svg, packages/web/src/components/dog-ear/DogEar.module.css, packages/web/src/components/dog-ear/DogEar.tsx, packages/web/src/components/tile/Tile.module.css, packages/web/src/components/tile/Tile.tsx, packages/web/src/components/track/GiantTrackTile.module.css, packages/web/src/components/track/desktop/ConnectedTrackTile.module.css, packages/web/src/components/track/desktop/TrackTile.module.css, packages/web/src/components/track/desktop/TrackTile.tsx, packages/web/src/components/track/mobile/TrackTile.module.css, packages/web/src/components/track/mobile/TrackTile.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
DogEars were rendering with a visible gap around the outside (the border of the container beneath them). The fix for this turned out to be a little trickier than expected, partially due to the way the component was implemented.
The original implementation was done with an 80x80px square linear gradient, rotated 45 degrees and then clipped by the parent container's border box to achieve the desired shape. While this works, it had two disadvantages:
* It requires `overflow:hidden` to be set on the parent. When using this overflow setting, no child is allowed to exceed the border box. And that means the DogEar cannot overlap the border, and the border will be visible around the outside.
* It was not in sync with the vectors being used in the Figma designs
I brought in the new SVG, which uses …
=> [PAY-1618] Update DogEar rendering and fix spacing

packages/web/src/components/track/desktop/TrackTile.module.css, packages/web/src/components/track/desktop/TrackTile.tsx, packages/web/src/components/track/mobile/TrackTile.module.css, packages/web/src/components/track/mobile/TrackTile.tsx
According to the designs, Artist Pick should show in the same location as the other special content labels. This change moves the text from the upper right to the middle and shows it if the track is not premium.
None
Verified locally on web and mobile web emulator
N/A
N/A
---
---
---
=> [PAY-1615] Fix display of "Artist Pick" text

packages/common/src/utils/dogEarUtils.ts, packages/web/src/components/track/GiantTrackTile.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
I noticed we were (cleverly) omitting arguments on mobile to force showing dog ears on track details pages. This approach felt cleaner than my attempts to break the combination of access/owner logic out to individual components. So I documented the behavior of `getDogEarType` and updated the web variants to use this strategy.
None
,
Locally verified on web and mobile web
N/A
N/A
=> [PAY-1575] Always show premium DogEars on track details page

packages/web/src/components/track/GiantTrackTile.tsx, packages/web/src/components/track/desktop/BottomRow.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Track owners should be able to share a hidden track they own regardless of visibility settings for the button. This updates the various components on web/mobile web to make sure the button is visible in that case.
None
Verified locally on web / mobile web emulator
N/A
N/A
=> [PAY-1635] Always show share button for track owners on hidden tracks

packages/mobile/src/components/drawer/Drawer.tsx
Drawer background should be `palette.white` instead of `palette.neutralLight10`.
Have not tested every single drawer, but it's a very slight color change so should be fine. The only problem I can think of is, if there was some content that was `palette.white` in order to stand out against the background, this would make that less visible. Again, very slight color change.
=> Change mobile drawer background to white

packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx, packages/mobile/src/components/locked-content-drawer/LockedContentDrawer.tsx, packages/mobile/src/components/track-details-tile/TrackDetailsTile.tsx, packages/mobile/src/components/track-details-tile/index.ts
To keep the layout/design consistent with the incoming USDC Purchase drawer.
`TrackDetailsTile` is kind of generic-sounding, open to suggestions.
Confirmed it doesn't break existing track screen layout.
=> [PAY-1652] Update LockedContentDrawer on mobile

packages/mobile/src/components/core/LockedStatusBadge.tsx
Realized vertical padding was 1px off.
Also setting a default for `variant` bc in USDC Purchase Drawer there is a case where the badge will only ever be locked and therefore background color will only ever be gray, so we don't care about which variant is used.
=> Fix mobile LockedStatusBadge padding

packages/common/src/models/Track.ts, packages/mobile/src/app/Drawers.tsx, packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx, packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx, packages/mobile/src/components/lineup-tile/LineupTilePremiumContentTypeTag.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/mobile/src/components/premium-track-purchase-drawer/index.ts, packages/mobile/src/components/track-details-tile/TrackDetailsTile.tsx, packages/mobile/src/store/drawers/slice.ts
Re-trying this PR, had to close previous one due to git snafu: https://github.com/AudiusProject/audius-client/pull/3791
UI for purchasing USDC-gated tracks.
How do we feel about exporting the PremiumContentType enum in models?
Also cc @dylanjeffers wondering if there's a smarter way to do the colors in TrackDetailsTile. Icon takes a string, while Text takes a keyof ThemeColors.
=> [PAY-1587] Mobile USDC Purchase Drawer Skeleton

packages/mobile/src/components/core/Text.tsx, packages/mobile/src/components/track-details-tile/TrackDetailsTile.tsx
Adds support for `Text` to accept a `colorValue` prop like `palette.accentBlue` rather than a string like `accentBlue`.
Updates the usage of `Text` in `TrackDetailsTile` to use this prop.
=> [PAY-1655] Add ColorValue prop to Text component

packages/web/src/components/typography/Text.tsx, packages/web/src/components/typography/constants.ts, packages/web/src/components/typography/index.ts, packages/web/src/components/typography/types.ts, packages/web/src/components/typography/typography.module.css
Testing out a first version of a Typography component for web.
Note: This does not use the css variables that were written by Randy bc this we mostly build out before that work was done
N/A
Manual testing
N/A
N/A
=> [C-2890] Add first version of a typography component to web

packages/web/src/components/track/desktop/BottomRow.tsx, packages/web/src/components/track/desktop/TrackTile.tsx, packages/web/src/components/track/mobile/BottomButtons.tsx, packages/web/src/components/track/mobile/TrackTile.tsx, packages/web/src/components/typography/Text.tsx, packages/web/src/components/typography/constants.ts, packages/web/src/components/typography/types.ts, packages/web/src/components/typography/typography.module.css, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx, packages/web/src/pages/upload-page/forms/AttributionModalForm.tsx
Update the component to use the classnames that were already defined from before. makes things a little cleaner in the file.
Also needed to update the references to the classnames that were used in the code base.
This looks a little weird now, but will be replaced with the component in the future so this won't be an issue
slight risk of incorrect styles in the interim before the component is used. shouldn't be a big issue though
N/A
N/A
=> Update typography component to use classnames

packages/web/src/components/card/desktop/CollectionArtCard.tsx, packages/web/src/components/menu/CollectionMenu.tsx, packages/web/src/components/menu/Menu.tsx, packages/web/src/components/menu/TrackMenu.tsx, packages/web/src/components/table/components/OverflowMenuButton.tsx, packages/web/src/components/tracks-table/TracksTable.tsx
Fixes menu types that broke due to `Omit<>` breaking up the discriminated union, causing casting issues, and preventing menu usages from typing track vs album vs playlist vs user correctly
=> [C-2901] Fix menu types

packages/web/src/components/track/desktop/ConnectedTrackTile.module.css, packages/web/src/components/track/desktop/TrackTile.module.css
The stats row gets large if you happen to be following multiple people which reposted and favorited a track. The styling for the socials row includes a margin to make space for the plays. But it wasn't set up to restrict its content to the available space.
Also for small track tiles, we change the height of the row to 18px, which causes the plays count to be off-center since it is rendered absolutely. There is longer term cleanup needed on the socials row so that the content isn't sized larger than its container and centered. But it wasn't a safe change to make due to the multiple places we use the `Stats` component. This fixes the display issues for now, and we will address it more fully later.
N/A
Verified locally on Chrome
N/A
N/A
**Before**
---
**After**
=> [PAY-1660] Fix layout issues with TrackTile socials row with a lot of stats

packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
Use audius-query to fetch track data. Turns out I didn't need `status` anyway as the track should always exist (since we only open this drawer from a track tile) but might as well merge this!
=> Use audius-query in USDC Purchase Drawer

packages/web/src/components/search-users-modal/SearchUsersModal.tsx, packages/web/src/components/share-modal/ShareModal.tsx
Clicking outside the modal should just close everything. Clicking the X should go back to the previous modal.
=> DMs: Web: Don't nav back when clicking outside the modal

packages/common/src/services/audius-backend/AudiusBackend.ts
Fixes send audio flow - we had changed `solanaWeb3Manager` mint type but in this file, `audiusLibs` is `any` so we didn't catch it!
Tested locally against prod
=> Fix send audio flow

packages/common/src/store/pages/chat/sagas.ts, packages/common/src/store/pages/chat/slice.ts, packages/common/src/store/ui/create-chat-modal/slice.ts, packages/mobile/src/components/share-drawer/ShareDrawer.tsx, packages/mobile/src/screens/app-screen/AppTabScreen.tsx, packages/mobile/src/screens/chat-screen/ChatScreen.tsx, packages/mobile/src/screens/chat-screen/ChatTextInput.tsx, packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx, packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx, packages/mobile/src/store/chat/sagas.ts, packages/web/src/components/search-users-modal/SearchUsersModal.tsx, packages/web/src/pages/chat-page/ChatPage.tsx, packages/web/src/pages/chat-page/ChatPageProvider.tsx, packages/web/src/pages/chat-page/components/ChatComposer.tsx, packages/web/src/pages/chat-page/components/CreateChatModal.tsx, packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx, packages/web/src/store/application/ui/chat/sagas.ts
Use route parameters/location state instead of redux store where possible to prevent stale share data from leaking.
Tested locally against both web stage and ios stage
=> [PAY-1692] Rewrite 'Share to DMs' using less stateful logic

packages/web/.gitignore, packages/web/public/index.html, packages/web/scripts/workers-site/index.js, packages/web/wrangler.toml
Most (95+%) of pages aren't recognized by google at all right now.
This does a nifty on the fly html rewrite on the cloudflare side (which is then cached) and injects the proper tags from a request sent to discovery nodes.
This is a fairly well supported pattern:
https://developers.cloudflare.com/workers/runtime-apis/html-rewriter/#async-handlers
This will cause a minor slowdown when things aren't cached, but I think well worth it for discovery purposes.
Touches main serving.
```
npx wrangler preview --watch --env ray
```
Verified page source to see the right tags populated for
* …
=> [C-2941] Modify cloudflare worker to pull in SEO data from discovery nodes

packages/web/scripts/workers-site/index.js
Worker is fetching playlist via resolve url and that is failing for
https://discoveryprovider.staging.audius.co/v1/resolve?url=/ray/playlist/creative-playlist
and
https://discoveryprovider.staging.audius.co/v1/playlists/by_permalink/ray/creative-playlist
with empty data.
Add some safeguards. Also use the dot to prevent title whiplash b/c helmet uses the dot in the <title>
```
npm run build:stage
npx wrangler preview --watch --env staging
``` …
=> Fix broken playlist fetch via resolve

packages/mobile/src/components/image/CollectionImage.tsx, packages/mobile/src/components/image/TrackImage.tsx, packages/mobile/src/components/share-drawer/ShareToStorySticker.tsx, packages/mobile/src/hooks/useContentNodeImage.ts, packages/web/src/common/store/cache/collections/utils/optimisticUpdateCollection.ts, packages/web/src/common/store/cache/tracks/sagas.js
Before this PR, edits to tracks and playlists would result in the `cover_image_sizes` prop on the entity being set to the local URL of the file (eg. blob:// or file://). This was so that we could load the image optimistically on mobile. However, the downside was that the local URL would also get written on a subsequent update to the track and break the cover art.
This changes makes it so that we never touch the `cover_art_sizes` field, even on mobile, and updates mobile to check for overrides in `_cover_art_sizes` instead for optimistic updates.
=> Preserve CIDs for track and collection cover arts

packages/common/src/services/audius-backend/solana.ts, packages/common/src/store/buy-usdc/sagas.ts, packages/common/src/store/buy-usdc/slice.ts, packages/common/src/store/purchase-content/index.ts, packages/common/src/store/purchase-content/sagas.ts, packages/common/src/store/purchase-content/slice.ts, packages/common/src/store/purchase-content/utils.ts, packages/common/src/store/ui/buy-audio/slice.ts, packages/common/src/store/ui/stripe-modal/sagas.ts, packages/common/src/store/ui/stripe-modal/slice.ts, packages/common/src/store/ui/stripe-modal/types.ts, packages/web/src/components/buy-audio-modal/components/CoinbaseBuyAudioButton.tsx, packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx, packages/web/src/components/data-entry/HelperText.tsx, packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.module.css, packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.tsx, packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx, packages/web/src/store/application/ui/buy-audio/sagas.ts, packages/web/src/utils/theme/dark.ts, packages/web/src/utils/theme/matrix.ts
* Renamed actions to be less callback-like
* Handling onramp cancelation correctly
* Handling error cases so we don't get stuck in "Purchasing"
None
Verified locally against staging with Chrome
N/A
Experience is behind the usdc feature flag
=> [PAY-1629] Purchase flow cleanup

packages/web/src/common/store/pages/collection/lineups/sagas.js
Small change to fix how we process falling back to the time from metadata_time of a track.
Was causing an issue when a track had a metadata_time of 0
N/A
N/A
N/A
N/A
=> Change nullish check to falsey check for collection track times

packages/common/src/store/purchase-content/utils.ts, packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSummaryTable.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseSummaryTable.tsx
Moved some of the util fns in `web` over to `common` and used them to calculate `existingBalance`/`amountDue` for the `PurchaseSummaryTable`.
Confirmed web behavior is correct.
=> [PAY-1588] Use existing balance in purchase flow on mobile

packages/web/src/components/Icon/Icon.tsx, packages/web/src/components/form-fields/DropdownField.tsx, packages/web/src/components/form-fields/SwitchField.tsx, packages/web/src/components/form-fields/TextField.tsx, packages/web/src/components/upload/UploadArtwork.d.ts, packages/web/src/components/upload/UploadArtwork.js, packages/web/src/pages/upload-page/fields/SelectGenreField.tsx, packages/web/src/pages/upload-page/fields/SelectMoodField.tsx, packages/web/src/pages/upload-page/fields/TrackMetadataFields.tsx, packages/web/src/pages/upload-page/fields/TrackNameField.tsx, packages/web/src/pages/upload-page/hooks.ts, packages/web/src/pages/upload-page/pages/CollectionTrackField.tsx, packages/web/src/pages/upload-page/pages/CollectionTrackFieldArray.tsx, packages/web/src/pages/upload-page/pages/UploadCollectionForm.module.css, packages/web/src/pages/upload-page/pages/UploadCollectionForm.tsx, packages/web/src/pages/upload-page/types.ts
Implements collection upload form using formik + beautiful-dnd
I would like to see if there is an easy way to animate out tracks that have been removed. Right now they just suddenly disappear.
=> [C-2685 C-2686] Implement collection upload form

packages/mobile/src/components/lineup-tile/LineupTile.tsx, packages/mobile/src/components/lineup-tile/LineupTilePremiumContentTypeTag.tsx, packages/mobile/src/components/lineup-tile/LineupTileStats.tsx, packages/mobile/src/components/lineup-tile/LineupTileTopRight.tsx
Moves the artist pick, hidden track tags from the top right to the middle left of the lineup track tile.
=> [PAY-1658] Artist pick, hidden track tile tags moved to mid-left

packages/embed/src/components/app.jsx, packages/embed/src/components/collection/CollectionHelmet.jsx, packages/embed/src/components/collection/CollectionPlayerCard.jsx
manually reverts the changes here: https://github.com/AudiusProject/audius-client/commit/121b054f58ee9f3c94dcc320da8239b88aa44253
since we're soon preparing for the launch of removing playlist ids from urls
=> [plat-1055] revert legacy playlist route formatting in embed player to use permalink

packages/common/src/store/pages/collection/actions.ts, packages/common/src/store/pages/collection/reducer.ts, packages/common/src/store/pages/collection/selectors.ts, packages/common/src/store/pages/collection/types.ts, packages/web/src/common/store/pages/collection/sagas.js, packages/web/src/pages/collection-page/CollectionPageProvider.tsx
slight refactor that we discussed where we can set the collection permalink in the state as part of fetch collection succeeded, instead of a separate action that has to be called in conjunction with fetch collection
=> Move setCollectionPermalink within fetchCollectionSucceeded action

packages/common/src/models/Analytics.ts, packages/common/src/store/upload/selectors.ts, packages/common/src/store/upload/types.ts, packages/web/src/pages/upload-page/UploadPageNew.tsx, packages/web/src/pages/upload-page/components/EditPageNew.tsx, packages/web/src/pages/upload-page/components/FinishPage.module.css, packages/web/src/pages/upload-page/components/FinishPageNew.tsx, packages/web/src/pages/upload-page/components/ShareBanner.module.css, packages/web/src/pages/upload-page/components/ShareBannerNew.tsx
Adding the new components for the upload finish page and update the new upload flow to upload the tracks and display the finish page
[Going to add a vid soon]
N/A
Lots of manual testing, lots more to come in the future
N/A
N/A
=> [C-2681, C-2682, C-2683] Add new upload finish page

packages/stems/src/components/HarmonyButton/BaseButton.module.css, packages/stems/src/components/HarmonyButton/BaseButton.tsx, packages/stems/src/components/HarmonyButton/HarmonyButton.module.css, packages/stems/src/components/HarmonyButton/HarmonyButton.stories.tsx, packages/stems/src/components/HarmonyButton/HarmonyButton.tsx, packages/stems/src/components/HarmonyButton/HarmonyPlainButton.module.css, packages/stems/src/components/HarmonyButton/HarmonyPlainButton.stories.tsx, packages/stems/src/components/HarmonyButton/HarmonyPlainButton.tsx, packages/stems/src/components/HarmonyButton/index.ts, packages/stems/src/components/HarmonyButton/types.ts
This adds a full implementation of the harmony PlainButton component, which was originally partially implemented as a variant of HarmonyButton.
* Moved non-styling functionality into a private `BaseButton` component.
* Updated HarmonyButton to layer its styling on top of the new base component
* Added `HarmonyPlainButton` component as a derived component implementing the new button type
Should be none
Locally verified in Storybook
N/A
N/A
Default Variant
---
Subdued Variant
---
Inverted Variant
=> [PAY-1720] Implements PlainButton

packages/web/scripts/workers-site/index.js
See this link:
https://audius.co/withoutmoralbeat/my-march-love-|-analog-trap-beat-160-bpm-377952
view-source:https://audius.co/withoutmoralbeat/my-march-love-%7C-analog-trap-beat-160-bpm-377952
Sitemap does uri encoding for us, so this will ensure things match.
https://discoveryprovider.audius.co/sitemaps/track/9.xml
While another option may be to make permalinks come back from the API as uri encoded, I believe that it is nicer to leave this up to developer or else our multilanguage permalinks will look extraordinarily bad in API responses.
Will ensure on stage via this track
https://staging.audius.co/ray65/%7C-%C3%B8%C7%83%C7%82%C7%86%C7%86%C7%86%CA%83%CA%84%CA%85%CA%86%CA%87%CA%88%CA%89%CA%8A%CA%8B%CA%8C%CA%8D%CA%8E%CA%8F%CA%90%CA%91%CA%92%CA%93%CA%94%CA%95%CA%96%CA%97%CA%98%CA%99%CA%9A …
=> [C-2964] Cannonical URL should be uri encoded

packages/common/src/models/Collection.ts, packages/mobile/src/utils/routes.tsx
mobile client is returning the old style permalink still which is incorrect with what we have stored in our playlist routes table. this returns new permalinks
=> Fix mobile share of playlist permalink

packages/web/src/utils/route.ts
Just adding routes for now, will be used in follow-up PRs
None, these routes are currently not handled in the router.
Locally verified, 404s as expected
N/A
N/A
=> [PAY-1741] Add routes for transactional pages

packages/web/src/common/store/account/sagas.js, packages/web/src/components/banner/Web3ErrorBanner.tsx, packages/web/src/hooks/useTabs/useTabs.tsx, packages/web/src/pages/sign-on/SignOnProvider.tsx, packages/web/src/pages/sign-on/components/desktop/SignOnPage.tsx
Drop `useMetaMask` local storage item when account fetch fails on web.
Address issue where a user may accidentally get halfway through the MetaMask flow, bail out, and then brick themselves from future sign up attempts.
1. Start MetaMask sign up flow
2. Verify useMetaMask set in local storage
3. Exit sign up, refresh, watch it get removed
=> [PAY-1742] Remove useMetaMask on invalid account

packages/web/src/components/collection/desktop/OwnerActionButtons.tsx, packages/web/src/components/collection/desktop/ShareButton.tsx, packages/web/src/components/collection/desktop/ViewerActionButtons.tsx
Fixes issue where viewers of a private collection can repost/favorite/share.
=> [C-2968] Fix private collection action buttons

packages/mobile/src/components/action-drawer/ActionDrawer.tsx, packages/mobile/src/components/drawer/Drawer.tsx, packages/mobile/src/components/share-drawer/ShareDrawer.tsx, packages/mobile/src/components/share-drawer/useShareToStory.tsx
Bug: share to X sticker (square with track/artist info) would not show up sometimes
This was a doozy
- Keep Share Drawer open while story being generated
- Since the share drawer would close right after the button was clicked, the sticker component would occasionally unmount  before the capture was taken 
-  Note: I tried to move the sticker component out to both the App level and the on progress drawer, but this did not work after hours of trying for various reasons 💀. Can try again another time - I think the drawer thing is an OK solution for now. 
- Fixing this issue now allows us to compute dominant colors and take the screenshot concurrently for perf win
On Android device
https://github.com/AudiusProject/audius-client/assets/36916764/bef2bfe1-7fe0-4724-8cfd-0bfe2ce9b01d
=> Fix Share to IG/T/S sticker consistency [C-3009]

packages/web/src/components/data-entry/DropdownInput.js, packages/web/src/components/data-entry/DropdownInput.module.css, packages/web/src/components/form-fields/ArtworkField.module.css, packages/web/src/components/form-fields/ArtworkField.tsx, packages/web/src/components/layout/layout.module.css, packages/web/src/pages/upload-page/UploadPageNew.tsx, packages/web/src/pages/upload-page/fields/TrackMetadataFields.module.css, packages/web/src/pages/upload-page/fields/TrackMetadataFields.tsx, packages/web/src/pages/upload-page/forms/EditTrackForm.module.css, packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
- Fix tag field wrapping
- Move description below art
- Make dropdown arrows clickable
_Note:_
The metadata inputs are currently 50px height but should be 60px to match designs. Currently, this results in too much gap between the fields.
Local web
=> [C-3006][C-3005] Fix tag field wrapping

packages/web/src/pages/upload-page/fields/CollectionTrackField.tsx, packages/web/src/pages/upload-page/fields/CollectionTrackFieldArray.tsx
Disable the delete button on the last remaining track in new collection upload flow
=> [C-2997] Disable delete on the last collection upload track

packages/stems/src/components/HarmonyButton/HarmonyButton.tsx, packages/stems/src/components/HarmonyButton/types.ts, packages/web/src/components/data-entry/TextAreaV2.module.css, packages/web/src/components/upload/TrackPreviewNew.tsx, packages/web/src/pages/upload-page/components/FinishPageNew.tsx, packages/web/src/pages/upload-page/fields/CollectionTrackField.module.css, packages/web/src/pages/upload-page/fields/CollectionTrackField.tsx, packages/web/src/pages/upload-page/fields/TrackMetadataFields.tsx, packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx, packages/web/src/pages/upload-page/forms/EditTrackForm.module.css, packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
- Fixes description limit location
- Migrate to plain button
Local web
=> [C-3018][C-2965] fix upload album/playlist description field styling

packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
Fixes issue where user is unable to play tracks coming from search page. This is due to a race condition where we fetch a tracks remixes and stems before the track itself, causing cases where remix values return and update the track entry before it even exists.
By moving these fetches to after the track is fetched, like we do with `fetchTrackBySlugAndHandle`, it works as expected.
searching and going to https://audius.co/russdiemon/freed-up-107829 works on mobile.
=> [C-3025] Fix race-condition with stem/remix fetch

packages/web/src/pages/upload-page/fields/availability/UsdcPurchaseFields.tsx
- Fixes https://audius.sentry.io/issues/4435303651/?project=1851611
- adds leading 0 on blur ($`.45` => $`0.45`)
local web
=> [C-3020] Fix errors in usdc purchase field

packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx, packages/mobile/src/components/share-drawer/ShareDrawer.tsx
Fixes issue where sharing to DM from the now-playing drawer does not close the drawer, leading to a funky user state.
Tested on local ios
https://github.com/AudiusProject/audius-client/assets/8230000/975dbf00-db2f-4ad6-a44a-89733518f6c0
=> [C-3026] Close now-playing when sharing to dm

packages/web/src/services/audius-backend/Jupiter.ts, packages/web/src/services/solana/WithdrawUSDC.ts
Importing Jupiter in the new workspaces setup throws a `Buffer is not defined` error at runtime. This seems to be bc Jupiter expects global `Buffer` to exist when it is imported, but bc of the workspaces change, Buffer doesn't exist until `index.tsx` is run. 
We really only need the string value of the enum so we can avoid importing Jupiter for now. The real fix will be to make webpack ProvidePlugin properly put Buffer into the global namespace
=> Fix jupiter Buffer is not defined

packages/common/src/models/Analytics.ts, packages/common/src/models/Track.ts, packages/common/src/store/lineup/actions.ts, packages/common/src/store/player/selectors.ts, packages/common/src/store/player/slice.ts, packages/common/src/store/queue/slice.ts, packages/web/src/common/store/lineup/sagas.js, packages/web/src/common/store/player/sagas.ts, packages/web/src/common/store/queue/sagas.ts, packages/web/src/components/track/GiantTrackTile.tsx, packages/web/src/components/track/desktop/ConnectedTrackTile.tsx, packages/web/src/pages/track-page/TrackPageProvider.tsx, packages/web/src/pages/track-page/components/desktop/TrackPage.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx, packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
This PR hooks up track previews for web and mobile web.
I added logic to the player saga to detect attempts to play tracks to which the user does not have access, switching to a preview instead if its available. This can be overridden by passing a boolean flag to the action. The previewing state is stored in the slice for retrieval later, which is helpful for determining the source of playback (full access of preview). I opted _not_ to use a new UID for this as it felt like it would have gotten quite complicated attempting to combine multiple sources (previewing from a lineup vs playing the same track from a lineup?). 
The TrackPageProvider is the only place that uses the boolean override, since we need to allow the track owner to preview the track.
The track page also makes use of the …
=> [PAY-1590] Hook up content previews for USDC content

packages/mobile/src/components/core/TextInput.tsx, packages/mobile/src/components/fields/TextField.tsx
Fixes issue where "demiBold" fontFamily leads to input text settling too high in it's container. this issue only exists on ios
Before: 
After:
=> Fix TextField input spacing

packages/web/src/components/search/SearchBar.js
Fixes issue where antd throws a warning about maxLength not working on a controlled input. This make sense since we are providing it `value`. I tested maxLength={2} just to see if it actually worked even with the warning and it didnt. The fix is to add our own maxLength check in the "onSearch" function to ensure users cant type more than 500 characters which i dont see why they would anyway, lol
=> Fix maxLength warning in search bar

packages/common/src/models/Track.ts, packages/common/src/utils/dogEarUtils.ts, packages/web/src/components/data-entry/AccessAndSaleModalLegacy.tsx, packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
Fixes release-blocking issue with access and sale modal.
Fixes
- Form was not able to be submitted when a validation error was present in other hidden fields
- Cleans form values when swapping between availability types
local web
=> Fix validation on access and sale modal

packages/common/src/models/Track.ts, packages/web/src/components/data-entry/AccessAndSaleModalLegacy.tsx, packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
Revert change to use `{}` instead of `null` for empty `premium_conditions`
local web
=> Revert premium_conditions empty object change

packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx
When deleting a track other than the selected track, the form got into a bad state where the selected index could be the deleted track. This was happening because the onClick for the row to select the track as active was also being activated when clicking the delete icon.
Stop propagation on the onClick for remove track so we don't also set the selected index to the track to be deleted.
- removes the deleted track from the tracks list
- fix bug in selected index calculation after deletion
local web
=> [C-3022] Fix broken multi-track index after deleting

packages/web/src/components/modal-radio/ModalRadioItem.tsx, packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
Add hint to modal radio item and then add the no collectible hint text in access and sale modal
=> [C-2995] Add hint to modal radio items

packages/web/src/pages/track-page/TrackPageProvider.tsx
We're using the preview boolean to determine which button was clicked on the track details page, but it wasn't being default initialized, so we were comparing `undefined === false`. 
Chrome on desktop
N/A
=> [PAY-1776] Fix playing check for track page

packages/web/src/components/data-entry/InputV2.tsx, packages/web/src/pages/upload-page/fields/availability/UsdcPurchaseFields.module.css, packages/web/src/pages/upload-page/fields/availability/UsdcPurchaseFields.tsx
Make the inputs white so they don't look disabled
=> [C-3028] make the usdc inputs white

packages/common/src/store/upload/selectors.ts, packages/web/src/pages/upload-page/UploadPageNew.tsx
Add a new selector for shouldReset and add effect in the new upload flow to listen for it and reset the state
[reset upload flow image here]
=> [C-3017] Reset the new upload flow state when the upload button in the side nav is clicked

packages/common/src/models/Analytics.ts, packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSuccess.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.tsx
Updates copy for twitter share buttons on purchase content modal/drawer (both web and mobile)
Tested local web stage (did not test ios yet - will do!)
=> [PAY-1723] Purchase content twitter share copy

packages/web/src/components/navigation-prompt/NavigationPrompt.module.css, packages/web/src/components/navigation-prompt/NavigationPrompt.tsx, packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
Adds a warning before navigating away if the form has any changed values.
Does not trigger on form submission or on the screen's back button.
*Note: Currently, this only blocks navigation within the app. Refreshing the page or navigating away via the address bar does not trip the condition.*
=> [C-3014] Add prompt on leaving upload form in progress

packages/web/src/services/solana/WithdrawUSDC.ts, packages/web/src/services/solana/solana.ts, packages/web/src/store/application/ui/buy-audio/sagas.ts, packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Final step of withdraw USDC flow - transfer to a destination account.
Works even if destination account has not been funded (but swap for sol flow doesn't work yet - solana wallet needs to be prefunded)
Example txs:
https://solscan.io/tx/3q1SofTyHpD1YzGGy9B2h63jCCpSFRxzcJyTaMGU1E3wvdbKzAkSutqj7v5kTATP8vdjqshZbND6JZg3eBi9V9Bc
https://solscan.io/tx/46uB41vDt3tFWUXnooyeyfsB4FCPHWVcmW3tqpbJyVJCj3qRvR5cPiknpnuKRjNUYEBf19S982pYcSdXzXj67kBv
=> [PAY-1791] Withdraw USDC - transfer to dest account

packages/common/src/models/Collection.ts, packages/common/src/models/Track.ts, packages/common/src/store/cache/reducer.ts, packages/mobile/src/store/offline-downloads/sagas/rehydrateOfflineDataSaga.ts
Fixes issue where downloaded tracks have stale stats when user is online. This is because the downloaded track is populated in the cache, and then doesn't update until cache TTL. Added update where any track, collection, or user that enters the cache from offline data has a `local` flag on it so the cache knows to flush it next time it's requested. We do the same thing for local account user.
=> [C-3035] Stale stats for offline tracks

packages/common/src/store/pages/collection/actions.ts, packages/common/src/store/pages/collection/selectors.ts, packages/mobile/src/components/navigation-container/NavigationContainer.tsx, packages/mobile/src/screens/app-screen/AppTabScreen.tsx, packages/mobile/src/screens/collection-screen/CollectionScreen.tsx, packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx, packages/mobile/src/screens/smart-collection-screen/SmartCollectionScreen.tsx, packages/web/src/common/store/pages/collection/sagas.js, packages/web/src/common/store/smart-collection/sagas.ts, packages/web/src/pages/collection-page/CollectionPage.tsx, packages/web/src/pages/collection-page/CollectionPageProvider.tsx, packages/web/src/utils/route/collectionRouteParser.ts
Fixes issues with collection fetching where mobile/web smart/not-smart collection pages all implement their own behavior for fetching collection metadata and fetching collection tracks. This PR merges all those paths, which in turn fix multiple issues:
1. Fixes mobile collection deep links
2. Fixes offline-mode collection loading
3. Fixes cases where smart collections sometimes would not fetch their tracks on mobile and web
4. Fixes duplicate fetch on mobile
Tested deep links for mobile and web, and tested navigating to and between collections on mobile and web. Tested that offline mode works
=> [C-2950 C-3033] Fix and simplify issues resulting from collection fetching

packages/web/src/components/stat-banner/StatBanner.tsx
Fixes issue where share button in desktop stats banner was missing share icon
=> [C-3039] Add icon to profile share button

packages/web/src/components/form-fields/ArtworkField.tsx, packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx, packages/web/src/pages/upload-page/fields/TrackMetadataFields.module.css, packages/web/src/pages/upload-page/fields/TrackMetadataFields.tsx, packages/web/src/pages/upload-page/forms/EditTrackForm.tsx, packages/web/src/pages/upload-page/validation.ts
- Waits until form is submitted before showing errors
- Adds artwork error display
- Improves alignment in the TrackMetadataFields to accommodate artwork error
local web
=> [C-2976] Fix upload form validation timing and display

packages/web/src/common/store/lineup/sagas.js
`getToQueue` has code paths that can return `undefined`, so we need to guard the check against `uid` for the new preview functionality
I am unable to reproduce the original crash, but will do coordinated testing with somebody who can.
=> Add guard to prevent attempted read of undefined queue items

packages/web/src/services/solana/WithdrawUSDC.ts, packages/web/src/services/solana/solana.ts, packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Check for existing SOL in root solana account that can be used to fund destination token account.
Also maintains minimum balance in root solana account for rent.
Bonus - fix a small bug: was using `TOKEN_LISTING_MAP.usdc` instead of `TOKEN_LISTING_MAP.USDC`.
Successfully created this token account without any swaps: https://solscan.io/account/3UV5mKKCDt6sPKi7RburgDfvrHtRKgrGmmdfbjggxNzL
=> [PAY-1793] Use existing SOL to fund dest ATA

packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
Fixes issue where artist-recommendation description does not wrap properly
=> [C-2924] Fix ArtistRecommendation description alignment

packages/web/src/services/solana/WithdrawUSDC.ts, packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
The two calls to `computeRoutes` were happening close enough together that Jupiter was caching the response, but for some reason the routes were empty in the cached response. Force-fetching fixes the bug.
Also includes some small cleanup.
=> Fix Jupiter caching bad route info

packages/common/src/store/ui/modals/createModal.ts, packages/common/src/store/ui/modals/withdraw-usdc-modal/index.ts, packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx, packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx, packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.tsx, packages/web/src/components/withdraw-usdc-modal/components/TransferInProgress.tsx, packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx, packages/web/src/pages/upload-page/fields/availability/UsdcPurchaseFields.tsx, packages/web/src/utils/tokenInput.ts
Add formik, zod, and proper inputs to USDC withdrawal modal
* Add error states to inputs (see screenshot)
* Break upload flow input helpers into a separate util
* Add `setData` method to `createModal` so the modal pages can use the shared modal state to manage internal pages
Local vs. staging, all the way up to the submit
=> [PAY-1792] Add formik, zod, and proper inputs to USDC withdrawal modal

packages/web/src/pages/upload-page/UploadPageNew.tsx, packages/web/src/pages/upload-page/fields/CollectionTrackField.tsx, packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx, packages/web/src/pages/upload-page/forms/EditTrackForm.tsx, packages/web/src/pages/upload-page/pages/EditPage.tsx, packages/web/src/pages/upload-page/utils/uploadPreviewContext.tsx
Add a new context for previews in the upload page and hook up the buttons in the edit track and collection forms
[image of the sound waves being produced in my headphones now]
=> [C-3044] Add preview functionality to new upload flow

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/store/notifications/types.ts, packages/mobile/src/screens/notifications-screen/Notifications/USDCPurchaseSellerNotification.tsx, packages/web/src/components/notification/Notification/USDCPurchaseSellerNotification.tsx
Needed to use diff formatting function since amount comes back as usdc wei.
Web and mobile on stage.
before:
after:
=> [PAY-1725] Display proper amount in track sold notification

packages/web/src/components/dynamic-image/DynamicImage.tsx, packages/web/src/components/play-bar/desktop/components/PlayingTrackInfo.tsx, packages/web/src/pages/artist-dashboard-page/components/ArtistCard.module.css, packages/web/src/pages/artist-dashboard-page/components/ArtistCard.tsx
* Dashboard didn't have background color set
* Now playing bar setting was removing the background on `moveBehind` in dynamic image. When we switch images in DynamicImage, remove the background color prop first before setting it to what we want.
Probably should refactor this whole beast a bit at some point, but these changes at least are consistent w/ current patterns.
Locally vs. staging -- played a few diff tracks on trending & tested /dashboard
=> [PAY-1811] Fix default/empty profile picture in now playing bar/dashboard

packages/web/src/pages/artist-dashboard-page/components/USDCCard.tsx, packages/web/src/pages/artist-dashboard-page/store/sagas.ts, packages/web/src/pages/purchases-and-sales/PurchasesPage.tsx, packages/web/src/pages/purchases-and-sales/PurchasesTable.tsx, packages/web/src/pages/purchases-and-sales/SalesTable.tsx, packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
This implements the links from the Artist Dashboard and Settings pages to the purchases/sales/withdrawals page.
There will be a follow up PR to implement the withdrawals page after this one is merged.
Also a quick detour to fix a crash when navigating away from the artist dashboard. A bad type causes us to attempt to yield on a channel and then call close on the result, instead of just closing the channel.
Tested locally against staging
=> [PAY-1763][PAY-1810] Wire up links to Purchases/Sales pages

packages/common/src/store/ui/withdraw-usdc/slice.ts, packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx, packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx, packages/web/src/components/withdraw-usdc-modal/components/TransferInProgress.tsx, packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx, packages/web/src/pages/upload-page/fields/availability/UsdcPurchaseFields.tsx, packages/web/src/store/application/ui/withdraw-usdc/sagas.ts, packages/web/src/utils/tokenInput.ts
Wires up withdraw USDC saga to modal state so it switches modal state when the withdrawal is successful.
=> Wire up withdraw USDC saga to modal state

packages/common/src/hooks/useUSDCBalance.ts, packages/common/src/store/purchase-content/utils.ts, packages/common/src/store/wallet/selectors.ts, packages/common/src/store/wallet/slice.ts, packages/common/src/utils/wallet.ts, packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.tsx, packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx, packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.tsx, packages/web/src/components/withdraw-usdc-modal/components/TransferInProgress.tsx, packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx, packages/web/src/pages/artist-dashboard-page/components/USDCCard.tsx
Store USDC balances in common slice so that it stays fresh when updated from misc. usage of `useUSDCBalance`
Issue:
1. User with balance 100 withdraws 5
2. Withdrawal modal UI shows 95, but dashboard page shows 100 still
I think I like this pattern more than polling for balance refresh every 1s.
Locally vs. staging. Tested via withdrawal flow.
=> [PAY-1814] Store USDC balances in wallet slice

packages/web/src/pages/upload-page/UploadPageNew.tsx, packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
* Added a useUnmount hook to the edit page to reset the track metadata index
* updated some check for upload type to handle 0 bc its an enum
[image of the page not being empty]
=> [C-3049] Fix upload type error where upload type is undefined

package.json
With the npm workspaces usage, we need to pass the `--deep` flag for npm-check-updates in order to get all of the nested `package.json` files.
=> Fix sdk:update command after node migration

packages/web/src/pages/saved-page/SavedPageProvider.tsx
Fixes silly bug where we were not setting the correct query-param when filtering a track table based on "dateAdded" and "dateSaved"
=> [C-2548] Fix favorites table saved date filter

.circleci/src/commands/@mobile-commands.yml
Fixes a few more issues with solana-dapp-store ci
- Removes redundant checkout
- Fixes corepack enable, it needs to be installed to local directory otherwise complains about permissions
- Also need to symlink react-native like other android builds.
- Removes nvm references since we are all on same version of node 18
=> Fixes solana-dapp-store ci with new node

packages/web/src/common/store/pages/trending-playlists/lineups/sagas.ts
For some reason, limit is 3 and we are not getting enough playlists back, maybe due to some bug in the lineup.
Setting the limit to 10 so we at least get enough playlists back from first fetch for now.
local web dapp vs prod
=> [PAY-1833] Increase trending playlists fetch limit
