AudiusProject/audius-client

- package.json
n/a
The path to the script `configureLocalEnv` was not correct in package.json 
n/a
run `npm run configure-local-env`
> Fix config local env script path

- src/containers/notification/store/sagas.ts
- src/services/AudiusBackend.js
https://trello.com/c/hy9V9hZ3/1489-notification-badge-regression-no-longer-clears-on-app-opening-if-theres-nothing-see-attached-video
On app load, call clear badge count via the react native action and to the identity service. 
no
I need to test this on the bounce app post merge, but what I did test that w/out the NATIVE_MOBILE (so on desktop), that the app did call the identity endpoint to clear badges on load. 
Post merge: Test that on app load the badges clear out.
> Call clear notification badges on native app init

- src/containers/notification/store/sagas.ts
- src/services/native-mobile-interface/types.ts
https://trello.com/c/hy9V9hZ3/1489-notification-badge-regression-no-longer-clears-on-app-opening-if-theres-nothing-see-attached-video
Adds a saga listener for the app enter foreground action to clear the notification badge count
no
I manually dispatched actions in the dapp to check that the saga takeEvery was being run. 
This will be testing on audius bounce where there are real notification & messages are passed from the react-native layer.
> Clear badge count on load on App foreground

- package-lock.json
- package.json
- src/__mocks__/Hashids.js
- src/__mocks__/hashids.js
- src/containers/App.js
- src/containers/collection-page/CollectionPageProvider.tsx
- src/containers/collection-page/store/sagas.js
- src/containers/profile-page/ProfilePageProvider.tsx
- src/containers/profile-page/store/actions.js
- src/containers/profile-page/store/reducer.js
- src/containers/profile-page/store/sagas.js
- src/containers/remix-settings-modal/store/sagas.ts
- src/containers/track-page/TrackPageProvider.tsx
- src/containers/track-page/store/actions.js
- src/containers/track-page/store/lineups/tracks/sagas.js
- src/containers/track-page/store/sagas.js
- src/setupTests.js
- src/utils/route.js
- src/utils/route/collectionRouteParser.test.js
- src/utils/route/collectionRouteParser.ts
- src/utils/route/hashIds.test.js
- src/utils/route/hashIds.ts
- src/utils/route/trackRouteParser.test.js
- src/utils/route/trackRouteParser.ts
- src/utils/route/userRouteParser.test.js
- src/utils/route/userRouteParser.ts
https://trello.com/c/5Y8RA0Vm/1497-api-expose-audius-client-track-route-to-handle-opaque-ids
There's currently no way to go from API result => audius link. This PR adds support for 
/tracks/{hashid}
/users/{hashid}
/playlists/{hashid}
This touches page load for tracks, users, and playlists which is a BFD. I tried to be very thorough in testing and I will continue to do so, but extra care in review would be great.
New unit tests as well as manual testing (local pointed @staging): 
tracks
/tracks/DOg1D
- load track page with normal track route
- load track page with hashed track route
- …
> Support opaque id routes

- src/containers/collection-page/CollectionPageProvider.tsx
- src/containers/profile-page/ProfilePageProvider.tsx
- src/containers/track-page/TrackPageProvider.tsx
https://trello.com/c/YSw7Cbkg/1514-fix-fully-escaped-url-names
Playlists that have no real characters in the title, e.g. '///' get escaped down to '' in the route. We should check for null here instead of falsey.
n/a
http://localhost:3002/archangel/playlist/-9580
> Fix check for route names that have no real characters

- scripts/dist.js
n/a
If our notarization job fails, explicitly return exit code 1 so CircleCI knows the job failed.
Very dragon-less
This is untested.
> Exit dist.js with exit(1) if build notarization fails

- src/containers/discover-page/store/lineups/trending/reducer.js
- src/containers/favorites-page/store/sagas.ts
- src/containers/followers-page/store/sagas.ts
- src/containers/following-page/store/sagas.ts
- src/containers/profile-page/store/sagas.js
- src/containers/reposts-page/store/sagas.ts
- src/containers/user-list/utils.ts
- src/services/audius-api-client/AudiusAPIClient.ts
- src/services/audius-api-client/ResponseAdapter.ts
- src/utils/route/hashIds.ts
https://www.notion.so/audiusproject/Porting-Client-to-API-9beefcc007ff4242be96124874606227
`/users/<id>/following` & `/users/<id>/followers`
Updates the get user following and get user follows endpoint to use the new api DP v1 api
This shouldn't be merged until DP is merged
I ran this locally against a local DP pointed at a prod DB snapshot. and loaded the user followers and following modals from the user page on the desktop.
> Add DP v1 api user follows/following

- src/containers/remixes-page/store/lineups/tracks/sagas.ts
- src/models/Track.ts
- src/services/AudiusBackend.js
- src/services/audius-api-client/AudiusAPIClient.ts
- src/services/audius-api-client/ResponseAdapter.ts
- src/services/audius-api-client/types.ts
- src/store/cache/tracks/sagas.js
- src/store/cache/tracks/utils/fetchAndProcessRemixes.ts
- src/store/cache/tracks/utils/fetchAndProcessStems.ts
- src/store/cache/tracks/utils/helpers.ts
- src/store/cache/tracks/utils/processAndCacheTracks.ts
- src/store/cache/tracks/utils/retrieveTracks.ts
https://trello.com/c/A7BOsv5J
Consume stems, remixes, remixing endpoints. 
None
Tested on remix pages, tracks with stems.
> Consume Remixes + Stems API Endpoints

- src/services/AudiusBackend.js
- src/services/audius-backend/eagerLoadUtils.ts
This fixes two bugs we've actually had for a while:
* direct linking into /history fails because we don't wait for libs init
* eager load util straight up had a bug where it was not using a full URL if url params were passed in. this led to visiting /profile and looking at their reposts, you'd actually just see YOUR feed. 
nah
Manually by running the dapp
> hotfix 10 9 bugfix

- src/containers/profile-page/store/lineups/tracks/sagas.js
- src/models/Collection.ts
- src/models/Track.ts
- src/services/audius-api-client/AudiusAPIClient.ts
- src/services/audius-api-client/ResponseAdapter.ts
- src/services/audius-api-client/types.ts
- src/store/cache/reducer.js
Fixes two bugs:
- DP returns 404 for deleted content, breaking profile pages
- User profile updates will flicker back and forth between old and new on profile page refresh because we load outdated cached users from tracks. This change won't cache any object with an outdated blocknumber
**Yes** This touches cache code.
Tested locally, ensured that user flickering disappeared, ensured that 404s don't break track pages anymore.
> Fix API 404 handling and storing outdated data

- src/services/AudiusBackend.js
- src/store/cache/collections/sagas.js
na
The old DP api returns the playlist fields `playlist_image_multihash` and `playlist_image_sizes_multihash` instead of `cover_art` and `cover_art_sizes` respectively returned from the v1 API. 
Since the collections saga func watchFetchCoverArt was updated to only look for the new fields, I added a mapping in the audiusBackend instead of updating the `watchFetchCoverArt` function to handle both fields for redux store consistency, but I could see the argument to also add the check in watchFetchCoverArt. lmk what you guys think.  
Also fix the confirmer comparing against the correct image field. 
no …
> Fix legacy playlist cover art fields

- src/components/artist/UserListModal.module.css
- src/components/artist/mobile/UserListModal.module.css
- src/components/dynamic-image/DynamicImage.tsx
- src/components/track/desktop/ConnectedPlaylistTile.module.css
- src/containers/discover-page/components/desktop/GenreSelectionModal.module.css
- src/containers/service-selection/ServiceSelectionModal.module.css
- src/containers/upload-page/components/TracksPreview.module.css
- src/containers/user-list-modal/components/UserListModal.module.css
- src/services/audius-api-client/AudiusAPIClient.ts
https://trello.com/c/inyb5DjL/1609-fix-full-models-to-include-signatures-remove-sigs-from-health-check
Switches from `fetch` to libs' `axios` make request after eager initial load
impacts everything *after* initial load
manually ran dapp against staging. verified that libs is invoked, but requests are the same!
> Use libs discprov makeRequest when available

- src/containers/notification/store/sagas.ts
na
If a user has no notification, it's left in a spinning state forever b/c the status is never set to success. 
no
ran it locally against a new account w/ no notifs and an old account w/ notifs
> Fix loading on notifications when empty

- src/store/cache/users/selectors.ts
https://audius.co/DJRROS3
Links with non-case-sensitivity in handles are broken. We always cache handles as lowercase
```
handleStatuses[status.handle.toLowerCase()] = {
id: status.id,
status: status.status
}
```
So we've probably had some bugs from this for a while
verified fetching both http://localhost:3002/DJRROS3 and http://localhost:3002/djrros3 work
> Fix handle case sensitivity

- package-lock.json
- package.json
- src/components/preload-image/PreloadImage.module.css
- src/components/preload-image/PreloadImage.tsx
- src/containers/App.js
- src/containers/artist-dashboard-page/ArtistDashboardPage.module.css
- src/containers/artist-dashboard-page/Tiles.module.css
- src/containers/artist-dashboard-page/Tiles.tsx
- src/containers/artist-dashboard-page/components/ArtistProfile.module.css
- src/containers/artist-dashboard-page/components/SendInputBody.module.css
- src/containers/artist-dashboard-page/components/SendInputBody.tsx
- src/containers/sign-on/components/desktop/EmailPage.js
- src/containers/sign-on/components/desktop/SignInPage.js
- src/containers/sign-on/components/desktop/SignOnPage.tsx
- src/containers/sign-on/components/mobile/InitialPage.tsx
- src/services/remote-config/Provider.ts
* Stops optimizely info logs on dev mode (I don't think we actively use them, but it's easy enough to re-enable)
* Switches around /signup lazy loading so we only lazy load the metamask component (which requires libs content). This makes first load on audius.co/signup a bit nicer
* Disables the send button if there's an error on the "send" wallet client
* Fixes dashboard on lower res displays
Pushed to joey.audius.co and played around sign up & dashboard
> UI Touchups

- src/containers/notification/store/sagas.ts
- src/services/remote-config/RemoteConfig.ts
- src/services/remote-config/defaults.ts
Sets notif polling interval to 60s, and uses remote config.
None
Tested locally, changed in optimizely
> Move notification polling interval to remote config

- public/index.html
- src/services/AudiusBackend.js
Attempts to address `this.web3.eth.Contract is not a constructor` error by having internal web3 stick a `web3Loaded` flag on the window, and testing for that in backend setup, rather than the existence of window.Web3.
Nah
Tested locally
> Fix web3 race

- src/containers/artist-dashboard-page/ArtistDashboardPage.tsx
- src/containers/artist-dashboard-page/store/sagas.js
- src/store/cache/collections/sagas.js
- src/store/cache/tracks/sagas.js
- src/store/cache/users/sagas.js
1 - creating a playlist + adding a track to the playlist before the confirmer happens, ends up leading to a playlist half-created state. what happens is the playlist gets moved, and between the next confirmation adding a new track to the playlist, the image reloads and uses a selector to fetch a version of the playlist that should get cached with fresher data later. Changed user and track image fetch for posterity, but I don't think these manifest with bugs.
2 - requires sign in for /dashboard
> Minor ui fixes

- package-lock.json
- package.json
- src/containers/service-selection/store/sagas.ts
- src/services/AudiusBackend.js
- src/services/analytics.ts
Adds analytics for creator node selection. Eventually this CB should be passed to libs rather than used as it is here.
Link to dash: https://analytics.amplitude.com/audius/chart/ivqnd9r
Ran against staging and prod & verified trigger of event on new creator & switching cns as old creator
> Track creator node selection

- src/components/data-entry/Input.module.css
I believe this bug has been around for forever (or browsers changed how they do things, which I doubt).
https://github.com/AudiusProject/audius-client-old/commit/8f57bd28309630b6410f87fd95269d60db69834d#diff-081e9cd26dc46773db656642905fae33c5851bdb37c4b4ec38ea416c0b7c41ecR38
This PR added (I think erroneously) a background color to disabled placeholders, which actually show on top of handles (placeholder being the elevated "handle" here)
This manifests as a "bug" where artists coming in who are verified on twitter, prepopulate their sign on form, and aren't allowed to change their handle (input disabled). So it displays weirdly and they back out and try again (sometimes even giving up) which does write to identity & generates a lot of noise
Is there anything the reviewer should be on the …
> Fix input bg

- package-lock.json
- package.json
- src/components/track/mobile/TrackTile.tsx
https://trello.com/c/F4sWZtX0/1643-0-play-counts-in-reposts-tab
Hides plays when 0 on mobile to replicate desktop behavior. The real bug is that get_repost_feed_for_user.py doesn't call populate track metadata in discprov, so it doesn't contain all the data we want.
Dapp locally against prod
> Hide 0 plays on mobile just like desktop

- src/components/general/Modal.js
- src/components/source-files-modal/SourceFilesModal.module.css
- src/components/track/EditTrackModal.js
https://trello.com/c/Bsd1cdey/1657-fix-dropdown-modal-zindex-clash
Fixes dropdown showing behind modal (on edit track modal)
Just touches edit track, but is a modal thing
> Fix dropdown placement

- src/containers/profile-page/store/sagas.js
- src/store/cache/collections/sagas.js
- src/store/cache/tracks/sagas.js
https://trello.com/c/cgHC2F4j/1658-handle-multiple-calls-to-upload-image-on-editing-profile-in-same-session-as-updating-profile-picture
Fun little bug where if you update an image on a user/track/collection, save the update, and then go update it again, we re upload the image because it's still attached to the cached metadata.  Whole thing deserves better typing.
Not really
Made sure subsequent edits of track/user/playlist don't send calls to image_upload
> Fix duplicate image uploads after first edit

- src/containers/upload-page/store/utils/processFiles.ts
Handle invalid mime type upfront.
We do this check on the creator node, but not on the client
https://github.com/AudiusProject/audius-protocol/blob/master/creator-node/src/fileManager.js#L22
If mime can't be determined, just allow it and let BE reject it.
Impacts all uploads
- Upload mp4 is rejected (mime: video/mp4)
- Uploaded mp3
- Uploaded flac
- Uploaded wav
- Uploaded aif
> Reject non audio mime upfront

- src/containers/deleted-page/components/desktop/DeletedPage.module.css
https://trello.com/c/LbfTvZCx/1666-line-wrapping-issue-on-soft-404-page
Don't wrap if the title is too long on deleted track pg
none
I ran the site locally against prod to use the deleted track noted in the trello card to confirm it doesn't wrap.
> Fix wrap on long title deleted track

- src/containers/saved-page/components/desktop/SavedPage.tsx
https://trello.com/c/9a8Ck7rc/1667-playlist-instead-of-the-album-in-overflow-menu-and-on-the-album-page-in-favorites-album
Fix text to say album instead of playlist by passing in correct prop
no
Ran it locally
> Fixes saved albums to have album label instead of playlist

- src/components/search/SearchBarResult.js
https://trello.com/c/RYLp0NUv/1668-autocomplete-search-tiles-briefly-show-as-square-for-users-and-then-transition-to-circles
Just made the user autocomplete img always be a circle and not wait for load. 
nope
Ran the client against staging and recorded the search autocomplete to ensure it was working properly
> Fix user search img to be circle always

- src/utils/gatewayUtil.js
https://trello.com/c/zzrS6SgS/1680-fix-broken-stream-bug-caused-by-invalid-cn-endpoint-race
Fixes bug in streaming where we end up fetching CIDs directly from audius.co/ (or rather "/") because an endpoint is configured incorrectly.
Should be fine.
Manually ran dapp & streamed a song (while manually setting a bad cn endpoint to be "creatornode.audius.co,"
> Filter out bad gateways

- .env/.env.prod
- src/services/AudiusBackend.js
- src/services/remote-config/RemoteConfig.ts
- src/services/remote-config/defaults.ts
https://trello.com/c/bTn3yiff/1678-add-libs-mechanism-to-select-cdn-eth-proxy-for-reads
Switches provider urls from alchemy to a generic eth.audius.co
Ping me so I can walk you through what eth.audius.co does :)
Impacts initial load (libs init)
Manually running client against production. No change to staging as of now.
> Add caching eth provider url endpoint

- src/components/track/desktop/ConnectedPlaylistTile.module.css
- src/components/track/desktop/TrackTile.tsx
- src/components/track/mobile/TrackTile.tsx
- src/store/cache/reducer.js
https://trello.com/c/ICmgtwgo/1694-tapping-icons-on-skeleton-tiles-causes-the-app-to-blow-up
https://trello.com/c/CtupFHiu/1699-fix-this-scroll-bar-issue-on-playlists-in-feed
https://trello.com/c/I64JDcQ0/1700-adding-same-song-2-times-to-one-playlist-then-removing-track-shows-all-instances-of-that-track-missing-on-the-ui-coming-to-revis
Fixes a few misc. small bugs (commit-by-commit).
One of the bugfixes touches the cache merging layer. This bug manifests when there are multiple tracks with the same id in the same playlist that are confirming (they have a UID assigned). The current merge method ends up coercing the tracks with the same id to have the same UID which makes removing one of them …
> Fix misc. bugs

- src/assets/img/iconGradientUpload.svg
- src/components/drawer/Drawer.module.css
- src/components/drawer/Drawer.tsx
- src/containers/App.js
- src/containers/mobile-upload-drawer/MobileUploadDrawer.module.css
- src/containers/mobile-upload-drawer/MobileUploadDrawer.tsx
- src/containers/mobile-upload-drawer/store/selectors.ts
- src/containers/mobile-upload-drawer/store/slice.ts
- src/containers/now-playing/NowPlayingDrawer.tsx
- src/containers/profile-page/components/mobile/ProfileHeader.tsx
- src/containers/profile-page/components/mobile/UploadButton.module.css
- src/containers/profile-page/components/mobile/UploadButton.tsx
- src/hooks/usePortal.ts
- src/store/reducers.js
- src/store/types.ts
https://trello.com/c/Clro3f9J/1692-upload-from-desktop-button-on-mobile
Add a button to your own profile page on mobile for upload. Clicking the button triggers a drawer to appear (copy pasta from now playing drawer) with a call to action to visit audius.co on web. Swipe down or tapping outside cause the drawer to dismiss.
Nope
Locally on mobile web + ngrok ios app.
> Mobile upload CTA button

- src/containers/profile-page/store/reducer.js
- src/containers/profile-page/store/sagas.js
https://trello.com/c/wNWX6xxN/1707-refresh-causes-the-page-content-to-disappear-on-profiles-video-link-in-description
Fix pull to refresh on profile pages on mobile. Currently it flashes an empty screen.
Breakage caused by https://github.com/AudiusProject/audius-client/commit/21766e952cc197f0753f2195bef4b5e72cc975b8
Because that PR added a line to allow fetching by user id rather than handle alone, fetching by handle alone unsets the user id and causes the profile page selector to think there was no page loaded at all.
n/a
* Ran local iOS app pointed at local build & verified the blank …
> Fix profile page pull to refresh

- src/containers/collection-page/CollectionPageProvider.tsx
https://trello.com/c/6wa2YJ7y
Reset race condition that would break deeplinking into collections on mobile. Solution is to reset on Collection page unmount, rather than during mount.
Probably not
Tested in simulator and browser, still trying to test on device...
> Fix deeplink into collection on mobile

- src/containers/nav/mobile/TopLevelPage.tsx
- src/hooks/useScrollLock.ts
https://trello.com/c/s04A5Jac
- Scrolling on edit playlist page was broken (would get stuck). Moved to using our native scroll lock solution to handle this instead of body-scroll-lock npm package.
- Improved useScrollLock ergonomics
None
Tested in iOS simulator safari
> Fix broken scroll on edit playlist mobile

- src/assets/img/iconGradientNotification.svg
- src/containers/App.js
- src/containers/enable-push-notifications-drawer/EnablePushNotificationsDrawer.module.css
- src/containers/enable-push-notifications-drawer/EnablePushNotificationsDrawer.tsx
- src/containers/enable-push-notifications-drawer/store/sagas.ts
- src/containers/enable-push-notifications-drawer/store/selectors.ts
- src/containers/enable-push-notifications-drawer/store/slice.ts
- src/containers/sign-on/components/mobile/SignOnPage.tsx
- src/services/native-mobile-interface/lifecycle.ts
- src/services/native-mobile-interface/types.ts
- src/store/account/sagas.js
- src/store/reducers.js
- src/store/sagas.js
- src/store/types.ts
https://trello.com/c/vWEe1wwb/1693-reminder-to-turn-on-notifications
Add a drawer that shows up every 10sessions (native mobile) to have a user turn on notifications if they've never been turned on or explicitly disabled. Also shows on native mobile sign in flow.
Tiny touch to sign in flow
Tests described on native mobile PR
> Enable notifications reminder

- src/containers/App.js
https://trello.com/c/Ubt497ux/1719-noticed-a-bug-on-mobile-i-dont-think-caused-by-anything-recently-but-if-you-try-typing-into-sign-in-immediately-after-the-app-lo
On native mobile, on load and the user is not signed in, the signin page will appear for a second then switch to the sign up page. 
What happening is that on load of the react native app, the webview is directed to http://localhost:3000. There is no route associated with this pathname, so the react router redirect is hit, pushing the /feed route. This is an authenticated route that can only load if the user is signed in. There is logic in /src/containers/App.js that checks for the page being unauthenticated and the user not being signed in and redirects to the /signin route. Additionally, there is a mobile only saga that is …
> Wrap redirect to signup on authenticated route only if non-native

- src/containers/track-page/store/retrieveTrending.ts
- src/containers/track-page/store/sagas.js
- src/services/audius-api-client/AudiusAPIClient.ts
na
FIxes the trending badge on the track page.
The error was that this [line in retrieveTrending](https://github.com/AudiusProject/audius-client/blob/079c4d34a2475f55a8bc8ffc850be679f3a16b9d/src/containers/track-page/store/retrieveTrending.ts#L60) was comparing null and undefined and thought that they were different genres. 
It now only expects a string or null so it can strictly compare the values. 
no
I ran the dapp locally against staging.
> Fix trending badge

- src/store/cache/collections/utils/addUsersFromCollections.ts
- src/store/cache/tracks/utils/helpers.ts
- src/store/cache/users/sagas.js
https://trello.com/c/HFeIWwAf
Profile completion meter broken for two reasons:
- Updates to profile weren't synced to local storage, so we could hit 5 followees but when we load up again, the old profile with 4th followees is cached
- Visiting your Profile Page loads the cached account user embedded into your tracks + collections into the redux store. This profile is potentially out of date from your local redux state, so you have a bug where you go follow the 5th person, confirm, go the profile page, add user with 4 follows into the store, write that out to local storage, and then reload and still see 4
- Cache changes
Tested locally with profile completion meter
> [AUD-13] Fix profile completion meter

- src/components/data-entry/FormTile.js
https://trello.com/c/hXkQmKzV/1740-editing-track-genre-broken-on-staging-because-of-modal-work
Fixes edit track dropdown by changing dropdown input to be parent mounted inside form tile. This allows "clickOutside" to work properly in the stems modal
n/a
Tested both edit track change genre as well as upload track change genre
> Dropdown fix

- src/audio/AudioStream.test.js
- src/audio/AudioStream.ts
- src/containers/now-playing/NowPlaying.tsx
- src/containers/play-bar/desktop/PlayBar.js
- src/containers/play-bar/mobile/PlayBar.tsx
- src/store/player/sagas.ts
- src/store/player/selectors.ts
- src/store/player/slice.ts
https://trello.com/c/dy9UrJ9J/1732-fix-bug-where-spinner-shows-on-track-tile-despite-playing
Track tiles can incorrectly show buffering because buffering state is is pulled directly off of the audio object vs. from a proper state mutation that triggers a re-render. Add buffering to the player state so that components can use selectors to pull buffering directly.
n/a
1. Updated unit test for the callback
2. Reproduced bug by playing tracks before they finish prefetching to trigger bad buffering state. Tested with bugfixes on web + mobile web.
> [AUD-14] Fix stale buffering state

- src/containers/track-page/store/actions.js
- src/containers/track-page/store/reducer.js
- src/containers/track-page/store/sagas.js
- src/containers/track-page/store/selectors.ts
- src/containers/track-page/store/types.ts
- src/services/audius-api-client/AudiusAPIClient.ts
- src/services/audius-api-client/ResponseAdapter.ts
Closes AUD-27
Updates the trending track badge on the track page to be sourced from the new DP endpoint - [created in this protocol pr](https://github.com/AudiusProject/audius-protocol/pull/1137)
Caches the trending tracks id results as to not make subsequent request on multiple track pages
no
I ran the client locally and hard coded the DP to be the locally running DP against a staging RDS instance.
> Update fetch trending track ids to updated endpoint

- package-lock.json
- package.json
- src/services/AudiusBackend.js
- src/services/wallet-client/WalletClient.ts
- src/store/wallet/sagas.ts
- src/store/wallet/slice.ts
Invalidates the cache after local state changes to claim amt and balance.
Currently the web3 provider can cache requests to your current balance and if we poll for your balance and get a cached value right after a local state change, the value can toggle back to what it was before your local state change.
The AudiusTokenClient .bustCache method invalidates the cache by adding a nonce query param -- this feature could be extended to the ContractClient.js class in libs at some point if we need this behavior more than for fetching balance
Nah
Ran against prod & issued a claim. Ensured that …
> [AUD-28] Bust web3 provider cache on balance of

- src/containers/track-page/store/sagas.js
- src/services/remote-config/RemoteConfig.ts
- src/services/remote-config/defaults.ts
na
Add back the old method for retrieving the trending track badge by calling the trending tracks endpoint. 
This is added behind an optimizely flag which defaults to the old method. 
Reference #154 for the changes to the updated endpoint.
no
I ran it against staging with the flag set to both true and false and saw the badge in both cases.
> Add optimizely for legacy track trending rank badge

- src/containers/sign-on/components/mobile/InitialPage.module.css
We had a weird fixed width that caused our inputs to bleed into the right side for sign up + sign in, on mobile
None
> [AUD-47] Fix offset sign up + sign in inputs on mobile

- src/containers/nav/desktop/NavColumn.js
- src/containers/now-playing/NowPlaying.tsx
- src/models/Track.ts
- src/store/application/ui/average-color/slice.ts
- src/store/cache/tracks/sagas.js
- src/store/reducers.js
- src/store/types.ts
Switching between tracks with the same artwork would cause the dropshadow to do an ugly flicker (highly visible here: https://audius.co/mrcarmack/album/blu-ep-154) because when we load the new track, we haven't calculated the averageRGB yet, so we briefly display the placeholder while calculating the new one.
This fix pulls the averageRGB info out of the track model and into a new redux slice that maps the image CID -> averageRGB to allow us to reuse the average color info for tracks with the same artwork.
Nah
Tested on desktop + mobile browser
> [AUD-54] Fix flickering drop shadow in nav column

- src/containers/settings-page/components/desktop/VerificationModal.module.css
Fixes a set value to verification modal width. Weird behavior where this looks fine locally, but not on a built version of the dapp
> Fix verification modal width

- src/services/AudiusBackend.js
- src/services/remote-config/RemoteConfig.ts
- src/services/remote-config/defaults.ts
Adds ability to use remote config to disallow clients from waiting for a particular content node to resolve. Discovery node needs more plumbing, unfortunately.
Nope
Ran against prod, manually blocked https://content-gru02.audius.hashbeam.com and made sure everything worked
> Add content node block list

- src/containers/saved-page/store/lineups/tracks/sagas.js
Closes AUD-55
Issue: When on the mobile favorites page, if you play a track, the lineup updates the queue. If you remove a track on the favorites page, it's removed from the queue as well and the Now Playing overlay uses the queue to display the track information, but since it's missing, it displays nothing. Note, at this point the player in redux still has the information so the track still plays. 
My solution was to do a simple check on un-save for if it's the currently playing track and if so, do not remove from queue. 
No
I ran the dapp on my browser with mobile width.
> Fix mobile saved page lineup - currently playing

- src/containers/profile-page/store/lineups/tracks/sagas.js
Closes AUD-113
If on the user profile page and a track is deleted, it should be removed from the page. 
nope
I ran the dapp locally against staging and removed a track on the profile page.
> Remove track from profile lineup when deleted

- src/containers/browser-push-confirmation-modal/BrowserPushConfirmationModal.tsx
Closes AUD-66
On sign-in and sign-up the user is presented a popup modal the asks if they want to turn on browser notifications. 
If the user is in incognito mode or if they have previously declined notifications and click turn on notifications, nothing happens. The modal only closes if the browser permissions are changed or they close close. 
This PR closes the modal on user action even if it doesn't succeed. 
no
I ran the dapp locally against staging and signed in on incognito and in normal browsing mode. I clicked enable notifications and expected it to always close.
> Close notification popup on user select

- package-lock.json
- package.json
- src/components/actions-tab/ActionsTab.js
- src/components/card/desktop/Card.tsx
- src/components/create-playlist/CreatePlaylistModal.js
- src/components/track/EditTrackModal.js
- src/containers/Modals.tsx
- src/containers/collection-page/CollectionPageProvider.tsx
- src/containers/collection-page/components/desktop/CollectionPage.tsx
- src/containers/edit-playlist/desktop/EditPlaylistModal.tsx
- src/containers/edit-track/EditTrackModal.tsx
- src/containers/menu/CollectionMenu.tsx
- src/store/application/ui/editPlaylistModal/selectors.ts
- src/store/application/ui/editPlaylistModal/slice.ts
- src/store/cache/collections/selectors.ts
- src/store/reducers.js
- src/store/types.ts
- src/utils/zIndex.ts
* Update stems from 0.3.2 -> 0.3.3
* Adds an Edit Playlist Modal component - it reuses the ui of the create playlist component, but is added at the root level to the Modals container. 
* Adds an edit playlist option to the dropdown of the playlist card.
* Updates the edit playlist modal in the playlist page to use the new component.
* Added a zIndex file to collect all z-indices used in the app. 
* Removed toggle key in edit track modal
Closes AUD-84
**Yes**: I updated stems from 0.3.2 -> 0.3.3 which has the modal style changes.
I played around with the modals and they seemed to be working fine.  …
> Fix edit playlist overflow

- src/containers/profile-page/store/sagas.js
Repeated updates to profile picture/cover photo end up erroneous because local state is not updated after the confirmer finishes.
1. Repeated full steps in AUD-126 description
2. Repeated minimal repro steps in AUD-126 description
3. Verified that multiple attempts to modify profile picture before the first attempt has been confirmed works as intended (both displaying the latest update as well as actually writing the correct metadata for the most recent update)
> [AUD-126] Fix failure to update photos on repeated changes

- src/containers/profile-page/store/lineups/feed/sagas.js
We weren't accounting for uncofirmed reposts on the profile page reposts lineup.
This is a linear scan that adds about 1ms to profile page load.
None
Tested locally
> [AUD-62] Fix unconfirmed reposted tracks not appearing on profile

- src/components/artist/ArtistPopover.tsx
- src/components/general/FollowButton.js
- src/containers/user-list/UserList.tsx
- Changes follow button to immediately show 'follow' after unfollowing, as per discussion w product and design
- Fixes unfollow from userlist broken on desktop
- Looks like we were missing unsubscribe when unfollow on a few buttons, following the behavior on mobile here. Not 100% sure this is necessary?
None
Locally
> [AUD-110] Fix Unfollow from Desktop User List

- src/containers/history-page/components/mobile/HistoryPage.tsx
Closes AUD-56
Bug: On the mobile listening history page, when you reposted a song, it would not show up as reposted. This was caused by a missing prop. 
Solution: add the isReposted prop!
no
Ran the dapp locally against staging w/ the desktop browser set to mobile width. Then went to the mobile listening history page and reposted a track and checked that it was reposted and the option said unrepost after.
> Fix tracklist missing prop on mobile history pg

- src/components/public-site/Footer.module.css
Fix the footer, it was previously wrapping the text on `Hot & New`
Updated footer in desktop and mobile
Closes AUD-49
no
I ran the dapp with these changes
> Fix styling on public site footer links

- src/components/create-playlist/CreatePlaylistModal.js
- src/containers/collection-page/CollectionPageProvider.tsx
- src/containers/edit-playlist/mobile/EditPlaylistPage.tsx
- src/containers/profile-page/components/desktop/ProfilePage.module.css
- src/store/cache/collections/sagas.js
Fixes a few playlist issues & can be reviewed commit by commit, but they were all discovered trying to fix AUD-26.
AUD-26 has more description about the actual bug that the last commit fixes. The gist was that our confirmation process for playlists was kind of broken.
Touches playlist creation flow. Worth serious QA.
On both desktop & mobile -- 
1. Created a playlist and waited for confirmation on the playlist page
2. Created a playlist from a track and waited for confirmation on the playlist page
3. Created a playlist, went to profile page and waited for confirmation
4. Created a …
> [AUD-26] Playlist fixes

- src/containers/sign-on/components/desktop/MetaMaskModal.js
- src/services/AudiusBackend.js
Fixes race condition on window.Web3 on initial load.
The reason this was happening is because the metamask sign in component was importing Utils directly from libs. Utils, in turn, imports libs/src/Web3.js which checks to see if Web3 is provided by the window or whether requiring it is necessary. In order to do that check in libs/src/Web3.js, Web3 must be already present on the window object. Since Web3 itself is lazy loaded in the client, directly importing Utils from libs is not safe.
Doing so through AudiusBackend as done in this PR is though because the correct ordering enforced --
1. Web3 is lazy loaded
2. Libs is lazy loaded
3. Metamask can use libs utils
n/a
Please describe the tests that …
> [AUD-118] Fix web3 race on mobile init

- src/containers/add-to-playlist/store/sagas.ts
Unfetched playlists do not show up in the edit playlist page.
n/a
* Added a track to a playlist on first load
* Added a track to a playlist after visiting profile and loading all my own playlists
> Fetch playlists on edit playlist page

- src/components/bottom-bar/BottomBar.module.css
- src/containers/nav/mobile/NavBar.module.css
A bug exists where you can lose the ability to scroll on the edit playlist page.
Really what this boils down to is you creating a scroll focus on the nav/play bar and scrolling accidentally (which triggers inertial scrolling on the window/document). If you then try to immediately scroll the edit playlist page, since the window/document hasn't lost scroll focus, you continue to scroll it. The user then gets frustrated and scrolls much more aggressively which creates more inertia and it takes a while to regain scroll focus where you want it.
Touch action none is supported pretty widely and from my testing I believe this prevents the issue:
https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action
Is there anything the reviewer should be on the lookout for? Are there any dangerous …
> [AUD-111] Prevent touch actions on nav and bottom bar

- src/containers/profile-page/ProfilePageProvider.tsx
- src/containers/profile-page/components/desktop/ProfileWrapping.js
- src/containers/profile-page/components/mobile/ProfileHeader.tsx
- src/utils/handleWhitelist.ts
Fixes instagram/twitter handles on profiles according to verif status
Nope
Visited these profile in prod context and made sure on both desktop & mobile the twitter/ig links are correct:
audius.co/miquela
audius.co/JodyBreeze
audius.co/masego
audius.co/rayjacobson
audius.co/riotmusic
Then, manually set AudiusBackend to tell us that my account was verified on both twitter & ig and made sure the links were right and i could not update my handles.
> [AUD-133] Fix instagram/twitter handles on profiles

- src/containers/App.js
- src/services/native-mobile-interface/theme.ts
- src/services/native-mobile-interface/types.ts
- src/store/application/ui/theme/sagas.ts
This & native layer code fixes two bugs:
- Manually setting the theme in the app wouldn't change the StatusBar color - so if your phone was in dark mode and you set the theme to light, your status bar is invisible. 
- Our react-native-webview package has an evil default where it manages the StatusBar color unless you tell it otherwise, and it has weird behavior (randomly changing the color to be white when it shouldn't be, etc). https://github.com/react-native-webview/react-native-webview/issues/735
Native change did update the Webview package. But seems fine.
On physical iOS device
> Send theme change messages to native layer

- src/store/account/mobileSagas.ts
If you load in the signin page or the signup page and quickly switch to the signup page, it goes back to the signup page. 
This is because a saga re-routes to the signup page if fetch account fails.
The fix is to check if the user is already on either and not push route if the user is on signup or signin. 
Closes AUD-121
nope
I loaded the signup page and quickly switched to the signin page and it didn't switch back. 
I loaded the signin page and it didn't switch to the signup page
> Prevent a route switch if already on login/signup

- src/containers/settings-page/components/desktop/SettingsPage.module.css
- src/containers/settings-page/components/desktop/SettingsPage.tsx
Adds margin-left to the buttons on the desktop settings page 
Closes AUD-136
no
ran it locally!
> Add spacing to desktop settings btn

- src/store/cache/users/sagas.js
- src/store/cache/users/utils/index.ts
- src/store/cache/users/utils/pruneBlobValues.ts
Sometimes the user's profile pic does not load in the nav column. This is a race condition that is manifested by us caching _profilePictureSizes on the user object in local storage and that user not getting updated with a fresh image before the image is rendered by the useImageSize hook.
The reason it's bad to cache _profilePictureSizes in local storage is that our image references are sometimes blob references (e.g. blob:audius.co/xxx-yyy-zzz), a side effect of how fetchCID needs to work. These references are no longer valid on a new session, but there's a chance we could read the (outdated) local storage ones before having refetched.
n/a
Please describe the tests that you ran to verify your …
> [AUD-129] Fix profile pic not loading

- src/containers/track-page/store/sagas.js
- src/services/remote-config/RemoteConfig.ts
- src/services/remote-config/defaults.ts
Removes the optimizely boolean value `OPTIMIZED_TRENDING_BADGE_ENDPOINT`
We introduced this remote config value to wait for all discprovs to have a new endpoint before consuming it on the client.
The nodes running the current version of discprov 0.3.28 (check [dashboard](https://dashboard.audius.org/services/discovery-node) - 17/18 Discovery nodes) have this endpoint. 
Closes AUD-256
none
The remote config value was already flipped from false to true and the client was working as intended. 
This change removes the now, unused code path.
I ran the client against prod locally after the changes and still saw the trending badges
> Remove optimizely trending bool

- src/containers/profile-page/ProfilePageProvider.tsx
- src/containers/profile-page/components/mobile/ProfilePage.tsx
On mobile, if the user edits their profile and pulls down to refresh, the old state is displayed. 
This change prevents the user from pulling to refresh if the user's profile is confirming. 
Closes AUD-213
none
I ran this locally, ngroked and on my phone edited my profile, and made sure that I could not pull to refresh while it was confirming.
> Prevent pull to refresh if confirming

- src/services/AudiusBackend.js
The autoselect function expects an object and since nothing is passed in, the function is trying to pull properties off undefined and it errors. This change just passes an empty object so the default properties get pulled off in the autoselect and fixes the error.
This is only a problem in the old user metadata -> creator flow. New users created via libs don't face this issue because libs correctly passes in an object
Ran the client pointed against prod and verified replica set is assigned
> Pulling property off undefined object throws error in creator node autoselect

- src/containers/settings-page/components/desktop/SettingsPage.tsx
- src/containers/settings-page/components/mobile/SettingsPage.tsx
Fixes tab slider crashes when:
- Matrix mode is set but gold is lost
- Gold tier is gained when on settings page
None
Locally
> Fix tab slider

- src/services/audius-api-client/AudiusAPIClient.ts
Bug:
- If we're in eager mode and a request fails, we would always wait for libs to init before doing the libs route. However, libs might have already initted in this time, causing us to never retry the request. 
None
Careful console logging of the control flow here, before and after the fix. I can get 500s now and the client still works as expected.
> Fix race condition in AudiusAPIClient

- package-lock.json
- package.json
Published 1.1.14-dev.1 for temporarily disabling CN rollover
> Use libs 1.1.14 as base for hotfix

- src/components/drawer/Drawer.module.css
Token info drawer shows when scrolling down on audius.co inside Twitter. 100px padding here fixes that. Could not repro the other half of the ticket, but lmk if you know what the repro is (i forgot).
n/a
Ngrokked link via tweet
> [AUD-281] Fix drawer pos on safari

- package-lock.json
- package.json
This PR bumps `@audius/libs` to version `1.1.16`
Includes minor changes that do not impact main flows.
This includes the change to make the number of retries optional for claim rounds.
N/A
N/A
> Bump libs to v1.1.16

- public/index.html
- src/services/AudiusBackend.js
High level of confidence that this will make the captcha error message never show.
I believe the outer div is where the text got added -- effectively it replaced the contents of the outer div in this screenshot:
By choosing where to render recaptcha (inside of the ghost div, that should take care of things)
touches index.html 
Against staging
> Hide recaptcha always with custom render

- src/services/AudiusBackend.js
Electron assets are served from file:// and thus have no domain for captcha to verify against.
n/a
* Reproduced error locally w/ electron on sign up
* Disabling mitigates that error
> Disable electron captcha

- package-lock.json
- package.json
Update libs to 1.1.18. No user-facing changes, but includes multi wallet / collectibles libs support, URSM client changes, and updated listen method for content node use.
> Bump to libs 1.1.18

- src/store/account/sagas.js
I believe `twitterId` is not the name of the action value. It should be uuid. This must have changed with instagram auth.
See https://github.com/AudiusProject/audius-client/blob/ea04a6ef7dfd20156aa889280f2c932658890985/src/containers/settings-page/SettingsPageProvider.tsx#L243
Broken in this commit:
https://github.com/AudiusProject/audius-client-old/pull/1119
> Fix twitter uuid

- src/containers/upload-page/store/sagas.js
Throttles the maximum number of concurrent /relay requests on collection uploads.
As it stands today (in the above screen shot) we wait until all uploads for a collection happen and then we spam the relay endpoint. For 200 concurrent tracks, we would send 200x concurrency leading to too many tracks in the same block and discovery struggles to index.
After this change, we bundle the relays & track posts into groups and collate any errors.
Touches core playlist/album upload flow
- Uploaded playlist of 28 tracks on staging
- Multi upload of 8 tracks (not collection -- should be unimpacted) …
> [AUD-462] Throttle upload relays for collections

- package-lock.json
- src/components/track/desktop/ConnectedPlaylistTile.module.css
- src/components/track/desktop/ConnectedPlaylistTile.tsx
- src/components/track/desktop/PlaylistTile.module.css
- src/components/track/desktop/PlaylistTile.tsx
- src/components/track/helpers.ts
- src/components/track/mobile/ConnectedPlaylistTile.tsx
- src/components/track/mobile/PlaylistTile.tsx
- src/components/track/types.ts
- src/containers/collection-page/store/sagas.js
- src/containers/nav/desktop/NavColumn.js
- src/containers/trending-playlists/store/lineups/collections/sagas.ts
- src/models/Collection.ts
- src/services/AudiusBackend.js
- src/services/audius-api-client/ResponseAdapter.ts
- src/services/audius-api-client/types.ts
- src/services/remote-config/RemoteConfig.ts
- src/services/remote-config/defaults.ts
- src/store/cache/collections/utils/retrieveCollections.ts
- src/store/wallet/sagas.ts
- Add a button for navigating to the additional tracks in a playlist that aren't displayed on the playlist tile
- Make sure that when navigating to a collection page from a collection tile that if we have fetched partial tracks, we go refetch them all
- Remove some dead claim code (reduces startup work + comstock request)
- Add optimizely var for omitting playlists from a certain user id
Locally against staging on top of piazz-rewards
* Trending playlist -> playlist page shows all tracks
* Mobile trending playlist page -> playlist page shows all tracks
Unrelated I think, but i noticed a …
> Add more in playlist component to playlist tile

- src/services/AudiusBackend.js
- src/services/remote-config/RemoteConfig.ts
- src/services/remote-config/defaults.ts
Ability to turn the rolloverNode sanity check off with a config flag. The libs side of this PR is here https://github.com/AudiusProject/audius-protocol/pull/1355
Shouldn't be any.
Testing and pics here https://github.com/AudiusProject/audius-protocol/pull/1355
> Ability to skip rolloverNodes sanity check with a config

- package-lock.json
- package.json
Bump libs in v1.1.21
Shouldn't be any
Each commit in libs has been tested against client pointed to stage/prod
> Bump libs to v1.1.21

- src/store/lineup/reducer.js
We forgot to deal with newState.deleted. This fixes infinite loading for playlist trending on mobile. Mobile would fetch a smaller page size (2) and get stuck before hitting our conditional.
Nah
Tested mobile + desktop, 27 results each
> Fix limited lineup end point calculation

- package-lock.json
- package.json
Found a version of bn.js that satisfies the dep requirements of all the libraries we use. Only importing 1 version now vs 15 previously.
I'm not sure how to properly test this. I've verified that this version meets the requirements of all packages and have browsed around the app. But if there is something specific I should look at just let me know and I will test that out.
> Bump bn.js to 4.11.9

- src/components/track/mobile/TrackTile.module.css
Fix mobile track tile to have ellipsis in title
Fixes AUD-431
none
ran locally in browser mobile view
> Fix ellipsis on mobile track title

- src/store/cache/collections/sagas.js
On temp playlist creation and confirmation, the wrong playlist id is added to the confirmed new playlist and prevents playlist  editing.
Fixes AUD-370
none
ran locally
> Add correct playlist id from temp

- src/services/AudiusBackend.js
- src/store/token-dashboard/sagas.ts
The user metadata w/ associated wallet was being overriden with null when not updating the associated wallets field in the metadata directly. This was due to an oversite in fetching the user's ipfs metadata before re-writing to it. The associated wallet metadata (ie. signature) is not passed as part of the DP response, so we must request the user's ipfs metadata to update it before posting a new version.  
none
Ran locally w/ users that have associated wallets and w/out associated wallet to ensure the flow works are expected. 
Also ran updates to the associated wallets metadata to ensure …
> Fix associated wallet override

- package-lock.json
- package.json
- src/components/preload-image/PreloadImage.tsx
- src/containers/collectibles/components/CollectibleRow.tsx
- src/containers/collectibles/components/CollectiblesPage.module.css
- src/containers/collectibles/components/CollectiblesPage.tsx
- src/containers/collectibles/components/types.ts
- src/containers/collectibles/helpers.ts
- src/services/opensea-client/OpenSeaClient.ts
- src/services/opensea-client/types.ts
Fix bug where white tiles e.g. on /boysnoize/collectibles and collectible not displaying on click e.g. /3lau/collectibles
Tested locally with prod build and went to
/boysnoize/collectibles
/3lau/collectibles
/rac/collectibles
/coopahtroopa/collectibles
Also ran a staging build to test sort modal image/video behavior. looked good too
> Fix collectibles white tile and asset not displaying bugs

- src/containers/collection-page/CollectionPageProvider.tsx
Fix playlist reorder
The playlist reordering was breaking because if the lineup was reloaded ie. on adding a new track, the uid of the track might be different. Then, if you attempted to re-order the tracks, it would then differ from the internal state of uids for reordering for the tracks and error on line 524 here https://github.com/AudiusProject/audius-client/blob/3fdc376d4aacc8fdeb6223503e05b587599b13e3/src/containers/collection-page/CollectionPageProvider.tsx#L516-L526 
The fix is to update the component's order uid ordering to reflect changes in the lineup track entry uids
Fixes AUD-468
none …
> Fix playlist reorder breaking

- src/services/native-mobile-interface/queue.ts
- src/services/native-mobile-interface/types.ts
- src/store/queue/mobileSagas.ts
On native mobile shuffle and repeat were broken 🙃 
This should fix both. 
* Shuffle was never implemented
* Repeat broken when we switched to using redux toolkit and forgot to destruct the action's content from the new `payload` body of the action vs getting the value directly 
Yes, this is dangerous as it touched playing on native mobile. 
Please take some time to play around and test it 🙏 
I ran the client locally against a simulator and tested w/ a playlist to ensure it was shuffling and repeating correctly.
> Fix repeat and shuffle

- src/components/track/GiantTrackTile.module.css
Wraps the giant track tile for smaller screens on desktop. 
NOTE: the 338px is the width of the image on the left, so it wraps after the right side is smaller than the image on the left. 
Screenshot of the min size before wrapping
Fixes AUD-454
none
ran locally
> Wrap track tile for smaller screens

- src/components/collection/mobile/CollectionHeader.module.css
Prevent overflow of text on mobile playlist name
Fixes AUD-475
none
ran locally
> Break playlist title name on mobile

- package-lock.json
- package.json
- src/assets/img/wallet-link.svg
- src/services/remote-config/RemoteConfig.ts
- src/services/remote-config/defaults.ts
- src/services/web3-modal/index.ts
- src/store/token-dashboard/sagas.ts
Adds walletLink as a provider to web3modal.
Note that on disconnect of the walletLink provider it calls a page reload. I couldn't find clean a way around this, so after confirming wallet, it reloads the page if using walletLink as a provider. We disconnect so that the next time you try to connect with walletLink, it shows the QR code instead of using the last cached linked wallet.
none
Ran locally against staging to connect wallets with walletLink and the iOS wallet app.
> Add wallet link as provider

- src/containers/collectibles/components/CollectiblesPage.tsx
- src/containers/collectibles/helpers.ts
Fix iOS safari video thumbnail and limit video support
Tested locally
> Fix iOS safari video thumbnail and limit video support

- src/components/dynamic-image/DynamicImage.tsx
This broke because somehow our default image placeholder is being base64 encoded as a data uri instead of as something in /static. Not really sure how this changed, but this fix seems reasonable to me & i've hit a bunch of dynamic image spots to see if there's any impact
> Fix profile image empty state

- package-lock.json
- package.json
- src/services/opensea-client/OpenSeaClient.ts
- src/types/promise.allsettled/index.d.ts
Some clients do not have the Promise.allSettled function which causes some errors e.g. [here](https://sentry.io/organizations/audius/discover/audius-dapp:296df7dc3f2849bab953905b8d078681/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&query=&sort=-timestamp&statsPeriod=24h&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) This is to mitigate that issue.
> Include promise allsettled polyfill where it is missing

- src/components/search/SearchBarResult.js
- src/containers/search-bar/SearchBar.js
- src/containers/user-badges/UserBadges.tsx
Adds a controlled variant to UserBadges since autocomplete results are not cached
> Fix verified not showing in autocomplete

- src/containers/nav/desktop/CurrentlyPlaying.tsx
- src/containers/nav/desktop/NavColumn.js
- src/containers/play-bar/desktop/PlayBar.js
- src/containers/play-bar/desktop/components/PlayingTrackInfo.tsx
Disallow dragging a private track into a playlist on desktop from the currently playing image and now playing track name
Fixes AUD-544
none
Ran the client locally and checked that dragging public track still worked and private tracks no longer work from the currently playing image and now playing track name.
> Fix drag unlisted track bug

- package-lock.json
- package.json
- src/app.tsx
- src/types/object.entries/index.d.ts
- src/utils/polyfill.ts
Shim the function `Object.entries`
Note that the function is widely supported - https://caniuse.com/object-entries
But there are a lot of error in sentry for `Object.entries is not a function` which seemingly come from react spring, but specifically this function. This is my best guess for the fix.
none
I ran the function and it has no affect even if Object.entries is defined.
> Shim Object.entries

- src/components/general/Page.module.css
- src/components/search/SearchBar.js
- src/components/search/SearchBar.module.css
- src/components/search/SearchBarResult.js
- src/containers/search-bar/SearchBar.js
- src/containers/user-badges/UserBadges.tsx
- src/containers/user-badges/utils.ts
- src/services/audius-api-client/AudiusAPIClient.ts
- src/services/audius-api-client/helper.ts
Fixes a bunch of things:
- Adds badges in autocomplete search
- Removes %20 in search bar if you search for multiple words (pressing enter, full search)
- Stops sorting exact handle matches to top on client, since DP is smart now
- Fix bug where if you hover over an autocomplete option and then press arrow key down, two opts show selected (go see this one on prod)
- Fix bug where a 5px dropshadow from the header would steal focus as you scrolled through autocomplete results (a @forrestb find)
Had to break up the selectors for badge stuff a bit, but no logic changes.
Nah
Locally against DP1
> Fix various search issues

- src/containers/profile-page/store/sagas.js
- src/containers/sign-on/store/sagas.js
- src/containers/upload-page/store/sagas.js
- src/services/AudiusBackend.js
- src/services/audius-api-client/AudiusAPIClient.ts
- src/services/audius-api-client/types.ts
- src/store/cache/collections/sagas.js
- src/store/cache/tracks/sagas.js
- src/store/confirmer/sagas.js
- src/store/social/collections/sagas.ts
- src/store/social/tracks/sagas.ts
- src/store/social/users/sagas.ts
- src/store/token-dashboard/sagas.ts
This will make the confirmation of different actions such as repost, save, upload, signup, follow, etc. to use the same confirmation paradigm. That is, by using the transaction receipt block hash and block number and verifying that they have been indexed.
This touches many flows in the dapp and we want to make sure those still work as intended.
Spun up local libs with changes, and spun up local dapp and tested all the impacted flows.
> Confirm transactions using block has and block number

- package-lock.json
- package.json
- src/electron.js
Electron supports M1 arch after v11. Upgrade to v12 to just stay at latest with one special caveat (commented).
This upgrades electron several versions. Things seem to check out locally, but will want to cut staging desktop apps, etc. to make sure this is working as intended after merged.
Locally via electron:localhost & electron:stage commands.
> Upgrade electron to latest to support M1

- package-lock.json
- package.json
This libs bump is inclusive of the protocol hashes
`27576f58c4cdfa8e18e3f90f2c427d1e4a7eb51c` to `d2a7b99e5b098c3eff761c543936f9773e707457`
most importantly, this libs bump includes fixing the `creator_node_endpoint` bug where some users on signup were not getting assigned a `creator_node_endpoint`. now, there will be a sanity check that assigns a replica set & on file upload, will also assign a replica set if necessary
NOTE: 1.2.1 in libs was not merged into `audius-protocol`, but was published to npm. 
> Use libs 1.2.2

- src/components/image-selection/ImageSelectionButton.js
- src/components/upload/Dropzone.js
- src/utils/imageProcessingUtil.js
Certain image formats are not supported by the back end, so we should filter them out on the client.
Adds an explicit `accept` prop to React Dropzone (docs: https://react-dropzone.js.org/#!/Accepting%20specific%20file%20types ) so that invalid types aren't mistakenly uploaded.
- Higher coupling with the utils file (the cost of a single source of truth for file support)
- Defaulted the `accept` prop to `audio/*` when `type` is not `'image'` as the only types for the `ImageSelectionPopup` are `'track'`, `'stem'`, and `'image'` (and both track and image should be audio files). Previously, no such filter existed.
Please describe the tests that you ran to verify your changes. Provide repro …
> Update "accept" field on image uploads to allowable images

- src/containers/sign-on/store/sagas.js
- src/store/cache/collections/sagas.js
- src/store/social/collections/sagas.ts
- src/store/social/tracks/sagas.ts
- src/store/social/users/sagas.ts
- src/store/token-dashboard/sagas.ts
Return result from confirmation calls so subsequent confirmations do not get blocked
Tested locally
> Return result from confirmation calls

- src/components/play-bar/repeat-button/RepeatButton.js
- src/components/play-bar/shuffle-button/ShuffleButton.js
Save the user's shuffle/repeat states to local storage to persist it on page reload.
Manually tested on Microsoft Edge Desktop:
1) Toggle Shuffle/Repeat settings
2) Refresh page
3) Observe settings persist
1) Open local storage in devtools
2) Set relevant keys to 1 (for the "ANIMATE_OFF_ALL" etc keys)
3) Observe the settings change to 2
> Save shuffle and repeat states to local storage

- src/containers/profile-page/store/lineups/feed/sagas.js
- src/utils/uid.js
There were a couple issues with the chunk of code in the reposts tab that added "unconfirmed" reposted content in (https://github.com/AudiusProject/audius-client/commit/368abbc67453083e245fbd42b09c592bcf2d65e4).
1. The logic checks anything that's in the cache and only dedupes against what is currently coming back in the lineup pagination. If you visited some track pages/trending/etc. where you had tracks that were reposted, the existing code basically ends up shoving all of that content into your reposts tab (even if you had reposted it months ago)
2. The logic runs on every pagination so you'd get the same content repeated many times at the end of each page
3. The logic only accounted for tracks, not collections
Is there anything the reviewer should be on the lookout for? Are there any …
> Fix reposts tab content ordering/pagination

- src/services/AudiusBackend.js
- src/services/remote-config/FeatureFlags.ts
- src/services/remote-config/Provider.ts
**Context:** As of right now, we use userIds to bucket users for certain features in Optimizely. Since users are initialized with userIds as `ANONYMOUS_USER`, if this id is deterministically bucketed by Optimizely to have a certain feature on, then effectively all users will have the feature on. 
**Problem:** This prevents proper feature rollout. 
**Solution:** 
1. Enable session based feature rollouts using a local storage Optimizely key as the unique identifier for users. 
2. Keep userId feature rollouts, but if `ANONYMOUS_USER`, disable
1. Set feature flag to 100% in development mode …
> Fix optimizely bug

- src/containers/nav/desktop/PlaylistLibrary.tsx
For some reason, while dog-fooding the playlist library feature, I ended up with an explore playlist "Under the Radar" which is not the canonical string. "Under The Radar" is. I looked at identity and I'm the only user with this (i must have been playing with this in prod before we launched explore).
https://discoveryprovider.audius.co/v1/full/users/7eP5n?user_id=7eP5n
I'm going to manually issue the write to chain to clear this from my subscribed playlists, but in general, I think this safety check would be good on the off chance that the playlist literally cannot be found given the id reference …
> Fix playlist library bug when explore playlist is not found

- src/containers/track-page/store/sagas.js
Fixes the request to track page badge ids while experiment support is still needed
https://github.com/AudiusProject/audius-protocol/pull/1557
This change can be reverted after that releases to discprovs
Locally against prod with experiment turned on
> Temporarily fix track page badge experiment dep

- src/containers/play-bar/desktop/PlayBar.js
In `PlayBar.js`, the audio volume is being conditionally set when `initialVolume` has a truthy value. This breaks when the volume in local storage is 0. The volume doesn't get set, but the volume bar still displays the volume at 0.
Solution is to explicitly check for `null`. `initialVolume` is either `null` or the numeric value from local storage.
None introduced by this PR, the only dragon being JS's amazing truthy/falsy values
Tested locally against staging. Did not write a test case because `Playbar.js` doesn't have any tests yet and it seemed overkill to add a test file for this small bug fix
https://linear.app/audius/issue/AUD-323/volume-slider-doesnt-take-effect-until-interacted-with
> Set volume when initialVolume is 0

- src/store/playlist-library/helpers.test.js
- src/store/playlist-library/helpers.ts
- src/store/playlist-library/sagas.ts
Currently on prod, I do not believe you could end up in a situation with duplicates, but I did for my account because I was playing around with it on release.audius.co before using audius.co where it tried to re-"migrate" me over to the new library from the identity stored library. Since there are not db constraints around how playlist library is handled, I think it's best to add this safeguard.
On every reorder, with this change, we will just remove duplicates if somehow they happen to exist.
- Unit
- Locally against prod, repairing my duplicates
> Handle duplicates in playlist library

- src/containers/collection-page/CollectionPageProvider.tsx
Small bug where toggling a sort a third time to remove the sort resulted in an error. The `parseCollectionRoute` method was returning null for the path and the `componentDidUpdate` method was returning early and not setting `initialOrder` in state. 
I just moved the code to set initialOrder up so that it is set and it's fixed now 👍 
Should fix AUD-658
None to my knowledge
Manually: I sorted columns and the error did not occur. I also tried reordering tracks after sorting and it worked
> [AUD-658] Update CollectionPageProvider update function to set the initial order in state

- src/hooks/useTabs/useTabs.tsx
The commit that fixed our terser issues involved upgrading react-scripts & therefore ts version, which complained about this hook: https://github.com/AudiusProject/audius-client/commit/55992434196d44a949a1d83c1dcf8a85c4ac7ae8#diff-8b5683265aeafe8204c7641fd7620982cba8605cb28e7e6bc47c50e5b89fdd57R434 (b/c the signature changed)
Solution from that change was not correct, see https://github.com/facebook/react/issues/19240#issuecomment-652945246
* ngrok to mobile device
> Fix useTabs setOffset hook

- src/containers/user-list-modal/components/UserListModal.module.css
There was an error with styling where the bottom of the UserList in the UserListModal would not be visible. This updates the styles of the UserListModal to use flexbox to force the content to the the correct size within the modal. 
Should fix AUD-651
I think this will only affect these two modals (Reposts and Favorites), but there may be other modals that are affected
I opened the modal and it looked good. :chef-kiss:
> AUD-651 Update styles for UserListModal to allow seeing the bottom of the list

- src/containers/remote-config/hooks.ts
userId gets set after the useFlag hook may be called. The useMemo prevents recomputation, so add the account selector in to the mix for USER_ID experiments
- Locally against prod: verified user id experiment triggers (playlist library update dots). Verified mobile still works as well.
- Locally against stage: verified that track polling session id exp is working as intended
> Retrigger useFlag when userId gets set

- src/components/general/TwitterAuth.js
- src/containers/sign-on/SignOnProvider.tsx
- src/containers/sign-on/components/ProfileForm.js
- src/containers/sign-on/components/desktop/ProfilePage.js
- src/containers/sign-on/components/desktop/SignOnPage.tsx
- src/containers/sign-on/components/mobile/ProfilePage.tsx
- src/containers/sign-on/components/mobile/SignOnPage.tsx
- src/containers/sign-on/store/actions.js
- src/containers/sign-on/store/reducer.js
- src/containers/sign-on/store/sagas.js
- src/containers/sign-on/utils/formatSocialProfile.ts
- src/store/account/reducer.ts
Handles oauth profiles from twitter and instagram a bit better. Does a little bit of work to typescriptify + condense the code around processing profiles.
The changes are best understood by the test cases
For both twitter & instagram (i mocked data since that doesn't work against local):
1. Create an account and oauth with a valid handle that's unclaimed on audius => skips the "edit profile page" of sign up
2. Create an account and oauth with a valid  handle that's claimed on audius => shows the "edit profile page" with handle in use message
3. Create an account and oauth with a handle …
> Handle twitter & insta oauth profiles better

- public/index.html
AFAIK, jimp does not need to be preloaded (it's used for computing average artwork colors in a web worker, resizing images on upload). Also, I do not believe it needs to have CORS setup -- it'd always be coming from the same domain.
> Import jimp without preload

- src/containers/menu/Menu.tsx
Fixes a small bug I noticed with the z index being too low for the notification overflow menu.
I originally lowered the z-index of the Menu (specific to tracks, users, collections, and notifications) to account for the frosted header on Feed and Trending pages, but this was breaking because the Notification menu is opened from another popup.
Are there any other places popup menus happen from modals/dialogs? 
> Fix zindex issue with notification menu

- src/services/AudiusBackend.js
It seems like users no longer have profile_picture, but have a single non sizes CID in the _sizes prop.
https://discoveryprovider.audius.co/users?handle=emilyhou
I couldn't think of a better way to handle this unfortunately.
localhost:3002/emilyhou
> Fix old accounts

- src/containers/profile-page/store/actions.js
- src/containers/profile-page/store/sagas.js
- src/services/AudiusBackend.js
- src/store/account/sagas.js
It's possible while fetching another profile to refetch your own account as part of the followers/followees/mutual followers and these endpoints don't respect (or support) the ?user_id route param fo the current user.
In those cases, we don't really need to refetch the current user, so filter it out.
Repro was from my account => profile /emilyhou and verified the bug no longer shows up with this change
> Fix playlist library staleness bug

- .circleci/config.yml
- wrangler.toml
Sets up release-candidate flow to be on cloudflare (rather than s3)
Job on CircleCI
https://app.circleci.com/pipelines/github/AudiusProject/audius-client/1709/workflows/2c819698-367c-42c2-b6ed-89703a8877b3
> Add release-candidate flow

- .eslintrc.js
Adding the `import/order` eslint rule caused an issue when a local module was `npm link`ed. The module was no longer considered "external" and therefore the rule required it to be in a different import group. This PR fixes that by specifying the directories from which modules should be considered "external"
Are there any other modules we commonly link?
If we were to add a `stems` or `audius-protocol` directory in the client, this would consider files imported from those directories external. But I don't think there would ever be a reason to have directories of those names in the client
Manually, by linking/unlinking and running the linter
> Fix linked module import order lint

- package-lock.json
- package.json
- src/containers/profile-page/store/sagas.js
- src/containers/sign-on/SignOnProvider.tsx
- src/containers/sign-on/store/actions.js
- src/containers/sign-on/store/reducer.js
- src/containers/sign-on/store/sagas.js
- src/containers/sign-on/store/selectors.js
- src/schemas/index.js
- src/services/AudiusBackend.js
- src/store/account/mobileSagas.ts
- src/store/account/sagas.js
- src/utils/signOut.js
Add referrer and is_mobile_user events tracking
_referrer_ gets added on sign up and parsed off of the URL, e.g. audius.co/signup?ref=ray
_is_mobile_user_ gets added along w/ the existing flow that writes hasUserSignedInOnMobile to the identity service for notification email processing
Nope other than there should be a point of notification refactor where we remove the identity field and use the user metadata one. That would also include a discovery database migration for backward compat.
Ran against local backend services & tested setting `referrer` and `is_mobile_user`
For features …
> Add support for referrer and is_mobile_user events

- src/containers/share-sound-to-tiktok-modal/ShareSoundToTikTokModal.tsx
- src/containers/share-sound-to-tiktok-modal/store/sagas.ts
- src/containers/share-sound-to-tiktok-modal/store/selectors.ts
- src/containers/share-sound-to-tiktok-modal/store/slice.ts
- src/containers/share-sound-to-tiktok-modal/store/types.ts
- src/containers/upload-page/components/ShareBanner.tsx
- src/services/remote-config/FeatureFlags.ts
- src/store/application/ui/modals/slice.ts
This PR:
* Fixes a bug where the `creator_node_endpoint` was being used incorrectly, causing the request to the users CN to fail and always falling back to the public ipfs gateways
* Sets the default value for the TikTok sharing feature flag  to `false`
* Adopts the pattern of using the `modal` slice to handle open/close state while using a custom slice for the business logic
No
Manually
> TikTok share sound fixes

- src/containers/collection-page/components/desktop/CollectionPage.tsx
Fixes a tiny bug on explore page collections where if no user is signed in, it's possible for null === null (since explore collections have no "owner") and reordering to be allowed.
- Explore collection signed out
- Normal playlist signed out
- Normal playlist signed in (can reorder if owner)
> Make sure a user id is present before allowing reorders

- src/containers/explore-page/ExplorePage.tsx
- src/containers/explore-page/components/desktop/ExplorePage.tsx
- src/containers/explore-page/components/mobile/ExplorePage.tsx
- src/containers/remote-config/hooks.ts
- src/containers/remote-config/selectors.ts
Because the layout for the explore page is now controlled by a feature flag, the first few renders happen when the feature flag is off and then renders happen when it's on. This causes two issues:
1. The layout jumps when the Remixables tile shows up
2. It's possible that the array of explore tiles gets instantiated before the feature flag loads at all, making remixables never show
Both of these issues are fixed by
1. Moving the decision to render the remixables tab into the conmponent lifecycle rather than as a global
2. Wait to render explore until remote config loads in
1. Feature …
> Fix subtle bug in explore layout

- src/containers/play-bar/desktop/PlayBar.js
If there is no currently playing track, the next and previous btn trigger an error because we try to get the field `genre` on an undefined track obj.
Sentry Error: `genre title:"TypeError: Cannot read property 'genre' of null" project:audius-client ` 
**Fix**: Add optional chaining to check if the track object is defined.
Closes AUD-816
none
Ran the client against staging and it didn't error
Check if sentry errors go away.
> Adds null check on playbar

- src/components/card/desktop/CollectionArtCard.tsx
- src/containers/menu/Menu.tsx
The overflow menu kebab on the explore tile got shifted due to a classname being incorrectly applied. Typescript missed this because we had a `// @ts-ignore` 💀 
> AUD-848 Fix explore tile kebab position

- src/services/AudioManager.ts
- src/store/account/sagas.js
Closes the transfer waudio to audio modal after 2 seconds if not already closed (ie. still waiting for transfer transaction to be completed and confirmed)
Also updated the analytics event to be correct
Closes AUD-807
none
Ran it manually with a timeout in place of the transfer audio to waudio 
manually
> Close transfer waudio modal after 2 sec

- src/components/image-selection/ImageSelectionPopup.js
- src/utils/zIndex.ts
The migration to `Popup` introduced a visual bug on the profile page when editing the profile photo or cover photo. This PR adds a zIndex to the `ImageSelectionPopup` to fix this bug
> AUD-840 Add zIndex to ImageSelectionPopup

- src/components/track/mobile/ConnectedTrackListItem.tsx
- src/components/track/mobile/ConnectedTrackTile.tsx
- src/containers/menu/TrackMenu.tsx
- src/containers/track-page/components/mobile/TrackHeader.tsx
The entire TikTok Share feature is supposed to be wrapped in a feature flag, but I realized that it was missing for the context menu tiktok share option. This PR wraps that option with the flag
No
Manually
> Add feature flag around tiktok share from context menu

- src/containers/audio-rewards-page/components/WalletsTable.tsx
Updates the associated wallets modal to not display the copy icon when loading 
Enables copy when the row is not in a pending state
Updated mount position of toast within modal so as to not be hidden
none
Ran locally against staging
manually
> Fix styles with associated wallets

- src/containers/profile-page/ProfilePageProvider.tsx
- src/containers/profile-page/components/SocialLink.tsx
- src/containers/profile-page/components/SocialLinkInput.tsx
- src/containers/profile-page/components/desktop/ProfilePage.tsx
- src/containers/profile-page/components/desktop/ProfileWrapping.js
- src/containers/profile-page/components/mobile/EditProfile.tsx
- src/containers/profile-page/components/mobile/ProfileHeader.tsx
- src/containers/profile-page/components/mobile/ProfilePage.tsx
- src/containers/profile-page/store/sagas.js
- src/models/User.ts
- src/services/AudiusBackend.js
- src/services/analytics.ts
This PR:
* Adds and input for the tiktok handle to the profile page
This does not pull from the tiktok user when they have been authed, mainly because they aren't setting their account up with tiktok and it would be weird to populate this field based on their auth for sharing a sound IMO
Also, crazy how many changes were required to do this. I feel like this could be structured differently to improve maintainability, but due to time constraints I followed the existing pattern (classic)
For features that are critical or could fail silently please describe the monitoring/alerting being …
> AUD-756 Add tik tok handle to profile page

- src/store/cache/tracks/selectors.ts
We lowercase all permalinks in storage:
https://github.com/AudiusProject/audius-client/blob/daf20f01b3737d8ca9a975b71f7f662eaa2c9aeb/src/store/cache/tracks/selectors.ts#L14
The selector does not lowercase though, so tracks w/ capitalization are not fetched properly by the selector
^^^^^^^
After this first change, realizing that there's already a permalink selector that does the .toLowerCase and some of the logic can be consolidated. I believe this second fix is safe as well.
Touches track retrieval
Locally against prod (mobile + web)
http://localhost:3002/Galazy_Music
-> click on first …
> Fix permalink selector to lowercase

- src/components/track/GiantTrackTile.js
- src/components/track/desktop/ConnectedTrackTile.tsx
- src/components/track/desktop/TrackListItem.tsx
- src/components/track/helpers.ts
- src/components/track/mobile/ConnectedTrackTile.tsx
- src/components/tracks-table/TableOptionsButton.js
- src/containers/artist-dashboard-page/ArtistDashboardPage.tsx
- src/containers/menu/TrackMenu.tsx
- src/containers/now-playing/NowPlaying.tsx
- src/containers/share-sound-to-tiktok-modal/store/sagas.ts
- src/containers/track-page/components/mobile/TrackHeader.tsx
- src/containers/upload-page/components/ShareBanner.tsx
This PR:
* Hides the "Share to TikTok" option for unlisted tracks
* In the overflow menu
* In the upload flow
* Tweaks one of the error analytics calls to only include the error message, not the entire error
> AUD-857 disable tiktok sharing for unlisted tracks

- src/components/actions-tab/ActionsTab.js
- src/components/actions-tab/ActionsTab.module.css
- src/components/create-playlist/CreatePlaylistModal.js
- src/containers/edit-playlist/desktop/EditPlaylistModal.tsx
- src/containers/nav/desktop/NavColumn.js
- src/utils/zIndex.ts
Noticed a couple of styling issues:
1. The zIndex issue I thought I'd addressed still persisting on the CreatePlaylistModal. This is preventing creation of new playlists in prod on the web client
2. Issue with the alignment of the kebab icon on the Card
Probably need to deploy this to prod asap
Manually, confirmed the image popover has correct z-index in the following places:
* Create Playlist
* Edit Playlist
* Edit Track
* Change cover photo
* Change profile photo
* Upload Track
> Fix Popup styling

- scripts/workers-site/index.js
Adds a check for a specific route in the cloudflare worker in order to rewrite it to be a new-style route.
Old style routes are not generated on the DN anymore, but outdated mobile apps will still generate them. This hotfix fixes one specific Audius link but a fix should go out next release to continue making old-style links until user sediment moves to the latest app version.
** This can never fail or all URLs will fail **
Tested the new code on a dummy "request" JS object in the console.
For features that are critical or could fail silently please describe the monitoring/alerting being …
> hotfix: Add temporary fix for old-style route

- src/containers/sign-on/store/actions.js
- src/containers/sign-on/store/sagas.js
Creates a new action/saga for validating email, throttling the email check to 2 seconds
The throttle method was used in place of a delay in the existing saga so that it does not have to wait on the very first pass.
Closes AUD-930
none
Running locally
manually
> Add wait between validating email

- src/components/data-entry/FormTile.js
Changes the character limit of the Description field on tracks to 1000 characters (was the default 256 characters).
Might be worth investigating a "see more" link if there's more than a few lines of description on a track.
Tested that DN accepts that many characters and that they display fine by uploading a track with that description length as well as editing an existing track (against stage, no backend changes necessary)
> Increase description field limit to 1000 characters

- src/containers/profile-page/ProfilePageProvider.tsx
Closes the artist recommendations if the profile changes from one user to another.
Manually: Open an artist profile with > 200 followers, click follow (unfollow first if necessary), then hover over an artist profile in the recommendations. Click on one of their names/handles, and observe the artist recommendations popup will be closed.
> Close artist recommendations when navigating away from the profile

- src/containers/collectibles/components/CollectibleDetails.tsx
- src/containers/collectibles/ethCollectibleHelpers.ts
- src/services/WebWorker.js
3D nfts on opensea with a gif frame were display the gif instead of a still image on the collectibles page. This PR makes an image out of the gif so the card shows a still image.
Spun app locally and tested account with 3d nft that had a gif as a frame. The frame now shows a still image instead of a gif.
> Fix 3d object nft frame in case of gif

- .circleci/config.yml
Per https://circleci.com/docs/2.0/xcode-policy/ the version of xcode we are using for macOS builds has been sunset. Time to upgrade!
Nope
Manual staging run: https://app.circleci.com/pipelines/github/AudiusProject/audius-client/2182/workflows/12f47af0-490c-4f7d-8437-1d9e75d549ac
🧑‍🍳
> [AUD-753] Update xcode version for macOS builds

- src/containers/artist-recommendations/store/sagas.ts
- src/containers/artist-recommendations/store/slice.ts
Fix bugs in fetching suggested follows
1. If filteredArtists.length < 5, we will definitely re-pick the same ones. Even if >5 it could still repick. Use shuffle/slice instead
2. Update reducer to only update recommendations if not already set
Locally vs. prod with my account
> Fix duplicate data/refetch suggestions bug

- scripts/workers-site/index.js
- src/services/audius-api-client/AudiusAPIClient.ts
Updates the `getTrackByHandleAndSlug` method to fallback to trying to parse the ID from the route if the initial request 404s. This fixes the links sent out by mobile users using outdated app versions.
Also removes one-off since that link should now also work.
Tested manually on -instrumental-prod.-by-mattrickbeats-530271 and -instrumental-prod.-by-mattrickbeats-100000 and -instrumental-prod.-by-mattrickbeats-1 to ensure the proper logic. (First one redirects to the proper track, second 404s, third 404s)
For features that are critical or could fail silently please describe the …
> Fallback to parsing the ID from URL on 404

- src/containers/sign-on/components/ProfileForm.js
- src/containers/sign-on/components/desktop/ProfilePage.js
- src/containers/sign-on/utils/formatSocialProfile.ts
- Fixes bug causing Instagram signup flow to not autofill for all desktop users
- Fixes bug when Twitter/Instagram names are longer than 32 characters, asks user to verify the truncated names.
- Tested locally by placing breakpoints in `TwitterOverlay`'s `onClickInstagram` function, and then in the console running one of the following to fake a login from instagram or twitter respectively: 
```js
setTimeout( () => props.onInstagramLogin('', { username: 'foo', full_name:'abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz', verified: false, id: 'idk'}), 5000) …
```
> AUD-947 Truncate display names on signup if necessary

- src/containers/nav/desktop/NavColumn.js
- src/containers/nav/desktop/NavColumn.module.css
- src/containers/sign-on/SignOnProvider.tsx
- src/containers/sign-on/components/desktop/EmailPage.module.css
- src/containers/sign-on/components/desktop/EmailPage.tsx
- src/containers/sign-on/components/desktop/MetaMaskOption.js
- src/containers/sign-on/components/desktop/MetaMaskOption.module.css
- src/containers/sign-on/components/desktop/SignInPage.js
- src/containers/sign-on/components/desktop/SignInPage.module.css
- src/containers/sign-on/components/desktop/SignOnPage.tsx
- src/containers/sign-on/components/mobile/InitialPage.module.css
- src/containers/sign-on/components/mobile/InitialPage.tsx
- src/containers/sign-on/components/mobile/SignOnPage.tsx
- src/containers/sign-on/store/actions.js
- src/containers/sign-on/store/sagas.js
AUD-671
- Make the sidebar have a "Sign In" link instead of "Sign Up" when not logged in.
- Submitting an email that already exists in the "Sign Up" flow no longer errors but sends you to the "Sign In" page with the email pre-filled and the password field focused.
- Adjusted the "Sign Up" page to include a button instead of a link for "Have an account? Sign In"
- ~I dislike the way I handled the issues with the Saga for the `EmailPage`, would love to brainstorm other ideas here.~ Updated: Feedback still welcome but looks better now.
- Manually/locally.
For features that are critical or …
> AUD-671 Sign Up/Sign In Redesign

- .circleci/config.yml
In order to open up staging build, before probers receive changes for the new sign up flow, temporarily disable
> Temporarily disable probers

- src/containers/sign-on/components/mobile/PasswordPage.tsx
Remove mobile onConfirmKeyDown on password pg of signup as it causes the user to double submit the onClickContinue btn and skip the profile page of signup on mobile only
* manually in mobile view on desktop
* mobile web
> Remove mobile confirm keydown

- src/containers/profile-page/store/lineups/feed/reducer.js
- src/store/lineup/reducer.js
This PR fixes the infinite scroll on the reposts tab on the profile page.
The issue was due to the feed lineup having `containsDeleted: true` and there being a deleted track in the lineup. When a page request was made for 19 reposts and only 18 came back, the lineup was incorrectly marked as `hasMore: false`.
I think confusion was caused by the `containsDeleted` flag, so I updated the comment to be a bit more descriptive.
> AUD-991 Fix Profile Page Reposts Lineup Infinite Scrolling

- src/common/store/cache/sagas.js
- src/common/store/cache/store.test.js
- src/containers/sign-on/store/sagas.js
The change in #621, while functional, does not address the root cause of why the fork didn't work.
What actually was happening behind the scenes is that when the followed collection belongs to the auto followed user, we get into a situation where:
1. The user is not in the cache
2. The `follow user` action is being confirmed
3. The collection follow (save) fails because the user is not in the cache
The reason the user is not in the cache is because we have a check that disallows recaching of fetched assets while something is confirming. Generally this is really good because we don't overwrite client state around fields like `has_current_user_followed.` However, in this case, the user was never cached in the first place, so we were unable to complete the collection save.
This PR addresses …
> Fix fork fetch collections

- src/containers/trending-page/TrendingPageProvider.js
Resetting the genre & timerange will cause the behavior noted in linear where:
1. Trending reducer sets initial genres and time ranges based on URL
2. User navigates away from trending and on unmount, resets genre & timerange in the reducer to null/week
3. User navigates back to trending and the lineup componentDidMount fires before the page's componentDidMount making it so the URL genres are never captured.
I think this is the most sane fix. We could try and pipe the trending actions to set store state down into the lineup's componentDidMount itself, but realistically, I think we can just avoid clearing this on unmount. Because we are still calling the makeReset, we will still get fresh data on every load.
Is there anything the reviewer should be on the lookout for? Are there any …
> [AUD-1053] Avoid resetting genre & trending on componentWillUnmount

- src/containers/sign-on/store/mobileSagas.ts
Currently, if user on a mobile client spends a long time on the follow artists screen during sign up and then clicks continue, the feed is empty because the account would've already been available/ready before the followees had a chance to be triggered. This fix waits for the follows trigger to set the account available flag.
> Wait for follow artists before sending account available to mobile

- src/audio/AudioStream.ts
This PR:
* Adjusts the `webkitAudioContext` declaration to the class `AudioContext` instead of the interface `AudioContext` (Thanks typescript)
This is needed to properly typecheck `audius-mobile-client`. The mobile client is necessarily using a newer version of typescript and gets upset when we try to construct an `AudioContext` below in this file
> Adjust AudioContext type

- src/common/store/cache/tracks/utils/retrieveTracks.ts
- src/services/audius-api-client/AudiusAPIClient.ts
Fix bug where a track does not appear to be reposted immediately after reposting and reloading. The source of this issue (and the reason probers have been flaky most of the time) is because the current user id (if applicable) is not passed to the handle/slug endpoint, so `has_current_user_reposted` does not return as true.
My suspicion for why this has gone unnoticed for so long is that likely the track is being fetched by another endpoint the majority of the time on production and that is overwriting the `has_current_user_x` field
* Locally vs. staging as a logged in account
* Locally …
> [AUD-1069] Fix missing repost on initial load

- src/components/track/desktop/TrackListItem.module.css
Fix overflow position in playlist tile so it matches mocks
https://www.figma.com/file/NgLUY1n0YBi1rLRwYE0PuV/Overflow-Menus?node-id=101%3A141
> [AUD-922] Fix position of overflow in playlist tile

- src/containers/remix-settings-modal/store/sagas.ts
Taking every fetch event meant that the "not found" case completed after the "success" case (since it takes longer to fail), even if the successful entry was the most recently typed.
Manually
> [AUD-839] Fix remix settings modal to only fetch the most recent url

- package-lock.json
- package.json
- src/AppContext.tsx
- src/app.tsx
- src/components/image-selection/ImageSelectionPopup.js
- src/components/tracks-table/TracksTable.module.css
- src/containers/App.js
- src/containers/MainContentContext.tsx
- src/containers/artist-recommendations/ArtistRecommendationsPopup.tsx
- src/containers/menu/Menu.tsx
Create a "global" MainContentRef context that allows components to grab a ref for the "main content" (everything inside the left nav and bottom bar).
Use that main context ref instead of mucking with state everywhere in App.js (perf win? 🤞)
This change should be paired with https://github.com/AudiusProject/stems/pull/64 to fix the actual bug at hand
* ImageSelectionPopup
* Menu popup
* Artist recommendations popup
> [AUD-900] Add main content context

- src/schemas/index.js
Updates newUserMetadata to include `is_deactivated` with default value of false.
Without this change, running the client with the latest libs fails signup as the user replica set validates the metadata and sees `is_deactivated` is missing.
Tested signup manually against latest libs.
> Add is_deactivated to default metadata fields

- src/containers/collectibles/ethCollectibleHelpers.ts
Display gif frame instead of autoplaying gif in collectibles page.
Locally against prod accounts with collectibles
> Fix gif preview

- src/containers/collectibles/components/CollectibleDetails.tsx
- src/containers/collectibles/components/CollectibleDetailsModal.tsx
- src/containers/collectibles/components/CollectiblesPage.tsx
Use pushState instead of navigate (pushRoute) to change the URL, so it doesn't trigger a full page remount.
I think there is probably an overhaul due in the land of how we handle rendering pages based on routes, but in the near-term, this is a reasonable solution. Opening the modal triggers a history state change, but not a re-route to a new page. I think ~reasonable because we don't actually change "pages."
- Click on collectible (no rerender)
- Click out of details modal (no rerender)
- Navigate directly to collectibles page
- Navigate directly to collectible id page 
For features that …
> Fix collectible deep link

- public/fonts.css
- public/index.html
- src/assets/styles/index.css
- src/components/collection/mobile/CollectionHeader.module.css
- src/containers/artist-dashboard-page/components/TotalPlaysChart.js
- src/containers/landing-page/components/FeaturedContent.module.css
- src/containers/nav/desktop/NavHeader.module.css
- src/containers/profile-page/components/mobile/ProfileHeader.module.css
- src/containers/sign-on/components/desktop/EmailPage.module.css
- src/containers/sign-on/components/desktop/MetaMaskOption.module.css
- src/containers/sign-on/components/desktop/SignInPage.module.css
- src/containers/sign-on/components/mobile/FollowPage.module.css
- src/containers/sign-on/components/mobile/LoadingPage.module.css
- src/containers/sign-on/components/mobile/NotificationPermissionsPage.module.css
- src/containers/upload-page/components/TracksPreview.module.css
On prod nowadays b/c our main css bundle is pretty heavy, we have a decent amount of FOUT (flash of unstyled text).
I think there are two camps around the base64 encoding of fonts like we do (I generally like it, primarily b/c it's self-contained), but regardless, we should be pulling the font in far earlier than we do in the main css bundle.
Some best practices stolen from 
https://css-tricks.com/how-to-load-fonts-in-a-way-that-fights-fout-and-makes-lighthouse-happy/
ray.audius.co
> [AUD-1071] Improve Avenir font load to avoid FOUT

- src/containers/smart-collection/store/sagas.ts
- src/services/audius-api-client/AudiusAPIClient.ts
- Updates `getRemixables` to call with `with_users` set to true, and filters tracks that are from deactivated users on the client
Tested manually locally against staging on `mjp-tombstones`
> Don't show deactivated user tracks in Explore Remixables

- src/containers/history-page/store/lineups/tracks/sagas.js
- src/services/AudiusBackend.js
- src/services/audius-api-client/AudiusAPIClient.ts
Proper history endpoint support was added in 
https://github.com/AudiusProject/audius-protocol/pull/2045
Migrate AudiusBackend history API to APIClient, add support for history & update the lineup
Note: the new endpoint supports up to limit =500, but this PR keeps parity at limit =100 for the history page. In the future, we will make the table paginate, but will probably not store indefinite history
Client locally vs. prod & verified history results are consistent.
> [AUD-1068] Migrate history call to use new discovery API endpoint

- src/components/remix-settings-modal/RemixSettingsModal.tsx
- src/containers/remix-settings-modal/store/sagas.ts
- Setting remix parents would fail for tracks with non-ascii characters, because the slug was double encoded
- We would also show the encoded version of the title in the remix box, which is annoying
None
n/a
> Fix remixes with non-ascii characters

- src/store/analytics/providers/amplitude.ts
Bug in the amplitude tracking
The init event was not called correctly - bug from #665 
NOTE: we did not turn on the amplitude feature flag yet, so this code path is not executed
none
ran locally against prod and manually forced amplitude instead of using the feature flag
By looking for the amplitude events for init
> Fix init track event

- .circleci/config.yml
Following along w/ changes in:
https://github.com/AudiusProject/probers/commit/269c32effb4b932b7e60fe57837af3b405bc80ef
This PR ups the resource class to run the web driver test and fixes the node version to 14 for consistency.
only ci
Ran probers
> Up resource class and pin node version for probers

- src/containers/profile-page/ProfilePageProvider.tsx
Remove unnecessary profile handle check on profile page mount to fix tracks not loading when hitting the back button
Manually tested. tracks load
> Remove unnecessary route comparison on ProfilePage mount

- package-lock.json
- package.json
- src/components/track/GiantTrackTile.js
- src/components/track/GiantTrackTile.module.css
- src/containers/download-buttons/DownloadButtons.module.css
- src/containers/download-buttons/DownloadButtons.tsx
- src/containers/track-page/components/mobile/TrackHeader.module.css
- src/containers/track-page/components/mobile/TrackHeader.tsx
- src/containers/track-page/components/mobile/TrackPage.tsx
- src/services/audius-backend/TrackDownload.js
- src/services/native-mobile-interface/downloadTrack.ts
- src/services/native-mobile-interface/types.ts
- src/store/social/tracks/sagas.ts
Trigger a mobile download onto audius-mobile-client when clicking the "download" button on the track page. 
- Create new type of message: DownloadTrackMessage
- When download button is clicked -> send that message to audius-mobile-client which will handle the rest. 
Designs
https://www.figma.com/file/ii6uNAdGGoQ7X7p7cENGhf/Mobile-Download-Buttons?node-id=101%3A141
- Easier to review by commit
- Drawer functionality was fully moved to the audius-mobile-client
Running through the download track flow from both web and mobile. See [MobilePR](https://github.com/AudiusProject/audius-mobile-client/pull/180) for more testing.  
Making sure the UI for the buttons looks good. 
| | Web | Mobile |
|-- | -- | -- |
| One button |![Screen Shot 2021-12-04 at 3 46 38 …
> Ms download tracks mobile

- src/services/AudiusBackend.js
Fetching image cid was incorrect
This PR is to add the ipfs gateway in front of UM.
fetching ipfs gateways on client console.log results:
old:
(4)['https://creatornode10.staging.audius.co/ipfs/', 'https://creatornode5.staging.audius.co/ipfs/', 'https://creatornode7.staging.audius.co/ipfs/', **'https://usermetadata.staging.audius.co'**]
new:
(4)['https://creatornode10.staging.audius.co/ipfs/', 'https://creatornode5.staging.audius.co/ipfs/', 'https://creatornode7.staging.audius.co/ipfs/', **'https://usermetadata.staging.audius.co/ipfs**']
Probably not. this potential bug has been in place for a year now …
> Add /ipfs to UM cid fetch

- scripts/configureLocalEnv.js
`audius-disc-prov_web-server_1` isn't used anywhere now that we can have multiple disc provs.
> Update configureLocalEnv.js to use new name for discovery

- src/common/store/cache/users/sagas.js
- src/containers/download-buttons/DownloadButtons.tsx
- src/containers/track-page/components/mobile/TrackHeader.module.css
Fix two bugs
1. Don't show download buttons container when no download button
2. Horizontally stack download buttons when there are multiple
|--|Mobile|Desktop|
|--|--|--|
|No Download Track|![1](https://user-images.githubusercontent.com/12490332/146433471-e0e4bc93-132c-4e4d-ab09-07d8ed7219c3.png)|![Screen Shot 2021-12-16 at 11 00 35 AM](https://user-images.githubusercontent.com/12490332/146433558-9c92c470-eaf2-4bb1-9d49-bf8eb1ceed48.png)|
|Multiple Download Tracks|![Screen Shot 2021-12-16 at 10 59 14 AM](https://user-images.githubusercontent.com/12490332/146433510-046a50cd-c9a5-475a-a782-90803dbe0b5a.png)|![Screen Shot 2021-12-16 at 11 00 41 AM](https://user-images.githubusercontent.com/12490332/146433639-e55e2515-6b38-4ada-8789-226ae060459b.png)|
> Fix bug to make download buttons show up in vertical alignment

- src/services/audius-backend/TrackDownload.js
- src/store/social/tracks/sagas.ts
Previously: No filename would show up when downloading stem version of a file on mobile
After this change: Filename shows up and track is saved to the user-specified directory
This was happening because stem files don't have a track name associated with them, they inherit the track name from the parent track file. This has already been incorporated into the "filename" within src/store/social/tracks/sagas.ts 
Tested downloading instrumental version & normal version on mobile. Filename now shows up.
> Stem files don't have a track.title, use filename instead

- src/containers/confirmer-preview/ConfirmerPreview.module.css
- src/containers/discovery-node-selection/DiscoveryNodeSelection.module.css
- src/containers/discovery-node-selection/DiscoveryNodeSelection.tsx
Add current to discovery preview
> Add current discovery node to preview

- src/containers/lineup/LineupProvider.tsx
- src/containers/profile-page/store/lineups/tracks/reducer.js
Skeletons were not loading due to change from MAX_TILES_COUNT to lineupCount in the lineup provider. 
Problem was found to be with lineup.hasMore as a result of having containsDeleted = true. This PR fixes that
Skeleton loading throughout the app
Tested by running through trending, feed pages and noticing skeletons show up. 
Tested by going to Artist profile page and see all tracks (hidden + public showing up)
> [AUD-1035] Fix bug with skeletons not loading on trending

- src/services/audius-backend/TrackDownload.js
- src/services/native-mobile-interface/downloadTrack.ts
QOL fix, send filename instead of title to the mobile-client so the mobile-client doesn't have to generate it.
Ran on iOS simulator and iOS device to ensure download tracks still works
> [AUD-1037] Send filename instead of title

- src/services/audius-api-client/AudiusAPIClient.ts
X-User-ID is added in two places and this one was -Id versus -ID. Previously makeRequest never copied headers, now it does, and this leads to `X-User-ID = (val, val)` instead of `X-User-ID = val` if two cases are sent through.
=> API client
{ 'X-User-ID' : 1 }
=> makeRequest
{ 'X-User-ID' : 1, 'X-User-Id': 1 }
=> axios
{ 'x-user-id' : (1, 1) }
> Fix user id

- src/components/card/mobile/Card.module.css
- src/components/card/mobile/Card.tsx
- src/containers/lineup/CardLineup.module.css
- src/containers/lineup/CardLineup.tsx
When there are two or fewer cards in a CardLineup, or an odd number of cards, the cards render incorrectly due to flex not positioning flex-items in a 2xn grid (the last card tries to take up the whole lower space, centering it). This fix addresses the case for two or fewer cards.
The issue can be reproduced on [staging](https://staging.audius.co/joey), and tested locally using the same user.
> [AUD-1088] Fix CardLineup layout when only 1-2 cards present

- package-lock.json
- package.json
- src/services/audius-api-client/AudiusAPIClient.ts
Relies on changes from - https://github.com/AudiusProject/audius-protocol/pull/2219
if the optimistic api client sees a 404, have it wait for the libs init and use the libs discovery make request method - which retries on another node
Ran manually
> Force libs make request on 404 of resource with optimistic api client

- src/components/general/IconButton.module.css
- src/components/general/IconButton.tsx
Small change to ensure icon buttons use the button html attribute. This helps with a11y, and also enables a small refactor to add the `disabled` prop directly to the button element, which is a bit cleaner.
I wanted to separate this pr, since it affects a lot of elements on the page.
> Refactor IconButton to use button element

- src/services/AudiusBackend.js
This PR is to remove the resumable upload flag since the code is now removed in the protocol dir.
Uploaded track with this key removed and was successful
If track uploads fail, we have sentry and amplitude to catch errors.
> Remove resumable upload flag

- src/common/models/AudioRewards.ts
- src/containers/audio-rewards-page/ChallengeRewardsTile.tsx
- src/containers/audio-rewards-page/config.tsx
- 3 track uploads
- 5 referrals
- Removed 'referred' challenge since we never use it on client
None
locally
> [AUD-1189] Challenges config tweaks

- src/components/action-drawer/ActionDrawer.module.css
- src/components/action-drawer/ActionDrawer.tsx
In order to implement the [ShareModal](https://www.figma.com/file/E2CeYYlz4vc8csivJyJlle/Share-Menu?node-id=501%3A97), the ActionDrawer needs custom styling and icon options.
- Adds custom styling for each action and actions in general
- Reimplements actions to use list and button elements for improved a11y
- Adds optional `id` prop which enables proper list/list-title relationship, improving a11y.
Here is an example leveraging the features in this pr:
> [AUD-1196] Add icons/styling options to ActionDrawer

- src/services/wallet-client/WalletClient.ts
- src/store/wallet/sagas.ts
Update the total balance on the /audio page to include the solana user bank account balance
Also fixes the associated solana wallet balance 
Closes AUD-1173
NOTE: needs libs change to get balance from root account
Ran locally against prod
> Update audio balances on /audio page

- src/common/store/ui/share-modal/sagas.ts
- src/common/store/ui/share-modal/selectors.ts
- src/common/store/ui/share-modal/slice.ts
- src/common/store/ui/share-modal/types.ts
- src/components/action-drawer/ActionDrawer.tsx
- src/containers/share-modal/components/ShareDrawer.module.css
- src/containers/share-modal/components/ShareDrawer.tsx
- Adds copy-link-track action ui to the ShareDrawer
- Extends ActionDrawer to allow each action to provide `onClick` callback to simplify action api
- Adds ShareSource to share slice.
> [AUD-1218] Add copy-link-to-track action to ShareDrawer

- src/containers/track-page/components/mobile/ActionButtonRow.module.css
Fixes margins for action buttons. This regression occurred because a css selector expected the action buttons to be div elements, which changed due to IconButton now rendering a button element.
Before: 
After:
> Fix ActionButton margins

- src/containers/audio-rewards-page/ChallengeRewardsTile.tsx
Add 'Claim Your Reward' button text for undisbursed challenges
Manually tested.
Complete but undisbursed:
Complete and disbursed:
> Add 'Claim Your Reward' button text for undisbursed challenges

- src/components/tracks-table/TableOptionsButton.js
- src/containers/now-playing/NowPlaying.tsx
These variables were missed with the pr to remove all tiktok references in overflow menus: https://github.com/AudiusProject/audius-client/pull/751. 
It's also breaking the build!
> [AUD-1249] Remove extranous shareTikTok references

- src/containers/nav/desktop/NavAudio.tsx
Fixes AUDIO Balance to include solana wrapped wormhole audio in the top left nav
Closes AUD-1219
Ran against stage
> Fix earn audio balance for total balance

- src/containers/nav/desktop/NavAudio.tsx
Adds no tier icon to nav if user does not have a tier
Fixes AUD-1267
ran against stage
> Add no tier icon to nav audio balance

- src/store/routing/mobileSagas.ts
Parameterizes `fromNativeNotifications` in `pushRoute` to allow `goBack` to go back to a web route even if triggered from native mobile. This is necessary for `ChallengeRewardsDrawer`.
https://github.com/AudiusProject/audius-client/blob/189c30ebc9c770487c4ef001c82f61d48e20c156/src/containers/nav/mobile/NavBar.tsx#L129
Tested against changes for `ChallengeRewardsDrawer`
> Allows native mobile to navigate and retain history

- src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
- Prior to this change, if you referred more than the total number of referrals or uploaded more tracks than required for disbursement, the UI shows eg. 5/3 and as though it is in progress. 
- Also brings the text for the error to the `messages` object
Uses the `challenge.is_complete` member instead to determine challenge completion. Steps should never be complete without the challenge being complete, as they're pulled from the same response object.
N/A
Manually against stage
N/A
> Fix rewards progress exceeds total steps

- src/pages/audio-rewards-page/components/modals/HCaptchaModal.tsx
- Decouples the HCaptcha modal from rewards (note: depends on #773 going in in order to keep current behavior)
- fixes minor nit: Use `useCallback` instead of recreating a callback function every render
N/A
Tested manually against stage on top of #773 - HCaptcha modal only reopens if that was the source
N/A
> Decouple HCaptcha modal from Rewards

- src/pages/audio-rewards-page/components/modals/CognitoModal.tsx
Fixes eslint error for an unused variable. React is unnecessary in this component as we're not even using JSX.
> Remove import of unused React

- src/common/services/remote-config/defaults.ts
- src/common/services/remote-config/types.ts
- src/common/store/pages/audio-rewards/selectors.ts
- src/common/store/pages/audio-rewards/slice.ts
- src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
- src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
- src/pages/audio-rewards-page/hooks.ts
- src/pages/audio-rewards-page/store/sagas.ts
Add hook that will return optimistic (client state) version of challenge completions. For now it only includes the profile-completion challenge as others are fine as-is.
Also fetch user challenges periodically to get latest DN challenge state for the user.
This means that if the profile completion is complete from the client perspective but incomplete from DN sides, the reward claim will fail. As-is, we just let it fail and the user can try again.
Manually, running client against stage.
> Add profile completion optimistic update and refresh user challenges periodically

- src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
- src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
Do not optimistically override the challenge current step count if the challenge is already/has already been complete
locally against staging
> Only override current step count if challenge is not complete

- src/common/store/pages/audio-rewards/slice.ts
Resetting the state of userChallenges was causing flickering in the Rewards modals.
Locally against stage (web and mobile)
> Don't reset UserChallenges state on polling refresh

- src/common/store/pages/audio-rewards/slice.ts
- src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
- src/pages/audio-rewards-page/store/sagas.ts
Fixes a bug introduced by the move to using sagas for the claim rewards button. Since the button was being unmounted whenever the modal was closed, it didn't have this problem. But now, the claim is processed in the background and needs to be explicitly stopped on unmount.
Prior to this change, if the claim took sufficiently long, its resolution could come while the user has a different modal open. This could cause the user to see an error on the wrong modal, for instance.
Also removes unnecessary state for `displayError` and `setDisplayError`. As we no longer need to reset the state post-claim, we can simply check the claim state instead.
~The HCaptcha modal sets visibility to false for the challenge reward modal, but should not cancel the claim.~ ✅ 
Is there anything the reviewer should …
> Cancel reward claim on modal close

- src/common/models/AudioRewards.ts
- src/pages/audio-rewards-page/config.tsx
Follows #795 
AUD-1281
Adds config for "referred" challenge despite it not having a modal, as it is needed for the title and amount of the corresponding notification on web.
N/A
Manually against staging
N/A
> [AUD-1281] Add config for referred challenge for notifications

- src/pages/audio-rewards-page/components/modals/RewardsModals.tsx
Hide mobile rewards drawer from web client on native mobile, as the native drawer will pop instead.
iOS simulator with changes from https://github.com/AudiusProject/audius-mobile-client/pull/213
> Use native challenge rewards drawer

- package-lock.json
- package.json
Bump libs to v1.2.54 from v1.5
Diff between last libs bump and current
```
[8220dcd7] Bump libs version to v0.1.2.54 (#2337) Dheeraj Manjunath
[7b480847] Automatically reconnect if content node returns invalid auth token error (#2224) Dheeraj Manjunath
[608a013d] 1.2.53 (#2334) Michael Piazza
[8d35dd5a] [AUD-1309][AUD-1291] Improve Identity challenge attestation (#2332) Michael Piazza
```
> Bump libs to v1.2.54

- src/common/models/AudioRewards.ts
- src/common/store/pages/audio-rewards/slice.ts
- src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
- src/pages/audio-rewards-page/config.tsx
- src/services/audius-api-client/AudiusAPIClient.ts
Discovery Node returns the amount for a reward as a string, but it should be a number. Convert at the root API call so that the client has the amount as a number throughout.
Tested manually against stage - checked UI, claimed reward.
> [AUD-1328] Reward amounts should be numbers

- package-lock.json
- package.json
- scripts/analyzeBundle.js
- src/pages/App.js
Improves load time by preventing large sign-in dependencies from downloading when user already logged in
before:
after:
> Lazy-load sign-in page, reinstate analyzeBundle

- src/common/store/pages/audio-rewards/selectors.ts
- src/common/store/pages/audio-rewards/slice.ts
- src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
- src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
- src/pages/audio-rewards-page/hooks.ts
Uses a new hook to make it clearer how challenge progress is overridden by an optimistic client, and consolidates that logic.
Tested manually against stage
> Consolidate stepCountOverride into useOptimisticUserChallenge hook

- src/common/services/remote-config/defaults.ts
- src/common/services/remote-config/types.ts
- src/common/store/pages/audio-rewards/selectors.ts
- src/common/store/pages/audio-rewards/slice.ts
- src/components/reward-claimed-toast/RewardClaimedToast.module.css
- src/components/reward-claimed-toast/RewardClaimedToast.tsx
- src/components/toast/mobile/ToastLinkContent.tsx
- src/pages/App.js
- src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
- src/pages/audio-rewards-page/store/sagas.ts
- src/utils/sagaPollingDaemons.ts
- Show's a reward claimed toast if identity claims a reward on behalf of a user during a session.
- Moves polling to be during all pages, but is quicker on the $AUDIO page
- Only refresh wallet balance if a challenge was disbursed
Based largely on https://github.com/AudiusProject/audius-client/pull/799/files
Reviewer notes:
- Copies the notification polling daemon logic to a util that can be reused
Tested by mocking responses from discovery, flipping is_disbursed back and forth.
N/A?
> [AUD-1288] Show reward claimed toast when identity claims on user's behalf

- src/common/models/AudioRewards.ts
- src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
- src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
- src/pages/audio-rewards-page/config.tsx
- Support DN's new challenge type, referrals-verified, which is the same as a regular referral challenge but with a higher max referral count.
- DN now returns different lists of challenges per user (verified/not-verified), incorporate that into the display logic
None
Tested with verified + unverified accounts against staging
n/a
> Handle referrals-verified challenge

- src/common/services/remote-config/defaults.ts
- src/common/services/remote-config/feature-flags.ts
- src/common/services/remote-config/types.ts
- src/pages/audio-rewards-page/WalletModal.tsx
- src/pages/audio-rewards-page/components/ReceiveBody.tsx
- src/pages/audio-rewards-page/components/SendInputBody.tsx
- src/store/wallet/sagas.ts
Adds feature flag for enable spl audio and replaces the remote-config enable spl audio variable
If enabled
* adds the user_bank_spl audio to the user's balance
* Update the /audio page to display the solana user bank address instead of the user's eth wallet 
* Update the /audio page to send using sol audio instead of eth audio
Closes AUD-1335
none
Ran against stage
> Add feature flag enable_spl_audio

- src/common/services/remote-config/feature-flags.ts
When loading the /audio page, the challenges do not appear at first and flash in after a second. 
This was due to the challenges component being gated by the feature flag with cohort user-id - which means that the default is returned until the the user id is loaded in, thus causing the delay and subsequent challenges box appearing. 
Fix: Update the cohort to be sessionID - as it shouldn't matter because we're not rolling it out incrementally. 
Fixes AUD-1266
none
manually
> Fix challenges flashing

- src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
- src/pages/audio-rewards-page/RewardsTile.module.css
Sets height of the loading spinning on the mobile rewards challenges tile
Fixes AUD-1325
> Fix height of mobile reward challenges

- src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
- src/pages/audio-rewards-page/components/PurpleBox.module.css
- src/pages/audio-rewards-page/components/PurpleBox.tsx
- src/pages/audio-rewards-page/components/modals/ChallengeRewards.module.css
- src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
- src/pages/audio-rewards-page/config.tsx
- src/pages/audio-rewards-page/hooks.ts
Adds a number of changes for referrals & referrals-verified challenges, documented on Figma and in Linear
- New share to twitter button
- For aggregate challenges, show amount as the max you'd get if every referral was completed
- Some verbiage changes for the verified version of the challenge
- I should probably QA this myself again tomorrow with less covid-brain
- Still needs native mobile changes
- Tested with nonverified + verified acounts
> Add new UI for verified challenges

- src/services/AudiusBackend.js
Changes the check in AudiusBackend to check for strings rather than truthy values to avoid not updating to empty string. Also adds tikTokHandle to update user
N/A
Tested against stage by setting twitter handle to empty string
N/A
> Check for social links being a string rather than truthy

- src/common/services/remote-config/defaults.ts
- src/common/services/remote-config/types.ts
- src/common/store/pages/audio-rewards/selectors.ts
- src/common/store/pages/audio-rewards/slice.ts
- src/components/nav/desktop/NavAudio.module.css
- src/components/nav/desktop/NavAudio.tsx
- src/pages/audio-rewards-page/store/sagas.ts
- src/pages/audio-rewards-page/store/store.test.ts
Adds a "Claim Rewards" button to the nav after waiting for disbursement longer than the configured delay.
New `MANUAL_CLAIM_PROMPT_DELAY_MS` configures how long to delay before prompting the user to claim.
Also adds fade effects for the buttons and hover/active effects to make them button-like.
- Needs to handle the case where both the balance is at 0 and the user has unclaimed challenges
- Rewrites a lot of the existing logic for `NavAudio`
- Adds two additional test cases for testing that the `fetchUserChallenges` saga triggers the appropriate actions.
- Tested manually against stage …
> Add 'Claim Rewards' button in nav

- src/components/notification/store/sagas.ts
When new notification are set, check for ChallengeReward type and trigger a balance refresh if found
Fixes AUD-1393
Ran locally against stage
> Fetch balance refresh on reward notification

- src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
Update invite link to use remote `copyToClipboard` helper so staging env works
Closes AUD-1392
Ran locally
> Update invite friends link to use copylink

- src/pages/App.test.tsx
Not exactly sure why this was passing before, but it makes sense that it should have been breaking since we weren't passing in the required props for `App`
> Fix app test

- src/common/models/Analytics.ts
- src/services/AudiusBackend.js
- src/services/audius-backend/waudio.ts
Adds amplitude tracks for user bank creation.
Since signup also creates a user bank account and is nested in libs, the track method is passed to the signup method which tracks it. Handled in https://github.com/AudiusProject/audius-protocol/pull/2387
Fixes AUD-1324
none
ran locally
> Add amplitude user bank tracking

- src/pages/audio-rewards-page/store/sagas.ts
Starts the fetching of challenges / polling daemon on fetch account
The actions are currently being triggered even for non-signed in users
Ran locally against stage and ensured it started on page refresh when signed in, after signing in, and after signing up and not when not signed in
> Start fetching challenges on get account

- .circleci/config.yml
Update CI to always release the staging desktop apps from master. This will 1. not have a hold on each `master` push that we never do anything about and 2. hopefully see issues in desktop builds earlier (#1 being linux builds are currently breaking!)
CI
> Always release staging electron app

- src/pages/smart-collection/store/sagas.ts
`Explore.getTopUserListens` does _not_ return an array of `UserTrack`s. It hits identity and does not have user objects, but `userIds`. My guess is this failed to break on staging because the users would exist in the cache whenever I would visit the Heavy Rotation page?
This fix adds a fetch to get the users to check for deactivated accounts.
Tested against prod. Bug no longer repros for me.
> Fix Heavy Rotation

- src/pages/smart-collection/store/sagas.ts
- src/services/audius-backend/Explore.ts
- src/store/recommendation/sagas.ts
Use `typed-redux-saga` on the explore page to prevent type errors and to keep types closer to the API client and AudiusBackend.
I did my best to confirm that all the places I used `UserTrack` actually call with `withUsers = true`. But there is a chance I missed one and it's lying.
Tests passed, tested against prod on each explore page tile. Triggered recommendations manually and saw the action put to the store.
N/A
> Add types to the sagas for the explore page

- src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
Previously on the dashboard page, when looking at a specific track and clicking ... -> Visit Track Page, it would not redirect to the track page. This PR fixes that and will redirect to the track page now. 
By clicking visit track page on both hidden and public tracks on the artist dashboard page.
> [AUD-1429] Clicking "Visit Track Page" from artist dashboard not redirecting bug fix

- src/pages/artist-dashboard-page/store/sagas.js
- src/services/AudiusBackend.js
Update artist dashboard to use just the retrieveUserTracks query onto discovery node. Then filter into listed and unlisted tracks. 
Opened /dashboard to confirm both types of tracks are still showing up (listed & unlisted)
> [AUD-1253] Move artist dashboard query to use discovery node

- src/services/audius-backend/waudio.ts
- src/store/wallet/sagas.ts
Validate the recipient address when sending SOL 
Ran locally against prod trying to send to a user bank account that was created and not created
> Validate sol token address

- src/components/public-site/Footer.tsx
> Change 2020 to current year on home page

- src/common/services/remote-config/defaults.ts
- src/common/services/remote-config/types.ts
- src/common/store/pages/audio-rewards/slice.ts
- src/pages/audio-rewards-page/store/sagas.ts
- src/pages/audio-rewards-page/store/store.test.ts
Adds max retry count to claiming logic (instead of a single retry) with exponential backoff
check that it can't infinite loop or break the claim flow
Ran locally against stage and manually forced `AudiusBackend.submitAndEvaluateAttestations` to return unknown error
Also wrote a couple tests
> Adds retry claim with exponential backoff

- src/common/models/User.ts
- src/common/store/challenges/selectors/profile-progress.ts
Fixes a bug where profile pic/cover photo show as completed when unset
> Fix profile completion selector for profile pic/cover photo

- src/common/models/AudioRewards.ts
- src/common/store/challenges/selectors/optimistic-challenges.ts
- src/common/store/pages/audio-rewards/selectors.ts
- src/common/store/pages/audio-rewards/slice.ts
- src/components/nav/desktop/NavAudio.tsx
- src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
- src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
- src/pages/audio-rewards-page/store/sagas.ts
- src/pages/audio-rewards-page/store/store.test.ts
Tracks the individually disbursed challenges so that they can be coalesced into the optimistic challenge and calculate the claimable amount accordingly.
Not that I can think of
Locally against stage, mocking the response of the backend
Tons of manual testing
> [AUD-1478] Adds support for optimistic disbursements of aggregate challenges

- package-lock.json
- package.json
This change includes using `/track_content_status` instead of `/async_processing_status` when polling for track upload updates
No
- ran local dapp against staging 
- upload track and worked
> Bump libs 1.2.65

- src/services/sentry.ts
- src/store/configureStore.ts
- src/store/types.ts
* Fixes the type `AppState` to remove application > pages > profile bc it was moved to the `CommonState` pages > profile 
* Updates sentry to allow deeper nested objects as part of the additional data
* Updates the sentry statepruner to point to the updated profile page state
manually triggered error locally against stage and saw it in sentry
> Fix sentry state pruner

- package-lock.json
- package.json
- src/common/models/AudioRewards.ts
- src/pages/audio-rewards-page/store/sagas.ts
- src/services/AudiusBackend.js
- Consumes latest libs
- Had some typing confusion issues in AudiusBackend messing up the error handling for aggregate challenges.
- Not explicitly handling missing / incomplete challenge errors
None
> Improve error handling for challenges

- src/common/store/index.ts
- src/common/store/solana/selectors.ts
- src/common/store/solana/slice.ts
- src/pages/audio-rewards-page/store/sagas.ts
- src/pages/audio-rewards-page/store/store.test.ts
- src/pages/sign-on/store/sagas.js
- src/services/AudiusBackend.js
- src/services/audius-backend/waudio.ts
- src/store/account/sagas.js
- src/store/sagas.ts
- src/store/solana/sagas.ts
Fetch random solana fee payer from identity and send it through solana relay for rewards and user bank creation.
Here is the protocol counterpart PR: https://github.com/AudiusProject/audius-protocol/pull/2453
Locally by spinning up all services and the client and making sure we get the random fee payer and that it's passed in the right places and that those functionalities still work.
Also updated unit test.
> Support Multiple Fee Payers

- packages/mobile/package-lock.json
- packages/mobile/src/components/challenge-rewards-drawer/ProfileCompletionChecks.tsx
- packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
Various places we display the profile completion stages were not consuming the selector from the `profile-progress` selectors but rather recreating it, and they got out of sync.
Would have opted to use `getOrderedCompletionStages` but didn't want to reorder the stages close to launch.
Also fixes progress bar being hidden when challenges complete on desktop.
Tested against stage on desktop, having issues testing mobile standby
> [AUD-1522] [AUD-1470] [AUD-1467] Fix profile completion stages display

- packages/web/src/pages/audio-rewards-page/components/PurpleBox.module.css
- packages/web/src/pages/audio-rewards-page/components/ReceiveBody.module.css
Update margin for PurpleBox label and removed margin from ReceiveBody label
[AUD-1543]
Manually tested, ReceiveBody PurpleBox still looks good
> Styling updates for PurpleBox for properly formatted single and double line view

- packages/mobile/src/components/audio-rewards/IconAudioBadge.tsx
- packages/mobile/src/components/audio-rewards/audioTier.ts
- packages/mobile/src/components/audio-rewards/index.ts
- packages/mobile/src/components/notifications/NotificationBlock.tsx
- packages/mobile/src/components/notifications/content/TierChange.tsx
- packages/mobile/src/components/notifications/content/TwitterShare.tsx
- packages/mobile/src/components/user-badges/UserBadges.tsx
- packages/mobile/src/screens/profile-screen/ProfileBadge.tsx
- packages/mobile/src/screens/profile-screen/constants.ts
- packages/mobile/src/store/notifications/types.ts
- Moves common audio-rewards code into `components/audio-rewards`
- Simplifies usage of AudioBadges with IconAudioBadge
- Renames some helpers to be more clear
- Prep work for TierExplainerDrawer
> Consolidate audio-rewards

- packages/web/src/common/models/User.ts
- packages/web/src/components/nav/desktop/NavAudio.tsx
- packages/web/src/store/wallet/sagas.ts
Follows TODO and relies on stored `account.total_balance` field if the wallet manager has not recovered balance (yet).
This avoids some of the "popping" in. Of course the "Claim Rewards >" pops in
Locally vs. prod on my account
> Optimize happy path $AUDIO nav balance

- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/mobile/src/Drawers.tsx
- packages/mobile/src/components/audio-rewards/TierText.tsx
- packages/mobile/src/components/audio-rewards/TiersExplainerDrawer.tsx
- packages/mobile/src/components/audio-rewards/audioTier.ts
- packages/mobile/src/components/audio-rewards/index.ts
- packages/mobile/src/components/core/GradientText.tsx
- packages/mobile/src/components/drawer/AppDrawer.tsx
- packages/mobile/src/components/drawer/Drawer.tsx
- packages/mobile/src/screens/edit-profile-screen/index.ts
- packages/mobile/src/screens/profile-screen/ProfileBadge.tsx
- Adds `TiersExplainerDrawer`
- Adds `LinearGradientProps` to `GradientText`
- Adds `AppDrawer` to handle the `isOpen` and `onClose` logic. Can eventually use this for every drawer.
- Adds `type-fest` type library to help with various things. Using `SetOptional` to help with prop modification in this PR
> [AUD-1009] Add TiersExplainerDrawer

- packages/web/src/components/card/desktop/Card.tsx
- packages/web/src/components/card/desktop/CollectionArtCard.tsx
- packages/web/src/components/card/desktop/UserArtCard.tsx
- packages/web/src/components/card/mobile/Card.tsx
- packages/web/src/components/edit-playlist/mobile/EditPlaylistPage.tsx
- packages/web/src/components/search-bar/ConnectedSearchBar.js
- packages/web/src/components/search/SearchBarResult.js
- packages/web/src/components/upload/UploadArtwork.js
- packages/web/src/hooks/useCollectionCoverArt.ts
- packages/web/src/hooks/useTrackCoverArt.ts
- packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
- packages/web/src/pages/upload-page/components/FinishPage.js
Somehow, during the course of the monorepo work, most of the blank image paths got changed to the default cover photo path. I don't know how this happened, I'll be in the corner
> [AUD-1678] Update blank image to correct path

- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/services/AudiusBackend.js
- Bumps libs to 1.2.84 
- Stop using `submitAndEvaluate` and opt for `processChallenges` for all challenges
Test error handling
Tested locally against staging, but not against various errors.
> Bump Libs to 1.2.84 and use processChallenges

- packages/mobile/src/components/lineup/Lineup.tsx
- packages/mobile/src/components/lineup/types.ts
- packages/mobile/src/screens/feed-screen/FeedScreen.tsx
- packages/mobile/src/screens/profile-screen/RepostsTab.tsx
- packages/mobile/src/screens/profile-screen/TracksTab.tsx
- packages/mobile/src/screens/track-screen/TrackScreen.tsx
- packages/mobile/src/screens/trending-screen/TrendingLineup.tsx
- packages/web/src/common/store/lineup/actions.ts
- Migrates lineup actions to ts to make it easier to import and use lineup actions
- Implements play/pause actions in lineup using new types
- Removes redundant play/pause implementations
We may want the ability to know when a track is played/paused from outside the lineup. Rather than keep the `playTrack` `pauseTrack` props, thinking we add`onPlay`, `onPause` callbacks at that point?
> Migrate lineup action to ts, implement play/pause in lineup

- packages/web/src/common/models/Analytics.ts
- packages/web/src/common/services/remote-config/feature-flags.ts
- packages/web/src/pages/sign-on/store/sagas.js
* Adds `DISABLE_SIGN_UP_CONFIRMATION` feature flag. Hoping this allows more users to successfully sign up while most discprovs are behind
* Adds `SIGN_IN_WITH_INCOMPLETE_ACCOUNT` event to track users who get into bad sign up state
This could potentially break many things. Since we aren't confirming, the user is potentially missing data until they get indexed. This especially causes problems when signing out immediately and trying to sign back in. We added analytics to determine if more users end up in this bad state
Tested social actions, creating playlists, etc while in an unindexed state and things seem to work pretty well
New analytics event. Monitoring sign up success rate
> Add feature flag to disable sign up confirmation

- packages/mobile/package.json
Missing space in `cd..` causes last part of the command to fail
> Fix missing space in ios:update-signing-cert script

- packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
- packages/web/src/common/store/cast/sagas.ts
- packages/web/src/common/store/cast/slice.ts
- packages/web/src/common/store/index.ts
- packages/web/src/store/configureStore.ts
- packages/web/src/store/reducers.ts
- packages/web/src/store/sagas.ts
- packages/web/src/store/storeContext.ts
This change fixes the cast integration with the common store and also addresses the local storage issue in common.
Curious for feedback on this approach, but I figured that abstracting the complexity around storage away from the sagas and reducers themselves is the way to go.
One annoying thing is of course that AsyncStorage is async and local storage interaction is not, so local storage really can't be used in a common store reducer. I'm guessing that there will be more platform-specific context to be passing in for system APIs in the future though.
Not actively used yet
Locally vs. …
> [AUD-1611] Fix airplay and cast for native

- packages/web/src/common/models/PlaylistLibrary.ts
- packages/web/src/common/store/ui/createPlaylistModal/actions.ts
- packages/web/src/common/store/ui/createPlaylistModal/reducer.ts
- packages/web/src/common/store/ui/createPlaylistModal/selectors.ts
- packages/web/src/common/store/ui/createPlaylistModal/types.ts
- packages/web/src/components/create-playlist/CreatePlaylistModal.tsx
- packages/web/src/components/create-playlist/PlaylistForm.tsx
- packages/web/src/components/nav/desktop/NavColumn.js
- packages/web/src/components/nav/desktop/NavColumn.module.css
- packages/web/src/components/nav/desktop/PlaylistLibrary.module.css
- packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
- packages/web/src/pages/profile-page/ProfilePageProvider.tsx
- packages/web/src/pages/saved-page/components/mobile/NewPlaylistButton.tsx
- packages/web/src/store/playlist-library/helpers.ts
-Functionality for creating playlist folder (note - drag/drop not implemented but some starter code is in there)
-Hide folder tab if the modal isn't opened from the desktop sidebar 
Note these changes are reliant [on schema changes](https://github.com/AudiusProject/audius-protocol/pull/2610). 
[Designs
](https://www.figma.com/file/u8UHdkD60030aqsRkItWUV/Playlist-Folders?node-id=101%3A141)
-Product should be unchanged if the feature flag `playlist_folders` is not on
-Try creating playlist folder in browser …
> Create playlist folder functionality

- packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
- packages/mobile/src/screens/profile-screen/TracksTab.tsx
Fixes issue where default loadMore wasn't including userId, leading to a load error for users with more than 12 tracks
- also patches type error
> Fix profile track-tab loadMore

- packages/mobile/src/components/audio-rewards/TiersExplainerDrawer.tsx
- packages/mobile/src/components/lineup/Lineup.tsx
- packages/mobile/src/hooks/selectors.ts
- packages/mobile/src/screens/profile-screen/AlbumsTab.tsx
- packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
- packages/mobile/src/screens/profile-screen/CoverPhoto.tsx
- packages/mobile/src/screens/profile-screen/EmptyProfileTile.tsx
- packages/mobile/src/screens/profile-screen/ExpandableBio.tsx
- packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
- packages/mobile/src/screens/profile-screen/ProfileBadge.tsx
- packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
- packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx
- packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
- packages/mobile/src/screens/profile-screen/ProfileSocials.tsx
- packages/mobile/src/screens/profile-screen/ProfileTabNavigator.tsx
- packages/mobile/src/screens/profile-screen/RepostsTab.tsx
- packages/mobile/src/screens/profile-screen/Sites.tsx
- packages/mobile/src/screens/profile-screen/TracksTab.tsx
- packages/mobile/src/screens/profile-screen/selectors.ts
- packages/mobile/src/screens/profile-screen/utils.ts
- packages/mobile/src/screens/trending-screen/TrendingLineup.tsx
Cuts down profile page rerenders from 60 (at the root) to 3 for the entire profile stack
- Uses hook selector hybrids to share equality functions, but open to defining whatever pattern we want.
There are assumptions made with the selectors that prevent potential re-renders that are necessary for some subcomponents to function (ie expecting nested profile data that gets added in a separate re-render)
Ran through various profiles to ensure things look the same
If there seems to be data missing on the profile page, we will look into existing selectors as one of the first points of triage
> [AUD-1632] ProfileScreen performance

- packages/web/src/components/edit-playlist/desktop/EditPlaylistModal.module.css
- packages/web/src/components/edit-playlist/desktop/EditPlaylistModal.tsx
- packages/web/src/components/nav/desktop/NavColumn.module.css
- packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
- packages/web/src/components/nav/desktop/PlaylistLibrary.module.css
- packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
- packages/web/src/components/nav/desktop/PlaylistNavItem.tsx
Allow editing playlists from sidebar (desktop)
See designs [here](https://www.figma.com/proto/u8UHdkD60030aqsRkItWUV/Playlist-Folders?page-id=101%3A141&node-id=748%3A4421&viewport=282%2C48%2C0.08&scaling=min-zoom&starting-point-node-id=748%3A4421&show-proto-sidebar=1)
This addition is guarded under the `playlist_folders` feature flag
Make sure this doesn't break any existing playlist UI/functionality
Adding Amplitude events in one PR after reaching feature completion
*For features that are critical or could fail silently please describe the monitoring/alerting being …
> Allow editing playlists from the sidebar

- packages/web/src/pages/upload-page/UploadPage.js
- Selecting identical tracks (either in the same drag-and-drop session, or already selected and in the state) will skip duplicates
None
Tested locally
Looking for error rate of MULTI_TRACK_UPLOAD decreasing
> [AUD-1616] Disallow identical track uploads in same session

- packages/mobile/src/WebAppManager.tsx
- packages/mobile/src/hooks/useSelectorWeb.ts
- packages/mobile/src/message/handleMessage.ts
- packages/mobile/src/message/handlers/commonState.ts
- packages/mobile/src/message/types.ts
- packages/mobile/src/screens/feed-screen/FeedScreen.tsx
- packages/mobile/src/store/clientStore/slice.ts
- packages/mobile/src/store/common/slice.ts
- packages/mobile/src/store/index.ts
- packages/web/src/services/native-mobile-interface/types.ts
- packages/web/src/store/configureStore.ts
After getting some conflicting signals, I was finally able to confirm that the expensive part of the state syncing operation is sending large amounts of data over the message bridge. Here is an average case of the times in ms for each leg of the trip:
Sending only the changed top-level entries of the state over the bridge, the `Web -> Mobile` time was decreased by ~75%. This specific case was for an update in the `pages` slice
We could probably further improve this by flattening the redux state, but that might get into diminishing returns
Also includes:
* Rename `clientStore` to `commonState` for clarity
* Added some useCallbacks to prevent rerenders on FeedScreen
Using reference equality on the web layer to determine which slices have changed, so theoretically the mobile state should …
> [AUD-1638] Partial web -> mobile state syncing

- packages/mobile/src/components/app-navigator/AppNavigator.tsx
- packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
- packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
This PR removes extra logic at the AppNavigator level to allow enabling certain RN screens individually. Since we decided to roll all the screens out at once, this is a little more performant
Wraps the BottomTabNavigator in a check for if the navigation is enabled, this prevents RN screens from rendering when they are supposed to be disabled. Shouldn't cause issues though
Manually on ios simulator
Not deployed yet
> Remove logic to individually enable RN screens

- packages/web/src/pages/audio-rewards-page/store/sagas.ts
Allows us to remove the config from optimizely by setting it to be empty and allowing libs to select for us.
Tested against stage with stage having empty endpoints config.
We have an amplitude dashboard [here](https://analytics.amplitude.com/audius/dashboard/0ebjc1d), and one of those charts shows [error counts by type](https://analytics.amplitude.com/audius/chart/76f22tw). If we see a spike of INSUFFICIENT_DISCOVERY_NODES when setting the config to an empty string, we know that the …
> Check for empty endpoint config

- packages/mobile/src/components/core/VirtualizedScrollView.tsx
- packages/mobile/src/components/lineup/Lineup.tsx
- packages/mobile/src/components/lineup/types.ts
- packages/mobile/src/screens/feed-screen/FeedScreen.tsx
* Properly aligns scroll bar to right on ios
* hides the scrollbar on the feed screen
n/a
ios simulator
n/a
> [AUD-1647] Fix Scrollbar

- packages/web/src/components/data-entry/TabSlider.js
- packages/web/src/pages/App.js
- packages/web/src/services/Logging.ts
- packages/web/src/services/native-mobile-interface/logging.ts
Fixes two issues when loading settings page using null-renderer:
- React.lazy seems to not work
- refs will sometimes not be attached and their values will be null.
We may have a future issue where we can't use react.lazy in places that we would like. The fix here will need to be build-time webpack code-mod to either use `React.lazy(....)` or `require(...).default` https://webpack.js.org/plugins/define-plugin/
> Fix settings-page when null-rendering

- packages/web/src/components/nav/desktop/NavColumn.module.css
- packages/web/src/components/nav/desktop/PlaylistNavItem.tsx
Before:
After:
Note the changes causing the "before" here hasn't been released yet so as long as this gets in before the next release we should be fine. 
> Quick fix for update dot styles

- packages/mobile/src/components/animated-button/AnimatedButtonProvider.tsx
- packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
- packages/mobile/src/components/bottom-tab-bar/BottomTabBarButton.tsx
- packages/mobile/src/components/core/CardList.tsx
- packages/mobile/src/components/core/VirtualizedScrollView.tsx
- packages/mobile/src/components/lineup/Lineup.tsx
- packages/mobile/src/components/lineup/types.ts
- packages/mobile/src/hooks/useScrollToTop.ts
- packages/mobile/src/screens/explore-screen/tabs/ForYouTab/ForYouTab.tsx
- packages/mobile/src/screens/profile-screen/AlbumsTab.tsx
- packages/mobile/src/screens/profile-screen/CollectiblesTab.tsx
- packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
- packages/mobile/src/screens/profile-screen/RepostsTab.tsx
- packages/mobile/src/screens/profile-screen/TracksTab.tsx
* Adds custom `useScrollToTop` hook that supports nested tab navigators (unlike the one provided by react-navigation)
* Triggers scroll to top on long tab press and focused tab press
* Does not scroll to top on profile tab page tab press
https://user-images.githubusercontent.com/19916043/157122124-7c97c617-bc55-478e-acab-e483c3d11f7e.mov
Attaching listeners to a few events, they get cleaned up but could have slight performance/memory impact
iOS simulator
Not released yet
> [AUD-1648] RN Scroll To Top

- packages/web/src/components/nav/desktop/NavColumn.module.css
- packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
- packages/web/src/components/nav/desktop/PlaylistLibrary.module.css
- packages/web/src/components/nav/desktop/PlaylistNavItem.tsx
-Fix regression I caused where long playlist names were clipped instead of ellipsis-ed (not in prod yet)
-Fix spacing in between playlist links (too big before) to match [these designs](https://www.figma.com/file/u8UHdkD60030aqsRkItWUV/Playlist-Folders?node-id=101%3A141) 
-Consolidate some styles
Tested in browser with long and short playlist/folder names, playlist folder flag on/off, playlist updates/not
> Fix more styling issues in the nav column 😩

- packages/mobile/src/components/audio-rewards/RewardsBanner.tsx
- packages/mobile/src/components/core/Tile.tsx
Adds press animation when tile is pressable.
This affects all tiles that are pressable. It seems like a fair assumption that any tile with onPress should have an animation, though.
> [AUD-1669] Add tile press animation

- packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
- packages/mobile/src/components/overflow-menu-drawer/CollectionOverflowMenuDrawer.tsx
- packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
Fixes two issues:
1. Overflow menu `View Track/Collection Page` and `View Artist Page` were not hooked up with native navigation
2. When clicking overflow menu items that trigger navigation, the NowPlayingDrawer would not close
It is def a bit interesting the way this pr implements this fix. Curious of folks thoughts
> [AUD-1603] Fix overflow menu nav, close now-playing drawer on navigate

- packages/mobile/src/WebAppManager.tsx
- packages/mobile/src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx
- packages/mobile/src/components/core/DynamicImage.tsx
- packages/mobile/src/components/details-tile/DetailsTile.tsx
- packages/mobile/src/components/lineup/Lineup.tsx
- packages/mobile/src/screens/feed-screen/FeedScreen.tsx
- packages/mobile/src/screens/track-screen/TrackScreen.tsx
This PR:
* Reduces rerenders related to loading the track screen
* Fixes the scroll indicator on Lineup based pages
* Fixes the flashing of images on Track/Collection screens
Added some pretty specific selector equality functions around track screen, if omitted data is needed in the future it will be important to update those
ios simulator
when released
> [AUD-1625] TrackScreen performance and DynamicImage fix

- packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx
- packages/mobile/src/components/lineup-tile/LineupTileRoot.tsx
- packages/mobile/src/components/lineup-tile/LineupTileSkeleton.tsx
- packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
* Adjusts height of LineupTileStats to avoid height shift when replacing skeleton with LineupTile
* Apply width to container of LineupTileActionButtons to prevent the buttons from moving during render (The lottie animation buttons take a bit longer to load)
There will still be shift when loading Collections in a lineup, this is expected and current behavior
iOS simulator
n/a
> [AUD-1623] Fix LineupTile layout shift

- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
- packages/web/src/components/nav/desktop/PlaylistLibrary.module.css
- packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
-Show/hide playlist folder contents
I refactored the playlist library component a bit to enable the library contents nesting - need to make sure this doesn't break anything. I tested things pretty thoroughly on staging (no playlists/folders, playlists with updates, playlists/folders with long names, etc) but wasn't quite sure how to test the `playlistsNotInLibrary` functionality (will comment in PR).
Tested in browser using fake data for folder contents
> Implement expanding/collapsing folders

- packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
- packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
- packages/web/src/pages/audio-rewards-page/config.tsx
Remove config related to step counts. It was only being used in the rewards tile, and was causing discrepancies between what DNs were reporting and what the client showed.
N/A
Verified the rewards tiles look good on stage.
N/A
> [PAY-83] Remove step counts from rewards config

- packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawer.tsx
- packages/mobile/src/screens/audio-screen/Panel.tsx
- packages/mobile/src/utils/challenges.tsx
- packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
- packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
- packages/web/src/pages/audio-rewards-page/config.tsx
Adds commas to amount/step numbers in rewards page/modal
Also fixes bug with the progress text on mobile
Tested manually on web desktop and iOS native
> Add commas to numbers

- packages/web/src/components/dragndrop/Droppable.js
- packages/web/src/components/nav/desktop/NavColumn.module.css
- packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
- packages/web/src/components/nav/desktop/PlaylistLibrary.tsx
- packages/web/src/components/nav/desktop/PlaylistNavItem.tsx
- packages/web/src/store/playlist-library/helpers.test.js
- packages/web/src/store/playlist-library/helpers.ts
UI / functionality for dragging a playlist (from library or tile) into a collapsed or expanded folder (general area)
Up next: Reordering playlists/folders incl. playlists within folders
Shouldn't affect anything in prod / outside of folders feature flag
Unit tests + tested in browser 
> Add playlists to folders functionality

- packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx
- packages/mobile/src/components/app-navigator/TopTabNavigator.tsx
- packages/mobile/src/components/lineup/Lineup.tsx
- packages/mobile/src/components/lineup/types.ts
- packages/mobile/src/components/user/ProfilePicture.tsx
- packages/mobile/src/hooks/selectors.ts
- packages/mobile/src/screens/profile-screen/AlbumsTab.tsx
- packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
- packages/mobile/src/screens/profile-screen/CoverPhoto.tsx
- packages/mobile/src/screens/profile-screen/EmptyProfileTile.tsx
- packages/mobile/src/screens/profile-screen/ExpandableBio.tsx
- packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx
- packages/mobile/src/screens/profile-screen/ProfileBadge.tsx
- packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
- packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx
- packages/mobile/src/screens/profile-screen/ProfilePicture.tsx
- packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
- packages/mobile/src/screens/profile-screen/ProfileSocials.tsx
- packages/mobile/src/screens/profile-screen/ProfileTabNavigator.tsx
- packages/mobile/src/screens/profile-screen/RepostsTab.tsx
- packages/mobile/src/screens/profile-screen/Sites.tsx
- packages/mobile/src/screens/profile-screen/SubscribeButton.tsx
- packages/mobile/src/screens/profile-screen/TracksTab.tsx
- packages/mobile/src/screens/profile-screen/selectors.ts
- packages/mobile/src/screens/profile-screen/utils.ts
- packages/mobile/src/screens/settings-screen/AccountSettingsRow.tsx
- packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
- packages/mobile/src/screens/track-screen/TrackScreen.tsx
- packages/mobile/src/screens/user-list-screen/UserChip.tsx
- packages/web/src/common/store/pages/profile/selectors.ts
Uses new selector equality and selectors to drastically minimize profile rerenders and push them as far down the render tree as possible.
Experimenting with `lazy: true` for profile tabs. This helps with navigation animation by quieting down other tabs.
A few improvements to Lineup
- Show skeleton on initial mount, which improves perceieved perf as the lineups don't suddenly show skeletons
- Check the `limit` prop before rendering skeletons or loading more. this allows us to immediately show `ListEmptyComponent`, which is useful for our EmptyProfileTiles
A bit of a hack adding `initalParams: {handle: "accountUser"}}` which is a way to immediately tell account profile tab to render with account user data
> [AUD-1684]: ProfileScreen performance

- packages/mobile/ios/fastlane/Fastfile
We get rejected by AppStoreConnect for build 57 even though the CLI returns 56 as the latest version.
🤷 
CI should pass
> Increment build number by 2 to unblock apple

- packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
- packages/mobile/src/components/bottom-tab-bar/BottomTabBarButton.tsx
- packages/web/src/store/configureStore.ts
* Adds `200ms` debounce to the state sync. Noticed that much of the button lag had to do with the volume of state sync actions happening on native. This was the case even when no components were rendering. Debouncing/batching the updates helped a lot here. Because of the partial state sync, we now have to aggregate the state to sync across debounce calls
* Adds a `50ms` delay to the navigation when pressing a bottom button. This allows the button highlight state and animation to feel much more snappy because it doesn't get blocked by the huge render of the incoming screen. The delay is nearly imperceptible, but does increase perceived performance IMO
* Allows long presses to trigger normal press handler on non active routes 
https://user-images.githubusercontent.com/19916043/158232418-f484 …
> [AUD-1692] Native bottom button performance round 2

- packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
- packages/mobile/src/utils/theme.ts
* Adds notification badge
N/A
Tested on iOS sim with various numbers of notifications
QA on mobile
> [AUD-1641] Add notification badge in native

- packages/mobile/src/components/core/Button.tsx
* Fixes an issue with full width button contents not being centered
* Fixes the color of the text on buttons in dark mode
Potentially all buttons affected
Tested on iOS simulator. Did a sweep and all the buttons look good
n/a
> [AUD-1686] Button style fixes in native

- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
* Adds hidden track header
N/A
ios sim
N/A
> [AUD-1636] Add hidden track header on native

- packages/web/src/components/card/mobile/Card.tsx
- packages/web/src/components/lineup/CardLineup.tsx
- packages/web/src/pages/explore-page/components/mobile/CollectionsPage.tsx
Before:
Could drag album tile to playlist library, which would be a no op
Could not drag album tile to "Favorites" list
After:
Can only drag album tile to "Favorites" list
> Fix album draggable bug

- packages/mobile/src/components/core/DynamicImage.tsx
* Fixes a bug that was introduced due to the equality check in DynamicImage changing
DynamicImage rerender behavior could be affected
iOS sim. No longer exceeding max render depths for images
N/A
> [AUD-1742] Fix issue with DynamicImage rerenders

- packages/web/src/common/store/cache/users/sagas.js
- packages/web/src/store/playlist-library/helpers.test.js
- packages/web/src/store/playlist-library/helpers.ts
Before:
1. Create a playlist
2. Quickly reorder the playlist or add it to a folder. This triggers a cache + local storage update with the new library order (which includes the temp playlist).
3. Refresh
4. Result: Temp playlist gets stuck in local storage, which prevents any user playlist library updates from being persisted because we wait for all temp playlists to be resolved before updating the user metadata
After:
Temp playlists never get put in local storage which prevents the corrupted state described above. 
Tested in browser using repro steps above
*For features that are …
> Fix local storage temp playlist bug

- packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.module.css
- packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.tsx
- packages/web/src/components/nav/desktop/NavColumn.js
- packages/web/src/components/nav/desktop/NavColumn.module.css
*Cannot be merged until corresponding [Stems PR](https://github.com/AudiusProject/stems/pull/107) is merged and Stem is bumped in this repo.*
Switch out old react-simplebar for near Scrollbar which uses react-perfect-scrollbar. Simplebar does not respond to content size changes well, which causes the scrollbar to look super glitchy when the content does change (I tried fixing it for a while with some props/CSS changes to no avail). React-perfect-scrollbar is able to do so smoothly and is generally more widely used than Simplebar.
I'm currently in the middle of switching out all instances of Simplebar but wanted to get these two out first.
Before:
After:
Tested in browser.
*Please describe the …
> Switch out scrollbar for new one in add playlist modal and nav bar to avoid jumpiness

- packages/mobile/src/components/details-tile/DetailsTile.tsx
- packages/mobile/src/components/details-tile/types.ts
- packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
- packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
- packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Fixes a bug where the play button would show playing even if the current track wasn't queued
Updates `PlayBar` and `AudioControls` play buttons to use `iconIndex`
N/A
iOS sim
Testflight qa
> [AUD-1741] [AUD-1744] Fix Play button state on track/collection screen

- packages/mobile/src/screens/user-list-screen/UserChip.tsx
Fixes issue where long names don't overflow correctly
> [AUD-1773] Fix user-list name overflow

- packages/mobile/src/components/core/Tile/Tile.tsx
- packages/mobile/src/components/core/Tile/TileShadow.tsx
- packages/mobile/src/components/core/Tile/index.ts
- Adds shadow inset to Tile
- Adds layered shadows to simulate multiple box-shadows
Before:
First attempt:
Final:
- There may be a perf issue doing this, now that each tile renders 3x the shadows
- I followed our box-shadow specs for each shadow exactly, but it def looks funky, so we should modify things before merge
> [AUD-1761, AUD-1670] Add shadow offset and multiple shadows

- packages/mobile/src/components/now-playing-drawer/TrackInfo.tsx
[AUD-1768]
Small fix to center the icons
Needed to use a View to actually center them and then needed another to make sure that they didn't go off the side when the artist name was really long
N/A
N/a
> [AUD-1768] Update artist info in now playing drawer to center icons

- packages/mobile/src/screens/search-results-screen/SearchFocusContext.tsx
- packages/mobile/src/screens/search-results-screen/SearchResultsScreen.tsx
- packages/mobile/src/screens/search-results-screen/TagSearchScreen.tsx
- packages/mobile/src/screens/search-results-screen/tabs/SearchResultsTab.tsx
- packages/mobile/src/screens/search-results-screen/tabs/TracksTab.tsx
- packages/mobile/src/screens/search-screen/SearchBar.tsx
Fixes a few loading issue with search results:
- Fixes case where "no results" briefly shows up in between the loading component and the results list.
- Fixes case where popping back to search results shows old list, then loading component, then list again. For now we are following what prod mobile does, which is show a loading component on pop-back.
- Fixes case where search-results tracks have a secondary loading status (inside tracks.status) that is slightly different from searchStatus that was not being referenced, resulting in extra flash of "no-results" every time.
> [AUD-1775] Improve search results loading state

- packages/web/package-lock.json
- packages/web/package.json
Bump libs to 1.2.94. This will include consuming a new route called /async_processing_status instead of /track_content_status
> Bump libs to 1.2.94

- packages/mobile/src/screens/search-results-screen/tabs/TracksTab.tsx
Incorrectly imported trackLineup results in issue where user unable to play track from search-results track list
> [AUD-1788] Fix play track from search-results

- packages/mobile/src/components/lineup/Lineup.tsx
Improves track tile click animation by delaying the cpu intensive tasks (queueing) until after the animation finishes
- Obviously this slightly slows down play/pause responsiveness. In testing it seems okay, but something to watch out for.
- I also considered adding the `setImmediate` to all tile `onPress` actions since that would ensure all animations are smooth. Curious what folks think about that idea and its tradeoffs
> [AUD-1779] Improve track tile click animation fluidity

- packages/mobile/ios/Podfile.lock
- packages/mobile/package-lock.json
- packages/mobile/package.json
Upgrades to use @rickyrombo fixes for react-native-linear-gradient
Before:
After: 
> [AUD-1770] Use latest react-native-linear-gradient

- packages/mobile/src/components/drawer/Drawer.tsx
BIG PR
* Fixes a bug where the drawer would pop to the top of the screen. This usually happened when lots of other processing was going on and the `onLayout` callback wasn't called immediately
Affects drawers, but the actual height should always get set and therefore this shouldn't be dangerous
iOS sim
TestFlight QA
> [AUD-1671] Prevent Drawer from popping to top of screen

- packages/web/package.json
- packages/web/src/components/drag-autoscroller/DragAutoscroller.tsx
- packages/web/src/components/nav/desktop/NavColumn.js
- packages/web/src/components/nav/desktop/NavColumn.module.css
- packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx
Sadly the new scrollbar component doesn't play well with native drag and drop scrolling - see https://github.com/mdbootstrap/perfect-scrollbar/issues/100 and https://stackoverflow.com/questions/55482184/auto-scroll-while-dragging-an-item-with-perfect-scrollbar-and-sortablejs.
This means that when you drag something to the top or bottom of the nav container, it doesn't scroll automatically like it used to.
This PR adds back that functionality manually (+ a shadow indicator when you're drag-scrolling up or down).
*For features that are critical or could fail silently …
> Add drag auto scroll capability for custom scrollbar containers

- packages/mobile/src/components/lineup/Lineup.tsx
- packages/mobile/src/screens/feed-screen/FeedScreen.tsx
- packages/mobile/src/screens/root-screen/RootScreen.tsx
* Fixes the issue with the feed not loading after sign in
This was due to the strange boolean logic we have to switch between `SignOnStack` and `MainStack`. `authed` is always true initially because the dapp has not yet loaded, which causes the feed screen to render while the splash screen is still visible. The feed lineup uses `selfLoad` which is fine when the account already exists in state, but when signing in the feed has already tried to load with no user and failed. Then no new fetch is performed on the lineup
We should probably improve the boolean logic there, could be as simple as checking `signedIn`. But trying that resulted in a flash of blank screen after the splash screen because the feed screen takes a second to render
The kinda hacky fix here is to set `selfLoad` based on …
> [AUD-1781] Fix issue with feed not loading after sign in

- packages/web/src/common/store/notifications/reducer.ts
- packages/web/src/common/store/pages/audio-rewards/slice.ts
* Updates some reducers to not update state when not necessary. This allows the equality checks to be more accurate when determining when to sync state to the mobile layer
* Removes a todo and special case for `listen-streak` challenge types. See: https://linear.app/audius/issue/AUD-1536/fix-challenge-overrides-for-completed-challenges
Touches rewards reducers which could be dangerous
iOS sim, checked that empty sync actions were reduced
TestFlight QA
> [AUD-1812] Prevent unnecessary store syncs

- packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
Fixes issue where PlayBar has opacity < 1 at resting point since opacity interp is not taking into place it's height relative to the NowPlayingDrawer height.
Down to make `NOW_PLAYING_HEIGHT - PLAY_BAR_HEIGHT a constant, but not sure of the name
> [AUD-1817] Fix PlayBar opacity

- packages/mobile/src/components/core/FlatList.tsx
- packages/mobile/src/components/core/PullToRefresh.tsx
- packages/mobile/src/components/core/SectionList.tsx
Removes pull-to-refresh on track screen. Also goes the extra step and removes refresh indicator for any section-list that doesn't explicitly pass down an `onRefresh` function. Curious if the way it was implemented is best!
> [AUD-1800] Remove pull-to-refresh on track screen

- packages/mobile/src/components/core/DynamicImage.tsx
- packages/mobile/src/components/lineup-tile/LineupTile.tsx
Improves the transition handoff from track-tile skeleton to track-tile content by starting the content fade-in at 50%, which is a similar color to the skeleton gray color. Happy to continue adjusting if it seems like it could be better!
https://user-images.githubusercontent.com/8230000/162079739-bb37081a-f8ac-451f-906b-5f368b81c531.mov
With the dynamic image opacity change:
https://user-images.githubusercontent.com/8230000/162080902-7ceebc81-8406-4c2d-8121-2569d00d228c.mov
> [AUD-1824] Improve track-tile skeleton transition

- packages/mobile/src/screens/audio-screen/AudioScreen.tsx
* Fixes missing padding at bottom of audio screen by using `Screen` component
N/A
iOS simulator
TestFlight QA
> Fix audio screen bottom padding

- packages/mobile/src/components/now-playing-drawer/TrackingBar.tsx
[AUD-1852]
Fixed the interpolation for the TrackingBar opacity. A bit hacky, but the effect looks good
N/A
N/A
> [AUD-1852] Fix opacity interpolation for the mobile tracking bar

- packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
* Uses the provided `CastButton` to trigger the cast dialog so that network permissions are properly obtained
There isn't a good way to render the provided `CastButton` in the background and trigger it. So we are kinda tied to the icon and animations provided out of the box. However, with styling the button looks pretty similar to the rest of the UI
iOS device in release config
TestFlight QA
> [AUD-1807] Fix Chromecast permissions

- packages/mobile/src/components/track-list/TrackListItem.tsx
[AUD-1843]
* Small styling update for deleted tracks and disabled the TouchableOpacity
Can't quite figure out why the track in the issue is disabled, but other deleted tracks show as deleted
N/A
> [AUD-1843] Update styles for deleted track list items

- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/services/LocalStorage.ts
- packages/web/src/types/libs/libs.d.ts
Upgrades libs to latest, and includes fixes for constants that were imported directly from libs/src, which isn't supported anymore.
> Upgrade libs to 1.2.105, adds constants patch

- packages/mobile/src/components/lineup/Lineup.tsx
The Lineup had an issue where when the end threshold was reached while metadata was still loading, no new load would be triggered because the check against offset was happening during the load.
This fixes the issue by separately keeping track of if the threshold has been reached and then triggering a fetch when the lineup load finishes
A more ideal solution could be to remove the check against offset completely, allowing for free scrolling. But this results in duplicate/unordered lineup items so would need to be a bigger feature.
Touches lineup loading, potentially dangerous.
iOS sim
TestFlight QA
> [AUD-1857] Fix issue with scrolling to bottom of Lineup

- packages/mobile/src/components/navigation-container/NavigationContainer.tsx
- packages/mobile/src/components/web/WebApp.tsx
- packages/mobile/src/screens/app-screen/ExploreTabScreen.tsx
- packages/mobile/src/screens/app-screen/FavoritesTabScreen.tsx
- packages/mobile/src/screens/app-screen/FeedTabScreen.tsx
- packages/mobile/src/screens/app-screen/ProfileTabScreen.tsx
- packages/mobile/src/screens/app-screen/TrendingTabScreen.tsx
- packages/mobile/src/screens/root-screen/RootScreen.tsx
* Configures mapping so deep links go to correct screens
* Need to run in release configuration to test links when the app is not already running. 
* Came across some logic for handling recovery params, not sure if we already have this implemented in the new app. Will need to double check on this
iOS sim
TestFlight QA
> [AUD-1845]  Configure deep linking

- packages/mobile/src/components/lineup-tile/CollectionTile.tsx
- packages/mobile/src/components/lineup-tile/LineupTile.tsx
- packages/mobile/src/components/lineup-tile/TrackTile.tsx
- packages/mobile/src/components/lineup-tile/types.ts
- packages/mobile/src/components/lineup/Lineup.tsx
[AUD-1858]
There may be unintended regression added to certain flows with the TrackTile. Please keep an eye out for that
Manually tested. Play-pause for collection tile works and the title switched to primary color
N/A
> [AUD-1858] Move isPlayingUid logic back into TrackTile and CollectionTile and fix Collectiontile play-pause logic

- packages/web/src/store/configureStore.ts
* Removes the debounce from the state sync. This was added to help with lag when navigating between screens via the bottom tabs, but other performance improvements have made it unnecessary
* Still seems to be a slight delay with the Share drawer sometimes, but there is not much rendering going on so if anything it's probably some small latency with the message bridge. Think it should be ok for now
Could potentially be a lot of rerenders again in places that I didn't check
iOS sim in dev and release configs
TestFlight QA
> [AUD-1855] Improve drawer performance

- packages/web/src/store/configureStore.ts
* Adds back the state sync debounce at 50ms to fix lag when playing tracks
This is basically what we had before but instead of 200ms
iOS sim
TestFlight QA
> Add back state sync debounce

- packages/mobile/src/screens/search-results-screen/tabs/SearchResultsTab.tsx
Fixes case where loadMore would cause loading-indicator to render. We only want to show loading-indicator when we are loadingMore and there are no current lineup items.
> [AUD-1886] Fix search results refresh

- packages/mobile/src/components/core/PullToRefresh.tsx
Fixes bug where the initial scroll on a lineup would trigger a scrollTo(0) bug, which is needed when pull-to-refresh is triggered.
> [AUD-1884] Fix scrollTo bug on initial scroll

- packages/mobile/ios/AudiusReactNative/AppDelegate.m
- packages/mobile/src/components/audio/GoogleCast.tsx
* Fixes issue where chromecast session was suspended when app was backgrounded
* Starts the chromecast media at the correct time to prevent the scrubber from bouncing between 2 values. (There are still some instances where it occasionally gets off by like 1 second, but I think this is due to the latency of starting the session)
Removes unused `openChromecastDialog` function
iOS device (lock screen controls don't work on simulator)
TestFlight QA
> [AUD-1859] Fix lock screen media controls when chromecasting

- packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
* Fixes issues with the text at the top of the Track Remixes lineup
N/A
iOS sim
TestFlight
> [AUD-1896] Fix text on remixes lineup

- packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx
Remove gesture responder capture to allow track tile to be clicked in the bottom part
Not sure if there was a reason we didn't allow this initially, or if any unintended issues arise from this change
Manually tested, click play works and the buttons still work 
N/A
> Allow TrackTile click in the action button section

- packages/mobile/src/screens/track-screen/TrackScreen.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Silently disabling the play button until the 'more by this artist' lineup loads to avoid the weird play-pause behavior
N/A
N/A
> Silently disable play button on track screen until the lineup loads

- packages/mobile/src/components/lineup/Lineup.tsx
- packages/mobile/src/components/lineup/types.ts
- packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
- packages/mobile/src/screens/track-screen/TrackScreen.tsx
- packages/mobile/src/screens/track-screen/TrackScreenRemixes.tsx
- packages/web/src/common/store/pages/track/lineup/reducer.js
* Adds "Remix of" UI
* Fixes issue with Remixes screen lineup loading
* Fixes issue with track screen with no other tracks by artist lineup loading
Shuffled some things around on track screen, added a max of 6 on the track screen Lineup (this was only enforced at the component level for some reason)
iOS sim
TestFlight QA
> [AUD-1894] Remix Lineup fixes

- packages/mobile/src/components/core/FlatList.tsx
- packages/mobile/src/components/core/SectionList.tsx
* Adds onto the fixes for onScroll being passed correctly to the SectionList/Flatlist. Our custom onScroll wasn't being called for the collapsible versions of these components
`forkEvent` https://reactnative.dev/docs/0.67/animated#forkevent
iOS sim
TestFlight
> [AUD-1902] Fix scroll to end of lineup on profile page

- packages/mobile/src/screens/explore-screen/components/ColorTile.tsx
When swiping quickly in explore screen sometimes the color tiles register a press event
> Prevent ColorTile presses when swiping

- packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
- packages/mobile/src/screens/notifications-screen/NotificationBlock.tsx
- packages/mobile/src/screens/notifications-screen/NotificationsDrawerNavigationContext.tsx
- packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx
- packages/mobile/src/screens/notifications-screen/content/Entity.tsx
- packages/mobile/src/screens/notifications-screen/content/User.tsx
- packages/mobile/src/screens/notifications-screen/content/UserImages.tsx
- packages/mobile/src/screens/profile-screen/TracksTab.tsx
* Prevents notif rerenders on navigation by changing the NotificationsDrawerNavigationContext to not provide an object and wrapping NotificationScreen in memo
Could prevent the notifs screen from being render when it was before so could see some state out of sync
iOS sim
TestFlight
> [AUD-1899] Reduce notif rerenders on navigation

- packages/mobile/src/hooks/useNavigation.ts
- packages/mobile/src/hooks/usePopToTopOnDrawerOpen.ts
- packages/mobile/src/screens/app-screen/AppTabScreen.tsx
- packages/mobile/src/screens/app-screen/transitionSpec.ts
- packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
- packages/mobile/src/screens/explore-screen/ExploreScreen.tsx
- packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
- packages/mobile/src/screens/feed-screen/FeedScreen.tsx
- packages/mobile/src/screens/notifications-screen/NotificationBlock.tsx
- packages/mobile/src/screens/notifications-screen/content/Entity.tsx
- packages/mobile/src/screens/notifications-screen/content/User.tsx
- packages/mobile/src/screens/notifications-screen/content/UserImages.tsx
- packages/mobile/src/screens/notifications-screen/routeUtil.ts
- packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
- packages/mobile/src/screens/trending-screen/TrendingScreen.tsx
* Disables transition animations on the stack when coming from notifications so that the content is immediately there
* Changes back button and swiping gesture to open the notifications drawer after going to a nested stack screen from a notification
https://user-images.githubusercontent.com/19916043/163479038-48abb9c4-30f0-425d-a691-b85e26f496f3.mov
This touches a lot so I think we should probably hold off on merging this until we have the release cut
iOS simulator
TestFlight
> [AUD-1888] Notification transitions

- packages/web/src/store/lineup/sagas.js
Reduce the delay to speed up the lineup metadata saga
N/A
Tested for a while, and didn't notice any issues or places where lineups did not load.
N/A
> Reduce the delay for the lineup metadata saga

- packages/mobile/patches/@react-navigation+drawer+6.3.1.patch
* Fixes 2 issues with swiping from the first tab in a tab navigator:
* Swiping perfectly horizontally wouldn't register as a swipe
* Swiping to go back from a pushed stack screen didn't register every time
https://user-images.githubusercontent.com/19916043/163634521-6c93d63f-db92-4638-93a8-cacf5693a874.mov
Another patch, arbitrarily set `-1` and `1` values. Seems to work but I might have broken something else
iOS sim. swiping tabs, stack screens, notifications, etc
TestFlight QA
> Fix swipe on first tab

- packages/mobile/src/screens/trending-screen/TrendingScreen.tsx
* Rename trending ThisYear to AllTime (This was done on web already)
N/A
iOS simulator
TestFlight
> Rename trending ThisYear to AllTime

- packages/mobile/src/components/now-playing-drawer/Artwork.tsx
* Uses 1000x1000 art on NowPlaying
Before & After
Slow load times for images in NowPlaying
iOS sim
TestFlight QA
> [AUD-1904] Use high res artwork on NowPlaying

- packages/mobile/src/components/now-playing-drawer/TrackInfo.tsx
* Vertically align user badges on now playing
Possible layout changes on different sized screens
iOS sim
TestFlight QA
> [AUD-1927] Vertically align user badges on now playing

- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
* Fixes behavior of TrackScreen button to match that of CollectionScreen
Changing logic slightly, but it's actually more consistent with the rest of the app (including Lineup)
iOS sim, playing/pausing from track screen when another track is already playing. Compared to working CollectionScreen
TestFlight
> Fix behavior of track screen play button

- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/common/store/cache/reducer.js
- packages/web/src/common/store/cache/tracks/sagas.js
- packages/web/src/services/AudiusBackend.js
When we get Unauthorized (403) from the getCID route: https://github.com/AudiusProject/audius-protocol/pull/2951, avoid showing the content.
Note this is a stop gap solution in favor of a broader fix that indexes this data and makes it available to discovery nodes: https://linear.app/audius/project/better-track-unavailability-ui-c676176f9b93
Locally vs. production data on tracks getting 403s.
> [AUD-1930] Avoid showing content that gets a 403 (stop-gap)

- packages/mobile/src/components/details-tile/DetailsTile.tsx
* Adds haptics to track/collection screen play buttons
N/A
iOS
TestFlight
> Add haptics to other play buttons

- packages/mobile/src/components/audio-rewards/TierText.tsx
Fixes app breaking bug on legacy android app. Issue was due to linear gradient breaking when not receiving at least 2 colors.
> [C-405] Fix legacy android build profile freeze

- packages/mobile/src/components/scrubber/Slider.tsx
Fixes a few scrubber issues to improve responsiveness and jumpiness
- Reset handle position to 0 when starting a new song. Fixes issue where dragging after a new song plays results in handle skipping to end of song, since we never reset
- Tie handle press animations with `onTouchStart` and `onTouchEnd` to prevent cases where clicking in but not dragging results in handle and track staying in pressIn animation.
- Ensure handlePosition is calculated onHandlePressIn so drags use the correct handlePosition, which fixes issue where handle would be out of sync with drags.
> [C-293, AUD-1936] Fix track scrubber gestures

- .circleci/src/jobs/@mobile-jobs.yml
- .circleci/src/jobs/@web-jobs.yml
Builds have been failing a decent bit for resource issues. Bump the resource spec from large to xlarge for web builds. Ideally this wouldn't be necessary, but not a huge deal.
On CI via release branch
https://app.circleci.com/pipelines/github/AudiusProject/audius-client?branch=release-4-20-22&filter=all
> Bump resource class size

- packages/web/src/store/wallet/sagas.ts
Account balance already includes eth and spl audio. And the total balance adds the spl audio again.
So, we are counting the spl audio balance twice in the balance check when sending $audio.
make sure that fix makes sense
did not test
n/a
> Fix waudio amount check and error message

- packages/mobile/src/components/lineup/Lineup.tsx
- packages/web/src/common/models/Lineup.ts
- packages/web/src/common/store/lineup/actions.ts
- packages/web/src/common/store/lineup/reducer.ts
- packages/web/src/common/store/pages/profile/lineups/tracks/reducer.js
- packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
- packages/web/src/common/store/pages/search-results/reducer.ts
- packages/web/src/components/lineup/Lineup.tsx
- packages/web/src/components/lineup/LineupProvider.tsx
- packages/web/src/store/lineup/sagas.js
* Instead of slicing the artist pick out of the response, set it to null and keep track of the null count to avoid messing up the offset
This could break lineups
Locally against prod, web and ios
Michael will confirm fix
> [C-403] Fix lineup with artist pick

- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/services/AudiusBackend.js
- packages/web/src/services/LocalStorage.ts
Upgrades libs to latest, which includes large typescript refactor. Along with this we can start using the new dist/core entrypoint for constants and other values that need to be used separately from the libs main entrypoint (since that is dynamically imported)
> Upgrade libs to 1.2.112, use core entrypoint

- packages/mobile/package-lock.json
- packages/mobile/src/screens/profile-screen/CoverPhoto.tsx
* Fixes crash on profile screen by disabling blur view (added an issue to update `react-native-screens` when the fix is released)
There will be no blur on android cover photo on scroll
Android device
TestFlight / playstore beta
> [C-419] Fix react native Android profile screen crash

- packages/mobile/src/components/lineup/Lineup.tsx
* On android a "Malformed js calls" error was crashing the app because the lineup `limit` and `offset` were `NaN` because `deleted` and `nullCount` were undefined. Defaulting to 0 fixes the issue
No dragons but this was a pain to debug. If we see this in the future, this stackoverflow answer helped a lot: https://stackoverflow.com/a/67100389/5705462
Android and ios
TestFlight / playstore
> [C427] Fix malformed js calls error

- packages/mobile/src/components/core/AnimatedButton.tsx
- packages/mobile/src/components/now-playing-drawer/PlayButton.tsx
* Adds resizeMode='cover' to the play button to fix the sizing on android. Not entirely sure why it's only needed on the play button and not other animated buttons but some context here: https://github.com/lottie-react-native/lottie-react-native/issues/428
Sizing of play button could be off
Tested on android and ios
TestFlight / playstore
> [C-414] Fix size of PlayButton on android

- packages/web/src/components/nav/store/context.tsx
It's annoying that the entire app breaks when switching from mobile to desktop requiring a refresh. This moves us towards the path of gracefully handling window changes.
> [AUD-1645] Prevent app error on resize

- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/mobile/src/components/core/FormTextInput.tsx
- packages/mobile/src/components/core/SearchInput.tsx
- packages/mobile/src/components/core/SegmentedControl.tsx
* Fixes styling issues around TextInputs on android
* Downgrades lottie-react-native to what we had before because it caused a crash on certain animations using colorFilters
* Removes shadow from segmented control on android
Styling could affect ios, but I double checked and everything looks good!
Android and ios
TestFlight / playstore
> [C-415] Fix search styling on android

- packages/mobile/src/components/core/FlatList.tsx
- packages/mobile/src/components/core/SectionList.tsx
* Adds pull to refresh on android
Unfortunately, android does not support "overscrolling" or scrolling past the ends of a scrollview (contrary to what this prob would lead you to believe https://reactnative.dev/docs/scrollview#overscrollmode-android). So there is no way to use the same refresh indicator as we do on ios. Instead, we can use the native android one which looks a lot better than on ios
The only strange part of this is on the collapsible tabs on the profile screen. The indicator shows at the top of the list instead of at the top of the screen, which looks a little weird when scrolling down while the indicator is visible. But I think probably the best we can do for now because when shown at the top, the header covers the indicator and there seems to be no way of bringing the …
> [C-422] Add pull to refresh on android

- packages/web/src/utils/zIndex.ts
Small issue with the zindex value of the artist popover where the popup would show up behind modals.
Reverting to its previous value of 20000 which seems like overkill, but it works
N/A
N/A
> Revert ArtistPopover zIndex value to its previous value

- packages/web/src/services/AudiusBackend.js
Fixes case where legacy images don't load properly in native.
- Cleans up redundant extra fetch (libs already handles this logic)
Legacy images load on native, and still load on desktop/mobile web
> [C-462] Fix legacy image loading for native

- packages/mobile/android/app/src/main/AndroidManifest.xml
- packages/mobile/src/components/core/Hyperlink.tsx
- packages/mobile/src/screens/profile-screen/ExpandableBio.tsx
* Fixes the positioning and functionality of bio links on android
* Fixes issue without text cut off due to `numberOfLines=2`
This was already pretty fragile code and now it's even more fragile. Have to use `measureInWindow` on the refs of the links to get the position instead of `onLayout` because `onLayout` doesn't return correct values on android
iOS and android
TestFlight, play store
> [C-424] Fix profile screen bio links on android

- packages/mobile/package-lock.json
- packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/common/utils/formatUtil.ts
Fixes issue where long titles mess up RemixesScreen text wrapping
Before:
After: 
Learned that Pressable has a bug where it doesn't align well with text, the suggested workaround is to just use the onPress on Text components since we don't care about onPresIn, onPressOut: https://stackoverflow.com/questions/66590167/vertically-align-pressable-inside-a-text-component
> [C-475] Fix RemixesScreen header text alignment

- packages/mobile/src/components/top-tab-bar/TopTabNavigator.tsx
- packages/mobile/src/screens/app-screen/AppTabScreen.tsx
- packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
- packages/mobile/src/screens/notifications-screen/NotificationBlock.tsx
- packages/mobile/src/screens/notifications-screen/NotificationsDrawerNavigationContext.tsx
- packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx
- packages/mobile/src/screens/notifications-screen/content/Entity.tsx
- packages/mobile/src/screens/notifications-screen/content/User.tsx
- packages/mobile/src/screens/notifications-screen/content/UserImages.tsx
- packages/mobile/src/screens/root-screen/RootScreen.tsx
* Prevents the notification drawer from opening when swiping tabs on android. Luckily android doesn't have the same nondeterminism in gesture handlers so I was able to do this completely in js, didn't have to touch native android code
https://user-images.githubusercontent.com/19916043/167898569-99c9f7c1-4924-42e9-8bcd-0416ab30c861.mp4
* Refactors the NotificationDrawer context to provide the actual drawer navigation as well as the drawer helpers
Toggling the notification drawer on and off has a slight delay so occasionally if swiping very quickly it can still open when it shouldn't. It's pretty minor though
android and ios
TestFlight / play store beta
> [C-416] Fix swiping behavior with tabs/notifications on android

- packages/mobile/src/components/web/WebApp.tsx
* Allow os back button to be handled by react navigation by removing custom handler in WebView
Previously we were sending a `nav-go-back` action to web but I believe this is no longer necessary because we are updating the web route after the native route changes
android and ios
TestFlight / play store beta
> [C-460] Enable os back on android

- packages/mobile/src/screens/audio-screen/AudioScreen.tsx
* Numeric separators break the react native build 😞 : https://app.circleci.com/pipelines/github/AudiusProject/audius-client/5183/workflows/8846317f-18b8-4bb4-9c81-ac2ccd5977d2/jobs/38878
Tried some solutions in here https://github.com/facebook/metro/issues/645 but they didn't work so I opted to remove the separators
n/a
built locally
circle ci
> Remove numeric separators to fix react native build

- packages/web/package-lock.json
- packages/web/package.json
- packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
- packages/web/src/services/AudiusBackend.js
Form JWT containing user's profile information to send back to the redirect URI.
> C-408 Send OAuth read-only response

- .circleci/config.yml
- .circleci/src/jobs/@web-jobs.yml
* A couple of build steps are failing because they are looking for the old location of the AASA file. I believe these steps are no longer necessary because the AASA file is part of the build in the public folder now
* Updates ci config to trigger both web and mobile flows when only ci config has changed
Possibly breaking AASA
Waiting for CI steps to pass
Verify that CI passes and universal links continue to function
> Remove CI steps for old way of handling AASA file

- packages/web/src/components/notification/Notification/Notification.tsx
- packages/web/src/components/notification/Notification/components/NotificationTile.tsx
Adds ErrorBoundary to NotificationTile so issues with notification tiles don't break the whole page. This is necessary because we are still not strictly typing notification types, so there are cases where we expect users to be present when they aren't. Hoping to address this after native notifications, since the notification types need to be changed wholesale!
> [PAY-212] Add ErrorBoundary to NotificationTile

- packages/mobile/src/components/navigation-container/NavigationContainer.tsx
Fixes issue where clicking on an nft-playlist deep link opens the track screen and breaks.
Also fixes case where audius.co links weren't picked up
> [C-528] Fix nft playlist deep link

- packages/mobile/src/components/core/Button.tsx
- packages/mobile/src/components/core/Text.tsx
- Adds `corner` prop to button
- Adds `inherit` option for `color` prop for text
is `corner` the prop type we want here? the goal is to have a "variant" type option for pill vs rounded buttons.
> [C-537] Add button corner prop, text inherit color

- packages/web/src/common/utils/genres.ts
Previously, the Lo-Fi genre was filtered out of trending genres due to being a new genre. At this point we have enough music to show, so this change reveals lofi music in trending.
N/A
ran client locally against stage
N/A
> aud-1172 show lofi in trending genre pickers

- packages/web/src/common/services/remote-config/remote-config.ts
- packages/web/src/pages/profile-page/sagas.js
- packages/web/src/store/account/sagas.js
Add new waitForUserRemoteConfig for feature flags that depend on user
n/a
local against stage and tested the tipping feature flag returns true on profile sagas; it used to always be false.
> Add new waitForUserRemoteConfig for feature flags that depend on user

- packages/mobile/src/components/core/Screen.tsx
Fixes pesky issue where header elements clash between transitioning screens:
Before: 
https://user-images.githubusercontent.com/8230000/170350616-325f8305-7f90-4a8a-8d7c-303ece41b174.mov
After: 
https://user-images.githubusercontent.com/8230000/170350725-47dd1042-eb29-4355-b85c-2f9abc3baa3a.mov
> [C-545] Fix native screen transition jank

- packages/mobile/src/message/handlers/lifecycle.ts
* The user id was never being set on the optimizely client on native, resulting in feature flags with the user_id cohort to always return false. Fixed by setting the user id on the `signed_in` message 
n/a
Confirmed that the TikTok feature flag returns true
> [C-546] Fix USER_ID cohort feature flags on native

- packages/web/src/components/tipping/tip-audio/TipAudio.module.css
- packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
Fixes transitions in the tip modal by not getting the state from the selector inside of `ModalContent`. Also gets rid of the custom durations and simplifies the "next/previous" logic.
Before:
https://user-images.githubusercontent.com/3690498/170397327-dcf41827-e0b1-47e9-899b-4655713b6e0e.mov
After:
https://user-images.githubusercontent.com/3690498/170397496-b72d8a4f-8dac-4b0b-b01b-230f92335989.mov
Tested locally against stage. Needs QA from design.
> [PAY-231][PAY-180] Fix Tip Modal Animation Transitions

- packages/web/src/common/models/Wallet.ts
- packages/web/src/common/store/tipping/slice.ts
- packages/web/src/common/store/tipping/types.ts
- packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
- packages/web/src/components/tipping/tip-audio/SendTip.tsx
- packages/web/src/components/tipping/tip-audio/TipSent.tsx
- packages/web/src/store/tipping/sagas.ts
Changes tipping slice amount type from BNWei to StringAudio, which fixes case where `dispatchWeb` incorrectly serializes BNWei (by calling .toString()), resulting in different mobile vs web behavior. Moving to StringWei helps since that is directly serializable across apps.
Also changes StringWei type to be a string alias since it's unclear how these types are actually `string & {_brand: string}` maybe in the future we can change the stringaudio data to properly match these types though.
Changing the underlying type may have messed up the tipping flow, so lets def check this works before merging
Types pass, but a local run-through is needed
> [PAY-261] Refactor tipping slice amount type from BNWei to StringAudio

- packages/mobile/src/screens/notifications-screen/NotificationErrorBoundary.tsx
- packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
Adds native notification error boundary to prevent weird notification type edge cases from breaking app. This is temporary until we properly type all notifications to prevent run time errors.
> Add native notification error boundary

- packages/mobile/src/screens/profile-screen/ExpandableBio.tsx
Fixes issue where expandible bio links were rendering on top of one another: 
Before: 
After: 
The render flow that seems to fix this is:
1. Render the bio with `Text` component
2. Check that it's size is large enough to show `expand` button
- If it's not large enough, replace `Text` with `Hyperlink` component
- If it is large enough, keep rendering the `Text` component with 32 height when not expanded (setting height on `Hyperlink` is causing the issue i believe), and replace `Text` with `Hyperlink` when expanded
The one not perfect case is when the bio is expandable, but closed. in that case we still render the text element, so any links on the first two lines of bio wont be clickable till the bio is expanded.
> [C-552] Fix expandible-bio link render issue

- packages/mobile/src/components/drawer/Drawer.tsx
Fixes issue where drawers don't open enough for android phones with navigation bar.
> Fix android drawer height issue

- packages/web/src/components/notification/NotificationPanel.tsx
Context: https://audius-internal.slack.com/archives/C03C2V84A1L/p1653598933291159
Scroll threshold for loading in new notifications was recently changed to 400 - increasing back to 1000 to minimize occurrences of "jumping" when you hit the bottom and more notifs load.
> Reset scroll threshold to 1000

- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/mobile/src/components/scrubber/Slider.tsx
Fixes bug where now-playing scrubber is incorrectly positioned when coming back to app, esp after a new song starts.
The code here in general is a bit complex, and this adds yet another useEffect. there are cases where this may be a duplicate call with another useEffect when mediaKey changes. From what i can tell this is okay, though ideally we look at all thees effects and consider ways to make them simpler/work together.
> Fix slider handle position when re-entering from background

- packages/mobile/src/screens/favorites-screen/TracksTab.tsx
- packages/web/src/pages/saved-page/SavedPageProvider.tsx
Fixes bug where favorites tab always resets causing bad user experience
Before: 
https://user-images.githubusercontent.com/8230000/171063496-4f817ce5-6304-4af6-8cea-4e08d8f33c59.MP4
After:
https://user-images.githubusercontent.com/8230000/171063688-004a2420-18be-4c60-ae03-d025db18f124.mov
Just to be safe, we prevent clear only on native
> Prevent favorites tab from resetting on navigation

- packages/mobile/src/screens/trending-screen/TrendingFilterDrawer.tsx
Fixes case where selecting a genre requires two presses after filtering with input: one to dismiss keyboard, and a second to select the genre. we should probably add this functionality to favorites tab filters as well
> Fix double press issue when filtering in filter genre drawer

- packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
- packages/mobile/src/screens/settings-screen/CastSettingsRow.tsx
Fixes pretty bad bug where now-playing drawer always shows airplay for android devices, always leading to fatal error when clicked. Users can't switch to chromecast either since we dont show the option in settings.
Also fixes bug where ios cast setting doesn't default to the actually selected cast method.
> Fix casting for android, setting for ios

- packages/web/src/components/tipping/support/Support.module.css
- packages/web/src/components/tipping/support/SupportingTile.tsx
Before:
After:
Before:
After:
Locally against stage.
N/A
> [PAY-286][PAY-291] Fix cover photo stretch and displayname overflow in supporting tiles

- packages/web/src/components/tipping/tip-audio/SendTip.tsx
- packages/web/src/services/audius-api-client/AudiusAPIClient.ts
Ensures that the tip amount suggested to become top supporter takes into account the current tipped amount.
Decided to have it _not_ cache the result as the cache would serve very little utility, as sending repeat tips to the same artists warrants a refetch anyway.
Tested manually locally against staging accounts using stage DN1.
N/A
> [PAY-281] Fetch current user tip amount if not already loaded when tipping

- packages/web/scripts/workers-site/index.js
Currently the snapchat browser is treated as a bot and gets the GA meta response:
According to https://developers.snap.com/robots the correct user agent for a bot is "Snap URL Preview Service; bot; https://developer.snapchat.com/robots". This updates our regex to look not just for `snap` but for `snap url preview` to not treat the normal snap browser (which has a user agent that looks like "Snapchat/11.69.0.36 (SM-S908B; Android 12#S908BXXU1AVC6#31; gzip) V/MUSHROOM") as a bot.
Possible other user agent strings for Snapchat preview things?
❗ N/A 👻  - tested the regex against user …
> Fix Snapchat browser going to GA

- packages/web/src/store/token-dashboard/sagas.ts
- packages/web/src/utils/error.ts
Adds error message helper, which gracefully handles extracting error message from catch block error.
Fixes one of our many error cases
Note, this will be useful for the incoming typescript upgrade from v3 to v4 in web.
Information about the type situation, and inspiration for helper: 
https://kentcdodds.com/blog/get-a-catch-block-error-message-with-typescript
> Add error message helper

- packages/web/src/components/artist/ArtistCard.tsx
- packages/web/src/components/artist/ArtistCardCover.tsx
- packages/web/src/components/artist/ArtistPopover.tsx
- packages/web/src/components/artist/ArtistSupporting.tsx
Dismisses the artist hover tile when an interaction within it causes a modal to pop or the page to navigate.
- *Note:* The page navigation one is redundant, as it was being dismissed anyway due to its parent being unmounted. Added support anyway for consistency
- Required some particularly gritty debugging and also requires https://github.com/AudiusProject/stems/pull/136
- Before the stems change, the hover tile would get unmounted before the click event would even fire since the modal (its parent) would dismiss via a listener to mousedown
- Putting the modal `useOutsideClick` on the click event makes it part of the same event bubbling, thus the outside click happens _after_ the supporting tile …
> [PAY-224] Dismiss Popover when navigating away

- packages/mobile/src/components/feed-tip-tile/ReceiverDetails.tsx
- packages/mobile/src/components/user/ProfilePicture.tsx
- packages/mobile/src/screens/notifications-screen/Notification/ProfilePictureList.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ProfileHeaderV2.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeaderV2/TopSupporters.tsx
- packages/mobile/src/screens/user-list-screen/TopSupportersScreen.tsx
- packages/mobile/src/screens/user-list-screen/UserList.tsx
Add mobile profile top supporters section below the tip audio button (or upload button if user in own profile)
n/a
on native ios locally against local dapp pointing to staging
n/a
> Add mobile profile top supporters

- packages/web/src/components/tipping/support/Support.module.css
- packages/web/src/components/tipping/support/SupportingTile.tsx
Fixes the background of the supporting tiles to have the gradient matching figma
Note the values of the gradient - I pulled these from Figma but they vary based on which supporting tile I inspected in the figma. I picked the values that matched the bug description appearance the closest.
Locally against staging using Chrome on Mac
N/A
> [PAY-292] Adjust Supporting tile gradient

- packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.module.css
Fix border radius on profile mutuals tile.
See that it's similar to the top supporters tile in the image below.
n/a
n/a
> Fix border radius on profile mutuals tile

- packages/web/src/components/notification/Notification/components/UserProfilePictureList.module.css
- packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.module.css
- packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.tsx
See commits
[PAY-307](https://linear.app/audius/issue/PAY-307/[currently-live]-too-much-space-below-title-margin-top-should-be-12px)
[PAY-226](https://linear.app/audius/issue/PAY-226/profile-picture-list)
[PAY-310](https://linear.app/audius/issue/PAY-310/[currently-live]-change-the-border-of-the-photos-to-neutral-light-10)
[PAY-249](https://linear.app/audius/issue/PAY-249/[currently-live]-hover-state-shadow-is-wrong-on-supporter-supporting)
Note: Need to update supporter/supporting tiles as well! …
> [PAY-307][PAY-226][PAY-310][PAY-249] Hotfixes for Mutuals Tile

- packages/web/src/common/models/Analytics.ts
- packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
Add option to send the auth response back in the query string instead of the fragment (default behavior).
Fragment is default behavior because it's better for security (since fragments don't get sent in requests to servers), but some consumers might need the query param option for their implementation.
> Add response mode param to Oauth

- packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.tsx
Use the followee follow count prop instead of number of users for profile mutuals.
n/a
n/a
> [PAY-320] Use correct number for total followee follow count

- packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.tsx
Use the followee follow count prop instead of number of users for profile mutuals.
n/a
n/a
> Use correct number for total followee follow count

- packages/web/src/components/tipping/support/Support.module.css
- packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.module.css
Udpate profile support and mutuals tiles and and content transitions based on:
- On Hover, let’s make all of these mutuals/supporters/supporting tiles grow by 1.01 (instead of 1.005)
- let’s change the active state on tiles from .995 to .99
- And let’s keep duration of .18s for the tile
- lets do .07s for the purple (both the text and the arrow icon)
n/a
n/a
> Udpate profile support and mutuals tiles and and content transitions

- packages/web/src/components/notification/Notification/components/UserProfilePictureList.module.css
- packages/web/src/components/notification/Notification/components/UserProfilePictureList.tsx
- packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.module.css
- packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.tsx
Review by commit if necessary
- Centers the tooltip in the profile picture list by giving the container a size of 40x40
- Adds a shadow overlay to the +N profile picture tile by adding a semitransparent overlay circle (would have done `filter` but that affects the profile picture border)
- Disables clicking the profile pictures in mutuals
- Makes profile images grow instead of shrink
- Disables grow effect if not clickable
> [PAY-317][PAY-321] Fix tooltip, +N tile in mutuals tile

- packages/web/src/common/store/cache/users/sagas.js
Wouldn't you know it, mutable state strikes again!
I noticed that even with the cache update action commented out the pictures were still loading. It turns out that the `user._profile_picture_sizes` was updating the user object and the cache update action wasn't causing the `getProfile` selector to run again.
Changing this to an immutable update causes the cache update to actually rerender the profile page. 
I was having a hard time reproing the initial issue, so I added some long delays on the picture fetching to recreate the issue. Would love if someone who can repro the initial issue could double check this fix!
Locally against prod
> [PAY-315] Fix mutuals profile pics loading

- packages/web/src/components/follow-button/FollowButton.js
- packages/web/src/components/user-list/components/UserList.tsx
After adding the event listener to the modal user list rows, clicking the follow button shouldn't propagate the click to the row.
Tested against stage (Mac Chrome)
> [PAY-323] Don't dismiss modal when clicking the follow button

- packages/web/src/components/follow-button/FollowButton.js
Looks like the button was also triggering `useClickOutside` when clicking the icon for some reason. This hotfix should fix that.
Locally against stage on Chrome Mac
> [PAY-323] Stop immediate propagation on follow button click

- packages/mobile/src/screens/profile-screen/ProfileHeaderV2/TopSupporters.tsx
Currently, we show profile top supporters even if there are none. Clicking on it shows an empty list modal. This PR hides that section altogether if the profile has no supporters.
n/a
local mobile app vs local dapp vs stage
n/a
> Hide profile top supporters on mobile if none

- packages/web/src/components/artist/ArtistChip.module.css
- packages/web/src/components/artist/ArtistChipTips.tsx
Fix spacing between rank and audio amount in the top supporters list modal
n/a
n/a
> [PAY-277] Fix spacing between rank and audio amount

- packages/web/src/components/artist/ArtistSupporting.module.css
- packages/web/src/components/artist/ArtistSupporting.tsx
Render empty container when artist supporting is loading
https://user-images.githubusercontent.com/9600175/173122547-65c753de-a211-4ad5-b184-d7ae95d558e7.mov
n/a
n/a
> [PAY-278] Render empty container when artist supporting is loading

- packages/mobile/src/screens/notifications-screen/routeUtil.ts
- packages/mobile/src/screens/user-list-screen/NotificationUsersScreen.tsx
Fixes two issues with native follow notifications with 8+ followers
- Fixes incorrect title count by using `userIds` instead of `users` (which is limited to 8)
- Fixes user-list loading by renaming the tag correctly
> [C-576] Fix NotificationUsersScreen title, large list

- packages/mobile/src/screens/notifications-screen/Notification/ProfilePictureList.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeaderV2/TopSupporters.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ViewAllSupportingTile.tsx
Add +N UI on mobile profile picture list component
_(the first two images do not represent the accurate number of profile pictures for notififications and profile top supporters that would trigger the limit for the +N UI, it's only for illustration purposes)_
make sure that the correct number of profile pictures is displayed on different components that use the profile picture list
local mobile vs local dapp vs stage
n/a
> [PAY-324] Add +N UI on mobile profile picture list component

- packages/mobile/src/components/feed-tip-tile/SenderDetails.tsx
- packages/mobile/src/screens/app-screen/AppTabScreen.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeaderV2/TopSupporters.tsx
- packages/mobile/src/screens/user-list-screen/SupporterInfo.tsx
- packages/mobile/src/screens/user-list-screen/TopSupportersScreen.tsx
- packages/mobile/src/screens/user-list-screen/UserListTitle.tsx
- packages/web/src/components/user-list-modal/components/UserListModal.module.css
- packages/web/src/components/user-list-modal/components/UserListModal.tsx
When user clicks on the tippers/senders from the feed tip tile, show the display name of the receiver in the list modal title.
See below for list modal titles on feed vs on profile page for both mobile and web
n/a
local dapp against stage. local mobile dev pointing to local dapp
n/a
> [PAY-296] Show display name in top supporters modal / drawer from feed

- packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
- packages/web/src/components/tipping/tip-audio/TipAudio.module.css
- packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
- packages/web/src/components/tipping/tip-audio/TipSent.tsx
- packages/web/src/store/tipping/sagas.ts
- Fixes issue where switching between screens would "flicker" as the state would change and the modal contents would swap out while animating
- Fixes "jitter" on the "Hold on a moment" screen due to the header size not staying the same and the state quickly switching between "Sending" and "Converting" (added a 1s delay)
- Fixes spacing issue on the "Hold on a moment" screen
- Normalizes spacing for elements in the transition container so that they all have 24px margins
- Consolidates the styles for the header/subheader in the modal contents
- Changes the header to "Sending" for the sending screen
(pics below)
- Seems like the modal should have a 24px bottom padding as well as the side paddings …
> [PAY-228][PAY-300][PAY-301] Various "Send a Tip" Modal Bugfixes

- packages/mobile/src/components/feed-tip-tile/SenderDetails.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/SupporterAndSupportingNotificationContent.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/TipSentNotification.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/TopSupporterNotification.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/TopSupportingNotification.tsx
- Consolidates top supporter/supporting notifs, since the styling is the same
Fixes:
Old
New
Old
New
New (just minor alignment fix)
None
Tested on simulator
> [PAY-303] Native Mobile QA

- packages/stems/package-lock.json
- packages/stems/package.json
- packages/stems/src/hooks/useClickOutside.ts
In #1462 , I added `setTimeout` to delay the event listener for the click outside from getting attached to _after_ the current event bubbling was done. However, what I didn't realize was that the _removal_ of that event listener was firing _before_ the handler was attached! So the handler never got detatched and the bug would occur again once a modal had been opened once.
This PR changes the cleanup method to _also_ wait until after events are done bubbling, and thus it waits until after the handler is listening before removing it.
Also bumps stems to v0.3.40
*For features that are …
> Stems: Fix for modals not reopening after close

- packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx
- packages/web/src/components/artist/ArtistChip.tsx
- packages/web/src/components/artist/ArtistSupporting.module.css
- packages/web/src/components/notification/Notification/ChallengeRewardNotification.tsx
- packages/web/src/store/tipping/sagas.ts
- Fix jitter in artist hover tile
^ reason why the height is 102px
- Do not force fetching users from source when fetching supporting for a user
- Remove force retrieve from source for tipping users
- Optimistically update sender supporting count and receiver supporter count if appropriate
- Add spacing in reward notif text
- Add delay on artist hover tile in list modal row
local dapp against stage:
- did not notice any jittering
- the unwanted modal refresh not happening anymore
- sending a tip updating the supporting count on the profile page
n/a
> [PAY-339] [PAY-327][PAY-326] [PAY-274] Fix some QA issues

- packages/web/src/components/user-list-modal/components/UserListModal.tsx
Right now it shows supporting as the title (introduced in PR that removed legacy user list modal https://github.com/AudiusProject/audius-client/pull/1405). This PR correctly changes it back to mutuals.
n/a
local dapp against stage.
n/a
> Fix mutuals user list title

- packages/web/src/components/user-list/UserList.tsx
- Closing the modal should not reset state and be in loading state before hiding the modal.
- Switching between user list modals should not lead to wrong content
https://user-images.githubusercontent.com/9600175/174846627-c271c3a3-b323-4bbb-8074-ad2350fa724d.mov
we now reset the list modal state on initial load rather than on exit, but should not really cause issues.
local dapp against stage. also check out the loom video
n/a
> [PAY-342][PAY-344] Fix user list modal issues

- packages/web/src/components/artist/ArtistCard.tsx
- packages/web/src/components/feature-flag-override-modal/FeatureFlagOverrideModal.tsx
- packages/web/src/components/notification/store/sagas.ts
- packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx
- packages/web/src/pages/audio-rewards-page/WalletModal.tsx
- packages/web/src/pages/audio-rewards-page/components/ReceiveBody.tsx
- packages/web/src/pages/audio-rewards-page/components/SendInputBody.tsx
- packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
- packages/web/src/pages/profile-page/sagas.js
- packages/web/src/pages/sign-on/store/sagas.js
- packages/web/src/services/AudiusBackend.js
- packages/web/src/services/remote-config/featureFlagHelpers.ts
- packages/web/src/store/tipping/sagas.ts
- packages/web/src/store/wallet/sagas.ts
Adding feature flag helper for the areas that cant use the hook to maintain the override logic
Should this file live somewhere else?
Should we build in the waitForUserRemoteConfig logic or keep that separate?
Should the components that are using this be updated to use the useFlag hook?
N/A
> Add feature flag helper for flag overrides

- packages/web/src/components/tipping/support/Support.module.css
- packages/web/src/components/tipping/support/SupportingList.module.css
- packages/web/src/components/tipping/support/SupportingList.tsx
- packages/web/src/components/tipping/support/SupportingTile.module.css
- packages/web/src/components/tipping/support/SupportingTile.tsx
- packages/web/src/components/tipping/support/TopSupporters.module.css
- packages/web/src/components/tipping/support/TopSupporters.tsx
Easiest way to review is probably commit by commit, since I did a refactor of the CSS in the second commit where all I did was split the CSS into separate files and remove unused classes.
Figma: https://www.figma.com/file/Q67LDHvSoc5KMLwU5esC24/%F0%9F%92%B8-Tipping?node-id=2628%3A36127
Before:
After:
Locally against stage (Chrome Mac)
- Tested long user names got ellipses
- Tested usernames with "g"s don't get cut off
- Tested buttons still work and have proper animation
N/A
> [PAY-350] Web: Supporting Tile Redesign

- packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingList.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingTile.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ViewAllSupportingTile.tsx
- packages/mobile/src/utils/theme.ts
https://www.figma.com/file/Q67LDHvSoc5KMLwU5esC24/%F0%9F%92%B8-Tipping?node-id=2628%3A36127
See image below
Note:
- Removes hardcoded `maxWidth` of the name contents, opting to use `flexShrink` instead to trigger ellipses
- Renames style references (eg. `backgroundImage` and `gradient` vs `supporterInfo` and `supporterInfoRoot`) mostly for my own benefit but can go back to old "root" convention if wanted
- Also fixes [PAY-355](https://linear.app/audius/issue/PAY-355/supporting-tiles-are-clipping-before-the-edges-of-the-device)
- Had to use negative margins on the rank text to achieve correct padding, as otherwise the container left space for ascenders and descenders in the font which aren't necessary for numbers (we only need cap height)
- Cheesed the size of the trophy icon to match …
> [PAY-350][PAY-355] Mobile: Supporting Tile Redesign

- packages/web/src/components/notification/Notification/components/UserProfilePictureList.module.css
> [PAY-364] Web: Use static white for the +N in UserProfilePictureList

- packages/web/src/components/artist/ArtistChip.tsx
- packages/web/src/components/artist/ArtistPopover.tsx
- packages/web/src/components/notification/Notification/components/ProfilePicture.tsx
- packages/web/src/components/notification/Notification/components/UserNameLink.tsx
- packages/web/src/components/user-list-modal/components/UserListModal.tsx
- packages/web/src/components/user-list/UserList.tsx
- packages/web/src/components/user-list/components/UserList.tsx
Pass through a handler to trigger the modal to close if a nested popover navigates.
It looks like this works in part because the handler that triggers the modal to reappear will trigger after the event is finished bubbling, so the hide happens first:
https://github.com/AudiusProject/audius-client/blob/9ab24da187ff7b54745e62fc61ac95cc526691af/packages/web/src/components/artist/ArtistSupporting.tsx#L95-L99
This was the piece I was wary of, it may have been missing the last time we attempted this route.
- Are there other modals that have popovers inside?
Tested locally against stage. …
> Close user list modals when a nested popover triggers a navigation

- packages/stems/src/components/Modal/Modal.tsx
Clicking the modal content and changing out the content based on the click will unmount the modal content, causing the `useClickOutside` handler to not be able to find the parent ref when doing the `ignore` checks. Instead of relying on parent elements and refs, simply stop the propagation of the event from the parent modal container. Everything else is then going to trigger the click outside (we can probably remove the ignore handler later).
Affects ALL MODALS. No clicks inside will be propagated to the root!
Did a smoke test of existing modals inc supporting to supporting and …
> Don't propagate clicks inside modals to other content

- packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingTile.tsx
Mimics https://github.com/AudiusProject/audius-client/blob/2be3701f9a1925435f913ef01e0da1a8d483c40e/packages/mobile/src/screens/profile-screen/CoverPhoto.tsx#L58
Might be worth wrapping the hook to do this for us?
After: (ignore gradient, fixed separately in #1496 )
iOS sim
> [PAY-373] Mobile: Fix default cover art on supporting tile

- packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingList.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingTile.tsx
Single tiles shouldn't have the `spacing(1)` margins
(see linear for before picture)
After:
N/A
iOS sim
N/A
> [PAY-377] Mobile: Fix single supporting tile margins

- packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx
As far as I understand, entity was never part of the notification itself, which comes from the makeGetAllNotifications selector and we have a separate selector to pull the entity.
This may not be the full solution, but this unblocks local build! @isaacsolo  & I discovered this
Locally vs. staging w/ a listens milestone notification
> Pass entity through to milestone notif

- packages/mobile/src/screens/user-list-screen/SupporterInfo.tsx
- packages/mobile/src/screens/user-list-screen/Tip.tsx
- packages/mobile/src/screens/user-list-screen/UserListItem.tsx
- Updates user list items to have equally sized metric fonts, icons
- Updates the profile image to be 72x72 (with a 1px border instead of 2px)
- Aligns the profile image to the top
iOS sim: iPhone 13 iOS 15.0
(See Linear for before pic)
After:
> [PAY-353] Mobile: Update user list items

- packages/mobile/src/screens/profile-screen/ProfileHeaderV2/TopSupporters.tsx
Makes the whole row for "Top Supporters" the touch target
N/A
iOS sim: iPhone 13 iOS 15.0
N/A
> [PAY-354] Mobile: Make Top Supporters a larger touch target

- packages/mobile/src/components/feed-tip-tile/SendTipButton.tsx
- packages/mobile/src/screens/notifications-screen/Notification/NotificationText.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SocialLink.tsx
- packages/mobile/src/screens/tip-artist-screen/TipInput.tsx
- packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
- packages/web/src/components/tipping/tip-audio/SendTip.tsx
- packages/web/src/components/tipping/tip-audio/TipAudio.module.css
Fix more tipping QA issues:
- fix mobile notification text wrapping
- add margin between go back button and chevron in confirm send tip screen
- vertically center send tip button text on mobile feed tip tile
- fix tipping conversion screen, error state, sending state, and converting state
- give profile bio links active state on mobile
n/a
- local dapp and local mobile app against stage.
- also tested eth<>spl audio conversion, which failed a few times and eventually succeeded when i kept retrying. the UI showed the expected states during sending, conversion, error, and success.
n/a
> [PAY-369][PAY-349][PAY-331][PAY-376][PAY-389][PAY-219] Fix more tipping QA issues

- packages/mobile/src/components/feed-tip-tile/SendTipButton.tsx
Fixes bad merge between:
- #1514 
- #1516 
Tested on iOS Sim
> Mobile: Remove unnecessary padding from send tip button

- packages/web/src/components/tipping/support/TopSupporters.module.css
> [PAY-380] Web: Make trophy icon neutral fill

- packages/web/src/common/store/pages/audio-rewards/selectors.ts
- packages/web/src/common/store/pages/audio-rewards/slice.ts
- packages/web/src/pages/audio-rewards-page/store/sagas.ts
- packages/web/src/pages/audio-rewards-page/store/store.test.ts
Can be reviewed per commit to cut down on some of the type fixing noise.
- Set state.userChallenges to be a mapping of challengeId -> specifier -> user_challenge, and then adapt the selectors and calling code as necessary
None
Tested challenge completion locally. Also no longer see confetti spam
> Fix challenge confetti re-render

- packages/web/src/common/services/remote-config/feature-flags.ts
- packages/web/src/components/tipping/tip-audio/TipAudioButton.tsx
- packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
So that the tip audio button will always be there and prompt the user to take an action.
no dangerous changes really.
https://user-images.githubusercontent.com/9600175/176057246-f791fb18-313a-4fb5-af4a-042a25de0486.mp4
n/a
already exisiting tipping feature flag.
> [PAY-391] Redirect user to signup page when click on tip audio button and not signed in

- packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.module.css
In the referral challenge modal, in matrix mode, the Twitter icon
and text was gray. Switched to white.
None
Checked visually in web client.
n/a
n/a
> [PAY-379] Fix Twitter icon in referral challenge modal in matrix mode

- .circleci/config.yml
- .circleci/src/@continue_config.yml
- .circleci/src/jobs/@stems-jobs.yml
- .circleci/src/workflows/stems.yml
- packages/stems/.gitignore
- packages/stems/scripts/workers-site/.gitignore
- packages/stems/scripts/workers-site/index.js
- packages/stems/scripts/workers-site/package-lock.json
- packages/stems/scripts/workers-site/package.json
- packages/stems/wrangler.toml
Tested by changing the regex to the name of this branch; here is the successful job: https://app.circleci.com/pipelines/github/AudiusProject/audius-client/6205/workflows/d920b8e6-c56f-40f3-a07a-55f8ba8cf2ae/jobs/48965
And the Storybook is up at stems.audius.co
> Deploy Storybook to stems.audius.co upon Stems commit to main

- packages/mobile/ios/AudiusReactNative/Info.plist
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/mobile/src/hooks/useUpdateRequired.ts
- packages/mobile/src/screens/root-screen/RootScreen.tsx
- packages/mobile/src/screens/update-required-screen/UpdateRequiredScreen.tsx
- packages/web/src/common/services/remote-config/defaults.ts
- packages/web/src/common/services/remote-config/types.ts
* Add remote config key
* Add UpdateRequiredScreen
* Add useUpdateRequired hook for mobile
N/A
Need to test on a device to make sure that the link to the app store and play store works
N/A
N/A
> [C-400] Add logic for mobile app minimum version

- packages/web/src/components/nav/desktop/NavAudio.tsx
Fixes a bug where the "Claim Rewards" Pill in the left navbar on web client would turn green whenever the user completed a challenge - even if the challenge wasn't enabled in Optimizely.
The useRewardIds hook is ripe for refactoring but I can open a separate ticket for that.
* Uploaded 3 tracks to complete the upload challenge
* De-whitelisted the upload challenge in Optimizely
* Confirmed that the pill does not turn green.
* Confirmed that it does when the upload challenge is re-enabled.
> [PAY-405] Fixed Claim Rewards Pill To Respect Optimizely Config

- packages/web/src/components/artist/ArtistSupporting.module.css
The non-empty supporting container must've changed height. So the empty container is updated to match the height and prevent the jitter.
n/a
n/a
> Fix jitter

- packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx
- packages/mobile/src/screens/notifications-screen/Reaction/ReactionList.tsx
Fixes issue where quickly swiping on notification reactions results in multiple reactions being selected at the same time. This also caused the entire notification drawer to freeze since reaction gesture handler was blocking all other gestures, yikes.
> [PAY-399] Fix reaction notification selection bug

- .circleci/src/workflows/mobile.yml
Currently, prod mobile is being built on all commits that touch mobile. This isn't really necessary because we only upload prod mobile from release branches. Also, the staging build passing should be enough of an indicator that the prod build will pass too.
Including prod mobile build on `main` as a kind of sanity check that everything is green on main
The branch filters on the `mobile-build-upload-production-ios` and `mobile-build-upload-production-android` aren't necessary because the one on `mobile-build-production-web-app` would short circuit, but I'm adding them for clarity
*For features that are critical or could fail silently please describe the monitoring/alerting being …
> [C678] Limit prod mobile builds to main & release branches

- packages/mobile/src/components/core/IconButton.tsx
- packages/mobile/src/components/core/TextInput.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeaderV2/TopSupporters.tsx
- packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
- packages/mobile/src/utils/theme.ts
- Improves touch targets for profile screen settings and rewards icons.
- Fixes rewards icon matrix color
- Fixes text-input placeholder color
> [C-677] Fix profile-screen icon hit-slop and color

- packages/web/src/common/store/wallet/selectors.ts
- packages/web/src/common/store/wallet/slice.ts
- packages/web/src/store/wallet/sagas.ts
There is a bug (exercised by @dharit-tan) where after sending a tip and optimistically updating the balance, some balance polling rewrites the balance before Solana has returns the correct value. This is easily seen by sending a tip and going to the artist-dashboard, which triggers a polling interval.
This definitely isn't the *best* way to handle this – the proper way would be to look up the tx referenced by the signature returned from identity relay, store the slot, and then when fetching balance, compare the stored slot to the current on chain slot. But too much effort for a small bug like this.
Not really.
Tested on stage
*For features that are critical or could fail silently please …
> [PAY-432] Freeze balance briefly after sending a tip

- packages/web/src/pages/smart-collection/store/sagas.ts
- packages/web/src/services/audius-backend/Explore.ts
Update explore page to use new v1 endpoints
Relies on updated libs version
reference PRs: 
* https://github.com/AudiusProject/audius-protocol/pull/3353
* https://github.com/AudiusProject/audius-protocol/pull/3354
Fixes PLAT-233
Ran locally against linked libs and discovery running against prod with (fixed) endpoint
> Update explore endpoints in libs to use v1

- packages/web/src/components/tracks-table/TracksTable.module.css
Small issue when displaying antd table on smaller screens. Removing the pseudo elements to avoid unwanted shadows in the table
N/A
N/A
N/A
> Remove antd table shadow pseudoelements

- packages/web/src/common/store/tipping/selectors.ts
- packages/web/src/components/tipping/support/SupportingTile.module.css
- packages/web/src/components/tipping/support/SupportingTile.tsx
The `getOptimisticSupporters` selector re-ranks supporters based on the amounts, ensuring the ranking of supporters in the "Top Supporters" modal is correct. However, it doesn't do the same for the _supporting_, which is set to -1 when applied optimistically. Rather than rewrite this to do reranking at the saga level, I added the `getOptimisticSupporters` selector to the `getOptimisticSupporting` selector as a dependency. That way we'll have the updated rankings already computed on the supporter side and can map the rankings over to the supporting side.
Additionally, includes a bugfix where the profile image/name weren't at the bottom of the tile for non-top supporters on web
This might …
> [PAY-425] Fix optimistic trophy icon for supporting

- packages/web/src/components/profile-info/ProfileInfo.module.css
- packages/web/src/components/profile-info/ProfileInfo.tsx
- packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
- packages/web/src/components/tipping/tip-audio/SendTip.tsx
- packages/web/src/components/tipping/tip-audio/TipAudio.module.css
- packages/web/src/components/tipping/tip-audio/TipSent.tsx
- packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
Rebased and updated version of https://github.com/AudiusProject/audius-client/pull/1336
Change TipProfilePic to ProfileInfo component since we are using the same component on the Oauth page and may use it again elsewhere. We might want to move this into Stems if Julian plans to use this in more places.
No effective changes to the component/app.
> Move TipProfilePic to top level ProfileInfo component

- packages/web/src/common/store/tipping/selectors.ts
Tipping supporter ranks used to be in the form of: 1, 2, 2, 3, 4. Now, they'll be 1, 2, 2, 4, 5.
n/a
local v. prod
n/a
none
> Fix rank tie logic

- packages/web/src/components/user-list-modal/components/UserListModal.tsx
Closes user-list-modal when trying to follow a user while logged out
> Close user-list when navigating to sign-in page

- packages/mobile/src/components/track-list/TrackListItem.tsx
Updated the "Deleted By Artist" text to always be displayed in the track list item titles
There was some funkiness getting the sizing to work out properly, but I think I have it dialed in here
N/A
N/A
> [C-639] Update track list item title to display the deleted by artist text better

- packages/web/src/pages/search-page/components/desktop/SearchPageContent.js
scrollableSearch seems to be used for pages that do not have a header rendered so the search results page was rendering two search bars. Removed the prop to allow the header to render the searchbar
N/A
N/A
N/A
> [C-707] Remove extra search bar from the search results page

- packages/web/src/components/card/UserCard.js
- packages/web/src/components/card/UserCard.module.css
- packages/web/src/components/search/SearchBarResult.module.css
Quick fixes for the skeletons for the UserCard and SearchBarResults
N/A
manually tested
N/A
N/A
> [C-710] Update the skeletons for the UserCard and the search bar results

- packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
Use hash id version of user id instead of int version in OAuth response.
Should be released after this discovery PR: https://github.com/AudiusProject/audius-protocol/pull/3406
> Change OAuth user ids to hash ids

- packages/stems/src/components/Modal/ModalHeader.tsx
- packages/stems/src/components/Modal/types.ts
- packages/stems/src/components/PillButton/PillButton.module.css
- packages/stems/src/components/PillButton/PillButton.stories.tsx
- packages/stems/src/components/PillButton/PillButton.tsx
- packages/stems/src/components/PillButton/index.ts
- packages/stems/src/components/PillButton/types.ts
- packages/stems/src/index.tsx
- packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css
- packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx
- packages/web/src/components/tipping/tip-audio/TipAudio.module.css
- packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
Update stems components:
- update ModalHeader in stems to take styles for the dismiss button
- update tip audio modal to use ModalHeader
- add new PillButton
The new PillButton can be used for future components. It takes a type prop that will change the hover and active state styles accordingly (currently only primary and secondary types).
n/a
=============
n/a
none
> [PAY-244][PAY-245] Update tip modal header and extract pill button

- packages/web/src/pages/audio-rewards-page/store/sagas.ts
Fixes claiming rewards on stage
> Default endpoints to empty array instead of null

- packages/common/src/hooks/index.ts
- packages/common/src/hooks/useFeatureFlag.ts
- packages/common/src/hooks/useRemoteVar.ts
- packages/common/src/index.ts
- packages/common/src/services/remote-config/feature-flags.ts
- packages/common/src/services/remote-config/index.ts
- packages/common/src/services/remote-config/remote-config.ts
- packages/mobile/src/hooks/useRemoteConfig.ts
- packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
- packages/mobile/src/services/remote-config/remote-config-instance.ts
- packages/web/src/common/hooks/useFeatureFlag.ts
- packages/web/src/common/hooks/useRemoteVar.ts
- packages/web/src/common/services/remote-config/index.ts
- packages/web/src/common/store/remote-config/selectors.ts
- packages/web/src/components/feature-flag-override-modal/FeatureFlagOverrideModal.tsx
- packages/web/src/components/nav/desktop/NavHeader.js
- packages/web/src/components/nav/desktop/NavHeader.module.css
- packages/web/src/components/nav/mobile/NavBar.module.css
- packages/web/src/components/nav/mobile/NavBar.tsx
- packages/web/src/hooks/useRemoteConfig.ts
- packages/web/src/pages/explore-page/ExplorePage.tsx
- packages/web/src/services/remote-config/featureFlagHelpers.ts
- packages/web/src/services/remote-config/remote-config-instance.ts
This PR does 3 things:
- Changes the feature flag logic to remove the session + user based feature flag distinction. We always prefer a user ID now if it's available, opting for a session if not - sessions are negative integers, so you can group them differently on Optimizely.
- Consolidates the mobile and desktop implementation of feature flags, using an 'injected selectors' pattern. Also made this logic less brittle. 
- Adds new UI to indicate when you're in the 'early access mode' group, with access to features on prod that normal users don't have. 
Touches feature flags, so it's a bit scary. 
Tested on prod with different accounts belonging to different groups. Added a bunch of logs and saw …
> [PAY-416] Early access mode & feature flag refactor

- packages/mobile/ios/Podfile.lock
- packages/mobile/metro.config.js
Accidently bricked mobile build with new metro config. These changes are a temporary revert to enable feature flags to work correctly. In the future we need to get to the bottom of why feature flags break when only referencing mobile node_modules.
also removes react-wasm pod
> Fix native build with new metro-config dependencies

- packages/web/src/services/AudiusBackend.ts
We weren't awaiting the fetch promises and there was no `.catch` so errors were not being caught, causing the app to crash. Added `await` for each fetch call, ideally we would refactor so there are no chained `then`s also but that isn't necessary right away
Because we are catching more errors now this should be fairly safe, the impact being that something that did cause the app to crash before no longer does so
*Are all new features properly feature flagged? Describe added …
> [C-782] Catch fetch errors in AudiusBackend

- packages/web/src/utils/commonPasswordCheck.ts
Add a minimum threshold to the common password check to make it less aggressive
N/A
Will watch to see if the check is still too aggressive
N/A
> [C-781] Add minimum threshold to common password check

- packages/web/src/store/account/disconnected_wallet_fix.json
- packages/web/src/store/account/sagas.js
Add an online helper for users to connect wallets that got disconnected in Flare-101
This PR should be reverted after a sufficient amount of time has passed or all users have re-connected their wallets. (Since we have the user ids, the query is easy to run to check).
Tested on production account `rayjacobson`
The "migration" ran once for the user, fixed the wallets, and is not running again.
> Fix associated wallets

- packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
Ensures header text in TrackRemixScreen is color is neutral
> [C-797] Fix track-remix-screen text color

- packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
- packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
- packages/web/src/components/track/desktop/TrackListItem.tsx
- packages/web/src/components/track/desktop/TrackTile.tsx
- packages/web/src/components/track/helpers.ts
- packages/web/src/utils/domUtils.ts
Prevent multiple overflow menus at a time.
The issue was that there was an event.stopPropagation as the click event from the the kebab menu in the track/playlist was bubbling up. This was there so that the underlying track does not play/pause on kebab menu click. However, because the click event stopped bubbling up, the logic for the click outside of already open menus would not trigger, leaving those menus open.
This PR does not stop the click event from bubbling up to the document, and it prevents the play/pause track if the click target is from the kebab menu.
Other menu overflow behavior should still work as expected.
local vs stage
https://www.loom.com/share/034b9e3fb52e4ac09fdd2b975cd2ad08
n/a
none
> [C-806] Prevent multiple overflow menus at a time

- packages/mobile/src/components/lineup-tile/TrackTile.tsx
- packages/mobile/src/components/track-list/TrackList.tsx
- packages/mobile/src/components/track-list/TrackListItem.tsx
- packages/mobile/src/hooks/useNavigation.ts
Fixes case where artist's track's overflow menu shows option to go to artist page, which doesn't make sense since we are already on the artist page
Definitely a bit hacky.
> [C-808] Don't show unnecessarily show profile option on overflow menu

- packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawer.tsx
- packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
- packages/web/src/common/services/audius-backend/AudiusBackend.ts
- packages/web/src/common/store/pages/audio-rewards/selectors.ts
- packages/web/src/common/store/pages/audio-rewards/slice.ts
- packages/web/src/common/utils/aaoErrorCodes.ts
- packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
- packages/web/src/pages/audio-rewards-page/store/sagas.ts
When a user tries to claim a challenge reward and fails due to an AAO rejection, display an emoji that corresponds to error codes from the AAO.
Things get a bit hairy in sagas.ts - we switch on failure reasons, then throw an error in the BLOCKED case and in the case of an AAO_ATTESTATION_REJECTION we end up in the else statement after retries. I think these are the only paths an AAO rejection will follow but would like confirmation.
Tested manually on both web and mobile. Manually set selector to return all expected values and confirmed behavior.
> [PAY-466] Display AAO emoji errors for failed reward claims

- packages/web/src/components/image-selection/ImageSelectionButton.js
Prevent showing file explorer on pressing enter and file open button not on focus.
We still have the ability to not only show the explorer on button click, but also on pressing enter/space as long as the button is on focus.
n/a
n/a
none
> [C-773] Prevent showing file explorer on pressing enter

- packages/web/src/components/actions-tab/ActionsTab.js
- packages/web/src/components/card/desktop/Card.module.css
- packages/web/src/components/nav/desktop/NavColumn.tsx
- packages/web/src/components/tooltip/Tooltip.tsx
- packages/web/src/components/tooltip/types.ts
- packages/web/src/components/track/desktop/TrackTile.tsx
Fix tooltip bugs. There were kind of a few things that were causing jankiness, primarily the timeout though, which is a blunt weapon to handle this kinda stuff. This is why I kinda dislike antd... Have to learn about the internals a little bit to get the behavior.
Focused on 3 places
- GiantTrackTile (track page): to test the bug in the linear issue -- tooltip appearing after clicking
- Receive $AUDIO modal -- to test that the tooltip goes away when you click, even if you're still hovering over the element
- Track tile on feed: to test that the tooltip goes away when you click, but …
> [C-608] Fix tooltip bugs

- packages/web/src/pages/landing-page/components/Hero.module.css
Fixes width of foreground image by scaling it based on vw not vh.
Tested on various screen sizes
> [C-786] Fix width of foreground hero image

- packages/web/src/pages/upload-page/store/sagas.js
`yield*` was being used in a file that was not using `typed-redux-saga`, this caused apiClient to be undefined.
Will do a pass to see if there are any other instances of this
> [C-829] Fix upload error

- packages/web/package.json
- packages/web/src/electron.js
* Use `app.getPath('appData')` instead of `app.getAppPath` to store/retrieve the update builds because `app.getAppPath` can't apparently be modified when the app is built using electron-build (it's packaged into a single file)
* On initial build registration, conditionally register the build located in the app data directory (if an update has been previously applied)
* Update logic of replacing builds on update because they are now stored in a different location
> For some reason the `packages/web` path was not being accounted for, did something change the structure of the s3 bucket?
* Add `appDataPath` helper
I would like to test this on windows. Does anyone have a windows machine to test on?
Also need prevent auto updater from downloading full update if only a patch version is required …
> [C-815] Fix electron update

- packages/web/src/common/store/challenges/selectors/optimistic-challenges.ts
There is a bug where if you sign up on web and then load your account into mobile, we don't mark the mobile install challenge as claimable because your is_mobile user_events haven't propagated to DN yet. So optimistically mark this challenge as claimable if mobile.
I was a bit on the fence about where to put this check - at first I was going to put it in userChallengeOverrides in the slice, which required adding a new action, and then felt that dispatching an action was really indirect compared to just putting this check in the obvious place, even though it makes this code more tightly coupled to a specific challenge now. 
None
I haven't tested this yet :) 
*For features that …
> [PAY-497] Fix native mobile install challenge

- packages/web/src/services/audius-backend/eagerLoadUtils.ts
Eager loader is returning early if no cached value. Instead we should pull from the env vars set in the .env file.
Observed behavior is when you load localhost:3001/df/playlist/probers_playlist_do_not_delete-511 in incognito for the first time, it would crash b/c we can't initialize API client w/o some discovery node.
Locally w/ probers
> Fix eager discovery loader

- packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx
- packages/web/src/common/store/tipping/selectors.ts
- packages/web/src/hooks/useGetFirstOrTopSupporter.ts
This bug is new because it's now possible to tip a user without going to their profile and without clicking from the feed tip tile. The bug is because the receiver's supporters weren't fetched and so the UI thinks there is no supporter for the user.
So the fix is to fetch that user i.e. the receiver's supporters.
=====
I think this change will make sure that the account and receiver's necessary supporting / supporters exist, so if there is another UI flow that goes into tipping in the future, we'd still be okay.
https://user-images.githubusercontent.com/9600175/185279845-c84e3b50-af10-4df7-9660-8913f2be4ce0.mov
mobile against local dapp pointing to prod
n/a
none
> [PAY-531] Fix become first supporter bug

- packages/mobile/src/components/sign-out-confirmation-drawer/SignOutConfirmationDrawer.tsx
- packages/mobile/src/screens/signon/SignOn.tsx
- packages/mobile/src/store/sagas.ts
- packages/mobile/src/store/store.ts
- packages/web/src/common/store/account/reducer.ts
- packages/web/src/common/store/pages/signon/sagas.js
- packages/web/src/common/store/sign-out/sagas.ts
Ended up struggling to test sign up stuff without sign out, so I went ahead in that direction. Hopefully didn't steal too much.
Curious for thoughts here. I believe this is "shippable" with the sagas on mobile enabled at this point. That might save us some pain of having everything be off & then on while we're working.
This is all a good learning exercise for me. I'm starting to get the feeling that we're doing an "in then back out" approach to things.
1. Mirror dispatch & fetch logic in core stuff like account/sign in (double dispatch/select)
2. Move all the "inner pages" onto the local redux store instead of common
3. Go back to the core stuff and remove the web dispatch/select stuff
Maybe this was already obvious to folks...
https://user-images.githubusercontent.com/2731362/185336740-0e …
> Get sign in/out working end to end

- packages/web/src/pages/profile-page/sagas.js
> [C-859] Omit `is_verified` from metadata that gets stored in user cache from fetchCID

- .circleci/src/workflows/web.yml
- packages/web/package-lock.json
- packages/web/package.json
https://app.circleci.com/pipelines/github/AudiusProject/audius-client/7131/workflows/fd895ab7-4f22-4bdc-b63e-a134f922a282/jobs/58834
`web-dist-mac-staging` has been failing since https://github.com/AudiusProject/audius-client/commit/bcd68c7eec9eb61b482296113159742cc890de33
This was due to the ci job using the `macOS` image with npm v8 and un-reconcilable peer deps added in the commit. ~Adding `--legacy-peer-deps` for now but we should probably address the peer dependency issue~
Changing the peer deps to regular deps because audius-client isn't being consumed anyway
*For features that …
> [C-860] Fix failing mac ci build due to peer deps

- packages/web/src/common/hooks/useModalState.ts
`useModalState` hook implementation was gutted in #1675 , this PR adds back the functionality
@nicoback2 does this break anything? Seems like it was intentionally removed...
> Add back modal hook functionality

- packages/common/src/store/ui/buy-audio/selectors.ts
- packages/web/src/components/buy-audio-modal/BuyAudioModal.module.css
- packages/web/src/components/buy-audio-modal/BuyAudioModal.tsx
- packages/web/src/components/coinbase-pay-button/index.ts
- packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
- packages/web/src/pages/modals/Modals.tsx
Creates a new (currently empty) modal for buying $AUDIO and wires it up to the new $AUDIO & Rewards page.
Tested against stage with the BUY_AUDIO_ENABLED feature flag turned on.
Behind BUY_AUDIO_ENABLED feature flag
> Wire up initial BuyAudioModal

- packages/common/package.json
- packages/common/src/store/pages/track/actions.ts
- packages/mobile/src/hooks/useImageSize.ts
- packages/mobile/src/screens/track-screen/TrackScreen.tsx
- packages/mobile/src/services/audius-backend-instance.ts
- packages/mobile/src/store/sagas.ts
- packages/web/src/common/store/pages/track/sagas.js
- packages/web/src/pages/track-page/TrackPageProvider.tsx
- packages/web/src/store/sagas.ts
- Adds track-page sagas to native
- Refactors TrackScreen to fetch tracks within native
- For now, useImageSize is not only using `useDispatch` breaking other places it's used, like profile. Thinking this is okay in the interim.
- Added `disableImagePreload` to mobile audius-backend, which simplifies fetching the track image. This seems like a decent approach, until we maybe want to add a native version of preload?
- Loading track page is slower perf right now since we can't rely on a cached version from the lineup screen. should be fixed as we continue to migrate, but just an fyi
- Separated trackPageLineupSagas from trackPageSagas since lineup requires work with player first
> [C-858] Add track page sagas to native, Refactor TrackScreen

- packages/mobile/index.js
- packages/mobile/package-lock.json
- packages/mobile/package.json
- packages/web/package-lock.json
Fixes build issue by polyfilling TextEncoder, which is needed for newly added SolanaUtils.
This issue was not caught in development because the ReactNativeDebugger app injects it's own implementation of TextEncoder, which allows the app to run without a hitch. The issue only appears when you turn off Chrome Debugging (or obviously when run on a device from testflight)
Ran on device with Chrome Debugging disabled
> [C-890] Polyfill TextEncoder, fixes builds
