AudiusProject/audius-client

package-lock.json, package.json
=> Bump 0.21.17

package-lock.json, package.json
https://trello.com/c/WtLiEhjd/1513-missing-scale-transitions-on-buttons-throughout-the-app-they-now-snap-between-states-julian
Fixes missing scale animation on buttons
n/a
Ran client locally & verified button changes
=> Upgrade stems to 0.2.4

src/containers/track-page/TrackPageProvider.tsx, src/utils/route/trackRouteParser.ts
https://trello.com/c/Hbo5gNn5/1563-fix-back-bug-from-track-page
Fixes going "back" from a track page (404s right now)
Touches track URLs
- Trending -> track page -> back
- Track page -> other track page
- Track page -> other track page -> back
=> Fix going back from track page

package-lock.json, package.json, src/services/AudiusBackend.js
=> Use all gateways

src/containers/saved-page/store/sagas.js, src/services/audius-api-client/AudiusAPIClient.ts
https://trello.com/c/A7BOsv5J/1476-port-the-new-api-into-the-dapp
Moves the tracks from from the favorites page to be sourced from the new api
na
Ran locally against a local DP w/ DB pointing to a prod snapshot
=> Update save page tracks to use new api client

src/containers/sign-on/store/sagas.js, src/services/audius-api-client/AudiusAPIClient.ts
https://trello.com/c/A7BOsv5J/1476-port-the-new-api-into-the-dapp
Moves call for top users per genre to use the DP cached v1 routes
na
Ran locally against a local DP w/ DB pointing to a prod snapshot
=> Add api client top user genres call

src/containers/upload-page/components/ShareBanner.tsx, src/services/audius-api-client/AudiusAPIClient.ts, src/services/audius-api-client/types.ts, src/store/cache/tracks/utils/retrieveTracks.ts, src/store/confirmer/sagas.js
https://trello.com/c/A7BOsv5J
Consume new tracks API, including in confirmer.
None
Tested throughout app, including performing social actions + uploading tracks.
=> Consume Tracks API

src/store/cache/collections/sagas.js, src/store/confirmer/sagas.js
- Fix track upload polling bug
- Fix playlist creation bug
None
Tested locally
=> Fix client bugs from API work

src/services/audius-api-client/AudiusAPIClient.ts, src/services/audius-api-client/ResponseAdapter.ts, src/services/audius-api-client/types.ts
na
Create separate types for search user/track/playlist and update makeuser/maketrack/makeplaylist to accept those
na
Ran locally against staging.
=> Fix search types

src/containers/track-page/store/lineups/tracks/sagas.js
n/a
Fixes a bug where playing a track fails sometimes after initial upload
n/a
manually ran against staging, verified the content of `track` in the case of the race condition error & verified the fix makes that go away
=> Fix track page race condition

package-lock.json, package.json, src/containers/artist-dashboard-page/ArtistDashboardPage.module.css, src/containers/artist-dashboard-page/ArtistDashboardPage.tsx, src/containers/artist-dashboard-page/Tiles.module.css, src/containers/artist-dashboard-page/Tiles.tsx, src/containers/artist-dashboard-page/WalletModal.module.css, src/containers/artist-dashboard-page/WalletModal.tsx, src/containers/artist-dashboard-page/components/ClaimSuccessBody.tsx, src/containers/artist-dashboard-page/components/ClaimingModalBody.module.css, src/containers/artist-dashboard-page/components/ClaimingModalBody.tsx, src/containers/artist-dashboard-page/components/ReceiveBody.tsx, src/containers/artist-dashboard-page/components/SendInputBody.tsx, src/containers/artist-dashboard-page/components/SendInputConfirmation.tsx, src/containers/artist-dashboard-page/components/SendInputSuccess.tsx, src/containers/nav/desktop/NavHeader.js, src/services/wallet-client/WalletClient.ts, src/store/token-dashboard/sagas.ts, src/store/token-dashboard/slice.ts, tsconfig.json
Skeleton UI for all dashboard flows, fully wired up.
Nope
Went through the dashboard flows.
=> Skeleton Dashboard UI + Flows

src/containers/artist-dashboard-page/WalletModal.tsx, src/containers/artist-dashboard-page/components/ClaimSuccessBody.tsx, src/containers/artist-dashboard-page/components/ClaimingModalBody.tsx, src/containers/artist-dashboard-page/components/DisplayAudio.module.css, src/containers/artist-dashboard-page/components/DisplayAudio.tsx, src/containers/artist-dashboard-page/components/SendInputConfirmation.tsx, src/containers/artist-dashboard-page/components/SendInputSuccess.tsx
na
Display audio component
na
Looked at it locally!
=> Add display audio component

src/containers/artist-dashboard-page/WalletModal.tsx, src/containers/artist-dashboard-page/components/ErrorBody.module.css, src/containers/artist-dashboard-page/components/ErrorBody.tsx
na
error modal
na
manually change state to error for send and claim
=> Add dashboard error modals

src/containers/artist-dashboard-page/Tiles.tsx, src/containers/artist-dashboard-page/WalletModal.tsx, src/containers/artist-dashboard-page/components/DashboardTokenValueSlider.tsx, src/containers/artist-dashboard-page/components/DisplayAudio.tsx, src/containers/artist-dashboard-page/components/SendInputBody.tsx, src/services/wallet-client/WalletClient.ts, src/store/wallet/slice.ts
- Fix handling of fractional $Audio across the board
- Set min transfer amount 
- Fix misc UI, inc commas on the value slider
=> Better Support Fractional Audio

src/assets/styles/colors.css
n/a
We lost the color at some point! Must have been a looooong time ago :-) 
=> Fix scrubber hover color

package-lock.json, package.json, src/store/cache/users/sagas.js
Since we don't call processAndCache in this flow, we don't reformat the user into having the proper image fields
=> Fix user missing images

src/containers/artist-dashboard-page/ArtistDashboardPage.tsx, src/containers/artist-dashboard-page/store/actions.js, src/containers/artist-dashboard-page/store/sagas.js, src/services/remote-config/RemoteConfig.ts, src/services/remote-config/defaults.ts, src/store/wallet/sagas.ts, src/utils/sagaHelpers.js
n/a
Polls for wallet balance on dashboard page (5s default)
n/a
Manually ran & visited dashboard page, made sure that requests stopped getting sent after leaving dashboard page
=> Wallet polling

package-lock.json, package.json, src/containers/notice/Notice.module.css, src/containers/notice/Notice.tsx, src/services/remote-config/RemoteConfig.ts, src/services/remote-config/defaults.ts
Changes degraded service notice to be customizable (remotely)
Adds safe area insets for mobile.
=> Allow customizable notice text

src/services/AudiusBackend.js
n/a
Wraps necessary calls to make app not crash w/o identity
=> Dont crash with identity down

package-lock.json, package.json
=> bump libs to 1.0.9

package.json, src/components/source-files-modal/SourceFilesModal.tsx
- Fix Z-Index of Source Files Modal
Nah
Tested Source Files Modal
=> Fix Source Files Modal Z-Index

src/containers/notification-users-page/store/sagas.ts
https://trello.com/c/hN96mqqf
Fixes bug where you click on a list of followers on a mobile notification and we crash.
None
Mobile web
=> Fix broken notification users pagination

src/containers/play-bar/desktop/PlayBar.js
https://github.com/AudiusProject/audius-protocol/issues/1019
Fixes volume persisting correctly between sessions
This deserves a proper rewrite with hooks (& ts). useEffect would have handled this way more elegantly.
Nah!
Verified against staging
=> Fix initial volume

package-lock.json, package.json, src/services/audius-api-client/AudiusAPIClient.ts, src/store/confirmer/sagas.js
Makes it so track confirmer can tolerate initial 404s
Touches upload flow
No reselection!
=> Allow track null in polling confirmation

src/containers/artist-dashboard-page/store/sagas.js
https://trello.com/c/C9KWWW7b/1659-fix-dashboard-for-tracks-100
Currently in the artist dashboard, for users with > 100 tracks, we stop aggregating stats. The new API client supports up to 500, so this switch improves that aspect a bit. Also parallelizes fetching playlists & tracks.
Nope
Manually put in a user id / handle that we know has not been displaying metrics properly. Seems to be correct now.
Manually compared metrics on my production account w/ & w/o this change and it is consistent.
=> Fix dashboard listen counts up to 500

src/audio/AudioStream.ts
https://trello.com/c/cdjlfZqf/1661-figure-out-player-error-log-spam
Rate limits "player/error" which stem from HLS throwing errors. Though the errors we see 
```
"error":"HLS","trackId":50363,"info":{"type":"mediaError","details":"fragParsingError","fatal":true,"reason":"no demux matching with content found"
```
are legitimate, it impacts like ~10 users per day who make up thousands of events b/c HLS.js is noisy. I believe this error comes from content unavailability, so I want to just merge this rate limit and close out for now. We can continue to monitor.
Nah
Made sure that we can …
=> Add error rate limiting

src/containers/upload-page/store/sagas.js, src/containers/upload-page/store/utils/sagaHelpers.ts, src/services/analytics.ts, src/store/application/ui/stemsUpload/sagas.ts
- Adds success + error events for track upload
- Fixes collection uploads not following collection upload code path
Upload is scary, but this is pretty tame for upload.
Tested every upload type in both failure + success cases, logged out the events we'll be sending up.
=> Add Track Upload Metrics

package-lock.json, package.json
Upgrades lives to 1.0.13 which containers extra logging. (Already on prod via hotfix)
Nope
On prod 😈
=> Libs 1.0.13

src/containers/landing-page/components/PlatformFeatures.module.css, src/containers/landing-page/components/PlatformFeatures.tsx
https://trello.com/c/oOvYL5ro/1675-replace-no-takedowns-feature-card-on-audiusco
Updates landing page copy
N/a
Locally tested
=> Update landing page copy

.circleci/config.yml, scripts/workers-site/.gitignore, scripts/workers-site/index.js, scripts/workers-site/package-lock.json, scripts/workers-site/package.json, wrangler.toml
https://trello.com/c/JFoThV8g/1676-integrate-cloudflare-into-ci
Integrates CF deployment into CI via wrangler
Nah
Manually ran staging workflow
=> Add CI for cloudflare

src/services/AudiusBackend.js
Always also checks UM node for images in case there was a broken sync
n/a
Verified against profile on prod
=> Add user metadata to gateways for images

public/index.html, src/services/AudiusBackend.js
Fixes optimizely local setup blocking libs init
initial load
- verified locally against local services, libs loads
- verified locally against staging, blocking network requests to optimizely, libs loads and optimizely uses default values
-- showing 
```
ERROR 2020-11-13T01:31:29.039Z CONFIG_VALIDATOR: This version of the JavaScript SDK does not support the given datafile version: undefined
```
=> Fix optimizely local setup

src/containers/sign-on/components/desktop/FollowPage.tsx
Minor change to min follower count, just to make local dev smoother - I always use dapp and end up refreshing randomly so I figured this would be nicer.
None that i can think of
Created users locally and verified that the gate does not block on 3 follows - will verify on stage later as well (it should still be 3 followers required)
=> Local Dev - Remove 3 follower requirement

src/services/AudiusBackend.js
Found a bunch of unused methods in AudiusBackend, removed them
None
Tested client against staging
=> Cleanup unused AudiusBackend methods

package-lock.json, package.json, src/containers/nav/mobile/NavBar.module.css, src/containers/service-selection/store/store.test.js
Updates the creator-node sp type to content-node
Nope
Deployed to prod as a part of the migration yesterday to content-node
=> Update content node sp type

src/services/audius-api-client/AudiusAPIClient.ts, src/services/audius-api-client/helper.ts
https://trello.com/c/LgWOugzO/1691-look-into-algo-for-better-search-matches
Prefer some 1/3 authentic results in addition to content you follow/have favorited in search autocomplete. Might want to switch this to 2/3 at some point as well, but this is certainly better.
n/a 
Locally pointed against staging
=> Update autocomplete search

src/root.tsx, src/services/Logging.ts, src/services/native-mobile-interface/logging.ts, src/services/native-mobile-interface/types.ts
Fixes the pain of using Safari for debugging mobile app.
None. Curious if you think this is the right place to init the logging service, though?
Tested in mobile, we see logs!
=> Forward logs to mobile

src/assets/img/iconGradientUpload.svg, src/assets/styles/colors.css, src/components/drawer/Drawer.module.css, src/components/drawer/Drawer.tsx, src/utils/theme/dark.ts, src/utils/theme/default.ts
https://trello.com/c/Clro3f9J/1692-upload-from-desktop-button-on-mobile
Misc. style cleanup after Julian's feedback
Nope
Against staging
=> Fix drawer styles

src/containers/settings-page/components/mobile/NotificationsSettingsPage.tsx, src/services/native-mobile-interface/helpers.ts, src/services/native-mobile-interface/notifications.ts, src/services/native-mobile-interface/types.ts
- Show the enable push notifs prompt when we visit the notification settings page.
- Adds logging around messages
No
Tested locally
=> Handle notif reminder prompt

src/components/track/mobile/TrackTile.module.css
https://trello.com/c/PWYplMEM
Track playing icon was misaligned
None
Tested locally
=> [AUD-12] Misaligned track tile icon

src/containers/explore-page/components/desktop/Section.module.css
https://trello.com/c/ORBtUVSX
Because Safari, that's why
No
Tested explore in multiple browsers
=> [AUD-15] Fix Explore Page section expand overlap on Safari

src/containers/artist-dashboard-page/store/sagas.js
https://trello.com/c/ZHQzWV7d
Sharing unlisted was broken on dashboard because we weren't calling retrieve
None
Tested dashboard
=> [AUD-11] Fix sharing unlisted tracks

src/containers/track-page/TrackPageProvider.tsx, src/containers/track-page/store/sagas.js
na
Fix for showing the track badge at 10 instead of 5
na
Ran it locally against staging
=> Increase badge limit to 10

README.md, package-lock.json, package.json, src/containers/App.js, src/electron.js
https://trello.com/c/yfI3UrsO/1726-bricked-update-flow-on-windows-not-sure-how-many-users-it-impacts
https://trello.com/c/kJ1ydmFP/1669-404-page-after-upgrading-windows-app
Windows updates unbricked by cert work (on CI already), but this adds better logging around updates, plus the ability to do cmd + option + i to open the console on prod builds without adding a menu item.
Nope
Manually created 0.24.0 releases and forced updates on a windows box.
=> [AUD-8] Windows build logging improvements & update flow fix

src/components/track/mobile/TrackTile.module.css, src/components/track/mobile/TrackTile.tsx
Fix track tile regression
None
Tested locally
=> [AUD-18] Fix skeleton tile widths

src/services/analytics.ts, src/store/wallet/sagas.ts
Adds analytics for claiming & sending $AUDIO
nope
Tested request/success/failure against staging for claim & send. Verified wallet addresses were correct in analytics payloads.
=> Add analytics for wallet actions

package-lock.json, package.json
https://www.notion.so/audiusproject/11-20-discovery-node-rollout-todo-2e4a704d212544bea60fddc516776001
Merges libs 1.1.0 which changes sp type to "discovery node"
N/a
Locally
=> Libs 1.1.0

package-lock.json, package.json
This might fix it?
Noticed some references to older tersers in package-lock, seems like maybe this issue was fixed https://github.com/facebook/create-react-app/issues/6334#issuecomment-460244100
npm run build:prod
=> [AUD-25] Update terser

src/store/cache/tracks/sagas.js
On delete track, this checks if that track is selected as the "Artist Pick" and makes a request to remove it as the artist pick if so.
Closes AUD-30
nope
I ran the client locally against staging and confirmed that deleting a pinned track deleted it from identity as well and that deleting a non-pinned track did not.
=> Delete artist pick on delete track

src/containers/app-cta-modal/AppCTAModal.tsx
Fixes app CTA modal on smaller resolutions
=> [AUD-29] Allow scroll on app CTA modal

scripts/configureLocalEnv.js
**Depends on https://github.com/AudiusProject/audius-protocol/pull/1148 to enable local standalone UM**
Updates client local dev to point to standalone UM node
=> Modify local setup to point to standalone UM node

src/components/general/MobilePageContainer.tsx
=> [AUD-80] Fix lack of bottom padding on mobile playlist pages

src/components/general/InstagramAuth.tsx, src/containers/settings-page/components/TwitterAccountVerified.js, src/containers/settings-page/components/desktop/VerificationModal.tsx, src/containers/settings-page/components/mobile/VerificationPage.tsx, src/containers/sign-on/components/desktop/TwitterOverlay.js, src/containers/sign-on/components/mobile/TwitterOverlay.js, src/containers/sign-on/store/sagas.js
=> [AUD-120] Fix verified case sensitivity

src/components/drawer/Drawer.module.css, src/components/drawer/Drawer.tsx
=> Block clicks behind drawer when open

src/containers/explore-page/components/mobile/ExplorePage.tsx, src/containers/explore-page/store/actions.ts, src/containers/explore-page/store/reducer.ts, src/containers/explore-page/store/selectors.ts, src/containers/explore-page/store/types.ts, src/containers/nav/mobile/ConnectedBottomBar.tsx
Remember tab state on explore page, clear it out when using navbar.
None
Browser
=> [AUD-81] Remember tab position on Explore Page

src/components/track/desktop/TrackListItem.tsx, src/components/track/mobile/TrackTile.tsx
Closes AUD-59
I don't think 0:00 is hard coded anywhere, but if `0` or `undefined`  are passed to the function `formatSeconds` then it returns `0:00`. 
I was unable to repro, but believe this change should stop it.
Let me know if this is not the issue. 
no
I ran to dapp to make sure nothing weird happened, but could not test.
=> Stop display of time if 0 or undefined

src/containers/collection-page/store/sagas.js, src/store/configureStore.js, src/utils/clientUtil.ts
- Fix undefined collection crash bug
- Better sentry logging
Nah
Locally
=> Fix invalid playlist ID crash

src/components/track/mobile/TrackList.tsx, src/components/track/mobile/TrackListItem.module.css, src/components/track/mobile/TrackListItem.tsx, src/containers/edit-playlist/mobile/EditPlaylistPage.tsx
Added animation for rotating remove track from playlist icon
https://user-images.githubusercontent.com/7064122/104776360-f6cf3000-5747-11eb-989c-ca5a02befd9c.mov
nope
ran it locally
=> Add rotate animation on remove track playlist

package-lock.json, package.json
Libs @ https://github.com/AudiusProject/audius-protocol/pull/1177
=> Upgrade libs to 1.1.10

src/containers/visualizer/VisualizerProvider.tsx, src/containers/visualizer/utils.ts, src/utils/visualizer/visualizer-1.js
If for some reason the browser doesn't have WebGL installed, we immediately crash upon load. Fixes a linked sentry issue
Nah
Tested on regular browser, browser with webgl disabled, and safari
=> Fix WebGL disabled crash

src/containers/embed-modal/EmbedModal.tsx, src/containers/embed-modal/components/EmbedFrame.module.css, src/containers/embed-modal/components/EmbedFrame.tsx, src/containers/embed-modal/types.ts, src/services/analytics.ts
Add tiny embed variant to embed modal
Demo: ray.audius.co
May need some slight adjustment after product sync
ray.audius.co, various tracks inc. deleted
=> [AUD-181] Add tiny embed variant

src/containers/artist-dashboard-page/Tiers.tsx, src/containers/user-badges/utils.ts, src/utils/signOut.js
Adds confetti if you move up tiers
noe
ropsten audio send
=> Add tier change confetti

src/containers/artist-dashboard-page/Tiers.module.css, src/containers/artist-dashboard-page/Tiers.tsx, src/containers/artist-dashboard-page/Tiles.tsx, src/containers/user-badges/ProfilePageBadge.tsx
=> Badges QA Fixes

package-lock.json, package.json, src/services/AudiusBackend.js, src/services/analytics.ts, src/services/remote-config/RemoteConfig.ts, src/services/remote-config/defaults.ts, src/services/serviceMonitoring.ts
Add analytics mechanism for recording service monitored metrics to segment.
This is the last PR to enable "service monitoring" (aka, sample data from content node and discovery node requests & health checks that gets piped to segment/amplitude).
services/serviceMonitoring.ts is the entry point to look at
Nope!
Locally ran against staging with updated services to verify that metrics are being recorded to segment/amplitude:
https://analytics.amplitude.com/audius/chart/45hom7i?source=redirect%3A+chart+saved
Response from content node:
```
version: "0.3.29",
service: "content-node",
healthy: …
```
=> [AUD-145] Add analytics wrapper for monitoring

src/containers/artist-dashboard-page/Tiers.module.css, src/containers/artist-dashboard-page/Tiers.tsx, src/containers/artist-dashboard-page/Tiles.module.css
Address a few new minor QA things 
Nah
Tested locally
=> Additional badges QA fixes

src/assets/styles/colors.css, src/containers/user-badges/ProfilePageBadge.module.css, src/utils/theme/dark.ts, src/utils/theme/default.ts
Fix dark mode profile page badge
No
Locally and ngrok to device
=> Fix badge for dark mode

src/assets/styles/colors.css, src/containers/profile-page/components/mobile/ProfileHeader.module.css, src/containers/user-badges/ProfilePageBadge.module.css, src/utils/theme/dark.ts, src/utils/theme/default.ts
Visual polish for profile page requested by design
no
locally
=> Adjust profile page header background color

src/components/card/UserCard.module.css, src/components/track/TrackInfo.module.css, src/components/track/mobile/PlaylistTile.module.css, src/containers/play-bar/desktop/components/PlayingTrackInfo.module.css
Some verified icons had old coloring applied. Also UserCards in the feed if you hadn't followed users had layout issues.
None
Locally
=> Fix verified coloring + layout for UserCards

src/containers/sign-on/store/sagas.js
n/a
Local npm run start:stage
Local npm run build:stage
=> [AUD-318] Skip check if local build

src/containers/sign-on/SignOnProvider.tsx, src/containers/sign-on/components/desktop/SignOnPage.tsx, src/services/analytics.ts
Add more drilldown dimensions to sign up metrics
Locally, ensured metrics got sent out
=> [AUD-292] Add more drilldown dimensions to sign up metrics

package-lock.json, package.json, src/containers/search-page/store/sagas.js
Currently we were requesting all tracks for each playlist on search
1. slows it down
2. if there are too many tracks will fail to get responses back from DP
Locally @ prod
=> Fix search

src/containers/animated-switch/AnimatedSwitch.tsx, src/containers/nav/mobile/ConnectedBottomBar.tsx, src/containers/nav/mobile/NavBar.module.css, src/containers/nav/mobile/NavBar.tsx, src/containers/notification/store/mobileSagas.ts, src/containers/notification/store/sagas.ts, src/containers/notification/store/types.ts, src/services/native-mobile-interface/lifecycle.ts, src/services/native-mobile-interface/notifications.ts, src/services/native-mobile-interface/types.ts, src/store/account/sagas.js, src/store/routing/mobileSagas.ts, src/store/routing/sagas.ts
Add support for full react native notifications drawer
Will need some more QA passes, especially on the native side, but wanted to get a PR out
Mobile bounce build
=> [AUD-267] Support native notifications panel

package.json
=> Consume latest stems

src/services/serviceMonitoring.ts
Adds a type field to the monitor payload for more drilldowns in metrics tools
n/a
=> Add type to service monitor

src/containers/artist-dashboard-page/WalletModal.module.css, src/containers/artist-dashboard-page/components/SendInputBody.module.css, src/containers/artist-dashboard-page/components/SendInputBody.tsx
=> [AUD-326] Warn people they will lose badges by sending

src/services/analytics.ts, src/store/wallet/sagas.ts
Add specific copy for rate limit error message, otherwise report generic message out to client.
Forgot to open this PR after hotfixing this out :-/
=> Add rate limit specific error

.circleci/config.yml, src/containers/sign-on/store/sagas.js, src/containers/sign-on/store/verifiedChecker.test.js, src/containers/sign-on/store/verifiedChecker.ts
=> Hotfix verif fix

src/assets/styles/colors.css, src/containers/artist-dashboard-page/ArtistDashboardPage.module.css, src/utils/theme/dark.ts, src/utils/theme/default.ts, src/utils/theme/matrix.ts
Fixes tile in light mode
None
Local
=> Fix Stat Tiles in Light mode

src/containers/App.js, src/services/sentry.ts, src/store/account/sagas.js
Pull sentry out into its own service rather than utils and invoke setUser via saga rather than render flow
Nah
=> [AUD-373] Pull sentry set user out of render flow

package-lock.json, package.json, src/services/AudiusBackend.js, src/services/remote-config/RemoteConfig.ts, src/services/remote-config/defaults.ts
Enables optimizely discovery node block list to deal with temporary entire downtime from a single discovery node. Nominally to be unused.
Requires libs 1.1.17
N/a
Locally against prod & hotfixed on top of prod
=> Add blocklist

src/components/general/IconButton.tsx, src/components/general/IconPopup.module.css, src/components/general/IconPopup.tsx, src/components/general/Popup.js, src/utils/domUtils.ts
Description
Add a new component that represents icons that will display a popup with its menu items on click
Dragons
Whether current popup behavior is maintained
How Has This Been Tested?
Ran and tested on the browser manually on local
=> Add new icon popup component

public/index.html
Fixes recaptcha trying to use v2 instead of v3 when render=explicit.
Confirmed that this still loads into the hidden div
index.html
Created account, uploaded track
=> Fix recaptcha

src/components/general/IconButton.tsx, src/components/general/IconPopup.module.css, src/components/general/IconPopup.tsx, src/components/general/Popup.js
Add ability to determine placement for popup
Tested locally on browser
=> Add popup placement to icon popup component

src/components/drawer/Drawer.module.css, src/components/drawer/Drawer.tsx
Supports locked fullscreen drawers.
None
Locally
=> Add fullscreen drawer component

src/components/track/desktop/ConnectedPlaylistTile.tsx, src/components/track/desktop/ConnectedTrackTile.tsx, src/components/track/desktop/PlaylistTile.tsx, src/components/track/desktop/TrackTile.module.css, src/components/track/desktop/TrackTile.tsx, src/components/track/mobile/ConnectedPlaylistTile.tsx, src/components/track/mobile/ConnectedTrackTile.tsx, src/components/track/mobile/PlaylistTile.module.css, src/components/track/mobile/PlaylistTile.tsx, src/components/track/mobile/TrackTile.module.css, src/components/track/mobile/TrackTile.tsx, src/components/track/types.ts, src/containers/discover-page/components/RewardsBanner.module.css, src/containers/discover-page/components/RewardsBanner.tsx, src/containers/discover-page/components/desktop/TrendingPageContent.module.css, src/containers/discover-page/components/desktop/TrendingPageContent.tsx, src/containers/discover-page/components/mobile/TrendingPageContent.module.css, src/containers/discover-page/components/mobile/TrendingPageContent.tsx, src/containers/lineup/LineupProvider.tsx, src/containers/lineup/hooks.ts, src/containers/trending-playlists/TrendingPlaylistPage.module.css, src/containers/trending-playlists/TrendingPlaylistPage.tsx
Additional changes to finish trending page + playlist rending:
- Changes to tiles to show crowns
- Clickable rewards banner
None
Locally
=> Additional trending rewards work

public/index.html
Will wait on !window.bItems forever
=> Set no bitems if not found

package-lock.json, package.json, src/services/AudiusBackend.js, src/services/remote-config/FeatureFlags.ts
Add a feature flag for the URSM libs init
=> Add feature flag for URSM

src/utils/gdpr.ts, src/utils/route.js
Fixes gdpr display / deep link
n/a
manually enabled/set location to verify
=> Fix gdpr on desktop and hide on mobile

src/components/track/desktop/ConnectedTrackTile.module.css
See comment
- Safari
- Chrome
- Firefox
=> [AUD-389] Fix weird font alignment issue

src/components/drawer/Drawer.tsx
=> Fix fullscreen drawer style

src/containers/sign-on/store/sagas.js
Increases from 5 min to 20 min for bulk of work
=> Increase signup timeout

package-lock.json, package.json
Includes distributed tracing changes for mysterious "Network Error" bug
https://github.com/AudiusProject/audius-protocol/commit/8e5b53be7fb62b82cd5092250885a8c38883bc97
`npm run start:stage`
=> Up libs to 1.1.20

src/components/drawer/Drawer.module.css, src/containers/audio-rewards-page/AudioRewardsPage.tsx, src/containers/audio-rewards-page/RewardsTile.module.css, src/containers/audio-rewards-page/RewardsTile.tsx, src/containers/audio-rewards-page/Tiles.module.css, src/containers/audio-rewards-page/Tiles.tsx, src/containers/audio-rewards-page/components/ButtonWithArrow.module.css, src/containers/audio-rewards-page/components/ButtonWithArrow.tsx, src/containers/audio-rewards-page/components/ExplainerTile.module.css, src/containers/audio-rewards-page/components/ExplainerTile.tsx, src/containers/audio-rewards-page/components/modals/ModalDrawer.module.css, src/containers/audio-rewards-page/components/modals/ModalDrawer.tsx, src/containers/audio-rewards-page/components/modals/TopAPI.tsx, src/containers/audio-rewards-page/components/modals/TopApi.module.css, src/containers/audio-rewards-page/components/modals/VerifiedUpload.module.css, src/containers/audio-rewards-page/components/modals/VerifiedUpload.tsx, src/containers/nav/desktop/NavIconPopover.module.css, src/store/token-dashboard/sagas.ts
Can reference notion if curious. The discord code commit is the only interesting bug imo.
=> Fix rewards QA issues

src/containers/audio-rewards-page/components/modals/TopApi.module.css
Mobile fix broke a desktop fix :(
=> Additional Rewards QA fix

src/containers/sign-on/store/sagas.js
Has been hotfixed on prod for a bit, but we need to try for up to ~4s instead of up to ~2.5s because the check can take a while.
On prod 😈
=> Update ig max attempts

.circleci/config.yml, package-lock.json, package.json, src/containers/audio-rewards-page/WalletModal.module.css, src/containers/audio-rewards-page/WalletModal.tsx, src/containers/audio-rewards-page/components/PurpleBox.module.css, src/containers/audio-rewards-page/components/PurpleBox.tsx, src/containers/audio-rewards-page/components/modals/ModalDrawer.module.css, src/containers/audio-rewards-page/components/modals/ModalDrawer.tsx
Rename remaining audius-dapp references to audius-client
Use withMobileStyle to fix
=> Fix vip discord modal style on mobile

src/services/sentry.ts, src/store/account/sagas.js
Add isVerified user prop to sentry
Against staging
https://sentry.io/organizations/audius/discover/audius-staging:6810e2b5632840c3970ed7cc17fd35ae/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=1851611&query=&sort=-timestamp&statsPeriod=24h&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1
=> [AUD-436] Add is verified to sentry

src/components/track/desktop/TrackTile.module.css, src/containers/artist-dashboard-page/ArtistDashboardPage.tsx, src/containers/audio-rewards-page/Tiles.tsx, src/containers/audio-rewards-page/components/ExplainerTile.tsx, src/containers/audio-rewards-page/components/modals/TrendingRewards.module.css, src/containers/audio-rewards-page/components/modals/TrendingRewards.tsx, src/containers/audio-rewards-page/components/modals/VerifiedUpload.tsx, src/containers/discover-page/components/RewardsBanner.module.css, src/containers/nav/desktop/NavIconPopover.module.css, src/containers/nav/desktop/NavIconPopover.tsx, src/containers/trending-playlists/store/lineups/collections/reducer.ts, src/store/lineup/reducer.js
Still need to do Discord drawer, will be in the other PR. 
- Lineup hacky fix :( done with @jowlee 
Locally
=> Add more Rewards QA

src/components/general/InstagramAuth.tsx, src/containers/sign-on/store/sagas.js, src/services/remote-config/RemoteConfig.ts, src/services/remote-config/defaults.ts, src/utils/network.js
Add timeout in remote config instead of max attempts pattern
Locally against stage w/ insta check enabled
=> Clean up instagram check code

src/containers/discover-page/components/desktop/TrendingPageContent.tsx, src/containers/discover-page/components/mobile/TrendingPageContent.tsx
=> Disable rewards UI on trending genres

src/components/general/IconPopup.module.css, src/containers/collectibles/components/CollectiblesPage.module.css, src/containers/collectibles/components/CollectiblesPage.tsx
=> Add style changes

src/services/sentry.ts, src/store/account/sagas.js, src/store/analytics/providers/segment.ts
Add clientVersion to all segment track events and add isVerified + trackCount to identity events (same as sentry)
Ran against prod locally and follow my events through sentry & amplitude
=> [AUD-442] Add clientVersion and isVerified to segment

src/containers/audio-rewards-page/AudioRewardsPage.module.css, src/containers/audio-rewards-page/WalletModal.module.css, src/containers/audio-rewards-page/WalletModal.tsx, src/containers/audio-rewards-page/components/modals/ModalDrawer.tsx
Fix the styles on the drawer/modal on the /audio page
none, just styles
locally looked at it on my browser.
=> Fix audio modal drawer styles

src/containers/collectibles/components/CollectiblesPage.module.css, src/containers/collectibles/components/CollectiblesPage.tsx, src/containers/collectibles/helpers.ts, src/services/opensea-client/OpenSeaClient.ts, src/utils/imageProcessingUtil.js
=> Handle gifs and add style fixes

src/components/drawer/Drawer.tsx, src/containers/collectibles/components/CollectiblesPage.module.css, src/containers/user-badges/utils.ts, src/services/sentry.ts
Misc updates to feature collectibles
Commits should hopefully self-explainitory
=> Feature collectibles updates

src/containers/audio-rewards-page/AudioRewardsPage.tsx, src/hooks/useRequiresAccount.ts
=> Redirect on /audio if not logged in

README.md, package-lock.json, package.json, scripts/analyzeBundle.js
Description
Added Webpack Bundle Analyzer. I know we already include source-map-explorer but bundle analyzer shows more details, allows us to see content of concatenated modules and displays the gzipped / parsed file sizes.
Happy to keep this one local but thought it might be useful to have in the repo!
Dragons
How Has This Been Tested?
=> Bundle analyzer

src/containers/collectibles/components/CollectibleRow.tsx, src/containers/collectibles/components/CollectiblesPage.module.css, src/containers/collectibles/components/CollectiblesPage.tsx
Add more style tweaks and fixes to collectibles based on design feedback
Tested locally
=> Add more style tweaks and fixes to collectibles

src/containers/profile-page/ProfilePageProvider.tsx
Exit edit profile if routing to another user profile 
Fixes AUD-522
none
ran locally
=> Edit edit profile if route to another profile

src/containers/profile-page/components/EditableName.module.css
Screenshots of before and after
Actually not sure if this is what the below issue was referring to. 
Fixes AUD-282
none
ran locally.
=> Add ellipsis to profile page name

src/components/preload-image/PreloadImage.tsx, src/containers/App.js, src/containers/collectibles/components/CollectiblesPage.module.css, src/containers/collectibles/components/CollectiblesPage.tsx, src/containers/collectibles/components/types.ts, src/containers/collectibles/helpers.ts, src/containers/profile-page/ProfilePageProvider.tsx, src/containers/profile-page/components/desktop/ProfilePage.tsx, src/containers/profile-page/components/mobile/ProfilePage.tsx, src/containers/profile-page/store/types.ts, src/containers/user-badges/utils.ts, src/hooks/useTabs/useTabs.tsx, src/services/analytics.ts, src/services/opensea-client/OpenSeaClient.ts, src/utils/effects.js, src/utils/image.ts, src/utils/route.js, src/utils/route/userRouteParser.ts
Commits should be self-descriptive & reviewed 1 by 1. Requires somewhat thorough review/testing. The 2nd commit (profile page deep links) is a bit hefty, but allows us to link to things like
audius.co/rayjacobson/collectibles
but not have that take up a full history state (so the back button will not switch tabs).
Demo on ray.audius.co (http://ray.audius.co/rayjacobson/collectibles)
Touches useTabs (minorly, but touches it)
Locally against prod, web + mobile
=> Collectibles touchups

src/audio/AudioStream.ts, src/services/audius-api-client/AudiusAPIClient.ts, src/services/remote-config/RemoteConfig.ts, src/services/remote-config/defaults.ts, src/store/player/sagas.ts
Same as #345 but on top of the last released client app https://app.circleci.com/pipelines/github/AudiusProject/audius-client/1147/workflows/c785e01b-58d1-4092-8cb5-e510527dbd5c from commit 8fa9f02ba7af113a5193042d3253b04a9d272208
none
tested locally against prod and played regular tracks as well as diplo's
=> Hotfix diplo prev

src/containers/collectibles/helpers.ts, src/services/opensea-client/OpenSeaClient.ts
Fixes
1. Created collectibles not showing
2. Not all collectibles showing (limits)
=> Fix collectibles limits and creations

src/containers/collectibles/components/CollectiblesPage.tsx
Display spinner while processing gifs
tested locally
=> Display spinner while processing gifs

src/containers/collectibles/helpers.ts
=> Fix firefox

package-lock.json, package.json
Update libs version to fix audio send
none
ran on joey.audius.co
=> Update libs to 1.1.23

src/components/preload-image/PreloadImage.tsx, src/containers/collectibles/components/CollectiblesPage.tsx
=> Fix preload image as bg

src/containers/collectibles/components/CollectibleRow.tsx, src/containers/collectibles/components/CollectiblesPage.module.css, src/containers/collectibles/components/CollectiblesPage.tsx, src/utils/timeUtil.js
=> Display collectible dates based on timezone and fix min desktop tab width

src/containers/collectibles/components/CollectiblesPage.tsx
=> Play media inline in mobile drawer

src/containers/add-to-playlist/mobile/AddToPlaylist.tsx, src/containers/edit-playlist/mobile/EditPlaylistPage.tsx, src/hooks/README.md, src/hooks/useHasChangedRoute.ts
Closes the top level pages on mobile if the user routes to another page. 
Fixes AUD-509
none
locally in the chrome browser w/ mobile view
=> Close modal for top level mobile pages

src/services/opensea-client/OpenSeaClient.ts
=> Fix null pointer issue for event assets

src/components/search/SearchBar.module.css, src/components/search/SearchBarResult.module.css
Fix colors on search result autocomplete. 
Fixes AUD-390
before and after pics
none
Ran locally against prod - see screenshots
=> Fix colors on search result

src/utils/route/userRouteParser.ts
Fixes route parser issue caused by profile sub-routes.
Issue here is that track pages match the /:tab matcher.
=> Fix route parse for profile tabs

src/audio/AudioStream.ts, src/store/analytics/providers/segment.ts
=> Handle AudioContext constructor error and limit analytics tracking per session

package-lock.json, package.json, src/containers/collectibles/components/CollectibleDetails.tsx, src/containers/collectibles/components/CollectiblesPage.module.css, src/containers/collectibles/components/CollectiblesPage.tsx, src/containers/collectibles/components/types.ts, src/containers/collectibles/helpers.ts, src/containers/profile-page/components/desktop/ProfilePage.tsx, src/services/opensea-client/OpenSeaClient.ts, src/services/opensea-client/types.ts
- Fix video aspect ratios
- Fix duplicate collection token ids[
- Add tab recalculator to profile page 
=> Hotfix id collision

src/containers/notification/components/FormatText.module.css, src/containers/notification/components/formatText.tsx
Add user badges in notifications
Tested locally on both desktop and mobile
=> Add user badges in notifications

src/components/remix/RemixCard.module.css, src/components/remix/RemixCard.tsx, src/containers/user-badges/UserBadges.module.css, src/containers/user-badges/UserBadges.tsx
Fix user badges position on remixes
Tested locally
=> Fix user badges position on remixes

src/components/perspective-card/PerspectiveCard.tsx, src/containers/App.js, src/containers/explore-page/collections.ts, src/containers/explore-page/components/desktop/ExplorePage.tsx, src/models/Collection.ts, src/utils/route.ts
Fixes:
- trending/underground & trending/playlists -> explore/underground + explore/playlists, with redirect for backlinks
- fix horizontal movement on wide cards
none
locally
=> Trending Underground Fixes

.circleci/config.yml, .gitignore, package-lock.json, package.json, scripts/updateIpfsBuild.js, src/containers/profile-page/ProfilePageProvider.tsx, src/utils/route.ts
Fix to hash routing + IPFS build ci support
Ran e2e http://ipfs.staging.audius.co/
=> ipfs build

src/services/AudiusBackend.js
Scores are not computed properly because isElectron is a func and always returning truthy
=> Fix captcha

src/containers/track-page/store/retrieveTrending.ts, src/containers/track-page/store/sagas.js, src/containers/trending-playlists/store/lineups/collections/sagas.ts, src/containers/trending-underground/store/lineups/tracks/sagas.ts
TF didn't account for badges on track pages
=> Use TF in track page badges

src/components/search-bar/SearchBar.tsx, src/containers/nav/mobile/NavBar.tsx, src/containers/search-bar/store/actions.ts, src/containers/search-bar/store/mobileSagas.ts, src/containers/search-bar/store/sagas.js, src/containers/search-page/components/mobile/SearchPageContent.tsx, src/services/native-mobile-interface/search.ts, src/services/native-mobile-interface/types.ts, src/store/routing/mobileSagas.ts, src/utils/nativeRoute.ts
* Adds bindings for native search to message passing.
Relies on https://github.com/AudiusProject/audius-mobile-client/pull/77
None
Ran it locally against staging
=> Adds native mobile search

src/containers/search-page/components/mobile/SearchPageContent.module.css, src/containers/search-page/components/mobile/SearchPageContent.tsx
Adds header to search page
none
ran locally in app and in mobile browser
=> Fix mobile native search

src/components/drawer/Drawer.tsx
If the drawer is not open, but the keyboard is opened and closed, then the drawer is opened. 
Fixes AUD-284
none
I tested this locally on native.
=> Fix drawer appearing if not open and keyboard opens

.env/.env.prod
Updates eager selection to remove downed node
=> Update eager selection

.circleci/config.yml
cid.audius.co
cid.staging.audius.co
We pull these CIDs when generating manifests to ship https://github.com/AudiusProject/audius-k8s/pull/215
Manually ran CI job with branch filter removed
=> Publish CIDs

src/containers/upload-page/components/FinishPage.module.css
Add space between 'Created by and user name in FinishPage'
Tested Locally
=> Add spaced between Created by and user name

package-lock.json, package.json, src/app.tsx, src/types/object.entries/index.d.ts, src/utils/polyfill.ts
This reverts commit 4c949d300d576d5a6e7629090e25483555eabaaf.
=> Revert "Shim Object.entries (#404)"

package-lock.json, package.json, src/containers/trending-underground/TrendingUndergroundPage.tsx, src/services/AudiusBackend.js, src/services/remote-config/FeatureFlags.ts
Flag removed in
https://github.com/AudiusProject/audius-protocol/compare/rj-remove-user-replica-flag?expand=1
Requires libs bump
Created staging account
=> Remove user replica flag

scripts/workers-site/index.js, wrangler.toml
Redirect `/sitemaps` to the s3 bucket
none
You can test on joe.audius.co
=> Add sitemaps redirect from cloudflare

src/containers/audio-rewards-page/RewardsTile.tsx, src/containers/audio-rewards-page/components/modals/TrendingRewards.tsx, src/containers/explore-page/components/desktop/ExplorePage.tsx, src/containers/explore-page/components/mobile/ExplorePage.module.css, src/containers/explore-page/components/mobile/ExplorePage.tsx, src/containers/trending-underground/TrendingUndergroundPage.tsx, src/services/remote-config/FeatureFlags.ts, src/services/remote-config/Provider.ts
Removes trending underground feature flag. 
Nah
Testing locally
=> Remove trending underground flag

.env/.env.prod, .env/.env.stage, src/containers/App.js, src/containers/check-page/CheckPage.module.css, src/containers/check-page/CheckPage.tsx, src/containers/embed-modal/EmbedModal.tsx, src/models/User.ts, src/services/AudiusBackend.js, src/utils/route.ts
Add /check page for cognito.
Waiting on identity release to test e2e, but code can be reviewed now!
https://github.com/AudiusProject/audius-protocol/pull/1485
Locally ngrok
=> Add cognito check page

package-lock.json, package.json, src/services/AudiusBackend.js, src/services/remote-config/FeatureFlags.ts
Consume libs 1.2.1 for resumable track upload
linking libs:
1. ran dapp locally, pointed against staging
2. uploaded track successfully 
using published libs:
1. ran dapp locally, pointed against staging
2. uploaded track successfully
=> Add optimizely flag for resumable track upload + consume libs 1.2.1

src/services/AudiusBackend.js
Was getting error in console where `this` could not be found. The fix is to replace `this` with `AudiusBackend`
Uploaded an album pre and post fix. Fix worked
=> Update 'this' to 'AudiusBackend' in confirmer calls

src/components/card/mobile/Card.module.css, src/components/card/mobile/Card.tsx, src/components/general/UpdateDot.module.css, src/components/general/UpdateDot.tsx, src/containers/collection-page/CollectionPage.tsx, src/containers/collection-page/CollectionPageProvider.tsx, src/containers/nav/desktop/NavColumn.js, src/containers/nav/desktop/NavColumn.module.css, src/containers/notification/store/actions.ts, src/containers/notification/store/reducer.ts, src/containers/notification/store/sagas.ts, src/containers/notification/store/selectors.ts, src/containers/notification/store/types.ts, src/containers/saved-page/SavedPage.tsx, src/containers/saved-page/SavedPageProvider.tsx, src/containers/saved-page/components/mobile/SavedPage.tsx, src/services/AudiusBackend.js, src/store/social/collections/sagas.ts
Display playlist update dots on nav column and mobile playlist favorites
Tested locally by having 2 users on different browsers, favoriting each other's playlists, adding tracks to their own playlists, and verifying that there is the playlist dot on the others' playlists after track addition. Playlist dots dismiss on clicking the playlist.
=> Add playlist updates

src/containers/track-page/TrackPageProvider.tsx
=> Add track redirect

.env/.env.stage
=> Update sokol RPC

src/containers/nav/desktop/NavColumn.js, src/containers/remote-config/hooks.ts, src/containers/saved-page/components/mobile/SavedPage.tsx, src/services/AudiusBackend.js, src/services/remote-config/FeatureFlags.ts
=> Add feature flag for playlist updates

src/components/background-animations/MusicConfetti.tsx
Fix profile completion confetti
Locally against staging.
=> Fix profile completion confetti

package-lock.json, package.json
=> Libs 1.2.3

src/containers/audio-rewards-page/Tiers.tsx, src/containers/first-upload-modal/FirstUploadModal.tsx, src/containers/music-confetti/ConnectedMusicConfetti.tsx, src/containers/music-confetti/store/slice.ts, src/containers/settings-page/SettingsPageProvider.tsx, src/containers/settings-page/components/desktop/VerificationModal.tsx
=> Use ConnectedMusicConfetti for first track upload

.circleci/config.yml, package-lock.json, package.json
Create release branching nomenclature
Just a small CI change--no functionality impact.
`circleci config validate`
=> Release branch nomenclature

src/containers/audio-rewards-page/AudioRewardsPage.module.css, src/containers/audio-rewards-page/Tiers.module.css, src/containers/audio-rewards-page/Tiles.module.css, src/containers/audio-rewards-page/components/ExplainerTile.module.css
The https://audius.co/audio page is not responsive, and gets cut off with no remedy (as we don't have horizontal scrolling) to read the content on smaller screens. Added flexboxes and wrapping to make it responsive.
The bottom tier list might have 3 tiers on top, 1 on bottom for certain screen sizes. Is that a dealbreaker? Can put more time into it and force them to break into 2 and 2
1. Visit https://marcus.audius.co/audio
2. Resize window slowly, observe responses
⚠️ have not tested mobile!
=> First pass at making the Audio page responsive

src/services/AudiusBackend.js
This log should help us see why we get COLLECTION_CREATE_PLAYLIST_NO_ID errors in sentry. We currently assume that we never hit this code path. This log is to double-check this assumption.
=> Add log to check whether we hit catch block of createPlaylist

package-lock.json, package.json
Fix mac electron build, per convo in https://github.com/electron/electron/issues/23534#issuecomment-661126808 via update to electron-builder package.
To cherry-pick onto `release-v0.24.18`
Touches a version of the electron-builder package.
Local build + signing of staging app
`npm run dist:mac`
Output:
```
audius-client git:master ❯ npm run dist:mac …
```
=> Up electron-builder to 22.10.5

src/components/play-bar/repeat-button/RepeatButton.js, src/components/play-bar/shuffle-button/ShuffleButton.js
#439 introduced a bug as the settings weren't being applied on mount, and the state wasn't being propagated to the store.
Locally against stage db, see previous PR for details
=> Handle changes on mount to put state in store

src/services/audius-api-client/AudiusAPIClient.ts, src/services/remote-config/RemoteConfig.ts, src/services/remote-config/defaults.ts
Add flag to support trending exp.
Tested locally against prod using the exp. `ePWJD`
=> Add UI flag for trending experiment

src/store/account/selectors.ts
This selector is returning albums when it should not be
Locally against prod with my account
=> Fix account navigation playlist selector

src/containers/sign-on/components/ProfileForm.js
Update copy per chat w/ Forrest!
=> Update handle copy

package-lock.json, package.json
Fixes a bug in libs 1.2.4 https://github.com/AudiusProject/audius-protocol/pull/1596
=> Update libs to 1.2.5

.github/pull_request_template.md
As discussed, adding a section about monitoring/alerting to the PR template.
If this one looks good to you guys I'll put add it to `audius-protocol`
=> Add monitoring section to PR template

.env/.env.stage
Our sokol gateway is not behaving correctly -- seeing inconsistent transaction data. Need to investigate that more.
n/a
Locally & created an account against stage
Probers
=> Remove audius poa sokol gateway

src/store/cache/collections/selectors.ts
Make sure users has a length before fetching them from a collection
`npm run start:prod`
=> Check length of users

src/containers/user-list/UserList.tsx
Filter out users not in cache
none
ran prod locally
manually
=> Fix error for user list no user in cache

.env/.env.stage
After upgrading Nethermind past https://github.com/NethermindEth/nethermind/pull/3155, our nodes are functional!
npm run start:stage & create account and repost track
Probers
=> Update poa provider

src/containers/embed-modal/EmbedModal.tsx
Changes embed schema used in client to hash id based
Closes AUD-772
Embed track
Embed playlist
Embed album
Community feedback
=> Update client embed player url

src/containers/track-page/store/sagas.js
This reverts commit 7b6aad748dbff2111b8ef113ae2227e01f49d43a.
This original change was added temporarily as support for trending experiments had not reached discovery nodes (https://github.com/AudiusProject/audius-protocol/pull/1557).
That change landed in 0.3.38, so it is safe to revert back to the old (better) logic
=> Revert "Temporarily fix track page badge experiment dep (#452)"

scripts/configureLocalEnv.js
Currently seeing some error on start:dev setup where this is undefined. Might be due to react scripts change?
=> Add items to configure local env

package-lock.json, package.json
Closes AUD-662
Touches crypto dependencies (web3.js), which is potentially very scary. This build requires lots of QA.
* Create account
* Upload track
* Create playlist (of varying unicode strings)
* $AUDIO xfer
Sentry
=> Update libs to 1.2.13

src/containers/nav/desktop/PlaylistLibrary.tsx, src/containers/notification/store/sagas.ts, src/containers/saved-page/components/mobile/SavedPage.tsx, src/hooks/useImageSize.ts, src/services/analytics.ts, src/store/analytics/providers/segment.ts, src/store/playlist-library/sagas.ts, src/store/social/collections/sagas.ts
Adds a few new analytics events around playlist library
1. Playlist reorders
2. Has playlist updates
3. Click on playlist library nav item (and track whether it had an update or not)
New logs for analytics events in non-production build.
Tested both desktop web & desktop mobile
Amplitude!
=> Add analytics around playlist library

package-lock.json, package.json
https://github.com/AudiusProject/stems/pull/50
=> Bump stems

src/utils/route.ts
Current link is non-existent. This should probably redirect to the new docs setup once that is in place.
=> Direct devs+stakers to /protocol

src/services/AudiusBackend.js
Fixes local dev setup
npm run start:dev:cloud
=> Ignore claimable token PDA if not set

src/containers/smart-collection/store/sagas.ts
Limiting artists popping up too many times in the remixables playlist
=> Update fetchRemixables query to limit the number of times an artist can appear

src/containers/smart-collection/store/sagas.ts, src/services/audius-api-client/AudiusAPIClient.ts, src/services/audius-api-client/ResponseAdapter.ts
Temporary fix for remixables while disc-prov is being fixed
Removes the with_users flag from remixables query and does a fetch for users afterwards
=> Add a temporary fix for remixables while disc-prov is being fixed

package-lock.json, package.json
=> Libs 1.2.16

src/containers/explore-page/components/desktop/ExplorePage.tsx, src/containers/explore-page/components/desktop/Section.tsx, src/services/remote-config/FeatureFlags.ts
=> Add remixables web FF

src/services/remote-config/FeatureFlags.ts
=> Switch to underscore for remixables_web

package-lock.json, package.json
=> Libs 1.2.18

src/hooks/useTikTokAuth.ts
This PR increases the granularity of tiktok error analytics to differentiate between `server_errors` coming from tiktok and other errors in the auth flow
=> Increase granularity of tiktok error analytics

src/components/tracks-table/TableOptionsButton.js, src/components/tracks-table/TracksTable.js
https://linear.app/audius/issue/AUD-854/[qa]-visit-track-page-overflow-menu-button-not-functioning-properly
Missing props
=> [AUD-854] Fix permalink from playlistpage

package-lock.json, package.json, src/services/AudiusBackend.js, src/services/remote-config/RemoteConfig.ts, src/services/remote-config/defaults.ts
=> Update reselection timeouts

src/containers/sign-on/components/desktop/ProfilePage.js
uuid is not passed back by the format function and it's being overwritten as undefined. this leads to no associate call being made. this works on mobile.
Need to test on stage. Discovered this by tracing redux dev tools
=> Fix oauths

src/containers/notification/NotificationPanel.tsx, src/containers/notification/components/FormatText.module.css, src/containers/notification/components/TwitterShare.tsx, src/containers/notification/components/desktop/NotificationBlock.module.css, src/containers/notification/components/desktop/NotificationBlock.tsx, src/containers/notification/components/formatText.tsx, src/containers/notification/store/types.ts, src/utils/tweet.ts
Add the NotificationType, notification block component, and formatText code for ChallengeReward notifications
manually
=> AUD-764 Add ChallengeReward desktop notification

src/containers/audio-rewards-page/components/WalletsTable.tsx
=> Fix wallet table column style

src/services/solana-client/SolanaClient.ts
We don't own the nft => don't show
Locally against prod data
=> Filter non-owned sol NFT

src/components/preload-image/PreloadImage.tsx, src/containers/collectibles/components/CollectibleDetails.tsx, src/containers/collectibles/ethCollectibleHelpers.ts, src/containers/collectibles/solCollectibleHelpers.ts
Compute gif frame during collectible render and display loading spinner
Manually
=> Improve collectible performance and experience

src/containers/collectibles/ethCollectibleHelpers.ts
=> Fix name if missing

src/containers/profile-page/store/sagas.js, src/services/solana-client/SolanaClient.ts
=> Fix collectibles display after edit

package-lock.json, package.json, src/services/solana-client/SolanaClient.ts
Pass all program addresses to getMultipleAccountsInfo to reduce number of rpc calls
Spun up dapp and tested locally and it works. same results as in prod
=> Pass all program addresses to getMultipleAccountsInfo to reduce number of rpc calls

src/containers/audio-rewards-page/components/SendingModalBody.module.css, src/containers/collectibles/components/CollectibleDetails.tsx, src/containers/collectibles/components/CollectiblesPage.module.css, src/containers/profile-page/components/desktop/ProfilePage.tsx, src/containers/profile-page/components/mobile/ProfilePage.tsx
Fix collectible edge cases and styling
Spun up app locally and tested.
=> Fix collectible edge cases and styling

scripts/workers-site/index.js
=> Hotfix: Redirect old links

src/containers/profile-page/store/sagas.js
=> Fix null collectibles metadata schema

src/containers/collectibles/components/CollectiblesPage.module.css, src/containers/collectibles/solCollectibleHelpers.ts, src/services/solana-client/SolanaClient.ts, src/services/solana-client/types.ts
Add solana nfts that live in star atlas.
Manually by looking at accounts that have not only star atlas nfts, but also metaplex/arweave and eth nfts.
=> Add star atlas solana nfts

src/containers/audio-rewards-page/components/ClickableAddress.module.css, src/utils/zIndex.ts
Fix wallet connection zindex
Locally
=> Fix clickable addr

src/containers/collectibles/solCollectibleHelpers.ts, src/services/solana-client/SolanaClient.ts, src/services/solana-client/types.ts
Add compatibilities for more nfts
local against prod, also deployed to subdomain for others to test
=> Add compatibilities for more nfts

src/containers/collectibles/components/CollectibleDetails.tsx, src/containers/collectibles/solCollectibleHelpers.ts
=> Fix order of variables in extension check

src/containers/audio-rewards-page/components/WalletsTable.tsx
Fix disappearing connect wallet modal
=> Fix disappearing connect wallet modal

package-lock.json, package.json
Need to bump libs for challenges local testing
None
Locally
n/a
=> Bump libs to 1.2.22

src/services/solana-client/SolanaClient.ts
Handle downed RPC for solana collectibles better
Locally against prod
=> Dont block on RPC

src/containers/sign-on/SignOnProvider.tsx, src/containers/sign-on/components/desktop/ProfilePage.js, src/containers/sign-on/components/desktop/SignOnPage.tsx, src/containers/sign-on/components/desktop/TwitterOverlay.js, src/containers/sign-on/components/mobile/ProfilePage.tsx, src/containers/sign-on/components/mobile/SignOnPage.tsx, src/containers/sign-on/components/mobile/TwitterOverlay.js, src/containers/sign-on/store/actions.js, src/containers/sign-on/store/sagas.js, src/services/analytics.ts
=> Fix events, fix, and clean up race cond in oauths

src/store/cache/tracks/utils/blocklist.ts
=> Fix bitems

src/containers/sign-on/components/desktop/TwitterOverlay.js
Fixes residual `this` from https://github.com/AudiusProject/audius-client/pull/545/files#r700449088
Ran locally vs staging, tested signup 
=> Fix overlay

scripts/workers-site/index.js
Updates the cloudflare worker to redirect `/undefined` to the homepage.
=> Reroute /undefined to homepage

scripts/workers-site/index.js
=> Move worker /undefined check to the start to impact GA

src/services/audius-api-client/AudiusAPIClient.ts
Makes the handle check on the fallback logic case insensitive
=> Make handle check case insensitive

src/containers/search-bar/store/sagas.js
=> Fix search autocomplete bitem

src/containers/audio-rewards-page/ChallengeRewardsTile.tsx, src/containers/audio-rewards-page/components/modals/ChallengeRewards.tsx, src/containers/audio-rewards-page/config.tsx, src/containers/audio-rewards-page/types.ts, src/containers/notification/components/FormatText.module.css, src/containers/notification/components/TwitterShare.module.css, src/containers/notification/components/TwitterShare.tsx, src/containers/notification/components/desktop/NotificationBlock.tsx, src/containers/notification/components/formatText.tsx, src/containers/notification/store/sagas.ts, src/containers/notification/store/types.ts, src/containers/user-badges/utils.ts
-  Added code for tier changes notifications
- Updated code to account for proper challenge ids
Manual testing in the client
=> Add notifications for  tier changes

src/containers/audio-rewards-page/components/ClaimRewardButton.tsx, src/containers/audio-rewards-page/components/modals/ChallengeRewards.module.css, src/containers/audio-rewards-page/components/modals/ChallengeRewards.tsx, src/containers/audio-rewards-page/components/modals/HCaptchaModal.module.css, src/containers/audio-rewards-page/components/modals/HCaptchaModal.tsx, src/containers/audio-rewards-page/components/modals/ModalDrawer.module.css, src/containers/audio-rewards-page/components/modals/RewardsModals.tsx, src/containers/audio-rewards-page/config.tsx, src/containers/audio-rewards-page/store/sagas.ts, src/containers/audio-rewards-page/store/slice.ts, src/containers/audio-rewards-page/types.ts, src/containers/check-page/CheckPage.module.css, src/services/AudiusBackend.js, src/services/remote-config/RemoteConfig.ts, src/services/remote-config/defaults.ts, src/utils/constants.ts, src/utils/zIndex.ts
Add claim reward button flow
Spin up dapp locally and go through the different flows
=> Add claim reward button flow

src/components/data-entry/TabSlider.js, src/components/data-entry/TabSlider.module.css, src/components/general/CoverPhoto.js, src/components/general/ProfilePicture.js, src/components/image-selection/ImageSelectionButton.js, src/components/image-selection/ImageSelectionPopup.js, src/components/image-selection/ImageSelectionPopup.module.css, src/components/image-selection/PropTypes.js, src/components/upload/UploadArtwork.js, src/containers/collectibles/components/CollectibleDetails.tsx, src/containers/collectibles/components/CollectiblesPage.module.css, src/containers/collectibles/components/CollectiblesPage.tsx, src/containers/profile-page/ProfilePageProvider.tsx, src/containers/profile-page/components/desktop/ProfilePage.tsx, src/containers/profile-page/components/mobile/ProfileHeader.tsx, src/containers/profile-page/components/mobile/ProfilePage.tsx, src/containers/profile-page/components/mobile/UploadStub.tsx, src/services/analytics.ts, src/services/remote-config/FeatureFlags.ts
[AUD-937 AUD-938 AUD-939]
- Added NFT option to the ImageSelectionPopup behind a feature flag
- Added a button to set profile picture to collectible details modal
- Updated TabSlider to work better with flexible width and not have a hard-coded padding value
Lots of manual testing
=> [AUD-937 AUD-938 AUD-939] Add NFT option to image picker

.circleci/config.yml
https://github.com/AudiusProject/audius-client/pull/590
Removed test-staging prereq, but didn't add build-staging
=> Add back requires step

package-lock.json, package.json
For attestations and cm changes.
=> Upgrade libs: attestations and cm

.circleci/config.yml
Probers were fixed in https://github.com/AudiusProject/probers/commit/5fb7b055128300291025432eebf9953e9dd95b27
=> Put probers back

src/containers/collectibles/components/CollectibleDetails.tsx, src/containers/collectibles/components/CollectiblesPage.module.css
Small styling updates for CollectibleDetails modal to match the figma design
=> Update styles for CollectibleDetails modal

src/containers/upload-page/store/sagas.js
=> Double upload timeout

package-lock.json, package.json
https://github.com/AudiusProject/audius-protocol/pull/1926
=> Bump libs to 1.2.25

src/containers/collectibles/components/CollectiblesPage.tsx
Feature flag null check gotcha
Local vs. prod
=> Fix collectibles race cond with feature flag

src/components/image-selection/ImageSelectionPopup.js, src/components/image-selection/ImageSelectionPopup.module.css
Fixes for NFT image picker styles and rendering without order object
=> Add fixes for NFT image picker styles and rendering without order object

src/containers/sign-on/components/desktop/EmailPage.tsx, src/containers/sign-on/components/mobile/InitialPage.tsx
=> Disabled buttons should have the disabled type

src/components/image-selection/ImageSelectionPopup.module.css
Use grid to fix collectibles view image picker styles
=> Update collectibles styles in image picker

src/components/image-selection/ImageSelectionPopup.js, src/containers/collectibles/components/CollectibleDetails.tsx
=> Add silver restriction

src/services/solana-client/SolanaClient.ts
Audius x Thugbirds sol nft now shows up on the collectibles tab.
Spin up app locally and view thugbirdz audius nft.
=> Show thugbirdz and ipfs-hosted sol collectibles

src/containers/audio-rewards-page/components/modals/ChallengeRewards.module.css, src/containers/sign-on/store/sagas.js, src/services/analytics.ts
[AUD-666]
Adding a new saga and updating sign up saga to follow the Hot & New playlist
=> [AUD-666] Update sign up flow to auto-follow Hot & New Playlist

src/containers/discovery-node-selection/DiscoveryNodeSelection.tsx
Fix import broken in #640 
npm run start
=> Fix import

src/components/search/SearchBar.module.css
Coloring was off on hover state before and font was incorrect.
Fixed!
Locally
=> [AUD-1070] Fix no results option in search bar

src/containers/nav/desktop/NavAudio.module.css, src/containers/nav/desktop/NavColumn.js
Fix nav header margin when not logged in. Also tweak fade in.
Locally without and with logged in user.
=> Fix nav header margin when not logged in

src/containers/collectibles/ethCollectibleHelpers.ts
Fix edge case where the nft is a video and the image is a gif
=> Fix video frame

src/containers/audio-rewards-page/config.tsx
Updating these to match the DN config for ease of testing, prior to these being finalized in the future
No
=> Update rewards config

.circleci/config.yml
Upgrade CI node version to 14.
See existing breakage:
https://app.circleci.com/pipelines/github/AudiusProject/audius-client/2636/workflows/d226092c-41c6-43cd-9fbe-a1707db3851a/jobs/15711
Let CI run
=> [AUD-1101] Upgrade CI to node 14

src/containers/collectibles/components/CollectibleDetailsModal.tsx, src/containers/collectibles/components/CollectiblesPage.module.css, src/containers/collectibles/components/CollectiblesPage.tsx
[AUD-1058]
- Added edit and share buttons to mobile collectibles page
- Added share button to mobile collectibles details drawer
=> [AUD-1058] Add share buttons to mobile collectibles page and collectibles drawer

src/containers/audio-rewards-page/components/ClaimRewardButton.tsx
=> Fix import order

package-lock.json, src/containers/audio-rewards-page/components/modals/RewardsModals.tsx
Add native mobile transfer audio drawer
Locally against native mobile app on iOS
=> Add native mobile transfer audio drawer

package-lock.json, package.json, src/services/AudiusBackend.js
Consumes latest libs (currently unpublished, will update this PR with package-lock when it is)
None
Locally, a lot
=> Consume latest libs with Solana Relay changes

src/containers/audio-rewards-page/Tiles.tsx
Updating MobileConnectWalletsDrawer to only render on web mobile
Manually tested. It doesn't render
=> Update MobileConnectWalletsDrawer to only render on web mobile

src/containers/profile-page/store/lineups/feed/reducer.js
Fixed actually in https://github.com/AudiusProject/audius-protocol/pull/1977 which is safely rolled out everwhere, so the original change in https://github.com/AudiusProject/audius-client/pull/612 can be reverted
Demo site
=> Remove deleted from reposts

src/common/store/cache/users/sagas.js
=> Remove unused averageRgb call on users

.circleci/config.yml
Disable script execution in installed packages. Not a magic bullet, but certainly a good measure.
Demo site
=> Ignore scripts in CI

src/containers/audio-rewards-page/components/modals/TopAPI.tsx
This PR:
* Disables the TopAPI drawer on native mobile (will show the RN component instead)
=> [AUD-1007] Api Rewards Explainer in RN

src/common/services/remote-config/remote-config.ts
`console.time` broke the mobile client, commenting for now
=> Remove console.time

src/common/store/cache/collections/selectors.ts
Fix missing track in playlist bug from crashing user session. Record console.error though still so we get notified.
=> Hotfix missing track in collection

.circleci/config.yml
We should not be doing this.
Demo site CI jobs
=> Remove update npm statements from CI config

package-lock.json, package.json
Includes https://github.com/AudiusProject/audius-protocol/pull/2210
None
Staging
n/a
=> Consume libs 1.2.42

src/components/general/CoverPhoto.js, src/components/general/CoverPhoto.tsx
Fixes default cover photo tiling, by overriding the default DynamicImage `background-size` from `cover` to `auto`. 
Also converts CoverPhoto to ts.
Go to any track with a default cover photo, modify screen size, and confirm it tiles and the resolution stays true.
=> [AUD-1034] Fix default CoverPhoto tiling

src/components/general/CoverPhoto.tsx
Refactors to use Nullable type based on feedback
=> Refactor CoverPhotoProps to use Nullable util type

src/containers/profile-page/components/mobile/ProfilePage.module.css, src/containers/profile-page/components/mobile/ProfilePage.tsx, src/containers/profile-page/components/mobile/ShareUserButton.module.css, src/containers/profile-page/components/mobile/ShareUserButton.tsx
- replaces kebab-menu with share-user-button
- refactors share-user-button to be separate component
=> [AUD-1187] Replace kebab-menu with share-user-button

package-lock.json, package.json, src/common/store/cache/tracks/sagas.js, src/containers/nav/desktop/CurrentlyPlaying.tsx, src/containers/nav/desktop/NavColumn.js, src/containers/now-playing/NowPlaying.tsx, src/containers/visualizer/VisualizerProvider.tsx, src/store/application/ui/average-color/slice.ts, src/utils/imageProcessingUtil.js, src/utils/visualizer/shaders/visualizer-1.frag, src/utils/visualizer/visualizer-1.js, src/workers/averageRgb.worker.js, src/workers/dominantColor.worker.js
- Within UI state for tracks add fields for averageColor and dominantColors
- Make changes to dominantColorWorker to get 3 dominant colors from album art
- Pass dominant colors to visualizer through the visualizer provider
UI changes to design coming in different PR
Ran visualizer locally with these changes, works as expected! 
https://user-images.githubusercontent.com/12490332/148117476-218c7ad3-c2d0-4abd-99c2-10e400c2e876.mov
=> [AUD-1148] Get visualizer working with 3 album art colors

src/components/action-drawer/ActionDrawer.tsx
My bad, linter wasn't configured properly!
=> Remove extraneous ActionIcon import

src/common/store/index.ts, src/common/store/ui/modals/slice.ts, src/common/store/ui/share-modal/sagas.ts, src/common/store/ui/share-modal/slice.ts, src/common/store/ui/share-modal/types.ts, src/containers/Modals.tsx, src/containers/profile-page/components/mobile/ShareUserButton.tsx, src/containers/share-modal/ShareModal.tsx, src/containers/share-modal/components/ShareDrawer.module.css, src/containers/share-modal/components/ShareDrawer.tsx, src/store/sagas.js
Adds a basic ShareModal and connects it to our store following the established modal patterns.
=> [AUD-1198] Add and connect ShareModal

src/common/store/pages/audio-rewards/slice.ts, src/common/store/wallet/slice.ts, src/common/utils/wallet.ts, src/containers/audio-rewards-page/components/ClaimRewardButton.tsx
Updates the challenge complete optimistically and updates the user balance
Closes AUD-1158
Ran manually while mocking submitAndEvaluateAttestations
=> Optimistic challenge complete and balance update

src/services/AudiusBackend.js
Handle null case in getWaudioBalance
=> Don't crash if Userbank creation fails

src/services/audius-backend/waudio.ts, src/store/account/sagas.js
Recover if no userbank exists
Tested with a broken account on staging
=> [AUD-1227] Create userbanks if needed

package-lock.json, package.json
=> Consume libs 1.2.49

src/common/models/Analytics.ts, src/containers/share-modal/components/ShareDrawer.module.css, src/containers/share-modal/components/ShareDrawer.tsx
Adds share-to-twitter action to ShareDrawer
Should we include analytics similar to https://github.com/AudiusProject/audius-client/blob/70748bba8f05cc9f15adf0d38b5d747d6d0f5ffa/src/containers/notification/components/TwitterShare.tsx#L278 ?
=> [AUD-1220] Add share-to-twitter action to ShareDrawer

src/containers/share-modal/components/ShareDrawer.tsx
Add share-to-titktok action to ShareDrawer for tracks owned by current user
Curious what reviewers think of the code choices in the `getActions` helper
=> [AUD-1221]: Add share-to-titktok action to ShareDrawer

src/containers/share-modal/components/DesktopShareModal.module.css, src/containers/share-modal/components/DesktopShareModal.tsx, src/containers/share-modal/components/ShareDrawer.tsx, src/containers/share-modal/messages.ts
Adds share modal for desktop
I wasn't able to compose stem button styles without using `!important`, not sure if im doing something wrong, or potentially a bug?
=> [AUD-1224] Add DesktopShareModal

src/components/action-drawer/ActionDrawer.tsx, src/containers/share-modal/ShareModal.tsx, src/containers/share-modal/components/IconTikTok.tsx, src/containers/share-modal/components/ShareDialog.module.css, src/containers/share-modal/components/ShareDialog.tsx, src/containers/share-modal/components/ShareDrawer.module.css, src/containers/share-modal/components/ShareDrawer.tsx, src/containers/share-modal/messages.ts, src/containers/share-modal/types.ts
- Brings desktop and mobile share layouts together
- Finalizes styling
=> [AUD-1230] Combine desktop and mobile share-modal

src/services/AudiusBackend.js
Changes in:
- https://github.com/AudiusProject/audius-protocol/pull/1790
Changed `audiusLibs.Challenge` to `audiusLibs.Rewards` 
=> Consume libs breaking change from Challenge => Rewards

src/components/image-selection/PropTypes.js, src/containers/audio-rewards-page/RewardsTile.module.css, src/containers/audio-rewards-page/components/modals/ChallengeRewards.module.css
A couple small ui fixes based on Julian's feedback
=> Add small rewards UI fixes

package-lock.json, src/components/action-drawer/ActionDrawer.module.css, src/components/track/GiantTrackTile.js, src/components/track/desktop/ConnectedTrackTile.tsx, src/components/track/desktop/TrackTile.tsx, src/components/track/mobile/BottomButtons.tsx, src/components/track/mobile/ConnectedTrackTile.tsx, src/containers/now-playing/NowPlaying.tsx, src/containers/now-playing/components/ActionsBar.tsx, src/containers/share-modal/ShareModal.tsx, src/containers/share-modal/components/ShareDialog.module.css, src/containers/share-modal/components/ShareDialog.tsx, src/containers/share-modal/components/ShareDrawer.tsx, src/containers/share-modal/types.ts, src/containers/track-page/TrackPageProvider.tsx, src/containers/track-page/components/mobile/ActionButtonRow.tsx, src/containers/track-page/components/mobile/TrackHeader.tsx
Updates all share track buttons to open the ShareModal instead of copying track link to clipboard.
- TrackListItem mobile and desktop
- TrackPage mobile and desktop
- NowPlaying Drawer
=> [AUD-1247]: Open ShareModal when sharing tracks

src/containers/audio-rewards-page/config.tsx
=> Fix challenge descriptions

src/common/store/ui/share-modal/selectors.ts, src/components/actions-tab/ActionsTab.js, src/components/collection/desktop/CollectionHeader.js, src/components/collection/mobile/CollectionHeader.js, src/components/track/desktop/TrackListItem.tsx, src/components/track/mobile/ConnectedPlaylistTile.tsx, src/components/track/mobile/ConnectedTrackListItem.tsx, src/components/track/mobile/ConnectedTrackTile.tsx, src/containers/now-playing/NowPlaying.tsx, src/containers/now-playing/components/ActionsBar.tsx, src/containers/share-modal/ShareModal.tsx, src/containers/share-modal/components/IconTikTok.tsx, src/containers/share-modal/components/ShareDialog.module.css, src/containers/share-modal/components/ShareDialog.tsx, src/containers/share-modal/components/ShareDrawer.module.css, src/containers/share-modal/components/ShareDrawer.tsx, src/containers/track-page/components/mobile/TrackHeader.tsx
Addresses callouts https://www.notion.so/audiusproject/Share-Menu-QA-0578063986144490b253242f63d9ecf0
=> [AUD-1247] Improve matrix mode, styles, fix share button

src/pages/audio-rewards-page/ChallengeRewardsTile.tsx, src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
=> [AUD-1295] Fix broken staging build

src/common/services/remote-config/feature-flags.ts, src/components/notification/store/sagas.ts, src/services/AudiusBackend.js
Add with rewards feature flag for client to get notifications with rewards
Related to PR: https://github.com/AudiusProject/audius-protocol/pull/2321
Closes AUD-1272
Ran locally against local identity with staging db seed
=> Add notifications with rewards ff

package-lock.json, package.json
Gets us: https://github.com/AudiusProject/audius-protocol/commit/74c0add3edb2a8cc0376fa4d691f57a440b1cccf
=> Libs 1.2.52

src/components/profile-progress/store/selectors.js, src/pages/profile-page/ProfilePageProvider.tsx
- Allow empty strings to be valid user bio/description and be consistent with DN
- Also display current user name if user attempts to save empty name
Locally against staging. update bio to be empty check that it's part of profile completion stages. failed attempt to save empty name
=> Update profile bio logic

scripts/configureLocalEnv.js, src/pages/audio-rewards-page/store/sagas.ts
Consume AAO config in client for local dev
On local dev
=> Consume AAO config in client for local dev

src/common/store/cache/tracks/sagas.js, src/components/nav/desktop/CurrentlyPlaying.module.css, src/components/nav/desktop/CurrentlyPlaying.tsx, src/components/nav/desktop/NavColumn.js, src/pages/visualizer/VisualizerProvider.tsx, src/utils/visualizer/visualizer-1.js
Fixed some bugs
- Tested visualizer icon on firefox, now looks centered
- Tested image sizes for dominant colors being the same using this track from two different locations
- https://milind.audius.co/trending?timeRange=month
- https://milind.audius.co/dontlisten/heliosky-hold
- Tested out changes to prevent going to track page on visualizer click
=> Ms visualizer bug fixes

package-lock.json, package.json
=> Update react-router-dom types

src/common/store/ui/modals/slice.ts, src/components/collectibles/components/CollectiblesPage.tsx
Add `MobileEditCollectiblesDrawer` to modals state slice for mobile to open the drawer
Also block web drawer from rendering when on native mobile
=> Update modal slice for mobile edit collectibles drawer

src/pages/audio-rewards-page/AudioRewardsPage.module.css, src/pages/audio-rewards-page/AudioRewardsPage.tsx, src/pages/audio-rewards-page/Tiers.module.css, src/pages/audio-rewards-page/components/ExplainerTile.module.css
Move what is audio tile to bottom of rewards page
Locally against staging
=> [AUD-1305] Move what is audio tile to bottom of rewards page

.circleci/config.yml
Switch to npm ci instead of install in circle to get deterministic builds
=> Npm install => npm ci

src/components/notification/store/sagas.ts
The event name for visibility change has a typo. Discovered while copy-pasting the code to use for rewards polling.
N/A
N/A
N/A
=> Fix bug where notifs weren't being fetched on refocus

package-lock.json, package.json, src/components/alt-button/RepostButton.module.css, src/components/alt-button/RepostButton.tsx, src/components/data-entry/DropdownInput.js, src/components/data-entry/FormTile.js, src/components/image-selection/ImageSelectionButton.js, src/components/track/GiantTrackTile.js, src/components/track/GiantTrackTile.module.css, src/components/track/desktop/TrackTile.tsx, src/components/upload/Dropzone.js, src/components/upload/Dropzone.module.css, src/components/upload/ProgressBar.js, src/pages/upload-page/components/FinishPage.js, src/pages/upload-page/components/FinishPage.module.css
Adds various fixes needed for e2e selectors to correctly query and interact with audius-client.
=> [AUD-1363] Add a11y fixes for e2e flows

src/pages/audio-rewards-page/ChallengeRewardsTile.tsx, src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
Accounts for disbursed state in showing challenge completeness.
Tested with staging account that has completed challenges
=> [AUD-1385] Fix challenge complete state

src/pages/audio-rewards-page/components/modals/ChallengeRewards.module.css, src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
Fix ui jumping
Fixes AUD-1367
Ran locally against staging
=> Fix ui jumping on copy referral

src/app.tsx, src/pages/App.d.ts
Adds type definition file for App.js to ensure consumers pass it the correct props
=> Add type defs for App

src/common/store/errors/actions.ts, src/common/store/errors/sagas.ts, src/common/store/index.ts, src/common/store/ui/toast/sagas.ts, src/common/store/ui/toast/slice.ts, src/components/toast/ToastContext.tsx, src/store/sagas.js
- Makes it possible for redux actions to add toasts, which helps with providing relevant error messages
- Adjusts the handleError action to accept `shouldToast` option to show a toast on an error
=> [AUD-1402] Move toast logic to redux

src/pages/audio-rewards-page/store/sagas.ts
- Separates the body of the generator of the `takeEvery` in `watchFetchUserChallenges` to its own function
- Separates the logic of checking for disbursements to its own function, `checkForNewDisbursements`, triggered on successful fetch of user challenges
- Middleware runs before reducers, so the state should still have the stale user challenges in the store during the separate `checkForNewDisbursements` saga
Have test coverage with the saga tests
=> Refactor Rewards Sagas

package-lock.json, package.json
Includes https://github.com/AudiusProject/audius-protocol/pull/2403
=> Consume Libs 1.2.61

src/common/store/pages/audio-rewards/slice.ts, src/pages/audio-rewards-page/store/sagas.ts, src/pages/audio-rewards-page/store/store.test.ts, src/store/social/tracks/sagas.ts
Optimistically update the listen streak challenges in the client
Closes AUD-1379
=> Optimistically update ui for listen streak challenge

src/common/models/Analytics.ts, src/common/store/errors/sagas.ts, src/pages/something-wrong/SomethingWrong.tsx
Add additional error context to track in amplitude
Ensure demo site doesn't crash
On amplitude Error charts
=> [AUD-1436] Add additional error context to amplitude

LICENSE, src/utils/route.ts
Fixes broken discord link & updates LICENSE copyright
Clicked the link
=> Update broken discord link

src/common/models/AudioRewards.ts, src/pages/audio-rewards-page/ChallengeRewardsTile.tsx, src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx, src/pages/audio-rewards-page/config.tsx
=> Support new verified referrals challenge in client

src/common/store/cache/tracks/utils/reformat.ts, src/components/track/desktop/TrackTile.tsx
1. Missing fields when hidden track => public
2. Tooltip on hidden track on profile 
=> Fix two field visibility bugs

src/services/audius-backend/waudio.ts
Track event in the wrong spot
ran against staging
=> Fix tracking create user bank

src/components/notification/components/desktop/NotificationBlock.tsx, src/components/notification/components/mobile/Notification.tsx
Go to rewards page on rewards notification click
Locally against staging
=> [AUD-1468] Go to rewards page on rewards notification click

package-lock.json, package.json, src/services/AudiusBackend.js
- Pipe feePayerOverride into the single attestation path
=> Fix fee payer

package-lock.json, package.json, src/common/models/Analytics.ts, src/services/AudiusBackend.js, src/services/audius-backend/Rewards.ts
**Needs latest libs**
- Adds sentry, amplitude, identity reporting
=> Add reward analytics

packages/mobile/src/components/collectible-details-drawer/CollectibleDetailsDrawer.tsx
Fixes whitespace clipping at the bottom of the CollectibleDetailsDrawer
Before: 
After:
=> [AUD-1342] Fix whitespace clipping at bottom of CollectibleDetailsDrawer

packages/web/src/pages/sign-on/store/sagas.js
=> Hotfix challenge

package-lock.json, package.json, src/common/models/Analytics.ts, src/pages/audio-rewards-page/store/sagas.ts, src/pages/audio-rewards-page/store/store.test.ts, src/services/AudiusBackend.js, src/services/audius-backend/Rewards.ts
Report claim reward retry if not on final attempt
Update unit tests
=> Report claim reward retry if not on final attempt

packages/mobile/package-lock.json, packages/web/package-lock.json, packages/web/package.json, packages/web/src/common/models/Analytics.ts, packages/web/src/pages/audio-rewards-page/store/sagas.ts, packages/web/src/pages/audio-rewards-page/store/store.test.ts, packages/web/src/services/AudiusBackend.js, packages/web/src/services/audius-backend/Rewards.ts
https://github.com/AudiusProject/audius-client/commit/9b0f7f8e04943f582922c2421d6ecc19d3ca73c0
=> Track retry for rewards analytics if not final attempt

packages/web/package-lock.json, packages/web/package.json, packages/web/src/common/store/pages/audio-rewards/slice.ts
Set listen streak challenges steps when complete
See TODO
=> Set listen streak challenges steps when complete

packages/web/src/store/wallet/sagas.ts
=> [AUD-1542] Fix send spl audio

.circleci/src/jobs/@web-jobs.yml
=> Fix @web-jobs sentry push

packages/mobile/src/App.tsx, packages/mobile/src/Drawers.tsx, packages/mobile/src/components/api-rewards-drawer/ApiRewardsDrawer.tsx, packages/mobile/src/components/api-rewards-drawer/index.ts, packages/mobile/src/components/audio-rewards/index.ts, packages/mobile/src/components/challenge-rewards-drawer/index.ts, packages/mobile/src/components/collectible-details-drawer/CollectibleDetailsDrawer.tsx, packages/mobile/src/components/collectible-details-drawer/index.ts, packages/mobile/src/components/connect-wallets-drawer/ConnectWalletsDrawer.tsx, packages/mobile/src/components/connect-wallets-drawer/index.ts, packages/mobile/src/components/deactivate-account-confirmation-drawer/index.ts, packages/mobile/src/components/download-track-progress-drawer/DownloadTrackProgressDrawer.tsx, packages/mobile/src/components/download-track-progress-drawer/index.ts, packages/mobile/src/components/forgot-password-drawer/ForgotPasswordDrawer.tsx, packages/mobile/src/components/forgot-password-drawer/index.ts, packages/mobile/src/components/mobile-upload-drawer/MobileUploadDrawer.tsx, packages/mobile/src/components/mobile-upload-drawer/index.ts, packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx, packages/mobile/src/components/overflow-menu-drawer/index.ts, packages/mobile/src/components/share-to-tiktok-drawer/ShareToTikTokDrawer.tsx, packages/mobile/src/components/share-to-tiktok-drawer/index.ts, packages/mobile/src/components/transfer-audio-mobile-drawer/TransferAudioMobileDrawer.tsx, packages/mobile/src/components/transfer-audio-mobile-drawer/index.ts, packages/mobile/src/components/trending-rewards-drawer/TrendingRewardsDrawer.tsx, packages/mobile/src/components/trending-rewards-drawer/index.ts, packages/mobile/src/screens/trending-screen/index.ts
Moves drawers to separate file
Standardizes imports using named-imports
=> Move drawers to separate file, standardize imports

packages/web/src/common/store/pages/token-dashboard/slice.ts, packages/web/src/services/wallet-client/WalletClient.ts, packages/web/src/store/wallet/sagas.ts
=> Prevent wormhole from sending 0 audio

packages/web/package-lock.json, packages/web/package.json
Make sure modals and buttons don't break or change unexpectedly. Everything should look the same
=> Bump stems to 0.3.22 (for Modal sub components and button update)

packages/web/src/components/artist/ArtistCard.js
fixes look of stats on artist card
=> Add size prop to ArtistCard Stats

packages/web/package-lock.json, packages/web/package.json
=> Upgrade libs to 1.2.81

packages/web/package-lock.json, packages/web/package.json
Release notes: https://github.com/AudiusProject/stems/pull/101
=> Bump Stems to 0.3.23 for small icons and ModalTitle fix

packages/web/src/pages/audio-rewards-page/store/sagas.ts, packages/web/src/pages/audio-rewards-page/store/store.test.ts
Allow for cognito retry if passed captcha and score too low
=> Allow cognito retry

packages/mobile/src/components/app-navigator/BaseStackNavigator.tsx, packages/mobile/src/components/track-tile/TrackTile.tsx, packages/mobile/src/components/track-tile/TrackTileStats.tsx, packages/mobile/src/components/user-badges/UserBadges.tsx, packages/mobile/src/components/user-badges/index.ts, packages/mobile/src/hooks/useNavigation.ts, packages/mobile/src/screens/user-list-screen/FavoritedScreen.tsx, packages/mobile/src/screens/user-list-screen/FavoritesList.tsx, packages/mobile/src/screens/user-list-screen/FollowingList.tsx, packages/mobile/src/screens/user-list-screen/RepostsScreen.tsx, packages/mobile/src/screens/user-list-screen/UserChip.tsx, packages/mobile/src/screens/user-list-screen/index.ts
- Adds favorited screen and connects TrackTile favorite icon
- Replaces handle with UserBadges in UserList
https://user-images.githubusercontent.com/8230000/154747711-fd3cee46-3999-4455-bb33-1ca42e07c44b.mov
=> [AUD-1423] Add FavoritedScreen

packages/mobile/src/components/app-navigator/BaseStackNavigator.tsx, packages/mobile/src/components/track-tile/TrackTile.tsx, packages/mobile/src/components/track-tile/TrackTileStats.tsx, packages/mobile/src/hooks/useNavigation.ts, packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx, packages/mobile/src/screens/user-list-screen/FollowingScreen.tsx, packages/mobile/src/screens/user-list-screen/RepostsScreen.tsx, packages/mobile/src/screens/user-list-screen/index.ts
Adds RepostsScreen and FollowingScreen
https://user-images.githubusercontent.com/8230000/154750486-f00896c8-403f-43f0-9ef4-00312b1f081a.mov
=> [AUD-1424] Add RepostsScreen, FollowingScreen

packages/web/package-lock.json, packages/web/package.json, packages/web/src/services/wallet-client/WalletClient.ts
=> Fixes bugs in AUD-1581

packages/web/src/components/social-proof/SocialProof.tsx, packages/web/src/components/twitter-auth/TwitterAuth.js
Close modal and handle error for twitter more gracefully
=> Fix social proof bugs

packages/web/src/pages/audio-rewards-page/WalletModal.tsx
Reopen modal and confirm send instead of just reopening the modal.
=> Fix onconfirm send bug

packages/web/src/components/social-proof/SocialProof.tsx
=> Update copy in SocialProof

packages/web/src/common/models/User.ts, packages/web/src/components/nav/desktop/NavAudio.tsx
This reverts commit cfae04dfaff9e8f46aeb911d9c73a5e22e4621b3.
Need https://github.com/AudiusProject/audius-protocol/commit/2f0a72cfbe4d27ab473a113102a6a565e61bfe00 to land on all discovery nodes
=> Revert "Optimize happy path $AUDIO nav balance (#914)"

packages/web/src/services/Location.ts
To better see why we get null locations
logs and sentry
=> Debug error from getLocation call

packages/web/src/components/instagram-auth/InstagramAuth.tsx, packages/web/src/components/instagram-button/InstagramButton.tsx, packages/web/src/components/social-proof/SocialProof.tsx, packages/web/src/pages/settings-page/components/InstagramAccountVerified.tsx
Do not require social metadata for insta social proof. Comments explain why.
Will test thoroughly on stage where oauth is easier
=> Do not require social meta for insta in proof

packages/web/src/common/models/Analytics.ts, packages/web/src/components/social-proof/SocialProof.tsx
Fixes analytics for social proof
=> Fix analytics

packages/mobile/src/components/lineup/Delineator.tsx, packages/mobile/src/components/lineup/Lineup.tsx, packages/mobile/src/components/lineup/delineate.ts, packages/mobile/src/screens/profile-screen/TracksTab.tsx
- Configures "artist-pick" tile for profile track list
- Updates lineup's delineation logic to handle cases where we want delineation with no title
=> [AUD-1571] Add ArtistPick to Profile TrackList

packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
=> Adds Follows You indicator to react native profile header

packages/web/src/components/artist/ArtistCard.module.css
https://linear.app/audius/issue/AUD-1599/wrapping-is-funky-with-long-handles
=> Style fixes for artist popover width

packages/mobile/src/components/animated-button/AnimatedButtonProvider.tsx, packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
Connects play bar & now playing drawer play button correctly
Video evidence (you can't tell where I tapped, but the first time was the track tile and the second was the play bar)
https://user-images.githubusercontent.com/2731362/153985445-4ecd3c0d-d86a-4b37-93bc-72297db49f83.mp4
=> [AUD-1413] Allow for controlled AnimatedButtonProvider

packages/mobile/src/App.tsx, packages/mobile/src/components/app-navigator/navigationThemes.ts, packages/mobile/src/components/core/CardList.tsx, packages/mobile/src/components/core/EmptyCard.tsx, packages/mobile/src/components/navigation-container/NavigationContainer.tsx, packages/mobile/src/components/user/FollowButton.tsx, packages/mobile/src/components/user/ProfilePicture.tsx, packages/mobile/src/screens/profile-screen/EditProfileButton.tsx, packages/mobile/src/screens/profile-screen/ExpandableBio.tsx, packages/mobile/src/screens/profile-screen/ProfileInfo.tsx, packages/mobile/src/screens/profile-screen/ProfileScreen.tsx, packages/mobile/src/screens/profile-screen/ProfileSocials.tsx, packages/mobile/src/screens/profile-screen/RepostsTab.tsx, packages/mobile/src/utils/theme.ts
Fixes various styles in profilescreen to be up to spec
- Adds react-navigation theme to properly style the tab-navigator background-color
- Fixes placement of subscribe/follow buttons
- properly hides social links
- Fixes expandabe bio issue where "show more" button was always showing
=> [AUD-1526] Improve ProfileScreen styles

packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx, packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx, packages/mobile/src/components/now-playing-drawer/AudioControls.tsx, packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx, packages/mobile/src/components/now-playing-drawer/PlayBar.tsx, packages/web/src/common/store/cast/sagas.ts, packages/web/src/common/store/cast/selectors.ts, packages/web/src/common/store/cast/slice.ts, packages/web/src/common/store/index.ts, packages/web/src/components/now-playing/NowPlaying.tsx, packages/web/src/components/now-playing/components/ActionsBar.tsx, packages/web/src/pages/settings-page/SettingsPageProvider.tsx, packages/web/src/pages/settings-page/components/mobile/SettingsPage.tsx, packages/web/src/pages/settings-page/store/actions.ts, packages/web/src/pages/settings-page/store/reducer.ts, packages/web/src/pages/settings-page/store/sagas.ts, packages/web/src/pages/settings-page/store/selectors.ts, packages/web/src/pages/settings-page/store/types.ts
* Const existing action bar
* Move cast logic to common store to connect cast button
Simulator
https://user-images.githubusercontent.com/2731362/155643003-015b311a-4daa-489c-b5bd-54a8f0f6fab8.mp4
Mobile release / sentry mobile crashes, etc.
=> Connect now playing action bar

packages/web/src/pages/audio-rewards-page/store/sagas.ts, packages/web/src/pages/audio-rewards-page/store/store.test.ts, packages/web/src/services/audius-backend/Cognito.ts
So that identity has a chance to receive and store flow webhook data
Make sure that current flow is not broken
Updated unit tests and also test manually
No monitoring
=> Poll identity for cognito existence

packages/web/package-lock.json, packages/web/package.json
- Allows for more granular error reporting for rewards
- Reworks attesting flow in libs
n/a
Tested locally
=> Consume libs 1.2.87

packages/mobile/src/components/app-navigator/AppNavigator.tsx, packages/mobile/src/components/app-navigator/BaseStackNavigator.tsx, packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx, packages/mobile/src/components/app-navigator/TopBar.tsx, packages/mobile/src/components/app-navigator/types.ts, packages/mobile/src/components/lineup-tile/CollectionTile.tsx, packages/mobile/src/components/lineup-tile/LineupTileMetadata.tsx, packages/mobile/src/components/lineup-tile/TrackTile.tsx, packages/mobile/src/components/navigation-container/NavigationContainer.tsx, packages/mobile/src/screens/explore-screen/ExploreScreen.tsx, packages/mobile/src/screens/explore-screen/components/ArtistCard.tsx, packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx, packages/mobile/src/screens/feed-screen/FeedScreen.tsx, packages/mobile/src/screens/profile-screen/EditProfileButton.tsx, packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx, packages/mobile/src/screens/profile-screen/ProfileTabNavigator.tsx, packages/mobile/src/screens/search-screen/content/SearchItem.tsx, packages/mobile/src/screens/search-screen/content/SeeMoreResultsButton.tsx, packages/mobile/src/screens/track-screen/TrackScreen.tsx, packages/mobile/src/screens/track-screen/TrackScreenHeader.tsx, packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx, packages/mobile/src/screens/trending-screen/TrendingScreen.tsx, packages/mobile/src/screens/user-list-screen/UserChip.tsx
Improves a variety of app navigation issues
- unmounts stacks on blur (resetting stacks) to follow existing app behavior
- moves search components into each main stack (this plus resetting stacks essentially fixes our search navigation issues)
- changes navigate to push where appropriate
- renames lowercase screens to PascalCase (follows the react-navigation standard)
- uses Screen component for each root stack element (cleans up a lot of code)
=> [AUD-1631] Improve app navigation

packages/web/package-lock.json, packages/web/package.json
Changelog: https://github.com/AudiusProject/stems/pull/104
=> Bump Stems to 0.3.24

packages/web/package-lock.json, packages/web/package.json
Bump libs version to 1.2.88 for user schema update to enable playlist folders
=> Bump libs to 1.2.88

packages/mobile/src/Drawers.tsx, packages/mobile/src/components/sign-out-confirmation-drawer/SignOutConfirmationDrawer.tsx, packages/mobile/src/components/sign-out-confirmation-drawer/index.ts, packages/mobile/src/screens/settings-screen/AccountSettingsItem.tsx, packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx, packages/web/src/common/store/index.ts, packages/web/src/common/store/sign-out/sagas.ts, packages/web/src/common/store/sign-out/slice.ts, packages/web/src/common/store/ui/modals/slice.ts, packages/web/src/store/sagas.ts
* Add SignOutConfirmationDrawer
* Add saga for signing user out
[AUD-1097]
N/A
Manual Testing
N/a
=> [AUD-1097] Add SignOutConfirmationDrawer

packages/web/package-lock.json, packages/web/package.json, packages/web/src/common/models/Analytics.ts, packages/web/src/common/store/errors/actions.ts, packages/web/src/common/store/errors/sagas.ts, packages/web/src/pages/sign-on/store/actions.js, packages/web/src/pages/sign-on/store/errorSagas.js, packages/web/src/pages/sign-on/store/sagas.js
Redirect to signup and show try again toast if auth rate limit error.
Make sure handle error logic that reports/redirects/etc. isn't broken for other paths.
Manual client test
Is it worth reporting to Sentry but not paging or tweaking the alert trigger somehow?
Or reporting a diff erro type to sentry that does not page? @raymondjacobson
=> Redirect to signup if auth rate limit error

packages/mobile/src/components/app-navigator/AppNavigator.tsx
Fixes bug where header was shown on sign on
Hiding headers at top level AppNavigator
ios simulator
Apparently app store review will catch it
=> [AUD-1652] Don't show header on SignOn

packages/mobile/src/Drawers.tsx, packages/mobile/src/assets/images/iconInfo.svg, packages/mobile/src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx, packages/mobile/src/components/audio-breakdown-drawer/index.ts, packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawer.tsx, packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx, packages/mobile/src/components/progress-bar/ProgressBar.tsx, packages/mobile/src/components/progress-bar/index.ts, packages/mobile/src/screens/audio-screen/AudioScreen.tsx, packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx, packages/mobile/src/screens/audio-screen/Panel.tsx, packages/mobile/src/screens/audio-screen/TrendingRewards.tsx, packages/mobile/src/utils/challenges.tsx, packages/mobile/src/utils/theme.ts, packages/web/src/common/utils/fillString.ts, packages/web/src/pages/audio-rewards-page/AudioRewardsPage.tsx, packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
Finishes /audio page on mobile. This is unf a big PR because there was a lot to wire up.
Notably I did not also solve for the fact that we have two JSON objects (one in mobile and one in web that represent challenges. I felt that was asking for too much in this PR). Things are somewhat more consolidated here though, so we can continue to refactor.
It's all new basically, but touched a few web audio page things to refactor.
https://user-images.githubusercontent.com/2731362/156687250-cae5eeb2-2b01-4e91-9d60-2d832c0a2317.mp4
*For features that are critical or could fail silently please …
=> [AUD-972] Finish $AUDIO mobile page

packages/mobile/src/components/app-navigator/baseStackScreenOptions.tsx
- Fixes tab navigation inside a stack navigation by resetting to the default gesture distance. The tradeoff is that the user can't navigate back from anywhere on the page.
- Improves goBack animation by not detaching the previous screen.
=> [AUD-1622] Fix stacked profile-tab nav, improve goBack animation

packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx, packages/mobile/src/components/scrubber/Slider.tsx, packages/mobile/src/components/top-tab-bar/TopTabBar.tsx, packages/mobile/src/screens/profile-screen/ProfileInfo.tsx, packages/mobile/src/screens/profile-screen/Sites.tsx, packages/mobile/src/screens/profile-screen/UploadTrackButton.tsx, packages/mobile/src/styles/typography.ts
Cleans up misc styles
Locally with simulator
Staging mobile release
=> Clean up misc styles

packages/mobile/src/components/lineup/Lineup.tsx, packages/mobile/src/hooks/selectors.ts, packages/mobile/src/hooks/useRoute.ts, packages/mobile/src/screens/collection-screen/CollectionScreen.tsx, packages/mobile/src/screens/profile-screen/ProfileScreen.tsx, packages/mobile/src/screens/track-screen/TrackScreen.tsx, packages/web/src/common/store/pages/collection/selectors.ts, packages/web/src/common/store/pages/profile/selectors.ts, packages/web/src/common/store/pages/track/selectors.ts
Drastically improves track, collection, and profile screen load time by using ids from navigation context instead of waiting for ids from redux
=> [AUD-1661] Improve ProfileScreen load time

packages/web/src/common/models/User.ts, packages/web/src/components/nav/desktop/NavAudio.tsx, packages/web/src/store/wallet/sagas.ts
Replays https://github.com/AudiusProject/audius-client/pull/914 given that the discovery node change has been released everywhere.
=> Remove nav audio flag

packages/mobile/src/components/app-navigator/BaseStackNavigator.tsx, packages/mobile/src/components/app-navigator/types.ts, packages/mobile/src/components/lineup-tile/LineupTileStats.tsx, packages/mobile/src/components/user/FollowButton.tsx, packages/mobile/src/hooks/useRoute.ts, packages/mobile/src/screens/collection-screen/CollectionScreen.tsx, packages/mobile/src/screens/profile-screen/ProfileInfo.tsx, packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx, packages/mobile/src/screens/user-list-screen/FavoritedScreen.tsx, packages/mobile/src/screens/user-list-screen/FavoritesList.tsx, packages/mobile/src/screens/user-list-screen/FollowersScreen.tsx, packages/mobile/src/screens/user-list-screen/FollowingList.tsx, packages/mobile/src/screens/user-list-screen/FollowingScreen.tsx, packages/mobile/src/screens/user-list-screen/RepostsScreen.tsx, packages/mobile/src/screens/user-list-screen/UserChip.tsx, packages/mobile/src/screens/user-list-screen/UserList.tsx
- Improves user-list performance by reducing rerenders and caching user-lists between reloads
- Fixes follow-button follow source
- Removes unused components
Also addresses [AUD-1662]
Before:
https://user-images.githubusercontent.com/8230000/157311532-abf794b3-1cb7-4d47-9548-11f09958276c.mov
After: 
https://user-images.githubusercontent.com/8230000/157312213-3a98f960-b3ba-4f6e-a6b6-9fb694038f69.mov
=> [AUD-1667] Improve user-list performance

packages/mobile/src/components/core/VirtualizedScrollView.tsx, packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Adds pull to refresh to profile screen
We are getting the same error that exists on current app, which is a pull-to-refresh results in empty profile picture and cover art:
https://user-images.githubusercontent.com/8230000/157353282-2c642ab6-81d0-4065-801e-74fc662aa9c4.mov
=> [AUD-1681] Add profile-screen pull-to-refresh

packages/mobile/src/components/artist-card/ArtistCard.tsx, packages/mobile/src/components/artist-card/index.ts, packages/mobile/src/components/collection-card/CollectionCard.tsx, packages/mobile/src/components/collection-card/index.ts, packages/mobile/src/components/collection-list/CollectionList.tsx, packages/mobile/src/screens/explore-screen/tabs/ArtistsTab.tsx, packages/mobile/src/screens/explore-screen/tabs/PlaylistsTab.tsx, packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx, packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx, packages/mobile/src/screens/profile-screen/AlbumsTab.tsx, packages/mobile/src/screens/profile-screen/PlaylistsTab.tsx, packages/mobile/src/screens/search-results-screen/tabs/AlbumsTab.tsx, packages/mobile/src/screens/search-results-screen/tabs/PlaylistsTab.tsx, packages/mobile/src/screens/search-results-screen/tabs/ProfilesTab.tsx, packages/mobile/src/screens/search-screen/content/SearchItem.tsx
Support search deep linking properly for profiles & collections
Locally w/ simulator against staging
Staging rollout
=> [AUD-1682] Support search deep linking properly

packages/mobile/src/components/app-navigator/baseStackScreenOptions.tsx
Removes topbar title flash for all pages.
=> [AUD-1680] Remove topbar title flash

packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx, packages/mobile/src/components/app-navigator/types.ts, packages/mobile/src/components/details-tile/DetailsTile.tsx, packages/mobile/src/components/track-list/TrackListItem.tsx, packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx, packages/mobile/src/screens/explore-screen/collections.ts, packages/mobile/src/screens/explore-screen/components/ColorTile.tsx, packages/mobile/src/screens/explore-screen/smartCollections.ts, packages/mobile/src/screens/explore-screen/tabs/MoodsTab.tsx, packages/mobile/src/screens/smart-collection-screen/SmartCollectionScreen.tsx
* Updated some types and did some plumbing for the mood screens, collections screens, and smart collection screens
* Added smart collection screen to the BottomTabNavigator
[AUD-1552]
[AUD-1555]
[AUD-1556]
[AUD-1557]
N/A
Manually tested, all of the smart collection screens work and render tracks properly
N/A
=> [AUD-1552, AUD-1555, AUD-1556, AUD-1557] Add smart collection screens

packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx, packages/mobile/src/components/app-navigator/types.ts, packages/mobile/src/components/with-loader/WithLoader.tsx, packages/mobile/src/screens/explore-screen/collections.ts, packages/mobile/src/screens/favorites-screen/TracksTab.tsx, packages/mobile/src/screens/mood-collection-screen/MoodCollectionScreen.tsx, packages/mobile/src/screens/settings-screen/ListeningHistoryScreen.tsx
* Added MoodCollectionScreen
* Added mood screens to the BottomTabNavigator
[AUD-1558]
N/A
N/A
=> [AUD-1558] Add MoodCollectionScreen and add mood screens to BottomTabNavigator

packages/mobile/src/components/app-navigator/BottomTabNavigator.tsx, packages/mobile/src/screens/explore-screen/tabs/ForYouTab/LetThemDJScreen.tsx, packages/mobile/src/screens/explore-screen/tabs/ForYouTab/TopAlbumsScreen.tsx, packages/mobile/src/screens/explore-screen/tabs/ForYouTab/index.ts
* Add LetThemDJScreen
* Add TopAlbumsScreen
[AUD-1551] [AUD-1554]
N/A
N/A
=> [AUD-1551, AUD-1554] Add LetThemDJ and TopAlbums screens for explore screen

packages/mobile/src/Drawers.tsx, packages/mobile/src/components/add-to-playlist-drawer/AddToPlaylistDrawer.tsx, packages/mobile/src/components/web/WebApp.tsx, packages/mobile/src/hooks/useScrollToTop.ts, packages/web/src/common/store/ui/add-to-playlist/actions.ts, packages/web/src/common/store/ui/add-to-playlist/reducer.ts, packages/web/src/common/store/ui/add-to-playlist/selectors.ts, packages/web/src/common/store/ui/modals/slice.ts, packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.tsx, packages/web/src/components/add-to-playlist/store/sagas.ts, packages/web/src/components/nav/mobile/TopLevelPage.tsx, packages/web/src/components/play-bar/PlayBarProvider.tsx
Delays render for AddToPlaylist and AudioBreakdown drawers
Also optimizes WebApp which rerendered a ton due to a boolean
=> [AUD-1685] Optimize AddToPlaylist and AudioBeakdown drawers

packages/mobile/src/components/core/SearchInput.tsx, packages/mobile/src/screens/search-screen/SearchBar.tsx
Clears search via icon when there is text
https://user-images.githubusercontent.com/2731362/157912732-427a1c5e-aa36-4d7e-aad3-b52db78dc929.mp4
Simulator
Staging bounce app
=> [AUD-1694] Add clear search icon

packages/web/src/common/services/remote-config/feature-flags.ts, packages/web/src/pages/explore-page/components/desktop/ExplorePage.tsx, packages/web/src/pages/explore-page/components/desktop/Section.module.css, packages/web/src/pages/explore-page/components/desktop/Section.tsx, packages/web/src/pages/explore-page/components/mobile/ExplorePage.module.css, packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
* Remove REMIXABLES and REMIXABLES_WEB flags
* Remove styles that will no longer appear
* 
[AUD-1703]
N/A
N/A
=> [AUD-1703] Remove Remixables feature flag

packages/web/src/common/services/remote-config/feature-flags.ts, packages/web/src/components/collectibles/components/CollectibleDetailsModal.tsx, packages/web/src/components/image-selection/ImageSelectionPopup.js
* Remove NFT image picker feature flag
[AUD-1704]
N/A
Manual testing
N/A
=> [AUD-1704] Remove NFT image picker feature flag

packages/mobile/src/components/app-navigator/BaseStackNavigator.tsx, packages/mobile/src/components/app-navigator/types.ts, packages/mobile/src/hooks/useRoute.ts, packages/mobile/src/screens/search-results-screen/TagSearchScreen.tsx, packages/mobile/src/screens/search-results-screen/index.ts, packages/mobile/src/screens/search-screen/SearchBar.tsx, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
There's some really weird stuff going on with tag search that makes this PR not 100%, but wanted to keep it smaller before diving too deep down that rabbit hole. This at least gets us
Search for tag => tag search page
Track page tag => tag search page
We also need more UI to support showing the tag b/c native mobile doesn't show the tag up top in the search bar.
https://user-images.githubusercontent.com/2731362/157999467-497e7c03-2f18-4fc7-8054-265e00ca0316.mp4
https://user-images.githubusercontent.com/2731362/157999471-efb59807-3222-4e7a-a2cd-a4082ade0b95.mp4
Locally with simulator …
=> [AUD-1545] Implement and wire up tag search

packages/web/src/store/playlist-library/helpers.test.js, packages/web/src/store/playlist-library/helpers.ts, packages/web/src/store/playlist-library/sagas.ts
Update the temp playlist resolver saga to also resolve temp playlists that are in folders
Unit tests for helpers + tested in browser by creating playlists and moving them around and seeing if they resolved properly
=> Resolve temp playlists within folders

packages/web/src/components/dragndrop/Droppable.js, packages/web/src/components/nav/desktop/NavColumn.module.css, packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx, packages/web/src/components/nav/desktop/PlaylistLibrary.tsx, packages/web/src/components/nav/desktop/PlaylistNavItem.tsx, packages/web/src/store/playlist-library/helpers.test.js, packages/web/src/store/playlist-library/helpers.ts
See title!
Make sure this does not break any existing functionality outside the folders feature flag
Unit tests and tested UI in browser
Amplitude events and improved error handling to come in future PRs
=> Enable reordering playlists and folders

packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx, packages/web/src/components/nav/desktop/PlaylistLibrary.tsx, packages/web/src/components/nav/desktop/PlaylistNavItem.tsx, packages/web/src/store/playlist-library/helpers.test.js, packages/web/src/store/playlist-library/helpers.ts
Same as https://github.com/AudiusProject/audius-client/pull/1053 I just merged into the wrong target branch (usually Github automatically updates the target to main after the original target is merged???)
=> Reorder folders and playlists - correct base branch lol

packages/web/src/services/AudiusBackend.js, packages/web/src/services/audius-backend/RecordIP.ts, packages/web/src/store/account/sagas.js
Record IP if not recent
None
Manually
Elsewhere on identity
=> Record IP if not recent

packages/web/src/common/services/remote-config/feature-flags.ts, packages/web/src/components/collectibles/components/CollectiblesPage.tsx, packages/web/src/components/image-selection/ImageSelectionPopup.js, packages/web/src/pages/profile-page/sagas.js
Remove sol collectibles feature flag
None
Locally against prod
N/A
=> Remove sol collectibles feature flag

packages/web/src/common/models/Analytics.ts, packages/web/src/components/create-playlist/CreatePlaylistModal.tsx, packages/web/src/components/edit-folder-modal/EditFolderModal.tsx, packages/web/src/components/nav/desktop/NavColumn.js, packages/web/src/components/nav/desktop/PlaylistFolderNavItem.tsx, packages/web/src/components/nav/desktop/PlaylistLibrary.tsx, packages/web/src/store/playlist-library/helpers.ts
See title!
In browser - perform folder related operations and make sure they result in appropriate event firing
=> Add Amplitude events for playlist folders feature

packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx, packages/web/src/common/store/index.ts, packages/web/src/common/store/recovery-email/sagas.ts, packages/web/src/common/store/recovery-email/slice.ts, packages/web/src/store/sagas.ts
* Add saga to request recovery email send
* dispatch action on button press
N/A
N/A
=> Add resend recovery email saga and functionality

packages/web/src/components/add-to-playlist/desktop/AddToPlaylistModal.tsx
Modal was using frankenstein state instead of the new modal state usage
Need probers test & amplitude metrics probably for this flow.
=> Fix playlist modal

packages/web/package-lock.json, packages/web/package.json
Bump Stems to get new Scrollbar component.
=> Bump Stems to 0.3.25

packages/web/package-lock.json, packages/web/package.json
Changelog [here](https://github.com/AudiusProject/stems/pull/111) (just the ResizeObserver polyfill!)
=> Bump Stems to 0.3.26

packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx, packages/mobile/src/components/bottom-tab-bar/BottomTabBarButton.tsx, packages/mobile/src/components/bottom-tab-bar/constants.ts, packages/mobile/src/components/bottom-tab-bar/index.ts, packages/mobile/src/components/lineup/Lineup.tsx, packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx, packages/mobile/src/components/now-playing-drawer/constants.ts, packages/mobile/src/components/now-playing-drawer/index.tsx, packages/mobile/src/screens/app-screen/AppTabBar.tsx, packages/mobile/src/screens/explore-screen/tabs/ForYouTab/ForYouTab.tsx, packages/mobile/src/screens/explore-screen/tabs/MoodsTab.tsx
Establishes bottom spacing for bottom-bar, and fixes case where now-playing-bar clips content
https://user-images.githubusercontent.com/8230000/159572283-1cf5f892-2673-4d82-8d18-633664597667.mov
=> [AUD-1759] Improve bottom spacing and content clipping

packages/mobile/src/components/status-message/StatusMessage.tsx, packages/mobile/src/screens/settings-screen/AccountVerificationScreen.tsx
Add AccountVerificationScreen for mobile
N/A
Manually tested (Except for the success flow, which will be tested on staging)
N/A
=> Add account verification screen

packages/mobile/src/screens/app-screen/ExploreTabScreen.tsx, packages/mobile/src/screens/explore-screen/components/ColorTile.tsx, packages/mobile/src/screens/explore-screen/tabs/ForYouTab/ForYouTab.tsx
[AUD-1749]
* Small update to fix the layout to match the original design
N/A
Manually tested, looks good
N/A
=> [AUD-1749] Update explore screen layout to match design

packages/mobile/ios/AudiusReactNative/Info.plist
Hopefully this uploads to testflight
=> Bump ios version to 1.1.11

packages/web/src/index.css
=> Fix Simplebar scroll

packages/mobile/src/components/top-tab-bar/TopTabBar.tsx
* Adds horizontal padding to tabs to match figma https://www.figma.com/file/qGwU0Nd3yrchciX8R3fjRW/Mobile-Tab-Bar?node-id=2%3A58
* Padding decreases as number of tabs increases. at 2 tabs it's 32px, and 5 tabs it's 8px
Touches the tab indicator width, need to keep and eye on the tabs to see if we catch anything funky
iOS sim
TestFlight QA
=> [AUD-1637] Add horizontal padding to tabs

packages/mobile/src/components/core/AnimatedButton.tsx, packages/mobile/src/components/now-playing-drawer/AudioControls.tsx, packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx, packages/mobile/src/components/scrubber/Scrubber.tsx
* Fixes a bug where the timestamp changing width due to longer times would shift the scrubber and break dragging
Verified that scrubber & timestamp styling works with times up to 59:59:59
https://user-images.githubusercontent.com/19916043/159995555-14532b14-ce94-48a4-992d-1154c290d51b.mov
* Adds now playing play button scale animation AUD-1767
N/A
iOS sim
TestFlight QA
=> [AUD-1783] Fix scrubber bug

packages/mobile/src/screens/profile-screen/Sites.tsx
* Profile links without https or http were not opening
Should we default to https or http? I chose https for now
iOS sim and device
TestFlight QA
=> [AUD-1782] Fix profile links

packages/mobile/src/components/web/WebApp.tsx
Use env var for URL intercept.
I frequently will run on device and replace URL_OVERRIDE with my local network IP so my phone can use the web code running on my computer.
I think I had erroneously checked in the ".*" piece in a prior PR, which is bad!
On device
=> Be smarter about URL intercept

packages/mobile/src/screens/search-results-screen/EmptyResults.tsx
Updates search results styles to match web values:
Web: 
Before:
After:
=> [AUD-1772] Fix empty search results styles

packages/mobile/src/components/web/WebApp.tsx, packages/mobile/src/screens/settings-screen/CastSettingsRow.tsx, packages/mobile/src/screens/settings-screen/SettingsScreen.tsx, packages/web/src/pages/settings-page/components/mobile/SettingsPage.tsx
Add UI for cast settings to settings screen
https://user-images.githubusercontent.com/2731362/160024431-dc92c433-0ecb-4890-8181-bb4eb1e3f38b.MP4
Physical device
=> [AUD-1789] Add cast settings UI

packages/mobile/src/components/now-playing-drawer/TrackInfo.tsx
Fixes case where we truncate the artist name way to early on the now-playing drawer
- Also updates text and style usage to use latest patterns.
=> [AUD-1790] Fix now-playing artist text truncate

packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx, packages/mobile/src/components/drawer/Drawer.tsx, packages/mobile/src/components/drawer/constants.ts, packages/mobile/src/components/drawer/index.ts, packages/mobile/src/components/now-playing-drawer/Logo.tsx, packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx, packages/mobile/src/components/now-playing-drawer/PlayBar.tsx, packages/mobile/src/components/now-playing-drawer/TrackingBar.tsx, packages/mobile/src/components/now-playing-drawer/constants.ts, packages/mobile/src/screens/app-screen/AppTabBar.tsx
Improves now playing drawer performance by
* Removing a lot of state updates
* Sharing translation anim between drawer & bottom bar
* Adding bottom "padding" elsewhere, which in its currently implementation is kinda jank
=> [AUD-1778] Improve now playing drawer performance

.circleci/src/commands/@mobile-commands.yml, .circleci/src/commands/@web-commands.yml, .circleci/src/jobs/@web-jobs.yml
```
./node_modules/@audius/libs/dist/index.js
Critical dependency: the request of a dependency is an expression
```
https://app.circleci.com/pipelines/github/AudiusProject/audius-client/4580/workflows/484ee3c4-9bdb-4ec5-b830-bcd38be32774/jobs/32394
This should be reverted for a proper fix
=> Turn on CI mode to unblock builds

packages/mobile/src/components/details-tile/DetailsStat.tsx, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
* Fixes bug where play counts weren't display
* Fixes styling for larger play counts
N/A
iOS sim
TestFlight QA
=> [AUD-1793] Fix display of play counts on track screen

packages/web/src/common/services/remote-config/feature-flags.ts, packages/web/src/components/share-modal/ShareModal.tsx, packages/web/src/pages/upload-page/components/ShareBanner.tsx
* Removes TikTok feature flag
TikTok sharing is enabled now, so no easy way to disable it
Manually, locally against prod
TikTok dashboard in amplitude
=> [AUD-1712] Remove TikTok feature flag

packages/mobile/src/components/challenge-rewards-drawer/ReferralLinkCopyButton.tsx
* Adjusts gradient angle to visually match figma:
N/A
iOS Sim
N/A
=> [AUD-1480] Adjust referral button gradient

packages/web/package-lock.json, packages/web/package.json
Fixes wormhole build issue due by upgrading to web-compatible libs
=> [AUD-1796] Fix wormhole compilation issue

packages/mobile/src/components/details-tile/DetailsTile.tsx, packages/mobile/src/components/details-tile/types.ts, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
* Fixes issue where mood could overflow on track screen
Other pieces of data on track screen could be affected, but I did a pass and everything looked right
iOS sim
TestFlight QA
=> [AUD-1757] Mood Overflow

packages/web/src/common/services/remote-config/feature-flags.ts, packages/web/src/components/artist-recommendations/ArtistRecommendationsDropdown.tsx, packages/web/src/components/artist-recommendations/ArtistRecommendationsPopup.tsx
Clean up the Artist Recommendations feature flag
TBD
=> Remove Artist Recommendations Feature Flag

packages/mobile/src/components/core/FormTextInput.tsx, packages/mobile/src/components/core/Screen.tsx, packages/mobile/src/components/core/TextButton.tsx, packages/mobile/src/components/form-screen/FormScreen.tsx, packages/mobile/src/components/form-screen/index.ts, packages/mobile/src/hooks/useNavigation.ts, packages/mobile/src/screens/app-screen/AppTabScreen.tsx, packages/mobile/src/screens/app-screen/FavoritesTabScreen.tsx, packages/mobile/src/screens/edit-playlist-screen/CreatePlaylistScreen.tsx, packages/mobile/src/screens/edit-playlist-screen/EditPlaylistScreen.tsx, packages/mobile/src/screens/edit-playlist-screen/PlaylistDescriptionInput.tsx, packages/mobile/src/screens/edit-playlist-screen/PlaylistImageInput.tsx, packages/mobile/src/screens/edit-playlist-screen/PlaylistNameInput.tsx, packages/mobile/src/screens/edit-playlist-screen/RandomImageButton.tsx, packages/mobile/src/screens/edit-playlist-screen/index.ts, packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx, packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx, packages/web/src/common/store/cache/collections/actions.ts, packages/web/src/common/store/cache/collections/sagas.js
Adds CreatePlaylistScreen
- Refactors EditPlaylistScreen and reuses input components in CreatePlaylistScreen
- Adds disabled, icon and icon placement to TextButton
- Adds required/ validation for input-field
- Adds FormScreen and uses it for all our form screens
=> [AUD-1797] Add CreatePlaylistScreen

packages/mobile/src/components/core/AnimatedButton.tsx, packages/mobile/src/components/core/SegmentedControl.tsx, packages/mobile/src/components/favorite-button/FavoriteButton.tsx, packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx, packages/mobile/src/components/repost-button/RepostButton.tsx, packages/mobile/src/haptics.ts
Adds missing haptics to favorite and reposts buttons, and segmented control
=> [AUD-1739] Add missing haptics

packages/mobile/src/components/bottom-tab-bar/BottomTabBarButton.tsx, packages/mobile/src/components/core/AnimatedButton.tsx, packages/mobile/src/components/favorite-button/FavoriteButton.tsx, packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx, packages/mobile/src/components/now-playing-drawer/AudioControls.tsx, packages/mobile/src/components/now-playing-drawer/FavoriteButton.tsx, packages/mobile/src/components/now-playing-drawer/PlayBar.tsx, packages/mobile/src/components/now-playing-drawer/PlayButton.tsx, packages/mobile/src/components/now-playing-drawer/RepeatButton.tsx, packages/mobile/src/components/now-playing-drawer/RepostButton.tsx, packages/mobile/src/components/now-playing-drawer/ShuffleButton.tsx, packages/mobile/src/components/repost-button/RepostButton.tsx
* Colorize all of the icons
* Updated AnimatedButton to only accept one json for the icon since it is colorized
N/A
Manually Tested, colors are looking good 👍 
N/A
=> Update AnimatedButton and colorize icons passed to animated buttons

packages/mobile/src/components/reachability-bar/ReachabilityBar.tsx
Fixes offline state that was showing offline indicator when online
Fixes pointer events to allow interacting with the top bar when indicator is active
=> [AUD-1784] Fix offline indicator state and pointer events

packages/mobile/src/components/top-tab-bar/CollapsibleTopTabNavigator.tsx, packages/mobile/src/screens/profile-screen/ProfileTabNavigator.tsx
Removes lazy option which removes strange profile scroll bug
=> [AUD-1805] Remove lazy screen option for profile

packages/web/README.md
Adds docs to run libs locally in audius-client, which has changed slightly due to libs now needing to be transpiled.
=> [AUD-1810] Add docs to run local libs in audius-client

packages/web/package-lock.json, packages/web/package.json, packages/web/src/common/models/Analytics.ts, packages/web/src/services/audius-backend/Rewards.ts
Update analytics based on new rewards responses
n/a
Test locally against staging
has analytics
=> Consume libs 1.2.101

packages/mobile/src/components/core/SegmentedControl.tsx
[AUD-1806]
* Updated the SegmentedControl component to set initial width and left position
* Changed optionsWidths to use the state hook so that the initial position would be correct
N/a
N/a
=> [AUD-1806] Update SegmentedControl component to set initial width and left position

packages/mobile/src/components/reachability-bar/ReachabilityBar.tsx
Fixes case where small purple line of the reachability bar is showing on smaller devices
=> [AUD-1784] Fix ReachabilityBar height

packages/mobile/src/components/reachability-bar/ReachabilityBar.tsx
Accidentally switch case when testing
=> Fix reachability-bar reachable state

packages/web/package-lock.json, packages/web/package.json
Gets https://github.com/AudiusProject/audius-protocol/commit/71b35a477d0160714959e8200fb9143132eb3681
=> Consume libs 1.2.102

packages/web/src/common/services/remote-config/feature-flags.ts
=> [AUD-1700] Remove TRENDING_UNDERGROUND feature flag

packages/web/src/common/services/remote-config/feature-flags.ts, packages/web/src/services/AudiusBackend.js, packages/web/src/services/audius-backend/waudio.ts
=> Remove userbank signup creation flag

packages/mobile/src/components/now-playing-drawer/PlayButton.tsx
[AUD-1823]
* Updated play button icon color to cover both dark mode and matrix mode cases
N/a
N/a
=> [AUD-1823] Update play button to use staticWhite color unless using matrix theme

packages/web/package-lock.json, packages/web/package.json
Bumps libs to a version where libs browser config does not exclude a dependency that is required.
=> Fix libs browser config

lerna.json, packages/mobile/package-lock.json, packages/mobile/package.json, packages/web/package-lock.json, packages/web/package.json
[48ac952c] Fix libs browser config (#1170) Dylan Jeffers
[916fb6ee] Update play button to use staticWhite color unless using matrix theme (#1169) Kyle Shanks
[b72a9a1d] [AUD-1817] Fix PlayBar opacity (#1167) Dylan Jeffers
[ba7a79cd] [AUD-1812] Prevent unnecessary store syncs (#1158) Sebastian Klingler
[e5034b7f] Remove userbank signup creation flag (#1164) Michael Piazza
[877f7f0f] [AUD-1700] Remove TRENDING_UNDERGROUND feature flag (#1166) Michael Piazza
[a7397f22] Consume libs 1.2.102 (#1165) Michael Piazza
[6f296cea] Add TrackListItemSkeleton component and add loading state to CollectionsScreenDetailsTile (#1163) Kyle Shanks
[5c8070ae] Fix reachability-bar reachable state (#1161) Dylan Jeffers
[3e703313] [AUD-1784] Fix ReachabilityBar height (#1159) Dylan Jeffers
[8006b371] Update …
=> Version bump

packages/mobile/src/components/audio-rewards/index.ts, packages/mobile/src/screens/profile-screen/ProfileBadge.tsx, packages/mobile/src/screens/settings-screen/AccountSettingsItem.tsx
Fixes profile badge gradient
Fixes account settings button variant to commonAlt
=> [AUD-1851,AUD-1847] Fix badge gradient, account settings button variant

.circleci/src/jobs/@mobile-jobs.yml, packages/mobile/src/screens/settings-screen/SettingsRowDescription.tsx, packages/web/src/components/bottom-bar/BottomBar.tsx
For consistency w/ local env
CI
CI
=> Upgrade xcode version

packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx
[AUD-1890]
Adding formatting to profile stats so larger numbers display a little better
N/A
N/A
=> [AUD-1890] Add formatting for profile stats

packages/mobile/src/components/core/CardList.tsx, packages/mobile/src/components/details-tile/DetailsTile.tsx, packages/mobile/src/components/lineup-tile/LineupTileRoot.tsx, packages/mobile/src/screens/explore-screen/tabs/ArtistsTab.tsx, packages/mobile/src/screens/explore-screen/tabs/ForYouTab/ForYouTab.tsx, packages/mobile/src/screens/explore-screen/tabs/ForYouTab/LetThemDJScreen.tsx, packages/mobile/src/screens/explore-screen/tabs/MoodsTab.tsx, packages/mobile/src/screens/explore-screen/tabs/PlaylistsTab.tsx, packages/mobile/src/screens/smart-collection-screen/SmartCollectionScreen.tsx
- Fixes TrackTile maxWidth (didn't render correctly for pro max)
- Improves bottom margins for card lists and other screens
- Preloads smart collection lists improving initial render
TODO: leaving this open for the day to address any other small changes
=> [AUD-1861] Minor release styling and fixes

packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx, packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Fixes profile left header spacing and back button navigation
=> [AUD-1891] Fix Profile left header, back button

packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
Fixes app breaking extraneous goBack in appScreenOptions dependencies
=> Remove extraneous goBack in appScreenOptions

packages/mobile/src/components/core/AnimatedButton.tsx, packages/mobile/src/components/core/Button.tsx, packages/mobile/src/components/favorite-button/FavoriteButton.tsx, packages/mobile/src/components/now-playing-drawer/FavoriteButton.tsx, packages/mobile/src/components/now-playing-drawer/RepeatButton.tsx, packages/mobile/src/components/now-playing-drawer/RepostButton.tsx, packages/mobile/src/components/now-playing-drawer/ShuffleButton.tsx, packages/mobile/src/components/repost-button/RepostButton.tsx, packages/mobile/src/components/user/FollowButton.tsx, packages/mobile/src/screens/profile-screen/SubscribeButton.tsx
- Adds haptics to follow/subscribe buttons
- Removes haptics for destructive actions
- Improve iconJSON perf
=> [AUD-1897] Add haptics to follow/subscribe buttons

packages/mobile/src/components/lineup/Lineup.tsx
* Fixes overlap of bottom of lineup with bottom bar
Just did this at the lineup level to cover all the cases
iOS sim
TestFlight QA
=> [AUD-1898] Fix overlap at bottom of lineup

packages/mobile/src/screens/user-list-screen/UserChip.tsx, packages/mobile/src/screens/user-list-screen/UserList.tsx
* Formatted count for user list
* Switched white background color to UserChip
N/A
N/A
=> [AUD-1905 AUD-1907] Add small fixes to mobile UserList

packages/mobile/src/screens/profile-screen/ProfileSocials.tsx
Improves profile cls by rendering skeletons for social icons.
=> Improve profile social loading and cls

packages/mobile/src/screens/search-results-screen/tabs/SearchResultsTab.tsx
Loading spinner different size on search section. using the same component to make updates easier
=> Consolidate loading spinner

packages/web/package-lock.json, packages/web/package.json
Gets https://github.com/AudiusProject/audius-protocol/commit/557cae60afa221f8440a7903c3f3a40c2427d62f
=> Consume Libs 1.2.107

packages/mobile/src/screens/app-screen/AppTabScreen.tsx
I accidentally merged before pushing the changes that addressed the PR comments
=> Notifications transitions pt 2

packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistLink.tsx, packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
* Adds event handlers to the artists in ArtistRecommendations
* Sets pointerEvents so that scrolling works on non pressable elements
N/A
iOS simulator
TestFlight QA
=> [AUD-1906] Make artist suggestions pressable

packages/mobile/src/styles/makeStyles.ts
Interesting improvements to makeStyles that reduces rerenders by 2x
- Memoize props
- Memoize Stylesheet.create
=> [AUD-1916] Improve makeStyles perf

packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
We shouldn't render ArtistRecommendations when there are no artists to recommend
=> [AUD-1921] Don't render ArtistRecommendations when empty

packages/web/src/store/lineup/sagas.js
Updated lineup saga delay up to 100ms
N/A
Manually tested. Appears to load fine
Will monitor for flakeness in the future and update if there are still issues
=> Update lineup saga delay up to 100ms to avoid flakeyness

packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Replaces search button with share-profile button on profile screens
https://user-images.githubusercontent.com/8230000/163886728-a73407e5-8a38-4192-a8ed-97c657ff05b0.mov
=> [AUD-1922] Replace search with share-profile on profile screen

packages/web/src/components/collectibles/components/CollectiblesPage.module.css, packages/web/src/components/collectibles/components/CollectiblesPage.tsx, packages/web/src/components/collection/desktop/CollectionHeader.js, packages/web/src/components/collection/desktop/CollectionHeader.module.css, packages/web/src/components/nav/desktop/NavButton.js, packages/web/src/components/nav/desktop/NavButton.module.css, packages/web/src/components/track/GiantTrackTile.js, packages/web/src/components/track/GiantTrackTile.module.css, packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.module.css, packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx, packages/web/src/pages/explore-page/components/desktop/CollectionsPage.module.css, packages/web/src/pages/explore-page/components/desktop/CollectionsPage.tsx, packages/web/src/pages/explore-page/components/mobile/CollectionsPage.module.css, packages/web/src/pages/explore-page/components/mobile/CollectionsPage.tsx, packages/web/src/pages/explore-page/components/mobile/ExplorePage.module.css, packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx, packages/web/src/pages/history-page/components/desktop/HistoryPage.module.css, packages/web/src/pages/history-page/components/desktop/HistoryPage.tsx, packages/web/src/pages/history-page/components/mobile/HistoryPage.module.css, packages/web/src/pages/history-page/components/mobile/HistoryPage.tsx, packages/web/src/pages/requires-update/RequiresUpdate.module.css, packages/web/src/pages/requires-update/RequiresUpdate.tsx, packages/web/src/pages/saved-page/components/mobile/SavedPage.module.css, packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx, packages/web/src/pages/search-page/components/desktop/SearchPageContent.js, packages/web/src/pages/search-page/components/desktop/SearchPageContent.module.css, packages/web/src/pages/search-page/components/mobile/SearchPageContent.module.css, packages/web/src/pages/search-page/components/mobile/SearchPageContent.tsx, packages/web/src/pages/sign-on/components/LoadingPage.js, packages/web/src/pages/sign-on/components/LoadingPage.module.css
[C-366]
Update all places that use the antd spin component to use the LoadingSpinner component
There may be some places where the loading is not the exact same size or position
N/a
=> [C-366] Remove antd Spin component and replace with LoadingSpinner

packages/mobile/src/screens/user-list-screen/FavoritedScreen.tsx, packages/mobile/src/screens/user-list-screen/FollowersScreen.tsx, packages/mobile/src/screens/user-list-screen/FollowingScreen.tsx, packages/mobile/src/screens/user-list-screen/RepostsScreen.tsx, packages/mobile/src/screens/user-list-screen/UserList.tsx
Fixes background color (now white)
Fixes loading spinner placement (now better spaced)
Fixes goBack logic to not flash blank screen
https://user-images.githubusercontent.com/8230000/165396483-9eb71231-b24a-4e34-a182-3c5904069b59.mov
=> [C-316] Fix user-list background and spinner

packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
* Centers the title in the header
n/a
android and ios
testflight / playstore
=> [C-412] Set title alignment

packages/web/src/pages/profile-page/components/mobile/ProfileHeader.module.css, packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
[C-362] 
Remove antd Skeletons from mobile Profile Header
N/a
N/a
=> [C-362] Remove antd from mobile ProfileHeader

packages/mobile/package-lock.json, packages/mobile/package.json, packages/mobile/src/components/core/AnimatedButton.tsx, packages/mobile/src/components/now-playing-drawer/AudioControls.tsx, packages/mobile/src/components/now-playing-drawer/PlayBar.tsx, packages/mobile/src/components/now-playing-drawer/PlayButton.tsx, packages/mobile/src/components/now-playing-drawer/TrackingBar.tsx
* Fixes play button state on android by adding a key to the LottieView and upgrading lottie
* Reduces rerenders of playbar by moving tracking state into tracking bar
Animations could be impacted, but things looked good
Android and ios
TestFlight / playstore
=> [C-421] Fix play button state on android

packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
* Removes extra header back button on android
n/a
android and ios
TestFlight / play store
=> [C-420] Remove header back button on android

packages/web/src/assets/styles/colors.css, packages/web/src/components/collection/desktop/CollectionHeader.js, packages/web/src/components/filter-input/FilterInput.module.css, packages/web/src/components/filter-input/FilterInput.tsx, packages/web/src/components/input/Input.module.css, packages/web/src/components/input/Input.tsx, packages/web/src/components/input/index.ts, packages/web/src/utils/theme/dark.ts, packages/web/src/utils/theme/default.ts, packages/web/src/utils/theme/matrix.ts
[C-372 C-376] 
* Add new Input component
* Remove antd input from CollectionHeader
* Remove antd input from FilterInput (Used on History Page and Saved Page)
There may be slight size differences
Manually tested, I think I covered all of the current functionality
N/A
=> [C-372 C-376] Add Input component and remove antd input from collection header and filter input

packages/mobile/src/components/core/Text.tsx, packages/mobile/src/components/trending-rewards-drawer/TrendingRewardsDrawer.tsx, packages/mobile/src/styles/typography.ts
Fixes trending terms link
Uses non-deprecated Text
Uses Link
=> [C-431] Fix trending terms link

packages/web/package-lock.json, packages/web/package.json
Fixes issue where contract-client appears to be initialized, but is missing _contractAddress, resulting in an incorrect relay call
=> [AUD-1940] Fix libs contract-client init

packages/web/package-lock.json, packages/web/package.json, packages/web/src/assets/styles/colors.css, packages/web/src/utils/theme/dark.ts, packages/web/src/utils/theme/default.ts, packages/web/src/utils/theme/matrix.ts
This fixes the colors for the Buttons and PopupMenus in dark mode to be white on primary and secondary colors
If there are any other places where the colors need to be updated
N/A
=> Update stems version to 0.3.31

packages/web/package-lock.json, packages/web/package.json, packages/web/src/services/AudiusBackend.js, packages/web/src/types/libs/libs.d.ts
Fixes DiscoveryAPI libs import using new core entrypoint
- TODO: publish and include libs changes before merging: https://github.com/AudiusProject/audius-protocol/pull/3038
=> Fix DiscoveryAPI libs import

packages/web/src/common/store/notifications/types.ts, packages/web/src/components/artist/ArtistPopover.tsx, packages/web/src/components/notification/Notifications/NotificationBody.tsx, packages/web/src/components/notification/Notifications/RemixCreateNotification.tsx, packages/web/src/components/notification/Notifications/TipSentNotification.module.css, packages/web/src/components/notification/Notifications/TipSentNotification.tsx, packages/web/src/components/notification/Notifications/UserNameLink.module.css, packages/web/src/components/notification/Notifications/UserNameLink.tsx
=> [PAY-158] Add TipSentNotification

packages/mobile/src/screens/audio-screen/AudioScreen.tsx
=> Fix AudioScreen typos

packages/mobile/src/screens/search-screen/SearchBar.tsx
Fixes issue when coming back to search page with an existing query, the clear button is missing.
=> [C-467] Fix missing clear button with existing search

packages/web/src/components/notification/Notifications/NotificationTile.module.css, packages/web/src/components/notification/Notifications/NotificationTile.tsx, packages/web/src/components/notification/Notifications/TipReceivedNotification.module.css, packages/web/src/components/notification/Notifications/TipReceivedNotification.tsx, packages/web/src/components/notification/Notifications/reactions/Reaction.module.css, packages/web/src/components/notification/Notifications/reactions/Reaction.tsx, packages/web/src/components/notification/Notifications/reactions/index.tsx
Add TipReceivedNotification
Adds disabled prop to NotifTile
Adds reaction animations
https://user-images.githubusercontent.com/8230000/167222913-4fd83104-48ed-48f0-ac56-1147a82e655c.mov
=> [PAY-156] Add TipReceivedNotification

packages/mobile/src/screens/audio-screen/AudioScreen.tsx
Fixes incorrect min amounts for audio tiers
=> [C-471] Fix AudioScreen audio tier min amount

packages/web/src/common/store/notifications/types.ts, packages/web/src/components/notification/Notifications/ChallengeRewardNotification.tsx, packages/web/src/components/notification/Notifications/FavoriteNotification.tsx, packages/web/src/components/notification/Notifications/FollowNotification.tsx, packages/web/src/components/notification/Notifications/MilestoneNotification.tsx, packages/web/src/components/notification/Notifications/RemixCosignNotification.tsx, packages/web/src/components/notification/Notifications/RemixCreateNotification.tsx, packages/web/src/components/notification/Notifications/RepostNotification.tsx, packages/web/src/components/notification/Notifications/TierChangeNotification.tsx, packages/web/src/components/notification/Notifications/TrendingTrackNotification.tsx, packages/web/src/components/notification/Notifications/TwitterShareButton.tsx, packages/web/src/components/notification/Notifications/UserSubscriptionNotification.tsx, packages/web/src/components/notification/Notifications/utils.ts
Implements share to twitter functionality for notifications that already have a share feature.
=> [PAY-177] Implement notification share to twitter actions

packages/web/src/common/store/notifications/types.ts, packages/web/src/components/notification/Notifications/ChallengeRewardNotification.tsx, packages/web/src/components/notification/Notifications/FollowNotification.tsx, packages/web/src/components/notification/Notifications/MilestoneNotification.tsx, packages/web/src/components/notification/Notifications/NotificationTile.tsx, packages/web/src/components/notification/Notifications/RemixCosignNotification.tsx, packages/web/src/components/notification/Notifications/RemixCreateNotification.tsx, packages/web/src/components/notification/Notifications/TrendingTrackNotification.tsx, packages/web/src/components/notification/Notifications/UserSubscriptionNotification.tsx, packages/web/src/components/notification/Notifications/types.ts, packages/web/src/components/notification/Notifications/utils.ts
Implements Notification tile click events
=> [PAY-179] Implement Notification click events

packages/web/src/common/services/remote-config/feature-flags.ts, packages/web/src/components/share-modal/ShareModal.tsx, packages/web/src/pages/upload-page/components/ShareBanner.tsx
This reverts commit d3df9a8873482b7b2efbc2762e65e0ca553ecc03.
=> Revert "Remove tik tok feature flag"

packages/web/package-lock.json, packages/web/package.json
Appears to fix sign up issues on current stage
=> Libs 1.2.116

packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx, packages/web/src/components/artist/ArtistPopover.module.css, packages/web/src/components/artist/ArtistPopover.tsx
This reverts commit b39c919db0099ed1ac90447e1ae4b24015a3d955.
Reverting artist popover replacement to open an antd deprecation branch
N/A
N/A
N/A
=> Revert 'Replace antd popover with popup from stems (#1284)

packages/web/src/common/store/notifications/types.ts, packages/web/src/components/dynamic-image/DynamicImage.tsx, packages/web/src/components/notification/Notifications/Notification.tsx, packages/web/src/components/notification/Notifications/TipReactionNotification.module.css, packages/web/src/components/notification/Notifications/TipReactionNotification.tsx, packages/web/src/components/notification/Notifications/TipReceivedNotification.module.css, packages/web/src/components/notification/Notifications/TipReceivedNotification.tsx, packages/web/src/components/notification/Notifications/TipSentNotification.module.css
Fixes a few layout and type issues for tip notifications. This happened since `NotificationBody` styles changed for Redesign
=> Fix TipNotification layouts

packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
Remove state from Oauth JWT payload since it should be returned in a redirect query param
=> (1 liner) Remove state from payload

packages/mobile/src/screens/notifications-screen/NotificationBlock.tsx
* Fixes type check by adding missing `TipReceived` notif type to mappings
will cherry pick onto release branch
=> Fix typecheck by adding missing notif type

packages/web/src/components/notification/Notification/FavoriteNotification.tsx, packages/web/src/components/notification/Notification/FollowNotification.tsx, packages/web/src/components/notification/Notification/RepostNotification.tsx, packages/web/src/components/notification/Notification/components/ProfilePicture.module.css, packages/web/src/components/notification/Notification/components/UserNameLink.module.css, packages/web/src/components/notification/Notification/components/UserNameLink.tsx, packages/web/src/components/user-badges/UserBadges.tsx
Fixes two callouts with notification profile picture
- Removes opacity on profile-picture hover
- Prevents default tile behavior when clicking on profile-picture
=> [PAY-214] Fix notification profile picture hover/click

packages/web/src/pages/profile-page/sagas.js, packages/web/src/services/audius-backend/Tipping.ts, packages/web/src/store/tipping/sagas.ts
So that it does not make unnecessary calls to the API
n/a
no calls are made to the tipping api
n/a
=>  Disable fetching tipping support on profile sagas

packages/mobile/src/components/collectible-details-drawer/CollectibleDetailsDrawer.tsx, packages/web/src/common/store/ui/collectible-details/slice.ts
Fixes issue where native collectibles-drawer wasn't showing collectible due to the way state was set in the reducer, which prevented re-sync
Also cleans up styling approach
=> [C-523] Fix native collectibles-drawer

packages/web/package-lock.json, packages/web/package.json
=> Bump Stems 0.3.33

packages/mobile/src/components/api-rewards-drawer/ApiRewardsDrawer.tsx, packages/mobile/src/components/core/Button.tsx, packages/mobile/src/components/core/Link.tsx, packages/mobile/src/components/discord-drawer/DiscordDrawer.tsx, packages/mobile/src/screens/notifications-screen/content/ChallengeReward.tsx, packages/mobile/src/screens/notifications-screen/content/Cosign.tsx, packages/mobile/src/screens/notifications-screen/content/TwitterShare.tsx, packages/mobile/src/store/search/hooks.ts, packages/web/src/pages/audio-rewards-page/WalletModal.tsx, packages/web/src/pages/audio-rewards-page/components/modals/TopAPI.tsx, packages/web/src/utils/route.ts
Fixes following sentry issues:
- https://sentry.io/organizations/audius/issues/3250523409/?project=1457231&query=is%3Aunresolved+release.version%3A1.1.13&sort=freq&statsPeriod=14d
- https://sentry.io/organizations/audius/issues/3251513034/?project=1457231&query=is%3Aunresolved+release.version%3A1.1.13&sort=freq&statsPeriod=14d
- https://sentry.io/organizations/audius/issues/3253018805/?project=1457231&query=is%3Aunresolved+release.version%3A1.1.13&sort=freq&statsPeriod=14d
- https://sentry.io/organizations/audius/issues/3259981985/?project=1457231&query=is%3Aunresolved+release.version%3A1.1.13&sort=freq&statsPeriod=14d
Will monitor 1.1.14 for similar errors
=> [C-522] Fix top sentry issues 1.1.13

packages/web/src/common/store/tipping/slice.ts, packages/web/src/components/artist/ArtistChip.tsx, packages/web/src/components/artist/ArtistSupporting.tsx, packages/web/src/components/tipping/support/SupportingList.tsx, packages/web/src/components/tipping/support/TopSupporters.tsx, packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx, packages/web/src/components/tipping/tip-audio/SendTip.tsx, packages/web/src/components/tipping/tip-audio/TipAudio.module.css, packages/web/src/components/user-list/utils.ts, packages/web/src/pages/favorites-page/sagas.ts, packages/web/src/pages/followers-page/sagas.ts, packages/web/src/pages/following-page/sagas.ts, packages/web/src/pages/profile-page/sagas.js, packages/web/src/pages/reposts-page/sagas.ts, packages/web/src/pages/supporting-page/sagas.ts, packages/web/src/pages/top-supporters-page/sagas.ts, packages/web/src/services/audius-backend/Tipping.ts, packages/web/src/store/tipping/sagas.ts, packages/web/src/utils/constants.ts
Fixes and updates for certain QA issues
- fix artist popover previously not showing in user list modal
- fix supporting user list modal after clicking on artist popover supporting section
- refactor fetching of supporters/supporting
- optimize number of initial supporters and supporting to fetch
- update retry confirm send tip button copy
- fix off-by-one become top supporter logic
- add logic for optional extra processing after fetching user list modal users, so that supporting and top supporters can cache tipping data in redux store
n/a
locally against staging
n/a
=> Fix tipping QA

packages/web/src/common/utils/genres.ts, packages/web/src/components/trending-genre-selection/TrendingGenreSelectionPage.tsx, packages/web/src/pages/trending-page/components/desktop/TrendingPageContent.tsx
Add `"Lo-Fi"` music genre.
Not too familiar w the client repo but don't think so!
Run client and check genres 
N/A; just a category add
=> AUD-1172 Add Lo-Fi Music Genre

packages/web/src/components/tracks-table/TracksTable.module.css
Fix long name in playlist causing table misalignment.
=> [C-539] Fix long name in playlist causing table misalignment

packages/mobile/src/components/core/Text.tsx, packages/mobile/src/screens/notifications-screen/Notification/NotificationHeader.tsx, packages/mobile/src/screens/notifications-screen/Notification/NotificationText.tsx, packages/mobile/src/screens/notifications-screen/Notification/NotificationTile.tsx, packages/mobile/src/screens/notifications-screen/Notification/ProfilePictureList.tsx, packages/mobile/src/screens/notifications-screen/Notification/UserNameLink.tsx, packages/mobile/src/screens/notifications-screen/Notification/index.ts, packages/mobile/src/screens/notifications-screen/Notifications/FollowNotification.tsx, packages/mobile/src/screens/notifications-screen/useDrawerNavigation.ts, packages/mobile/src/styles/typography.ts
Adds core native notification components
Implements FavoriteNotification
=> [PAY-222] Add native notification core components

packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx, packages/web/src/pages/styles/OAuthLoginPage.module.css
-Make sign out button hover state more prominent
-Fix sign out button text clipping on Safari
-Fix email loading icon misaligned on Safari
=> OAuth Design QA C-534 C-533 C-532

packages/mobile/src/components/core/Button.tsx, packages/mobile/src/screens/app-screen/AppTabScreen.tsx, packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx, packages/mobile/src/screens/profile-screen/TipArtistButton.tsx, packages/mobile/src/screens/tip-artist-screen/ConfirmTipScreen.tsx, packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx, packages/mobile/src/screens/tip-artist-screen/TipArtistModal.tsx, packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx, packages/mobile/src/screens/tip-artist-screen/index.ts, packages/mobile/src/screens/tip-artist-screen/navigation.ts
Adds TipArtistModal and basic modal navigation
This is the first native modal that is correctly using react-navigation and not redux modal state
https://user-images.githubusercontent.com/8230000/170354779-ac89d197-e142-40cd-9e53-2200c7bacdaf.mov
=> [PAY-247] Add TipArtistModal and basic navigation

packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
If user passes in `redirect_uri=postmessage` and `origin=<origin e.g. https://myapp.com>` the Oauth popup will use a window message to communicate with the consumer app, instead of a redirect.
This communication method is used in the SDK OAuth util https://github.com/AudiusProject/audius-protocol/pull/3147
Resources:
https://web-in-security.blogspot.com/2021/02/security-and-privacy-of-social-logins-part2.html
https://accidentalfactors.com/oauth2.0/googleplus/2013/03/06/postmessage-oauth-20/
*For features that are critical or could fail silently please describe the monitoring/alerting …
=> Add postMessage functionality to OAuth popup

packages/mobile/src/components/share-drawer/ShareDrawer.tsx
This was missed initially
n/a
ios sim
=> [C-547] Wrap tiktok on native in a feature flag

packages/mobile/src/screens/notifications-screen/NotificationList.tsx, packages/mobile/src/screens/profile-screen/ProfileScreen.tsx, packages/mobile/src/screens/user-list-screen/UserList.tsx
Adds native tipping feature flags
Unlocks:
- Notification Redesign
- User List Redesign
- Tip Audio Flow
=> Add native tipping feature flags

packages/web/src/components/follow-button/FollowButton.js, packages/web/src/components/follow-button/FollowButton.module.css, packages/web/src/components/tipping/support/Support.module.css, packages/web/src/components/tipping/support/SupportingTile.tsx, packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx, packages/web/src/components/tipping/tip-audio/SendTip.tsx, packages/web/src/components/tipping/tip-audio/TipAudio.module.css, packages/web/src/components/tipping/tip-audio/TipAudioButton.tsx, packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx, packages/web/src/pages/profile-page/sagas.js, packages/web/src/store/tipping/sagas.ts
Fix more tipping QA issues.
n/a
n/a
=> Fix more tipping QA issues

packages/mobile/src/components/twitter-button/TwitterButton.tsx, packages/mobile/src/components/twitter-button/index.ts, packages/mobile/src/screens/tip-artist-screen/ConfirmSendTipScreen.tsx, packages/mobile/src/screens/tip-artist-screen/TipHeader.tsx, packages/mobile/src/screens/tip-artist-screen/TipInput.tsx, packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx
- Implements TipSentScreen
- Adds TwitterButton
- Finishes native tipping flow
https://user-images.githubusercontent.com/8230000/170601417-b61ee8c1-7eac-4c9b-bb00-7a4829d86fa6.mov
=> [PAY-264] Implement TipSentScreen

packages/web/src/common/models/Analytics.ts, packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
=> Add Amplitude events

packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css
Fix alignment and tile hover issues.
n/a
n/a
=> Fix styling

packages/web/src/common/models/AudioRewards.ts, packages/web/src/pages/audio-rewards-page/store/sagas.ts
Wasn't handling this error properly, causing numerous retries
Tested on stage
=> Fix handling unknown AAO error

packages/web/package-lock.json, packages/web/package.json
=> Bump Stems 0.3.36 for Scrollbar fixes

packages/mobile/src/components/core/Hyperlink.tsx, packages/mobile/src/components/core/Link.tsx, packages/mobile/src/hooks/useAndroidNavigationBarHeight.ts, packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx, packages/mobile/src/screens/collection-screen/CollectionScreen.tsx, packages/mobile/src/screens/explore-screen/components/ColorTile.tsx, packages/mobile/src/screens/notifications-screen/NotificationList.tsx, packages/mobile/src/screens/notifications-screen/routeUtil.ts, packages/mobile/src/screens/profile-screen/EditProfileButton.tsx, packages/mobile/src/screens/profile-screen/ProfileScreen.tsx, packages/mobile/src/screens/settings-screen/AccountSettingsRow.tsx, packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx, packages/mobile/src/screens/settings-screen/SettingsScreen.tsx, packages/mobile/src/screens/track-screen/TrackScreen.tsx, packages/mobile/src/store/audio/reducer.ts, packages/web/src/common/store/cache/collections/selectors.ts, packages/web/src/common/utils/uid.ts, packages/web/src/pages/collection-page/CollectionPageProvider.tsx
Addresses top errors for 1.1.15 release:
https://sentry.io/organizations/audius/issues/3278477251/?_allp=1&query=is%3Aunresolved+release.version%3A1.1.15&statsPeriod=14d
https://sentry.io/organizations/audius/issues/3273253958/?_allp=1&query=is%3Aunresolved+release.version%3A1.1.15&statsPeriod=14d
https://sentry.io/organizations/audius/issues/3239725370/?_allp=1&query=is%3Aunresolved+release.version%3A1.1.15&statsPeriod=14d
https://sentry.io/organizations/audius/issues/3271472500/?_allp=1&query=is%3Aunresolved+release.version%3A1.1.15&statsPeriod=14d
https://sentry.io/organizations/audius/issues/2990680632/?_allp=1&query=is%3Aunresolved+release.version%3A1.1.15&statsPeriod=14d
https://sentry.io/organizations/audius/issues/2876540440/?_allp=1&query=is%3Aunresolved+release.version%3A1.1.15&s …
=> [C-553] Address sentry issues for 1.1.15

packages/mobile/src/screens/track-screen/TrackScreenRemixes.tsx
Fix margin issue with remixes tile on track screen
=> Fix remixes tile margin

packages/mobile/src/components/sign-out-confirmation-drawer/SignOutConfirmationDrawer.tsx
Fixes case where search history of a previous user appears when signing in as different user
=> [AUD-1146] Clear search history on sign-out

packages/mobile/src/screens/app-screen/AppTabScreen.tsx, packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ExpandedSection.tsx, packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ProfileMutualsButton.tsx, packages/mobile/src/screens/user-list-screen/MutualsScreen.tsx, packages/mobile/src/screens/user-list-screen/index.ts, packages/web/src/common/store/index.ts, packages/web/src/common/store/user-list/following/actions.ts, packages/web/src/common/store/user-list/mutuals/actions.ts, packages/web/src/common/store/user-list/mutuals/errorSagas.ts, packages/web/src/common/store/user-list/mutuals/reducers.ts, packages/web/src/common/store/user-list/mutuals/selectors.ts, packages/web/src/common/store/user-list/mutuals/types.ts, packages/web/src/pages/mutuals-page/sagas.ts, packages/web/src/store/sagas.ts
Adds native mutuals screen and action to open from mutuals button
Adds mutuals user-list redux state
=> [Pay-202] Add native mutuals screen

packages/web/src/common/services/remote-config/feature-flags.ts, packages/web/src/components/notification/store/sagas.ts, packages/web/src/services/AudiusBackend.js
- Enables notifications for tips
- Removes Rewards notification flag
=> [PAY-238] Enable tipping notifications

packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css
They were stacked instead of inline
n/a
locally against staging
n/a
=> Fix badges stacked up

packages/web/package-lock.json, packages/web/package.json, packages/web/src/services/AudiusBackend.js, packages/web/src/services/LocalStorage.ts, packages/web/src/services/audius-backend/AudiusLibsLazyLoader.ts
* Upgrades the web client to use `@audius/sdk` instead of `@audius/libs`
Potential changes to libs behavior
locally against prod data
=> Upgrade to @audius/sdk

packages/mobile/src/screens/notifications-screen/Notification/NotificationTile.tsx, packages/mobile/src/screens/notifications-screen/Notification/ProfilePicture.tsx, packages/mobile/src/screens/notifications-screen/Notification/UserNameLink.tsx, packages/mobile/src/screens/notifications-screen/NotificationList.tsx, packages/mobile/src/screens/notifications-screen/Notifications/AnnouncementNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TipReactionNotification.tsx, packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx
Addresses various mobile notification qa issues
=> [PAY-268 PAY-270 PAY-271] Fix announcement formatting, scroll, and spacing

packages/mobile/package-lock.json
Typecheck was failing bc mobile package-lock hadn't been updated with the upgrade to sdk
n/a
locally
=> Update mobile package lock

packages/web/src/components/artist/ArtistChip.tsx
Add touch target for entire list modal row
n/a
n/a
=> [PAY-276] Add touch target for entire list modal row

packages/web/src/components/tipping/support/Support.module.css, packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.module.css
.Add transition for text and icon color in profile mutuals and top supporters tile
n/a
n/a
=> [PAY-311] Add transition for text and icon color in profile tiles

packages/web/src/pages/profile-page/components/desktop/ProfilePage.module.css
Add hover purple text to See More / See Less in profile bio section
n/a
n/a
=> [PAY-312] Add hover purple text

packages/web/src/components/artist/ArtistChip.tsx, packages/web/src/components/user-list/components/UserList.tsx
Attaches the popover to body so that it doesn't scroll the page, to match previous user list behavior.
=> [PAY-308] Don't scroll user list popovers

packages/web/src/components/stat-banner/StatBanner.js, packages/web/src/components/stat-banner/StatBanner.module.css, packages/web/src/components/user-list-modal/components/UserListModal.module.css
Fixes:
Follow Button:
- Font size too small
- Icon Too Small
- Casing Wrong
Userlist Modal:
- Title casing wrong
- Title Font color is wrong
=> [PAY-316] Fix follow button font size and misc other QA

packages/web/src/components/tracks-table/TracksTable.module.css
* Fix the positioning of the artist popover
* Fix the height of the user tier and verified badges
N/A
Manually tested, looks good
N/A
=> [C-571] Update Artist Popover positioning and badge height

packages/web/src/components/tooltip/Tooltip.module.css
* Update position styles for vertical tooltips to avoid overlap
N/A
N/A
=> C-570 Update vertical tooltip styles to avoid arrow overlap

packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
Context: https://audius-internal.slack.com/archives/C03C2V84A1L/p1654720379393259?thread_ts=1654716585.218999&cid=C03C2V84A1L
Adds profile picture sizes to Oauth response
Tested in browser 
=> Return profile picture in OAuth response

packages/web/package-lock.json, packages/web/package.json
Required for fixing https://linear.app/audius/issue/PAY-218/things-jump-around-when-hovering-over-follow-buttons
See:
- https://github.com/AudiusProject/audius-client/pull/1404
- https://github.com/AudiusProject/audius-client/pull/1412
- https://github.com/AudiusProject/stems/pull/136
=> Bump stems to 0.3.37 in web client

packages/stems/package.json, packages/stems/src/components/Modal/Modal.tsx, packages/stems/src/components/Popup/Popup.tsx, packages/stems/src/hooks/useClickOutside.ts
Fixes issue with image selection popover not opening
Lots of interplay with modal onClickOutside logic and popovers
=> Only apply onClickOutside when visible

packages/mobile/src/components/feed-tip-tile/FeedTipTile.tsx, packages/mobile/src/components/feed-tip-tile/SendTipButton.tsx, packages/mobile/src/screens/profile-screen/TipArtistButton.tsx, packages/mobile/src/screens/profile-screen/TipAudioButton.tsx, packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx, packages/web/src/common/models/Analytics.ts, packages/web/src/common/store/tipping/slice.ts, packages/web/src/common/store/tipping/types.ts, packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx, packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx, packages/web/src/components/tipping/tip-audio/TipAudioButton.tsx, packages/web/src/components/tipping/tip-audio/TipSent.tsx, packages/web/src/store/tipping/sagas.ts
- Separate web vs mobile tips analytics by adding a device param
- Include source param for profile vs feed
- Add analytic for dismissing the feed tip tile
n/a
amplitude
=> [PAY-302] Update tipping analytics for web and mobile

packages/web/package-lock.json, packages/web/package.json
=> Upgrade stems to 0.3.38

packages/web/src/components/artist/ArtistCard.tsx
Stop propagation to prevent modal + popup from closing when clicking follow
=> Stop propagation on follow button in artist card

packages/web/src/components/sign-on/EnterPassword.tsx, packages/web/src/pages/sign-on/components/desktop/PasswordPage.js, packages/web/src/pages/sign-on/components/mobile/PasswordPage.tsx, packages/web/src/utils/commonPasswordCheck.ts, packages/web/src/utils/passwordListLazyLoader.ts
[C-556] 
* Add commonPasswordCheck function to handle api call and lazy load
* Update all component that use the passwordList to handle the async check
Any potential issues with the function now being async?
N/a
=> [C-556] Add commonPasswordCheck to lazy load the commonPasswordList

packages/web/package-lock.json, packages/web/src/common/models/Track.ts, packages/web/src/pages/track-page/TrackPageProvider.tsx, packages/web/src/services/audius-api-client/ResponseAdapter.ts, packages/web/src/services/audius-api-client/types.ts
Checks the is_available flag in addition to _blocked for content availability on the client.
Waiting to test against stage
Available content in production. Possible to instrument some addl amplitude charts, but probably not warranted at this time.
=> [CON-111] check is_available flag

packages/web/src/store/backend/sagas.js
Fix bad hydrateStoreFromCache import and use
n/a
local dapp against stage wasn't running prior. but now it is!
CI should pass too
=> Fix bad import and use

packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
Re: https://github.com/AudiusProject/docs.audius.org/pull/6#discussion_r894011297
=> Keep profile picture shape the same for legacy prof pics in Oauth response

packages/web/src/components/user-list-modal/components/UserListModal.tsx
=> Cherry pick Hotfix: comment out icons on modal titles

packages/stems/package-lock.json, packages/stems/package.json
- #1462 by Marcus Pasell
- #1460 by Dylan Jeffers
=> Bump stems to v0.3.39

packages/web/package-lock.json, packages/web/package.json
=> Consume Stems v0.3.39

packages/web/package-lock.json, packages/web/package.json
=> Consume stems v0.3.40

packages/mobile/src/screens/notifications-screen/NotificationList.tsx, packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx, packages/web/src/common/store/notifications/reducer.ts
1. <span> usage in mobile component
2. no padding after last notifications in the notifications list (in the case of no more notifs)
3. spinner on zero state
Local with simulator
Soaked + QA
=> [C-596] Fix small notifications bugs

packages/web/src/common/hooks/useFeatureFlag.ts, packages/web/src/common/store/ui/modals/slice.ts, packages/web/src/components/feature-flag-override-modal/FeatureFlagOverrideModal.module.css, packages/web/src/components/feature-flag-override-modal/FeatureFlagOverrideModal.tsx, packages/web/src/components/feature-flag-override-modal/index.ts, packages/web/src/hooks/useRemoteConfig.ts, packages/web/src/pages/Modals.tsx, packages/web/src/utils/zIndex.ts
* Add FeatureFlagOverrideModal (Opens with 'F' in dev mode) 
* Update the useFlag hook to respect the overrides
N/A
N/A
=> [C-558] Add FeatureFlagOverrideModal

packages/web/src/components/dev-mode-manager/DevModeManager.tsx, packages/web/src/pages/App.js
Update `enable-dev-mode` in localStorage based on `dev-mode` query param
N/A
N/A
=> C-599 Update dev-mode based on query param

packages/web/src/components/user-badges/TierExplainerModal.tsx
Changed DASHBOARD_PAGE to AUDIO_PAGE.
None
Tested manually on local web client.
=> [PAY-101] $AUDIO Modal for VIP tiers goes to wrong page

packages/mobile/src/components/twitter-button/TwitterButton.tsx, packages/mobile/src/screens/notifications-screen/Notifications/RemixCosignNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/RemixCreateNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TierChangeNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TipReactionNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TipSentNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TopSupporterNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TopSupportingNotification.tsx, packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx, packages/web/src/common/models/Analytics.ts
Adds tipping button for native tipping notifications
Still need to do desktop notifs! (we should be sure to use the existing pattern in RemixCosignNotification rather than the method done in native for now)
=> [PAY-279] Add tipping twitter button

packages/mobile/src/screens/tip-artist-screen/ConfirmSendTipScreen.tsx, packages/mobile/src/screens/tip-artist-screen/TipInput.tsx, packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
- fix app crash on non-numeric chars in tip input
- fix correct tip amount after going back and again forward during tipping flow
https://user-images.githubusercontent.com/9600175/175061483-b395978d-b14c-4b46-ae83-f79961aa82ca.mov
https://user-images.githubusercontent.com/9600175/175061524-3ac98541-6cd6-4ea6-8052-9487d7107392.mov
tipping flow on desktop and mobile should work accordingly
local mobile app against local stage dapp
n/a
=> [PAY-366][PAY-357] Fix more mobile QA issues

lerna.json, packages/mobile/package-lock.json, packages/mobile/package.json, packages/stems/package-lock.json, packages/stems/package.json, packages/web/package-lock.json, packages/web/package.json
Update stems to v1.1.10 and consume in web client.
Gets: #1499 
=> Stems: Upgrade to v1.1.10

packages/stems/package-lock.json, packages/stems/package.json
- #1507 by nicoback2 fix fill on arrow and download icons
=> Bump Stems to 1.1.11

package.json
Ran into an issue with a fresh install where following the readme caused an error because mookme wasn't installed. Adding a root level install to the init command
=> Add root npm install to init command

packages/web/src/components/user-list-modal/components/UserListModal.tsx
- Post launch, will look into adding icons to mobile userlist screens (tracked in linear)
Locally
=> [PAY-330] Add icons back to web userlist modals

packages/mobile/src/screens/notifications-screen/NotificationList.tsx, packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TipReactionNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx, packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx, packages/mobile/src/screens/notifications-screen/Reaction/ReactionList.tsx
- Only play reaction animations when the notification item is on screen.
- Sets Reaction autoplay to true for the Reaction notif
- Not a dragon, but a lot of prop drilling :( 
=> [PAY-378] [PAY-368] Address Reaction Perf

packages/web/src/pages/App.js, packages/web/src/root.tsx, packages/web/src/utils/route.ts
=> Fix redirect links

.circleci/src/jobs/@web-jobs.yml
https://discuss.circleci.com/t/xcode-image-deprecation/44294?mkt_tok=NDg1LVpNSC02MjYAAAGE6MeEggPLUM-i-bTcXMfA2ZTjvhtuQlX3L3UKSpmj0vFOZymLJ6iZjMzElf5CeHTEGAJL99zdsiNX_WDfu7k
=> Update deprecated xcode images

packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx
Further improves reaction perf by pausing animation when drawer is closed
=> [PAY-398] Improve reaction perf when drawer closed

packages/web/src/components/artist/ArtistChip.tsx
Removing other click handlers within ArtistChip as the call is handled by the parent div
Added saliou and piazza as assignees in case these were added to cover some specific case
N/A
N/A
=> [C-618] Remove unnecessary calls to onClickArtistName in ArtistChip to avoid multiple route changes

.circleci/src/commands/@web-commands.yml, .circleci/src/jobs/@web-jobs.yml
Add package.json and tar file to build for the web updates feature
Not sure if the string interpolation works like this in the yml file?
Tested out the commands individually in the terminal.
Will make sure that the s3 bucket has the correct files after this is merged
N/A
=> Add package.json and tar file to web-build ci command

.circleci/src/commands/@web-commands.yml
Forgot to add the tar file to the folder :/
N/A
N/A
N/A
N/A
=> Update build command to add build tar file to the build folder

packages/mobile/src/components/core/Screen.tsx, packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ProfileMutualsButton.tsx, packages/mobile/src/screens/user-list-screen/FavoritedScreen.tsx, packages/mobile/src/screens/user-list-screen/FollowersScreen.tsx, packages/mobile/src/screens/user-list-screen/FollowingScreen.tsx, packages/mobile/src/screens/user-list-screen/MutualsScreen.tsx, packages/mobile/src/screens/user-list-screen/RepostsScreen.tsx, packages/mobile/src/screens/user-list-screen/SupportingUsersScreen.tsx, packages/mobile/src/screens/user-list-screen/TopSupportersScreen.tsx, packages/mobile/src/screens/user-list-screen/UserListScreen.tsx, packages/mobile/src/screens/user-list-screen/UserListTitle.tsx
Adds v2 user-list headers which were missing for non-tipping user-lists
=> [PAY-397] Add v2 user-list headers

packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
We totally did not implement this
=> [C-601] Add missing mobile profile badges

packages/stems/package-lock.json, packages/web/package-lock.json, packages/web/package.json
For useMediaQueryListener
https://user-images.githubusercontent.com/9600175/177380340-2a07b704-c338-4963-8a5e-8eb0f5fc1abb.mp4
na
n/a
na
=> Consume stems 1.1.12 in web

packages/stems/src/components/Popup/Popup.module.css
Small z-index update on the popup wrapper to fix
N/A
N/A
N/A
N/A
=> [C-656] Fix z-index for collection header overflow menu popup

packages/web/src/components/data-entry/DropdownInput.module.css
Small ui fixes for dropdown menu background color and item text color
N/A
N/A
N/A
=> [C-650] Update dropdown input styles for dark mode

.circleci/src/commands/@web-commands.yml, .circleci/src/jobs/@web-jobs.yml, .circleci/src/workflows/web.yml, package-lock.json, packages/web/package-lock.json
Replaces cp inside build step with s3 cp to move tar file over to s3.
Staging CI run:
=> Move CP of tar file to s3 step

packages/stems/package-lock.json, packages/stems/package.json, packages/stems/src/components/Modal/Modal.tsx, packages/stems/src/components/Modal/types.ts, packages/web/src/components/share-modal/ShareModal.tsx, packages/web/src/components/share-modal/components/ShareDialog.module.css, packages/web/src/components/share-modal/components/ShareDialog.tsx, packages/web/src/components/share-modal/types.ts, packages/web/src/pages/App.js, packages/web/src/pages/modals/AppModal.tsx, packages/web/src/pages/modals/Modals.tsx, packages/web/src/pages/modals/useModalState.ts
Improves web modal usage by rendering modals on demand, and removing them from dom on close.
- Example revamp done for `ShareModal`
=> [C-654] Improve web modal usage and performance

packages/stems/src/components/Popup/Popup.tsx, packages/web/src/components/loading-spinner/LoadingSpinner.tsx, packages/web/src/components/upload/UploadArtwork.js, packages/web/src/components/upload/UploadArtwork.module.css
Improves upload flow a11y, helpful for probers
=> [C-581] Improve probers upload flow a11y

packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx, packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx, packages/mobile/src/screens/signon/SignOn.tsx
Fixes type error where fetch referrer can be string[], coercing to string
also removes explicit .js reference
=> Fix various mobile types

packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx, packages/mobile/src/screens/profile-screen/CollectiblesCard.tsx, packages/mobile/src/screens/profile-screen/CollectiblesTab.tsx, packages/mobile/src/screens/signon/SignOn.tsx, packages/web/src/components/collectibles/components/CollectibleDetails.tsx, packages/web/src/components/collectibles/components/CollectiblesPage.module.css
Adds chain icons to collectibles cards
=> [C-565] Add chain icon to collectibles card

packages/web/package-lock.json, packages/web/package.json
Fixed per
https://github.com/electron-userland/electron-builder/issues/6726
Diffed the breaking changes in the changelog and all looks fine.
CI test run, downloaded staging app. We good!
=> [C-667] Fix desktop build on mac

packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx, packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx, packages/mobile/src/screens/notifications-screen/content/ChallengeReward.tsx, packages/mobile/src/utils/challenges.tsx, packages/web/src/common/models/AudioRewards.ts, packages/web/src/common/services/remote-config/defaults.ts, packages/web/src/components/nav/desktop/NavAudio.tsx, packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx, packages/web/src/pages/audio-rewards-page/config.tsx
Created web and mobile UIs for first playlist challenge.
N/A
Ran local web client, mobile-web client, and IOS simulator and visually confirmed.
https://user-images.githubusercontent.com/3893871/178081385-53e04f65-20d0-41a4-aed6-fa98855ed9fa.mp4
=> [PAY-386] [PAY-387] Created Mobile + Web UIs for First Playlist Challenge

packages/web/.hooks/pre-commit.json
Noticed that the lint step was also doing stylelint
=> Remove extra stylelint step in pre-commit

packages/mobile/src/store/oauth/actions.ts, packages/web/src/common/store/account/reducer.ts, packages/web/src/pages/sign-on/SignOnProvider.tsx, packages/web/src/pages/sign-on/components/desktop/SignOnPage.tsx, packages/web/src/pages/sign-on/components/mobile/ProfilePage.tsx, packages/web/src/pages/sign-on/components/mobile/SignOnPage.tsx, packages/web/src/pages/sign-on/store/actions.ts
Fixes sign-on types introduced when sign-on actions was migrated to typescript
=> Fix sign-on action types

packages/mobile/src/screens/notifications-screen/Notifications/TipReactionNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TipSentNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TopSupporterNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TopSupportingNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/useGoToProfile.ts, packages/web/src/components/notification/Notification/TipReactionNotification.tsx, packages/web/src/components/notification/Notification/TipReceivedNotification.tsx, packages/web/src/components/notification/Notification/TipSentNotification.tsx, packages/web/src/components/notification/Notification/TopSupporterNotification.tsx, packages/web/src/components/notification/Notification/TopSupportingNotification.tsx, packages/web/src/components/notification/Notification/useGoToProfile.ts
Clicking/pressing on tipping notifications navigates user to profile page
=> [PAY-415] Clicking tipping notifications goes to profile

packages/web/src/services/web3-modal/index.ts, packages/web/src/store/token-dashboard/sagas.ts
Add types for PhantomProvider on the window object
=> Fix solana phantom provider types

packages/web/src/common/store/ui/reactions/sagas.ts
We were mistakenly defaulting to 'heart' for instances where the reaction was unsent, and represented with 0.
None
Tested on stage
=> [PAY-414] Fix unsending reactions

packages/mobile/src/screens/notifications-screen/Notification/EntityLink.tsx, packages/mobile/src/screens/notifications-screen/Notification/utils.ts, packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx, packages/mobile/src/screens/notifications-screen/content/AddTrackToPlaylist.tsx, packages/mobile/src/screens/notifications-screen/content/TwitterShare.tsx, packages/web/src/common/store/notifications/types.ts
Fixes native milestone notification, to ensure user is avail for Followers achievement, and entity is available for the rest
=> Fix native milestone notification

packages/web/src/components/notification/Notification/AddTrackToPlaylistNotification.tsx, packages/web/src/components/notification/Notification/components/EntityLink.tsx, packages/web/src/components/notification/Notification/utils.ts, packages/web/src/services/web3-modal/index.ts, packages/web/src/store/token-dashboard/sagas.ts
Fixes entity type issues introduced with mobile changes, and solana type issues.
=> Fix entity and solana types in web

packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingList.tsx, packages/mobile/src/screens/profile-screen/ProfileHeaderV2/SupportingTile.tsx
This animation was too aggressive - scaling down to default 0.97 looks bad for large tiles.
None
Device
=> [PAY-393] Fix active state animation on mobile SupportingTile

packages/stems/src/components/TokenValueInput/TokenValueInput.module.css, packages/stems/src/components/TokenValueInput/TokenValueInput.tsx, packages/web/src/components/tipping/tip-audio/TipAudio.module.css, packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
Fixes various matrix mode styles for send-tip flow in web
=> [PAY-423] Fix matrix-mode send-tip web styles

packages/mobile/src/screens/user-list-screen/UserListScreen.tsx
Removes search icon in user-lists, since it makes it look like the user-list is searchable
=> [PAY-424] Remove search icon in user-lists

.circleci/src/jobs/@web-jobs.yml
`serve` got a major version update so the path we were referencing no longer existed. Opted to use `npx` to keep breaking changes from preventing it from running
=> [C-679] Fix Probers

packages/common/package.json, packages/web/src/components/notification/Notification/components/icons.module.css
Fixes notification icon color for matrix mode by fixing css hierarchy
=> [PAY-422] Fix tip icon notification matrix color

package-lock.json, packages/mobile/src/store/search/types.ts, packages/web/src/common/models/User.ts, packages/web/src/common/store/account/selectors.ts, packages/web/src/common/store/cache/users/sagas.js, packages/web/src/components/artist/ArtistCard.tsx, packages/web/src/components/menu/CollectionMenu.tsx, packages/web/src/components/nav/desktop/NavPopupMenu.tsx, packages/web/src/components/service-selection/store/sagas.ts, packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx, packages/web/src/components/track/helpers.ts, packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx, packages/web/src/pages/profile-page/ProfilePageProvider.tsx, packages/web/src/pages/profile-page/sagas.js, packages/web/src/pages/settings-page/SettingsPageProvider.tsx, packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx, packages/web/src/pages/sign-on/components/mobile/PasswordPage.tsx, packages/web/src/pages/upload-page/components/FinishPage.js, packages/web/src/pages/upload-page/store/sagas.js, packages/web/src/schemas/index.js, packages/web/src/services/AudiusBackend.js, packages/web/src/services/audius-api-client/types.ts, packages/web/src/store/account/sagas.js
Remove is_creator usage in client.
https://github.com/AudiusProject/audius-protocol/pull/3475
Local stack, local client, linked sdk
- make account
- view profile without tracks
- upload track (no 1% stickiness)
- view track
- view profile
- upload second track
- update profile
- sign out / sign in
- view artist dashboard
- view cnode selection modal in settings
=> [PLAT-254] Remove is_creator usage

packages/web/src/pages/smart-collection/store/sagas.ts, packages/web/src/services/audius-backend/Explore.ts
This reverts commit 91d638ca5837914b72639bdfd199033e866d500a.
Relies on discovery node v62 being fully rolled out
=> Revert "Update explore endpoints in libs to use v1 (#1539)"

packages/web/package-lock.json, packages/web/package.json, packages/web/src/components/notification/NotificationModal.module.css, packages/web/src/components/notification/NotificationModal.tsx, packages/web/src/components/notification/NotificationPanel.module.css, packages/web/src/components/service-selection/ServiceSelectionModal.js, packages/web/src/components/service-selection/ServiceSelectionModal.module.css, packages/web/src/components/track/desktop/ConnectedPlaylistTile.module.css, packages/web/src/components/track/desktop/PlaylistTile.tsx, packages/web/src/components/track/desktop/TrackListItem.module.css, packages/web/src/index.css, packages/web/src/pages/audio-rewards-page/components/ErrorBody.module.css, packages/web/src/pages/audio-rewards-page/components/ErrorBody.tsx, packages/web/src/pages/sign-on/components/desktop/FollowPage.module.css, packages/web/src/pages/sign-on/components/desktop/FollowPage.tsx, packages/web/src/pages/sign-on/components/desktop/SignOn.module.css, packages/web/src/pages/trending-page/components/desktop/GenreSelectionModal.module.css, packages/web/src/pages/trending-page/components/desktop/GenreSelectionModal.tsx, packages/web/src/pages/upload-page/components/TracksPreview.js, packages/web/src/pages/upload-page/components/TracksPreview.module.css, packages/web/src/types/simplebar-react/index.d.ts
Bye
Very few css changes necessary
=> [C-411] Remove simplebar

packages/web/src/components/track/desktop/stats/ProfileImage.module.css, packages/web/src/components/track/desktop/stats/ProfileImage.tsx
=> [C-697] Set border radius on TrackTile stats profile picture skeleton

packages/mobile/ios/AudiusReactNative/Info.plist
Auto increment failing again. Seems like there is some delay on apple's side on updating their api to reflect the latest version
Will cherry pick onto release
=> Bump ios version

packages/web/src/common/store/cache/reducer.js
Always prefer truthy verified status
Locally vs. prod (/mattox)
=> Prefer verified always

packages/mobile/ios/AudiusReactNative/Info.plist
Same as https://github.com/AudiusProject/audius-client/pull/1612/files
To get https://github.com/AudiusProject/audius-client/pull/1614
=> Bump iOS 1.1.22

packages/mobile/src/components/overflow-menu-drawer/CollectionOverflowMenuDrawer.tsx, packages/mobile/src/screens/collection-screen/CollectionScreen.tsx, packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx, packages/mobile/src/store/search/types.ts
* Fix publishing of playlists with temp ids
* Update header text to indicate to the user that the playlist is being published
N/A
N/A
N/A
=> [C-635] Fix mobile publishing and add ui to indicate publishing to the user

packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css
Fix style for tippers in feed tip tile
n/a
local against prod
n/a
=> Fix style for tippers in feed tip tile

packages/mobile/android/app/src/main/AndroidManifest.xml
Modify android manifest to allow canOpenUrl to correctly return true when opening a social app that is already installed (twitter, ig, etc)
=> [C-702] Fix canOpenUrl on android

packages/web/src/pages/profile-page/sagas.js
Ensures logged out users can still see top supporters for artists
=> [PAY-446] Show top supporters for logged out users

packages/mobile/src/screens/profile-screen/ProfileHeaderV2/ExpandedSection.tsx
Prevent mutuals tile from showing on owners profile
=> [PAY-450] Dont show mutuals on owner's profile

packages/mobile/src/components/feed-tip-tile/SenderDetails.tsx
Replaces opacity with underline for feed-tip-tile sender styles
=> [PAY-453] Update feed-tip-tile sender styles

packages/mobile/src/screens/app-screen/AppScreen.tsx, packages/mobile/src/screens/audio-screen/AudioScreen.tsx, packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx
Fetches $AUDIO balance when navigating to audio/tip-screens, and when returning to app with one of these screens open
=> [PAY-452] Fetch audio balance on audio/tip-screen

packages/mobile/src/components/feed-tip-tile/PressableText.tsx, packages/mobile/src/components/feed-tip-tile/ReceiverDetails.tsx, packages/mobile/src/components/feed-tip-tile/SenderDetails.tsx
Removes opacity from feed-tip-tile receiver text
=> Fix feed-tip-tile receiver opacity

packages/mobile/src/components/feed-tip-tile/ReceiverDetails.tsx, packages/mobile/src/components/feed-tip-tile/SenderDetails.tsx, packages/web/src/components/menu/CollectionMenu.tsx
Fixes lint on mobile based on tipping fixes. It appears or pre-push hooks are not working for mobile
=> Fix mobile lint based on tipping fixes

packages/mobile/ios/AudiusReactNative/Info.plist
=> Bump ios to 1.1.23

packages/mobile/src/screens/tip-artist-screen/SendTipStatusText.tsx, packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx, packages/web/src/pages/audio-rewards-page/components/MigrationModalBody.tsx
Maintenance was spelled wrong.
=> Web/Mobile: Fix "maintenance" typo

packages/web/public/index.html
In response to:
Nothing obvious broke due to removing this
=> Remove recaptcha

packages/web/src/components/tracks-table/TableDragHandle.js, packages/web/src/components/tracks-table/TableDragHandle.module.css, packages/web/src/components/tracks-table/TableFavoriteButton.js, packages/web/src/components/tracks-table/TracksTable.module.css
Small fixes for matrix mode on web
N/A
manually tested
N/A
N/A
=> [C-687] Update some colors and styles for matrix mode

packages/web/src/pages/sign-on/store/sagas.js
Fixes issue where some devices appear to receive status code 0 when they are rate limited
=> Fix rate limit issue with sign-up on some devices

packages/web/src/components/tracks-table/TracksTable.module.css
Small updates to fix the look for sorted columns in dark and matrix mode
=> [C-708] Fix the table styles for sorted columns for dark mode and matrix mode

packages/mobile/src/screens/audio-screen/AudioScreen.tsx
Native audio tiers where showing current tier silver and gold
=> [C-709] Fix native audio tier

packages/web/src/components/notification/Notification/FavoriteNotification.tsx, packages/web/src/components/notification/Notification/FollowNotification.tsx, packages/web/src/components/notification/Notification/RepostNotification.tsx, packages/web/src/components/notification/Notification/components/OthersLink.module.css, packages/web/src/components/notification/Notification/components/OthersLink.tsx, packages/web/src/components/notification/Notification/utils.ts
- Add others link to web notifications to highlight there are more people
- Also fixes favorite notification text that said repost
=> [C-584] Add others link to web notifications

packages/web/src/components/notification/Notification/utils.ts, packages/web/src/components/notification/store/sagas.ts
Fixes bug where we are dispatching an uncalled action, which throws an error, breaking us out of the fetchNotification flow.
=> [C-721] Fix notifications not loading past 20

packages/web/src/components/search/SearchBarResult.js, packages/web/src/components/search/SearchBarResult.module.css
Small update to make the searchbar results that are users have a round skeleton instead of a square one
=> Small update to the styling of user searchbar result skeletons

packages/stems/package-lock.json, packages/stems/package.json, packages/web/package-lock.json, packages/web/package.json
For the changes here: https://github.com/AudiusProject/audius-client/pull/1653
n/a
ran local dapp v stage
n/a
none
=> Consume stems 1.1.14 in web

packages/web/src/components/artist/ArtistCardCover.module.css, packages/web/src/components/artist/ArtistCardCover.tsx
Small update to fix a skeleton that was square that Ray found
=> Update artist popover profile picture skeleton to be round

packages/web/package-lock.json, packages/web/package.json
=> Bump libs to 0.0.22 in client

packages/web/src/pages/PublicSite.tsx
Before: landing page hamburger menu on narrow width did not open
After: issue is fixed
=> [C-733] Fix mobile menu on narrow

packages/stems/src/components/Modal/ModalContentPages.module.css, packages/stems/src/components/Modal/ModalContentPages.stories.tsx, packages/stems/src/components/Modal/ModalContentPages.tsx, packages/stems/src/components/Modal/index.ts
(low pri)
Inspired by the tipping modal, adds a new type of `ModalContent` that is paginated and swipe animates.
Using storybook
=> Add ModalContentPages to stems

packages/web/scripts/configureLocalEnv.js
Fix local config for entity manager address.
=> Fix local env entity manager address

packages/mobile/tsconfig.json, packages/web/src/services/AudiusBackend.ts, packages/web/src/services/web3-modal/index.ts, packages/web/src/store/account/mobileSagas.ts, packages/web/src/store/token-dashboard/sagas.ts
=> Fix typecheck for mobile after AudiusBackend ts migration

.circleci/src/jobs/@web-jobs.yml, packages/web/.hooks/pre-push.json, packages/web/src/services/web3-modal/index.ts, packages/web/src/types/images/images.d.ts
Adds typecheck step to web ci. 
Needed to add images.d.ts declaration file because ci isn't picking up react-app.d.ts for some reason, while it does work on local. Not sure yet what's going on there
=> [C-794] Add typecheck to web ci

packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx
Show playlists count if tracks count is zero in native
=> [C-804] Show playlist count for non-artists in native

packages/mobile/src/components/collectible-details-drawer/CollectibleDetailsDrawer.tsx, packages/mobile/src/screens/profile-screen/CollectiblesCard.tsx, packages/web/src/components/collectibles/components/CollectibleDetails.tsx, packages/web/src/components/collectibles/components/CollectiblesPage.module.css, packages/web/src/services/audius-backend/audius-backend-instance.ts
Removes stamp and positions chain icon to the left
=> [C-798] Remove owned/created stamp from collectible tile

packages/web/src/components/card/desktop/Card.module.css
Fix artifact over badge count. This was probably necessary for old cascaders, but is fine w/o.
Tested against prod search & also went thru all of the other <Card usages, which there are no size=small anyway besides search
=> [C-805] Fix artifact on small card

packages/web/package.json
=> Add extends null to fix electron build

packages/mobile/package-lock.json, packages/mobile/package.json, packages/web/package-lock.json, packages/web/src/common/store/reducers.ts, packages/web/src/store/sagas.ts
Fixes type issue in mobile since the sdk version is off.
Also removes the buyAudio slice and sagas from the store for now since the jupiter package is quite large, causing cloudflare upload to fail
=> Fix typecheck with updated sdk version

packages/web/src/components/actions-tab/ActionsTab.js, packages/web/src/components/card/desktop/Card.module.css, packages/web/src/components/nav/desktop/NavColumn.tsx, packages/web/src/components/tooltip/Tooltip.tsx, packages/web/src/components/tooltip/types.ts
Fixes alignment -- chatted w/ design about top placement
=> [C-767] Fix tooltip on cards and new playlist

packages/web/src/components/search-bar/store/sagas.js
Fixes search bar error due to missing audiusBackendInstance in getBlocklist call
=> Fix missing audiusBackendInstance in search-bar saga

packages/mobile/src/store/sagas.ts, packages/mobile/src/store/store.ts
Removes common sagas from native to ensure best mobile performance as we develop reloaded.
=> Remove common sagas from native

packages/mobile/src/store/store.ts
Readding the native store context since it improves optimizely import resolutions
=> Re-add native store context to fix optimizely import resolution

packages/web/src/store/tipping/sagas.ts, packages/web/src/store/token-dashboard/sagas.ts, packages/web/src/store/wallet/sagas.ts
Fixes wallet-client usages, using redux-saga context arrays
=> Fix wallet-client usages

packages/eslint-config-audius/src/index.js, packages/web/src/common/store/cache/collections/sagas.js
Re-adds no-undef eslint rule
Fixes issues across repo
=> Fix no-undef, add rule back to eslint-config

packages/mobile/src/screens/profile-screen/ProfileHeader/Bio.tsx, packages/mobile/src/screens/profile-screen/ProfileHeader/CollapsedSection.tsx, packages/mobile/src/screens/profile-screen/ProfileHeader/ExpandedSection.tsx, packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
conditions to show see more on mobile profile:
- has a badge tier
- has mutuals
- is supporting (has tipped) other users
- has socials
- has long bio description
nah
local mobile against local dapp against stage
n/a
none
=> [Pay-516] Show see more only if profile header should be expansible on mobile.

packages/mobile/ios/AudiusReactNative/Info.plist
=> Bump ios version to 1.1.28

packages/mobile/src/screens/notifications-screen/Notifications/SupporterDethronedNotification.tsx, packages/web/src/components/notification/Notification/SupporterDethronedNotification.tsx
Twitter text starting with a username doesn't show up in the feed - this fixes that. Also lowercases some text.
=> Fix dethroned Twitter share copy

package-lock.json, packages/mobile/package-lock.json, packages/mobile/package.json, packages/mobile/src/services/audius-api-client/apiClient.ts, packages/web/package-lock.json, packages/web/package.json
=> Update @audius/sdk to 0.0.37

packages/mobile/src/App.tsx, packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
Need to enable an experimental flag for LayoutAnimation to work on Android: https://reactnative.dev/docs/layoutanimation
Tested on Android hardware
=> [PAY-564] Enable LayoutAnimation on android for profile screen
